### ISSUE TITLE
Implement sticky windows

### ISSUE THREAD

**Issue by stapelberg** [i3/i3#11]
When using the appropriate EWMH-hint, windows should appear on all workspaces. This is a bit tricky since a client can only be in one container and we need to store position inside each container.

**Comment by Airblader** [comment]
@stapelberg I'm not convinced we should implement this. It seems like it'd be an insane effort and even then it would probably not be what the user expects. #1856 would at least do this for floating windows. For tiling containers I think the "sticky groups" concept is more feasible.

What do you think?

@acrisci Out of curiosity, do you still have that patch that got rejected? Or at least, how did you deal with container positioning?

**Comment by acrisci** [comment]
@Airblader here: http://cr.i3wm.org/patch/540/

**Comment by Airblader** [comment]
Ah, I see, thanks. So Michael had the same concern I just asked him about. I feel like we should close this issue. EWMH sticky for floating + sticky groups should be all we need. @stapelberg Agreed?

**Comment by stapelberg** [comment]
> I'm not convinced we should implement this. It seems like it'd be an insane effort and even then it would probably not be what the user expects. #1856 would at least do this for floating windows. For tiling containers I think the "sticky groups" concept is more feasible.

Not sure what you are referring to with “this”. This issue (#11) is about sticky groups for tiling containers, at least that’s how I meant it. I realize in the first post I’m talking about EWMH hints, but I’m not 100% sure if it makes sense to hook up EWMH hints to sticky groups. If that’s what you meant, I agree.

**Comment by Airblader** [comment]
@stapelberg Then #1758 would just be a duplicate of this, right? I'd still close this original issue since #1758 doesn't have the confusing discussion baggage and you described the desired concept there clearly.

**Comment by stapelberg** [comment]
Agreed.

**Comment by Airblader** [comment]
Sticky tiling windows are now possible by using the `swap` command. See https://github.com/Airblader/i3-sticky for an example implementation (which can surely be improved upon).

> I can't understand why this useful feature is not implemented.

If no one writes the patch, it's not implemented. Pretty simple to understand. I think needing this to »live« is a vast exaggeration.
