### ISSUE TITLE
enhancement: notify users when commands fail

### ISSUE THREAD

**Issue by acrisci** [i3/i3#1470]
When executing a command with `exec` command or config directive, notify the user when the command exits with non-zero status through the session notification daemon.

**Comment by stapelberg** [comment]
I think this should just be `exec $command || notify-send $command exited` in the default config.

**Comment by acrisci** [comment]
I don't see a case where the user wouldn't want to be notified of command failure except where the user is adverse to any notifications at all, in which case they can not use a notification daemon. Otherwise, we could provide a config directive to turn i3 notifications off.

When a user presses a key that they know to be bound to an action, they expect for that action to happen. If that action doesn't happen, that can cause confusion or lead to mistakes in further actions based on the assumption that the binding executed the command successfully.

A common source of confusion is when a command given in a binding or for_window directive has a syntax or token error. Right now, these errors are silently ignored, which I think is a problem. A notification can alert the user of what exactly has gone wrong in the command so they can fix it.

Another common problem may occur on startup with exec directives. There, the stderr can be displayed to the user when a process fails to load because of some problem with the script. This makes it easier to reliably use the exec directive to start applications in the background.

**Comment by stapelberg** [comment]
> When a user presses a key that they know to be bound to an action, they expect for that action to happen. If that action doesn't happen, that can cause confusion or lead to mistakes in further actions based on the assumption that the binding executed the command successfully.

Agreed.

> A common source of confusion is when a command given in a binding or for_window directive has a syntax or token error. Right now, these errors are silently ignored, which I think is a problem.

No. We actually pop up a nagbar when there is a parser error in a configured binding: https://github.com/i3/i3/blob/next/src/bindings.c#L440

As for `for_window`, people need to check the log. I don’t think popping up nagbar is a good idea in that case because there is no direct action that could result in nagbar as a reaction, i.e. the user did not just press a button which is directly handled by i3. Therefore, I think such a popup would be rather annoying.

> Another common problem may occur on startup with exec directives. There, the stderr can be displayed to the user when a process fails to load because of some problem with the script. This makes it easier to reliably use the exec directive to start applications in the background.

That’s a good idea in theory, but in practice far too many apps flood stderr with warnings and other messages that even the devs of that application never look at and just take as given. We shouldn’t use that and push it into the user’s face.

**Comment by acrisci** [comment]
What about notifying the user of the name of the command and the exit code when the command fails?

No new dependencies would be required to do this if we try to send the notification over d-bus using GLib.

**Comment by stapelberg** [comment]
> What about notifying the user of the name of the command and the exit code when the command fails?
> 
> No new dependencies would be required to do this if we try to send the notification over d-bus using GLib.

That’s precisely what my earlier suggestion (`exec $command || notify-send $command exited`) does, isn’t it?
