### ISSUE TITLE
configure statusline separator

### ISSUE THREAD

**Issue by acrisci** [i3/i3#1472]
Right now, the statusline is drawn as a line with the X drawing api. It should be a character (such as "|") which the user can configure. Then people can use little circles or diamonds or something.

**Comment by stapelberg** [comment]
That would change the look & feel and consume more screen space. People can already turn off the built-in separator and just draw their own. How is yet another way of achieving the same thing any better?

**Comment by acrisci** [comment]
It removes code duplication across the statusline generators and provides a common way to accomplish this, such as within the header.

Right now, you have to append the separator to `full_text` and use markup to make it the right color, or maybe add blocks between all the blocks with the `color` set appropriately. This requires an ipc connection to find out what color is set for the separator in the bar config.

You could probably do it in such a way where the look and feel is not changed by only rendering it as a character if the option is given.

**Comment by stapelberg** [comment]
If it doesn’t change behavior, I think that’d be okay. Can you send a pull request for that?

**Comment by Airblader** [comment]
I'll start working on this unless Tony already did.

**Comment by acrisci** [comment]
@Airblader go ahead.
