### ISSUE TITLE
enhancement: use new RFC 7464 JSON sequencing in i3bar protocol

### ISSUE THREAD

**Issue by ortolot** [i3/i3#1493]
The current i3bar protocol uses a flow that is represented as an infinite, never-ending table. This is the current way to implement that common need, but since it was not entirely satisfactory, there is a new RFC 7464 that defines a standard way to represent JSON sequences, which are basically a series of JSON objects separated by specific delimiters:
    https://tools.ietf.org/html/rfc7464

I would be a nice thing to use it for a new version of the i3bar protocol. It may or may not require en enhancement of libyajl, as the JSON sequencing could for instance be considered as an external envelope, parsed without libyajl, before passing the JSON objects it contains to libyajl.

**Comment by Airblader** [comment]
What exactly are shortcomings that affect i3bar?

**Comment by ortolot** [comment]
Ingo Bürk, 2015-02-26 03:49-0800:
>What exactly are shortcomings that affect i3bar?

No real shortcomings, it is just that the need (a flow of JSON objects) 
is currently implemented in a kludgy way, and that there is now a 
standard way to do that.

Now, since it is using JSON, which is a standard, instead of some 
specific format, it would be nice to use the standard way for 
serializing flow of JSON objects rather than the current way.

**Comment by Airblader** [comment]
The question is whether this ever so little benefit is worth breaking basically all scripts and tools that have been built around the protocol. :/

**Comment by ortolot** [comment]
Ingo Bürk, 2015-03-02 08:59-0800:
>The question is whether this ever so little benefit is worth breaking basically all scripts and tools that have been built around the protocol. :/

Probably not. It could be just a possibility, however, that is, i3bar 
accepting that format as well as the never-ending table.

Or it could be kept in mind if one day there is a need for a new version 
of the protocol.

**Comment by Airblader** [comment]
I don't think maintaining two protocols is worth it either since there isn't really any benefit. 

The future — sure, if i3 was to start all over again with the protocol or if there was a good point in time to do so, why not. But it's not my project anyway. Maybe Michael favors the idea of the standard. Just my two cents. :)

**Comment by Airblader** [comment]
By the way, the protocol *does* have a version field already. So it would definitely be possible to have them coexist right now.

**Comment by ortolot** [comment]
Ingo Bürk, 2015-03-02 09:07-0800:
>By the way, the protocol *does* have a version field already. So it would definitely be possible to have them coexist right now.

I know it was, and this was my original suggestion, to create a new 
version of the protocol.

Now, another possibility would be to keep the current version while 
adapting i3bar so it can take both formats, making them two version of 
the updated current version of the protocol, if that makes any senses.

But anyway, the main reason I created that enhancement request is that 
is it just that, a suggestion to keep in mind, as that new RFC was just 
made for that kind of case, streamed JSON elements. No real need to 
change anything now, just knowing it exist and could be used if there is 
an occasion to change or update the protocol is good enough!

**Comment by stapelberg** [comment]
Just going through issues currently, and I don’t think this one is actionable, hence closing.
