### ISSUE TITLE
Games disappearing when switching workspaces

### ISSUE THREAD

**Issue by pfent** [i3/i3#1516]
Running i3 version 4.9 on x86_64 Archlinux.
When running a fullscreen game and switching workspaces the window containing the game disappears with the containing workspace being destroyed. The game continues to run until manually killed.
This happens for me with several Steam games (Dota 2, Civilization V etc.) and with xonotic-sdl (although xonotic-glx works fine)

This behaviour is not present in i3 version 4.8

relevant log starts @ 14:49:26:
http://logs.i3wm.org/logs/5147289865682944.bz2
i3 version 4.9 (2015-02-28, branch "tags/4.9")

**Comment by Airblader** [comment]
> relevant log starts @ 14:59:26:

Did you mean 14:**4**9:26?

**Comment by pfent** [comment]
Indeed. Sorry for the typo

**Comment by acrisci** [comment]
Put this in your shell rc file:

    export SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0

I think we may need to reevaluate the iconic state request for this reason.

**Comment by licaon-kter** [comment]
@pfent: SDL issue see this too: https://github.com/i3/i3/pull/1457#issuecomment-76618057

**Comment by pfent** [comment]
The shell rc export works for xonotic-sdl
dota_linux and Civ5 still get lost.

Since Dota 2 is a Source game I suspect a lot of other Valve games are also affected...

**Comment by licaon-kter** [comment]
I have a *.xsession* script to start **i3** and putting an **export SDL_...** there does the job.

**Comment by stapelberg** [comment]
@acrisci Can you come up with a fix for this until this weekend? Otherwise I’m inclined to just revert the commit introducing iconic state handling for the 4.9.1 release.

**Comment by acrisci** [comment]
There is no fix for this. I think it's a good idea to revert it. I'll do a pull request today or tomorrow.

**Comment by rainerborene** [comment]
> had to put the SDL export in the Steam game launch options

@pfent how did you do that?

**Comment by licaon-kter** [comment]
@rainerborene: right-click on the game -> ( last option down ) Advanced -> ( press the button under the overlay checkbox ) Set start command line -> write: 

> SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 %command%

*%command%* will be automatically replaced by Steam with the game EXE, this needs to be like this.

This might not work for games that use a launcher ( eg. Witcher 2 ), so you can rename the launcher, and soft-link the main EXE to the launcher so that Steam starts the game directly.

**Comment by licaon-kter** [comment]
I can confirm that it works, it would be perfect if the window would still be fullscreen and not end up floating on workspace switch back.

**Comment by stapelberg** [comment]
That’s up to SDL, nothing we can do about that, I think.

**Comment by rainerborene** [comment]
> That’s up to SDL, nothing we can do about that, I think.

What do you mean by SDL? Setting `SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS` environment variable would solve that problem?

**Comment by licaon-kter** [comment]
Yes it does and I'll just stick that back on my *~/.xinitrc* anyway.
