### ISSUE TITLE
feature request: scrolling over i3bar blocks should generate click events instead of switching workspace 

### ISSUE THREAD

**Issue by nonchip** [i3/i3#1550]
there should be the possibility (=config option) to make i3bar not switch the workspace but instead generate click events when scrolling while hovering an i3bar-json-block, for example for volume control/etc.

i'll implement&pullrequest this if you agree.

**Comment by Airblader** [comment]
This already exists.

**Comment by nonchip** [comment]
i did, but it still scrolls through workspaces. since when does this exist?

**Comment by Airblader** [comment]
I don't know what release introduced this, but it was a while ago. At the very least since 4.8, but probably sooner than that.

**Comment by nonchip** [comment]
well, i just rebuilt from master and tested, it still doesn't do that

Binary i3 version:  4.9.1-55-gcd48bcf (2015-03-14, branch "next") © 2009-2014 Michael Stapelberg and contributors
Running i3 version: 4.9.1-55-gcd48bcf (2015-03-14, branch "next") (pid 2315)

**Comment by nonchip** [comment]
oops, nvm, just realized i'm still running plain i3status on this host, migrating to my i3cat setup (that utilizes click events) in a minute and retrying

**Comment by Airblader** [comment]
Can you post the script that generates your JSON as well as some example JSON?

**Comment by nonchip** [comment]
ok, now it works. seems I'm still using 4.7 on the other host (I don't have access to right now) then.
