### ISSUE TITLE
[enhancement] sep_block_width for all blocks

### ISSUE THREAD

**Issue by Airblader** [i3/i3#1586]
#1578 likely requires the user to change the `sep_block_width` which currently has to be done on each individual block. If not specified, there is a default value, which is currently hardcoded.

Can we add a config directive to the bar config that sets this default value?

**Comment by stapelberg** [comment]
I’d like to avoid blowing up the config file. Why is it infeasible to set this on every block? Should be a simple change in your status line generator of choice, right?

**Comment by Airblader** [comment]
Sure. Just asking and documenting.

However, how about adding the separator text width to the default value for blocks that don't set a sep_block_width on their own? 

It'd be completely internal and the user only has to change the width themselves if they explicitly want a different value. I probably should've done this in the PR right away.

**Comment by acrisci** [comment]
I think that the statusline related things should go into the statusline config.
