### ISSUE TITLE
enhancement: accept list of outputs in workspace output assignment

### ISSUE THREAD

**Issue by acrisci** [i3/i3#1612]
Config directives of type `workspace [n] output [output]` should accept a list of outputs.

Example:

    workspace 1 output HDMI-0 DVI-D-0

The first output that exists and is suitable for the assignment will be the effective output this workspace will be assigned to.

Whenever the first output is turned off or disconnected, the second output will take over the assignment.

This would make the config more portable across machine or drivers that name outputs differently.

**Comment by Airblader** [comment]
This is a duplicate of #555

**Comment by acrisci** [comment]
Oh ok I didn't read that one all the way through to see what the enhancement became.
