### ISSUE TITLE
Crash when a floating window is tiled while being resized via mouse

### ISSUE THREAD

**Issue by Deiz** [i3/i3#1627]
Ran into this while testing yesterday and managed to reproduce it on current next.

I'm able to fairly reliably reproduce this by doing the following:
1. Open a floating window
2. Begin resizing the floating window (titlebar right-click seems most reliable)
3. Disable floating on the window

Note that this sometimes crashes X itself for me, so it's probably wise to test on a second X server.

I've [pastebinned a backtrace](http://pastie.org/private/ocp4p0juf0uagfovpqft4q) which seems to imply there's a race going on. 0x1de5ed0 (the floating container) is closed at line 1173 in the log, but then con_inside_floating() for the just-tiled window still returns it later, which leads to the segfault.

http://logs.i3wm.org/logs/5154321532452864.bz2
i3 version 4.10.1-47-g3b81e40 (2015-04-01, branch "next")

**Comment by Airblader** [comment]
(The things some people test *laughs*)

**Comment by Deiz** [comment]
It seems my steps are slightly incorrect. You actually need to start with one tiled window and one floating window.

As a bonus, it seems that this also often results in a con being its own parent, which causes an infinite loop in con_get_output.

**Comment by Airblader** [comment]
I managed to reproduce this.

**Comment by Deiz** [comment]
It seems like the crash happens when the mouse is moved quickly, and the infinite loop occurs when the mouse isn't moving.

I just ran i3 under valgrind while triggering the infinite loop case, and there are invalid reads and writes going on, which explains the nonsensical values I saw under gdb. My guess is that all of it stems from the resize not being aborted as soon as the floating con is destroyed.

**Comment by stapelberg** [comment]
Yeah, the loop should definitely be aborted when the window ceases to be floating. Pull requests for fixing this are welcome as I won’t get around to fix this myself.

**Comment by Deiz** [comment]
I spent a little more time investigating this, it occurs because the command that disables floating runs before the event loop. So, the window is tiled, its floating parent is destroyed, but then a key event is handled which causes the position/size of the now-destroyed parent to be modified.

I'm not sure what the best approach is for handling this, since destroying the floating parent doesn't generate any events that can be used to abort (rather than revert) the drag operation.
