### ISSUE TITLE
[enhancement] i3-msg should return with proper return codes

### ISSUE THREAD

**Issue by Airblader** [i3/i3#1639]
i3-msg currently always returns with `0`. How about having it return with proper error codes so that non-success cases can be handled without parsing the JSON? We should have two error codes, one for `ysuccess(false)` and one for `yerror(…)`.

However, this *can* break compatibility if people already do connect two calls with `&&` or `||` (even though it doesn't make much sense).

Just throwing it out there. If we don't want to do this, I'll just write a wrapper around i3-msg. :)

**Comment by stapelberg** [comment]
For what? If you’re doing anything moderately complex, you should not use i3-msg. It’s a toy for sending the occasional IPC command and serving as an example of how IPC works.

**Comment by Airblader** [comment]
My specific usecase is having a terminal in the scratchpad. I can already have a single keybinding to hide and show that terminal, now I'd also like the terminal to be opened with that shortcut if it hasn't been opened yet. With return codes, I could do something along the lines of

````
for_window[instance="__scratchpad"] floating enable
bindsym <key> exec i3-msg scratchpad show || urxvt -name __scratchpad
```

I don't think this is anywhere near "complex" and would usually expect any command-line call to return a proper error code. I can, of course, solve this particular problem in a number of ways, so I'm fine with not being able to react to the error code. It's just the first thing I'd think of.

**Comment by stapelberg** [comment]
I think having to be more explicit about what should happen on your end is a good thing here (i.e. using `jq` or a higher-level language to parse the error).

As you noted, scratchpad show doesn’t return an error, and personally I wouldn’t want to make this solution only work when that terminal is the only thing in the scratchpad.
