### ISSUE TITLE
[enhancement] Set _NET_WM_STATE_HIDDEN in tabbed / stacked containers

### ISSUE THREAD

**Issue by Airblader** [i3/i3#1648]
http://standards.freedesktop.org/wm-spec/1.3/ar01s05.html: 
> _NET_WM_STATE_HIDDEN should be set by the Window Manager to indicate that a window would not be visible on the screen if its desktop/viewport were active and its coordinates were within the screen bounds. The canonical example is that minimized windows should be in the _NET_WM_STATE_HIDDEN state. Pagers and similar applications should use _NET_WM_STATE_HIDDEN instead of WM_STATE to decide whether to display a window in miniature representations of the windows on a desktop.

Shouldn't this apply to unfocused containers in stacked / tabbed layouts?

**Comment by stapelberg** [comment]
Yeah, I think that’d be okay. We can certainly apply it in next and see what happens.

**Comment by ianks** [comment]
:+1:

**Comment by Airblader** [comment]
So just for reference: I closed the PR because the approach was by far too naive. I am working on a new approach and will issue a new PR.

**Comment by Airblader** [comment]
@stapelberg Can you maybe help me out with X11::XCB? How do I query the atoms set in `_NET_WM_STATE` in a test? I have this and am testing it on a fullscreened container:

````
sub foo {
    sync_with_i3;

    my ($con) = @_; 
    my $cookie = $x->get_property(
        0,  
        $con->{id},
        $x->atom(name => '_NET_WM_STATE')->id,
        GET_PROPERTY_TYPE_ANY,
        0,  
        4096                                                                                                                                         
    );  

    my $reply = $x->get_property_reply($cookie->{sequence});
    print($reply->{value});
}
```

… but the value always comes back as `Ã¸`.

**Comment by Airblader** [comment]
OK, with a lot of trial-and-error, looking at other tests and after (pointlessly) looking through the source code of X11::XCB and libxcb, I think this will do:

````
sub is_hidden {
    sync_with_i3;
    my $atom = $x->atom(name => '_NET_WM_STATE_HIDDEN');                                                                                             

    my ($con) = @_; 
    my $cookie = $x->get_property(
        0,  
        $con->{id},
        $x->atom(name => '_NET_WM_STATE')->id,
        GET_PROPERTY_TYPE_ANY,
        0,  
        4096
    );  

    my $reply = $x->get_property_reply($cookie->{sequence});
    my $len = $reply->{length};
    return 0 if $len == 0;

    my @atoms = unpack("L$len", $reply->{value});
    for (my $i = 0; $i < $len; $i++) {
        return 1 if $atoms[$i] == $atom->id;
    }   

    return 0
}
```

**Comment by yshui** [comment]
> Shouldn't this apply to unfocused containers in stacked / tabbed layouts?

Counterpoint: the focused container could be transparent.

**Comment by Airblader** [comment]
> Counterpoint: the focused container could be transparent.

But we don't support transparency.

> Also KWin doesn't set _NET_WM_STATE_HIDDEN for all other windows when there's a fullscreen window.

But we do. :-)

Let's please not discuss this in two places, so let's go [here](https://www.reddit.com/r/i3wm/comments/4oh58a/troubles_with_chrome/) from now on.
