### ISSUE TITLE
[enhancement] Legacy layout should be removed

### ISSUE THREAD

**Issue by Airblader** [i3/i3#1649]
From `src/con.c`:

````
* Starting from v4.6 though, we will nag users about using "layout
* default", and in v4.9 we will remove it entirely (with an
* appropriate i3-migrate-config mechanism). */
```

**Comment by stapelberg** [comment]
This comment was added in v4.1, and the as far as I can see, the mentioned nagging was never implemented. That’d be the first step.

That said, I’m not sure having this transition at all is worth it. Especially the i3-migrate-config cycle we’d need to have seems like a high-risk step with diminishingly small return.

**Comment by Airblader** [comment]
I'll send a PR then to remove the comment.

**Comment by Airblader** [comment]
I'm closing this issue independently of the PR since the issue was about doing what the comment states, not removing a comment. No need to track this any further.
