### ISSUE TITLE
[enhancement] keymap agnostic bindings

### ISSUE THREAD

**Issue by wapiflapi** [i3/i3#1656]
When switching between different keyboard layouts some bindings are obviously sub-optimal. (home vs work, different computers sharing a configuration, etc) It would be great if we could have some way to define different bindings for different keymaps, or have a way to bind to keys instead of "symbols" but the later might be more difficult to implement.

A simple example would be `$mod+1`, `$mod+2`, ... that I use to switch workspaces, on an `azerty` keyboard those become `$mod+&`, `$mod+é` or I would have to press `shift` all the time.

A simple fix would be some sort of conditional imports in the configuration file, then I could check which mapping is being used (with a shell command for example) and include a different i3 configuration file depending on the environment.  This could also be useful to change the configuration according to how many / witch screens are connected when starting i3.

**Comment by mh21** [comment]
To get sth. like conditional imports, I use the following setup to work with i3 across multiple computers with different configurations:

Custom i3 wrapper that generates a temporary config in `~/.local/bin/i3`:
```sh
#!/bin/sh
if [ $# = 0 ]; then
    CONFIG=$(mktemp -d)/i3config
    ~/.config/i3/update-config.sh "$CONFIG"
    ARGS="-c $CONFIG"
fi
exec /usr/bin/i3 "$@" $ARGS
```

Script to create custom config depending on hostname `~/.config/i3/update-config.sh`:
```sh
#!/bin/sh
CONFIG=$1
cat "$HOME/.config/i3/config" > "$CONFIG"
cat "$HOME/.config/i3/config-restart" | sed "s|%CONFIG%|$CONFIG|g" >> "$CONFIG"
cat "$HOME/.config/i3/config-$(hostname)" >> "$CONFIG"
```

a snippet to make i3 restart with the correct config `~/.config/i3/config-restart`:
```
bindsym $mod+Shift+r exec ~/.config/i3/update-config.sh %CONFIG% && i3-msg reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+p exec ~/.config/i3/update-config.sh %CONFIG% && i3-msg restart
```

and then the general configuration in `~/.config/i3/config` and the specific configurations in `~/.config/i3/config-hostname`.

All in all, that is about 15 lines of code. I would think that conditional imports implemented directly in i3 would require quite a bit more.

**Comment by wapiflapi** [comment]
That is a pretty elegant/flexible solution. Not sure why it didn't occur to me but I think I like it. I'll definitely setup something similar soon on my systems. Thanks for the tip.

As far as I am concerned this ticket can be closed but I'll leave it open for a few days in case anyone has something to add.

**Comment by stapelberg** [comment]
Use `bindcode` instead of `bindsym` to get keymap agnostic bindings.
