### ISSUE TITLE
Window title changes should trigger window swallowing (layout saving)

### ISSUE THREAD

**Issue by stapelberg** [i3/i3#1668]
@teto reports that i3 doesn’t swallow urxvt with the following layout JSON file:

``` json
// vim:ts=4:sw=4:et
{
    "border": "pixel",
    "current_border_width": 1,
    "floating": "auto_off",
    "geometry": {
       "height": 388,
       "width": 734,
       "x": 0,
       "y": 0
    },
    "name": "/home/teto",
    "percent": 1,
    "swallows": [
       {
        "class": "^URxvt$",
       // "instance": "^rxvt\\-unicode$",
        "title": "^/home/teto/dce$"                                                                      
       // "transient_for": "^$"
       }
    ],
    "type": "con"
}
```

@teto starts urxvt like this:

``` bash
#!/bin/sh

i3-msg "workspace 9; append_layout $HOME/.i3/test.json"                                                  

urxvt -cd $HOME/dce
```

Having a look at the logfile reveals that urxvt first starts up with a different title and later changes its `_NET_WM_NAME` property to set the correct title.

i3 should, once it got the new title, check whether the window can be matched by any of the placeholders and swallow it if so.

This affects not only window titles, but all properties that can be used to swallow a window.

**Comment by Airblader** [comment]
This should be as simple as a `run_assignments` call in `src/handlers.c`.

**Comment by stapelberg** [comment]
No. `run_assignments` is already called in `src/window.c`, but that’s for assignments, not for swallows.

**Comment by Airblader** [comment]
Oh, yeah. You're right. :)

**Comment by Airblader** [comment]
@stapelberg I think you now closed the wrong issue. As @acrisci said in #1672, the PR fixes #1661 and not this.

**Comment by keshavdv** [comment]
+1

**Comment by alexmcnurlin** [comment]
Is there any progress on this? I noticed that there hasn't been any comments on this issue for a while. I'd really like to see this feature implemented!

**Comment by Airblader** [comment]
No, there's no progress yet. This issue isn't entirely trivial as it involved detaching and reattaching a window correctly. Some quick attempts I made were buggy.

**Comment by teto** [comment]
I recently replaced urxvt with termite and tried again using layouts. I haven't enabled i3 debug but termite seems to behave like urxvt, thus windows aren't swallowed :'(

**Comment by Airblader** [comment]
Is there any reason why you need to match on the title? I think in most cases it should be possible to match on class and instance and start the terminals accordingly.

**Comment by alexmcnurlin** [comment]
If I launch a Firefox window with a specific url, the title doesn't get set
until the page loads. As a result, my layout restore always puts the
Firefox Windows in the wrong spot.

**Comment by teto** [comment]
Similarly, I want my terminals to start in specific directories. This is done with "termite -d $HOME/myrep" or "urxvt -cd $HOME/toto". I suppose I could do without the match on title and launch the terminals in the same order as I want  them swallowed. Could concurrency problems mess up the order if late terminals spawn before others ?

**Comment by Airblader** [comment]
I realize what you want to do, but you don't need to use the title to match on. Just match on class and instance and start the application accordingly. For example, start urxvt with

    urxvt -name foo

And match via 

    class: "(?!)urxvt" 
    instance: "foo"

**Comment by teto** [comment]
With termite I can override the role with "-r". I tried modifying the i3-save-tree output with matching "role" and it works as expected.
I leave this open as I think it would still be nice to have.

**Comment by arynaq** [comment]
@Airblader It wont match with -name either. Any ideas?

**Comment by Airblader** [comment]
@arynaq Please use the subreddit or mailing list and give a fill set of information on how you're starting the terminal and how you're matching it.

**Comment by Airblader** [comment]
I've sent a PR to clarify the docs for now in #2679. When this issue is resolved we should remove that documentation again.

**Comment by izzel** [comment]
I can work on this. I do have one question though. I see two ways of implementing this: Destroying the original window's container and reparenting it to the swallow one or destroying the swallow window container and moving the original container. Is either method preferable?

**Comment by Airblader** [comment]
Without looking I assume the code path when managing a window reparents the window into the swallow container, so I would probably do it that way — it also has the benefit that it's much easier to respect the layout that way. 

The downside is that we lose container level information. Things coming to mind are stickiness, title format and marks.

**Comment by teto** [comment]
thanks !

**Comment by JonnyHaystack** [comment]
I get some very strange bugs when restoring multiple windows in a 4x4 grid by appending a layout and then opening terminal windows whose titles adjust are changed after initial window creation. When I use the old workaround of unmapping all the windows in the workspace, appending the layout, then remapping the windows, it works fine as it always has.

How it should look (and how it does look when I restore it in the old way):
![img-2020-04-25-1750](https://user-images.githubusercontent.com/1266473/80282617-57c25e00-870a-11ea-9fef-5517b2e5e360.png)

How it looks when the windows are swallowed after a title change:
![img-2020-04-25-1751](https://user-images.githubusercontent.com/1266473/80282634-70cb0f00-870a-11ea-8142-1d7efe53c765.png)

These are not mere graphical artifiacts, because if I keep pressing enter you can see that the prompt never goes below the top of the "artifact", so the window must actually be ending there, and the tiling has completely broken.

Also thanks @izzel for your work on this, it's a great improvement to have. In most situations it has worked perfectly for me, and I'm not sure if this weird bug is directly related to this change or if this change is bringing to light a bug somewhere else in the codebase.

**Comment by izzel** [comment]
I went ahead and moved this into a new issue @JonnyHaystack.
