### ISSUE TITLE
[enhancement] Control i3bar click events

### ISSUE THREAD

**Issue by Airblader** [i3/i3#1695]
Currently, we already can change the behavior of scroll events via `wheel_up_cmd` and `wheel_down_cmd`. This should also work for click events, e.g., to allow disabling clicks on workspace buttons.

**Comment by acrisci** [comment]
I kind of regret not making those more extensible.

Maybe we should deprecate them in favor of something that takes a button number, similar to a bindsym.

**Comment by Airblader** [comment]
I like that. In fact, I was going to suggest it but then figured it wouldn't be favored as it's inconsistent with the current commands.

**Comment by Airblader** [comment]
Just FYI: I will be working on a PR for this tonight.
