### ISSUE TITLE
[enhancement] Move window to mouse

### ISSUE THREAD

**Issue by Airblader** [i3/i3#1696]
I guess there's a good chance this will be rejected since it is about floating containers and mouse, both of which aren't core i3 features, but anyway:

We have a command to move a floating container to the center of the screen. However, many dialogs, which open floating, I'd rather automatically move to wherever my mouse is. This could be file dialogs, alerts or panels for volume control etc.

This could be done via `move position mouse` which should fit nicely into the `move [absolute] position center` syntax.

**Comment by Airblader** [comment]
Of course I'd want to take screen boundaries into account. So basically an equivalent of the following script (which might have a much easier alternative). Note that while this is doable with a script, there are drawbacks: it can only be done once the window is there, which causes a noticable flicker and delay.

````
#!/usr/bin/env bash
set -eu

PATTERN="${1}"
WID=$(xdotool search --onlyvisible ${PATTERN} 2>/dev/null)

# get window geometry
eval $(xdotool getwindowgeometry --shell ${WID} 2>/dev/null)
WIN_WIDTH="${WIDTH}"
WIN_HEIGHT="${HEIGHT}"

# get mouse position
eval $(xdotool getmouselocation --shell 2>/dev/null)
MOUSE_X="${X}"
MOUSE_Y="${Y}"

# get screen size
eval $(xdotool getdisplaygeometry --shell 2>/dev/null)
DISPLAY_WIDTH="${WIDTH}"
DISPLAY_HEIGHT="${HEIGHT}"

# center the window to the mouse
TARGET_X=$((MOUSE_X - WIN_WIDTH / 2))
TARGET_Y=$((MOUSE_Y - WIN_HEIGHT / 2))

# stay in bounds
[[ "${TARGET_X}" -lt "0" ]] && TARGET_X="0"
[[ "${TARGET_Y}" -lt "0" ]] && TARGET_Y="0"
[[ "$((TARGET_X + WIN_WIDTH))" -gt "${DISPLAY_WIDTH}" ]] && TARGET_X="$((DISPLAY_WIDTH - WIN_WIDTH))"
[[ "$((TARGET_Y + WIN_HEIGHT))" -gt "${DISPLAY_HEIGHT}" ]] && TARGET_Y="$((DISPLAY_HEIGHT - WIN_HEIGHT))"

xdotool windowmove ${WID} ${TARGET_X} ${TARGET_Y}
```

**Comment by stapelberg** [comment]
I think adding this is okay, as it shouldn’t be too much code and makes sense for dealing with annoying popup dialogs.

**Comment by Airblader** [comment]
OK. I'm working on this already now. Just gotta add tests and docs, then I'll send the PR. It also works a whole lot better (read: at all) with multiple outputs, unlike my script above.
