### ISSUE TITLE
i3*.xession.desktop should allow a hook

### ISSUE THREAD

**Issue by RoUS** [i3/i3#1702]
Feature request: Have i3's Xsession `.desktop` files list a script as the `Exec` value, rather than the `i3`binary.

I'm using i3 on Fedora 21:

    $ rpm -q i3
    i3-4.9.1-1.fc21.x86_64
    $ i3 -v
    i3 version 4.9.1 (2015-03-07, branch "4.9.1") © 2009-2014 Michael Stapelberg and contributors

The `i3*.xsession.desktop` files contain `Exec=i3` and `TryExec=i3`, which means the binary will be directly `exec`ed by the Xsession sequence.

Unfortunately, that means the *only* hook for user intervention in this scenario (which is apparently where all of the Xsession stuff is now going) is the user's `$HOME/.profile` login script.  That gets invoked by `/etc/X11/xinit/xinitrc-common` and no other user script is in the sequence until the `.desktop` file's `Exec` is processed.

My feature request is that the `.desktop` files list a script as the {Try.}Exec key value, and that the script look for a user hook script to source before `exec`ing the i3 binary.

**Comment by Airblader** [comment]
What do you need to execute before starting i3?

**Comment by RoUS** [comment]
Things like setting the `PATH`, starting `gpg-agent`, `urxvtd`, `nm-applet` -- pretty much anything that someone might have put into `~/.xsession` is ye elder days.  Stuff that should be in `i3`'s environment when it actually starts.

**Comment by Airblader** [comment]
Why not put it into `~/.xinitrc`? Shouldn't that be executed?

**Comment by RoUS** [comment]
It isn't.  The gdm/Xsession model apparently goes straight to whatever was passed on its command line, which gets picked up from the .desktop files. :-(

**Comment by Airblader** [comment]
What version of gdm is Fedora 21 using? gdm not respecting the proper startup files seems like a bug to me. According to [this](http://webcache.googleusercontent.com/search?q=cache:p9C-AeXU6DkJ:subtle.subforge.org/blogs/show/13+&cd=4&hl=en&ct=clnk&gl=us), gdm had this bug a few years back. According to [this](https://wiki.archlinux.org/index.php/Xprofile), at least newer versions pick up on `~/.xinitrc`.

**Comment by RoUS** [comment]
Apparently the X startup gods have concluded that ~/.xsession and ~/.xinitrc are parallel mechanisms, with no crosstalk.  `~/.xsession` has its origins in the `xdm` sequence, and `~/.xinitrc` has its origins in `startx`. 

http://tldp.org/HOWTO/XWindow-User-HOWTO/runningx.html

**Comment by RoUS** [comment]
Whoops, timeshared.  F21 has gdm-3.14.2-1.fc21.x86_64.  Looking at those links..

**Comment by RoUS** [comment]
`grep -r '\.xinitrc' /etc/X11 /etc/gdm` => no results. :-(

**Comment by Airblader** [comment]
Does it execute `~/.xsession`?

**Comment by RoUS** [comment]
No. :-(  The only user script executed is `~/.profile` and that's by `/etc/X11/xinit/xinitrc-common`.

**Comment by Airblader** [comment]
[This](https://wiki.archlinux.org/index.php/GDM#Installation) suggests that at least `~/.xprofile` may be run. Maybe you can check that as a last resort.

If none of this works, you could still run all of these things from your `~/.i3/config` (or wherever you keep it). There's no technical reason not to use a script in the desktop file, but I'm also not sure it's worth adding yet another entry point. But we'll see what @stapelberg  says :)

**Comment by RoUS** [comment]
Well, you can't set the PATH for i3 in its own .i3/config file, so that breaks the 'do it in config' workaround, alas. :-(

**Comment by stapelberg** [comment]
xinitrc/xsession are executed when you chose “custom” as session type. The “i3” session type is not customizable because that’s how things are with these .desktop files.

**Comment by RoUS** [comment]
I created `/usr/local/bin/i3` containing the following:

    #! /bin/bash
    [ -x "${HOME}/.xprofile" ] && . "${HOME}/.xprofile"
    exec /usr/bin/i3

It worked an absolute treat.  So the session type may not be customisable, but that doesn't mean it can't be hooked.  `i3`-the-binary could go in `/usr/libexec` and a script such as the above in `/usr/bin`.

My objection to doing this as a workaround, as I just did, is that it requires root access to drop the file in `/usr/local/bin`.

Thanks!

**Comment by RoUS** [comment]
Since this would be getting done outside of the standard sequence, the user hook script invoked by `/usr/local/bin/i3` should have an i3-specific name and not overload `.xsession`, `.xinitrc`, or `.xprofile`.  At least IMHO.

@stapelberg Does putting it this way make it more palatable to alter the .desktop file to invoke an i3 script with user hooks before actually running `/usr/bin/i3` ?

**Comment by stapelberg** [comment]
I still think you’re on the wrong path. Get your session manager to make use of the .xsession or .xinitrc files. See also https://wiki.ubuntu.com/CustomXSession (very bottom of the page comes with a .desktop file).

**Comment by RoUS** [comment]
That's another root-required customisation requiring maintenance, and the chooser will say something about 'user session' rather than 'i3'.  If only `gdm/Xsession` would actually honour one of the `~/.x*` files this would be a non-issue. :-(

**Comment by stapelberg** [comment]
If that bothers you, file a bug with gdm :).

**Comment by RoUS** [comment]
LOL.  I intend to do so.  However, I'm a big fan of the "give 'em rope" approach, so I like the idea of app-specific user hooks -- so I still hope i3 might provide one. :-)

**Comment by stapelberg** [comment]
I don’t see any other window manager’s .desktop file providing such a hook, and I’m not keen to introduce yet another (non-standard) way for users to configure things that should really just go into .xsession.

**Comment by RoUS** [comment]
Ah, well.  Thanks anyway.
