### ISSUE TITLE
[enhancement] [i3bar] Balloon messages

### ISSUE THREAD

**Issue by Airblader** [i3/i3#1713]
The [System Tray Specification](http://standards.freedesktop.org/systemtray-spec/systemtray-spec-latest.html) mentions balloon messages as a feature.

How do we feel about adding this? My suggestion would be not to have i3 display those messages but instead just redirect them to `notify-send` since that probably integrates better with the user's system and saves us a lot of complexity / configurability.

However, I have to admit that I have no particular usecase since I don't know which tray icons even make use of balloon messages. It's hard to know if you never see it :) So if someone knows which ones do, it might also help make a point.

**Comment by acrisci** [comment]
I've never learned anything from reading something in a balloon message.

I think this should only be considered if there is a major breakage in a popular app.

**Comment by Airblader** [comment]
I think any major breakage would (and should) he considered a bug in that application since balloon messages are not mandatory for a tray.

**Comment by stapelberg** [comment]
I think you’ve already pretty much answered it. That feature is hard to implement in a good way for i3, and optional as well, so let’s not do that :).
