### ISSUE TITLE
feature request: scaling content for high density displays

### ISSUE THREAD

**Issue by or** [i3/i3#1717]
I think it'd be very useful to be able to scale the content of a window in i3. Even if it's only an integer factor >= 1.

Is this something i3 could do or would something like compton be the right place for that?

I'd also love to help with this, but am not sure how to start. I would assume i3 could tell a window, which should be put into a width x height area, that it has a (width / k) x (height / k) area at its disposal, then scale the output to width x height for display. Any mouse events would have to be scaled down.
The xcb copy calls only seem to copy 1:1. Does this sound doable?

Alternatively it'd also be nice if this could be done for an entire workspace. I guess xrandr could be used whenever the workspace is switched, but that's a pretty noticeable delay.

If anyone has other ideas how to accomplish this, then I'd love to read them too!

**Comment by stapelberg** [comment]
i3 cannot do that, as it’s not involved in rendering window content. What’s wrong with the current way of high-dpi display scaling? It works fine for me. See also https://wiki.archlinux.org/index.php/HiDPI for how to configure software accordingly.

**Comment by or** [comment]
The scaling works fine for most programs for me as well, but for some the solutions given in that link might not work.

In my particular case it's a game development framework IDE called Unity3D, which I run with wine. It doesn't honor dpi settings set with winecfg.

Could you explain briefly why it isn't possible? The content is rendered to some offscreen buffer and then copied to the screen into its assigned rectangle by i3, no? Can't that copying process change the content at all?

**Comment by stapelberg** [comment]
i3 does not copy pixmaps around. It reparents the application’s window into the decoration window. Everything else happens between the application and X11.

I suggest you open a bug with Unity3D and ask them to support high-dpi displays. This is a general problem, not one where a workaround in a window manager is an acceptable solution :).

**Comment by or** [comment]
I only gave that specific example in response to the suggested workarounds. :) I still think it'd be a useful feature for a number of other scenarios.
But it's good to know that i3 is not the right place for it and I understand the inner workings of it a little bit better now, thank you.
