### ISSUE TITLE
[enhancement] Separate binding mode color

### ISSUE THREAD

**Issue by Airblader** [i3/i3#1732]
The color currently used for binding mode indicators is the same as that for urgent workspaces. I know this is a detail, but I'd like to have a separate `binding_mode` directive in the colors that can be used.

The reason being that I want my urgent workspace to be really present since I really utilize urgency flags, but I feel the binding mode is too present due to that.

The idea would be to fall back to the urgent workspace setting if it is not present, providing backwards compatibility. The patch should be simple and not add any overhead.

**Comment by stapelberg** [comment]
Sounds good to me.

**Comment by Airblader** [comment]
Great! Getting started on it.
