### ISSUE TITLE
[enhancement] skip over shebang line in layout files

### ISSUE THREAD

**Issue by mh21** [i3/i3#1779]
At the moment, layout files for append_layout are not allowed to have a shebang line. If that would be possible, you could

- make layout files executable so that you could directly execute a layout file with a shebang line such as
```
#!/usr/bin/i3-msg append_layout
```
- integrate the complete workspace configuration in a layout file, including workspace name and starting programs with sth. like
```
#!/usr/bin/i3-msg workspace 9: terms; exec i3-sensible-terminal; exec ...; append_layout
```
- use a custom handler to set a layout and configure the workspace based on magic comments:
```
#!/usr/bin/env i3-run-workspace.sh
```

The code required is pretty minimal, an initial version can be found at 5b454bd. If this is deemed useful, I can add some use cases to the documentation.

**Comment by stapelberg** [comment]
I don’t think using the shebang like that is a good idea. When stuffing all commands into a single line, you’ll have trouble with quoting and composing these commands, ultimately resulting in a worse interface than what we have right now:

Our current recommendation is to write a script/program in your favorite language, and I think that’s a better alternative over the suggestion at hand.
