### ISSUE TITLE
"workspace next/prev" selectively skips some workspaces

### ISSUE THREAD

**Issue by rockfruit** [i3/i3#1798]
i3 version 4.10.2 (2015-04-16, branch "4.10.2") © 2009-2014 Michael Stapelberg and contributors
Log:  http://logs.i3wm.org/logs/5729201025974272.bz2

I have two displays, primary is the laptop LCD, and secondary is VGA1. On primary, I have workspaces A S D F, and R. On secondary, I have workspaces 6, 7, 9, and G.

Hitting "workspace next/prev" cycles correctly between A S D F R and G, but these two commands completely pass over workspace 6, 7 and 9 on VGA1.

If however, I have a numeric workspace (usually 1-5) on the primary monitor, then the cycling works fine: It will cycle from the last numerically named workspace on the primary, into the first numbered workspace on the secondary.

It's only when there are no numbered workspaces on the primary, that the secondary monitor's numeric workspaces are skipped.

The reverse does not seem to be true: if I have only alphabetical workspaces on the secondary monitor, it will happily cycle correctly through all workspaces.

**Comment by hwangcc23** [comment]
Hi,
I want to help debug this problem. 
But I cannot repro it. (I only have one monitor.)
I cannot find related infomation in the log file. (From the log, I only see you switch between workspace A and F.)
Could you double check your log and upload another one?
Thanks.

**Comment by Airblader** [comment]
@hwangcc23 To reproduce multi-monitor issues you can

* Use `fake-outputs` in your i3 config (but beware…)
* Use a virtual machine with two outputs (much better)

**Comment by hwangcc23** [comment]
@Airblader Thanks.  :D

**Comment by hwangcc23** [comment]
Hi,
I think this is not a bug. It is the intended behavior of the workspace-next command.
The command steps through either numbered workspaces or named workspaces.
See [its implementation](https://github.com/i3/i3/blob/next/src/workspace.c#L512).
Should we add a note and an example in the userguide?

**Comment by Airblader** [comment]
Thanks, that's a good point. @stapelberg The behavior is currently deliberate. I suppose we might not want to change it? The idea of documenting this better sounds good to me.

**Comment by stapelberg** [comment]
I think we should actually try to change the behavior: currently, we cycle through either numbered or named workspaces, but when we reach the last numbered/named workspace, we only look for named workspaces. I think we should look for named workspaces after exhausting numbered ones, but also for numbered ones after exhausting named ones.

**Comment by hwangcc23** [comment]
Will send a PR for this.
