### ISSUE TITLE
focus_on_window_activation keeps matching urgent criteria  

### ISSUE THREAD

**Issue by cornerman** [i3/i3#1825]
I have enabled ```focus_on_window_activation urgent``` so windows setting net_active_window are marked urgent instead of being focused. This essentially works, but there is something different to normal urgent windows.

The log file can be found here: http://logs.i3wm.org/logs/5702797177651200.bz2

You can see that in this case qutebrowser sets net_active_window, so i3 sets the urgency hint. Then I use ```[urgent=latest] focus``` in order to focus it, the urgent flag is cleared and there are no urgent window left; everything okay so far. But when I issue ```[urgent=latest] focus``` again, it again focuses the qutebrowser window. Somehow after the window is activated and got an urgency hint, the urgent criteria keeps on matching. Note, that this does not happen for windows that set the urgency hint for themselves.

i3 version 4.10.2-238-gc8b4303 (2015-07-27, branch "next") © 2009 Michael Stapelberg and contributors

**Comment by stapelberg** [comment]
I have a suspicion about what’s wrong here.

**Comment by cornerman** [comment]
Cool. Maybe it helps; I just tested a bit and found that the urgent matcher checks for existing urgent timers, but when focusing a window the timers are not reset (just the boolean urgent flag). But I am wondering why this currently works for normal urgent windows but not for active windows becoming urgent.

**Comment by stapelberg** [comment]
Are you sure this works with normal window? The following test case does currently fail for me, regardless of whether I use the urgency or NET_ACTIVE_WINDOW line:

```perl
my $config = "
# i3 config file (v4)
font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
        
focus_on_window_activation urgent
";
        
my $pid = launch_with_config($config);
my $i3 = i3(get_socket_path(0));
my $ws = fresh_workspace;
my $first = open_window;
my $second = open_window;

$first->add_hint('urgency');
#send_net_active_window($first->id);
sync_with_i3;
is($x->input_focus, $second->id, 'second window still focused');

cmd '[urgent=latest] focus';
sync_with_i3;
is($x->input_focus, $first->id, 'first window focused');

cmd 'focus right';
sync_with_i3;
is($x->input_focus, $second->id, 'second window focused again');

cmd '[urgent=latest] focus';
sync_with_i3;
is($x->input_focus, $second->id, 'second window still focused');

exit_gracefully($pid);
```

**Comment by stapelberg** [comment]
Ah, I think the difference is that normal windows will actively remove the urgency hint when being focused. When adding `$first->delete_hint('urgency');`, the test passes.

**Comment by cornerman** [comment]
That is what I observe when I try it in i3:
```sleep 1 && echo -e "\a"```

Then focus another window and try with ```[urgent=latest] focus```, it only works once.

Windows actively removing the urgency hint would explain why it works for them.

**Comment by cornerman** [comment]
I have played around a bit with it and found one solution for when the window gets focused, you can see the commit [here](https://github.com/cornerman/i3/commit/babff92516c791f9bad4fe340882c18fade6a306). Your testcases passes.

Nevertheless this is not complete; the same needs to be done when a workspace is shown and the urgency hint reset is deferred.

**Comment by stapelberg** [comment]
> Nevertheless this is not complete; the same needs to be done when a workspace is shown and the urgency hint reset is deferred.

Yeah, as I said, I’m working on fixing this issue currently.

To be honest, I don’t understand why you are duplicating work on this issue? If you’re interested in fixing it yourself, why did you file this bug instead of just sending a pull request in the first place?

**Comment by cornerman** [comment]
Thanks for fixing this.

I did not want to duplicate the work, in fact I just happened to look into it myself today and later saw your message in this thread. So, I thought it might not hurt to check your testcase and push what I have found.
