### ISSUE TITLE
enhancement: Resize borderless windows by mouse

### ISSUE THREAD

**Issue by acrisci** [i3/i3#1826]
Related to #1787.

i3 requires borders to resize by mouse.

This affects floating windows without borders and adjacent windows without borders.

Borderless windows would be much more useful if they could be resized somehow by mouse.

We could perhaps fix this by drawing an "invisible border" around the window which could be grabbed by the mouse. This would be less effective for tiling windows because it would require putting a gap between the windows.

I don't think it would be a good idea to make part of the actual client window grabbable by mouse.

Are there any clever solutions to this problem I might be missing?

**Comment by Airblader** [comment]
I think if you go for that solution you'll cause problems with window focus. The user will click "next" to the floating window in order to focus the window underneath that position, but it won't work because they will actually be clicking the invisible border.

**Comment by Airblader** [comment]
We should maybe look into how other window managers tackle this problem.

**Comment by stapelberg** [comment]
> Borderless windows would be much more useful if they could be resized somehow by mouse.

They can, that’s what the `floating_modifier` is for. E.g., use Mod4 + right-click to resize.

If you’re aware of this, why is it you say that borderless windows would be _much more useful_, if they could be resized by the mouse without using the `floating_modifier`?

**Comment by Airblader** [comment]
So I'm going to close this for now because a) the proposed solution wouldn't work and b) we already have a solution for this. If Tony disagrees, he knows how to reopen. :)
