### ISSUE TITLE
Allow reload to take an optional configuration file path

### ISSUE THREAD

**Issue by kneitinger** [i3/i3#1849]
I implemented something that helps me out a lot, but running it by everyone before updating the documentation and submitting a pull request:

I modified the `reload` command to take an optional argument which is the configuration file to load.

For example in ~/.i3/config:

    bindsym $mod+x reload ~/.i3/another_config
and in ~/.i3/another_config

    bindsym $mod+x reload ~/.i3/config

The reason I did this was to have drastically different i3 experiences for different use-cases, beyond the scope of modes.  For instance, my general configuration is fine most of the time, but when playing music, I do not need 80% of my defined keybindings and they could better be used for different functions.

I have two questions.  One, of course, is this something people are interested in?  It has been very helpful to me, but I understand if not.  Second, is this better implemented as a modification to `reload` or should it be a new command just called `load`?

**Comment by stapelberg** [comment]
> For instance, my general configuration is fine most of the time, but when playing music, I do not need 80% of my defined keybindings and they could better be used for different functions.

Are i3’s modes (see the last paragraphs of http://i3wm.org/docs/userguide.html#resizingconfig) not sufficient to cover this use-case?

> I have two questions. One, of course, is this something people are interested in? It has been very helpful to me, but I understand if not. Second, is this better implemented as a modification to reload or should it be a new command just called load?

Why can you not just replace your config file and use reload as-is?

**Comment by kneitinger** [comment]
I really dig modes, and they have helped me create many solutions to tasks I wanted, however, I do think that modes are not sufficient for this use-case, mainly because of the problems that occur during nesting of modes.  I want *mostly* the same experience from one config to another, but with some altered keybindings.

If I were to enter a "music performance" mode, but then go into "resize" mode, I would have to place an additional keybind in the music mode for resize.  Then once I enter resize from music, there is no general way for a mode to essentially "pop" off a modes stack, so one must define keybinds in resize to return to both default and music modes in this example.

Regarding replacing the config file: that method is certainly a way to accomplish the same task, so it comes down to the question of which is more preferable.  It would not be difficult to write a little script to facilitate the task of copying a particular config to the proper location, and if this is a very fringe use-case, I get that.  However, if this ability was included, the cleanness of built-in functionality may influence people to experiment with this and come up with interesting uses.

**Comment by Airblader** [comment]
Side note, but instead of copying files around I'd just use a symbolic link.

**Comment by stapelberg** [comment]
Thanks for the additional details. Keeping the (mental) complexity of i3 small by keeping commands simple weighs in higher than the additional cleanliness for advanced configuration use-cases, I think.

**Comment by nmschulte** [comment]
Does i3 allow macros in the config?  A way to have a mode extend another might save verbosity in the config, because instead of:
> Then once I enter resize from music, there is no general way for a mode to essentially "pop" off a modes stack, **so one must define keybinds in resize to return to both default and music modes in this example.**

one could have two different `resize` modes, one for `music` and one for `default`, and the macro/extensiblity idea would make this easier to see in the config.

**Comment by Airblader** [comment]
No, i3 intentionally doesn't offer that. But nothing stops you from scripting it. For a while I've used i3-bang which does an amazing job at this. I don't use it anymore, but it'll certainly do anything you can dream of.

https://github.com/KeyboardFire/i3bang
