### ISSUE TITLE
[enhancement] Additional title_format placeholders

### ISSUE THREAD

**Issue by Airblader** [i3/i3#1861]
I'd like to open this issue to argue in favor of new placeholders for the `title_format` directive. A few suggestions:

* `%command`, which typically will be equivalent to the process name. I'm suggesting the command rather than the process name since it's available as `WM_COMMAND` on the window.
* `%class`, `%instance` – These properties identify a window pretty well (opposed to, say, the role property, which is why I'm not suggesting that one), are pretty much always set and we already expose/support them in command criteria.

**Comment by Airblader** [comment]
Here is one user who would benefit from the first suggestion: https://faq.i3wm.org/question/6497/modify-application-title/

**Comment by stapelberg** [comment]
I think that’s fine.

**Comment by Airblader** [comment]
Great! I'll be working on this.

**Comment by Airblader** [comment]
@stapelberg I actually think that we don't need  `%command`. In general, according to the ICCCM this would just be the instance unless it was overridden by the user. In this case the class will usually still be close enough, plus a user overriding the instance name obviously knows what they're doing anyway.

What do you think?

**Comment by Airblader** [comment]
Just for reference, from the ICCCM:

> A string that names the particular instance of the application to which the client that owns this window belongs. Resources that are specified by instance name override any resources that are specified by class name. Instance names can be specified by the user in an operating-system specific manner. On POSIX-conformant systems, the following conventions are used:
>
> * If "-name NAME" is given on the command line, NAME is used as the instance name.
* Otherwise, if the environment variable RESOURCE_NAME is set, its value will be used as the instance name.
* Otherwise, the trailing part of the name used to invoke the program (argv[0] stripped of any directory names) is used as the instance name.

Although a quick test shows that at least neither Chrome nor Firefox follow this rule. Other applications do, though.

**Comment by stapelberg** [comment]
urxvt is one of the few applications which set WM_COMMAND to something else than just the instance. I’ll leave it up to you whether to include it, I don’t have strong feelings either way.

**Comment by Airblader** [comment]
My urxvt's WM_COMMAND is a list of the command sequence, so it looks "just fine". Chrome and Thunderbird, however, don't set the property at all. Also, the ICCCM says:

> A client with multiple top-level windows should ensure that exactly one of them has a WM_COMMAND with nonzero length

I think this makes this property pointless to have as from a technical point of view it's a per-window property, but from a spec point of view it's more of a per-application property.

If someone does ever want this because class, instance and title aren't enough, we can revisit.
