### ISSUE TITLE
monitor focus bug

### ISSUE THREAD

**Issue by andrewclarkii** [i3/i3#1867]
When you have a laptop and external monitor, i3 has a feature to open different workspaces on different displays. After first boot, if your mouse pointer is located on external display, i3 puts all workspaces on different monitors, not exactly as you configured them. When you logout and login again , i3 puts workspaces as you configured. 
```bash
$ uname -a
Linux powercharge 4.1.5-200.fc22.x86_64 #1 SMP Mon Aug 10 23:38:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/redhat-release 
Fedora release 22 (Twenty Two)
$ rpm -qa | grep i3
i3status-2.8-3.fc22.x86_64
i3-4.10.3-1.fc22.x86_64
$  i3 --version
i3 version 4.10.3 (2015-07-30, branch "4.10.3") © 2009-2014 Michael Stapelberg and contributors

http://logs.i3wm.org/logs/5644309118320640.bz2

**Comment by Airblader** [comment]
Can you give us the specific configuration of your workspace assignments and which workspaces end up on which output on boot?

**Comment by andrewclarkii** [comment]
```bash
# bind applications to exact workspaces
# use xprop | grep -i "class" to discover a WM_CLASS
assign [class="^Keepassx$"] 1:kpx output eDP1
assign [class="^URxvt$"] 2:term output VGA1
assign [class="^Chromium-browser$"] 3:web output VGA1
assign [class="^Caja"] 4:fmngr output VGA1
assign [class="^deadbeef$"] 5:music output eDP1
```
eDP1 - Lenovo laptop
VGA1 - Dell monitor

I guess i3 places it in random order, after boot. I have shot a video, I can
upload it to you.

**Comment by Airblader** [comment]
Wow, I'm surprised you can even start i3 with that. It's not at all the intended syntax to combine window assignment and workspace assignment in one line as you did. I'm also surprised that this works at all. I'll investigate that later. 

In the meantime, please split the two forms of assignment and see if that already solves the problem. You have to do it like this:

````
assign [...] 1:kpx
workspace 1:kpx output eDP1
```

Similarly for the others. You can also use variables to avoid having to repeat the workspace names.

**Comment by Airblader** [comment]
@stapelberg Or is it a "hidden" feature (undocumented) that should work?

**Comment by andrewclarkii** [comment]
According to paragraph 7.2 i3wm documentation:
There are several things to configure in i3 which may be interesting if you have more than one monitor:
1. You can specify which workspace should be put on which screen. This allows you to have a different set of workspaces when starting than just 1 for the first monitor, 2 for the second and so on. See [workspace_screen].
2. If you want some applications to generally open on the bigger screen (MPlayer, Firefox, …), you can assign them to a specific workspace, see [assign_workspace]

So I thought that I should define which monitor for which program I will use in assign paragraph. Anyway I had edited i3wm conf file and reboot my laptop. I guess everything working correct now. Thank you very much! And please, excuse me, for "false positive" bug.

**Comment by Airblader** [comment]
Yeah, there was one misunderstanding: you define which workspace to use for a window and you define which screen to use for a workspace. What you can't do is choose which screen to use for a window (except for putting it on a specific workspace). 

Anyway, I think everything is working as intended here. I might still take a look at why the syntax is even accepted like this (it should actually just lead to workspaces named "1:kpx output eDP1").

**Comment by andrewclarkii** [comment]
> I might still take a look at why the syntax is even accepted like this (it should actually just lead to workspaces named "1:kpx output eDP1")
Sometimes it actually does. When I tried to upload something, workspace "3:web output VGA1" had appeared.
