### ISSUE TITLE
i3 bindsym move down not working

### ISSUE THREAD

**Issue by TatriX** [i3/i3#1870]
I have a binding: ```bindsym $mod+Shift+j move down``` which is no longer working.
```i3-msg move down ``` works fine

http://logs.i3wm.org/logs/5743573328723968.bz2
```
Binary i3 version:  4.10.3-289-gea514eb (2015-08-26, branch "next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.10.3-289-gea514eb (2015-08-26, branch "next") (pid 23074)
Loaded i3 config: /home/tatrix/.config/i3/config (Last modified: Thu 21 May 2015 12:02:09 AM MSK, 8531807 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

**Comment by licaon-kter** [comment]
Yep I have this too: https://github.com/i3/i3/issues/1868#issuecomment-135202080 ( this is the commit: https://github.com/i3/i3/commit/bf3cd41b5ddf1e757515ab5fbf811be56e5f69cc at fault )

**xmodmap -pke**: https://gist.github.com/licaon-kter/56d785b0e9b7b509ddb0

**/etc/default/keyboard** ( *dvorak* or not )

> XKBMODEL="logicda"
> XKBLAYOUT="us"
> XKBVARIANT="dvorak"
> XKBOPTIONS=""
> BACKSPACE="guess"
