### ISSUE TITLE
[enhancement] Support _NET_WM_STATE_MAXIMIZED_*

### ISSUE THREAD

**Issue by Airblader** [i3/i3#1874]
We always give tiled windows as much space as possible. Hence, we could set `_NET_WM_STATE_MAXIMIZED_VERT` and `_NET_WM_STATE_MAXIMIZED_HORZ` on tiled windows. Floating windows should not have them set.

According to the spec, we (w|c|sh)ould use this to restore the geometry of a previously floated window which was tiled and is now being floated again.

See http://standards.freedesktop.org/wm-spec/1.3/ar01s02.html

> Maximizing a window should give it as much of the screen area as possible (this may not be the full screen area, but only a smaller 'workarea', since the window manager may have reserved certain areas for other windows). A window manager is expected to remember the geometry of a maximized window and restore it upon de-maximization.

However, we could also argue that this doesn't fit into our model of limited floating support.

**Comment by stapelberg** [comment]
I’m undecided on whether this makes sense. Do any other window managers set the hint? Do any toolkits actually look at the hint?

**Comment by acrisci** [comment]
It might be nice to have some way to differentiate floating windows from tiling windows with some sort of property. I think something like this could give compton users a way to have shadows on floating windows and not tiling windows, but I'm not exactly sure how that would work.

But that's the only use case I can think of and it's not very strong.

**Comment by Airblader** [comment]
I'm not sure if others set the hint or which tools actively use it. I do think that restoring the original geometry makes sense, but we technically don't need those atoms for that at all. I'll try to have a look to see if others set this, though I'm not sure when I get a chance to.

**Comment by Airblader** [comment]
I've just verified that Kubuntu does set these values.

**Comment by stapelberg** [comment]
Based on the fact that others don’t seem to set these hints either, I don’t think we should set them. i3’s user-base is not big enough to convince application authors to use the hint, and the use-case which @acrisci feels unclean — if we wanted to enable that, we should rather set a different (custom?) hint.

**Comment by Airblader** [comment]
@stapelberg Are you sure you didn't misread my last comment? Kubuntu *does* set those values.

**Comment by stapelberg** [comment]
Sorry, I indeed misread that. Okay, so the hint being set is a good start, but do applications actually use it? Perhaps using http://codesearch.debian.net/ is helpful for this.

**Comment by Airblader** [comment]
I'll try to see if I can find something. I'll reopen for the meantime.

**Comment by Airblader** [comment]
@stapelberg  Just from a quick look: gtk2, gtk3, qt, tk, sdl all do *something* with these atoms (though I haven't looked at what exactly), as well as some applications such as stalonetray, docky, mutter, chromium, wine, eclipse, … I also found comments in there that say that for GTK these atoms do in fact represent a kind of "tiling".

There's also code of some other window managers in there which respect this property.

**Comment by stapelberg** [comment]
Okay. Can you find out what the other WMs do with the atom and make a concrete proposal as to what i3 should be doing please?

**Comment by Airblader** [comment]
OK. This will have low priority for now, but when I get the time I'll look into it. By the way, thanks for the hint with the debian code search. I could've used that a few times in the past; so far I had to rely on the Github search.

**Comment by Airblader** [comment]
I couldn't really find anything *useful* being done with this. My proposal for i3 would be the same as initially stated, but I think we don't have a concrete enough reason to add this right now.
