### ISSUE TITLE
Not starting on first configured workspace anymore

### ISSUE THREAD

**Issue by lahol** [i3/i3#1889]
I configured i3 so that I am able to use 22 numbered workspaces. The first ten are from the standard configuration, the next ten are accessed by pressing Ctrl. Until recently, the workspace i3 created after logging in was the first in the configuration file. However, this is not the case anymore. After logging in I now get workspace 11 (i.e. the first with the Ctrl modifier). So, while expecting to start on workspace 1 I landed on workspace 11. I believe commit b68a400abfeb9f17901497eb005862853656287c introduced this behavior (although it fixed the issue of not being able to access the additional workspaces directly).

i3 version:

    % i3 --moreversion 2>&- || i3 --version
    Binary i3 version:  4.10.3-301-gee2983c (2015-09-03, branch "next") © 2009 Michael Stapelberg and contributors
    Running i3 version: 4.10.3-301-gee2983c (2015-09-03, branch "next") (pid 4326)
    Loaded i3 config: /home/lahol/.i3/config (Last modified: Fr 04 Sep 2015 08:48:24 CEST, 1389 seconds ago)
    
    The i3 binary you just called: /usr/bin/i3
    The i3 binary you are running: i3

Log: http://logs.i3wm.org/logs/5130467284090880.bz2

**Comment by stapelberg** [comment]
That’s a good point. I’ll look into why the tests didn’t catch this, and we likely need to keep a copy of the workspace-related bindings in the specified order.

**Comment by Airblader** [comment]
I think we should fix this before the next release since this is a clear regression and will probably affect quite a few people.
