### ISSUE TITLE
The floating window is disappeared after reloading

### ISSUE THREAD

**Issue by hwangcc23** [i3/i3#1910]
Repro:
1). Open a window. Make it floating.
2). Press MOD+Shift+C to reload the configuration file.
3). The window is disappeared.
P.S. If i don't make the window floating, there is no problem.

i3 version:
> Binary i3 version:  4.10.4-316-gc9b6ec7 (2015-09-08, branch "debug-reload-floating") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.10.4-316-gc9b6ec7 (2015-09-08, branch "debug-reload-floating") (pid 31518)
Loaded i3 config: /home/hwangcc23/.i3/config (Last modified: Tue Jul 28 11:42:01 2015, 3821491 seconds ago)

> The i3 binary you just called: /usr/bin/i3
> The i3 binary you are running: i3

Log:
* before reload: http://logs.i3wm.org/logs/5740087962763264.bz2
* after reload: http://logs.i3wm.org/logs/5746821397741568.bz2

Note:
In i3_before_reload.log, I find the window id (0100001c) of the floating window (name: PCManX) from the line 2669:
> 2664 09/10/2015 04:35:28 PM - manage.c:restore_geometry:61 - Re-adding X11 border of 0 px
2665 09/10/2015 04:35:28 PM - manage.c:restore_geometry:65 - placing window 00c00007 (name: i3bar f     or output Virtual1, title: (null)) at 0 1005
2666 09/10/2015 04:35:28 PM - manage.c:restore_geometry:61 - Re-adding X11 border of 1 px
2667 09/10/2015 04:35:28 PM - manage.c:restore_geometry:65 - placing window 00e00003 (name: rxvt, t     itle: (null)) at 0 18
2668 09/10/2015 04:35:28 PM - manage.c:restore_geometry:61 - Re-adding X11 border of 0 px
2669 09/10/2015 04:35:28 PM - manage.c:restore_geometry:65 - placing window 0100001c (name: PCManX      1.2, title: (null)) at 112 124
2670 09/10/2015 04:35:28 PM - restarting "i3"...
2671 09/10/2015 04:35:28 PM - util.c:append_argument:180 - original argument: "i3"

In i3_after_reload.log, the window (window id: 0100001c) is destroyed? (Not sure if my understanding is correct):
> 2575 09/10/2015 04:35:28 PM - handlers.c:handle_event:1342 - event type 10, xkb_base 85
2576 09/10/2015 04:35:28 PM - handlers.c:handle_event:1342 - event type 17, xkb_base 85
2577 09/10/2015 04:35:28 PM - handlers.c:handle_destroy_notify_event:543 - destroy notify for 0x010     0001c, 0x0100001c
2578 09/10/2015 04:35:28 PM - handlers.c:handle_unmap_notify_event:477 - UnmapNotify for 0x0100001c      (received from 0x0100001c), serial 1077

**Comment by Airblader** [comment]
Does this only happen for PCManX or for any application? Because I cannot reproduce this. Also, this *really* doesn't seem like an i3 bug – as you noticed yourself, we receive a destroy notify event. This is something the application triggers.

**Comment by Airblader** [comment]
Please also give us the version of PCManX you're running. I tried it with 1.2 and couldn't reproduce with that either.

**Comment by hwangcc23** [comment]
It also happens for rxvt (v.2.6.4). 
But rxvt is not killed. (I can find it in the output of the ps command)
I will upload i3 logs at home today.

**Comment by hwangcc23** [comment]
P.S. I built PCManX using the latest source code from https://github.com/pcman-bbs/pcmanx. As @Airblader said, it seems the application triggered it (get killed). We can ignore the case of PCManX.

**Comment by Airblader** [comment]
I've tried this with pcmanx-gtk2-git as well now and can't reproduce there either. Nor with urxvt.

**Comment by hwangcc23** [comment]
Log (reproduce with rxvt):
* before reload: http://logs.i3wm.org/logs/5723920363683840.bz2
* after reload: http://logs.i3wm.org/logs/5755812509122560.bz2

**Comment by hwangcc23** [comment]
@spudowiar also reported the problem (issue #1934).
Pressing $mod+Shift+Space (with default bindings) to restore it.

**Comment by spudowiar** [comment]
Mine was actually when restarting but it would make sense that it should also happen when reloading (if you look at the code). What I don't get is why it happens at all! I don't use layout restoring and I tried using Arch's `/etc/i3/config` file

**Comment by spudowiar** [comment]
If you use the commit 57438d270de49a97f1bb55e6730da2ff8621c6ce, does the bug still happen? If you use the commit before 57438d270de49a97f1bb55e6730da2ff8621c6ce, does the bug still happen?

**Comment by spudowiar** [comment]
@Airblader, are you trying without using a stock config file? (something in your config file may affect it)

**Comment by hwangcc23** [comment]
@spudowiar Thanks.  :) I roll back the commit 57438d2 and the problem doesn't happen.

**Comment by Airblader** [comment]
With the default config file I can reproduce this now. I can see that the i3 node has width/height set to 0, which is likely the problem. The question is why it doesn't happen with my normal config file.

**Comment by Airblader** [comment]
The problem seems to come from the `floating_check_size` call in that commit, so the difference in config is likely due to `floating_minimum_size`. I'm investigating this.

**Comment by Airblader** [comment]
I think I found the root cause.

**Comment by spudowiar** [comment]
This is still not working

    i3 version 4.10.4-680-g9b74e6e (2015-09-17, branch "gaps-next") © 2009 Michael Stapelberg and contributors

I can confirm I have the commit 55edbfe

**Comment by Airblader** [comment]
What happens if you actually check that commit out? I could imagine that the root output change interferes with this fix.

**Comment by Airblader** [comment]
Also, I cannot reproduce this anymore with the latest checkout, so for me it seems to work.

**Comment by Airblader** [comment]
@spudowiar Your i3 version says it was compiled on the 17th. That can't have the fix yet.

**Comment by hwangcc23** [comment]
The patch works. Thanks. :)

**Comment by spudowiar** [comment]
mea culpa. I installed to the wrong location and it was being overriden by another installation. The patch works.
