### ISSUE TITLE
Unable to switch sound since last update

### ISSUE THREAD

**Issue by fulljackz** [i3/i3#1922]
Hi, I tried irc channel for some help or troubleshooting without luck.
I dit not use my sound mixer for few days so I can not be sure about the date but it seems that since last debian update (testing), I can not adjust my sound volume with hotkeys on my dell laptop anymore. 

It works times by times and I do not know troubleshoot if it can come from i3 or my volume mixer or my hell laptop !

Here is my i3 version 
```
{0:28}~ ➭ i3 --moreversion 2>&- || i3 --version
Binary i3 version:  4.10.4 (2015-09-08, branch "4.10.4") © 2009-2014 Michael Stapelberg and contributors
Running i3 version: 4.10.4 (2015-09-08, branch "4.10.4") (pid 29360)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```
And here an attached log file : http://logs.i3wm.org/logs/5122107398684672.bz2

Thanks for feedback.

Cheers,

**Comment by Airblader** [comment]
You have these keybindings

    bindsym XF86AudioRaiseVolume exec pactl set-sink-volume 0 +10% #increase sound volume
    bindsym XF86AudioLowerVolume exec pactl set-sink-volume 0 -10% #decrease sound volume

Does adjusting the volume work if you execute the commands from the command line instead of through a shortcut?

**Comment by Airblader** [comment]
Actually I can see in the log that the commands are being called correctly. What makes you think this is a window manager issue?

**Comment by fulljackz** [comment]
Hum, I did not know how to investigate this bug and I though it could come from i3.

Previous command : 
```
{0:35}~ ➭ pactl set-sink-volume 0 +10% 
Échec lors de l'obtention des informations sur la destination : Aucune entité de ce type
```
But it seems that 
```
pactl set-sink-volume alsa_output.pci-0000_00_1b.0.analog-stereo +10%
``` 
runs fine..
Sorry, this simple test drive me to troubleshoot why 0 is neither recognized in my config file.

I think this issue can be closed :confused:

**Comment by Airblader** [comment]
Yeah, this isn't a window manager issue since we just execute the command you configured. The whole pulseaudio thing is pretty cryptic to me as well, if that's any consolation. Maybe look into scripts like ponymixer or pulseaudioctl which are a bit more clever about choosing the sink and so on.
