### ISSUE TITLE
Screen corruption on kvirc

### ISSUE THREAD

**Issue by kadogo** [i3/i3#1939]
Hello,

I have tried to restart i3 with alt+shift+r but it don't change anything.

I have some "screen corruption" or black screen sometimes with different apps.
I'm noticed the screen corruption on kvirc and skype.

I take a screenshot to show what I mean.
https://imgur.com/ltSWZtc

My OS is Debian Jessie and I use the jessie-backport for i3.

i3 --moreversion 2>&- || i3 --version
Binary i3 version:  4.10.2 (2015-04-16, branch "4.10.2") © 2009-2014 Michael Stapelberg and contributors
Running i3 version: 4.10.2 (2015-04-16, branch "4.10.2") (pid 11328)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

I activate logging on the fly and upload it here.
http://logs.i3wm.org/logs/5700735861784576.bz2

Cheers

**Comment by kadogo** [comment]
I just noticed something.
The problem dissapear when I close steam.

**Comment by Airblader** [comment]
i3 isn't actually involved in rendering the client window, so I will close this issue. Typically these are graphics driver issues. I'd recommend running a compositor (e.g., compton), as it usually takes care of such glitches.
