### ISSUE TITLE
Appending layout bypasses unique marks restriction

### ISSUE THREAD

**Issue by swiniopas** [i3/i3#1956]
Either by appending a layout more than once with a mark specified or by marking multiple windows/containers with the same mark manually in the layout file.
![img](https://a.pomf.cat/ygbdfp.png)
i3 version 4.10.4-355-gc82e6a8 (2015-09-24, branch "makepkg") © 2009 Michael Stapelberg and contributors
http://logs.i3wm.org/logs/5699714196439040.bz2

**Comment by Airblader** [comment]
Yeah, I think we can unmark the mark when restoring a container.

**Comment by swiniopas** [comment]
Being able to set marks within the layout file is useful, especially for startup so I hope you don't mean getting rid of that functionality.

**Comment by Airblader** [comment]
No, my proposed fix would be that of we read a mark from a layout file we don't just assign that mark to the new container but also call unmark on all existing containers (for this mark). 

So if a container has that mark and you append a layout that sets it as well, the new container will win and get it.

**Comment by swiniopas** [comment]
Got it. Sounds good to me.
