### ISSUE TITLE
Moving marked container to itself locks up i3

### ISSUE THREAD

**Issue by swiniopas** [i3/i3#1957]
To reproduce open two terminal windows, select parent, mark with i3-input and move container to mark.
i3 freezes with high cpu usage.
i3 version 4.10.4-355-gc82e6a8 (2015-09-24, branch "makepkg") © 2009 Michael Stapelberg and contributors
http://logs.i3wm.org/logs/5682747733442560.bz2

**Comment by Airblader** [comment]
Odd. For this very reason I implemented that a container cannot be moved to itself.

**Comment by Airblader** [comment]
I haven't looked at the code yet but I have an idea of why this happens. I'll look into it tonight or tomorrow.

**Comment by swiniopas** [comment]
Thanks. By the way i noticed some more oddities regarding marks. Is it ok to spam some more issues? :smiley:

**Comment by Airblader** [comment]
Yeah, report everything you got. :) it's even better if it's one issue per... Well... Issue. :)

**Comment by Airblader** [comment]
@swiniopas Can you check out my branch https://github.com/Airblader/i3-original/tree/bug-1957 and see if it fixes this?

**Comment by swiniopas** [comment]
Yep, seems to be fixed in that branch.

**Comment by Airblader** [comment]
Thanks for the feedback!
