### ISSUE TITLE
Draw decorations on own frame for V/H

### ISSUE THREAD

**Issue by Airblader** [i3/i3#1966]
@stapelberg I wonder if there is a good reason why we draw window decorations on the parent container? I understand that it's a design decision that is deeply integrated into the i3 code, but I'd still like to figure out whether it's something we could consider changing given someone does the work.

For stacked and tabbed containers it makes a lot of sense, but I'm not sure this applies to vertically or horizontally split containers as well.
- Is there an actual, technical reason for this? Can we anticipate changes other than the rendering that would become necessary?
- Is it something that could be considered to be changed?

i3 4.10.4

**Comment by stapelberg** [comment]
If you have a really good reason to change it, we might be able to pull it off.

The reason we went for this design is that it unifies the code paths for stacked/tabbed containers and regular containers. I don’t think there’s any technical reason for it.

**Comment by Airblader** [comment]
Thanks for the reply. I will close this issue for now as I have no immediate plans to do this move (and assume no one else does, either). The biggest reason I have in mind for this would likely be fixed by the move to cairo, too (well, once certain bugfixes have propagated enough), so I'll revisit once that happened. Given that we're talking a long time of inactivity on this issue, I'll close it.

**Comment by Airblader** [comment]
Reopening because the move to cairo does not fix the usecase properly, so this would be an option.

**Comment by Airblader** [comment]
@stapelberg I suspect that if we did this change, the values / meaning of things like `deco_rect` could change (we'd have to see). Is your answer, that you're generally not against this, still valid in this case? Might be something for a major version release (?)

**Comment by stapelberg** [comment]
We could retain deco_rect’s semantics when serializing for the IPC interface, right?

**Comment by Airblader** [comment]
I guess we could. My only pain point with it is that as a developer I don't have access to the proper information anymore, unless we add a new key for the new semantics.

**Comment by stapelberg** [comment]
Yes, we should add a new field with the new semantics.

**Comment by Airblader** [comment]
OK. Suggestions for a name welcome :) 

The following list is simply for myself. Please disregard.

- [ ] Come up with a good way to draw decorations for stacked/tabbed. Parent seems logical, but poses a problem due to the recursion approach when rendering decorations. Either one needs to be adapted.
- [ ] Adapt `is_pixmap_needed`, as window-less containers will no longer need a surface.
- [ ] Don't even create windows for window-less containers since we don't need to draw on them anymore.
- [ ] Adapt rendering of all types. Decorations must be respected on the actual leaf container now, not on the parent.
- [ ] Adapt decoration drawing to draw on the window's own container instead of the parent.
- [ ] Expose the new semantics in the IPC reply, make sure the old semantics stays for the existing field.
- [ ] The Hacking Howto docs may need a bit of an overhaul
- [ ] Cry from happiness and go party after having pulled this off.

**Comment by Airblader** [comment]
Just an FYI, I will continue working on this, but between pre-vacation work and then a few weeks of vacation, it might take a while. So inactivity on the ticket should not be mistaken with abandoning working on this.

**Comment by nmschulte** [comment]
What are the benefits of this change?  @Airblader, you note that switching to Cairo could have resolve some issues, but there's no elaboration as to what the issues actually are.

**Comment by Airblader** [comment]
With this implemented compton would actually work properly with i3. However it's unclear how this change should be done for stacked and tabbed containers and remaining completely compatible on the IPC makes this significantly more complex.

**Comment by Airblader** [comment]
@nmschulte Since I have (slightly) more time now:

The move to cairo, as a side effect, improved i3's behavior with opaque windows (think transparent terminals and the like; things we don't actually support in i3 as of now) when window titles are enabled (border style normal). Previously this used to not work at all with glitches all over the place. Now it works *for the most part*, but it's not quite there yet.

Switching to drawing all window decorations on a frame window per window rather than using the parent containers for that (which can hold multiple windows) will remove the reason for these glitches because the frame window no longer has to span multiple windows. Granted, this is an effect really only noticable in i3-gaps and not i3 by now.

But other reasons are compliancy with compositors and other tools. The way i3 handles decorations is just really, really odd. Generally, tools will assume the wm to be either reparenting or non-reparenting, but if it's reparenting (which is really the norm) then they have a specific expectation of how frame windows are used. Pretty much all WMs meet this expectation, but i3 doesn't. From a spec point of view we're totally clean. But it's an awkward concept and just causes issues with such tools, in particular noticable with certain compton parameters.

That's why I think making i3 behave more like tools expect reparenting WMs to behave is an important step in the right direction. However, a rather unique feature to i3 are stacked / tabbed windows and here it's not so clear how not to draw decorations on the parent container because it's really just the natural choice. I think my preferred solution is to render decorations for all tabs on their frame window with that window being drawn as the focused one in each of those renderings. Then we only actually display the frame of the focused window. This does mean we render too many decorations, but we get this penalty back by not requiring a redraw when switching to another tab. This might in fact even be better as it is now because it speeds up the render process.

So that's a lot of explanation on that. It's pretty late, I'm fairly tired so if anything didn't make too much sense please do feel free to ask about it and I'll answer it. :-)

**Comment by xzfc** [comment]
I could try to implement it.

Here some ideas on how to extend this to stacked/tabbed cons.
Non-leaf child cons can be handled in the same way as now, I think, so I'm talking only about leaf children below.

1. (my preference) Share the same frame window for every direct leaf child, and raise an active window.
   But there is a caveat: all child windows should have the same size (i.e. borders of same width), otherwise small parts of underlying inactive windows could be visible. Ways to fix it:
   1. Resize inactive windows to match the size of the active window.
   2. (my preference) Unmap inactive windows.

   Also, see text about depth below.
2. Make each leaf child have its own frame window, and draw all title bars on them (its own title bar + title bars of sibling cons). So, title bars would be duplicated.

---

Right now, i3 frame windows have the same depths as their managed windows, but this will not be possible if we implement (1). I propose to use `root_depth` (usually 32 bit) for every frame. Consequences:

1. This would reopen #3297, but since it is fixed in GTK3, it's not an issue now.
   Awesome doesn't handle this, and we probably don't need it either.
   At a pinch we can re-implement the following workaround from awesome: https://github.com/awesomeWM/awesome/pull/2280 (not merged as considered not required).
2. Together with #3478, this will make code cleaner. We could use single global gc for everything.
3. And this plays well with RGBA borders.

**Comment by Airblader** [comment]
Thanks for giving this some thought!

> Share the same frame window for every direct leaf child

I'm not really following. Can you explain this a bit more? Do you mean the window of the parent (as it is now)?

> (my preference) Unmap inactive windows.

Out of the two options also the only one I think would be feasible. This would essentially kill `_NET_WM_STATE_HIDDEN` support which we'd be removing with this (not that that's particularly bad). I wonder if there is some historic reason why the non-active windows in a tabbed/stacked container remained mapped (@stapelberg Any ideas?).

> Make each leaf child have its own frame window, and draw all title bars on them

I don't think this would be so bad either, to be honest. It would keep the codepaths the same, I think. 

> This would reopen #3297, but since it is fixed in GTK3, it's not an issue now.

If it works in awesome, I think it should work for us, too. :-) The rest also sounds fine.

---

In any case, please note the points further up in this issue regarding compatibility on the IPC, which makes this quite a bit trickier to implement. I believe the IPC needs to be designed separately, but for a prototype I think we can ignore the IPC's compatibility and first just get a feeling for the actual change.

**Comment by stapelberg** [comment]
> if there is some historic reason why the non-active windows in a tabbed/stacked container remained mapped (@stapelberg Any ideas?).

It just never occurred to me to unmap non-active windows. In my mind, mapping/unmapping is reserved for workspace switches, and stacks just bring windows to the foreground.

**Comment by Airblader** [comment]
One reason I just thought of that goes against unmapping is the Shape extension support. I think we'd be upsetting people here.

**Comment by xzfc** [comment]
@Airblader 
> I'm not really following. Can you explain this a bit more? Do you mean the window of the parent (as it is now)?

The window which have titlebar pixmap. So, yes.

<details><summary>Example for T[A B]</summary>

(1)
```
* root
  * (i3) frame around T[A B]
    * subwindow: (A) application window
    * subwindow: (B) application window
    * pixmap: titlebar T[A B] and window borders
```

(2)
```
* root
  * (i3) frame around T[A B]
    * subwindow: (A) application window
    * pixmap: titlebar T[A B] and window borders
  * (i3) frame around T[A B]
    * subwindow: (B) application window
    * pixmap: titlebar T[A B] and window borders
```

As opposed to current way:
```
* root
  * subwindow: (i3)
    * pixmap: titlebar T[A B]
  * subwindow: (i3) frame around A
    * subwindow: (A) application window
    * pixmap: window borders
  * subwindow: (i3) frame around B
    * subwindow: (B) application window
    * pixmap: window borders
```
</details>

> > Make each leaf child have its own frame window, and draw all title bars on them
>
> I don't think this would be so bad either, to be honest. It would keep the codepaths the same, I think.

One minor disadvantage: this would require O(N*N) memory for titlebar pixmaps instead of O(N).

> One reason I just thought of that goes against unmapping is the Shape extension support. I think we'd be upsetting people here.

Shape for tiled isn't supported at the moment. However, it breaks transparent window workflow, so, probably it doesn't worth that then.

**Comment by Airblader** [comment]
> One minor disadvantage: this would require O(N*N) memory for titlebar pixmaps instead of O(N).

Yeah, but I'm not sure the asymptotic behavior is too critical here.

> However, it breaks transparent window workflow, so, probably it doesn't worth that then.

We don't generally support that, but I agree that it's not good to intentionally break it since withh some applications like peek this is quite useful for some users.

**Comment by stapelberg** [comment]
> > if there is some historic reason why the non-active windows in a tabbed/stacked container remained mapped (@stapelberg Any ideas?).
> 
> It just never occurred to me to unmap non-active windows. In my mind, mapping/unmapping is reserved for workspace switches, and stacks just bring windows to the foreground.

I gave unmapping invisible windows in stacked containers a shot a while ago and ended up abandoning the approach, as it caused significant delays when switching focus between windows (tested with chrome browser windows and urxvt terminal emulator windows).

Most likely, applications/toolkits are written with the same assumption: unmapping happens only when minimizing (older window managers) or when switching to a different workspace (more modern window managers).
