### ISSUE TITLE
[enhancement] Move to the new Travis infrastructure

### ISSUE THREAD

**Issue by Airblader** [i3/i3#1968]
It needs to be verified if we can even reasonably do this at the moment. See http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

**Comment by stapelberg** [comment]
The biggest problem I see is that we need a bunch of packages from a newer Ubuntu than the 12.04 with which both infrastructures run (according to http://docs.travis-ci.com/user/ci-environment/).

**Comment by Airblader** [comment]
Yeah. I had a look at the packages and I think we currently can't move over because of some of the Perl modules (and maybe more).

**Comment by stapelberg** [comment]
The perl packages you can install into ~/perl5, see e.g. http://michael.stapelberg.de/cpan/

**Comment by stapelberg** [comment]
We should try to move to Ubuntu trusty instead, I think? http://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta/

**Comment by Airblader** [comment]
I'm going to close this as the best approach seems to be to update the Travis build as we go along and as Travis updates their machines.
