### ISSUE TITLE
[enhancement] support _NET_WM_WINDOW_TYPE_NOTIFICATION

### ISSUE THREAD

**Issue by Airblader** [i3/i3#1969]
Just like the other window types we already have. This notification is used, for example, for Chrome's desktop notifications but also by HipChat.

**Comment by stapelberg** [comment]
When you say “handle”, do you mean treating the window as if override_redirect=1 is set? fvwm seems to do that according to https://www.mail-archive.com/fvwm-workers@fvwm.org/msg02611.html

**Comment by Airblader** [comment]
No, I think setting override_redirect is the job of the application. I just want to handle it in the same sense as most other ones, which is allowing command criteria to select on it. 

However let me look into whether they're already given override_redirect anyway because I don't remember them being managed.

**Comment by stapelberg** [comment]
Ah, I see. Supporting it for command criteria is fine with me. In fact, why don’t we support all _NET_WM_WINDOW_TYPE_* for that?

**Comment by Airblader** [comment]
We already do. The ones the spec explicitly lists anyway. At least that's what I did when I added them. This one just came up more than once so it seemed worth it. 

We should only add it if any application uses it without override_redirect, though.

**Comment by Airblader** [comment]
The examples I know of use override_redirect, so there's no reason for us to support this type at the moment. If we find examples without override_redirect, we can revisit.

**Comment by ccryx** [comment]
As far as I can tell KDE Plasma 5.3 uses _NET_WM_WINDOW_TYPE_NOTIFICATION for its notifications without setting override_redirect resulting in the notifications being managed by i3. I have added the functionality to match for this window type and it seems to not cause any undesired behavior so far.

**Comment by Airblader** [comment]
@ccryx How did you manage to match on this window type? We currently don't support it. Anyway, thanks for the hint that Plasma uses this. I'll reopen.

**Comment by Airblader** [comment]
If you mean you actually implemented support for this, it'd be great if you could submit it as a PR. I think we have reason to support it now.
