### ISSUE TITLE
Neo layout still not handled correctly

### ISSUE THREAD

**Issue by Sohalt** [i3/i3#2000]
```
$ i3 --moreversion 2>&- || i3 --version
Binary i3 version:  4.11 (2015-09-30, branch "4.11") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.11 (2015-09-30, branch "4.11") (pid 833)
```
http://logs.i3wm.org/logs/5700983627710464.bz2

i3 4.11 finally made it into my distros package repos and I just tried it but the issues mentioned in #1835 still persist and have even gotten worse in that my previous hack to accomplish bindings on different layers using Mod3 (`bindsym $mod+Mod3+i focus left`, etc.) doesn't work anymore.
Keybindings using characters from higher layers don't work and strangely `$mod+ß` also doesn't work, even though ß is on the first layer.
I used `$mod+ß` and `$mod+>` to test.

**Comment by stapelberg** [comment]
“ß” is not a keysym, “ssharp” is. Use xev(1) to get the appropriate keysyms.

**Comment by Sohalt** [comment]
Oh, right, thanks. Sorry, didn't think about that. Yet the arrow keys on layer 4 don't work either and they use the correct keysym "Right", "Left", etc. Also correcting ß to ssharp didn't help.

**Comment by stapelberg** [comment]
Please post an updated log.

**Comment by Sohalt** [comment]
Ouch, somehow I managed to get rid of my notification daemon, which of course made testing the keybinding with notify-send impossible… Welp stupid me. `$mod+ssharp` is working now (with 'ß' being on layer 1.
Yet `$mod+greater` still doesn't work and neither do the neo arrow keys (both on higher layers).
http://logs.i3wm.org/logs/5067160539889664.bz2

**Comment by stapelberg** [comment]
Use `bindsym $mod+Mod5+greater` and `bindsym $mod+Mod3+Up`. You can get the modifiers from looking at the output of `xmodmap` (without parameters) and looking at which keysyms get triggered in `xev(1)` when you press the key you want to bind.

Note that keysyms are case-sensitive, so you’ll need to use `Up`, not `up`.

**Comment by Sohalt** [comment]
Ok, thanks! Everything is working now.
So I have to specify the modifiers explicitly and in addition to the actual keysym of interest.
Not what I had hoped for but manageable. In essence it has the same downside as my hack pre 4.11 in that you have to specify separate bindings for the neo arrows and don't get them automatically with the `$mod+Up` etc. bindings.
Is there a way to make i3 ignore certain modifiers? `ISO_Level5_Shift` and `ISO_Level3_Shift` are sort of a direct part of the neo keyboard layout in that they enable different layers. So essentially there is no situation where they could be used as actual modifiers for other keys, since the layout already incorporates them making for example `ISO_Level3_Shift+g` an impossible combination since that automatically translates to a `>` (but i3 still detects the held down ISO_Level3_Shift therefore disambiguating it from a "simple" `>` and complicating the config).

**Comment by stapelberg** [comment]
> Is there a way to make i3 ignore certain modifiers?

No. We want the keyboard handling to be precise, and any sort of hack that we introduce would make things ambiguous.

**Comment by Sohalt** [comment]
Ok, thanks. Very valid concern.
I guess I'll have to live with the duplication in the config file then, but knowing there are good reasons for it makes it easier.
