### ISSUE TITLE
Moving to empty workspace using "move window to mark" crashes i3.

### ISSUE THREAD

**Issue by miseran** [i3/i3#2003]
I've been trying to use the new "move window to mark" feature for some scripting, and encountered a crash when targeting an empty marked workspace.
I ran the following minimal example for the log:

On an empty workspace, open a terminal. Run

    i3-msg 'focus parent; mark test' 

Move the terminal window to another workspace and focus it again. Run

    i3-msg 'move window to mark test'

At this point, i3 crashes.

    $ i3 --moreversion 2>&-
    Binary i3 version:  4.11 (2015-09-30, branch "4.11") © 2009 Michael Stapelberg and contributors
    Running i3 version: 4.11 (2015-09-30, branch "4.11") (pid 541)
    Loaded i3 config: /home/myname/.local/config/i3/config (Last modified: Fri 16 Oct 2015 05:58:48 PM CEST, 2883 seconds ago)
    
    The i3 binary you just called: /usr/bin/i3
    The i3 binary you are running: i3

http://logs.i3wm.org/logs/5640941595525120.bz2
(I accidentally ran the second command once before the first, so that's also included in the log. And I failed to use the default config.)

The backtrace only says `No stack.`

**Comment by Airblader** [comment]
This makes no sense to me. If you leave the workspace empty and then focus the terminal on the other workspace, it means you're switching workspaces – which implies that the marked workspace will be closed and the mark disappears.

Haven't looked at the log yet, though.

**Comment by Airblader** [comment]
I can reproduce it by staying on the marked, empty workspace and just predefining a window on some other workspace to be moved there.

**Comment by miseran** [comment]
Ah, I should have mentioned that I have a dual screen setup, and in the test, the empty workspace was kept open on the second screen.

**Comment by Airblader** [comment]
I have an idea where the problem might be, I'll check it out.

**Comment by Airblader** [comment]
We die on an assertion failure in `src/ipc.c` in the `get_workspaces` handler:

````
TAILQ_FOREACH(ws, &(output_get_content(output)->nodes_head), nodes) {
            assert(ws->type == CT_WORKSPACE);
```

So I guess we're inserting the container incorrectly.
