### ISSUE TITLE
[enhancement] Support for key sequence bindings

### ISSUE THREAD

**Issue by stereolink** [i3/i3#2009]
This is a feature request to have key sequence bindings like in vim where you can have any number of symbols used to form a binding.

I.e., right now bindings are of the form `Mod+[Shift/Ctrl]+<1 symbol>` (e.g. `Mod+d`). Feature request is asking for there to be the option of 1+ symbols (e.g. `Mod+d+s`). 

If `Mod+d` and `Mod+d+s` both exist as bindings, i3 would capture the first part `Mod+d`, then wait for other sequences `s`, if it times-out then use `Mod+d`.

Using version 4.11. No log file.

**Comment by stapelberg** [comment]
We’ve discussed this before in #1410 and #662.
