### ISSUE TITLE
[enhancement] Allow for multiple marks on a single window

### ISSUE THREAD

**Issue by Adaephon-GH** [i3/i3#2014]
At the moment each window can only have one (unique) mark.  Marking an already marked window overwrites the old mark with the new one.  This is fine when you are using marks only to either manually tag a few windows or in one or two scripts/command chains. But if you want to make more extensive use of marks, for example mixing manual marks with scripts using them or having a larger number of scripts using them - things can go ugly. 

As only one mark can be placed on a window at a time, the chance that a previously set mark is inadvertently removed by another script/commands rises with the number of places where marks are used. This may break command combinations and could be especially annoying if manually set marks suddenly vanish.

I would like it to be possible to set more than one mark on a single window (similar to vim). The syntax of the currently available commands ``mark`` and ``unmark`` could remain the same for downward compatibility with older configurations. Although it would probably be useful if ``unmark`` were a bit more versatile than just remove one mark or remove all marks on all windows. For example by taking regex as argument and/or an option remove all marks on a specified window (focused or by criteria; e.g. ``unmark --window``). With active ``show_marks``, multiple marks could be shown as comma-separated list in the title bar.

**Comment by Airblader** [comment]
As long as one mark cannot be used on multiple windows, this should be fine.

**Comment by Adaephon-GH** [comment]
Yes, marks should still be removed from other windows if they are applied to a new window.

**Comment by stapelberg** [comment]
Fine with me, I think.

**Comment by Airblader** [comment]
Are you going to work on this yourself? Otherwise I'd do it.

**Comment by stapelberg** [comment]
I have no plans for working on it myself, so feel free to go ahead.

**Comment by Airblader** [comment]
Sorry, I meant Adaephon :)

**Comment by Adaephon-GH** [comment]
@Airblader please, go ahead. 

If I could, I would. But my C-skills are very limited (non-existent). So, thank you for offering.

**Comment by Airblader** [comment]
@Adaephon-GH Alright.
@stapelberg Just a thought, but this *is* a breaking change in terms of behavior. Is this OK?

**Comment by stapelberg** [comment]
In which ways exactly does it break? The original enhancements mentions backwards-compatibility.

**Comment by Airblader** [comment]
Any script that assumed that setting a new mark erases the previous one would break. The actual commands stay compatible API-wise. Also the container structure changes, for any script using GET_TREE to parse marks. The latter seems to be something we rarely ever consider (and perhaps shouldn't since we should consider the tree structure internal and not API, imho).

**Comment by stapelberg** [comment]
We could just add this functionality to the mark command by using e.g. `mark --add`, right?

The GET_TREE reply is actually an API, at least everything which is documented on http://i3wm.org/docs/ipc.html#_tree_reply — anything else is fair game to change, within reasonable bounds obviously.

**Comment by Airblader** [comment]
Okay, I'll go for an additional flag.

**Comment by Airblader** [comment]
@Adaephon-GH BTW, I've decided against the regex matching when unmarking for now. We'd be forced do introduce a flag for it and overall I think it's really easy to use `GET_MARKS` and do the matching yourself.

**Comment by Adaephon-GH** [comment]
@Airblader  I agree that it should be easy to script, so leaving out regex matching for ``unmark`` is fine by me.

I had a look at your changes and saw that you implemented criteria for ``unmark`` as a way to unmark specific windows. This should help with most, if not all use cases.

But I am not sure how I would go about completely unmarking the current window (only). As I said, my understanding of C is not that great, so I may be overlooking something, but it looks like the default for ``unmark`` is still to affect all marks/windows if no criteria are given (understandably so, as to not break backward compatibility). Unfortunately this sets ``unmark`` apart from any other command, which affect only the current window if no criteria are given. As far far as I can see there is no way to explicitly specify only the current window with criteria (probably because it is not needed for any of the other commands). 

Of course one could use the special value ``focused`` for the ``title``, ``class``, ``instance``, ``window_role`` and ``workspace`` criteria, but even combining all five does not necessarily match only the current window. An other way would be to use one of the marks on the current window as matching criterion, but that would require an automated way to get that mark (IMHO, if I scripted that, I would not need the criterion anymore).

So, did I miss something? If not (and providing I am not just imagining a use case), the question would be if there should be a criterion that only matches the current window (e.g. ``[id=focused]`` and/or ``[con_id=focused]``) or if there should be an option to ``unmark`` (e.g. ``--focused``).  While the option would solve the immediate issue, extending the criteria could be useful for other commands if you want to do something with the focused window only if it fulfills also some other criterion.

**Comment by Airblader** [comment]
Yeah, you're right. @stapelberg What's the best way to handle this? I'm somewhat against introducing this as a flag on a single command, it seems inconsistent.

I think we either break compatibility by having `i3-msg unmark` only remove the marks on the focused window (which I will just assume @stapelberg won't like) or, my prefered solution, we allow `[con_id=__focused__]`. This is unnecessary for the majority of commands, but at least it's consistent by using the criteria mechanism.

We could, of course, declare it a "non-problem" and simply advise users to figure out the focused window id in a script and pass it to the command.

**Comment by stapelberg** [comment]
I’d prefer introducing `con_id=__focused__` for this use-case.

**Comment by Airblader** [comment]
Alright! @Adaephon-GH So this will work now

````
[con_id=__focused__] unmark
```

**Comment by acrisci** [comment]
This change broke my ipc libraries.

**Comment by Airblader** [comment]
@acrisci We discussed this above, see @stapelberg's comment:

> The GET_TREE reply is actually an API, at least everything which is documented on http://i3wm.org/docs/ipc.html#_tree_reply — anything else is fair game to change, within reasonable bounds obviously.

**Comment by acrisci** [comment]
Yeah I should have been paying attention. Maybe I'll try to extend that documentation so we can have this to be stable. I bet you also broke Sway as well. Please try to remember to ping me on ipc changes so I can update my libraries faster.

**Comment by Airblader** [comment]
> Maybe I'll try to extend that documentation so we can have this to be stable.

That sounds fine, I think marks have reached a mature state anyway.

> I bet you also broke Sway as well.

sway is still missing the tree reply, so I doubt that.

> Please try to remember to ping me on ipc changes so I can update my libraries faster.

That's fair, I'll try to remember.
