### ISSUE TITLE
[enhancement] Background and border in status blocks

### ISSUE THREAD

**Issue by Airblader** [i3/i3#2022]
Some time ago we introduced setting a background color for urgent status blocks. The main concern against setting border and background individually (as done for workspace buttons) was that doing only the urgent background is a "feet in the water" step.

i3bar rendering has come a long way since, we have had no problems with the urgent background and on top, i3-gaps offers setting border and background per statusblock successfully (and has for a long time now).

My proposal is to add a `background` and a `border` key to the JSON API to specify colors for a block. Nonpresence means not drawing background/border, respectively, which provides full compatibility.

Usecases are a more controlled visibility of certain blocks, but also being able to make blocks look like buttons, which makes sense in the context of click events.

**Comment by stapelberg** [comment]
SGTM.
