### ISSUE TITLE
Weird screen tearing below floating window - new Hangouts chromium extension

### ISSUE THREAD

**Issue by japhir** [i3/i3#2067]
Hi there! This might be an issue on the part of Hangouts, but I thought I'd submit anyway and see if you guys can help me out.

This image shows the problem that's occurring. What happens is that when I move the floating little button window (that expands when I click it, I think it's trying to be transparent) it moves a large section with of the background with it. Resizing has even more drastic effects. I currently have an even weirder looking one open but it contains personal information so I uploaded this image instead.
![2015-11-15-20 27 11-region](https://cloud.githubusercontent.com/assets/10659193/11170586/21470096-8bd9-11e5-997b-f450816896ae.png)

Here are the logs: http://logs.i3wm.org/logs/5191954035900416.bz2
I'm running this version: Binary i3 version:  4.11 (2015-09-30, branch "4.11") © 2009 Michael Stapelberg and contributors.

**Comment by Airblader** [comment]
Sorry, I'm a little lost. Can you be more specific what button it is and how to get there?

**Comment by japhir** [comment]
I installed the newest Google Hangouts App from [https://chrome.google.com/webstore/detail/google-hangouts/knipolnnllmklapflnccelgolnpehhpl?hl=en](here). I'm also confused by the many different versions of hangouts apps/extensions/plugins, but this one seems pretty fun if it's running correctly.

**Comment by Airblader** [comment]
OK, that's the extension. Now where exactly do I find the button you are clicking? Just opening the Hangouts window from that extension is working fine for me.

Also, are you running a compositor such as compton?

**Comment by japhir** [comment]
Updated above before I read your reply ;).

Yes, I've recently started using compton because I still have some vsync issues on my primary monitor (I have 2) when watching video.

**Comment by Airblader** [comment]
Thanks, now I could reproduce it. Yeah, I too think it wants to be transparent. However, the window only has a 24bit depth. I suggest you file the bug with the Plugin creator. We don't support transparency either way, but using compton it generally works, but the app, of course, has to do it the right way.

Maybe it also wants to do very weird fake transparency.

**Comment by japhir** [comment]
Thanks for looking into it!
