### ISSUE TITLE
Error while building i3

### ISSUE THREAD

**Issue by hydride0** [i3/i3#2069]
Hi, I'm experiencing the following error while compiling i3wm:
``` 
   [i3] Generating command parser
    /bin/sh: ../generate-command-parser.pl: Permission denied
    src/i3.mk:62: recipe for target 'i3-command-parser.stamp' failed
    make: *** [i3-command-parser.stamp] Error 126
    make: *** Waiting for unfinished jobs....
```
It seems like it's trying to use /bin/sh to launch a perl script, so I tried modifying src/i3.mk in lines 63 and 68 adding the "perl" command before "../generate-command-parser.pl" and it works.

Binary i3 version:  4.11-107-gb255d14 (2015-11-16, branch "next")
Running i3 version: 4.11-100-gf836e4c (2015-11-03, branch "next")
OS: Arch Linux

**Comment by stapelberg** [comment]
> It seems like it's trying to use /bin/sh to launch a perl script, so I tried modifying src/i3.mk in lines 63 and 68 adding the "perl" command before "../generate-command-parser.pl" and it works.

Nothing in the Makefile is specifically using /bin/sh, it’s just that make uses a shell to execute commands.

I believe the filesystem on which you’re working might be mounted noexec. Is that it?

What happens when you run ./generate-command-parser.pl manually?

**Comment by hydride0** [comment]
> ./generate-command-parser.pl 
zsh: permission denied: ./generate-command-parser.pl
> perl generate-command-parser.pl
Input file "" does not exist! at generate-command-parser.pl line 25.

**Comment by hydride0** [comment]
> ./generate-command-parser.pl 
zsh: permission denied: ./generate-command-parser.pl
> perl generate-command-parser.pl
Input file "" does not exist! at generate-command-parser.pl rine 25.

**Comment by stapelberg** [comment]
What’s the output of `mount`, `df -h .` and `strace -v -s 2048 -f sh -c ./generate-command-parser.pl`?

**Comment by hydride0** [comment]
Uhm, yeah, it's mounted with noexec
Sorry, didn't know about that
