### ISSUE TITLE
[enhancement] workspace new

### ISSUE THREAD

**Issue by Nycroth** [i3/i3#2072]
I'm adding a `workspace new` command to i3 that changes the current workspace to the next unused numbered workspace.

Interested in the patch?

**Comment by stapelberg** [comment]
I’m not sure. I can imagine a number of different behaviors that make sense depending on one’s workflow, and I’m not convinced a single “workspace new” command can reasonably handle them all. E.g.:

Switch to a not-currently-existing workspace based on…

* the next unused number
* the next not-currently-existing workspace that has a name (possibly in combination with a number)
* the next unused number on the current output

And likely there are more.

I think the best way to proceed is to implement your addition as a little script using the IPC interface and then tell people on the i3-discuss mailing list about it.

What do you think?

**Comment by Nycroth** [comment]
I haven't looked into how it currently works in the source, but I planned to reuse the code that already handles when the last workspace on one output is moved to another.

Didn't know about the mailing list. Checked in with IRC and they said I should open an issue.

I'm more than happy to tool my work to meet the community's needs. I just have a script file sitting around that runs `i3-msg rename workspace to "ws$RANDOM"` that I want to get rid of.

**Comment by acrisci** [comment]
https://github.com/acrisci/i3ipc-python/blob/master/examples/workspace-new.py

**Comment by Nycroth** [comment]
People really love showing me that i3 has an IPC...

**Comment by stapelberg** [comment]
I’m going to close this issue for now in favor of fulfilling this use-case via the IPC interface. In case it turns out that there is significant user demand and my earlier comments can actually be dismissed with a clearly correct way to implement it, we can revisit.
