### ISSUE TITLE
[enhancement] Run mouse bindings on the root window

### ISSUE THREAD

**Issue by Airblader** [i3/i3#2097]
A mouse binding like

    bindsym --whole-window $mod+button4 workspace next

will only work on windows, but not on an empty workspace. We should allow selecting mouse bindings on the root window itself. Either by default when `--whole-window` is given or via another flag such as `--include-root-window`.

**Comment by stapelberg** [comment]
What’s the use-case you have in mind for a click on the root window?

**Comment by Airblader** [comment]
@stapelberg https://faq.i3wm.org/question/7528/scrolling-trough-workspaces/

**Comment by stapelberg** [comment]
That sounds reasonable.

**Comment by Airblader** [comment]
Do you have a preference regarding a separate flag?

**Comment by stapelberg** [comment]
I think we should not add a separate flag unless we have to.

**Comment by Airblader** [comment]
OK, then let's go with doing this if `--whole-window` is set.
