### ISSUE TITLE
i3wm crash on removing external hdmi

### ISSUE THREAD

**Issue by pniederlag** [i3/i3#2098]
no suspend/resume this time involved(to my knowledge), now it happend just when unplugging the external hdmi monitor.

debian testing/unstable
i3 version 4.11-129-gc490a60 (2015-11-30, branch "next") © 2009 Michael Stapelberg and contributors

backtrace:
https://gist.github.com/pniederlag/414849b8b1efe56d323c

log:
http://logs.i3wm.org/logs/5696758453633024.bz2

**Comment by Airblader** [comment]
How did you create the backtrace? Unless I'm reading it wrong, it makes no sense to me.

**Comment by pniederlag** [comment]
Just pressing b in Crash Dialog. 
Timestamp Matches.

**Comment by stapelberg** [comment]
With regards to the backtrace: either the version of your binary does not match the version of your debug symbols (an old i3-wm-dbg package floating around?) or we’re seeing memory corruption.

**Comment by Airblader** [comment]
Is there a good, systematic approach to dealing with this backtrace in this case? It's really all over the place and I'm not seeing how it'd be useful.

Since the problem currently isn't reliably reproducible, it's also not an option to run it under valgrind.

@pniederlag Can you try to see how easy you can reproduce this? Once we can reproduce this at least one out of x times (x being sufficiently small), we'd have options like bisecting etc.

**Comment by stapelberg** [comment]
> Is there a good, systematic approach to dealing with this backtrace in this case?

The specific backtrace that was provided (https://gist.github.com/pniederlag/414849b8b1efe56d323c) is just not useful, I don’t think there’s anything we can do with it. As I mentioned, my first guess would be that there is a symbol mismatch, so if @pniederlag still has the core dump lying around, a proper backtrace might be obtainable by re-installing the precise version of the binary and symbols that were used at the time of the crash.

**Comment by pniederlag** [comment]
As I am on a fresh restart now any old logs are probably lost. 

<pre>
i3:amd64/sid 4.11.1-1+g4.11-129-gc490a601 upgradeable to 4.11.1-1+g4.11-134-g04be42f1
i3-wm:amd64/sid 4.11.1-1+g4.11-129-gc490a601 upgradeable to 4.11.1-1+g4.11-134-g04be42f1
i3-wm-dbg:amd64/sid 4.11.1-1+g4.11-129-gc490a601 upgradeable to 4.11.1-1+g4.11-134-g04be42f1
</pre>

Will upgrade to -134 right now.

From what I think all i3-wm related packages should be on same version. I think at one time I read something like "nightly has debug symbols build in", so I'd like to get your confirmation that the above package selection is appropriate for debugging. 

Not sure on how to find/identify any old/obsolete binaries lying around (never built i3 myself yet, just packacked installs).

Hopefully backtrace/log will be more helpfull next time. Currently I do see crashes about once or twice a week.

Thx for you patience and assistance.

**Comment by pniederlag** [comment]
here is another fresh one, unplugging hdmi-monitor, i3wm crashed

backtrace:
https://gist.github.com/ae488621efab79e87e1c

log:
http://logs.i3wm.org/logs/5751700212154368.bz2

**Comment by Airblader** [comment]
Thank you, that backtrace makes more sense. It seems like the problem is that we're working on a con which has been detached because of the output being disconnected, which causes the workspace to be `NULL`, causing the crash.

@pniederlag Could it be that the crash happens if a container on the workspace on the output that you disconnected was set to urgent? If you're unsure, please try opening a shell on that output, then execute `sleep 5; echo -e "\a"` and switch focus to a window on the other output. A few seconds later, the shell should be marked urgent. Now disconnect the output to see if i3 crashes.

We appreciate your help with this.

**Comment by Airblader** [comment]
My previous theory was slightly off. It's not a detached container we are dealing with, but an output container (simply looking at the backtrace will tell you this). Since outputs are higher up in the hierarchy than workspaces, we end up with `NULL` there.

**Comment by pniederlag** [comment]
I could not reproduce the crash by the procedure that you described (`sleep 5; echo -e "\a"`a) but I did experience quite some crashes today in relation with suspend/resume and plug/unplugging external monitor.

backtrace:
https://gist.github.com/27ab568d8958c2781a47

log:
http://logs.i3wm.org/logs/5648334039547904.bz2

hth,
Peter

**Comment by Airblader** [comment]
Yeah, that's the same bug. Can you please tell me what applications you had open on the output you removed? How did you start them? Especially try to find similarities between the incidents.

It's pretty clear what the fix looks like, but I want to understand how we even get into this situation because I currently don't see how we end up there.

**Comment by pniederlag** [comment]
ok, here's the next one, before unplugging i tried your hint once more (closing most other workspaces and applications beforehand, add terminal on workspace attached to external monitor, run `sleep 5; echo -e "\a"`a).

unplug: fine
running xrandr to adapt randr config to current setup: -> crash

log:
http://logs.i3wm.org/logs/5724681378201600.bz2

backtrace:
(sry, must have forgotten to dump backtrace?)

**Comment by Airblader** [comment]
What really confuses me about your log files is that I don't see something like this in there:

````
12/09/2015 07:37:04 PM - randr.c:randr_query_outputs:785 - destroying disappearing con 0xd00ea0
```

> running xrandr to adapt randr config to current setup: -> crash

How exactly did you run xrandr, i.e., with which options?

Anyway, I think it's obvious what happens here. What I don't understand is HOW it happens. Can you run a `i3-msg -t get_tree > /tmp/layout.json` before(!) unplugging? Once you see the crash, provide that file.

**Comment by Airblader** [comment]
@pniederlag Did you have any luck with the layout file?

**Comment by pniederlag** [comment]
as the problem is not reproducible by will it's tough to run a script before. :(

I just had a crash again today, after about 4 days of stable operations.

backtrace:
https://gist.github.com/1bc7eeff05b7f04a749c

log:
http://logs.i3wm.org/logs/5643440998055936.bz2

**Comment by Airblader** [comment]
> as the problem is not reproducible by will it's tough to run a script before. :(

I was hoping you could just run the script and unplug, run the script and unplug and so on to see if it happens after a while.

Backtraces and logs aren't really useful anymore. They'll always look the same.

**Comment by Airblader** [comment]
@stapelberg Do you happen to know if / when an output container can have the urgency flag?

This bug is really easy to fix, but I'm hesitant to do so unless we understand how we get into this situation as we might be fixing a symptom.

**Comment by stapelberg** [comment]
So, the direct cause is that `output->con` has `urgent == true`, which shouldn’t happen. Looking at the logfile, I can see that even the root window has the urgent flag set:

```
09.12.2015 13:24:08 - Trying to restore the layout from "/run/user/1000/i3/restart-state.12418".
09.12.2015 13:24:08 - con.c:con_new_skeleton:52 - opening window
09.12.2015 13:24:08 - x.c:x_con_init:150 - Adding window 0x01e00064 to lists
09.12.2015 13:24:08 - x.c:x_con_init:154 - adding new state for window id 0x01e00064
09.12.2015 13:24:08 - load_layout.c:tree_append_json:576 - read 19498 bytes
09.12.2015 13:24:08 - start of map, last_key = (null)
09.12.2015 13:24:08 - con.c:con_new_skeleton:52 - opening window
09.12.2015 13:24:08 - key: id
09.12.2015 13:24:08 - int 38385184 for key id
09.12.2015 13:24:08 - key: type
09.12.2015 13:24:08 - string: root for key type
09.12.2015 13:24:08 - key: orientation
09.12.2015 13:24:08 - string: horizontal for key orientation
09.12.2015 13:24:08 - key: scratchpad_state
09.12.2015 13:24:08 - string: none for key scratchpad_state
09.12.2015 13:24:08 - key: percent
09.12.2015 13:24:08 - double 1.000000 for key percent
09.12.2015 13:24:08 - key: urgent
09.12.2015 13:24:08 - bool 1 for key urgent
```

Now the question is which of the various pieces of code that touch the `urgent` member are broken.

@Airblader We could add a function that verifies a number of conditions before setting `urgent` to true, then call that everywhere. That way, we might be able to locate the code path that causes the unintended state. What do you think?

**Comment by Airblader** [comment]
Yes, sounds like a good plan to me.

**Comment by Airblader** [comment]
It's a little bit of a stretch, but I wonder if #2132 also fixes this issue.

**Comment by pniederlag** [comment]
Just FYI: crashes still happening and appearing more frequent again. Still not able to produce at will and didn't manage to capture the tree before a crash yet. Is it really just me on debian testing/unstable seeing crashes with suspend/resume in relation to plug/unplug external monitor?

**Comment by Airblader** [comment]
@pniederlag I will try to write the patch we spoke of above soon so that you can run i3 with that patch until the crash happens. That should (hopefully) clear everything up.

**Comment by pniederlag** [comment]
I updated to a more recent version of i3-wm yesterday (debian/nightly build of https://github.com/i3/i3/commit/891bd6e3e5a955de4832053cfa292ba4dbf91874)

I'll let you know how this turns out, as you mentioned the meanwhile closed #2132 could be related.

**Comment by Airblader** [comment]
@pniederlag Out of curiosity, have you run into this since? If not, would you have expected to run into it?

**Comment by pniederlag** [comment]
I do still see crashes about every other day. However I am still without a clue on the circumstances that trigger them. It always happens shortly after unplugging and suspend/resume-cycles, at least that's what I think.

The more I try to produce a crash it just won't happen.

Sry I can't give more valuable input, big thx for taking so much care of your users! Will try to frequently run this script, anything else that could be worth tracking before suspending/plugging?

    #!/bin/bash
    LOG_NAME=/tmp/i3-$(date +"%Y-%m-%d-%H-%M-%S").tree
    i3-msg -t get_tree > $LOG_NAME

**Comment by Airblader** [comment]
I just wanted to make sure the other fix didn't fix this as well. We'll go with that patch we talked about – when I get around to it. I'm very busy at the moment.

**Comment by ndemou** [comment]
Just a quick "me too": it's rare (as in once every many days) but it happens. Dual monitor laptop. External monitor is also HDMI on mini-DP to HDMI converter. 

Sorry but I failed to get a backtrace although I've installed i3-wm-dbg for this purpose.

**Comment by hashhar** [comment]
I'd like to chime in on this. I'm seeing similar crashes (more like lockups) when I close the lid (or the display turns off) and open it again.

The screen turns back on but all I can see is the desktop background and the i3bar (completely static, it does not update). This was the first time it happenned, so I'll try adding additional details and logs later in the day.

**Comment by pniederlag** [comment]
#2252 seems to be a crash with similar conditions (on a more recent i3wm version)

**Comment by stapelberg** [comment]
@Corni @pniederlag Could you confirm that the just pushed fix addresses the issue for you please?

In case it doesn’t, could you build i3 with the following patch and supply the resulting backtrace(s) please?

```diff
diff --git i/src/con.c w/src/con.c
index 124d24e..30aa1f8 100644
--- i/src/con.c
+++ w/src/con.c
@@ -1957,6 +1957,12 @@ void con_update_parents_urgency(Con *con) {
 
     bool new_urgency_value = con->urgent;
     while (parent && parent->type != CT_WORKSPACE && parent->type != CT_DOCKAREA) {
+        if (parent->type != CT_CON && parent->type != CT_FLOATING_CON) {
+            ELOG("con %p is not a con, but type %d\n", parent, parent->type);
+            // crash
+            char *nullptr = 0;
+            *nullptr = 0x23;
+        }
         if (new_urgency_value) {
             parent->urgent = true;
         } else {
diff --git i/src/workspace.c w/src/workspace.c
index 0c80f69..90a94cb 100644
--- i/src/workspace.c
+++ w/src/workspace.c
@@ -793,7 +793,13 @@ static bool get_urgency_flag(Con *con) {
 void workspace_update_urgent_flag(Con *ws) {
     bool old_flag = ws->urgent;
     ws->urgent = get_urgency_flag(ws);
-    DLOG("Workspace urgency flag changed from %d to %d\n", old_flag, ws->urgent);
+    DLOG("Workspace urgency flag of con %p changed from %d to %d\n", ws, old_flag, ws->urgent);
+    if (ws->type != CT_WORKSPACE) {
+        ELOG("con %p is not a workspace, but type %d\n", ws, ws->type);
+        // crash
+        char *nullptr = 0;
+        *nullptr = 0x23;
+    }
 
     if (old_flag != ws->urgent)
         ipc_send_workspace_event("urgent", ws, NULL);
```

**Comment by Corni** [comment]
So I've been running this since the 5th of september and I had i3 not crash once anymore. So I *think* this is fixed, but as the bug doesn't occur in a reproducible way, I'm not 100% sure.

**Comment by stapelberg** [comment]
Thanks for confirming. I suppose if there still are problems, people will speak up :).

**Comment by albasili** [comment]
I'm not sure if my issue is related or not, but I have random crashes of i3 on resume. What typically happens is that on resume I need to press Ctrl+Alt+F1 to have at least the gnome login manager to fire up, then, if i3 is still working correctly it presents me the lock. Unfortunately sometimes (not clear when) i3 seems not to restart and the system falls back to the gnome login and at that point, once logged in I'm back into i3 but with all processes crashed (luckily I can recover most of the stuff).

I'll post logs and config as soon as I manage to know where to find them....
