### ISSUE TITLE
Extremely tiny unreadable fonts with 4k monitor

### ISSUE THREAD

**Issue by zenny** [i3/i3#2110]
Hi,

My i3 version is at 4.11:

>$ i3 --moreversion 2>&- || i3 --version
>Binary i3 version:  4.11 (2015-09-30, branch "4.11") © 2009 Michael Stapelberg and contributors

Logfile at:
http://logs.i3wm.org/logs/5684961520648192.bz2

The fonts are rendered extremely tiny (unreadable) with i3 in 4k monitor.

§1. Tried with 

> startx -- -dpi 196

which just increased the size of the workspace conky-i3bar, but not of i3staus bar nor of other application windows.

§2. Appended a line in .i3/config file with a larger fontsize:

> font pango:DejaVu Sans 10

§3. Tried with:
> xrandr --dpi 196'

§4. Appended with 

> Xft.dpi:        196

in .Xresources file.

On all accounts, there was no change at all.

Found a similar thread at
https://www.reddit.com/r/linux/comments/31d0wp/i3_and_hidpi_display_everything_is_to_tiny/

Thanks!

**Comment by Airblader** [comment]
You still are using a monospaces font:

    12/15/2015 10:07:56 AM - config_parser.c:parse_config:313 - CONFIG(line  16): font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1

As @stapelberg explained on the mailing list, this cannot be scaled. You mentioned you have the same issue with a scalable pango font, so please attach the log file using that.

**Comment by Airblader** [comment]
I'm going to close this now quite early since this bug report never contained anything that justifies a bug. @zenny If you can provide a log file with a pango font causing this, please let us know here and we'll reopen.
