### ISSUE TITLE
[enhancement] Add tests for mouse bindings on empty workspaces

### ISSUE THREAD

**Issue by Airblader** [i3/i3#2115]
See discussion on #2108:

> Side note: having tests for this would be cool. Given that we have https://github.com/i3/i3/blob/next/testcases/lib/i3test/XTEST.pm now, perhaps adding support for ButtonPress events is doable?

This refers to #2097

**Comment by acrisci** [comment]
We need something like libxdotool for perl.

**Comment by stapelberg** [comment]
Why? We already have i3test::XTEST which handles all that’s necessary for key bindings. I think it’s a small jump to make it also support button presses.

**Comment by acrisci** [comment]
> Why?

Because I want to use it outside of the test cases and all the current xtest libraries are too complicated to learn to do the goofy things I want to do with it. But for that case, maybe python is better.
