### ISSUE TITLE
Feature request: make workspace_auto_back_and_forth aware of workspaces, displays and focus

### ISSUE THREAD

**Issue by phinicota** [i3/i3#2118]
I was told this is currently not possible. Here is what I suggest:
So I have 6 workspaces (WS) on display 1 and other 6 on display 2. I have this enabled in my .i3/config:
```
workspace_auto_back_and_forth yes
```

**What I got**: when I'm in WS 4 (mod+4) and switch to 5 (mod+5), mod+5 will take me back to 4. (How it is supposed to work apparently)

**What I wanted**: if WS 5 is on display 2, after a press mod+5 again, I would like it to restore the WS I was on display 2 (and the focus to display 1, where I was)

**Problem Detailed**: let's say I got WS 1-5 in display 1, and 6-10 on display 2.
1.If I have currently WS 1 on display 1 and WS 6 on display 2 (and I'm focusing WS 1).
2.Then I switch switching to WS 7 with mod+7 (Display 2)
3.Then mod+7 again will take the focus back to WS1 on display 1 but it will not switch display 2 back to WS 6.

Is there a way to make workspace_auto_back_and_forth be aware of the current display and focus?

**Comment by stapelberg** [comment]
This is a reasonable use-case, but I’m not keen on making back-and-forth occupy more mental (and code) complexity in i3 than it already has.

I think your suggestion should be implemented as an external script using the IPC interface.

**Comment by Sohalt** [comment]
Has anybody written a script that does this via IPC?
This is exactly the behavior I'm looking for with back_and_forth in a multi monitor setup.

**Comment by WillForan** [comment]
I tried scratching this itch: https://github.com/WillForan/wf-utils/blob/master/i3/i3-back_within_output

**Comment by Psykar** [comment]
Another script that does more what I was hoping:
https://github.com/i3/i3/issues/2118

**Comment by Psykar** [comment]
Another script which does more what I was wanting (hooks back and forth behaviour to swap any monitors back to what they were before swapping to the new workspace, rather than having it's own binding)

https://github.com/Psykar/i3-backandforth-externalmonitor

**Comment by tom-doerr** [comment]
Here's a more minimalist script that also does this: https://github.com/tom-doerr/i3_workspace_toggle

**Comment by mreppen** [comment]
And here is another version that can both restore previous "views" or only cycle within the current workspace: https://github.com/mreppen/i3_output_back_and_forth
