### ISSUE TITLE
Feature request: support putting arbitrary windows into i3bar

### ISSUE THREAD

**Issue by hyiltiz** [i3/i3#2119]
There are many useful applets provided by other desktop environments. One can call the Application Menu provided by KDE5 by simply running `plasmawindowed org.kde.plasma.kicker` from a command line as a window, which can be interacted by clicks. 

It is possible to keep this as floated sticky window, but having a native way to put this window as a i3bar icon would be ideal. In the i3 User Guide, how to manually creating tray icons is not documented (if this feature is already implemented).

**Comment by acrisci** [comment]
:-1:

**Comment by Airblader** [comment]
I think embedding windows just like any other tray icon is the job of the requesting application, not the job of the embedding application. 

Sounds to me like KDE does it the same way by providing a separate utility for that. And since i3 is not a DE, I think such a tool should live outside of i3.

That is if I understood the request correctly. A video or picture would indeed help.

**Comment by Airblader** [comment]
Also, FYI, Michael stated some time ago that i3bar is intended to display information on workspaces, not windows, which is why we don't display things like number of windows and so on. 

To further rule out a misunderstanding I feel exists in the original post: creating tray icons is not the job of i3bar. We provide the interface to embed a window, but providing something to be embedded is the responsibility of the application that wishes to be embedded.

**Comment by hyiltiz** [comment]
i3wm as a Window Manager does not provide a Application Menu, as it should not. However, having an overview of all installed applications would really be great. Maybe a lightweight program based on ncurses would do it. Here I have KDE along with i3wm, so that I can use some of its applications when needed. So, it would be great to just use what KDE already provides to have that feature. Running `plasmawindowed org.kde.plasma.kicker` shows this Application Menu "icon" (plasmoid/applet) in a window, and it servers its intended purpose. However, it is too big. One way to workaround is making its size small, then make it sticky to a location where it does not annoy any other window. 
![kickerastrayicon](https://cloud.githubusercontent.com/assets/3246683/11834385/fa6abc78-a399-11e5-99a6-0cf23219a99a.png)

Or a better approach; if we could somehow export this application within a windows as a "tray icon object" as this fcitx tray icon, then we can click on it for all interaction, and it does not annoy any other window there. 

So, is it possible to transform this into a tray icon?
![fcitx-tray](https://cloud.githubusercontent.com/assets/3246683/11834390/018c285c-a39a-11e5-984b-524ceebf4773.png)

**Comment by hyiltiz** [comment]
I have been able to achieve what I meant above by the sticky window. 

```
floating_minimum_size 3 x 3

for_window [title="Application Menu"] floating enable, sticky enable, border none, resize set 20 20, move position 1350 680
exec_always --no-startup-id plasmawindowed org.kde.plasma.kicker
```

Here is how it looks like:
![sticky](https://cloud.githubusercontent.com/assets/3246683/11835066/b471989e-a39f-11e5-9fa0-23c566a40290.png)

Functionality achieved, but is a very hacky (ugly) workaround.

**Comment by stapelberg** [comment]
I agree with what @Airblader said.

**Comment by hyiltiz** [comment]
@Airblader said:

>We provide the interface to embed a window, but providing something to be embedded is the responsibility of the application that wishes to be embedded. 

The last clause is amusingly twisted that I did not quite understand. However, he said "the interface to embed a window" is provided. I was not able to find this API documented. Did he refer to this: http://i3wm.org/docs/4.2/userguide.html#_tray_output ? If so, it is not clear how this API would allow a user to embed a window into the i3bar. If not, then I think I should read the amusingly twisted clause several dozen times :grinning:

**Comment by stapelberg** [comment]
He means that i3bar implements the [XEMBED standard](http://standards.freedesktop.org/xembed-spec/xembed-spec-latest.html). X11 applications can make use of that, it’s not something that end-users can configure.

**Comment by hyiltiz** [comment]
Thank you @stapelberg ! I found from [this](http://doc.qt.io/qt-5/qtwidgets-desktop-systray-example.html) example that implementing a system tray object is *not* trivial, and as you pointed out, *not* something that end-users can configure. 

Maybe I should be content with my current configuration. Maybe I can do a small project, if feasible, to come up with a program that wraps an arbitrary window and exports it as a system tray icon object during this winter, if there is not already one out there somewhere.
