### ISSUE TITLE
[enhancement] Make formatting work with latest clang 

### ISSUE THREAD

**Issue by Airblader** [i3/i3#2174]
We currently require clang35 to be used for formatting the code. I wonder whether we can make a newer version behave the same (as is, the formatting changes).

**Comment by stapelberg** [comment]
Or we could just not bother and have a flag day where we switch from one to the other :).

**Comment by Airblader** [comment]
And change the formatting? SGTM. When? :)

**Comment by stapelberg** [comment]
Once I see proof that the version of clang-format you have in mind is available on travis, Debian testing and Arch Linux :).

**Comment by Airblader** [comment]
Arch won't be a problem. It seems like Travis isn't there yet, though.

**Comment by Airblader** [comment]
@stapelberg How does that Travis commit help with clang? :)

**Comment by stapelberg** [comment]
It uses debian sid for builds, which has clang 3.6.

**Comment by Airblader** [comment]
Ah, I see.

**Comment by stapelberg** [comment]
Filed https://llvm.org/bugs/show_bug.cgi?id=30353 for the unexpected line breaks found in https://github.com/i3/i3/pull/2335.

**Comment by stapelberg** [comment]
clang-format-3.5 was now removed from Debian unstable. We’ll need to upgrade to clang-format ≥ 3.7 or work around this issue in our travis config.
