### ISSUE TITLE
[enhancement] Spacer support for i3bar

### ISSUE THREAD

**Issue by kalsan** [i3/i3#2175]
As far as I know, it's not possible to use spacers with i3bar by piping from an external tool such as conky. It would be great to have a special unicode symbol trigger a spacer. Say, if I have Wireless and a clock and I want the Wireless to be displayed all the way left and the clock all the way right, I could separate them with that special unicode symbol.
This is just an idea. I think it would make i3 even cooler.

**Comment by Airblader** [comment]
I think this is a duplicated of #1148 which talks about centering, but at it's core it's the same issue.
