### ISSUE TITLE
[feature request] Restrict focus left/right to the active output screen in multi-output setup

### ISSUE THREAD

**Issue by blessed** [i3/i3#2180]
Hey, thanks for the great work on this excellent WM!

I think it would be great to have an option to limit _focus left/right_ only to the currently active output (the one that has a focused window). I think this optional behaviour could work the same as if there was only one output where _focus left/right_ just wraps to last/first container on the output.

**Comment by Airblader** [comment]
For context:

*  
https://www.reddit.com/r/i3wm/comments/4399ni/cycle_through_windows_and_workspaces_inside_only/
* https://faq.i3wm.org/question/1028/switch-focus-only-on-current-output/

**Comment by stapelberg** [comment]
The `_tree_next()` function (used for changing focus) is already really complicated. I’m wary of adding anything to it.

I would suggest to implement this in a third-party program/script using the IPC interface, but I can see how even just reaching feature parity with the current focus implementation might be rather involved :|.

Any good ideas on how to move forward?

**Comment by Airblader** [comment]
> Any good ideas on how to move forward?

I agree that `_tree_next` is quite complex, but I don't think it's unmanagable. We shouldn't be afraid of our codebase. Touching complex functionality is possible by leaving the code cleaner than we found it and by covering it with testcases.

**Comment by stapelberg** [comment]
I agree in principle (and we do have good test coverage), but still, `_tree_next` is one of the hairier parts of our code. In case it can be cleanly refactored into multiple functions, it might just become simple enough that adding this feature is easy. (In that case, we’d still need to weigh the mental complexity against the additional use, but let’s worry about that later.)

**Comment by cornerman** [comment]
I am really interested in this feature, which is why I made a small patch to see if it can be implemented with just a few changes (https://github.com/cornerman/i3/commit/b9d7de14321f12ab862d2be96e24ad1164f4adf9). It adds a config directive ```focus_keeps_workspace``` and, if enabled, just rejects changing the workspace in the ```_tree_next``` function. I am not entirely sure, whether I missed something or whether this is what you want at this point, as you mentioned that this function should be refactored first. What do you think?

**Comment by acrisci** [comment]
My opinion is that there is not a compelling enough use case for this to add a config directive.

To do this with the ipc without implementing `tree_next`, you could detect whether or not the focus would switch to another output, and delegate to the proper focus <direction> command in case it will not.

**Comment by cornerman** [comment]
For multi-monitor users, the use case is to have all workspaces behave the same with directional focus. So that directions only apply within the current workspace and not on the output level. As of now, it depends whether there is an output in that direction.

Additionally, I think that if this should be implemented, the same would need to be done for the ```move <direction>``` command. So, it might be a bit cumbersome to duplicate the same behaviour in an external script.

**Comment by acrisci** [comment]
> For multi-monitor users, the use case is to have all workspaces behave the same with directional focus

But why would you want this?

**Comment by cornerman** [comment]
> But why would you want this?

It is a nice way to switch between the two outermost windows with focus left/right. Also, it can easily happen to mistakenly move focus or another window to a different output, which can be confusing especially with a beamer. I want to explicitly leave the current workspace resp. output.

**Comment by jbriales** [comment]
If you got here AS desperate as I was, frustrated by not having this functionality, you'll love this: https://github.com/mota/i3-cycle

**Comment by logosity** [comment]
+1 to i3-cycle! +100 to i3!!
(BTW, I wanted this functionality so I could approximate the ALT+TAB behavior found in other window managers/UIs). And yes, I can learn new idioms/key combos, but there's other people to consider - I want to make my machine as hospitable as possible for someone to pair with me, without having to teach them my idomatic WM layout! I3 makes this super easy in general, and i3-cycle added the final touch! Here's how I mapped ALT+TAB using i3-cycle:

```
#alt-tab
bindsym Mod1+Tab exec i3-cycle right
bindsym Mod1+Shift+Tab exec i3-cycle left

```

**Comment by memeplex** [comment]
I think this is mostly desirable in connection with focus wrapping. Once you expect focus to wrap I find it pretty confusing to sometimes end up in another screen and sometimes not, depending on the direction of the focus change. Also, wrapping is useful for "blindly" (without having to think about directions) switching between 2/3 children and having two monitors connected implies that that kind of workflow suddenly becomes restricted to just one (arbitrary) direction.

**Comment by pkieltyka** [comment]
this ticket would certainly be more intuitive then the default behavior. has anyone found a workaround to make this happen? perhaps i3-msg to list workspaces, and if it returns a grouping by output device, instead of using `workspace next` or `workspace prev`, can specify the workspace directly to jump to, but, of course this would have a bunch of overhead

**Comment by pkieltyka** [comment]
btw, I ended up writing a utility to provide this functionality, written using Go i3 IPC https://github.com/pkieltyka/i3-powertools

**Comment by laurvas** [comment]
Found an easy solution

![2019-02-07-111604_806x609_scrot](https://user-images.githubusercontent.com/4542045/52398844-7f101980-2acb-11e9-9187-8f036540272e.png)

**Comment by AtreyaSh** [comment]
## i3-cycle workaround

Issue was fixed for me upon using i3-cycle: https://github.com/mota/i3-cycle. I simply replaced my focus up/down/left/right with i3-cycle equivalents. This also circumvents the need for a `force_focus_wrapping` call in your i3 config file.

### Snippet from local i3 config file
```
# changing focus within same workspace with legacy focus
# bindsym $mod+Left focus left
# bindsym $mod+Down focus down
# bindsym $mod+Up focus up
# bindsym $mod+Right focus right

# changing focus within same workspace with i3-cycle
bindsym $mod+Left exec i3-cycle left
bindsym $mod+Down exec i3-cycle down
bindsym $mod+Up exec i3-cycle up
bindsym $mod+Right exec i3-cycle right
```

## New issue and another workaround

However, this created a new unforeseen issue which was not present with the previous `focus` calls. As an example, assume I create a new workspace and execute the following i3 keyboard commands (bug only appears when using keyboard bindings, cannot be reproduced with direct i3-msg terminal commands):

1. i3-sensible-terminal ($mod+Enter)
2. split h ($mod+h)
3. i3-sensible-terminal ($mod+Enter)
4. split h ($mod+h)
5. i3-sensible-terminal ($mod+Enter)

The resulting workspace would have 3 terminals as shown below. 

```
|        | |        |        |
|   1    | |   2    |   3    |
|        | |        |        |
```

If using the old keybindings with `focus` calls, I would be able to change focus between terminals seamlessly. However, with the `i3-cycle` calls, I would get stuck in a cycle between terminals 2 and 3, and would not be able to reach terminal 1.

I am unsure why this discrepancy occurs, but I observe that the error arises by double-inputting split h where it was not necessary. But sometimes inadvertent mistakes do happen during work, so it would be good to mitigate this error nonetheless. To do this, I simply created a script which checks the split mode of a focused window. If the split mode of the focused window is the same as your intended split, the split keybinding does nothing. In this way, the error with regards to `i3-cycle` gets eliminated.

### Snippet from local i3 config file
```
# split in horizontal orientationi
bindsym $mod+h exec --no-startup-id ~/.config/i3/scripts/splitH.sh

# split in vertical orientation
bindsym $mod+v exec --no-startup-id ~/.config/i3/scripts/splitV.sh
```

### splitH.sh
```shell
#!/bin/bash
# code for layout adapted from https://www.reddit.com/r/i3wm/comments/50aptl/how_can_i_get_the_current_workspaces_layout/dafqxe1?utm_source=share&utm_medium=web2x
test=$(i3-msg -t get_tree | jq -r 'recurse(.nodes[]) | select(.nodes[].focused == true)
 | .layout')
if [ $test = "splitv" ]; then
	i3-msg split h
fi
```

### splitV.sh
```shell
#!/bin/bash
# code for layout adapted from https://www.reddit.com/r/i3wm/comments/50aptl/how_can_i_get_the_current_workspaces_layout/dafqxe1?utm_source=share&utm_medium=web2x
test=$(i3-msg -t get_tree | jq -r 'recurse(.nodes[]) | select(.nodes[].focused == true)
 | .layout')

if [ $test = "splith" ]; then
	i3-msg split v
fi
```
