### ISSUE TITLE
[feature request] Option to hide edge borders for workspaces with a single window

### ISSUE THREAD

**Issue by avrelaun** [i3/i3#2188]
Hi, thank you for this wonderful tiling wm !

It would be nice if we could have a "smart" option for edge borders:
- No borders when there's a single window in a workspace
- Borders when there are multiple windows in a workspace

Why:
- When managing multiple terminals in a workspace, the borders makes it easier to know where the focus is, but when there is only one it's obvious where the focus is.
- When there's only a web browser for example, the borders are actually counter-productive since it makes clicking a side scrollbar or a tab a bit harder (if I smash my cursor to the side or the top of the workspace, I have to move it in the other direction by just a few pixels to be able to grab it)

It seems some work was already done here:
https://github.com/ashinkarov/i3-extras/blob/master/0x2493-patches/smart-border.patch
and here:
https://github.com/i3/i3/pull/2070

Could I pick the remainings of the last PR ?

**Comment by jolange** [comment]
Hi,
are you aware of [`hide_edge_borders`](http://i3wm.org/docs/userguide.html#_hiding_vertical_borders)?

**Comment by Airblader** [comment]
Yes, he is. The linked pull request extends this directive by one option.

**Comment by jolange** [comment]
Oh, sorry, I only saw the patch, but not the PR.

**Comment by avrelaun** [comment]
@jolange I tried to be clearer by editing the title, which flooded this thread (sorry !)

But yeah, the idea is to have hide_edge_borders disabled by default, but enabled in workspaces with one window.
