### ISSUE TITLE
[enhancement] Support desktop window of file managers

### ISSUE THREAD

**Issue by alessandro-g89** [i3/i3#2189]
I made some changes to support the desktop window of file managers (I tested pcmanfm and nautilus).

Disclaimer: I know this is not a feature which the authors are really interested in. I made it mainly for myself,  but I think I should also discuss it here before publishing the patch somewhere else.  

The approach is based on [this old issue](https://github.com/i3/i3/issues/903), with additional handling of the focus state: when only floating windows and a desktop window are visible, the focus can be toggled by moving the mouse, clicking (if configured with "focus_follows_mouse no") or using the keybindings for "focus toggle/tiling/floating". I found this is enough for me to make the desktop window functionality comparable to common desktop environments.

No big technical changes are involved, as there is only one additional variable used to store the ID of the desktop window. If merging is a possibility, I'll setup a repository and issue a proper pull request.

**Comment by Airblader** [comment]
I'm strongly against this as it goes against our philosophy. We have floating windows for dialogs and only dialogs (and the like). The situation of floating windows on a workspace is very unusual for what we intend and once a tiled window is open, the desktop is unusable. 

There are many better ways to do this in i3, like binding modes or launchers like dmenu, roti, lighthouse,...

**Comment by Airblader** [comment]
That said, since the linked issue is three years old, I'm not going to close this issue right away and rather let @stapelberg say whether his views changed.

**Comment by stapelberg** [comment]
I agree — desktop windows go against the philosophy of a tiling window manager.
