### ISSUE TITLE
Window aspects affect displaying of content

### ISSUE THREAD

**Issue by Guanox** [i3/i3#2207]
Hello, since today I have been experiencing something I would call screen tearing inside some programs, namely chromium and slack.

logfile: http://logs.i3wm.org/logs/576414474567680

    /tmp λ i3 --moreversion 2>&- || i3 --version
    Binary i3 version:  4.11 (2015-09-30, branch "4.11") © 2009 Michael Stapelberg and contributors
    Running i3 version: 4.11 (2015-09-30, branch "4.11") (pid 12789)
    Loaded i3 config: /home/guano/.config/i3/config (Last modified: Wed 10 Feb 2016 19:07:12 CET,     966 seconds ago)

    The i3 binary you just called: /usr/bin/i3
    The i3 binary you are running: i3-with-/i3

Here's some pictures of how it appears: 
[pic](http://i.imgur.com/eY8nADA.png )
[pic](http://i.imgur.com/S0ts5UR.png) 
This tearing happens whenever I scroll the content, or move the cursor around inside the application

This picture shows the same application that is affected by the tearing(chromium) but after opening a terminal next to the app,  the tearing goes away
[pic](http://i.imgur.com/gxZDcFj.png)

**Comment by Airblader** [comment]
i3 is not involved in the rendering of the client, hence closing this. The common problems here are a) graphics driver and b) compositor settings.
