### ISSUE TITLE
[enhancement] Allow compositors to identify floating windows

### ISSUE THREAD

**Issue by Airblader** [i3/i3#2223]
While we don't officially support compositing, I think it's an indisputable fact that many users use i3 with a compositor. For a while I tried to see whether there is anything in the specs that would allow a compositor to tell floating and tiling windows apart, but with little luck.

I propose that we introduce a "proprietary" atom that we maintain on windows to indicate this state. Maybe something like `I3_FLOATING_WINDOW`. This would allow users to select such windows conditionally in their compositor configurations.

Example usecases for this are drop shadows on floating windows or transparency changes for floating windows.

I think this would be a nice-to-have feature for a large group of people while at the same time cheap to maintain.

**Comment by stapelberg** [comment]
Sounds good to me.
