### ISSUE TITLE
Remapping `Control + h` to `BackSpace` works inconsistently.

### ISSUE THREAD

**Issue by amosbird** [i3/i3#2227]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.11 (2015-09-30, branch "4.11")

URL to a logfile as per http://i3wm.org/docs/debugging.html

http://logs.i3wm.org/logs/5764748591235072.bz2

**What I did:**

I’m pressing Control+h in Firefox input box with i3 binding `bindsym control+h exec "xdotool getactivewindow key -clearmodifiers --window %1 BackSpace"`

**What I saw:**

1. Firefox's inbox box gets unfocused and focused again.
1. With input method framework active, this keybinding bypasses the input method. This issue only happens in GTK and QT applications.
1. VirtualBox GUI will stuck <kbd>Control</kbd> if <kbd>h</kbd> gets released first.

**What I expected instead:**
Same as pressing <kbd>BackSpace</kbd>

BTW, keybinding <kbd>Control</kbd>+<kbd>l</kbd> `--->` <kbd>Enter</kbd> also faces the same problem.

**Comment by Airblader** [comment]
Does it work if you use

    bindsym --release control+h exec "xdotool getactivewindow key -clearmodifiers --window %1 BackSpace"

?

**Comment by amosbird** [comment]
no

**Comment by Airblader** [comment]
Your `xdotool` command doesn't work for me even when run manually without any keybinding. What does work is this:

    bindsym --release control+h exec "xdotool key --clearmodifiers BackSpace"

**Comment by amosbird** [comment]
It performs worse than the previous `xdotool` command.

**Comment by Airblader** [comment]
Can you please be more specific on this? 

I really don't see an i3 issue here. We grab a key and execute a command. The command is executed. What doesn't work is the xdotool command but that's not i3's fault.

**Comment by amosbird** [comment]
Ok. I will open an issue there. It would be great if i3 could support sending key events directly.

**Comment by Airblader** [comment]
I would've loved to first get some more details than just "it's worse than before". My command works for me, yours didn't even work when run from a terminal. Saying "it doesn't work" isn't really helpful.

**Comment by amosbird** [comment]
I really don't know how to describe this problem literally. I think I should upload a screencast sometime later.
