### ISSUE TITLE
Reloading config while in a non-default binding mode confuses i3

### ISSUE THREAD

**Issue by kalgynirae** [i3/i3#2228]
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.11 (2015-09-30, branch "4.11") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.11 (2015-09-30, branch "4.11") (pid 19320)
Loaded i3 config: /etc/i3/config (Last modified: Tue 13 Oct 2015 11:06:45 AM PDT, 11438064 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5734616174428160.bz2

**What I did:**

1. In a terminal, I ran `sleep 2 && i3-msg reload`.
2. I entered `resize` mode by pressing Alt+r.
3. Two seconds passed and i3 reloaded the config.

**What I saw:**

i3bar still reported that I was in `resize` mode, but i3 acted like I was in the default mode.  Entering resize mode again and then exiting it normally put i3bar back to normal.

**What I expected instead:**

Reloading the config should not cause i3 to return to the default mode.  Alternatively, if the former is not possible for technical reasons, i3 should properly inform i3bar that it has returned to default mode after reloading the config.

**Comment by Airblader** [comment]
I think the best approach here is to switch into the default mode. We have no guarantee that the current mode will even still exist after the config has been reloaded and using the default mode as a fallback seems like unnecessary complexity for a really rare situation to me.
