### ISSUE TITLE
Gnome3 apps starts with border none

### ISSUE THREAD

**Issue by freed00m** [i3/i3#2237]
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.11 (2015-09-30, branch "4.11") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.11 (2015-09-30, branch "4.11") (pid 798)
Loaded i3 config: /home/frdm/.i3/config (Last modified: Wed 02 Mar 2016 15:09:36 CET, 14533 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

_REPLACE: i3 version output_

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5725637813731328.bz

**What I did:**

I started the logging on the fly, and opened Nautilus file manager
Then I used keysim to change it's border to pixel 2 and back to none

```
# change borders
bindsym $mod+u border none
bindsym $mod+y border pixel 2
```

**What I saw:**

Nautilus (and evince, gedit, eog and so on) had no borders when selected when started.

**What I expected instead:**

Nautilus to have border pixel 2 like other gtk3 apps (this behavior is only for gnome3 gui apps) on startup because there is no class interfering with it. 

Note: Pressing of `$mod+y border pixel 2` have the desired effect and spawns border of pixel 2 size.

This is what I use in config, and if I delete all the for_window and restart i3 the gnome apps have no borders either so I am thinking it's a conflict with gnome 3 gui or something.

```
# Configure border style <normal|1pixel|pixel xx|none|pixel>
new_window pixel 2
new_float normal

# Hide borders
hide_edge_borders none

# Open specific applications in floating mode
for_window [title="alsamixer"] floating enable border normal
for_window [class="Calamares"] floating enable border normal
for_window [class="Clipgrab"] floating enable
for_window [class="Pidgin"] border normal
for_window [title="File Transfer*"] floating enable
for_window [class="Galculator"] floating enable border pixel 2
for_window [class="GParted"] floating enable border normal
for_window [class="Lightdm-gtk-greeter-settings"] floating enable
for_window [class="Lxappearance"] floating enable
for_window [class="manjaro-settings-manager-gui"] floating enable border normal
for_window [title="MuseScore: Play Panel"] floating enable
for_window [class="Nitrogen"] floating enable border normal
for_window [class="Pavucontrol"] floating enable border normal
for_window [class="Qtconfig-qt4"] floating enable
for_window [class="Thus"] floating enable border normal
for_window [class="(?i)System-config-printer.py"] floating enable border normal
for_window [class="arandr"] floating enable border normal
for_window [class="Timeset-gui"] floating enable border normal
for_window [class="(?i)virtualbox"] floating enable border normal
```

Maybe related to this issue, this is in my gtk3/gtk.css however firefox gtk3 has no issue with borders.

```
.window-frame {
  box-shadow: none;
  margin: 0;
}

.titlebar {
 border-radius: 0;
}
```

**Comment by Airblader** [comment]
This is because those windows set `_MOTIF_WM_HINTS` which tell the window manager to not draw decorations. Everything's working as intended here.

If you want to force the border, you could use

````
for_window [class=".*"] border pixel 2
```
