### ISSUE TITLE
"move position mouse" doesn't move to the visible workspace

### ISSUE THREAD

**Issue by Airblader** [i3/i3#2241]
If a window is on a currently non-visible workspace, but is moved via `move window to position mouse`, it is not moved to the visible workspace, but instead just moved to the mouse position on the non-visible workspace.

i3 4.11

**Comment by Airblader** [comment]
`move position center` has the same behavior of not moving it to the current workspace.

@stapelberg Do we even want to do this? Or do we want it to be up to the user, who can, of course, just do `[…] move window to workspace current, move window to position mouse`?

**Comment by stapelberg** [comment]
I think the `move position mouse` command should do what it says and no more, i.e. it should stay as-is. If users want to have the window/container be moved to the current workspace, they should combine the commands you suggested.
