### ISSUE TITLE
Hidden window not centered when appearing

### ISSUE THREAD

**Issue by aacebedo** [i3/i3#2262]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12 (2016-03-06, branch "4.12") (pid 1500)
Loaded i3 config: /home/aacebedo/.i3/config (Last modified: sam. 06 févr. 2016 10:00:16 CET, 3320602 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:
http://logs.i3wm.org/logs/5750943224168448.bz2

**What I did:**
1. Invoke albert application (https://github.com/ManuelSchneid3r/albert) and run Thunar
2. Close Thunar
3. Reinvoke albert 

**What I saw:**
Albert window is not centered in the middle of the screen but is located in the top left corner of the screen.

**What I expected instead:**
Albert window shall be centered in the middle of the screen.
I've filled this bug because albert's developer already tried to solve this issue and pointed the fact that it works on awesome and shall work on i3 too (https://github.com/ManuelSchneid3r/albert/issues/125), so he thinks it's a i3 issue.

**Comment by Airblader** [comment]
CC @ManuelSchneid3r

Looking both at your logfile and mine when I reproduce it, it's very clear that the window is sending configure requests to be positioned at `(0, 0)`. I then reproduced it while running albert under x11trace and when showing the window this is what happens (`x11trace albert | grep --linebuffered -i configure`):

````
000:<:0277: 16: Request(12): ConfigureWindow window=0x02000004 values={stack-mode=Above(0x00)}
000:>:0279: Event ConfigureNotify(22) event=0x02000004 window=0x02000004 above-sibling=0x02a0003a x=0 y=0 width=654 height=131 border-width=0 override-redirect=false(0x00)
000:<:0284: 16: Request(12): ConfigureWindow window=0x02000004 values={stack-mode=Above(0x00)}
000:<:028c: 28: Request(12): ConfigureWindow window=0x02000004 values={x=0 y=0 width=654 height=75}
000:>:028e: Event (generated) ConfigureNotify(22) event=0x02000004 window=0x02000004 above-sibling=None(0x00000000) x=953 y=527 width=654 height=131 border-width=0 override-redirect=false(0x00)
000:>:0295: Event ConfigureNotify(22) event=0x02000004 window=0x02000004 above-sibling=None(0x00000000) x=0 y=0 width=654 height=75 border-width=0 override-redirect=false(0x00)
000:>:0295: Event (generated) ConfigureNotify(22) event=0x02000004 window=0x02000004 above-sibling=None(0x00000000) x=0 y=0 width=654 height=75 border-width=0 override-redirect=false(0x00)
000:<:02aa: 44: Request(25): SendEvent propagate=false(0x00) destination=0x000000f6 event-mask=SubstructureNotify,SubstructureRedirect UnmapNotify(18) event=0x000000f6 window=0x02000004 from-configure=false(0x00)
000:>:02aa: Event UnmapNotify(18) event=0x02000004 window=0x02000004 from-configure=false(0x00)
```

As you can see, the only configure requests the window sends are stacking or for the top left corner position. For comparison, when opening `albert` for the first time, the trace looks like this:

````
000:<:01c5: 16: Request(12): ConfigureWindow window=0x02000004 values={stack-mode=Above(0x00)}
000:<:01c7: 28: Request(12): ConfigureWindow window=0x02000004 values={x=0 y=0 width=654 height=75}
000:>:01c7: Event ConfigureNotify(22) event=0x02000004 window=0x02000004 above-sibling=0x02000005 x=0 y=0 width=400 height=300 border-width=0 override-redirect=false(0x00)
000:>:01c8: Event ConfigureNotify(22) event=0x02000004 window=0x02000004 above-sibling=0x02000005 x=0 y=0 width=654 height=75 border-width=0 override-redirect=false(0x00)
000:<:01e1: 28: Request(12): ConfigureWindow window=0x02000004 values={x=953 y=527 width=654 height=75}
000:<:01e2: 16: Request(12): ConfigureWindow window=0x02000004 values={stack-mode=Above(0x00)}
000:>:01e5: Event (generated) ConfigureNotify(22) event=0x02000004 window=0x02000004 above-sibling=None(0x00000000) x=953 y=700 width=654 height=75 border-width=0 override-redirect=false(0x00)
000:>:01e5: Event (generated) ConfigureNotify(22) event=0x02000004 window=0x02000004 above-sibling=None(0x00000000) x=953 y=527 width=654 height=75 border-width=0 override-redirect=false(0x00)
000:<:01ff: 44: Request(25): SendEvent propagate=false(0x00) destination=0x000000f6 event-mask=SubstructureNotify,SubstructureRedirect UnmapNotify(18) event=0x000000f6 window=0x02000004 from-configure=false(0x00)
```

In this trace, you can see an additional configure request for the correct position which is missing when the bug is reproduced. Since this proves quite clearly that it's not an i3 issue (i3 can't position the window if it never asks to be positioned), I'm going to close again. Maybe it's a QT bug?

**Comment by ManuelSchneid3r** [comment]
Thank you for pointing this out. This happens even if I use fixed values for QWidget::move so it has to be a Qt bug. I'm just curious why it works with awesome.

**Comment by Airblader** [comment]
Even with the instructions I can't reproduce this reliably, so it seems to be some sort of race condition, perhaps? Also, things like which atoms the window manager claims to support might make a difference. But either way, I suggest filing this bug against QT.

**Comment by aacebedo** [comment]
@ManuelSchneid3r Can you help me to fill the bug on QT tracker ? you are more familiar with your code than me and will be more efficient to explain how you use the QT window.
