### ISSUE TITLE
Enhancement: Cygwin build

### ISSUE THREAD

**Issue by AndersenJ** [i3/i3#2268]
Since this is my favorite window manager, it would be really nice to have a build to use with Cygwin. People have done this with XFCE, Openbox, and other projects, so it should be doable. I would do it myself, but quickly discovered I have no clue what I'm doing.

**Comment by acrisci** [comment]
I've built i3 on cygwin before. It should be doable.

The question is though, how useful would it really be? Is anyone actually running X on a windows as their desktop? Last time I looked into doing that, it seemed very limited.

**Comment by stapelberg** [comment]
I’d sure appreciate an external cygwin build for people who are interested, but we won’t have an official cygwin build. AFAIK, none of our core contributors use cygwin regularly, so we don’t have the manpower to support it.
