### ISSUE TITLE
Mouse buttons 11-14 bindsym not working

### ISSUE THREAD

**Issue by Cynerd** [i3/i3#2271]
Since I updated to version 4.12 from 4.11 all my mouse bindings for buttons 11-14  stopped working. Basic mouse buttons bindings works, only those additional doesn't. Log here is with new config file with just `bindsym --whole-window button11 exec --no-startup-id xterm` added. What I mean stopped working is that xterm is not started.

```
Binary i3 version:  4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12 (2016-03-06, branch "4.12") (pid 11412)
Loaded i3 config: /home/cynerd/.config/i3/config (Last modified: Thu 24 Mar 2016 05:14:00 PM CET, 1681 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

`http://logs.i3wm.org/logs/5738275486564352.bz2`

**Comment by Airblader** [comment]
If you add a binding

    bindsym --whole-window button4 nop

Does the `button11` binding work then?

**Comment by Cynerd** [comment]
I will try. I am until Tuesday away from my setup with that mouse, so I will inform you after that.

**Comment by Cynerd** [comment]
That additional binding fixed it.

**Comment by Airblader** [comment]
> That additional binding fixed it.

Thanks, I suspect it's what I described above then. I'll try to provide a patch for this soon.

For the other issue you mentioned: from the top of my head I can't remember a specific change here, but I'd say this new behavior is better. @stapelberg What do you think?

**Comment by Airblader** [comment]
@stapelberg We could also just grab *exactly* those buttons that we need to grab. But it would force us to ditch the XCB constants and use simple integers instead (`XCB_BUTTON_INDEX_1` → `1`) since constants only exist for up to `_5`. This seems to be the case for Xlib as well.

**Comment by stapelberg** [comment]
> I'd say this new behavior is better. @stapelberg What do you think?

Agreed.

> @stapelberg We could also just grab exactly those buttons that we need to grab. But it would force us to ditch the XCB constants and use simple integers instead (XCB_BUTTON_INDEX_1 → 1) since constants only exist for up to _5. This seems to be the case for Xlib as well.

That’s fine.

**Comment by Airblader** [comment]
@Cynerd Can you please try the patch from #2290 and tell us whether it fixes the issue?

**Comment by Cynerd** [comment]
@Airblader I tested it and it works fine. Thank all you for your work.

**Comment by Airblader** [comment]
@Cynerd Thanks for the confirmation!
