### ISSUE TITLE
Weird behavior when accessing a specific workspace

### ISSUE THREAD

**Issue by charlesvdv** [i3/i3#2272]
Hi !

Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12 (2016-03-06, branch "4.12") (pid 27256)
Loaded i3 config: /home/charles/.config/i3/config (Last modified: Sun 27 Mar 2016 12:33:28 PM CEST, 512 seconds ago)
The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:
http://logs.i3wm.org/logs/5715605172781056.bz2

My i3 config file : 
https://github.com/charlesvdv/dotfiles/blob/master/.config/i3/config

**What I did:** and **What I saw:**

I'm pressing Mod+6. It does anything. Then I tried to press Mod+Shift+6, the windows disappears. I repress Mod+6, the windows reappears but as floating windows. I press Mod+Shift+space to reset the windows in non-floating mode, it don't works. 

When I press Mod+6, the floating window toggles. 
When I repress Mod+Shift+6, the window disappears again. 

I tested with a bunch of applications as termite (terminal emulator), firefox, ...

**What I expected instead:**

As all my others shortcuts with Mod+'n', go to the workspace 'n' and when I press Mod+Shift+'n', move the window to workspace 'n'.  

**Other information**

My keyboard is in french so in my .xinitrc I have, above exec i3, setxkbmap=fr. 
My button works well because I can write 6 without problem and the others characters works well too (with azerty it's - and |) 

Thanks for looking to this issue :smile:

**Comment by jolange** [comment]
You have scratchpad [bindings](https://github.com/charlesvdv/dotfiles/blob/master/.config/i3/config#L120-L125) for `minus`. Quickly searching for french keyboard layout revealed that a minus is `Shift+6`, right? I bet it's related to that binding. Can you try it with those lines removed?

**Comment by charlesvdv** [comment]
It works ! Thanks a lot ! And sorry for the useless issue :/

**Comment by Airblader** [comment]
I suppose I can close this then.
