### ISSUE TITLE
Google Chrome does not update view when view in other workspaces changes

### ISSUE THREAD

**Issue by mattmahn** [i3/i3#2285]
Output of `i3 --moreversion 2>&- || i3 --version`:
```
Binary i3 version:  4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12 (2016-03-06, branch "4.12") (pid 28227)
Loaded i3 config: /home/matt/.i3/config (Last modified: Sun 10 Apr 2016 10:31:01 PM CDT, 4040 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

URL to a logfile as per http://i3wm.org/docs/debugging.html: 

http://logs.i3wm.org/logs/5676709948948480.bz2

**What I did:**
(When I was looking through the log file, I took the liberty to note the line numbers of the events I took, so you can hopefully jump around it more easily.)

1. Starting at workspace 3 (on a separate monitor; hade urxvt running)
2. Switched to workspace 2 where Chrome is running [line 824]
3. Switched to workspace 1 (two urxvt terminals) [line 1199]
4. Executed `i3status --help` (really any command, even <kbd>Enter</kbd>, would work) [line 1449]
5. Switched back to workspace 2 (Chrome) [line 1523]
6. I search for "asdf": <kbd>Ctrl+t</kbd>, <kbd>asdf</kbd>, <kbd>Enter</kbd>. Nothing happens. No new tab is shown. When I scroll, nothing happens. You can see that at line 1770, the window title of Chrome changed exactly as is expected (to `"asdf" at DuckDuckGo - Google Chrome`).
7. Switch back to other workspace _on that display_ (workspace 1) [line 1843]
8. Switch back to Chrome/workspace 2 and the correct tab/view/content/whatever is rendered (the DuckDuckGo search) [line 2067]

**What I saw:**

Google Chrome's view not updating to my attempt at doing something. In addition to the above search not working, this also happens  when I try to scroll, or when the contents a program needs to be updated that is in a workspace on the same display that Chrome is on (it fails less consistently with a program in a workspace on a different display). 

**What I expected instead:**

I expect Google Chrome's view to update immediately just as it does in every other WM/DE I've used (GNOME v3.18.4 in the Linux world).

---

Extra info:

Google Chrome version: 49.0.2623.110
`uname -a`: `Linux antergos 4.4.5-1-ARCH #1 SMP PREEMPT Thu Mar 10 07:38:19 CET 2016 x86_64 GNU/Linux`

**Comment by Airblader** [comment]
This isn't i3 at fault here because we aren't actually involved in the rendering of the client itself. Typically this is a graphics driver issue. 

Are you running a compositor?

**Comment by mattmahn** [comment]
Okay. That makes sense since this problem does not seems to happening very consistently anymore.
At some point I lost track of my graphics driver situation. I'm not sure if it's proprietary NVIDIA and Nouveau; all I know is that a big NVIDIA log pops up on the screen for a fraction of a second before LightDM loads.

No, I'm not using a compositor. Do you think that running one may fix this?

**Comment by Airblader** [comment]
Yeah, try running a compositor. It helps with these things quite often.

**Comment by Airblader** [comment]
I'm going to close this since as mentioned above, the window manager is not involved in rendering the client. From the description it appears the be a rather common issue we see due to graphics drivers / compositing.

If we do find out that this might be an i3 issue afterall, we can reopen.

**Comment by mattmahn** [comment]
(Commenting just for those that may run into this problem too.)
I've been running [compton](https://github.com/chjj/compton) since yesterday, and have not experienced this issue anymore.
