### ISSUE TITLE
Can't get no_focus working: always says "This is the first window on this workspace..."

### ISSUE THREAD

**Issue by Chocobozzz** [i3/i3#2292]
Output of `i3 --moreversion 2>&- || i3 --version`:

    Binary i3 version:  4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors
    Running i3 version: 4.12 (2016-03-06, branch "4.12") (pid 2193)
    Loaded i3 config: /home/florian/.config/i3/config (Last modified: mer. 13 avril 2016 11:23:09 CEST, 1567 seconds ago)

    The i3 binary you just called: /usr/bin/i3
    The i3 binary you are running: i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5741830645743616.bz2

**What I did:**

I configured I3 to don't focus VLC when opening: `no_focus [class="Vlc"]`

**What I saw:**

VLC always grabs focus in workspace with another windows.

**What I expected instead:**
VLC doesn't grab focus.

**Comment**
I read the logs and it seems that https://github.com/i3/i3/blob/next/src/manage.c#L578 always returns `true` (and thus print `"This is the first window on this workspace, ignoring no_focus.\n"` in logs) even if VLC is not the first window in the workspace.

For example:

![before](https://lut.im/sBmmVdE8mZ/96nmQ5BVv988EGQm.png)
![after](https://lut.im/MzNUfDA6iL/LYUYoMl7WLgwzZfN.png)

**Note:** I open VLC with [Synapse](https://farm8.staticflickr.com/7131/7552939146_45e8abc6e5_b.jpg)

Thanks.

**Comment by Airblader** [comment]
The problem seems to be that you are using a tabbed workspace layout, so even if many windows are open, there's only ever one (direct) descendant.

What we actually need to do is count the number of containers holding windows.

**Comment by Airblader** [comment]
I'll work on a fix for this.

**Comment by Chocobozzz** [comment]
Awesome, thanks @Airblader.

**Comment by Airblader** [comment]
@Chocobozzz Can you try the patch from #2296 please?
