### ISSUE TITLE
Random unrecoverable freezes

### ISSUE THREAD

**Issue by thisredone** [i3/i3#2309]
Output of `i3 --moreversion 2>&- || i3 --version`:

    Binary i3 version:  4.12-17-gcc5fa49 (2016-03-24, branch "gaps-next") © 2009 Michael Stapelberg and contributors
    Running i3 version: 4.12-17-gcc5fa49 (2016-03-24, branch "gaps-next") (pid 28046)
    Loaded i3 config: /home/piotr/.config/i3/config (Last modified: śro, 20 kwi 2016, 19:20:52, 51390 seconds ago)

    The i3 binary you just called: /usr/bin/i3
    The i3 binary you are running: i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5754818358411264.bz2

Seems to me like the logfile doesn't provide any useful information and frankly I'm not sure how to get it.
i3 freezes randomly multiple times a day. I can move the cursor and use the window that I was in when i3 froze. Ctrl+Alt+F2, login and `DISPLAY=:0 i3-msg restart` doesn't do anything - just hangs.

**Comment by Airblader** [comment]
Can you please attach gdb and pull a backtrace?

**Comment by thisredone** [comment]
This one comes from the next freeze http://pastie.org/pastes/10806475/text

**Comment by Airblader** [comment]
I feel like you might have something running using the IPC incorrectly. i3 behaves badly when this happens. Do you run any i3-related scripts in your setup? Can you reproduce the freeze when using the default config?

**Comment by thisredone** [comment]
You are correct - I'm using [i3ipc-ruby](https://github.com/veelenga/i3ipc-ruby) in one of my scripts. It is subscribed to all window events. Perhaps that's why using spotify is impossible without i3 freezing soon after (Spotify updates the title constantly).  
I've since disabled the script and will report back with the status. In the meantime - is there an alternative approach to what I was doing? Monitoring windows is important to me.

**Comment by Airblader** [comment]
The problem is probably not the amount of IPC messages, but that incomplete data is sent to the API. See #1876.

**Comment by thisredone** [comment]
The issue doesn't occur when not using [i3ipc-ruby](https://github.com/veelenga/i3ipc-ruby) so I guess I'll close this.
