### ISSUE TITLE
i3bar: Accept "primary" for output config option

### ISSUE THREAD

**Issue by wlhlm** [i3/i3#2311]
This is a feature request to add the argument "primary" as special case to the `output` config option for i3bar to enable the bar to automatically be put on the primary monitor without having to configure an output explicitly (helpful with occasionally changing monitor setups), similar to `tray_output`.

My specific use case is to be able to have an i3bar with a different `status_command` on the primary output.

**Comment by wlhlm** [comment]
I just realized that this feature request only covers the problem I want to solve by 50%: What I want to do is to write a custom `status_command` that runs in the i3bar on the primary output and acts as notification daemon (somewhat similar to `twmnd`). A second i3bar instance should run on all non-primary outputs and host the usual `status_command` like i3status.

So in summary I have two `bar {}`-configs:
```
bar {
    status_command notifyd
    output primary
}
bar {
    status_command i3status
}
```

The problem is that there is no way to select all "non-primary" outputs. The above would result in two bars being displayed on the primary output (since the second bar will run on all outputs). I don't think there is any preexisting config syntax that I could borrow for this. Not sure how to handle this…

**Comment by acrisci** [comment]
@wlhlm make another issue for the second case and come up with a proposal for how to handle that situation and we can discuss it there.
