### ISSUE TITLE
i3 does not adjust the output of workspace when monitors are unpluged.

### ISSUE THREAD

**Issue by zhou13** [i3/i3#2326]
**Output of `i3 --moreversion 2>&- || i3 --version`:**
````
Binary i3 version:  4.12-44-g42a3371 (2016-04-23, branch "next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12-44-g42a3371 (2016-04-23, branch "next") (pid 989)
Loaded i3 config: /home/zhou13/.config/i3/config (Last modified: Thu 28 Apr 2016 12:14:50 PM PDT, 17868 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
````

**URL to a logfile as per http://i3wm.org/docs/debugging.html:**

http://logs.i3wm.org/logs/5631943370604544.bz2

**What I did:**

1.  start i3 without external monitors

2.  plug in an external monitor

3.  run `xrandr --auto`

4.  create some workspace on the external monitor

5.  unplug the external monitor

6.  run `xrandr --auto`

**What I saw:**

i3 behaves strange after this, especially the resolution of external monitor is not as same as the internal monitor of my laptop.  Sometimes the i3 set the resolution to resolution of the external monitors, which cuts off some area of application and make i3bar disappear. Also the workspace originally on the external monitor does not move to the internal monitor.  The below is the `i3-msg` result:

````
[{"num":1,"name":"1:1  www","visible":true,"focused":true,"rect":{"x":0,"y":0,"width":1920,"height":1054},"output":"eDP1","urgent":false},{"num":2,"name":"2:2  code","visible":false,"focused":false,"rect":{"x":0,"y":0,"width":1920,"height":1054},"output":"eDP1","urgent":false},{"num":3,"name":"3","visible":true,"focused":false,"rect":{"x":0,"y":0,"width":1920,"height":1080},"output":"HDMI2","urgent":false}]
````

Now my HDMI2 output is unpluged and I have already run `xrandr --auto`,  but workspace "3" is still on the HDMI2 output.

**Comment by Airblader** [comment]
What is the output of `xrandr` in this "broken" state? My suspicion is that the monitor is unplugged, but not turned off. What happens if you explicitly turn off the output (`xrandr --output … --off`)?

**Comment by zhou13** [comment]
After I unplug the monitor and run `xrandr --auto`, I got the following in `xrandr` while I can still reproduce this bug.  Restart i3 in-place does not workaround the bug.

````
Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 32767 x 32767
eDP1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 344mm x 194mm
   1920x1080     60.00*+  40.00  
   1400x1050     59.98  
   1600x900      60.00  
   1280x1024     60.02  
   1280x960      60.00  
   1368x768      60.00  
   1280x720      60.00  
   1024x768      60.00  
   1024x576      60.00  
   960x540       60.00  
   800x600       60.32    56.25  
   864x486       60.00  
   640x480       59.94  
   720x405       60.00  
   640x360       60.00  
DP1 disconnected (normal left inverted right x axis y axis)
DP2 disconnected (normal left inverted right x axis y axis)
HDMI1 disconnected (normal left inverted right x axis y axis)
HDMI2 disconnected (normal left inverted right x axis y axis)
HDMI3 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
````

**Comment by zhou13** [comment]
I find more clue about this bug.  In fact I used the binding `bindsym $mod+Shift+r exec --no-startup-id autorandr --change, restart` to reset the monitor.

The `autorandr` is a wrapper to `xrandr`, which you can simply treat it as `xrandr --auto`.  The problem is on the `restart` command.  If I remove that command, it seems that I cannot reproduce this bug using the keybind `mod+shift+r`.  Therefore, the bug seems can only be reproduced by `xrandr` following by a restart command.

**Comment by Airblader** [comment]
I think we need to look at this either way, but: why are you restarting i3?

**Comment by zhou13** [comment]
I have two reasons for this.  First, I can use "mode+shift+r" in both the situation that I want to restart i3 and I need to reset the screen resolution so I can avoid remembering two shortcuts.  Second, after I reset the screen resolution, I need to reset the wallpaper.  I have `exec_always --no-startup-id feh --bg-scale ~/Pictures/wallpaper.jpg` in my i3 config so I think a restart following `xrandr` command is convenient.

**Comment by Airblader** [comment]
I see. My best guess right now is that we have a race condition. i3 saves the layout file for the in-place restart before the RandR events are processed. When i3 now starts up again it reads that layout file and blindly appends it without any kind of verification – which is bad since the entire environment changed in the meantime.

@zhou13 Can you append the following patch and see if it fixes the issue?

````
diff --git a/src/tree.c b/src/tree.c
index e848a6a..38a4816 100644
--- a/src/tree.c
+++ b/src/tree.c
@@ -106,6 +106,7 @@ bool tree_restore(const char *path, xcb_get_geometry_reply_t *geometry) {
     }
 
     restore_open_placeholder_windows(croot);
+    randr_query_outputs();
 
     return true;
 }
```

**Comment by zhou13** [comment]
It seems that i3 crashes in restart after applying this patch.

**Comment by Airblader** [comment]
Yeah, sorry. I was just a little too quick. We don't initialize RandR until after restoring the tree. Sorry about that! I'll provide a better patch for you to test tomorrow.

**Comment by Airblader** [comment]
My slightly adjusted working theory: due to the restart, we miss the screen change events. The layout file is written with the old state and when the restarted i3 process fetches outputs, it reads the new state as the initial one. Since it doesn't know the old state, it doesn't trigger moving workspaces to the correct output etc.

I'm not really sure how to handle this. We could serialize the output information for the restart as well, but that seems hacky. We could also check the tree in this case for outputs that don't exist, create a fake output and then a fake screen change event, maybe? Also rather hacky…

I'm lacking a really good idea at the moment.

**Comment by Airblader** [comment]
@zhou13 Can you try the following patch? Unfortunately I can't test it at the moment, so my apologies if it just ends in another crash or something. :-)

````
diff --git a/src/main.c b/src/main.c
index b2ce17d..17975da 100644
--- a/src/main.c
+++ b/src/main.c
@@ -623,7 +623,7 @@ int main(int argc, char *argv[]) {
     grab_all_keys(conn);
 
     bool needs_tree_init = true;
-    if (layout_path) {
+    if (layout_path != NULL) {
         LOG("Trying to restore the layout from \"%s\".\n", layout_path);
         needs_tree_init = !tree_restore(layout_path, greply);
         if (delete_layout_path) {
@@ -633,7 +633,6 @@ int main(int argc, char *argv[]) {
              * sockets) left. */
             rmdir(dir);
         }
-        free(layout_path);
     }
     if (needs_tree_init)
         tree_init(greply);
@@ -658,6 +657,28 @@ int main(int argc, char *argv[]) {
         randr_init(&randr_base);
     }
 
+    // TODO XXX Or use !needs_tree_init?
+    if (layout_path != NULL) {
+        Con *con;
+        TAILQ_FOREACH(con, &(croot->nodes_head), nodes) {
+            Output *output;
+            TAILQ_FOREACH(output, &outputs, outputs) {
+                if (output->active)
+                    continue;
+
+                if (strcmp(con->name, output->name) != 0)
+                    continue;
+
+                output->to_be_disabled = true;
+            }
+        }
+
+        if (randr_base > -1)
+            randr_query_outputs();
+
+        free(layout_path);
+    }
+
     scratchpad_fix_resolution();
 
     xcb_query_pointer_reply_t *pointerreply;
```

**Comment by zhou13** [comment]
The good news is that there is no crash.  The bad news is that it seems nothing has changed after applying this patch.  I still get wrong output in `i3-msg -t get_workspaces` and missing i3bar.

**Comment by Airblader** [comment]
@zhou13 I'm sorry this is tedious work :/ How about this patch?

````
diff --git a/src/main.c b/src/main.c
index b2ce17d..13dd2a5 100644
--- a/src/main.c
+++ b/src/main.c
@@ -623,7 +623,7 @@ int main(int argc, char *argv[]) {
     grab_all_keys(conn);
 
     bool needs_tree_init = true;
-    if (layout_path) {
+    if (layout_path != NULL) {
         LOG("Trying to restore the layout from \"%s\".\n", layout_path);
         needs_tree_init = !tree_restore(layout_path, greply);
         if (delete_layout_path) {
@@ -633,7 +633,6 @@ int main(int argc, char *argv[]) {
              * sockets) left. */
             rmdir(dir);
         }
-        free(layout_path);
     }
     if (needs_tree_init)
         tree_init(greply);
@@ -658,6 +657,33 @@ int main(int argc, char *argv[]) {
         randr_init(&randr_base);
     }
 
+    // TODO XXX Or use !needs_tree_init?
+    if (layout_path != NULL) {
+        Con *con;
+        TAILQ_FOREACH(con, &(croot->nodes_head), nodes) {
+            Output *output;
+            TAILQ_FOREACH(output, &outputs, outputs) {
+                if (output->active)
+                    continue;
+
+                if (strcmp(con->name, output->name) != 0)
+                    continue;
+
+                if (output->con == NULL) {
+                    output_init_con(output);
+                    output->changed = false;
+                }
+
+                output->to_be_disabled = true;
+            }
+        }
+
+        if (randr_base > -1)
+            randr_query_outputs();
+
+        free(layout_path);
+    }
+
     scratchpad_fix_resolution();
 
     xcb_query_pointer_reply_t *pointerreply;

```

**Comment by zhou13** [comment]
Never mind.

It seems that this patch works.  To test I unpluged my monitor several time and I never observed this problem again.  Thanks for your prompt work!

**Comment by Airblader** [comment]
@zhou13 Thanks for the testing. I'll just give this a bit more thought and then come up with a proper pull request. :-)

**Comment by Airblader** [comment]
@zhou13 Please see PR #2337
