### ISSUE TITLE
[enhancement] move workspace $tag to position mouse

### ISSUE THREAD

**Issue by leifmadsen** [i3/i3#2357]
Currently you can move a container to the output of the current mouse position, but it would be great to allow this for workspaces as well.

I have a buddy who is coming from xmonad, and this functionality is part of his standard workflow. It's really the last thing stopping him from adopting i3wm.

**Comment by Airblader** [comment]
This can mostly be done via `[workspace=…] move workspace to output <output>`. The only part missing is that we have no special `current` value for the output to represent the focused output. I think I prefer supporting that because the command feels more intuitive that way to me than it does to move a workspace "to the mouse".

Of course this is not entirely equivalent to the requested feature if your buddy doesn't use `focus_follows_mouse`.

**Comment by leifmadsen** [comment]
Yea, I would agree that the `current` probably makes more sense, so that it goes to current focus. I knew that you could specify a specific output, but it's not quite the dynamic setup that xmonad folks would be used to. I think if you added the ability to do `current` then it would fit the request.

**Comment by stapelberg** [comment]
Note that we don’t generally implement features just so that users of other window managers feel at home, or because “otherwise I can’t use i3!”.

That said, I think supporting `current` as @Airblader suggested makes sense.

**Comment by leifmadsen** [comment]
Yea, I totally get that, but in this case, it was more of a use case that made sense to me from another TWM, and since i3 had most of it, just a missing style of workspace movement, I thought it made sense to bring up. Thanks!

**Comment by Airblader** [comment]
Just FYI, a coworker of mine just asked me the same thing. I found that we have [this article for an IPC solution](https://i3wm.org/docs/user-contributed/workspace-current-output.html) which you can use in the meantime. I still think this is worth implementing directly into i3, though.

**Comment by Airblader** [comment]
@stapelberg I'm even wondering whether it should be a config directive to open workspaces on the current output rather than switching to the output that workspace is currently on. Seems like a worthy feature for a window manager which wants to support multi monitor workflows.

**Comment by stapelberg** [comment]
> I'm even wondering whether it should be a config directive to open workspaces on the current output rather than switching to the output that workspace is currently on.

The same behavior can be achieved by modifying the configuration file to chain “move workspace 1 to output current, workspace 1”, correct? If so, I don’t see the additional benefit in another configuration directive.

> Seems like a worthy feature for a window manager which wants to support multi monitor workflows.

We’re not claiming that we want to support every possible workflow which involves multiple monitors, though :).

**Comment by Airblader** [comment]
> The same behavior can be achieved by modifying the configuration file to chain “move workspace 1 to output current, workspace 1”, correct?

Almost, but not quite. I'm thinking potential IPC scripts and things like `_NET_WM_DESKTOP` messages. I realize that this affects many feature requests where we opt against directives, but

> We’re not claiming that we want to support every possible workflow which involves multiple monitors, though :).

… while this is, of course true, it's a judgement call for every feature and this one struck me as something that might be relevant enough to justify it, once I thought about how such a workflow feels for a while.

Most everyday cases probably won't care about such messages, though, so going without the directive is probably fine, too. I guess we could argue that we can go with this feature for now (which is worth having either way) and if someone finds it to be insufficient we could revisit a config directive.

**Comment by stapelberg** [comment]
> I guess we could argue that we can go with this feature for now (which is worth having either way) and if someone finds it to be insufficient we could revisit a config directive.

Sounds good, let’s go with that.

**Comment by jcornwall** [comment]
I'm trying to replace an IPC script I use which determines the current output and invokes "workspace X; move workspace to output Y".

This feature seems like a nice replacement but I haven't quite figured it out. The syntax "move workspace X to output current" doesn't appear to be valid. I tried instead "workspace X; move workspace to output current" but the first command changes the output, turning the second into a no-op.

Any ideas?

**Comment by Airblader** [comment]
@jcornwall See my first comment on this issue.

**Comment by jcornwall** [comment]
Thanks for the pointer. This gets closer but it appears to have issues when a workspace is empty. e.g.

output 1 focused, non-empty workspace 1 on output 1, empty workspace 2 on output 2
`[workspace=2] move workspace to output current; workspace 2`

This doesn't move the empty workspace (but does focus it). If I add a container to workspace 2 then it moves correctly.

I think a related issue is moving a non-empty workspace from one output to a different output which currently has an empty workspace focused. In that scenario the workspace moves correctly but the wrong output is focused.

Do you know why this might occur? If not I can do some debugging in the code.

**Comment by Airblader** [comment]
Yeah, it only works on non-empty workspaces because `[workspace=…] …` actually doesn't match the workspace, but all windows on that workspace and executes the command for each of them. If there's no window to be matched, nothing happens.

I think in this case what you need to do is write a script that gets the `con_id` of the workspace container from the IPC and match on that with `[con_id=…]`.

In general I don't mind implementing a way to address the workspace directly either, though.
