### ISSUE TITLE
strange color behavior; border color uses text color value

### ISSUE THREAD

**Issue by jefeyay** [i3/i3#2365]
Output of `i3 --moreversion 2>&- || i3 --version`:
Binary i3 version:  4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12 (2016-03-06, branch "4.12") (pid 575)
Loaded i3 config: /home/jeff/.config/i3/config (Last modified: Sat 28 May 2016 09:16:59 AM EDT, 1314 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: /usr/bin/i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5664606865326080.bz2

**What I did:**
I added a section in my config file to modify appearance.

**What I saw:**
Changing the 'border' section for the client.focused only changes the border around the window title, the border around the rest of the window remains as default. The border color around the rest of the window can only be changed by removing (or having an error in) the 'background' color value. Then the border color around the rest of the window takes on the value in the 'text' section. 

I currently have 'new_window pixel 1' set to remove window headers but this problem was also there when using a default config as well.

**What I expected instead:**
I expected the border color to change with the border color values. This works as expected on a different machine with the version currently in the Ubuntu software center.

**Comment by Airblader** [comment]
````
# class                 border  backgr. text    indicator child_border
client.focused          #4c7899         #4c7899 #2e9ef4   #285577
```

This doesn't do what you maybe expect it to do. To i3, this looks like this:

````
# class                 border  backgr. text    indicator child_border
client.focused          #4c7899 #4c7899 #2e9ef4 #285577
```

Why are you leaving a color out? i3 expects you to define all colors.

**Comment by jefeyay** [comment]
I left it out because that is the only way (that I found) to get the border color to actually change. Doing it the normal way (which works on every other i3 install I've had) does not work. Something strange is happening and it happens with the default config as well. Putting a value in the there and changing it around only results in the window-decoration part of the border changing color. It's definitely not the usual behavior. I'll post some screen shots in a bit because I think I haven't explained what's going on in the clearest way.

**Comment by jefeyay** [comment]
Ok so sorry my mistake. I was so focused on doing it the old way I didn't pay attention to the new child_border. And here I was trying to be helpful :| I see what is going on.

**Comment by Airblader** [comment]
No worries. :-)
