### ISSUE TITLE
Fullscreen window always moved to primary output when both outputs have the same dimension

### ISSUE THREAD

**Issue by lahol** [i3/i3#2369]
When starting a fullscreen application (Kodi) on my secondary (physically larger) screen via dmenu,
the application now always starts at my primary screen. I observed the same behaviour, when going to fullscreen in a browser (flash) video. Both screens share the same resolution. I tracked the issue down to commit fec1a9511e75f83b8707758c04d5a201edbc652d. In fact, if I comment out the line which does the moving, everything works as expected.
While I understand the rationale for the mentioned commit, it is really annoying always having the application start in the wrong place, especially since I never ran into the issue the commit addresses. Moreover, I cannot move the flash window (on the rare occasions I use it) to the secondary screen, since it goes out of fullscreen when I try to move it to the other output.
As I read the commit, it looks in the list of outputs for one matching the geometry of the new window, and, if it finds one, moves the window to this output. This leads to the unexpected behaviour if the outputs have the same resolution.
Some thoughts on how to fix this:
  * First check if the geometry matches the _current_ output (may return NULL to avoid a noop moving).
  * Make this configurable.
  * Only enable/disable this for windows with a for_window rule.

Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.12-68-g18d6a1b (2016-05-31, branch "next") © 2009
Michael Stapelberg and contributors
Running i3 version: 4.12-68-g18d6a1b (2016-05-31, branch "next") (pid 1220)

http://logs.i3wm.org/logs/5709941587312640.bz2

**Comment by Airblader** [comment]
That k you for reporting this and also doing the debugging work. We like to see reports like this :)

Your first suggestion on a fix sounds like a good way forward to me. Another solution would be to skip this logic if there's more than one output with these dimensions. 

@wentasah FYI.

**Comment by Airblader** [comment]
I actually think I'd prefer skipping this step if the dimensions can't be matched to a unique output. Everything else is guess work, even if we special case the current output. If the dimensions aren't unique we just don't know which output the window wants to be on.

**Comment by lahol** [comment]
Yes, thinking about it a little more, this sounds like the right way to go. I would take care of it myself, but, unfortunately, I do not have the time right now to learn how to write test. The fix itself should be rather simple.

**Comment by Airblader** [comment]
Sorry, I actually think we need to reconsider again. The logic doesn't just check the dimensions of the output, but also the _position_ of it. The tests already cover this scenario. We might be looking at an application bug.

**Comment by wentasah** [comment]
Yes, I the position is checked as well. How does kodi behave with other window managers?

**Comment by Airblader** [comment]
@wentasah Does LibreOffice set `WM_SIZE_HINTS`? We could use that for the check instead. The benefit here would be that the application actually has to tell us whether a specific information, such as x, y, width, height, is set or not (unlike the geometry which is always set to "something").

If it does, we could change the patch to use that information instead, but only if the appropriate hints are set.

**Comment by lahol** [comment]
Ok, I just checked with XFCE and Gnome. In both cases Kodi is put on the primary screen. So it is indeed an application bug.

**Comment by Airblader** [comment]
@lahol Thanks for testing it. Can you please report the bug against Kodi and cross-reference the two tickets with each other (for tracking purposes)?

@wentasah Please still check `WM_SIZE_HINTS`. If we can change the solution to work in both cases, that'd be better.

**Comment by lahol** [comment]
While investigating the issue with Kodi, I noticed that it has a setting on which output the window is shown. Now it seems to work as expected (although I think the default setting should be to start on the current screen; but this is a different matter).
As for the Flash-issue, this is a known bug and happens when the main Firefox window is on the other output.

Sorry for the noise. From my point of view, the ticket may be closed. Thank you for your patience.

**Comment by Airblader** [comment]
Thanks for the feedback!
