### ISSUE TITLE
[enhancement] list available binding modes

### ISSUE THREAD

**Issue by montiainen** [i3/i3#2375]
Apparently there is no way to retrieve information about available binding modes through IPC.

I'd find it useful to have a single binding for selecting any available binding mode using dmenu or something similar. At this time the only option (AFAIK) is to give configured binding modes to dmenu in a repeated, hard-coded fashion. I'm quite confident that there are other valid use cases also.

**Comment by Airblader** [comment]
Makes sense to me.

**Comment by montiainen** [comment]
If this was to be implemented, would it mean a new message type on i3-ipc? And if so, would it be get_modes or something similar, in the same way than other message types? Or maybe just get_config, giving current running configuration?

**Comment by Airblader** [comment]
I think dumping the entire configuration is tiresome and unnecessary. I'd opt for a `GET_BINDING_MODES` message type. Just my 2c.

**Comment by Adaephon-GH** [comment]
I confess, I do not know how much effort it would take to implement, but I could see the appeal of being able to retrieve the whole currently running configuration in a structured format (JSON). It would help for some other use cases that come up from time to time on the forums (reddit, stackexchange, mailing list): 
* getting a list of configured workspaces
* retrieving key bindings
* binding modes (obviously :) )
* retrieve default settings

Of course you can alway (try to) parse the configuration file on your own, but *i3* already has a fully functional parser for its configuration file, so why not let *i3* do the work (which it already does anyway) and show the results (which it currently does only for the bar configurations: `GET_BAR_CONFIG`).

**Comment by montiainen** [comment]
If I understand this correctly, parsing configuration file would not be the answer, since it may differ from runtime configuration (if it has changed after last load). 

Thinking behind my question about message type was, that I was a bit worried that i3-ipc might bloat in the future with different message types for every single thing that might be found useful to fetch. Then again, that's what it's for, really. Single JSON for whole configuration would be mostly irritating, since typically only a subset is needed. I'm leaning towards opinion of @Airblader (even though I'm neither an authority nor competent on this topic :)

List of configured workspaces can be fetched with message type get_workspaces, if I'm not mistaken.

**Comment by Airblader** [comment]
@Adaephon-GH 

> retrieving key bindings

I think this warrants its own IPC message as well and in fact Michael has expressed in the past that he'd be OK with that.

> Of course you can alway (try to) parse the configuration file on your own, but i3 already has a fully functional parser for its configuration file

Mostly because it's quite a bit of code to dump the structure again. So we should have an actual reason for this and I don't think the usecase is that strong yet. I prefer a service based approach where you query individual parts.

**Comment by Airblader** [comment]
I feel confident that @stapelberg would accept this, so I've provided a PR to implement it already.
