### ISSUE TITLE
i3 does not render tray icons from applications using tktray

### ISSUE THREAD

**Issue by czarkoff** [i3/i3#2381]
[Tktray](https://code.google.com/p/tktray/)-based tray icons don't appear in i3's built-in tray.  In fact they don't appear at all, as if they were never created.  Tested applications: tkabber and   coccinella.  Tray icons for GTK+ software work in the same setup, and tktray icons work with other systray implementations (tested tkabber with [stalonetray](http://stalonetray.sourceforge.net/)).

This [log file](http://logs.i3wm.org/logs/5700866052980736.bz2) was captured while enabling tktray icon in Tkabber (around 15:02, window id `0x1600017`).

My setup: OpenBSD -current (Sat Jun 18 17:43:31 UTC 2016), i3 4.12 ([port](http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/x11/i3/)), tktray 1.3.9 ([port](http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/x11/tktray/)), tkabber 1.1.2 ([port](http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/net/tkabber/)).

**Comment by Airblader** [comment]
Can you please provide the log file for i3bar? The i3 log file isn't too relevant for this scenario. See the last part in http://i3wm.org/docs/debugging.html

**Comment by czarkoff** [comment]
[Here](http://pastebin.ca/3646351) is an i3bar log.  I would not say it is helpful though.  During this run of i3bar I launched baresip (gtk+ tray icon) and tkabber (tktray icon).  Icon of tkabber did not show up, and I can't find anything relevant in the log.

**Comment by Airblader** [comment]
> and I can't find anything relevant in the log.

There are lines about a tray client:

````
[i3bar/src/xcb.c:684] _NET_SYSTEM_TRAY_OPCODE received
[i3bar/src/xcb.c:727] xembed format = 32, len = 2
[i3bar/src/xcb.c:729] xembed version = 1
[i3bar/src/xcb.c:730] xembed flags = 0
[i3bar/src/xcb.c:740] X window 01800003 requested docking
[i3bar/src/xcb.c:778] Falling back to output LVDS because no primary output is configured
[i3bar/src/xcb.c:845] Not mapping dock client yet
…
[i3bar/src/xcb.c:954] xembed_info updated
[i3bar/src/xcb.c:993] xembed format = 32, len = 2
[i3bar/src/xcb.c:995] xembed version = 1
[i3bar/src/xcb.c:996] xembed flags = 1
[i3bar/src/xcb.c:998] map state now 1
[i3bar/src/xcb.c:894] MapNotify for window = 01800003, event = 01800003
[i3bar/src/xcb.c:900] checking output LVDS
[i3bar/src/xcb.c:906] Tray client mapped (window ID 01800003). Adjusting tray.
[i3bar/src/xcb.c:664] Configuring tray window 01800003 to x=1349
…
[i3bar/src/xcb.c:1016] ConfigureRequest for window = 01800003
[i3bar/src/xcb.c:1039] This is a tray window. x = 1349
…
[i3bar/src/xcb.c:922] UnmapNotify for window = 01800003, event = 01800003
[i3bar/src/xcb.c:928] checking output LVDS
[i3bar/src/xcb.c:934] Tray client unmapped (window ID 01800003). Adjusting tray.
…
[i3bar/src/xcb.c:954] xembed_info updated
[i3bar/src/xcb.c:989] xembed_info unset
[i3bar/src/xcb.c:865] DestroyNotify for window = 01800003, event = 01800003
[i3bar/src/xcb.c:871] checking output LVDS
[i3bar/src/xcb.c:877] Removing tray client with window ID 01800003
```

So it appears that the tray client actually requests being unmapped again. Given that it works with stalonetray, in technical terms that means: something's wrong. :-) But it's not yet clear to me whether it's i3bar or the tray client.

**Comment by czarkoff** [comment]
@Airblader, as I mentioned above, this log is captured while running baresip (gtk+ tray icon) and tkabber.  Provided that baresip's icon showed up and these entries speak of the same window, I guess it is all about baresip, and tkabber with its tktray icon did not surface in this log.

**Comment by czarkoff** [comment]
Thank you for your suggestion to report the issue to `tktray` developers: I was acting under assumption that it is `i3bar`'s fault (because other tray implementation worked), but it turns out that the fault was on `tktray`'s account, and there is already a [corresponding issue](https://code.google.com/archive/p/tktray/issues/6) in their bug tracker.  With a patch from that PR `tktray` draws a proper icon in `i3bar` for me.
