### ISSUE TITLE
Changing layout does not redraw/resize unfocused wxwidgets windows

### ISSUE THREAD

**Issue by kcuzner** [i3/i3#2395]
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12 (2016-03-06, branch "4.12") (pid 965)
Loaded i3 config: /home/kcuzner/.i3/config (Last modified: Fri 13 Nov 2015 12:15:37 AM CST, 20775281 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

OS is Arch Linux, updated just last night.

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5746569068412928.bz2

**What I did:**

I ran two WxWidgets applications: Pronterface (log line 341) and Slic3r (log line 863). (this also happens with Kicad as well). I then changed the layout from side-by-side to tabbed (log line 3382).

**What I saw:**

Before changing to tabbed:
![wxbeforelayout](https://cloud.githubusercontent.com/assets/1793958/16715106/9464d3d6-469c-11e6-833a-ce82d4ab2e75.png)

Window that was already focused after tabbing: Notice that the internal widgets have resized properly.
![wx1afterlayout](https://cloud.githubusercontent.com/assets/1793958/16715105/9463c176-469c-11e6-84d9-e1405edc4e43.png)

Window that was out of focus when tabbing: Notice that the internal widgets are still sized as if the window was side-by-side.
![wx2afterlayout](https://cloud.githubusercontent.com/assets/1793958/16715107/94651620-469c-11e6-8cbe-2cb769e02f91.png)

**What I expected instead:**

I expected both windows to have resized their internal widgets, not just the one that was focused. I saw this issue originally probably over a year ago with Kicad, but since don't usually run any other WxWidgets applications I assumed it was just a Kicad problem. However, running these two other WxWidgets applications and seeing the same problem tells me that it is actually an i3 issue (or a bug in WxWidgets itself). 

This could be similar to #539 I think, unless I'm doing something wrong in my configuration and this is my problem.

**Comment by Airblader** [comment]
> or a bug in WxWidgets itself

This sounds more likely to me, unless we can reproduce this with applications not using WxWidgets. Redrawing and adjusting to the size given by the window manager is the job of the application.

Given that you already linked to #539, can you please provide an x11trace log as described there?

**Comment by Airblader** [comment]
Three months without further feedback, so I'm going to close this as the assumption is a client-side bug.
