### ISSUE TITLE
Firefox without a title bar freezes i3

### ISSUE THREAD

**Issue by mnelemans** [i3/i3#2413]
Output of `i3 --moreversion 2>&- || i3 --version`:

>Binary i3 version:  4.12-31-g0e29101 (2016-03-06, branch "master") © 2009 Michael Stapelberg >and contributors
>Running i3 version: 4.12-31-g0e29101 (2016-03-06, branch "master") (pid 3069)
>Loaded i3 config: /home/mathijs/.config/i3/config (Last modified: zo 31 jul 2016 00:38:12 CEST, >47477 seconds ago)
>
>The i3 binary you just called: /usr/bin/i3
>The i3 binary you are running: i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

>http://logs.i3wm.org/logs/5767917874446336.bz2

**What I did:**

Having Firefox open in one tile and then opening another tile, or even just having a pop-up from Firefox itself. It seems to only happen when I enable border none or when I disable the title bar for Firefox specifically. After spawning Firefox without a title bar, it will eventually hang i3. I can reproduce it by creating lots of windows with for example MOD+ENTER.

**What I saw:**

Firefox somehow hangs i3, without it actually crashing. I basically have to poweroff the system with the help of the powerbutton to be able to restart. 

**What I expected instead:**

Firefox not producing this bug.

**Comment by stapelberg** [comment]
Could you please test whether this also happens in a newly created user account on your computer, with the i3 default configuration file?

Instead of rebooting the system, you should be able to switch to a different virtual console using Ctrl+Alt+F1. In case that’s true, you should be able attach gdb to i3 using `gdb $(which i3) $(pidof i3)` and then generate a backtrace using `backtrace full`. Please provide that data here, as that’ll tell us more about the nature of the problem.

**Comment by mnelemans** [comment]
I just had the freeze and I was able to dump a backtrace ([gdb.txt](https://github.com/i3/i3/files/401596/gdb.txt)) in a virtual console. Unfortunately I haven't had the opportunity of creating one on a fresh user account yet, but it seems like the problem is actually on my side. After returning to i3 from the virtual console it just resumed without any issues, so I suspect another program is causing the temporary freeze.

**Comment by stapelberg** [comment]
In the backtrace, i3 is just waiting for events, so yes, that would support your theory that another program causes the freeze.

**Comment by stapelberg** [comment]
FWIW, I ran into a bug once where Firefox’s image scaling would trigger a graphics driver bug that would result in the computer appearing frozen for a couple of minutes. My guess is that it does 4M iterations of a loop until a counter overflows or something like that :).

Possibly what you’re seeing is similar.

**Comment by mnelemans** [comment]
My guess was also that compton is not always rendering the graphics correctly, because I've had problems with that before. I will try and see if I can find a solution there.

**Comment by mnelemans** [comment]
Thanks for the help!

**Comment by nikitawootten** [comment]
Hi guys, I am also having this problem. Even when compton is not running. Were you able to fix it @mnelemans?

**Comment by madhan34223** [comment]
steps to reproduce 

1. open firfox
2.  dm-tool switch-to-user <some_other_login>
3. login to the <some_other_login>
4. switch back to the original login and see firefox is freezed
5.
