### ISSUE TITLE
Alt+Shift+q does not work

### ISSUE THREAD

**Issue by akonstatinos** [i3/i3#2417]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.12-85-g012de8c (2016-08-03, branch "next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12-85-g012de8c (2016-08-03, branch "next") (pid 3311)
Loaded i3 config: /home/vagrant/.config/i3/config (Last modified: Fri 05 Aug 2016 10:22:28 AM UTC, 1239 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5727217287954432.bz2

**What I did:**

Alt+Shift+q

**What I saw:**

Nothing 

**What I expected instead:**
Window close

**Comment by Airblader** [comment]
* If you bind the key to something else, does that work?
* Do other keybindings involving Alt (and Shift) work?
* If you remove the binding, reload i3 and press the combination while running `xev -event keyboard`, what's the output?

From the log file it doesn't appear that the command is ever triggered.

**Comment by akonstatinos** [comment]
1. I already did an alternate bind to check Alt+Ctrl+q and it worked.
2. Alt + Shift works if I execute a script that I have for language switch using Alt+Shift
3 xev -event keyboard
KeyPress event, serial 28, synthetic NO, window 0x2200001,
    root 0x17c, subw 0x0, time 137481, (251,616), root:(1095,636),
    state 0x10, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 28, synthetic NO, window 0x2200001,
    root 0x17c, subw 0x0, time 137585, (251,616), root:(1095,636),
    state 0x18, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 28, synthetic NO, window 0x2200001,
    root 0x17c, subw 0x0, time 137865, (251,616), root:(1095,636),
    state 0x19, keycode 24 (keysym 0x51, Q), same_screen YES,
    XLookupString gives 1 bytes: (51) "Q"
    XmbLookupString gives 1 bytes: (51) "Q"
    XFilterEvent returns: False

**Comment by morgoth6** [comment]
I can observe similar problem, but it seems to affect all binds with Shift key. For example $mod+Shift+2 doesn't switch current window to workspace 2. My setup uses 'set $mod Mod4' and Im not sure when this starts to happen, but I just grab i3 snap and rebuild with no change. 
For now I switch Shift binds to use Mod1 (without shift) and this works just fine as a workaround.

Output of xev for Mod4+Shift+2
========
KeyPress event, serial 25, synthetic NO, window 0x3a00001,
    root 0x31a, subw 0x0, time 23722560, (342,449), root:(1306,506),
    state 0x10, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 28, synthetic NO, window 0x3a00001,
    root 0x31a, subw 0x0, time 23723432, (342,449), root:(1306,506),
    state 0x50, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 28, synthetic NO, window 0x3a00001,
    root 0x31a, subw 0x0, time 23724354, (342,449), root:(1306,506),
    state 0x51, keycode 11 (keysym 0x40, at), same_screen YES,
    XLookupString gives 1 bytes: (40) "@"
    XmbLookupString gives 1 bytes: (40) "@"
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x3a00001,
    root 0x31a, subw 0x0, time 23724444, (342,449), root:(1306,506),
    state 0x51, keycode 11 (keysym 0x40, at), same_screen YES,
    XLookupString gives 1 bytes: (40) "@"
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x3a00001,
    root 0x31a, subw 0x0, time 23725838, (342,449), root:(1306,506),
    state 0x51, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x3a00001,
    root 0x31a, subw 0x0, time 23725846, (342,449), root:(1306,506),
    state 0x11, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
========

**Comment by Corni** [comment]
This looks like #2418, doesn't it?

**Comment by Airblader** [comment]
Yeah, they look related. But I'd wait until one is fixed and then ask to retest to see if it fixed the other one, too.

**Comment by Airblader** [comment]
Actually I'm pretty confident it's the same issue now, so closing in favor of #2418.

If anyone has this issue regardless of num lock, please speak up.

**Comment by nullbio** [comment]
@Airblader I have a tenkeyless keyboard, so no numlock key, and I have this issue.

**Comment by nullbio** [comment]
I have this issue regardless of numlock @Airblader (tenkeyless keyboard).

**Comment by Airblader** [comment]
Closing again since you could confirm it is Numlock related in #2418.
