### ISSUE TITLE
Version 4.12 doesn't load keymap in VNC

### ISSUE THREAD

**Issue by tbnorth** [i3/i3#2425]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12 (2016-03-06, branch "4.12") (pid 8090)
Loaded i3 config: /home/tbrown/.i3/config (Last modified: Wed 06 Apr 2016 08:39:27 AM CDT, 11411155 seconds ago)

The i3 binary you just called: /home/tbrown/Downloads/i3-4.12/i3
The i3 binary you are running: /home/tbrown/Downloads/i3-4.12/i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5769623379116032.bz2

**What I did:**

Pressed Mod4 (Super_L) and 'd'

**What I saw:**

Current window became full screen

**What I expected instead:**

dmenu command menu appears on top of display

I think this is related to #1983 - I'm seeing this in a VNC session.

All the bindings are messed up, I'm just using mod4+d as an example.

4.10.4 works fine with the same config.

4.11 shipped with Ubunti 16.04 or my local compile doesn't run, it just says:

```
xkbcommon: ERROR: xkb_x11_keymap_new_from_device: illegal device ID: -1
08/16/2016 10:40:54 AM - ERROR: xkb_x11_keymap_new_from_device failed
i3: Could not load keymap
```

*Note:* pressing mod4+d was the last thing I did before dumping the log, so
the end of the log should be relevant.

Also, I followed these instructions:
https://faq.i3wm.org/question/5383/i3-ignores-mod4-windows-key-when-in-vnc-session.1.html
they are necessary in 4.10.4 but have no effect in 4.12.

**Comment by Airblader** [comment]
Here are the relevant log lines regarding parsing the keyboard state:

````
08/16/2016 10:29:52 AM - main.c:main:563 - xkb is not present on this server
08/16/2016 10:29:52 AM - No XKB / core keyboard device? Assembling keymap from local RMLVO.
08/16/2016 10:29:52 AM - ERROR: Could not get _XKB_RULES_NAMES atom from root window, falling back to defaults.
```

I think most likely everything works as intended here, but the problem is that your VNC doesn't set any kind of hints as to which keymap to use, so we fall back to system defaults. But let's verify.

Can you remove the binding, reload the config and press the combination while running `xev -event keyboard`? Then provide that output here. Relevant for comparison:

````
08/16/2016 10:29:52 AM - ../i3-4.12/src/bindings.c:translate_keysyms:450 - state=0x40, cfg="f", sym=0x66 → keycodes 41 (1)
08/16/2016 10:30:03 AM - ../i3-4.12/src/bindings.c:translate_keysyms:450 - state=0x40, cfg="d", sym=0x64 → keycodes 40 (1)
```

**Comment by stapelberg** [comment]
Which VNC client/server implementation are you using?

**Comment by tbnorth** [comment]
@stapelberg xtightvncserver - took a long time to find one that gave good performance on my hardware (raspberry pi) and network (mediocre).  So others might be better for this key binding issue, but not sure I can switch.

@Airblader New log
http://logs.i3wm.org/logs/5638059940904960.bz2

With the binding for *mod4+f* removed, xev gave the following for *mod4+d*
```
KeyPress event, serial 22, synthetic NO, window 0x1c00001,
    root 0x25, subw 0x0, time 2490933740, (799,511), root:(801,531),
    state 0x0, keycode 89 (keysym 0xffeb, Super_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 22, synthetic NO, window 0x1c00001,
    root 0x25, subw 0x0, time 2490934038, (799,511), root:(801,531),
    state 0x40, keycode 41 (keysym 0x64, d), same_screen YES,
    XLookupString gives 1 bytes: (64) "d"
    XmbLookupString gives 1 bytes: (64) "d"
    XFilterEvent returns: False
```

so as you seemed to guess, it's getting d and f confused, it seems. Without disabling the mod4+f binding, the KeyPress event for 'd' was missing in the xev output.

**Comment by Airblader** [comment]
> Without disabling the mod4+f binding, the KeyPress event for 'd' was missing in the xev output.

Yeah, that's expected since i3 will have grabbed the binding.

> it's getting d and f confused, it seems

It's not getting anything confused. It's just using the system default keyboard layout which isn't the one you want to use. But your VNC X server doesn't have anything that tells i3 what layout to use.

**Comment by stapelberg** [comment]
Related: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=476727

I think this should be taken upstream to https://sourceforge.net/p/vnc-tight/bugs/ after verifying that other VNC servers work.

**Comment by Airblader** [comment]
@tbnorth Have you taken this upstream?

**Comment by Airblader** [comment]
It's been two months. Once this is taken upstream please post the link here and we can reopen if necessary.
