### ISSUE TITLE
[feature request] Disable focus wrapping between containers

### ISSUE THREAD

**Issue by CamWright** [i3/i3#2432]
A few (admittedly not many) people have requested that there be an option to disable focus wrapping when reaching the edge of the screen. The only references I could find to this feature request are [this FAQ question](https://faq.i3wm.org/question/874/how-to-disable-focus-wrapping/) and [this closed issue](https://github.com/i3/i3/issues/2352).

I understand the sentiment for why not all patches are merged, and it seems that was the justification for closing the feature request. However, I would be willing to author the patch if it would be welcome. Is this something I should do?

**Comment by stapelberg** [comment]
Thanks for checking.

I don’t see evidence for an increase in user demand since https://github.com/i3/i3/issues/2352#issuecomment-220445479, so the current position is still that we will not merge such a patch into i3.

Thanks for your understanding!
