### ISSUE TITLE
enhancement: continuous build broken

### ISSUE THREAD

**Issue by stapelberg** [i3/i3#2437]
See https://travis-ci.org/i3/i3/builds/157492807

There’s two issues:

1. (gcc) Building debian packages fails
2. (clang) tests fail because AddressSanitizer is broken with clang and libc ≥ 2.24

As for ①, the issue seems to be quoting of the defines. Still looking into that.

As for ② (see also https://bugs.archlinux.org/task/50366) the following workaround seems to help:
```
cat >fixasan.c <<C
> void __isoc99_printf() {}
> void __isoc99_sprintf() {}
> void __isoc99_snprintf() {}
> void __isoc99_fprintf() {}
> void __isoc99_vprintf() {}
> void __isoc99_vsprintf() {}
> void __isoc99_vsnprintf() {}
> void __isoc99_vfprintf() {}
> void __cxa_throw() {} // NEW
> C
gcc fixasan.c -o fixasan.so -fPIC -shared -nostdlib
```

Then, run the tests with `LD_PRELOAD=./fixasan.so`

**Comment by stapelberg** [comment]
@eplanet In https://github.com/i3/i3/pull/2419/files, you removed the single quotes around I3_VERSION for the non-git case. This breaks Debian builds on travis. The same seems to be true for i3status, whereas in i3lock, the single quotes are still present.

Was that a mistake, or is there a reason you wanted to remove these?

**Comment by eplanet** [comment]
@stapelberg: it actually wasn't a mistake, the [doc I consulted](https://www.gnu.org/software/make/manual/html_node/Shell-Function.html) didn't mention quotes and since there wasn't any difference with or without quotes in the tests I did, I thought it would simplify the syntax without quotes.

No doubt I was wrong since it breaks the Debian builds… Would you like me to correct it ?

**Comment by stapelberg** [comment]
We use the quotes to enclose the _output_ of the shell command, so it’s not a surprise to me that the documentation for the shell command doesn’t mention it :).

Thanks for clarifying, I’m fixing these myself now.

**Comment by eplanet** [comment]
Sorry about that :-S
