### ISSUE TITLE
for_window [title="VIM$"] title_format is not updated correctly.

### ISSUE THREAD

**Issue by teto** [i3/i3#2446]
Output of `i3 --moreversion 2>&- || i3 --version`:
```
Binary i3 version:  4.12-97-g59c070b (2016-09-05, branch "next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12-97-g59c070b (2016-09-05, branch "next") (pid 3844)
Loaded i3 config: /home/teto/.i3/config (Last modified: dim. 11 sept. 2016 17:40:37 CEST, 59 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

```

URL to a logfile as per http://i3wm.org/docs/debugging.html:
http://logs.i3wm.org/logs/5670249378611200.bz2

**What I did:**
I have in my config : `for_window [title="VIM$"] title_format " %title"` to display some icon for terminals running (neo)vim. I use termite as a terminal  (VTE based).
1. launch termite
2. run zsh -f (prevents loading .zshrc)
3. start neovim (alternatively you change the terminal title  with `print -Pn "\e]0;VIM\a"`)
4. Close neovim (alternatively you change the terminal title  with `print -Pn "\e]0;test\a"`)

**What I saw:**
When launching Neovim, i3 correctly prepends my utf8 icon to the terminal title. Upon leaving neovim (step 4), the title gets changed but the icon remains.

**What I expected instead:**
To have the icon only when neovim is running and then disappears when the program exits.

**Comment by Airblader** [comment]
That is not how `for_window` works. It's only run when managing the window. There's no »undo« mechanism built into it. If you want that kind of functionality, you'll need to write a script that listens for events and handles them.
