### ISSUE TITLE
assert(result != NULL) in con_get_output() fails during/after undock

### ISSUE THREAD

**Issue by Cornelius-Riemenschneider** [i3/i3#2459]
Output of `i3 --moreversion 2>&- || i3 --version`:

~  i3 --moreversion 2>&- || i3 --version
Binary i3 version:  4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12-105-g555f458 (2016-09-12, branch "next") (pid 10664)
Loaded i3 config: /home/corni/.i3/config (Last modified: Sun 28 Aug 2016 03:55:27 PM CEST, 1736688 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: /home/corni/build/i3/i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:
bzip2 -c | curl --data-binary @- http://logs.i3wm.org

**What I did:**

Undock the laptop during suspend, then un-suspend. The docked laptop has two monitors connected, the undocked laptop just its internal display.

Instead I got the following backtrace in gdb:
![img_20160917_181809](https://cloud.githubusercontent.com/assets/70492/18609516/448ad178-7d04-11e6-948f-9e1403bf98cd.jpg)
(i.e. assert(result != NULL); failed in con_get_output() in src/con.c line 365).

**What I saw:**

I3 crashed.

**Comment by Airblader** [comment]
My gut feeling is that this is the same root cause as #2276
