### ISSUE TITLE
[Feature Request] Let user change DPI / logical pixel size

### ISSUE THREAD

**Issue by joemaro** [i3/i3#2465]
Coming from here: https://www.reddit.com/r/i3wm/comments/53he0f/bordersize_is_2_pixel_config_says_1/

Would like to be my bordersize exactly 1 pixel not 2 :)
Exposing the relation between logical and physical pixels via a variable in .Xresources (for example) or the config would be amazing!

Keep up the good work devs <3

**Comment by Airblader** [comment]
I've had this idea in my head for a while and would favor it. We already introduced `xcb-util-xrm` as a dependency, so this would be relatively easy to do.

**Comment by stapelberg** [comment]
We should use the well-established `Xft.dpi` variable for that.

**Comment by Airblader** [comment]
We sure can, but there were two reasons why I propose a different variable:

1. Xft is for fonts, so it somewhat seems like we're stealing another client's resource. That's not the spirit of X resources. The user is supposed to use wildcards to share values. 
2. Many users have this resource set and using it could lead to unintended changes for users from which they cannot recover.

**Comment by stapelberg** [comment]
`Xft.dpi` should be set to the DPI that you want your system to use. Other toolkits such as GTK and applications such as Chrome or Firefox will scale depending on `Xft.dpi`.

I can’t see any unintended changes that could happen here. i3 should follow the same approach that other widely-used software uses, thereby actually minimizing confusion/surprises.

It might be worth noting that I’m in favor of making the DPI detection more standard by querying `Xft.dpi`, not in favor of making the DPI independently configurable in i3 or theming i3 by changing the number of pixels for borders.

**Comment by Airblader** [comment]
Fair enough. I just wanted to explain my thoughts. If we accept this then I'm fine with using Xft. :-)
