### ISSUE TITLE
Window in a single-child tabbed container moves across displays

### ISSUE THREAD

**Issue by darkengine-io** [i3/i3#2466]
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12 (2016-03-06, branch "4.12") (pid 896)
Loaded i3 config: /home/simon/.i3/config (Last modified: Wed 21 Sep 2016 10:41:51 AM PDT, 4076 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5713050069893120.bz2

**What I did:**
1. open a new, empty workspace
2. mod+enter+enter to create two terminals, side by side
3. focus right-hand terminal, type something in it to make sure it is distinguishable from the other terminal
4. mod+v to create a new container
5. mod+w to switch it to tabbed mode
6. alt+shift+left to move the terminal out of the tabbed container

**What I saw:**

On a multi-monitor setup, the terminal moves to the right-hand side of the monitor to the left. On a single-monitor setup (or if the workspace is on the far-left monitor), the terminal does not move at all, and the tabbed container does not get destroyed. I have reproduced this on two machines, and with the default config.

**What I expected instead:**

I expected the tabbed container to be destroyed, leaving the terminal in the same place. I have done this in older versions of i3 to destroy single-child containers, and it does not seem to be working anymore.

**Comment by Airblader** [comment]
I can reproduce this and think that it is a bug as well. Given that it worked before, can you perhaps bisect the issue?

**Comment by darkengine-io** [comment]
A git bisect reveals this is the commit that broke it: 4e88c10564ca5366c2578908f62ec56625a26718.

**Comment by Airblader** [comment]
Thanks! @Deiz CC

**Comment by Deiz** [comment]
I only vaguely recall writing this, but the rationale is laid out in #1603. Perhaps a more refined approach would be to take the workspace's default layout into consideration.

**Comment by darkengine-io** [comment]
This bug is still present in 4.13 (I'm currently using a build with the aforementioned commit reverted). Is there a fix in the works for this?

**Comment by CyberShadow** [comment]
Not just tabbed containers. For example:
```
┌───────────────────────────┐  ┌───────────────────────────┐
│         Monitor 1         │  │    Monitor 2 - splith     │
│                           │  │┌───────────┐┌────────────┐│
│                           │  ││           ││   splitv   ││
│                           │  ││           ││╔══════════╗││
│                           │  ││           ││║          ║││
│     (empty workspace)     │  ││           ││║  Focused ║││
│                           │  ││           ││║  window  ║││
│                           │  ││           ││║          ║││
│                           │  ││           ││╚══════════╝││
│                           │  │└───────────┘└────────────┘│
└───────────────────────────┘  └───────────────────────────┘
```

"move left" will move the focused window to monitor 1.
