### ISSUE TITLE
[Feature Request] Allow splitting/tabbing/stacking floating containers

### ISSUE THREAD

**Issue by kairos** [i3/i3#2467]
I think it would be nice to be able to splitv/splith/stack floating containers, and resize child-containers. Currently we can select a container that we've organized in tiling mode, then float that, but it's not possible to modify that container (besides closing child-containers, and resizing the entire container)

Thoughts?

**Comment by Airblader** [comment]
> Thoughts?

Floating windows in i3 exist for dialogs and the like. We don't intend them to be used for normal windows or containers because i3 is a *tiling* window manager.

**Comment by Airblader** [comment]
Just FYI:

> Currently we can select a container that we've organized in tiling mode, then float that

That's not intended behavior and nothing we actually support. It might even cease to work in a future version.
