### ISSUE TITLE
[Feature Request] Add support for back_and_forth within each display

### ISSUE THREAD

**Issue by pstray** [i3/i3#2470]
What I suggest it that the 'workspace back_and_forth' command get an additional optional parameter, that changes its behaviour to only consider workspaces linked to the current display.

I guess this would need i3 to keep track of the last workspace shown on each display, an not only the last one active.

**Comment by Airblader** [comment]
duplicate of #https://github.com/i3/i3/issues/2118

**Comment by pstray** [comment]
Definitly not a duplicate, but related.

**Comment by Airblader** [comment]
I think our general stance holds true either way that this should be done in an external script. 

@stapelberg Correct me if you feel differently.

**Comment by stapelberg** [comment]
I agree with @Airblader
