### ISSUE TITLE
Mention rofi in the default configuration next to dmenu_run

### ISSUE THREAD

**Issue by Airblader** [i3/i3#2482]
As we're already discussing moving away from i3-dmenu-desktop, I'd also like to suggest changing the default config from dmenu to rofi. My reasons are simple enough:
- dmenu is no longer maintained and lacks a lot of features many users prefer.
- rofi is actively developed, can be made compatible with dmenu and does pretty much everything a user expects from a launcher.

CC @DaveDavenport

**Comment by Airblader** [comment]
Actually it seems dmenu has seen a release about a year ago. Even so, its development is much slower and rofi offers a whole bunch of nicer features.

**Comment by carnager** [comment]
Do I understand this correctly? You plan to remove i3-dmenu-desktop? So deciding on rofi would this make a static default choice that users have to override manually.

I don't think this is a good idea, since rofi is not in all distributions, but dmenu most likely is.

**Comment by Airblader** [comment]
> You plan to remove i3-dmenu-desktop?

Yes, but not with this issue. That's #949.

> So deciding on rofi would this make a static default choice that users have to override manually.

I'm not sure what you mean with static default, but I'm talking about the default config delivered with i3. A user can still easily switch to dmenu if they want.

> I don't think this is a good idea, since rofi is not in all distributions, but dmenu most likely is.

Which distributions exactly? Also, it's not a dependency, just a recommended tool.

**Comment by carnager** [comment]
i was confusing i3-desktop-menu with that terminal tool which uses whatever is present on system. updated my answer. still think a default should use the tool that's most likely available

**Comment by Airblader** [comment]
Same question. On which distributions is rofi not available?

**Comment by carnager** [comment]
afaik it's not in fedora

**Comment by Airblader** [comment]
It seems that while not available from the core distribution, rofi is available on Fedora from two different repositories. It's not a hard dependency and would be easy to provide a package there as well. I think the benefits of a more modern launcher outweigh that. The config could still mention dmenu as an alternative. I just think the typical new user benefits from being offered a better tool than dmenu.

**Comment by carnager** [comment]
being a collaborator of rofi I obviously agree on the "being better" part. And as an arch user I don't care either. Maybe make it part of the config wizard :)

**Comment by Airblader** [comment]
> Maybe make it part of the config wizard :)

I think that'd be too much complexity (I'd prefer just closing this issue over that). The config wizard is really only a quick way to get started. Virtually the only option it offers you is setting the modifier key. Having the launcher as the second option seems out of place. :-)

i3 typically even installs without dmenu, at least I'm not aware of a single distro that has dmenu as a hard dependency on the package. So the user will always still have to decide and install a launcher anyway.

Regarding Linux Mint: I'm pretty sure it also doesn't have a current i3, though. Debian based distros usually lag behind, sometimes quite a bit. When Mint gets i3 4.13, they might (should!) also have rofi.

**Comment by carnager** [comment]
Just checked. Ubuntu 16.04 has rofi. Current Debian too, Opensuse too. Even Slackware (that one surprised me). I guess there is no major player left. (Apart from fedora)

**Comment by Airblader** [comment]
I say let's give Fedora a reason to finally provide it. :-) And thanks for checking up on it.

**Comment by mosajjal** [comment]
As I said in #2475, rofi can also run commands with "pipe" in them. Also it keeps a history of commands. Overall it just tops !!

**Comment by Airblader** [comment]
@Hummer12007, @milouse You downvoted this feature, so I'm curious to know what your reasons against this change are?

**Comment by Hummer12007** [comment]
Mostly personal preference, but roughly: connman_dmenu and several other scripts which use it, rofi's broken under xwayland (so no consistency with sway (I sometimes use i3-gaps as well)), simplicity.

**Comment by Airblader** [comment]
> connman_dmenu and several other scripts which use it

We're not developing dmenu nor do we stop anyone from using it if they're using it already. We're talking about changing the default config here. Perhaps I'm misunderstanding the point?

> rofi's broken under xwayland (so no consistency with sway (I sometimes use i3-gaps as well))

We don't really care about sway in i3 (as harsh as it sounds) because sway is not leading the way for i3. Otherwise we wouldn't have been able to implement Xresources support either. And again, dmenu / rofi aren't an integral part of i3, they're just an external application for which we provide a default binding. rofi can choose to keep dmenu in their default config.

**Comment by Hummer12007** [comment]
@Airblader, that's why I've said personal preference.

**Comment by Airblader** [comment]
Yes, I skipped that point because clearly there is no arguing personal preference (and mine would be for rofi). I just wanted to make counter arguments for the arguments you made which aren't about personal preference. :-)

**Comment by Hummer12007** [comment]
Just to clarify, if you misunderstood. Consistency as in "personal consistency". You know, I use the same config in both, so I really have no reasons to object. Downvote withdrawn.

**Comment by Airblader** [comment]
I don't mind the downvote, I'm glad people (you) are participating in the discussion. Just wanted to make sure we can hear each side's arguments. So thank you!

**Comment by milouse** [comment]
As you may have seen on my profile, I'm a « sort-of » contributor to rofi: I maintain several side-branch of various project to add rofi support, like in i3-quickswitch. I use rofi as dmenu replacement on my i3 config.

However, I strongly disagree several point set in this thread:

* There is no relation between the date of the last version of a software and its quality. dmenu comes from the suckless community and, as this, put the stability/simplicity over all.
* Rofi is a much more complex/feature-full software, wich describes itself as [much more than dmenu](https://github.com/DaveDavenport/rofi/issues/457). Does i3 need a bazooka to kill a fly? 
* It's not clear if rofi may or may not stop dmenu-like support one day.
* Rofi is not available in all distribution and promoting non-official/default repos is wrong (this part may evolve if rofi become available in all major distro).

Thus, my point is: dmenu as a stable-simple-justdoit command-running interface is sufficient enough. Here we are talking about default configuration of something, which is not a hard dependancy. I think it's a better idea to keep promoting simple and sane stuff to newcomers. Rofi may be mentionned in the default config to explain how to change dmenu to something else (because why promote Rofi over Synapse, Mutate, Albert, grun, …?).

Or i3 may use a « sensible-command-launcher » as it does with terminal application. Putting rofi before dmenu and using the first present on the user system.

**Comment by Airblader** [comment]
Thanks for your input!

> There is no relation between the date of the last version of a software and its quality. dmenu comes from the suckless community and, as this, put the stability/simplicity over all.

True, but also see next point.

> Rofi is a much more complex/feature-full software

There are a bunch of dmenu patches and forks floating around and a lot of people resort to using one of them. That seems like an unnecessary annoyance and I'm not sure promoting the suckless approach of »just apply the patches you want« is much better than promoting unofficial repositories.

> Does i3 need a bazooka to kill a fly?

i3 doesn't »need« any of this anyway. I see quite a lot people switching away from dmenu eventually and I'm not sure what the benefit of keeping a suggestion with much fewer features are.

> It's not clear if rofi may or may not stop dmenu-like support one day.

Perhaps the KDE guys should not switch to Wayland then, because we don't know if one day… :-)

> Rofi is not available in all distribution 

In which ones isn't it available? In particular, in which distribution is rofi not available, but i3 4.14 will be? We discussed this above and apparently Fedora is the only missing player here. Isn't the better solution to get rofi into Fedora? What's the reason not to have it there?

> Rofi may be mentionned in the default config to explain how to change dmenu to something else (because why promote Rofi over Synapse, Mutate, Albert, grun, …?).

Yes, I'd personally be OK with just mentioning rofi as an alternative in the i3 config as well (and keeping dmenu as the default).

By the way, one benefit of using rofi over dmenu is that i3 currently maintains its own i3-dmenu-desktop script which is really sort of out of place in the i3 repository (we're not a launcher!). rofi offers this functionality out of the box.

**Comment by DaveDavenport** [comment]
> * It's not clear if rofi may or may not stop dmenu-like support one day.

DMenu support will not be removed.


For the rest I agree with point 1 and 4. 

Point 2, I kind of agree. But Rofi does not replace just dmenu but also the script wrapping it providing the actual launching functionality.  Given it provides more (imho) useful functions (window switch, run dialog, desktop dialog etc. ) it might be worth it (but I am biased).

Having said this, I don't really care what ever is done.

**Comment by milouse** [comment]
@DaveDavenport thanks for the clarification.

Regarding the distribution integration, you got a point @Airblader : as this optional dependency will only be for the new i3 version, old version will not be impacted and that will be the packager job to choose the right tool available for its distribution when the new i3 version will be published.

As a side note, do not forget to not only see where is rofi available, but also for which architecture. i3 may be available on some distro for ARM architecture with dmenu, where rofi will only be available for i686/x86_64. I don't take the time to check this one, sorry if it's just noise.

BTW, all my points where only my own opinion and as we're talking about an optional dependency, seriously, feel free to do what you think is the best for your project :) It's not me, who's in charge of the day to day support and progress of this project. Thanks for your work and listening!

**Comment by DaveDavenport** [comment]
FYI: rofi is tested (I use it myself) on ARM. There is currently no reason for it to be only available on x86/x86_64 it goal is to work on multiple architectures.

**Comment by milouse** [comment]
… and it's available for [Archlinux arm](https://archlinuxarm.org/packages/?q=rofi) and debian arm at least.

**Comment by Airblader** [comment]
So I think what we arrived at is mentioning rofi in the comment of the binding is fine, but we won't switch the binding itself to rofi.

**Comment by DaveDavenport** [comment]
Can I suggest a title change from:

>  Mention rofi in the default configuration next to rofi 

to

>  Mention rofi in the default configuration next to dmenu_run

(side-note:. dmenu is not a launcher, the script around it is.)

**Comment by Airblader** [comment]
Sure. :-)

**Comment by hallgat89** [comment]
I suggest to define the default config like this:
bindsym $mod+d exec rofi -show run || j4-dmenu-desktop || dmenu_run
Might look a bit complicated but good for all cases :)

**Comment by Airblader** [comment]
That won't work right if, say, rofi exits with an error code for some reason. And I'd like to avoid it being too complex.
