### ISSUE TITLE
Some programs become unusable (firefox, terminator)

### ISSUE THREAD

**Issue by david-caro** [i3/i3#2493]
Output of `i3 --moreversion 2>&- || i3 --version`:
Binary i3 version:  4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12 (2016-03-06, branch "4.12") (pid 7685)
Loaded i3 config: /home/dcaro/.i3/config (Last modified: Mon 22 Aug 2016 03:47:09 PM CEST, 3900409 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5650082896543744.bz2

**What I did:**

Start i3, open a terminator window, then open a firefox window, copy the og dump command and paste and execute it on the terminator window.

**What I saw:**

none of the windows refreshed properly, though they refresh if you change focus, that means that you don't see what you are typing until you change the window or a few seconds have passed.

**What I expected instead:**
Smooth refresh as usual, seeing in the window what you just typed almost instantaneously .
Please fix this, I love i3 and so far it has been amazing, let me know if you need any other information. I'm running on Fedora 24, and this started happening around 3 months ago. It does not happen on all windows, for example, with gnome-terminal it works well, but specially terminator and firefox lag a lot (and those are two of my main tools...).

Thanks for the great work!!

**Comment by Airblader** [comment]
Are you using a compositor and if so, can you reproduce it without it?

Applications freezing up isn't something I can imagine i3 being at fault for. It sounds odd, but i3 doesn't have anything to do with the applications. We only care about the window and even there we only care about their geometry etc. What happens *inside* the window is out of our reach.

**Comment by david-caro** [comment]
Well, I'm using gdm (not sure if that's what you mean by compositor), the default configuration that's used in fedora 24. Starting up with gnome3 instead of i3 works well, and it was working well too a few months back, that's why I think it's worth investigating on the i3 side too, as it seems to happen only on it, and not only for one application but for an heterogeneous set of them. If you tell me how to get the info about the compositor I'll post it here.

**Comment by Airblader** [comment]
> gdm (not sure if that's what you mean by compositor)

gdm is a display manager. A compositor is something like compton. Do you run i3 as a window manager within some desktop environment or do you run i3 standalone?

> and it was working well too a few months back, that's why I think it's worth investigating on the i3 side too

But this really comes down to how these moving parts interact. And the window manager isn't involved in the process of rendering the client itself. These issues basically always come down to compositing or video driver issues. :-)

**Comment by david-caro** [comment]
I run it as a window manager as far as I know, but it should be running with the same compositor than the gnome session, and with gnome I have no issues. Same video driver too.

If you guide me I can try to check which compositor it's using.
