### ISSUE TITLE
workspace id line at bottom disappears, workspace operations do not take effect

### ISSUE THREAD

**Issue by OSS542** [i3/i3#2504]
Output of `i3 --moreversion 2>&- || i3 --version`:

i3 version 4.12 (2016-03-06, branch "4.12") Â© 2009 Michael Stapelberg and contributors

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5662979341156352.bz2

---------------------------------------------

**What I did:**
create a default config file on i3 startup
restart i3

**What I saw:**
workspace id line at the bottom disappears.
Workspaces do not work. For example, cannot move to another workspace,
cannot move window to another workspace, etc

**What I expected instead:**
i3 works normally
workspace id line at the bottom appears.
Workspaces work normally.

---------------------------------------------

**What I did:**
rm -r .config/I3 # remove entire i3 configuration directory
start i3
use defaults instead of creating configuration directory

**What I saw:**
i3 works normally
workspace id line at the bottom appears.
Workspaces work normally.

---------------------------------------------

**What I did:**

use the only these two lines in .config/i3/config:

 # i3 config file (v4)
bindsym Mod1+Return exec i3-sensible-terminal

start i3

*** NOTE: The log supplied was taken under this circumstance.

**What I saw:**
workspace id line at the bottom disappears.
Workspaces do not work. For example, cannot move to another workspace,
cannot move window to another workspace, etc
Modify any part of the first line in the above short config file, and the workspace id line will appear as expected

---------------------------------------------

**Comment by Airblader** [comment]
The config with two lines cannot work because font is a required directive in the config and you're missing it. This will cause i3 to exit. 

This shouldn't happen with the generated config though since it should contain a font. Can you get a log file from that scenario?

**Comment by OSS542** [comment]
I will test this right away and reply in a few minutes.  I should note that i3 did not exit on trying to use the short config file, but appeared to work correctly with a single workspace.  The workspace id line disappeared, and workspace operations did not work.

**Comment by Airblader** [comment]
Actually it looks like it's no longer mandatory, though there is some dead code for it. Anyway, the log file just cuts off. I think what would help more is a backtrace from gdb. Can you get that?

**Comment by OSS542** [comment]
2nd log with font directive
http://logs.i3wm.org/logs/5722152447770624.bz2

short config file with font directive:

# i3 config file (v4)
font pango:monospace 8
bindsym Mod1+Return exec i3-sensible-terminal

workspace id line at the bottom disappeared as before.

**Comment by OSS542** [comment]
I should be able to manage that.  At what point do you need the backtrace ?

**Comment by OSS542** [comment]
I would in that case be starting X manually from the console and starting the window manager after setting the DISPLAY value, but I can do that if that would be helpful.

**Comment by Airblader** [comment]
Given that you say i3 doesn't crash that's an interesting question. Let's just try right after the bar disappears. Actually, right before that, can you execute `i3-msg nop TEST` and then trigger the binding to switch workspaces, followed by `i3-msg nop TEST` again?

You can avoid starting X and i3 manually by attaching gdb afterwards with `gdb $(which i3) $(pidof i3)`, but it might require root. You also need the debug symbols installed.

**Comment by OSS542** [comment]
The bar is not present at startup in the cases where workspaces are not operating normally.  It is present at startup when the config file is not used at all, or when the short config file is modified.

**Comment by Airblader** [comment]
One more thing, what system do you use? Linux or some BSD?

**Comment by OSS542** [comment]
Linux, constructed entire from source..... designed it myself.

**Comment by Airblader** [comment]
OK, then I assume you are familiar with compiling and the like. Before we do anything on the above, let's try something else. Can you compile i3 from source but try 4.11? If that works, we can just bisect it.

**Comment by OSS542** [comment]
using the short config file, I would not expect the workspace bindings to work, but I was expecting the workspace line to appear as it does when no config file is used.  In that case, is i3 using internal defaults of some sort ?  If so, does the "default" config file generated by the wizard actually match the internal defaults ?   The internal defaults, if they exist, appear to be working correctly.

**Comment by OSS542** [comment]
I can certainly try 4.11 instead of 4.12.   It will take a few minutes to remove 4.12 and do the build.  I will start now and let you know the result when I have done that.

**Comment by Airblader** [comment]
The »workspace line« on the bottom is actually a different program, i3bar. It comes with i3 but is a separate binary started by i3. With a short config file no such bar will appear as the configuration is not telling i3 to run i3bar. :-) Of course workspace bindings then also will not work.

The created config by the wizard should, however, display the bar. And switching workspaces should work, assuming you're pressing the correct keys. A log file from using the config created by the wizard a few seconds after start up might also be interesting, perhaps we just have some misunderstanding.

**Comment by OSS542** [comment]
note:  4.12 was also done from source

**Comment by OSS542** [comment]
I just looked at the config file generated by the wizard.  It does not appear to have an invocation of i3bar.

**Comment by OSS542** [comment]
I will generate a log file using the config built by the wizard and send that before doing the 4.11 build.

**Comment by Airblader** [comment]
It should have a `bar {` block at the bottom. It won't say `i3bar` anywhere since using that binary is the default in i3.

**Comment by OSS542** [comment]
It has no such block as far as I tell.

**Comment by OSS542** [comment]
The only "bar" reference is in the comments around the font directive.

**Comment by Airblader** [comment]
I'm starting to feel like the wizard is creating an incomplete config. Can you upload the generated config to pastebin?

**Comment by OSS542** [comment]
I will do that.  I am preparing the log file from i3 using the config generated by the wizard.
I will then upload the generated config to pastebin.
After that, if you need, I will remove 4.12 and build using 4.11.

just give me a minute and I will send the log file....:-)

**Comment by OSS542** [comment]
3rd log:  using config created by wizard - i3 was restarted using this config before generating the log

http://logs.i3wm.org/logs/5720758194012160.bz2

note: the workspace bar did not appear

config generated by wizard: http://pastebin.com/jQRQt1w7

**Comment by Airblader** [comment]
Yes, the generated config is broken. It's cut short. That's why the bar doesn't start and why switching workspaces doesn't work – all of those keybindings would come after that.

I know we had an issue with this under BSD, though I'm fairly sure the fix is already in 4.12. I'll have to find the ticket.

BTW, thank you for the details & support on this. I wish every bug report would be like this.

**Comment by Airblader** [comment]
Just FYI, for comparison take the file `i3.config.keycodes` in the i3 repository. That's the file i3-config-wizard will use to generate a config (but it will replace the keycodes with keysyms). There you can see where it cuts off. I assume that the next keycode that it wants to look up cannot be found and then it somehow aborts.

**Comment by Airblader** [comment]
#2141 is the issue I was talking about.

**Comment by OSS542** [comment]
just to note:  I used the 4.12 release to test this.  Is the fix in git ?

**Comment by Airblader** [comment]
Actually issue #2141 is still open, the fix for it was never merged because the PR was broken.

**Comment by Airblader** [comment]
@OSS542 Which key map rules did you configure for your Linux? evdev or base? Can you read up on #2141 and check if it's the same issue hitting you?

**Comment by OSS542** [comment]
looks like it's the same thing.   I did not do anything special xmodmap wise.   "xmodmap -pk" reports something that looks very like the base rules.  I'll look into the evdev rules.  I'm not terribly familiar with these, so it will be a much needed education

**Comment by OSS542** [comment]
The 2141 issue mentioned a complete config file at pastebin.  I'll get that one and try it.

**Comment by OSS542** [comment]
I have just picked up the complete config file [complete config file](http://pastebin.com/raw/ccW571zk).
That one works perfectly as far as I can tell.   I am presently running i3 without difficulty.

**Comment by Airblader** [comment]
Alright. I'm going to close this as a duplicate in favor of #2141 now. Thanks for your quick help on narrowing this down. :-)
