### ISSUE TITLE
Xcb Badwindow errors and hanging dialog box

### ISSUE THREAD

**Issue by 3sideslive** [i3/i3#2540]
Binary i3 version:  4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12 (2016-03-06, branch "4.12") (pid 25924)
Loaded i3 config: /home/mark/.config/i3/config (Last modified: Sat 05 Nov 2016 06:20:09 PM EDT, 2002 seconds ago)
The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile: http://logs.i3wm.org/logs/5706316634914816.bz2
Running on Arch Linux 4.8.6-1-ARCH #1 SMP PREEMPT Mon Oct 31 18:51:30 CET 2016 x86_64 GNU/Linux, QT5 version 5.7.0

A couple days ago I submitted a bug report to project Valentina: [584/frequent-xcb-errors-and-hangs](https://bitbucket.org/dismine/valentina/issues/584/frequent-xcb-errors-and-hangs)

Their program frequently hangs when I start but then cancel an action. A warning dialog box starts to display but is apparently never drawn (completely black). The program still appears responsive but the dialog can't be dismissed, so it has to be killed/restarted. Valentina's log always ends with the same error: 

`[2016.11.04 18:39:26:WARNING:(0)] : default: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1996, resource id: 10486107, major code: 40 (TranslateCoords), minor code: 0`

I haven't been able to get much information about this error and I've tried various reinstalls and other things, but I learned today that as long as I use another WM, the issue disappears. The issue reappears if I create a new user, login and start I3 with its default configuration, then run Valentina. Because it seems to be related to I3 I'm submitting this. Searching I3 issues for 'XCB' did find this which could possibly be related(?) [Issue 2525 - xrandr error when switching displays - black rectangle](https://github.com/i3/i3/issues/2525)

In case it helps with the log file:
18:45:08  - started Valentina and tried starting/cancelling a few things, until...
18:47:00  - clicked CANCEL on its Preferences dialog - warning dialog box shows up black.
18:47:30  - mouse drags of the blacked-out dialog box
18:47:45  - killed process

**Comment by Airblader** [comment]
> I haven't been able to get much information about this error

It means that Valentina is trying to do something with a window that doesn't exist (anymore or ever, probably anymore). To me this is most likely a fault in Valentina (despite it only occuring with i3 as you say). The client is informed if a window is closed and Valentina should listen for that and not send any more requests to that window.

That said, it doens't mean something goes wrong in i3 *before* that. A way forward here would be to run Valentina under xtrace and then upload both the xtrace log and the i3 log (of the same(!) run) so we can look at them and compare.

xtrace will create tons of log output within seconds, so don't waste any time with it and reproduce the problem as soon as possible and then instantly kill Valentina again. Likewise, restart i3 first (and enable debug logging) so the i3 log is kept to a minimum.

**Comment by Airblader** [comment]
Also, you should ask the Valentina developer to track down where the failing call is coming from, i.e., what the application is trying to do in that moment. Unfortunately that may be difficult because reading the post I get the impression the developer is unfamiliar with X (and what's happening is hidden behind Qt from their point of view).

**Comment by Airblader** [comment]
On an unrelated side note, your config contains a few illegal statements where you put a comment on the same line as the command to execute:

    for_window[class="jedit"] floating enable                                   # jedit

That doesn't work and causes errors in the log file.

**Comment by Airblader** [comment]
Also it's unfortunate that the i3 log you posted is from a different day than the line in the Valentina log. Please make sure that logs you post actually belong together. :-)

**Comment by Airblader** [comment]
And one (hopefully) final hint would be to make sure you close all irrelevant windows, restart i3 and only then pull logs. Otherwise the log file ends up containing some information you may not want to share, such as gmail addresses.

**Comment by 3sideslive** [comment]
thanks for all your help.  i will try this first thing tomorrow.

**Comment by dismine** [comment]
> Unfortunately that may be difficult because reading the post I get the impression the developer is unfamiliar with X (and what's happening is hidden behind Qt from their point of view).

True, i am unfamiliar with X. 

> It means that Valentina is trying to do something with a window that doesn't exist anymore. To me this is most likely a fault in Valentina (despite it only occuring with i3 as you say).

I will not insist that my code is perfect. But still this is little bit odd. The same code works fine on many platforms. But I also had expirience when my wrong configuration of a dialog that cause bug in window system. So, maybe you are right. But if i only could understand what is wrong.

**Comment by 3sideslive** [comment]
Well I can't get it to start up in xtrace. And that is across several setups, while anything else starts up and runs just fine. Clearly you are most likely correct. If anything shines some light on this in the future I'll add it but I don't have the skill or time to track this down now. Thanks for the help. I'll follow up with the dev as well.
