### ISSUE TITLE
Slow loading of Chrome

### ISSUE THREAD

**Issue by edgard** [i3/i3#2583]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.13-non-git © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13-non-git (pid 11709)-c to abort…)
Loaded i3 config: /home/edgard/.config/i3/config (Last modified: Mon 21 Nov 2016 11:25:17 AM BRST, 442 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3-with-/i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5742351410528256.bz2

**What I did:**

Switched to Chrome workspace and opened Chrome with keyboard shortcut (super+slash)

**What I saw:**

Slow loading of Chrome, takes up to 4 seconds.

**What I expected instead:**

Chrome loading faster, under 1 second or so. This is the time it takes on the same machine under Gnome-Shell.

**Comment by Airblader** [comment]
Please adapt your keybinding to do this:

```
bindsym … nop "STARTING CHROME", exec --no-startup-id google-chrome
```

Then do it again and upload the log file. I'm 99.9% that this is not an i3 issue and with that log we can see where the time is spent.

**Comment by edgard** [comment]
There you go:

http://logs.i3wm.org/logs/5643365030821888.bz2

**Comment by Airblader** [comment]
As suspected, the binding is executed at 11:48:29, but i3 doesn't receive a map request until 11:48:32. There's nothing i3 can do to open a window if no client asks to open a window. Please take this up with Chrome.
