### ISSUE TITLE
Display freezes after Fedora 25 update

### ISSUE THREAD

**Issue by SyedAmerGilani** [i3/i3#2588]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.13-32-g22faa35 (2016-11-21, branch "gaps-next") © 2009 Michael Stapelberg and contributors

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5727902603673600.bz2

**What I did:**

Updated to Fedora 25, recompiled i3 from sources and let it run

**What I saw:**

i3 works first, but after 5-15min the output freezes. from the logs i can see that i3 is still running and getting my keyboard commands.
i can reproduce this every time.
to rule out driver problems i ran gnome3 under xorg for a day and had no problems.

**What I expected instead:**

i3 works for more then 15 min.

**Comment by Airblader** [comment]
> i3 works first, but after 5-15min the output freezes.

Can you clarify that? Is it only moving windows etc. that doesn't work or are the applications themselves actually frozen? If it's the latter, then it cannot be an i3 issue since as you say i3 is still running and i3 is not responsible for what happens inside windows.

What is the RAM / CPU usage when the freeze occurs?

**Comment by SyedAmerGilani** [comment]
its like taking a screenshot of what i see and displaying it as a still image. the graphic output is frozen in place. the mouse cursur does not move anymore and the time in my i3bar stops.

RAM usage i am not sure, i have to reproduce. But CPU usage i checked last time and it was normal.
I had to ssh into the machine to get the logs.

**Comment by Airblader** [comment]
Can you still switch to another VT from that situation (Ctrl+Alt+F2)? Also, are you running a compositor with i3?

**Comment by SyedAmerGilani** [comment]
i did not try, will do it next time. Yes i am running compton.

**Comment by Airblader** [comment]
Then please also try and see if not running compton changes anything. Thanks!

**Comment by SyedAmerGilani** [comment]
Not running compton did help. i3 runs now since yesterday without problems.

**Comment by Airblader** [comment]
Thanks. In that case you want to experiment with compton. For starters, choose a different backend (xrender / glx). Unfortunately compton configuration is a bit wonky and requires trial and error.
