### ISSUE TITLE
Cannot assign to workspace by number

### ISSUE THREAD

**Issue by tarcisioe** [i3/i3#2590]
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08) (pid 20337) abort…)
Loaded i3 config: /home/tarcisioe/.config/i3/config (Last modified: Tue 29 Nov 2016 04:35:01 BRST, 4838 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

I am attaching no log since this is a feature request. For consistency and expected behaviour, I believe `assign [<criteria>] workspace number <n>` should work in the same manner as `move to workspace number <n>` does. It right now actually assigns the window to a workspace named `number <n>`.

The workaround I have found is using `for_window [<criteria>] move to workspace number <n>`, but that has slightly different behaviour (for example, if I have moved a window out of its assigned workspace and issue a `i3 restart` command it is moved back to its assigned workspace. Using `assign` does not do that.)

To illustrate with my use case: I am using a small daemon with the ipc to dynamically rename my workspaces based on their contents. Therefore, for assigning windows to specific numbered workspaces I cannot use their full name, since it is dynamic.

Thanks in advance for the attention.

**Comment by lucianoq** [comment]
+1
Any plans about this? Is this accepted or not?

**Comment by Airblader** [comment]
Yes, I think this would be OK. PRs welcome.

**Comment by nmschulte** [comment]
I was playing in the parser area of the code yesterday; I think this request may be a good candidate to continue cutting my teeth on there.  @Airblader, I'd like to discuss prioritizing my involvement in i3/friends given the project goals/priority at some point, if you find time.

**Comment by Airblader** [comment]
@nmschulte 

> I'd like to discuss prioritizing my involvement in i3/friends given the project goals/priority at some point, if you find time.

Sure, just drop me an email at admin (at) airblader (dot) de. But there are no specific project goals.

**Comment by orestisf1993** [comment]
I feel like this should work for `workspace number <number> output <output>` too. Should I open a new issue?
