### ISSUE TITLE
Missing i3bar after activating second output through xrandr

### ISSUE THREAD

**Issue by tnnn** [i3/i3#2594]
**What I did:**
I've activated second output (DP-2) by running:
`xrandr --output eDP-1 --mode 1920x1080 --pos 0x0 --rotate normal --output DP-1 --off --output DP-2 --primary --auto --pos 1920x0 --rotate normal --output DP-3 --off --output HDMI-1 --off --output HDMI-2 --off --output HDMI-3 --off; ~/.fehbg`

In the command presented above, eDP-1 is a laptop screen (it was ON before the change), DP-2 is an external monitor (it was OFF before the change).

**What I saw:**
While the DP-2 output was activated correctly, it was missing i3bar. Inplace i3 restart fixed the issue.

**What I expected instead:**
Activated DP-2 output with visible i3 bar.

**Additional info:**
This issue doesn't manifest itself in the last version that was not using RandR 1.5 (f2ffd8d8644c6c663f9da90cff42ac31acdc462e).

**URLs to a logfiles:**
Missing i3bar: http://logs.i3wm.org/logs/5693200475881472.bz2
Successful switch: http://logs.i3wm.org/logs/5641647580774400.bz2

**i3 versions used:**
Missing i3bar: `Running i3 version: 4.13-24-gd7dcef6 (2016-11-30, branch "next")`
Successful switch: `Running i3 version: 4.13-20-gf2ffd8d (2016-11-21, branch "4.13-20-gf2ffd8d")`

**Comment by Airblader** [comment]
Sounds similar to what @stapelberg mentioned as an issue before merging the PR. If you add

    disable_randr15 yes

to your config, does the issue go away?

@stapelberg Didn't take long. :-)

**Comment by tnnn** [comment]
I'll check it out (and report back) when I have access to an external screen. 

Thanks for looking into this :)

**Comment by tnnn** [comment]
@Airblader I can confirm that with `disable_randr15 yes` this issue doesn't manifest itself.

i3 version: `Running i3 version: 4.13-24-gd7dcef6 (2016-11-30, branch "next")`

**Comment by fd0** [comment]
I experience a very similar (or even the same) issue running the following version:
```
Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13-55-gfa488d72 (2017-01-24, branch "next") (pid 14006)
Loaded i3 config: /home/fd0/.i3/config (Last modified: Mo 19 Dez 2016 21:31:01 CET, 4366632 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: /home/fd0/src/i3/x86_64-unknown-linux-gnu/i3
```

When switching from the internal display of my laptop to the two external screens connected to the docking station, one of the monitors won't display a bar. This goes away when restarting i3.

**Comment by fd0** [comment]
Hm, `disable_randr15 yes` shows the bars on the right displays, but brings back #2657 for me.

Here's a log of the undocking process: http://logs.i3wm.org/logs/5750683647082496.bz2

**Comment by Airblader** [comment]
Thanks for the log. This issue we definitely should fix. :-)

**Comment by mrjovanovic** [comment]
Same issue, `disable_randr15 yes` solves it and i3bar shows up normally on external display. Using Debian stretch and i3-gaps fork (unsure if I need to submit the issue at that repository, sorry if that is the case and would be happy to do so.

**Comment by tnnn** [comment]
Seems to be working fine (without ```disable_randr15 yes```) on:
```
Binary i3 version:  4.13-212-gc40aaec7 (2017-08-20, branch "next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13-212-gc40aaec7 (2017-08-20, branch "next") (pid 1877)
Loaded i3 config: /home/tnnn/.config/i3/config (Last modified: Tue 22 Aug 2017 18:03:44 CEST, 2513 seconds ago)

The i3 binary you just called: /usr/local/bin/i3
The i3 binary you are running: i3
```

**Comment by stapelberg** [comment]
Thanks for confirming :)
