### ISSUE TITLE
Xft.dpi not working to set 480 as DPI

### ISSUE THREAD

**Issue by maletor** [i3/i3#2595]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08) (pid 599)to abort…)
Loaded i3 config: /home/maletor/.config/i3/config (Last modified: Sat 17 Sep 2016 10:31:55 AM PDT, 6402050 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5698497110081536.bz2

**What I did:**

I set `Xft.dpi: 480` in my `~/.Xresources` file.

**What I saw:**

No difference to the DPI of my fonts or i3bar despite the debug log file reading that it found the setting.

**What I expected instead:**

I expected to see the same as if I had run `xrandr --output HDMI-0 --dpi 480`.

**Comment by Airblader** [comment]
Can you please build the current git HEAD of the `next` branch and reproduce this?

**Comment by maletor** [comment]
This is resolved in `next`.
