### ISSUE TITLE
[Feature Request] i3-input: support composite keys

### ISSUE THREAD

**Issue by jolange** [i3/i3#2602]
Currently `i3-input` only recognizes single keypresses. Composite keys are not handled, e.g. `Alt Gr` + `8` on a german keyboard should produce `[`, but only `8` is displayed.

I know `i3-input` is more or less forseen as a reference implementation, but I think this "feature" is essential enough to be included: you should be able to type the symbols provided by your keyboard to be able to e.g. test commands. I guess the way `i3-lock` handles this could be adapted here.

What do you think?

**Comment by stapelberg** [comment]
Making the input handling consistent with i3lock sounds good to me. Pull requests welcome.

**Comment by Airblader** [comment]
Would #1868 take care of this already?

**Comment by stapelberg** [comment]
I think so, yes.

**Comment by Airblader** [comment]
I've added it to the other issue. Closing this one in favor of the other one.

**Comment by jolange** [comment]
Great, thanks!
