### ISSUE TITLE
offset screen rendering after resolution change with xrandr

### ISSUE THREAD

**Issue by kaueraal** [i3/i3#2613]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.13-28-g8d739b7f (2016-12-09, branch "makepkg") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13-28-g8d739b7f (2016-12-09, branch "makepkg") (pid 25372)
Loaded i3 config: /home/alexander/.i3/config (Last modified: Fr 09 Dez 2016 23:17:05 CET, 953850 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5702480826466304.bz2

**What I did:**

Change the resolution from the native one (3200x1800) to a smaller one (e.g. 1920x1080).

**What I saw:**

When changing the resolution the drawn screen is shifted to the bottom. At the top the old content prior the resolution change is seen but never changes. See e.g. here: 
![screenshot](https://cloud.githubusercontent.com/assets/2149767/21372283/7f43fdd8-c716-11e6-8160-7a2824e772cc.png)
.
On the bottom the real screen content is drawn, at the top the old content prior to the resolution change (here: Me running xrandr).

Despite this the mouse is handled correctly. It is bounded inside the real monitor rectangle and can be moved into the upper half containing the old screen content.
The clicks are calculated using correct screen coordinates. Clicking with the mouse at the top of the screen results in a click on the top of the lower, wrongly positioned drawn screen.

When reverting the resolution to the native one everything is aligned properly once again.

This issue is specific for i3, both in the stable version 4.13 and in the current git version with
 commit 8d739b7f. Openbox does not show such behaviour.

**What I expected instead:**

Everything should be aligned correctly.

**Comment by kaueraal** [comment]
A short video showing the behaviour: [screencapture.zip](https://github.com/i3/i3/files/665061/screencapture.zip)

**Comment by stapelberg** [comment]
Unfortunately, the logfile you provided seems incomplete — it does not contain any RandR changes at all. Could you please provide a _complete_ logfile of a _minimum session_, i.e. one in which you only do the necessary changes to trigger this bug and nothing else?

Please also use the default i3 config when capturing the logfile / reproducing the issue.

Can you also list the xrandr commands you’re using, plus the `xrandr -q` output before and after?

**Comment by kaueraal** [comment]
I was able to pin the problem down. It is caused by the compositor compton ran as `compton --backend glx`. Other backends work fine. Since the issue doesn't happen with e.g. openbox, maybe some weird interaction between i3, compton and opengl takes place?

A slimmed down, hopefully more useful logfile: http://logs.i3wm.org/logs/5629805013762048.bz2

**Comment by Airblader** [comment]
Thanks for clearing it up. i3 doesn't do or support compositing. It's also not involved in it at all. Please report  the issue against compton. These types of issues are pretty common.
