### ISSUE TITLE
feature request : show empty workspaces

### ISSUE THREAD

**Issue by eoli3n** [i3/i3#2617]
Is there a way to show all workspaces, even empty ?
bspwm allows it

**Comment by Airblader** [comment]
Empty workspaces don't exist unless they're the active workspace on an output. i3 discards empty workspaces and creates them when needed. 

This is a core part of the i3 concept and we've discussed before that we're not looking to change it.

**Comment by eoli3n** [comment]
https://github.com/Airblader/i3/issues/117

If somebody catch this, and want to try to pull request this :+1:
