### ISSUE TITLE
Feature request: Awesome/Xmonad-style automatic layouts

### ISSUE THREAD

**Issue by SirCmpwn** [i3/i3#2627]
Currently under discussion in sway is the addition of some layouts that automatically arrange windows, inspired by the behavior of some Awesome/Xmonad features. Bringing it up for discussion here.

Details here: https://github.com/SirCmpwn/sway/pull/1024

**Comment by Airblader** [comment]
How would this interact with, for example, layout restoring? Adding such a feature would mean a complete shift of paradigm.

**Comment by SirCmpwn** [comment]
It should fit into the current layout save/restore mechanism, no?

**Comment by Airblader** [comment]
If I specify a specific layout for a workspace but then load a layout file, what wins? The layout file or the predefined layout?

**Comment by SirCmpwn** [comment]
Isn't that already an issue?

**Comment by Airblader** [comment]
We don't have predefined layouts, so why would it be?

**Comment by SirCmpwn** [comment]
The layout file would of course show that the layout for that workspace is an auto layout, and arrange it appropriately. I'm looking at the layout JSON now and not seeing any reason why these layouts couldn't be represented in it.

**Comment by Airblader** [comment]
Layout files don't necessarily represent entire workspaces. You can insert layouts into arbitrary positions in the tree (below workspaces). So the layout file might be in violation with the predefined layout of the workspace.

**Comment by SirCmpwn** [comment]
You can insert auto layouts anywhere in the tree in the sway patches I linked to, and insert not auto layouts anywhere in an auto tree. It behaves just like any other kind of layout.

**Comment by Airblader** [comment]
OK, I misunderstood the feature then. I'd be open to implementing such new layouts. I'd like to avoid extending `workspace_layout` because this is already causing headache.

**Comment by SirCmpwn** [comment]
You mean that you'd like to add new layouts without supporting them in workspace_layout? That sounds like a bad idea imo. To answer your question directly, the layout file wins.

**Comment by Airblader** [comment]
No, the opposite. I *don't* want to touch anything related to the `workspace_layout` feature. Extending the usual container layouts (splitv, splith, tabbed, stacked) with new modes sounds like a neat idea to me.

My feeling is that implementing this is quite tough, but that's something we can only judge when we have a PR for it.

**Comment by mateusduboli** [comment]
This feature needs more :heart:

**Comment by SirCmpwn** [comment]
We're actually probably going to roll this out of sway now that Way Cooler has promised to implement AwesomeWM compatability.

**Comment by mateusduboli** [comment]
What do you mean about "compatibility", could you point me out to the ticket of the discussion?

**Comment by SirCmpwn** [comment]
http://way-cooler.org/blog/2017/12/24/way-cooler-2017.html

https://github.com/way-cooler/way-cooler/issues?q=is%3Aopen+is%3Aissue+label%3AAwesome

**Comment by mateusduboli** [comment]
Nice, thanks!
Shouldn't this be closed as a WONTFIX then?

**Comment by SirCmpwn** [comment]
Yeah probably
