### ISSUE TITLE
Feature request: bar { mouse_scroll_workspaces [yes|no]; }

### ISSUE THREAD

**Issue by SirCmpwn** [i3/i3#2630]
https://github.com/SirCmpwn/sway/pull/1041

**Comment by Airblader** [comment]
My position is exactly what @acrisci said: this already works in i3 the way he described it, so I see no reason to add such a directive.

**Comment by MachFour** [comment]
He also said that having this directive is much more semantic and easier to find (in the docs presumably).

As it is, specifying
```
bar {
   bindsym button4 nop
   bindsym button5 nop
}
```
prevents all scroll-wheel operation on the bar, unless I'm mistaken.

But one might want to maintain the scrolling operation on other parts of the bar. For example, I can scroll on my volume icon in the system tray to change the volume, which is very useful.

**Comment by Airblader** [comment]
The `bar { bindsym }` only affects the workspace icons, not the status blocks or tray icons.

**Comment by Airblader** [comment]
I'm going to close this now for the reasons that have been outlined. There's not enough benefit in adding a redundant directive.
