### ISSUE TITLE
Migrate all tools to draw_util

### ISSUE THREAD

**Issue by Airblader** [i3/i3#2642]
We should switch all tools to use `libi3/draw_util.c` so we have all drawing abstracted.

- [x] i3-config-wizard
- [x] i3-input
- [x] i3-nagbar
- [x] placeholder windows

i3 4.13

**Comment by mihaicmn** [comment]
@Airblader are you planning to implement this enhancement? Otherwise I would be glad to work on it.

**Comment by Airblader** [comment]
@mihaicmn Go ahead! :-) But I'd propose doing one PR for each of the bullet points above separately.

**Comment by Airblader** [comment]
Closing as all PRs have been merged.

@mihaicmn Thanks!
