### ISSUE TITLE
Allow dragging tiled windows with the mouse.

### ISSUE THREAD

**Issue by Airblader** [i3/i3#2643]
As suggested by @MForster in #2178:

> A container can be dragged by the title bar to one of the four sides of
another container. That container will then be split either horizontally
or vertically.

The PR there has open issues and has thus been closed until somebody is willing to continue working on it.

**Comment by acrisci** [comment]
I'm going to do my best to continue this work in #2653

**Comment by Airblader** [comment]
#2653 has now been abandoned. Anyone else feel free to pick up on @acrisci's continuation.

**Comment by azadi** [comment]
I have gone through the code but I can't seem to find if there is a way to disable this feature short of compiling and removing this myself. Would someone be kind enough to share if they have found something on how to disable this? Thanks!

I realize this is an important feature for some people but I seem to be dragging the windows when clicking on them and it's affecting my workflow.

```
i3 --version
i3 version 4.21 (2022-09-21) © 2009 Michael Stapelberg and contributors
```

**Comment by Airblader** [comment]
We will release a bugfix release very soon that will add a config switch to disable this.

**Comment by azadi** [comment]
> We will release a bugfix release very soon that will add a config switch to disable this.

Very much appreciate the quick reply and support for disabling this. Thank you! I realize it's an important feature but I guess I am too used to not dragging windows anymore and hence. 

Many thanks.

**Comment by joker234** [comment]
> > We will release a bugfix release very soon that will add a config switch to disable this.
> 
> Very much appreciate the quick reply and support for disabling this. Thank you! I realize it's an important feature but I guess I am too used to not dragging windows anymore and hence.
> 
> Many thanks.

I would really like that, too. Had to downgrade i3, because my workflow included clicking on the window titles and I moved them in 90% of the time :see_no_evil:

**Comment by stapelberg** [comment]
i3 v4.21.1 was released a week ago with the fixes: https://i3wm.org/downloads/RELEASE-NOTES-4.21.1.txt

**Comment by joker234** [comment]
> i3 v4.21.1 was released a week ago with the fixes: https://i3wm.org/downloads/RELEASE-NOTES-4.21.1.txt

Thanks for the hint. I only checked the Debian archives where it [doesn't seem to be released yet](https://tracker.debian.org/pkg/i3-wm).

**Comment by stapelberg** [comment]
Yeah, I’m assuming @sur5r hasn’t had a chance to upload the bugfix release to Debian yet.
