### ISSUE TITLE
[Enhancement] Make config-reload recognize bar status_command change

### ISSUE THREAD

**Issue by jolange** [i3/i3#2651]
Currently (4.13), a reload of the config does not re-evaluate the `status_command` of a `bar` block. If you change it, you have to restart i3 to take effect. I think the `status_command` should be checked for a change at a reload. This would also be in line with the discussion in #1446.

**Comment by acrisci** [comment]
I agree with this.

The `reload` command is not doing what it says it's doing in this case because it is not applying the new settings.

**Comment by Airblader** [comment]
I agree, but we shouldn't try to detect a change. We should kill and restart the status command everytime the config is reloaded.

**Comment by jolange** [comment]
Agreed, I also thought about that already, because the configuration of the status command can also have changed.

**Comment by jolange** [comment]
@acrisci are you working on this? Otherwise I'd take a look at it when I find the time.

**Comment by acrisci** [comment]
@jolange go ahead, I'm working on something else
