### ISSUE TITLE
Absolute geometries do not work multi-monitor setup.

### ISSUE THREAD

**Issue by woodruffw** [i3/i3#2661]
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08) (pid 1597)o abort…)
Loaded i3 config: /home/william/.config/i3/config (Last modified: Thu 26 Jan 2017 12:24:14 AM EST, 143250 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5737350726418432.bz2

**What I did:**

Ran `xterm -title floaterm -geometry "+730+1500"`. `floaterm` is a title I define in i3's configuration for a floating borderless terminal:

```
for_window [title="floaterm"] floating enable, border none
```

**What I saw:**

A floating borderless `xterm` appears at `+2353+743`, or at another proportionally similar position on whichever monitor has the mouse on it. If the mouse is one the monitor that should contain the window, the `xterm` appears in the correct place.

**What I expected instead:**

A floating borderless `xterm` at "+730+1500", regardless of where the mouse is. Using `xdotool windowmove 730 1500` moves the `xterm` to its expected position.

For reference, my `xrandr --listactivemonitors`:

```
 0: +*DVI-0 1680/430x1050/270+1080+0  DVI-0
 1: +DisplayPort-1 1080/475x1920/267+0+0  DisplayPort-1
 2: +HDMI-0 1920/476x1080/268+2760+0  HDMI-0
```

Visualized with `arandr`:

![](https://camo.githubusercontent.com/667249b131fe4c0cc1c74ba5d576dfeaaeb83c65/68747470733a2f2f73722e68742f724e5f612e706e67)

`i3-msg -t get_outputs | json_pp`:

```
[
   {
      "active" : true,
      "current_workspace" : "1B",
      "primary" : true,
      "name" : "DVI-0",
      "rect" : {
         "y" : 0,
         "x" : 1080,
         "width" : 1680,
         "height" : 1050
      }
   },
   {
      "rect" : {
         "x" : 0,
         "y" : 0,
         "height" : 1920,
         "width" : 4680
      },
      "name" : "xroot-0",
      "active" : false,
      "current_workspace" : null,
      "primary" : false
   },
   {
      "active" : false,
      "primary" : false,
      "current_workspace" : null,
      "name" : "DisplayPort-0",
      "rect" : {
         "height" : 0,
         "width" : 0,
         "x" : 0,
         "y" : 0
      }
   },
   {
      "name" : "DisplayPort-1",
      "rect" : {
         "width" : 1080,
         "height" : 1920,
         "y" : 0,
         "x" : 0
      },
      "active" : true,
      "primary" : false,
      "current_workspace" : "1A"
   },
   {
      "rect" : {
         "height" : 1080,
         "width" : 1920,
         "x" : 2760,
         "y" : 0
      },
      "name" : "HDMI-0",
      "current_workspace" : "1C",
      "primary" : false,
      "active" : true
   }
]
```

I submitted PRs to [mpv](https://github.com/mpv-player/mpv/issues/4070) and [feh](https://github.com/derf/feh/pull/275) earlier thinking that it was an application-specific problem, but the fact that I can replicate it with `xterm` and `urxvt` suggests that it's a problem with the way i3 handles custom positioning of floating windows in general.

**Comment by woodruffw** [comment]
I was able to replicate this bug in 4.11 as well:

```
Binary i3 version:  4.11 (2015-09-30, branch "4.11") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.11 (2015-09-30, branch "4.11") (pid 1597)
Loaded i3 config: /home/william/.config/i3/config (Last modified: Thu 26 Jan 2017 12:24:14 AM EST, 151350 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

**Comment by woodruffw** [comment]
Went through the logs a bit, the incorrect geometry appears for the first time here:

```
01/27/2017 04:14:28 PM - render.c:render_root:283 - floating child at (2353,743) with 486 x 318
01/27/2017 04:14:28 PM - render.c:render_con:49 - Rendering node 0x55a9d6ee1c60 / (null) / layout 6 / children 1
```

**Comment by woodruffw** [comment]
This looks like it:

```
01/27/2017 04:14:28 PM - floating.c:floating_enable:261 - This floating window is on the wrong output, fixing coordinates (currently (730, 1500))
01/27/2017 04:14:28 PM - floating.c:floating_fix_coordinates:874 - Fixing coordinates of floating window 0x55a9d6ee1c60 (rect (730, 1500), 490 x 338)
01/27/2017 04:14:28 PM - floating.c:floating_fix_coordinates:876 - old_rect = (0, 0), 1080 x 1920
01/27/2017 04:14:28 PM - floating.c:floating_fix_coordinates:878 - new_rect = (1080, 0), 1680 x 1050
01/27/2017 04:14:28 PM - floating.c:floating_fix_coordinates:887 - rel_x = 975, rel_y = 1669, fraction_x = 0.902778, fraction_y = 0.869271, output->w = 1080, output->h = 1920
01/27/2017 04:14:28 PM - floating.c:floating_fix_coordinates:891 - Resulting coordinates: x = 2351, y = 743
01/27/2017 04:14:28 PM - floating.c:floating_enable:273 - Floating rect: (2351, 743) with 490 x 338
01/27/2017 04:14:28 PM - floating.c:floating_enable:281 - Corrected y = 725 (deco_height = 18)
```

**Comment by woodruffw** [comment]
The faulty code is this:

```C
/* Sanity check: Are the coordinates on the appropriate output? If not, we
 * need to change them */
Output *current_output = get_output_containing(nc->rect.x +
                                                   (nc->rect.width / 2),
                                               nc->rect.y + (nc->rect.height / 2));

Con *correct_output = con_get_output(ws);
if (!current_output || current_output->con != correct_output) {
    DLOG("This floating window is on the wrong output, fixing coordinates (currently (%d, %d))\n",
         nc->rect.x, nc->rect.y);

    /* If moving from one output to another, keep the relative position
     * consistent (e.g. a centered dialog will remain centered). */
    if (current_output)
        floating_fix_coordinates(nc, &current_output->con->rect, &correct_output->rect);
    else {
        nc->rect.x = correct_output->rect.x;
        nc->rect.y = correct_output->rect.y;
    }
}
```

Looks like it was introduced in 247e11583 as a fix for #452, probably on the assumption that different i3 outputs are actually different X11 screens.

**Comment by Airblader** [comment]
Sorry, I don't understand why you think this is faulty. `+730+1500` is outside of any active output area. Yes, it's on the X screen due to DisplayPort-1, but it's in the middle of nowhere, uncovered by any active output. Thus i3 repositions the window. Where's the incorrect behavior?

**Comment by Airblader** [comment]
Ah, I misread the output of `xrandr --listactivemonitors`. `+730+1500` is actually on DisplayPort-1. I'll have to take another look.

**Comment by woodruffw** [comment]
> Ah, I misread the output of xrandr --listactivemonitors. +730+1500 is actually on DisplayPort-1.

Yep, hence the expectation that it appears there. I would agree that the current behavior is correct if the window wasn't covered by any active whatsoever, but in this case there is one (it's just not the one with the mouse on it :slightly_smiling_face:)

**Comment by woodruffw** [comment]
Just built a local copy with those lines removed -- the floating window's geometry gets applied correctly.

**Comment by Airblader** [comment]
Admittedly this is tricky, but I do believe the behavior is correct in the following way: the window first opens as tiling and thus its geometry is ignored and i3 places it on the current workspace. `for_window` directives are only applied after all of this and once this happens, i3 floats the window and detects that the geometry is off.

Now, admittedly, this situation could be handled differently. Instead of fixing the coordinates i3 could move the window to the output its geometry would put it on. However, this would then cause trouble in other situations (image moving the window to another output before floating it – it would now snap back to the previous output, which is counter-intuitive).

So I'm not really sure we should change this behavior and since i3 doesn't know intent, it can't differentiate between these situations. A »user-side« fix, assuming you open that terminal always with these coordinates, would be to not use `-geometry` when running the terminal, but instead put

````
for_window [title="floaterm"] floating enable, border none, move position 730 1500
````

in your config.

**Comment by woodruffw** [comment]
My actual use case is a floating `mpv` or `feh` window, placed in the corner of my screen for album art (as part of a larger program). I could apply a user-side fix like that, but I'd like the program's behavior to be as generic as possible across window managers - so I provide a `geometry` configuration option that takes an X11-style geometry string.



> (image moving the window to another output before floating it – it would now snap back to the previous output, which is counter-intuitive).

That would indeed be counter-intuitive, but I'd argue that not respecting `-geometry` is just as (if not more) counter-intuitive. This is just anecdotal, but I opened two PRs to projects before even *thinking* that the WM might be responsible for the underlying problem, since it's such a common X11 operation.



> So I'm not really sure we should change this behavior and since i3 doesn't know intent, it can't differentiate between these situations.

It's true that you can't know intent with 100% certainty, but `WM_NORMAL_HINTS` containing an absolute position is a pretty good hint at what the user wants. The current behavior *does* make sense in certain circumstances, but I don't think it makes sense as a general rule. If anything, it should be configurable as an option on a `for_window` directive (mutual with `floating`, of course).

**Comment by woodruffw** [comment]
This is just me thinking out loud, but possibly `floating_relative`?

**Comment by Airblader** [comment]
> I'd argue that not respecting -geometry is just as (if not more) counter-intuitive.

I'd disagree. :-) Managing geometry of windows (that is, position and size) is the very job of a window manager and the specifications give it full control and decision over it. A window can give *hints* as to where it wants to be, but the window manager disrespecting this hint is perfectly acceptable. In fact, that's what a tiling window manager does for every tiled window.

On the other hand, if I float a window and it seemingly just disappears because it jumps to a random output, I'd go and open an issue right away. Moving a window far away without the user requesting it in some way is a pretty strong intervention and almost certainly guaranteed to cause confusion.

> a pretty good hint at what the user wants

Actually I would say that in the vast majority of cases the user didn't actually have a say in setting those values. There's only very few cases where a user actually requests a very specific geometry (cases such as yours).

> If anything, it should be configurable as an option

I don't like that very much. We don't want to add options for every little detail of every decision i3 has to take because this increases mental complexity. Of course that's a fuzzy line, but IMHO in this case it's quite clear that we shouldn't offer this.

> I could apply a user-side fix like that, but I'd like the program's behavior to be as generic as possible across window managers

Note that you can actually keep the `-geometry` argument to have it keep working with other window managers. As long as you add the command to the `for_window` directive you should be good to go. I don't claim it to be a really pretty solution, but I'm not yet convinced of changing the behavior (as you can see above).

Looking at this from an entirely different perspecitve: I do wonder what the pros and cons would be for using the initial geometry to determine the output a window should be opened on in the first place. On first thought this makes a lot of sense to me, but it should be looked at carefully. We have some logic to this regard for dock clients and fullscreened windows already.

**Comment by woodruffw** [comment]
> Managing geometry of windows (that is, position and size) is the very job of a window manager and the specifications give it full control and decision over it. A window can give hints as to where it wants to be, but the window manager disrespecting this hint is perfectly acceptable. In fact, that's what a tiling window manager does for every tiled window.

On reflection, you're absolutely right here. Having spent about an hour now running my patched version, spawning all floating windows on their absolute coordinates is a much worse user experience. My usage is edge case compared to the nicety of having floating windows appear under your cursor.

> I don't like that very much. We don't want to add options for every little detail of every decision i3 has to take because this increases mental complexity. Of course that's a fuzzy line, but IMHO in this case it's quite clear that we shouldn't offer this.

That's fair. I wish `i3` had some way of adding directives at run-time, but I guess that not going to happen any time soon ;)

> Note that you can actually keep the -geometry argument to have it keep working with other window managers. As long as you add the command to the for_window directive you should be good to go. I don't claim it to be a really pretty solution, but I'm not yet convinced of changing the behavior (as you can see above).

Yeah, I suppose that this is what I'll end up doing. `mpv` and `feh` both have `--title` flags, so those should make my life easier.

Thanks for reviewing my "bug" here. I appreciate the work the i3 team has done - it's a real pleasure to use.

**Comment by Airblader** [comment]
Not so fast. :-) I still think it might be worth considering using the initial geometry to determine the workspace to put a window on.

**Comment by woodruffw** [comment]
> I still think it might be worth considering using the initial geometry to determine the workspace to put a window on.

What would be the best way to go about determining intent, like you said earlier? The majority of floating windows should probably be re-proportioned onto the active workspace, but a few need to be identified in such a way that they get moved correctly.

**Comment by Airblader** [comment]
> What would be the best way to go about determining intent, like you said earlier?

There's no intent to determine in this case. The hints are optional. In general I'd expect windows not to set the positional hints if they don't care about their position (note that this is speculation and something we'd have to look into); if, however, they specify the geometry, why not use that information to place the window on the output it wants to be on (even if we're not gonna respect potentially set size hints)?

The patch to test this should be fairly simple to write. In `src/manage.c` we have a few code paths for `nc == NULL` that we use to determine the target workspace. We'd just have to add another case along the lines of »if the hints specify a position, use the active workspace on the output containing that position«.

**Comment by Airblader** [comment]
The patch would be something like this. Note that I haven't tested this *at all*, so running this might do anythin up to and including crashing i3 and your X.

````
diff --git a/src/manage.c b/src/manage.c
index 86a361c3..01740dc3 100644
--- a/src/manage.c
+++ b/src/manage.c
@@ -296,6 +296,18 @@ void manage_window(xcb_window_t window, xcb_get_window_attributes_cookie_t cooki
                 nc = tree_open_con(nc, cwindow);
             else
                 nc = tree_open_con(nc->parent, cwindow);
+        } else if (wm_size_hints.flags & XCB_ICCCM_SIZE_HINT_US_POSITION || wm_size_hints.flags & XCB_ICCCM_SIZE_HINT_P_POSITION) {
+            Output *output = get_output_containing(wm_size_hints.x, wm_size_hints.y);
+            if (output != NULL) {
+                nc = TAILQ_FIRST(&(output_get_content(output->con)->focus_head));
+
+                if (nc != NULL && nc->type == CT_WORKSPACE) {
+                    nc = tree_open_con(nc, cwindow);
+                } else {
+                    ELOG("This shouldn't happen.\n");
+                    nc = NULL;
+                }
+            }
         } else {
             /* If not, insert it at the currently focused position */
             if (focused->type == CT_CON && con_accepts_window(focused)) {
````

**Comment by woodruffw** [comment]
> There's no intent to determine in this case. The hints are optional. In general I'd expect windows not to set the positional hints if they don't care about their position (note that this is speculation and something we'd have to look into); if, however, they specify the geometry, why not use that information to place the window on the output it wants to be on (even if we're not gonna respect potentially set size hints)?

That makes sense. A quick test confirms that, at least for `xterm` and `mpv`.

I'll try the patch out.

**Comment by woodruffw** [comment]
The patch works - windows without position fields in their size hints get relocated, while windows with position fields end up in the correct output.

Would there be any problems with getting this added in the next release?

**Comment by Airblader** [comment]
> The patch works

Cool. :-)

> Would there be any problems with getting this added in the next release?

No, there's no direct reason against it. I'd appreciate if you kept running the patch to gather more feedback. I will have to rewrite the patch, though, and make it a little cleaner.

**Comment by woodruffw** [comment]
> I'd appreciate if you kept running the patch to gather more feedback

Sure, no problem!

**Comment by woodruffw** [comment]
Noticed one outlier - the Firefox certificate viewer decides to position itself on output 0. I'll supply some more details once I'm back on the machine that's running the patched i3.

**Comment by woodruffw** [comment]
Here's the `xprop` dump from Firefox's cert viewer: https://p.sicp.me/fz7HN

`WM_NORMAL_HINTS` doesn't contain a location request, but the `_NET_WM_WINDOW_TYPE` is `_NET_WM_WINDOW_TYPE_DIALOG`. Does i3 treat dialogs different from windows that have to be explicitly floated?

**Comment by Airblader** [comment]
> WM_NORMAL_HINTS doesn't contain a location request,

I think `xprop` never prints the positional hint in `WM_NORMAL_HINTS`, so that may just be misleading. I might be wrong, though.

> Does i3 treat dialogs different from windows that have to be explicitly floated?

Well… yes and no. It really does the same (float it), it just does it a little earlier because it detects it on its own.

**Comment by Airblader** [comment]
Just to clarify, without this patch but running the git version the window doesn't get placed on output 0?

**Comment by woodruffw** [comment]
> Edit: I am wrong, it does display it. But for example in urxvt -geometry "+300+300" it doesn't show up either.

That's weird, I can see the position hints for `xterm` and `urxvt` in `xprop`: https://p.sicp.me/mWpRj, https://p.sicp.me/qbgGb

The `urxvt` one gets centered on output 0 though, so I'm not sure what's happening there.


> Just to clarify, without this patch but running the git version the window doesn't get placed on output 0?

Yes, from memory. I'll confirm that in a moment.

**Comment by woodruffw** [comment]
I can replicate this with the Firefox download dialog as well, and can provide logs if desired.

**Comment by woodruffw** [comment]
`xprop` from the download dialog: https://p.sicp.me/nWHvp

One other thing that stands out as different between these Firefox dialogs and floating `urxvt`/`xterm` is the `WM_PROTOCOLS` property being set:

```
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
```

`_NET_WM_SYNC_REQUEST` in particular might have an effect, based on the [EWMH docs](https://specifications.freedesktop.org/wm-spec/1.3/ar01s06.html).

**Comment by Airblader** [comment]
> _NET_WM_SYNC_REQUEST in particular might have an effect, based on the EWMH docs.

I don't quite understand what that spec has to do with this situation, but either way, i3 doesn't support this protocol so it doesn't matter. :-)

Dialogs may differ in the fact that they have a leader window set; however, I don't see how my patch changes this. I'll try to reproduce it with the Firefox downloads dialog and see if I can figure it out. If not, I might ask you to run a modified patch with a bit more logging.

**Comment by Airblader** [comment]
Actually I don't have another output handy right now. Could you do a run with this patch and provide the i3 log file afterwards? Please make sure to close other windows and keep the log file small (as described in the debugging docs). :-)

````
diff --git a/src/manage.c b/src/manage.c
index ac2a5ae2..2b2d4642 100644
--- a/src/manage.c
+++ b/src/manage.c
@@ -296,6 +296,21 @@ void manage_window(xcb_window_t window, xcb_get_window_attributes_cookie_t cooki
                 nc = tree_open_con(nc, cwindow);
             else
                 nc = tree_open_con(nc->parent, cwindow);
+        } else if (wm_size_hints.flags & XCB_ICCCM_SIZE_HINT_US_POSITION || wm_size_hints.flags & XCB_ICCCM_SIZE_HINT_P_POSITION) {
+            ELOG("[FOO] Window has size hints set.\n");
+            Output *output = get_output_containing(wm_size_hints.x, wm_size_hints.y);
+            if (output != NULL) {
+                ELOG("[FOO] Found output containing %d / %d\n", wm_size_hints.x, wm_size_hints.y);
+                nc = TAILQ_FIRST(&(output_get_content(output->con)->focus_head));
+
+                if (nc != NULL && nc->type == CT_WORKSPACE) {
+                    ELOG("[FOO] Using workspace %s\n", nc->name);
+                    nc = tree_open_con(nc, cwindow);
+                } else {
+                    ELOG("This shouldn't happen.\n");
+                    nc = NULL;
+                }
+            }
         } else {
             /* If not, insert it at the currently focused position */
             if (focused->type == CT_CON && con_accepts_window(focused)) {
````

**Comment by woodruffw** [comment]
Sure! I'll have the logs in a bit.

**Comment by Airblader** [comment]
On a side note, I randomly came across the fact that GTK deprecated geometry handling. Looks like quite a lot of GTK applications have started removing the `--geometry` flag as a result.

https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-parse-geometry

**Comment by woodruffw** [comment]
Here's the log: https://p.sicp.me/bnGAG

I opened two (relevant) windows - a floating `xterm` and a Firefox certificate dialog. The `xterm` is first, and the size hints get detected correctly:

```
02/04/2017 06:25:59 PM - ERROR: [FOO] Window has size hints set.
02/04/2017 06:25:59 PM - randr.c:get_output_containing:96 - comparing x=300 y=300 with x=1080 and y=0 width 1680 height 1050
02/04/2017 06:25:59 PM - randr.c:get_output_containing:96 - comparing x=300 y=300 with x=0 and y=0 width 1080 height 1920
02/04/2017 06:25:59 PM - ERROR: [FOO] Found output containing 300 / 300
02/04/2017 06:25:59 PM - ERROR: [FOO] Using workspace 1A
```

(1A is correct.)

The cert viewer comes next, and gets incorrectly detected as having a position hint at `+0+0`:

```
02/04/2017 06:26:10 PM - ERROR: [FOO] Window has size hints set.
02/04/2017 06:26:10 PM - randr.c:get_output_containing:96 - comparing x=0 y=0 with x=1080 and y=0 width 1680 height 1050
02/04/2017 06:26:10 PM - randr.c:get_output_containing:96 - comparing x=0 y=0 with x=0 and y=0 width 1080 height 1920
02/04/2017 06:26:10 PM - ERROR: [FOO] Found output containing 0 / 0
02/04/2017 06:26:10 PM - ERROR: [FOO] Using workspace 1A
```

(1A is not correct, since the Firefox main window is on 1C.)

My guess then is that `wm_size_hints.flags` is getting incorrectly populated somewhere, since `xprop` confirms that the dialog has no position hints (only minimum and base size hints).

**Comment by woodruffw** [comment]
> On a side note, I randomly came across the fact that GTK deprecated geometry handling. Looks like quite a lot of GTK applications have started removing the --geometry flag as a result.

Probably makes sense for them, since the parsed geometry string is a very X11-esque concept and they're targetting multiple display systems. It looks like they haven't deprecated any of the other window moving/resizing/hinting methods, so my guess is that they just want to nudge users towards letting the windower/DE/WM figure it out.

**Comment by woodruffw** [comment]
Here's an `xwininfo` comparison:

Floating `xterm` placed at `+300+300`:

```
xwininfo: Window id: 0x3c00024 "floaterm"

  Absolute upper-left X:  302
  Absolute upper-left Y:  300
  Relative upper-left X:  0
  Relative upper-left Y:  0
  Width: 484
  Height: 316
  Depth: 24
  Visual: 0x21
  Visual Class: TrueColor
  Border width: 1
  Class: InputOutput
  Colormap: 0x20 (installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +302+300  -3892+300  -3892-1302  +302-1302
  -geometry 80x24+302+300
```

Cert viewer:

```
xwininfo: Window id: 0x3200108 "Certificate Viewer: “xcb.freedesktop.org”"

  Absolute upper-left X:  166
  Absolute upper-left Y:  605
  Relative upper-left X:  2
  Relative upper-left Y:  0
  Width: 750
  Height: 724
  Depth: 24
  Visual: 0x318
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x3200002 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +166+605  -3764+605  -3764-591  +166-591
  -geometry 750x724+164+605
```

Nothing really stands out here either, except that the `xterm` is borderless and still has `Border width: 1` and the cert viewer *has* a border but also has `Border width: 0`. That's a little strange, but probably not the root issue here.

**Comment by Airblader** [comment]
So I did some digging through the ICCCM and xprop and I *think* that the spec is either unclear or doesn't intend for applications to provide x/y values for program-specified positions (which sounds insane because why is a program not allowed to specify its desired location?).

So my current assumption is that (unless Firefox simply violates the spec) we just need to exchange

````
} else if (wm_size_hints.flags & XCB_ICCCM_SIZE_HINT_US_POSITION || wm_size_hints.flags & XCB_ICCCM_SIZE_HINT_P_POSITION) {
````

for

````
} else if (wm_size_hints.flags & XCB_ICCCM_SIZE_HINT_US_POSITION) {
````

… and given the misunderstanding (although I'm not sure who is misunderstanding something here…) we'd have to fix this for all code paths relying on the x/y values in the hints at the moment. I think I'll bring ask about this on the Xorg mailing list to be sure.

**Comment by Airblader** [comment]
Uhm, sorry, I forgot to add: can you see what happens if you change the patch accordingly?

**Comment by Airblader** [comment]
Although this doesn't explain why the xprop output of the dialog doesn't list user-specified *nor* program-specified location.

**Comment by woodruffw** [comment]
With the second half of the condition removed (program specified position), the patch works. Both the positioned `xterm` and the cert viewer show up where expected.

> Although this doesn't explain why the xprop output of the dialog doesn't list user-specified nor program-specified location.

Yeah, that's an utter mystery to me.

**Comment by Airblader** [comment]
Either way, I think we should give up on this idea: according to `man XSizeHints` the x/y values are obsolete (read: not just deprecated) and only exist for compatibility anymore. We certainly shouldn't start using something even Xorg-osaurus dropped already.

Oddly, I originally talked about the initial geometry but in my patch just went straight to using the hints. Mea culpa, I guess. So we could ask the same for the initial geometry itself. The part that worries me is that this isn't some optional case where we get informational hints – the geometry is *always* set and we're back at the no-intention problem. So really, this would be a fundamental change of how i3 places windows during mapping.

Worth a shot? Perhaps. But after a couple of years in the X world my confidence in all Xorg apps providing a sensible geometry is… well… low. You can do a quick test by watching the output of

````
i3-dump-log -f | grep -i "initial geometry"
````

while opening a few different applications while being active on the second output (the one not containing the position x=0/y=0). Anytime you see a "0, 0" as the first two numbers that'd be an application we'd be misplacing.

**Comment by woodruffw** [comment]
Maybe I'm not understanding, but what's wrong with the solution you've provided above? It seems to cover both cases correctly, at least in every situation I've tested. I understand that it won't work for program-specified size hints, but my impression is that i3 is less concerned with those anyways.

> Either way, I think we should give up on this idea: according to man XSizeHints the x/y values are obsolete (read: not just deprecated) and only exist for compatibility anymore. We certainly shouldn't start using something even Xorg-osaurus dropped already.

Obsolete basically means nothing in XOrg land, since X11 is essentially a frozen specification. The size hints also get used elsewhere in `manage.c` and other files, so adding them here wouldn't be breaking with current practices.

**Comment by Airblader** [comment]
> Obsolete basically means nothing in XOrg land, since X11 is essentially a frozen specification.

Yes, it does – »obsolete« isn't the same as »deprecated«. The latter would mean »keep using it, but it will be removed in the future«, but the former means it already shouldn't be used anymore; it already *is* considered removed, it's just in there to ensure compatibility.

In particular it means we can run into clients which set the user-position flag but not x/y values. This would break the window behavior for the user, but the application could rightfully claim that they're not breaking any spec.

Given that we're trying to solve a problem for which we have a viable alternative solution (just one that isn't WM-agnostic) my current conclusion is to rather not make this change.

> The size hints also get used elsewhere […]

The *size* values, yes. But those aren't marked obsolete. Only the x/y values are marked obsolete. :-)

**Comment by Airblader** [comment]
> In particular it means we can run into clients which set the user-position flag but not x/y values.

And just to prove it, not even two minutes of using Google brought me to http://profs.etsmtl.ca/mmcguffin/codegallery/mandelbrot.c:

````
   /* Use USPosition | USSize instead of PPosition | PSize to force hints. */
   /* size_hints->flags = PPosition | PSize | PMinSize; */
   size_hints->flags = PMinSize;
   /* In R4 and later, the x, y, width, and height members of XSizeHints should not be set. */
   size_hints->min_width = minWidth;
   size_hints->min_height = minHeight;
   if (isFullScreenAndBorderless)
      size_hints->flags |= (USPosition | USSize);
````

**Comment by woodruffw** [comment]
> In particular it means we can run into clients which set the user-position flag but not x/y values. This would break the window behavior for the user, but the application could rightfully claim that they're not breaking any spec.

That makes sense, although I think the breakage here can be reconciled: we can check if the flag is set, then do some centering logic similar to the unspecified-geometry case if x/y aren't actually set. I can understand if you don't want to include that upstream, though.

Thanks for reviewing this so thoroughly; I'm going to keep this in a fork for my own use :slightly_smiling_face:

**Comment by woodruffw** [comment]
Just for reference, this is the final patch I went with. It covers both user and program-specified positions without breaking windows that set the flags without setting x/y:

```diff
diff --git a/src/manage.c b/src/manage.c
index 86a361c3..c378f7bb 100644
--- a/src/manage.c
+++ b/src/manage.c
@@ -296,6 +296,23 @@ void manage_window(xcb_window_t window, xcb_get_window_attributes_cookie_t cooki
                 nc = tree_open_con(nc, cwindow);
             else
                 nc = tree_open_con(nc->parent, cwindow);
+        } else if ((wm_size_hints.flags & XCB_ICCCM_SIZE_HINT_US_POSITION ||
+                    wm_size_hints.flags & XCB_ICCCM_SIZE_HINT_P_POSITION) &&
+                    wm_size_hints.x > 0 && wm_size_hints.y > 0) {
+            ELOG("[FOO] Window has nonzero size hints set.\n");
+            Output *output = get_output_containing(wm_size_hints.x, wm_size_hints.y);
+            if (output != NULL) {
+                ELOG("[FOO] Found output containing %d / %d\n", wm_size_hints.x, wm_size_hints.y);
+                nc = TAILQ_FIRST(&(output_get_content(output->con)->focus_head));
+
+                if (nc != NULL && nc->type == CT_WORKSPACE) {
+                    ELOG("[FOO] Using workspace %s\n", nc->name);
+                    nc = tree_open_con(nc, cwindow);
+                } else {
+                    ELOG("This shouldn't happen.\n");
+                    nc = NULL;
+                }
+            }
         } else {
             /* If not, insert it at the currently focused position */
             if (focused->type == CT_CON && con_accepts_window(focused)) {
```

**Comment by Airblader** [comment]
> I can understand if you don't want to include that upstream, though.

Yes, I think all things considered we should stay away from it. Keeping it as a local patch should be fine if you prefer it over `for_window` directives. Thanks for posting the final version of what you'll use as well. :-)

**Comment by woodruffw** [comment]
> Thanks for posting the final version of what you'll use as well. :-)

No problem. Thanks again for reviewing, and making `i3` such a nice program to use!
