### ISSUE TITLE
[Enhancement] Improve documentation for workspace commands

### ISSUE THREAD

**Issue by xkpd3** [i3/i3#2663]
Hello,

I would love if default names for workspaces could be set.
To understand what I mean, let's assume the following config:

```
set workspace default name  "1:[1]"
set workspace default name  "2:[2]"
set workspace default name  "3:[3]"
bindsym $mod+1 workspace number 1
bindsym $mod+2 workspace number 2
bindsym $mod+3 workspace number 3
bindsym $mod+Shift+exclam move container to workspace number 1
bindsym $mod+Shift+quotedbl move container to workspace number 2
bindsym $mod+Shift+section move container to workspace number 3
```

The first three lines are not implemented. I'm switching to workspaces using the "workspace number", because I rename workspaces while working.

When a new workspace is created, it is created with the number as name.

It would be nice to be able to set a default name, which is used when a workspace is created.

I worked around this with a [bunch of scripts](https://github.com/xkpd3/xkpd3conf-i3/tree/master/bin). It works okay, but I wonder if this would be something other people also would like to see in the core.

What do you think?

Best Regards,
Stefan

**Comment by fantomas911** [comment]
You can do something like this:
`bindsym $mod+1 workspace myDevelopWorkSpace
bindsym $mod+Shift+exclam move container to myDevelopWorkSpace`

**Comment by xkpd3** [comment]
Hi @fantomas911,

As I wrote above, I rename workspaces **while working**. This is why I'm naming my workspaces with the special `<WSNumber>:<WSName>` string, because this enables me to use
`bindsym $mod+1 workspace number <WSNumber>`
`bindsym $mod+Shift+exclam move container to workspace <WSNumber>`
to switch or move to a workspace regardless of `<WSName>`.

However, if I use "workspace number", I can not set a default workspace name. THIS is what I want.
If I do not use "workspace <WSName>" then I have a much bigger problem with not matching key bindings after the rename.

**Comment by Airblader** [comment]
I think you can just use

````
set $ws1_default "1:Foo"
set $ws2_default "1:Bar"
bindsym $mod+1 workspace number $ws1_default
bindsym $mod+2 workspace number $ws2_default
````

This should both name it correctly initially and deal with renames, I think.

**Comment by xkpd3** [comment]
@Airblader I'll try that. I did not know that `workspace number "1:Foo"` is a valid statement. I'll report back this evening.

**Comment by xkpd3** [comment]
@Airblader, you're my hero! This works perfectly fine!

**Comment by xkpd3** [comment]
Now, after I know how it works - I also understand [chapter 6.7.1](http://i3wm.org/docs/userguide.html#_named_workspaces).

I think the documentation could be clearer, but I'm not yet sure how to improve it. I think once the string "1:Foo" is used, the 1 is treated as WS number and the Text is just the display text for this number.

So I see two different methods which could be described separately.
- Workspace identification by text
In this "mode" the workspace has a text and is displayed in the order of creation. Here it makes sense to bind `workspace Foo` and `move container to workspace Foo`. The workspace names are fixed and renaming them on-the-fly doesn't make much sense.
- Workspace identification by number
In this "mode" the workspace is identified by a number and displayed sorted by number. Here it makes sense to bind `workspace 1` and `move container to workspace number 1`. A default text can be applied by adding a description after the number like "1:Foo". In this case, it would still be a numbered workspace, but the text would be displayed. The commands `workspace 1:Foo` and `move container to workspace number 1:Foo` will work. They will also still work when the workspace has been renamed to "1:Bar", as only the number part is used to reference the workspace.

This would probably a better description of how workspace naming works.

What do you think? I can try to put this into the documentation. Maybe as "Usecases" subchapter?

**Comment by Airblader** [comment]
I'm all for improving documentation, but I don't think the userguide is a good place to document »Usecases«. There's way too many of them and it would make the document too cluttered, IMHO. We should document how things behave, but if you want to write something on how to achieve specific things I'd recommend blog articles.

@stapelberg What do you think?

**Comment by stapelberg** [comment]
I agree that more elaborate descriptions of use-cases are better suited for blog articles. Outlining use-cases via examples in the userguide is fine, though. Given that the referenced section already mentions that one can combine names and the “number” command, I’m not sure what else we need to do, though. Maybe move that sentence into a separate paragraph and expand on it a little bit?

**Comment by xkpd3** [comment]
Documentation updated.
