### ISSUE TITLE
Feature request: Ability to hide the tab bar

### ISSUE THREAD

**Issue by kilbith** [i3/i3#2664]
In tabbed mode, the tab bar is redundant since I already have `tint2` listing the windows.

I need to hide this i3 tab bar to the profit of other panel/taskbars.

**Comment by Airblader** [comment]
We've discussed this in the past and decided not to allow this. Did your position on this change, @stapelberg ?

**Comment by stapelberg** [comment]
No change, I still think title bars must be visible in any non-default layout.

**Comment by kilbith** [comment]
Is there an explanation somewhere for this decision ? How does it hurt to have it as an option ?

**Comment by Airblader** [comment]
https://faq.i3wm.org/question/778/why-is-patch-not-merged-and-made-optional/

**Comment by stapelberg** [comment]
The rationale is that hiding the title bars makes it significantly harder to build up a mental model of the layout that is on your screen. I.e., you can no longer distinguish different layouts from each other.

**Comment by amosbird** [comment]
How about adding an option for merging title bar and i3bar?

**Comment by Airblader** [comment]
i3bar is a standalone tool, so that wouldn't work. Plus it's part of the i3bar philosophy to display workspaces, not individual windows.

**Comment by Airblader** [comment]
If you want to disable the titlebars I'd suggest just running your patch locally.

**Comment by blueforesticarus** [comment]
*refusing to accept patches for the ability to turn off a default feature.*

You're clowning.

**Comment by Nadrieril** [comment]
If anyone is interested in patching it themselves, it's very easy:
```patch
diff --git a/src/render.c b/src/render.c
index 478a1cc4..4644005a 100644
--- a/src/render.c
+++ b/src/render.c
@@ -25,10 +25,7 @@ bool has_adjacent_container(Con *con, direction_t direction);
  * Returns the height for the decorations
  */
 int render_deco_height(void) {
-    int deco_height = config.font.height + 4;
-    if (config.font.height & 0x01)
-        ++deco_height;
-    return deco_height;
+    return 0;
 }
 
 /*
```

**Comment by enesaltinkaya** [comment]
How very apple of you.

**Comment by blueforesticarus** [comment]
![Image](https://github.com/user-attachments/assets/48a42f02-d1fe-4a84-bf5c-6938c587727c)
