### ISSUE TITLE
focus not following mouse unless click or crossing window border

### ISSUE THREAD

**Issue by mmlb** [i3/i3#2666]
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08) (pid 24108) abort…)
Loaded i3 config: /home/manny/.config/i3/config (Last modified: Tue 31 Jan 2017 04:24:47 PM EST, 1367 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5654961308303360.bz2

**What I did:**

Open 5 terminals in vertical splits.
The mouse is moved to the left-most terminal, it has focus as expected.
Now I type `exit` to close that terminal.
The mouse is in the same position, over the new left-most terminal.
The right-most terminal has focus, as expected.
I move the mouse around, **while not crossing any terminal/window borders**

**What I saw:**

right-most terminal keeps focus, left-most does not gain it, focus is *not* following the mouse.

**What I expected instead:**

Focus should be on the window to the left.

I have been able to gain focus by either crossing into the 2nd-from-left and back to left-most, or by clicking in the left-most terminal.

**Comment by mmlb** [comment]
looks a lot like #1213

**Comment by Airblader** [comment]
This is the expected behavior. Really that is what "focus follows mouse" means: if the mouse moves from one window to another, focus will follow. In this situation there is no crossing from one window to another. 

In fact we know that quite a few users actually rely on this behavior.

**Comment by mmlb** [comment]
Hmm I thought this might be the case, and I can see how slight mouse movements may bring focus to an unwanted window. Maybe this can be cleared up in the docs, current contents are:

```
4.21. Focus follows mouse
By default, window focus follows your mouse movements. 
```

Which is (IMO) easily interpreted as any mouse movement, not just movement crossing window borders.

Alternatively, it might be nice to have `focus_follows_mouse = something_else` that will change focus on any mouse movement > jitter.

**Comment by Airblader** [comment]
> Maybe this can be cleared up in the docs, current contents are

Feel free to send a PR to clarify it. :-)

**Comment by mankinskin** [comment]
Would it be possible to implement something like focus_on_hover?

**Comment by orestisfl** [comment]
@mankinskin I don't think we will be extending i3's behavior on this aspect. It might be possible to implement this in a wm-agnostic way.

> We are generally happy with the current feature set of i3 and instead focus on maintenance such as stability and fixing bugs. New features will rarely be considered if they require additional configuration and/or commands, or if they add significant complexity (either through the exposed configuration or mental complexity) to the project.

https://github.com/i3/i3/blob/next/.github/CONTRIBUTING.md
