### ISSUE TITLE
enhancement: adopt a formal code of conduct

### ISSUE THREAD

**Issue by stapelberg** [i3/i3#2676]
Currently, i3 core contributors and/or i3’s BDFL (see PR https://github.com/i3/i3/pull/2675 for formalization) tell people when they are out of line within the i3 projects. For examples, see https://github.com/i3/i3status/pull/43, https://github.com/i3/i3status/pull/175, https://github.com/i3/i3/issues/1307 or https://github.com/i3/i3lock/issues/56.

We should make it more clear to people what acceptable behavior within the i3 projects is. To that end, I propose adopting Django’s [Code of Conduct](https://www.djangoproject.com/conduct/), which I like because it lines up with the values that the current core contributors/BDFL uphold, is brief and easy to understand and was written specifically for a project where most interactions happen online (as opposed to an in-person conference).

I intend to move forward with this next weekend.

**Comment by Airblader** [comment]
I like the proposal. Short and on the spot. :-)

**Comment by nmschulte** [comment]
Sorry to derail, but I have a question:  @stapelberg how did you manage to close an issue for i3/i3 from a different repository?

![2017_02_12-14_57_28-1186x726](https://cloud.githubusercontent.com/assets/8540239/22865971/b09b275c-f133-11e6-8eba-777f31ee53cf.png)

**Comment by Airblader** [comment]
The commit message directly refers to the i3 repository via `i3/`, so I assume that if you have the necessary privileges, Github does the magic.

**Comment by stapelberg** [comment]
Just put the full URL of the issue into the commit message. As @Airblader mentioned, GitHub verifies permission and closes the issue accordingly.
