### ISSUE TITLE
Enhancement: Switching tabs/workspaces by scrolling horizontally

### ISSUE THREAD

**Issue by mahkoh** [i3/i3#2677]
I would like i3 to allow me to switch tabs/workspaces by scrolling horizontally. That is, whenever scrolling downwards would switch to the tab/workspace to the right of the current tab/workspace, scrolling rightwards behaves the same way. The same applies to upwards/leftwards.

Chromium recently introduced this feature and by now I'm quite used to scrolling horizontally on my touch-pad to switch tabs.

**Comment by Airblader** [comment]
This should already work by configuring

````
bindsym button4 workspace next_on_output
bindsym button5 workspace prev_on_output
````

Can you confirm?

**Comment by mahkoh** [comment]
Those settings seem to have no effect.

**Comment by Airblader** [comment]
Yeah, sorry, it was incomplete. I meant to say

````
bindsym --whole-window --border button4 workspace next_on_output
bindsym --whole-window --border button5 workspace prev_on_output
````

And if you have NumLock enabled you might have to add `Mod2`:

````
bindsym --whole-window --border Mod2+button4 workspace next_on_output
bindsym --whole-window --border Mod2+button5 workspace prev_on_output
````

**Comment by mahkoh** [comment]
Also: I did not use "tab" as a synonym for "workspace". By "tabs" I meant windows which i3 allows me to scroll though just like workspaces.

**Comment by Airblader** [comment]
Once the scrolling keybind works you can use a script to do whatever focus change you want. I'm not keen on forcing this in i3 since it would require a new config directive for something i3 is already capable of. It's also really tricky to get the concept of left/right/up/down right in terms of windows.

**Comment by mahkoh** [comment]
```
bindsym --whole-window --border button4 workspace next_on_output
bindsym --whole-window --border button5 workspace prev_on_output
```

This does have an effect but not as intended. First of all it does not have an effect on scrolling horizontally. Instead, whenever I scroll vertically (no matter where the cursor is), i3 switches workspaces.

**Comment by Airblader** [comment]
> First of all it does not have an effect on scrolling horizontally.

Because it only binds button 4 and 5, so the vertical scroll buttons. Figure out the buttons for horizontal scrolling and you can bind them the same way.

> no matter where the cursor is

What difference do you expect the location to make?

> i3 switches workspaces

As I said, you can execute any command you want. You explicitly mentioned workspaces, so I used this as an example. You can also execute a script to perform any logic you want. There's also #2587 already which implements what I believe you're asking for as a command, so with #2587 you can bind that command directly.

**Comment by mahkoh** [comment]
>It's also really tricky to get the concept of left/right/up/down right in terms of windows.

I'm not sure what you mean by this. i3 only seems to allow switching windows by scrolling if the container is using the tabbed layout. In this case, when you hover your cursor over the area displaying the tab headers and scroll vertically, i3 switches the visible tab. Since the tabs are organized horizontally, mapping horizontal scrolling to this operation should be much easier.

>What difference do you expect the location to make?

As I described above, the position of the cursor determines whether scrolling causes i3 to switch between workspaces, tabbed windows, or simply passes the event to the underlying window. This is already a feature of i3 but only for vertical scrolling. I want this feature to also work for horizontal scrolling.

**Comment by Airblader** [comment]
OK, I think I (finally) understood you. :-) 

So in terms of window switching you simply expect left/right scrolling to do exactly the same up/down scrolling already does, correct? I think this sounds acceptable and we could implement that.

**Comment by nmschulte** [comment]
> Because it only binds button 4 and 5, so the vertical scroll buttons. Figure out the buttons for horizontal scrolling and you can bind them the same way.

On my mouse, scroll left is `button6` and right is `button8`.

> This is already a feature of i3 but only for vertical scrolling. I want this feature to also work for horizontal scrolling.
The feature doesn't exist as you imagine: there exists the ability to cycle workspaces, but those are one-dimensional.  Containers are multidimensional (vertical, horizontal), and #2587 exists to encapsulate the dimension-agnostic cycling feature, which is *not* yet in i3.

**Comment by Airblader** [comment]
The one part I still don't understand is cycling workspaces. AFAIK scrolling titlebars never switches workspaces. Can you describe exactly the layout in which you scroll the titlebar which changes workspaces? That sounds like it might be more of a bug. The only scrolling switching workspaces happens on the i3bar workspace buttons.

Other than that, enabling the same functionality we have for up/down scrolling also for left/right scrolling sounds OK to me.

**Comment by Airblader** [comment]
A quick patch would look like this. You could perhaps see if it behaves as you expect, but I haven't tested it yet so please be careful:

````
diff --git a/src/click.c b/src/click.c
index 913741b4..94cab255 100644
--- a/src/click.c
+++ b/src/click.c
@@ -229,7 +229,9 @@ static int route_click(Con *con, xcb_button_press_event_t *event, const bool mod
     if (in_stacked &&
         dest == CLICK_DECORATION &&
         (event->detail == XCB_BUTTON_INDEX_4 ||
-         event->detail == XCB_BUTTON_INDEX_5)) {
+         event->detail == XCB_BUTTON_INDEX_5 ||
+         event->detail == 6 ||
+         event->detail == 8)) {
         DLOG("Scrolling on a window decoration\n");
         orientation_t orientation = (con->parent->layout == L_STACKED ? VERT : HORIZ);
         /* Focus the currently focused container on the same level that the
@@ -244,10 +246,12 @@ static int route_click(Con *con, xcb_button_press_event_t *event, const bool mod
          * #557), we first check if scrolling is possible at all. */
         bool scroll_prev_possible = (TAILQ_PREV(focused, nodes_head, nodes) != NULL);
         bool scroll_next_possible = (TAILQ_NEXT(focused, nodes) != NULL);
-        if (event->detail == XCB_BUTTON_INDEX_4 && scroll_prev_possible)
+        if ((event->detail == XCB_BUTTON_INDEX_4 || event->detail == 6) && scroll_prev_possible) {
             tree_next('p', orientation);
-        else if (event->detail == XCB_BUTTON_INDEX_5 && scroll_next_possible)
+        } else if ((event->detail == XCB_BUTTON_INDEX_5 || event->detail == 8) && scroll_next_possible) {
             tree_next('n', orientation);
+        }
+
         goto done;
     }
 
````

**Comment by mahkoh** [comment]
Just to make sure we're talking about the same thing, I've made a video showing the feature I'm talking about. Note that I'm using only scrolling operations to switch between tabs/workspaces in this video.

https://my.mixtape.moe/hqoaak.mp4

>The only scrolling switching workspaces happens on the i3bar workspace buttons.

That's exactly the behavior I would expect. As I said in the OP:

>That is, **whenever scrolling downwards would switch to the tab/workspace to the right of the current tab/workspace**, scrolling rightwards behaves the same way. 

At that point I did not properly distinguish between tabs and workspaces so maybe that's what caused the confusion.

**Comment by Airblader** [comment]
> At that point I did not properly distinguish between tabs and workspaces so maybe that's what caused the confusion.

Yeah, OK, I gotcha now. Workspace switching is on i3bar, so that is what confused me. The patch above will only do the window part, not the workspace part. That would be equally fine with me, though.

**Comment by Airblader** [comment]
And thanks for the video, that really cleared it up!

**Comment by nmschulte** [comment]
Note, I typo'd: the "right scroll" is `button7`, not `button8`.

**Comment by Airblader** [comment]
Ah, OK. Then the patch needs to be adapted accordingly.

**Comment by Airblader** [comment]
Here's an updated patch which should also take care of i3bar:

````
diff --git a/i3bar/src/xcb.c b/i3bar/src/xcb.c
index edef9b7e..fb6a9421 100644
--- a/i3bar/src/xcb.c
+++ b/i3bar/src/xcb.c
@@ -532,6 +532,7 @@ void handle_button(xcb_button_press_event_t *event) {
     }
     switch (event->detail) {
         case 4:
+        case 7:
             /* Mouse wheel up. We select the previous ws, if any.
              * If there is no more workspace, don’t even send the workspace
              * command, otherwise (with workspace auto_back_and_forth) we’d end
@@ -542,6 +543,7 @@ void handle_button(xcb_button_press_event_t *event) {
             cur_ws = TAILQ_PREV(cur_ws, ws_head, tailq);
             break;
         case 5:
+        case 8:
             /* Mouse wheel down. We select the next ws, if any.
              * If there is no more workspace, don’t even send the workspace
              * command, otherwise (with workspace auto_back_and_forth) we’d end
diff --git a/src/click.c b/src/click.c
index 913741b4..b3a289e6 100644
--- a/src/click.c
+++ b/src/click.c
@@ -229,7 +229,9 @@ static int route_click(Con *con, xcb_button_press_event_t *event, const bool mod
     if (in_stacked &&
         dest == CLICK_DECORATION &&
         (event->detail == XCB_BUTTON_INDEX_4 ||
-         event->detail == XCB_BUTTON_INDEX_5)) {
+         event->detail == XCB_BUTTON_INDEX_5 ||
+         event->detail == 7 ||
+         event->detail == 8)) {
         DLOG("Scrolling on a window decoration\n");
         orientation_t orientation = (con->parent->layout == L_STACKED ? VERT : HORIZ);
         /* Focus the currently focused container on the same level that the
@@ -244,10 +246,12 @@ static int route_click(Con *con, xcb_button_press_event_t *event, const bool mod
          * #557), we first check if scrolling is possible at all. */
         bool scroll_prev_possible = (TAILQ_PREV(focused, nodes_head, nodes) != NULL);
         bool scroll_next_possible = (TAILQ_NEXT(focused, nodes) != NULL);
-        if (event->detail == XCB_BUTTON_INDEX_4 && scroll_prev_possible)
+        if ((event->detail == XCB_BUTTON_INDEX_4 || event->detail == 7) && scroll_prev_possible) {
             tree_next('p', orientation);
-        else if (event->detail == XCB_BUTTON_INDEX_5 && scroll_next_possible)
+        } else if ((event->detail == XCB_BUTTON_INDEX_5 || event->detail == 8) && scroll_next_possible) {
             tree_next('n', orientation);
+        }
+
         goto done;
     }
 
````

**Comment by nmschulte** [comment]
`s/7/6/` and `s/8/7/`

**Comment by Airblader** [comment]
Right… Updated. :-)

**Comment by Airblader** [comment]
@mahkoh Did you give the patch a try?

**Comment by mahkoh** [comment]
I had to spend an uncomfortable amount of time figuring out how to build i3 (because I'm not a package maintainer) but I can confirm that the patch works on my machine.

**Comment by Airblader** [comment]
@mahkoh We would've been happy to help with how to compile. :-) Anyway, thanks for the confirmation!

**Comment by JuninhoFreitas** [comment]
> Yeah, sorry, it was incomplete. I meant to say
> 
> ```
> bindsym --whole-window --border button4 workspace next_on_output
> bindsym --whole-window --border button5 workspace prev_on_output
> ```
> 
> And if you have NumLock enabled you might have to add `Mod2`:
> 
> ```
> bindsym --whole-window --border Mod2+button4 workspace next_on_output
> bindsym --whole-window --border Mod2+button5 workspace prev_on_output
> ```


Hey @Airblader , just coming here to say, thank you!
it worked very well! 
Now i can have a good experience with i3.
