### ISSUE TITLE
i3 bindsym does not respect keyboard layout

### ISSUE THREAD

**Issue by patrickdepinguin** [i3/i3#2686]
This issue is a follow-up of mail thread:
http://www.freelists.org/post/i3-discuss/i3-bindsym-does-not-respect-keyboard-layout

Output of `i3 --moreversion 2>&- || i3 --version`:
```
Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08) (pid 5033)o abort…)
Loaded i3 config: /home/tdescham/.config/i3/config (Last modified: Thu 16 Feb 2017 09:27:59 AM CET, 86569 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: /usr/bin/i3
```

URL to a logfile as per http://i3wm.org/docs/debugging.html:
http://logs.i3wm.org/logs/5735735550279680.bz2
                                                                                                                                                   
**What I did:**

I started i3 on a second x server with the minimal config
```
set $mod Mod4
bindsym $mod+Return exec urxvt
bindsym $mod+k focus down
bindsym $mod+Shift+k move down
bindsym $mod+v split v
bindsym $mod+Shift+v split h
```
then I did the following actions:

* open terminal (mod+Return)
* type 'dvorak' (in the log file this causes a brief change of the window title, so you can observe this point)
* press 'mod+v'
* press 'mod+shift+v'
* change keyboard layout to qwerty via xorg
* type 'qwerty' (observe the window title change in the log)
* press 'mod+v' using the natural location of 'v' in qwerty layout (=fourth key from the left on the bottom row)
* press 'mod+Shift+v'
* press 'mod+period' (period in qwerty is the same physical location as 'v' in dvorak, this is second key from the right on the bottom row)
* press 'mod+Shift+period'

**What I saw:**

In the dvorak mode, the desired actions occur: 'split v'  (mod+v), then 'split h' (mod+shift+v).
In qwerty mode, using the qwerty normal positions, an incorrect action is done: 'focus down' and 'move down' respectively. This is because 'v' in qwerty layout is the same physical location as 'k' in dvorak layout and mod+k is mapped to 'focus down'.
When I then used the same physical keys as in dvorak (mod+period), then I get again the correct actions (but on the wrong key).

**What I expected instead:**

Since I'm using bindsym rather than bindcode, the key binding should move along with the keyboard layout, i.e. if I use 'mod+v', wherever v is located in the selected keyboard layout, the action 'split v' should be executed.

My xorg settings for keyboard layout are:
```
      Option "XkbLayout" "us,us"
      Option "XkbVariant" "dvorak,"
      Option "XkbOptions" "grp:shifts_toggle,compose:ralt,caps:ctrl_modifier"
```
which means dvorak is the default layout, and qwerty is the second
layout reachable by pressing both shift keys.

**Comment by patrickdepinguin** [comment]
I've been investigating this issue in more detail. I have made a more clear and annotated log file here: http://logs.i3wm.org/logs/5769457217568768.bz2

My analysis is that i3 is always grabbing the keycodes that correspond to the _first_ keymap in the xorg configuration, even when changing keymap.

The log is taken with keymap list 'be,us' (=azerty, qwerty). The i3 configuration has a binding on 'a' but not on 'q'  (a and q are swapped between azerty and qwerty).

'a' (keysym 0x61) has keycode 24 in azerty, and keycode 38 in qwerty. Yet, the log file clearly shows that i3 unconditionally grabs keycode 24, which is incorrect.


I'm not sure if it's relevant, but the changing of keymap seems to be triggering an xkb notification type of 'XCB_XKB_STATE_NOTIFY', while there exists another seemingly more specific notification type 'XCB_XKB_MAP_NOTIFY' which is not triggered. I tried aligning the code executed on STATE_NOTIFY to the code of MAP_NOTIFY as follows, but it did not fix the grabbing:

```
diff --git a/src/handlers.c b/src/handlers.c
index 9fb9040..e66d5c8 100644
--- a/src/handlers.c
+++ b/src/handlers.c
@@ -1477,7 +1477,10 @@ void handle_event(int type, xcb_generic_event_t *event) {
             if (xkb_current_group == state->group)
                 return;
             xkb_current_group = state->group;
+            xcb_key_symbols_free(keysyms);
+            keysyms = xcb_key_symbols_alloc(conn);
             ungrab_all_keys(conn);
+            translate_keysyms();
             grab_all_keys(conn);
         }
```

It is not clear to me where in the code something is missing or incorrect. Any pointers are welcome.

**Comment by stapelberg** [comment]
Haven’t looked at this in detail yet, but one thing I can say already is that testcase https://github.com/i3/i3/blob/6a7f9370dbff7c9147622c4a3f364b98125a08b2/testcases/t/257-keypress-group1-fallback.t is relevant. It sets up a similar configuration (two layouts at the same time).

**Comment by stapelberg** [comment]
Please see the last paragraph of https://i3wm.org/docs/userguide.html#keybindings:

> When using multiple keyboard layouts (e.g. with setxkbmap -layout us,ru), you can specify in which XKB group (also called “layout”) a keybinding should be active. By default, keybindings are translated in Group1 and are active in all groups. If you want to override keybindings in one of your layouts, specify the corresponding group. For backwards compatibility, the group “Mode_switch” is an alias for Group2.

I think you’ll need to use e.g.:
```
bindsym Group1+$mod+v split v
bindsym Group2+$mod+v split v
```
…in order to have a key binding for “v” in both group 1 (dvorak) and group 2 (qwerty).

Does that work?

**Comment by patrickdepinguin** [comment]
Yes that seems to work. I had read over that paragraph -- I guess the title with words GroupX that didn't mean anything to me made me dismiss it as irrelevant. Perhaps there could be a FAQ entry to clarify this behavior?

Do you think that this need of repeating each binding for every group is 'correct', or should something be changed in the default behavior?

**Comment by stapelberg** [comment]
Thanks for confirming, I’ll close this issue.

> Perhaps there could be a FAQ entry to clarify this behavior?

Sure, feel free to create one.

> Do you think that this need of repeating each binding for every group is 'correct', or should something be changed in the default behavior?

At this point, I’m definitely not looking to change the default behavior. In general, we never want to break existing configs in i3 (when we need to fix bugs, we make a judgement call).

**Comment by patata3000** [comment]
> Haven’t looked at this in detail yet, but one thing I can say already is that testcase https://github.com/i3/i3/blob/6a7f9370dbff7c9147622c4a3f364b98125a08b2/testcases/t/257-keypress-group1-fallback.t is relevant. It sets up a similar configuration (two layouts at the same time).

This seems to only be testing `Super_L + Return` binding which don't change the keycode in the case of `us` vs `ru` layouts. This is why it's working. Try to test with a random letter and you may have a failure with a bindsym.
