### ISSUE TITLE
xrdp/xorgxrdp reconnection causes i3 to use 100% CPU

### ISSUE THREAD

**Issue by soedar** [i3/i3#2701]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5731132955951104.bz2

**What I did:**
1. Build and install [xrdp 0.9.1](https://github.com/neutrinolabs/xrdp/releases/tag/v0.9.1) and [xorgxrdp 0.2.0](https://github.com/neutrinolabs/xorgxrdp/releases/tag/v0.2.0) on an Ubuntu 16.04 VM (server)
2. Install i3 on the server.
3. Install Remmina (RDP client) on another Ubuntu 16.04 VM (client)
4. Connect to the server from client using Remmina via RDP. On first connection, i3 responds to keyboard and mouse events, and things appears to be fine.
5. Disconnect, and reconnect to the server using Remmina.

**What I saw:**

1. Subsequent connections to the server shows the same i3 session since the first connection. All previously opened windows/workspace are present, and time continues to tick on i3status.
2. However, i3 no longer responds to keyboard and mouse events.
3. i3 on the server runs with 100% CPU
4. Interesting parts of i3 logs upon reconnection. The last few log lines are repeated until i3 is killed.
```
08/03/2017 19:43:28 - handlers.c:handle_event:1369 - event type 89, xkb_base 85
08/03/2017 19:43:28 - handlers.c:handle_screen_change:416 - RandR screen change
08/03/2017 19:43:28 - handlers.c:handle_screen_change:426 - root geometry reply: (0, 0) 1920 x 1080
08/03/2017 19:43:28 - randr.c:randr_query_outputs:641 - primary output is 00000000
08/03/2017 19:43:28 - randr.c:handle_output:561 - found output with name rdp0
08/03/2017 19:43:28 - randr.c:handle_output:598 - mode: 1920x1080+0+0
08/03/2017 19:43:28 - randr.c:randr_query_outputs:671 - Active RandR output found. Disabling root output.
08/03/2017 19:43:28 - randr.c:randr_query_outputs:685 - output 0x55e5909da800 / rdp0, position (0, 0), checking for clones
08/03/2017 19:43:28 - randr.c:randr_query_outputs:698 - output 0x55e590a69c40 has the same position, his mode = 1920 x 1080
08/03/2017 19:43:28 - randr.c:randr_query_outputs:709 - disabling output 0x55e590a69c40 (rdp0)
08/03/2017 19:43:28 - randr.c:randr_query_outputs:714 - new output mode 1920 x 1080, other mode 1920 x 1080
08/03/2017 19:43:28 - randr.c:randr_query_outputs:724 - Need to initialize a Con for output rdp0
08/03/2017 19:43:28 - randr.c:output_init_con:283 - init_con for output rdp0
08/03/2017 19:43:28 - randr.c:output_init_con:293 - Using existing con 0x55e590a62e80 / rdp0
08/03/2017 19:43:28 - randr.c:output_init_con:314 - Not adding workspace, this was a reused con
08/03/2017 19:43:28 - randr.c:randr_disable_output:778 - Output rdp0 disabled, re-assigning workspaces/docks
08/03/2017 19:43:28 - randr.c:randr_disable_output:792 - This output (0x55e590a62e80) was focused! Getting next
08/03/2017 19:43:28 - randr.c:randr_disable_output:794 - next = 0x55e590a593d0
08/03/2017 19:43:28 - randr.c:randr_disable_output:809 - Detaching current = 0x55e590a593d0 / 1
08/03/2017 19:43:28 - randr.c:randr_disable_output:811 - Re-attaching current = 0x55e590a593d0 / 1
08/03/2017 19:43:28 - con.c:_con_attach:84 - it's a workspace. num = 1
08/03/2017 19:43:28 - randr.c:randr_disable_output:813 - Fixing the coordinates of floating containers
08/03/2017 19:43:28 - randr.c:randr_disable_output:818 - Done, next
08/03/2017 19:43:28 - randr.c:randr_disable_output:809 - Detaching current = 0x55e590a593d0 / 1
08/03/2017 19:43:28 - randr.c:randr_disable_output:811 - Re-attaching current = 0x55e590a593d0 / 1
08/03/2017 19:43:28 - con.c:_con_attach:84 - it's a workspace. num = 1
08/03/2017 19:43:28 - randr.c:randr_disable_output:813 - Fixing the coordinates of floating containers
08/03/2017 19:43:28 - randr.c:randr_disable_output:818 - Done, next
08/03/2017 19:43:28 - randr.c:randr_disable_output:809 - Detaching current = 0x55e590a593d0 / 1
08/03/2017 19:43:28 - randr.c:randr_disable_output:811 - Re-attaching current = 0x55e590a593d0 / 1
08/03/2017 19:43:28 - con.c:_con_attach:84 - it's a workspace. num = 1
08/03/2017 19:43:28 - randr.c:randr_disable_output:813 - Fixing the coordinates of floating containers
08/03/2017 19:43:28 - randr.c:randr_disable_output:818 - Done, next
08/03/2017 19:43:28 - randr.c:randr_disable_output:809 - Detaching current = 0x55e590a593d0 / 1
08/03/2017 19:43:28 - randr.c:randr_disable_output:811 - Re-attaching current = 0x55e590a593d0 / 1
08/03/2017 19:43:28 - con.c:_con_attach:84 - it's a workspace. num = 1
08/03/2017 19:43:28 - randr.c:randr_disable_output:813 - Fixing the coordinates of floating containers
08/03/2017 19:43:28 - randr.c:randr_disable_output:818 - Done, next
```

**What I expected instead:**
1. i3 should continue to work after reconnection via RDP
2.  Ideally, the same session should be preserved after reconnecting via RDP

Related: neutrinolabs/xrdp#662

**Comment by soedar** [comment]
I've done some digging around, and it seems like the cause of the infinite loop happens here:
https://github.com/i3/i3/blob/next/src/randr.c#L876

Because the con is reused, `output->con` and `first->con` are the same, and the reassignment of the workspace simply removes and attach to the some con.

However, this appears to be the superficial cause of the problem. Interestingly, when I compile `next` with RandR 1.5, I no longer run into this issue. Seems like the issue probably originates from the RandR 1.4 output query code, but I haven't look too deeply there.

At this point, is it worth investigating into fixing the RandR 1.4 code? Would future i3 packages be compiled with RandR 1.5, making this a non issue for future version?

**Comment by seidler2547** [comment]
I'm having the same issue on a fresh Debian 8 install using xrdp 0.9.1 and i3 4.13 from backports.

I do not see 100% CPU usage, but the other issues you describe are exactly the same.

However, I have just found a workaround: when I make the initial connection with xfreerdp (from FreeRDP 1.1.0~git20140921.1.440916e+dfsg1-4) using the /multimon parameter, then at least I can then reconnect without making i3 stop. It won't pick up any resolution changes, but since i reacts to keyboard shortcuts, I can restart it and then it uses the new resolution.

Any subsequent connections then work also without the /multimon parameter. *Might* be more a bug in the way xrdp presents the xrandr outputs?

**Comment by soedar** [comment]
> Might be more a bug in the way xrdp presents the xrandr outputs?

Although that is possible, I think that is unlikely. I've tried awesomewm and i3 compiled with RandR1.5 (which uses a different code path to detect monitors), and in both instances I did not encounter issues when I reconnect.

It might be worthwhile to see how [randr_query_outputs_14](https://github.com/i3/i3/blob/next/src/randr.c#L710) and [randr_query_outputs_15](https://github.com/i3/i3/blob/next/src/randr.c#L536) differs, that might give us some clue on how to fix this issue.

**Comment by seidler2547** [comment]
That's right. Also, XFCE4 doesn't exhibit any of these problems. As Debian 8 is using XRandR 1.4, I would prefer if this would be fixed on 1.4, unless 1.5 is backwards compatible.

**Comment by stapelberg** [comment]
We intend to release 4.14 soon (within the next couple of weeks). I’ll leave this open for now (so that affected users can find it easily), but tag it as wontfix already, since the move to RandR 1.5 fixes it.

**Comment by soedar** [comment]
I can confirm that with i3 4.14 with [xrdp 0.9.3.1](https://github.com/neutrinolabs/xrdp/releases/tag/v0.9.3.1) and [xorgxrdp 0.2.3](https://github.com/neutrinolabs/xorgxrdp/releases/tag/v0.2.3), I am no longer seeing this issue.
