### ISSUE TITLE
Feature request: new_window -> default_border

### ISSUE THREAD

**Issue by SirCmpwn** [i3/i3#2702]
We get a lot of people running sway who don't understand how to disable borders by default. I think it mostly has to do with this command being poorly named. I suggeste adding the default_border command, aliasing new_window to it for compatability, and deprecating the old command.

**Comment by zandrmartin** [comment]
Would also make sense to change `new_float` to `default_floating_border`.

**Comment by Airblader** [comment]
Can you take me through the actual user process that allows the user to find it more easily because of such a rename? It's still not a guess-able name, I would say, so doesn't this require the user to read the userguide just as much?

Perhaps it'd be just as good, if not better, to rephrase the documentation for it such that searching for specific terms brings the user to this directive more quickly?

**Comment by SirCmpwn** [comment]
By that logic you could just start naming commands after the next few bytes out of /dev/random, so long as the user guide clears things up.

**Comment by Airblader** [comment]
I think the current name is not quite as bad as random bytes. And there's a difference between the initial naming and a change later on. Introducing a new name comes with a certain complexity that should be justified. 

That said, your answer makes me think you're not really interested in constructively discussing this.

**Comment by SirCmpwn** [comment]
What I'm saying is that it's a bad name, and clearing it up in the user guide doesn't make it a better name. But I guess that's not constructive. Yeesh.

**Comment by Airblader** [comment]
And I haven't said that it's a great name, just that I haven't quite understood what's so fundamentally bad about it that a mere change in name suddenly leads users to finding it. And I've explained why aliases should be avoided if they aren't actually useful. These points haven't actually been addressed.

I'm also not going to further comment condescending or provocative comments.

**Comment by zandrmartin** [comment]
I recently added a note to our FAQ explaining how to use the `border` and `new_window` commands. We were getting several questions a day in our IRC channel asking how to remove borders from all windows. Even with the note in the FAQ, we still get this question a lot. At least if the command were `default_border` there would be a better chance users would find it.

Yes we could go to painstaking detail in the man page to explain what `new_window` does, but I don't get the sense most people asking this question read the man page at all. I suspect many of them are looking at other people's config files, and there `new_window` doesn't look like it's related to borders at all, so they just skip it.

**Comment by SirCmpwn** [comment]
They'll see it in a variety of ways. They'll find it in other user's configs (wtf does `new_window none` mean without context), lists of commands, etc. A lot of people don't use the user guide as the source of truth here - you've argued from a conflicting perspective on other issues, saying that good docs don't justify features for this reason.

In terms of complexity, adding an alias would be pretty trivial.

**Comment by Airblader** [comment]
> In terms of complexity, adding an alias would be pretty trivial.

I'm not talking about implementation complexity, but mental complexity. Small things add up. 

That said, the arguments regarding other config files sound convincing to me. Let's go with these new aliases. The old ones should still be documented for reference, but marked as deprecated there. Similarly to what we're doing for the 1pixel value.

**Comment by clawoflight** [comment]
I'll look into this. Is this what needs to be done?

- [ ] copy/rename `new_{window,float}` and associated states in `parser-config/config.spec`
- [ ] rename `cfg_new_{window,float}` in `config_directives.c` and update calls (only in tests?)
- [ ] extend the test case in `201-config-parser.t`
- [ ] update the user guide

**Comment by Airblader** [comment]
Yeah, that sounds like a reasonable plan.
