### ISSUE TITLE
New windows are not focused, no apparent no_focus in config

### ISSUE THREAD

**Issue by chadfurman** [i3/i3#2704]
**Output of `i3 --moreversion 2>&- || i3 --version`:**

```
Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08) (pid 1711)o abort…)
Loaded i3 config: /home/lotus/.config/i3/config (Last modified: Fri 10 Mar 2017 03:26:22 PM EST, 303 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

**URL to a logfile as per http://i3wm.org/docs/debugging.html:**

http://logs.i3wm.org/logs/5648943388033024.bz2

**What I did:**

hit super+enter to create a new terminal

**What I saw:**

new terminal was created but not focused

**What I expected instead:**

focus should be on new terminal

**Comment by Airblader** [comment]
What terminal emulator are you using? Does this happen only with that emulator or also other programs?

**Comment by chadfurman** [comment]
I'm using "terminator" and it only happens in the terminal, @Airblader

**Comment by chadfurman** [comment]
switched to urxvt, works fine

**Comment by Airblader** [comment]
Yes, terminator has this behavior of rejecting focus. See #2622. You can also find a couple of suggestions there.
