### ISSUE TITLE
Focus issue in tabbed/stacked layouts with emacsclient

### ISSUE THREAD

**Issue by djl** [i3/i3#2708]
Output of `i3 --moreversion 2>&- || i3 --version`:

    Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
    Running i3 version: 4.13 (2016-11-08) (pid 4519)o abort…)
    Loaded i3 config: /home/djl/.config/i3/config (Last modified: Tue 14 Mar 2017 01:45:30 PM GMT, 503498 seconds ago)

    The i3 binary you just called: /usr/bin/i3
    The i3 binary you are running: i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5703417800425472.bz2

**What I did:**

1. Switch the workspace to tabbed or stacked layout (this happens in both)
2. Open Emacs and start the server (`M-x server-start`)
3. Open a terminal
4. Run `emacsclient foo`

**What I saw:**

Emacs will be "focused" but it's not brought to the front - the terminal will still be at the front while Emacs, in another tab, has focus.

**What I expected instead:**

Focus should be switched the Emacs window and it should be brought to the front.

**Other stuff which might relevant**

If emacsclient creates a new frame (i.e. `emacsclient -c foo`), then i3 correctly switches to this newly spawned window.

This does not happen in split layout, only tabbed/stacked.

**Comment by stapelberg** [comment]
I can’t reproduce this on Debian testing. Haven’t checked out the log yet.

**Comment by stapelberg** [comment]
Can reproduce it now (in tabbed layout, not entirely sure yet whether that’s relevant).

**Comment by stapelberg** [comment]
This is actually the same issue as #2745 — by running Emacs through `xtrace`, I can see that it sends a `ConfigureWindow` request, whose `stack-mode` we don’t currently honor:

```
002:<:41bc: 16: Request(12): ConfigureWindow window=0x02c00126 values={stack-mode=Above(0x00)}
```
