### ISSUE TITLE
Mod5 / AltGr / ISO_Level3_Shift with German keyboard layout is not working if used in the i3 config file

### ISSUE THREAD

**Issue by Smbw42** [i3/i3#2717]
Output of `i3 --moreversion 2>&- || i3 --version`:
```Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
(Getting version from running i3, press ctrl-c to abort…)
Running i3 version: 4.13 (2016-11-08) (pid 521)
Loaded i3 config: /root/.config/i3/config (Last modified: Sat 25 Mar 2017 03:21:12 PM UTC, 11668 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: x-window/i3
```

URL to a logfile as per http://i3wm.org/docs/debugging.html:

[http://logs.i3wm.org/logs/5756901417549824.bz2](http://logs.i3wm.org/logs/5756901417549824.bz2)

**What I did:**
Preparation:
My `$mod` variable is set to `Mod1` (which is basically `Alt_L` on my system / keyboard). My config differs from the default config in that `Mod5+Shift+q` closes a window. `Mod5` is basically `AltGr` on my keyboard,
So I started i3 (via `startx`) and typed `Alt_L`+`Return` to open a terminal, then I typed `Alt_L`+`Shift`+`r` to restart i3 inplace.

The problem:
Now I type `AltGr`+`Shift`+`q`

**What I saw:**
 Nothing happend

**What I expected instead:**
 I expect the terminal window to close.

**Additional info:**
I tried it with a minimal config choosing `Mod1` as `$mod` and changing the line:
`bindsym $mod+Shift+q kill`
to
`bindsym Mod5+Shift+q kill`

On further testing I also tried it for full screen mode (`mod5+f`) and closing i3 (`mod5+shift+e`) without any luck. BUT: 
`bindsym Mod5+Return exec i3-sensible-terminal`
actually works and opens a terminal as expected when typing `AltGr`+`Return`.

**Why this is important:**
On German keyboards there is only one `Alt` key: the `Alt_L` key. There is no `Alt_R`. Some key combinations are really hard to type if there is no way to use the `AltGr` key.

On Debian Jessie (i3 version 4.8) this problem doesn't exist so you can use `AltGr` as expected.
If further help in debugging is needed / welcome: I'm willing to help ;)

**Comment by Airblader** [comment]
Can you use `xev -event keyboard` and type the combination that doesn't work and post the output of that? I assume that given your layout it actually comes out as a different key which then isn't recognized.

**Comment by Smbw42** [comment]
Okay:
I've configured `bindsym Mod5+Shift+q kill`.
Now I type `AltGr`+`Shift`+`q` and get:
```
KeyPress event, serial 28, synthetic NO, window 0xe00001,
    root 0x1c5, subw 0x0, time 5069749, (110,369), root:(514,389),
    state 0x10, keycode 108 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 92
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 28, synthetic NO, window 0xe00001,
    root 0x1c5, subw 0x0, time 5070074, (110,369), root:(514,389),
    state 0x90, keycode 62 (keysym 0xffe2, Shift_R), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 28, synthetic NO, window 0xe00001,
    root 0x1c5, subw 0x0, time 5070373, (110,369), root:(514,389),
    state 0x91, keycode 24 (keysym 0x7d9, Greek_OMEGA), same_screen YES,
    XLookupString gives 2 bytes: (ce a9) "Ω"
    XmbLookupString gives 2 bytes: (ce a9) "Ω"
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0xe00001,
    root 0x1c5, subw 0x0, time 5070490, (110,369), root:(514,389),
    state 0x91, keycode 24 (keysym 0x7d9, Greek_OMEGA), same_screen YES,
    XLookupString gives 2 bytes: (ce a9) "Ω"
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0xe00001,
    root 0x1c5, subw 0x0, time 5071011, (110,369), root:(514,389),
    state 0x91, keycode 108 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 92
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0xe00001,
    root 0x1c5, subw 0x0, time 5071033, (110,369), root:(514,389),
    state 0x11, keycode 62 (keysym 0xffe2, Shift_R), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```
Looking at this log I've the feeling that I have to bind the greek omega instead of q? How would I do that?

**Comment by Airblader** [comment]
You have to use `bindsym Mod5+Shift+Greek_OMEGA`, I think. Can you try that?

**Comment by Smbw42** [comment]
Sure that works. Thank you very much! So this might not even be an issue.
This problem popped up switching from Debian 8 to 9.
Do you think i3's interpretation of the pushed keys changed since version 4.8 or is it more likely that the keyboard layout changed in Debian?
Thanks again, this issue is resolved.

**Comment by Airblader** [comment]
Yes, we had a breaking change in i3 here. We didn't intend for it to be breaking, but decided that we accept that because the reason for the change was to support other bindings which otherwise wouldn't be possible. :-)
