### ISSUE TITLE
xrandr pos changes i3 container locations

### ISSUE THREAD

**Issue by mrmuskrat** [i3/i3#2726]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08) (pid 1684)o abort…)
Loaded i3 config: /home/musgrom/.config/i3/config (Last modified: Tue 04 Apr 2017 10:26:15 AM CDT, 1734 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3-with-/i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5670758869106688.bz2

**What I did:**

Ran `xrandr --output DP-1 --auto --pos 0x420 --output DP-2 --auto --pos 1920x0 --rotate left`

**What I saw:**

All containers on first monitor (DP-1) shifted down 420 pixels.

**What I expected instead:**

Both monitors are 1920x1080. DP-1 is the left monitor and is in landscape mode. DP-2 is the right monitor and is in portrait mode. The expectation from running that xrandr command is that the left monitor would be centered vertically next to the right monitor such that the pointer does not get trapped on invisible walls when moving the pointer from the right monitor to the left monitor.

**Comment by mrmuskrat** [comment]
![20170404_110144](https://cloud.githubusercontent.com/assets/24446/24666497/22ff7ed2-1926-11e7-942b-e34a77581ff6.png)

**Comment by mrmuskrat** [comment]
It's hard to make out from the screenshot but what's displayed on the left monitor starts at position 0, 0 and I expected it to start at 0, 420.

Output of xrandr:
Screen 0: minimum 320 x 200, current 3000 x 1920, maximum 8192 x 8192
DVI-I-1 disconnected (normal left inverted right x axis y axis)
DP-1 connected primary 1920x1080+0+420 (normal left inverted right x axis y axis) 598mm x 336mm
   1920x1080     60.00*+
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
   720x400       70.08  
DP-2 connected 1080x1920+1920+0 left (normal left inverted right x axis y axis) 598mm x 336mm
   1920x1080     60.00*+
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
   720x400       70.08

**Comment by mrmuskrat** [comment]
BTW, I ran `xrandr --output DP-1 --auto --pos 0x0 --output DP-2 --auto --pos 1920x0 --rotate left` prior to uploading the log file.

**Comment by Airblader** [comment]
On a somewhat unrelated note, if you want to avoid those invisible walls you might also want to look into my tool xedgewarp.

**Comment by mrmuskrat** [comment]
@Airblader I will definitely check that out. Before posting this I was actually considering just rotating the right monitor back to landscape just to get past the frustration.

**Comment by nmschulte** [comment]
What happens if you reset i3 after reconfiguring your X11 Outputs?
What does the X11 Output configuration look like before you re-configure?

I use [autorandr](https://github.com/wertarbyte/autorandr) via Xsession (`~/.xsession` + xdm desktop manager/`startx`) and some keybindings in i3, and I don't experience any undesired behavior.

My setup matches yours: landscape 1080p to the left of portrait 1080p.  I have recently started using the laptop display, which is yet further left of the landscape 1080p display, but I believe that is superfluous (as is the specific hardware interface/protocol and topology, though I'm open to the idea that this is an X11 video driver bug).
![2017_04_04-17_22_42-969x875](https://cloud.githubusercontent.com/assets/8540239/24681565/7234f22c-195b-11e7-897e-9b5ba8fd0391.png)

```
$ i3 --moreversion 2>&- || i3 --version
Binary i3 version:  4.13-70-g8c3ddce5 (2017-03-06, branch "next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13-70-g8c3ddce5 (2017-03-06, branch "next") (pid 1138)
Loaded i3 config: /home/nmschulte/.config/i3/config (Last modified: Tue 04 Apr 2017 09:05:30 AM CDT, 30019 seconds ago)

The i3 binary you just called: /home/nmschulte/.local/bin/i3
The i3 binary you are running: i3
```

---

I have to add, though: I am not explicitly resetting i3 via autorandr (it hooks a `postswitch` script, for each "profile") or the i3 keybindings, but it seems i3 is getting reset.  I noticed this today, because I am dealing with non-uniform DPIs across these X11 Outputs, and my `postswitch` scripts munge Xresources to achieve desirable results.  If I understand correctly, i3 only picks up the Xresources during reset, not during signals it may/may not get from X11 about Outputs changing.  I imagine I've found some sort of bug/exceptional code-path in i3, with this.  I _have_ caused i3 to crash by playing with this.

```
$ cat ~/.config/autorandr/laptop/postswitch 
#!/usr/bin/env bash

sed -i '/^!Xft\.dpi: 144/s/^!//' /home/nmschulte/.Xresources
sed -i '/^Xft\.dpi: 96/s/^/!/' /home/nmschulte/.Xresources
xrdb -load /home/nmschulte/.Xresources
```

**Comment by mrmuskrat** [comment]
FYI, I'm using gdm to start at login.

With the y offset in place for DP-1 restarting i3 via keybind or `i3-msg restart` causes it to jump to the top for a fraction of a second and then it goes back to the middle of the screen.

Where would I get the X11 Output configuration? I don't have an .Xresources file in my home directory.

**Comment by nmschulte** [comment]
> Where would I get the X11 Output configuration?

The `xrandr` utility outputs this information; Xrandr manages X11 Outputs (and more...).

**Comment by mrmuskrat** [comment]
I run `xrandr --output DVI-I-1 --off --output DP-1 --auto --pos 0x0 --output DP-2 --auto --pos 1920x0 --rotate left` in my i3 config via exec.

xrandr output after logging in is:
```
Screen 0: minimum 320 x 200, current 3000 x 1920, maximum 8192 x 8192
DVI-I-1 disconnected (normal left inverted right x axis y axis)
DP-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 598mm x 336mm
   1920x1080     60.00*+
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
   720x400       70.08  
DP-2 connected 1080x1920+1920+0 left (normal left inverted right x axis y axis) 598mm x 336mm
   1920x1080     60.00*+
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
   720x400       70.08  
```

After running `xrandr --output DVI-I-1 --off --output DP-1 --auto --pos 0x420 --output DP-2 --auto --pos 1920x0 --rotate left` the xrandr output is:
```
Screen 0: minimum 320 x 200, current 3000 x 1920, maximum 8192 x 8192
DVI-I-1 disconnected (normal left inverted right x axis y axis)
DP-1 connected primary 1920x1080+0+420 (normal left inverted right x axis y axis) 598mm x 336mm
   1920x1080     60.00*+
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
   720x400       70.08  
DP-2 connected 1080x1920+1920+0 left (normal left inverted right x axis y axis) 598mm x 336mm
   1920x1080     60.00*+
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
   720x400       70.08  
```

The display looks correct and the mouse behaves as expected (it aligns properly when moving from DP-1 to DP-2 and back again) but i3 is shifted down by 420 pixels.

**Comment by nmschulte** [comment]
Can you demonstrate the "i3 is shifted down by 420 pixels" claim?  I don't understand.  What you describe seems like correct, intended behavior, to me.

**Comment by mrmuskrat** [comment]
"Normal" i3 display but mouse does not move normally between displays.

![20170405_101757](https://cloud.githubusercontent.com/assets/24446/24712739/49d3b870-19e9-11e7-946c-2cc1dda55b9c.png)

**Comment by mrmuskrat** [comment]
Maybe it is correct for i3 but using the same xrandr command Gnome does not shift down (I'll try to provide a screenshot of that in a bit).

![20170405_101846](https://cloud.githubusercontent.com/assets/24446/24712775/69749302-19e9-11e7-9700-61ef2211fdea.png)

**Comment by mrmuskrat** [comment]
Maybe it is correct for i3 but using the same xrandr command Gnome does not shift down (I'll try to provide a screenshot of that in a bit).

![20170405_102053](https://cloud.githubusercontent.com/assets/24446/24712831/955f51e6-19e9-11e7-86f5-22354e59ece2.png)

**Comment by mrmuskrat** [comment]
Given the second screenshot: The context menu (right-click) is 420 pixels out of sync. In order to get the terminal context menu to appear I have to right-click in the area above i3. 

I have tried to get a screenshot of that but when I do the mouse pointer moves. I'm going to try again.

**Comment by mrmuskrat** [comment]
I switched to Gnome on Xorg and now it too suffers the same fate so yeah, it's looking more and more like the driver.

**Comment by nmschulte** [comment]
Ah, okay -- I understand what you're getting at now.  The containers (and the rest of i3, and really all X clients) are _supposed_ to "shift down" by 420px; your comments made it sound like this wasn't what you expected.

It seems, then, that somehow your pointer/mouse/cursor in X is getting out of whack.  I know tools like `fakexrandr` exist; maybe something like that is causing interference, or a bug in X11/Xorg, or ...

I've never written a window manager before, just hacked on i3 a bit, but I don't think it's special in any way with regard to pointer/mouse interaction and X clients.  @Airblader can likely comment more, but I suspect this isn't i3's fault and there's not much i3 can do about it.

I would test by stop running xedgewarp and similar tools if you are; perhaps one of them is causing interference (by e.g. not picking up new X11 Output configurations) and causing your problem.

**Comment by mrmuskrat** [comment]
If this the expected behavior then I'm sorry to have wasted your time.

I'm not using fakexrandr, xedgewarp or anything other than i3 and xrandr at this point.

I guess we can close the ticket and I'll just rotate DP-2 back to landscape and move on.

**Comment by mrmuskrat** [comment]
What I have:
![what_i_have](https://cloud.githubusercontent.com/assets/24446/24720234/f9235944-1a01-11e7-8400-e048837c48b5.png)

What I want:
![what_i_want](https://cloud.githubusercontent.com/assets/24446/24720239/013b51d6-1a02-11e7-8ff4-b79da16e1326.png)

So if xrandr/ARandR are the wrong tools for this do you have any suggestions?

**Comment by nmschulte** [comment]
@mrmuskrat I believe `xrandr` and `arandr` are the right tools to re-configure your X11 Output configuration.  Something else is getting in the way, it seems.  I'm not sure which tool you're using to capture the entire X11 Display (all of the Outputs, and the "dead-space" that isn't mapped to an Output), but that seems to be a point of confusion.

On your `DP-1` display, you see the `i3bar` at the top, and the program/window shown in your screenshots (first a terminal, and then `arandr`), correct?

That indicates to me that `arandr`/`xrandr` are working fine, and that `i3` is reacting accordingly to these changes.  It seems then, you are having some issue with your mouse; particularly, that your mouse input doesn't seem to react to the Output changes.  I don't think this is `i3`'s fault, but I defer to @Airblader.

**Comment by Airblader** [comment]
I haven't had time to read everything in detail, but a few things:

> If I understand correctly, i3 only picks up the Xresources during [re]start, not during signals it may [not] get from X11 about Outputs changing.

Correct. But i3 is not the only program reading these values. :-)

It is correct that i3 is not directly involved in translating mouse interactions. If this is broken it sounds like some issue with the driver or Xorg itself.

**Comment by mrmuskrat** [comment]
So I captured a video and limited it DP-1. It contains an alternate reality in that it does not show what I saw... The mouse pointer was actually in the empty space above the i3 bar. It's as if everything but the viewport shifted. (I think that's the right term.) Is there something else that controls the viewport? 

[https://youtu.be/wK7wZe3_r6U](https://youtu.be/wK7wZe3_r6U)

**Comment by mrmuskrat** [comment]
I think I'm going to have to use my phone to capture a video of this.

**Comment by nmschulte** [comment]
Thank you for the capture.  I want to note that `arandr` does not automatically update its display when you change the configuration with another tool, so that is why it still shows DP-1 aligned to the top of DP-2 when you run `xrandr`.  If you close and re-start `arandr`, it'll show the new configuration.

I'll try recording like this myself too, to see how `ffmpeg` behaves when recording while changing the output configuration.  Your e.g. phone recording could be helpful too.

**Comment by mrmuskrat** [comment]
Here's the phone capture.  https://www.youtube.com/watch?v=7Uc4w_ledBM

**Comment by bad884** [comment]
I was having the same/similar problem with xrandr directives in my i3 config not working as expected. I solved my issue by saving the arandr shell script and running it in i3 through exec_always.

**Comment by nmschulte** [comment]
@mrmuskrat, did you ever resolve this issue?

**Comment by mrmuskrat** [comment]
Not really but I think this should be closed as it doesn't appear to be caused by i3. In the end, I just went back to a traditional layout with the monitors side-by-side in landscape.
