### ISSUE TITLE
focus_on_window_activation defaults as urgent and cannot be modified

### ISSUE THREAD

**Issue by alxjsn** [i3/i3#2732]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08) (pid 1360)o abort…)
Loaded i3 config: /home/alxjsn/.config/i3/config (Last modified: Fri 07 Apr 2017 01:03:12 PM PDT, 417 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5684192989937664.bz2

**What I did:**

I was using urxvt to test this, but any form of getting a window to trigger urgency will work. In my case I added `URxvt.urgentOnBell: true` to my `.Xresources` file and then did a `xrdb ~/.Xresources` in order to configure urxvt to trigger urgency on bell.

Next, I started two urxvt windows in one workspace, ran the command `sleep 3 && echo "\a"`, moved focus to my other window and waited for the other window to trigger an urgent hint.

**What I saw:**

No matter what `focus_on_window_activation` was set to in my config, it would always result in the behavior described by "urgent" in the documentation:

>The window will always be marked urgent, but the focus will not be stolen.

**What I expected instead:**

The behavior should be as described here: https://i3wm.org/docs/userguide.html#focus_on_window_activation

If there is no explicit setting in your configuration it still does not behave as smart should (which documentation says is the default). I tried using "none" in order to disable urgent notifications completely, but that does not work. The setting doesn't affect any behavior at all.

**Comment by Airblader** [comment]
You have this a little backwards. `focus_on_window_activation' determines behavior when the window is activated, which is a specific request. You are directly setting the urgency hint on the window, which is something else. i3bar marks urgent windows with the defined colors and i3 with the defined borders.

If you don't want urgency to be displayed, configure i3bar and i3 to not use special colors for urgency using `client.urgent` and `bar { urgent_workspace }`, respectively.

I'm going to close this since there is no issue here, but just a misunderstanding. If you have further questions please feel free to ask them!

**Comment by alxjsn** [comment]
@Airblader So the problem with that solution is that I like to keep the i3bar hidden and whenever I get an ugent hint then the bar appears. That is the main issue I am trying to resolve.

But from what it looks like `focus_on_window_activation` isn't even working properly for when setting the urgency hint on the window and switching focus. For example, if I do not set that option at all or set it to `smart` the behavior is still `urgent`. If I have two windows open in one workspace and I have focus set to one of them, then if I have `smart` set then if the other window is urgent then the focus should switch to that window and not trigger an urgent hint. That is what I understand should happen from the documentation, but it's not. Instead the window gets a red border and doesn't switch focus, even though they are in the same active workspace.

>smart
>This is the default behavior. If the window requesting focus is on an active workspace, it will receive the focus. Otherwise, the urgency hint will be set.
