### ISSUE TITLE
i3bar: Character `&` empties workspace name

### ISSUE THREAD

**Issue by joepvd** [i3/i3#2741]
When using a pango font in i3bar, the workspace name will show up as an empty string if the characters `&` or `<` are included but do not make a syntactically correct pango markup.

Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08) (pid 28712) abort…)
Loaded i3 config: /home/joep/.config/i3/config (Last modified: So 16 Apr 2017 01:19:19 CEST, 1555 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

**Logfile:**

[i3log](http://logs.i3wm.org/logs/5678205671309312.bz2)
[i3bar.txt](https://github.com/i3/i3/files/924000/i3bar.txt)

**What I did:**

I created a new workspace containing the character `&`.

```sh
i3-msg -t command move workspace 'a & b'
[{"success":true}]
```

**What I saw:**

The named workspace in i3bar is an empty string:

![selection_055](https://cloud.githubusercontent.com/assets/884975/25067720/08b90ed2-224d-11e7-9f51-3b97e8c84e64.png)

**What I expected instead:**

The name of the workspace in i3bar equals `a & b` (as also reported by `i3-msg -t get_workspaces`).

**Comment by joepvd** [comment]
The same happens with the `<` chareacter:

```sh
i3-msg -t command rename workspace to 'a<b'
```

**Comment by joepvd** [comment]
Updated bug report to add that the problem only appears when using a pango font.

**Comment by Airblader** [comment]
This is probably a problem with not escaping pango markup correctly. PRs welcome.

**Comment by Airblader** [comment]
Actually this is working as intended. We parse workspace names as pango markup. If we escaped workspace names, we'd effectively prevent pango markup from being used. You'll just have to properly escape the markup when naming workspaces.
