### ISSUE TITLE
Feature Request: Key Release IPC message for Mod keys

### ISSUE THREAD

**Issue by muhmud** [i3/i3#2744]
I'm using i3 version 4.13

I think it would be nice to have an ipc message sent out when any of the mod keys are released. This would allow a client script to be used to implement Alt+Tab style window stacking, which is really useful for some users. The release event is required to know when cycling is over and to allow the stack to be updated.

I have done this in my own fork by adding code to test `state->eventType` and `state->keycode` in the `handle_event()` function in handlers.c when processing a `XCB_XKB_STATE_NOTIFY` message, and then sending out a message as required.

I was then able to use a slightly hacked version of i3ipc.py to create client python scripts that now allow me to do Alt+Tab style switching for both windows and workspaces (woohoo!).

Would be nice if this could be pulled in.

Thanks for a great WM!

**Comment by Airblader** [comment]
I think the feature itself sounds acceptable. Can you create a PR?

**Comment by muhmud** [comment]
OK, done, it's [here](https://github.com/i3/i3/pull/2756)

**Comment by Airblader** [comment]
As explained in the PR I've changed my mind on accepting this. Sorry again for the confusion!

**Comment by muhmud** [comment]
No problem, but a bit of a shame. 

If bindsym --release worked for mod keys by themselves, that would also be OK, but it doesn't.
