### ISSUE TITLE
Intellij idea can't switch windows content by it's own

### ISSUE THREAD

**Issue by abonec** [i3/i3#2745]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08) (pid 1778)o abort…)
Loaded i3 config: /home/abonec/.i3/config (Last modified: Чт 20 апр 2017 10:51:41, 1806 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5686969954729984.bz2

**What I did:**

Switching windows between [Idea](https://www.jetbrains.com/idea/) projects by i3wm hotkeys (win+k/l) and by idea (ctrl+alt+[)

**What I saw:**
http://files.topmission.ru/tmp/i3wm-idea.ogv
when I switching by i3wm hotkeys windows switched normally. When I switched by Idea hotkeys headers is switched but content of windows is the same (at the end of video above)

**What I expected instead:**
windows should switch by idea hotkeys with the same way as i3wm

**Comment by stapelberg** [comment]
Thanks for the video and log.

It looks like Idea sends a ConfigureRequest to re-stack the window, raising it to the top (i3 doesn’t handle this right now), then uses SetInputFocus to change focus, circumventing the window manager. This is why the title bars are updated (i3 gets the event and reacts accordingly), but the window is still hidden.

Let’s fix this after the 4.14 release.

**Comment by Airblader** [comment]
Someone(TM) should file a bug against Idea for this as well, though. No »normal« client has any good reason for calling SetInputFocus these days.
