### ISSUE TITLE
i3bar feature request: x/y co-ordinates relative to module output

### ISSUE THREAD

**Issue by soumya92** [i3/i3#2767]
Currently i3bar's click events provide `x` and `y` relative to the root window (https://i3wm.org/docs/i3bar-protocol.html#_click_events), which is useful if you need to open an absolutely-positioned menu/applet.

It would be useful to have `x_frac`, `y_frac` (for the lack of a better name) that are relative to the module's output, such that a click on the top-left is `{"x_frac": 0, "y_frac": 0}`, and a click on the bottom right of the output is `{"x_frac": 1, "y_frac": 1}`.

This would allow a new level of interactivity, e.g., a volume module setting the volume to `(1 - y_frac) * 100`, a media player seeking to `x_frac * length`, or a 5-day weather forecast opening directly to day `int(x_frac * 5)`

**Comment by Airblader** [comment]
The idea is OK to me, but I would prefer if we instead exposed pixel values relative to the block (`relative_x`, `relative_y`) and width and height of the block (`width`, `height`).

**Comment by soumya92** [comment]
That was my initial thought too, but I assumed that adding two keys would be preferable to adding four. I'm all in favour of providing more information in the click event 😃

**Comment by PMunch** [comment]
Maybe even better would be the x, y of the current implementation, the x, y of the block (in reference to root), and the width and height. That way you can easily calculate relative_x (block_x-click_x) and relative_y, fractions, and you could even start applications that are aligned with the block. So if I clicked eg. a date/time block I could create a calendar window aligned with the block. To keep it aligned however the user would obviously need to set a monospace font lest the bar would change below the window.
