### ISSUE TITLE
i3 always changes focus to workspace 3 when I open qutebrowser

### ISSUE THREAD

**Issue by Hund** [i3/i3#2770]
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08) (pid 5941)o abort…)
Loaded i3 config: /home/johan/.i3/config (Last modified: Fri 12 May 2017 08:25:06 PM CEST, 45775 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

**Log:**

http://logs.i3wm.org/logs/5677090456207360.bz2

**What I did:**

Open my web browser with the command `qutebrowser` via rofi or just via the terminal emulator. And as far as I know, qutebrowser is the only affected application.

**What I saw:**

qutebrowser gets launched on the current workspace, i3 then switches focus to workspace `3`. It doesn't matter on what monitor I have workspace `3`, it always changes focus to workspace 3.

And the workspace I launched qutebrowser from gets marked as *urgent* since i3 switches focus before qutebrowser has a chance of even starting.

**What I expected instead:**

For qutebrowser to be launched on the current workspace and for i3 to not change focus to workspace `3`.

**Comment by Airblader** [comment]
Could it be that when you open qutebrowser, the title includes "youtube"? You have this line in your config which tells i3 to focus workspace 3:

    05/13/2017 09:05:57 AM - config_parser.c:parse_config:267 - CONFIG(line 135): for_window [title="youtube"] workspace 3

**Comment by Hund** [comment]
It is. And now I feel pretty stupid. :( Thanks though! I forgot to remove that rule before.

**Comment by Airblader** [comment]
No worries. :-)
