### ISSUE TITLE
Strange behavior with i3bar and eve online in wine

### ISSUE THREAD

**Issue by aereaux** [i3/i3#2774]
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08) (pid 10355) abort…)
Loaded i3 config: .i3_config_tmp (Last modified: Thu 18 May 2017 01:25:19 AM CDT, 556 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5750345418407936.bz2

**What I did:**

My config file sets i3bar mode hide.  I attempted to interact with the bar by pressing the modifier key and clicking and scrolling on the bar while an eve online window running in wine was underneath the bar.  (In case it makes a difference, there were no title decorations on the eve online client window).

**What I saw:**

The eve online/wine window under the bar reacts to the click or scroll.

**What I expected instead:**

The i3bar should have reacted to the interaction, by changing workspaces or showing the tray right click menus.  This works correct with other windows I tried, mostly native applications, but I also tried Evemon in wine, which worked correctly.

**Comment by aereaux** [comment]
One interesting thing about this issue is that the eve online window does not have a title bar, even though I did not configure it this way.

**Comment by stapelberg** [comment]
My guess is that wine captures the entire input, so that i3bar won’t even get any events. I don’t think we can do anything about this.

**Comment by aereaux** [comment]
The issue appears to go away temporarily when I press $mod+f (presumably to unfullscreen the window).  It also happens way less often (the part where wine decides to go fullscreen) when I have two monitors.  Is there anything I can put in my i3 config to make sure that this window is never fullscreen?  Do you think it would be worth it to file a bug in wine, or where does the fault for this behaviour lay?  Most of my other windows when fullscreen let i3bar get events, so is there some way to prevent the window from capturing the entire input?

**Comment by stapelberg** [comment]
> Is there anything I can put in my i3 config to make sure that this window is never fullscreen?

I don’t think so.

> Do you think it would be worth it to file a bug in wine

Yes, that can’t hurt.
