### ISSUE TITLE
i3 freezes when sending `i3-ipc00000001` to the socket

### ISSUE THREAD

**Issue by awalgarg** [i3/i3#2775]
Output of `i3 --moreversion 2>&- || i3 --version`:

i3 version 4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5687423342215168.bz2

**What I did:**

sending the string `i3-ipc00000001` to the i3 socket

**What I saw:**

i3 freezes. opening new windows doesn't work. current window continues to respond for a while.

the i3 process takes 100%  cpu after this and all hell breaks lose.

**What I expected instead:**

an error message in return

edit: stracing the running i3 process shows that i3 is constantly reading an empty string from the opened socket after this. :|

**Comment by Airblader** [comment]
See #1876. We expect IPC clients to behave properly.

**Comment by Airblader** [comment]
Closing due to above-mentioned reason and no further feedback.
