### ISSUE TITLE
Resizing vertically corrupts window above

### ISSUE THREAD

**Issue by benfrankel** [i3/i3#2776]
Output of `i3 --moreversion 2>&- || i3 --version`:

```Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08) (pid 1374)o abort…)
Loaded i3 config: /home/ben-frankel/.config/i3/config (Last modified: Thu 18 May 2017 05:01:32 PM CDT, 3002 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5631639635886080.bz2

**What I did:**

1. Create 3 terminals vertically.
2. Resize the bottom terminal as follows:
    a. Click its title bar.
    b. Bring the blue line up until it's just under the middle terminal's menu bar.

**What I saw:**

The middle terminal is now in a corrupted state. If I float it and resize it for example, it will look [like this](http://i.imgur.com/5a0psxo.png). It is possible to close the window using Mod+Shift+q, but I am not aware of any way to uncorrupt the window rather than close it.

**What I expected instead:**

Trying to resize the bottom terminal too close to the middle terminal should instead:
- snap it to the greatest allowable height, or
- push the middle terminal up, or
- something else, as long as the corruption does not occur.

**Comment by Airblader** [comment]
I'm like 99% sure we have an open issue for this already, but I can't find it right now. Either way, yes, this should be fixed. In this case it makes sense to not allow the window to become too small, but this solution doesn't work in the case of just opening a lot of windows – eventually we need to decide what should happen when we run out of space.

Thus, I think the proper solution is to allow the window to become small, but ensure the corruption doesn't happen.
