### ISSUE TITLE
Workspaces stay on inactive (disconnected) output?

### ISSUE THREAD

**Issue by fd0** [i3/i3#2786]
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08) (pid 1019)o abort…)
Loaded i3 config: /home/fd0/.i3/config (Last modified: Mi 19 Apr 2017 19:27:57 CEST, 3285728 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: /usr/bin/i3
```

URL to a logfile as per http://i3wm.org/docs/debugging.html:

(apologies, this is from a restarted instance, I thought that this may resolve the problem)
http://logs.i3wm.org/logs/5733423247261696.bz2

**What I did:**

Undock from the docking station, so outputs DP3-1 und DP3-2 (connected to external screens) disconnect. eDP1 is the only active screen.

**What I saw:**

I'm on workspace 4. Pressing Mod4-1 to switch to the first workspace only makes the small `4` in the bar switch to the inactive color. No windows are hidden/shown.

In contrast to #2657, xrandr sees the outputs as disconnected:
<details>

```
Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 32767 x 32767
eDP1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 310mm x 170mm
   1920x1080     60.01*+
   1400x1050     59.98  
   1600x900      60.00  
   1280x1024     60.02  
   1280x960      60.00  
   1368x768      60.00  
   1280x720      60.00  
   1024x768      60.00  
   1024x576      60.00  
   960x540       60.00  
   800x600       60.32    56.25  
   864x486       60.00  
   640x480       59.94  
   720x405       60.00  
   640x360       60.00  
DP1 disconnected (normal left inverted right x axis y axis)
DP2 disconnected (normal left inverted right x axis y axis)
DP3 disconnected (normal left inverted right x axis y axis)
DP3-1 disconnected primary (normal left inverted right x axis y axis)
DP3-2 disconnected (normal left inverted right x axis y axis)
DP3-3 disconnected (normal left inverted right x axis y axis)
HDMI1 disconnected (normal left inverted right x axis y axis)
HDMI2 disconnected (normal left inverted right x axis y axis)
HDMI3 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
```

</details>

**What I expected instead:**

Workspace 1 is shown.

Other Information
--------------------

 * i3 still thinks that DP3-1 and DP3-2 are active:
<details>

```
$ i3-msg -t get_workspaces | jq .
[
  {
    "num": 1,
    "name": "1",
    "visible": false,
    "focused": false,
    "rect": {
      "x": 0,
      "y": 0,
      "width": 2560,
      "height": 1440
    },
    "output": "DP3-1",
    "urgent": false
  },
  {
    "num": 2,
    "name": "2",
    "visible": false,
    "focused": false,
    "rect": {
      "x": 0,
      "y": 0,
      "width": 2560,
      "height": 1440
    },
    "output": "DP3-1",
    "urgent": false
  },
  {
    "num": 3,
    "name": "3",
    "visible": true,
    "focused": false,
    "rect": {
      "x": 0,
      "y": 0,
      "width": 2560,
      "height": 1440
    },
    "output": "DP3-1",
    "urgent": false
  },
  {
    "num": 4,
    "name": "4",
    "visible": true,
    "focused": true,
    "rect": {
      "x": 0,
      "y": 0,
      "width": 1920,
      "height": 1055
    },
    "output": "eDP1",
    "urgent": false
  },
  {
    "num": 7,
    "name": "7",
    "visible": false,
    "focused": false,
    "rect": {
      "x": 2560,
      "y": 0,
      "width": 1600,
      "height": 1200
    },
    "output": "DP3-2",
    "urgent": false
  },
  {
    "num": 10,
    "name": "10",
    "visible": true,
    "focused": false,
    "rect": {
      "x": 2560,
      "y": 0,
      "width": 1600,
      "height": 1200
    },
    "output": "DP3-2",
    "urgent": false
  }
]
```

</details>
 
 * restarting i3 does not help, the workspaces stay on the inactive outputs.
 * DP3-1 is still marked primary, removing the flag (with `xrandr --output eDP1 --primary`) changes nothing

Is there anything else I can do?

**Comment by Airblader** [comment]
There's a difference between disconnected and disabled. You need to actually turn the output off in xrandr. 

Do the workspaces move when you execute `xrandr --off` after unplugging it?

**Comment by fd0** [comment]
Good idea, but it doesn't change anything:
```
$ xrandr --output DP3-1 --off
$ xrandr --output DP3-2 --off
$ i3-msg -t get_workspaces | jq .
[...]
  {
    "num": 10,
    "name": "10",
    "visible": true,
    "focused": false,
    "rect": {
      "x": 2560,
      "y": 0,
      "width": 1600,
      "height": 1200
    },
    "output": "DP3-2",
    "urgent": false
  }
```

Restarting doesn't change anything.

**Comment by fd0** [comment]
It looks like i3 doesn't even see the outputs any more:

<details>

```
$ i3-msg -t get_outputs | jq .
[
  {
    "name": "eDP1",
    "active": true,
    "primary": true,
    "rect": {
      "x": 0,
      "y": 0,
      "width": 1920,
      "height": 1080
    },
    "current_workspace": "4"
  },
  {
    "name": "xroot-0",
    "active": false,
    "primary": false,
    "rect": {
      "x": 0,
      "y": 0,
      "width": 1920,
      "height": 1080
    },
    "current_workspace": null
  },
  {
    "name": "DP1",
    "active": false,
    "primary": false,
    "rect": {
      "x": 0,
      "y": 0,
      "width": 0,
      "height": 0
    },
    "current_workspace": null
  },
  {
    "name": "DP2",
    "active": false,
    "primary": false,
    "rect": {
      "x": 0,
      "y": 0,
      "width": 0,
      "height": 0
    },
    "current_workspace": null
  },
  {
    "name": "DP3",
    "active": false,
    "primary": false,
    "rect": {
      "x": 0,
      "y": 0,
      "width": 0,
      "height": 0
    },
    "current_workspace": null
  },
  {
    "name": "DP3-3",
    "active": false,
    "primary": false,
    "rect": {
      "x": 0,
      "y": 0,
      "width": 0,
      "height": 0
    },
    "current_workspace": null
  },
  {
    "name": "HDMI1",
    "active": false,
    "primary": false,
    "rect": {
      "x": 0,
      "y": 0,
      "width": 0,
      "height": 0
    },
    "current_workspace": null
  },
  {
    "name": "HDMI2",
    "active": false,
    "primary": false,
    "rect": {
      "x": 0,
      "y": 0,
      "width": 0,
      "height": 0
    },
    "current_workspace": null
  },
  {
    "name": "HDMI3",
    "active": false,
    "primary": false,
    "rect": {
      "x": 0,
      "y": 0,
      "width": 0,
      "height": 0
    },
    "current_workspace": null
  },
  {
    "name": "VIRTUAL1",
    "active": false,
    "primary": false,
    "rect": {
      "x": 0,
      "y": 0,
      "width": 0,
      "height": 0
    },
    "current_workspace": null
  }
]
```

</details>

**Comment by Airblader** [comment]
So to clarify, after you ran `xrandr --auto` the workspaces haven't moved and if you reconnect (and turn on) the output they are still on that output again?

**Comment by fd0** [comment]
Exactly. Upon undocking, I basically run: `xrandr --output DP3-2 --off --output DP3-1 --off --output eDP1 --auto`, maybe in several steps.

**Comment by fd0** [comment]
If it's valuable I can try to reproduce it today. Anything I should pay particular attention to?

**Comment by Airblader** [comment]
Nothing particular, no. We'll have to debug and find out why i3 doesn't react appropriately. Unfortunately I don't have the time to do this myself right now.

**Comment by fd0** [comment]
I just tried it once yesterday, I was unable to reactivate the outputs on the docking station. I suspect that there may be a bug in the kernel/X subsystem. I'm not sure how to proceed, please let me know if there's anything I can do!

**Comment by Airblader** [comment]
Yeah, it does sound like that; and wouldn't surprise me, docking stations seem to be a common source of bugginess.

Capturing the output of `xrandr -event randr` while doing all of this might be somewhat interesting.

You could also try updating to the current `next` branch where we switched to the RandR 1.5 protocol. Perhaps it fixes the issue?

**Comment by fd0** [comment]
I'll try the next branch and report back.

My `xrandr` command does not have an `-event` parameter, do I need a patch for that? Or is it a different tool?

**Comment by fd0** [comment]
Seems to work with the `next` branch, I'll try it for a few days.

**Comment by Airblader** [comment]
I meant `xev -event randr`, sorry. :-)

**Comment by fd0** [comment]
Ran `xev` with `4.13-111-ga7e8c4dd` and a slightly newer kernel while undocking, looks good so far:

<details>

xev -event randr 
Outer window is 0x3200001, inner window is 0x3200002

RRScreenChangeNotify event, serial 25, synthetic NO, window 0x3200001,
    root 0xf8, timestamp 2271599, config_timestamp 20147548
    size_index 65535, subpixel_order SubPixelUnknown
    rotation RR_Rotate_0
    width 4160, height 1440, mwidth 978, mheight 338

RRNotify event, serial 25, synthetic NO, window 0x3200001,
    subtype XRROutputChangeNotifyEvent
    output DP3-1, crtc 63, mode 2560x1440 (2560x1440)
    rotation RR_Rotate_0
    connection RR_Connected, subpixel_order SubPixelUnknown

RRNotify event, serial 25, synthetic NO, window 0x3200001,
    subtype XRROutputChangeNotifyEvent
    output DP3-2, crtc 64, mode 1600x1200 (1600x1200)
    rotation RR_Rotate_0
    connection RR_Connected, subpixel_order SubPixelUnknown

RRNotify event, serial 25, synthetic NO, window 0x3200001,
    subtype XRROutputChangeNotifyEvent
    output DP3-3, crtc None, mode None
    rotation RR_Rotate_0
    connection RR_Disconnected, subpixel_order SubPixelUnknown

RRNotify event, serial 25, synthetic NO, window 0x3200001,
    subtype XRROutputPropertyChangeNotifyEvent
    output DP3-1, property EDID, timestamp 20147548, state Delete

RRNotify event, serial 25, synthetic NO, window 0x3200001,
    subtype XRROutputPropertyChangeNotifyEvent
    output DP3-2, property EDID, timestamp 20147548, state Delete

RRScreenChangeNotify event, serial 25, synthetic NO, window 0x3200001,
    root 0xf8, timestamp 2271599, config_timestamp 20147781
    size_index 65535, subpixel_order SubPixelUnknown
    rotation RR_Rotate_0
    width 4160, height 1440, mwidth 978, mheight 338

RRNotify event, serial 25, synthetic NO, window 0x3200001,
    subtype XRROutputChangeNotifyEvent
    output DP3-1, crtc 63, mode 2560x1440 (2560x1440)
    rotation RR_Rotate_0
    connection RR_Disconnected, subpixel_order SubPixelUnknown

RRNotify event, serial 25, synthetic NO, window 0x3200001,
    subtype XRROutputChangeNotifyEvent
    output DP3-2, crtc 64, mode 1600x1200 (1600x1200)
    rotation RR_Rotate_0
    connection RR_Disconnected, subpixel_order SubPixelUnknown

RRScreenChangeNotify event, serial 43, synthetic NO, window 0x3200001,
    root 0xf8, timestamp 2271599, config_timestamp 20147781
    size_index 65535, subpixel_order SubPixelUnknown
    rotation RR_Rotate_0
    width 4160, height 1440, mwidth 978, mheight 338

RRNotify event, serial 43, synthetic NO, window 0x3200001,
    subtype XRRCrtcChangeNotifyEvent
    crtc 64, mode None, rotation RR_Rotate_0
    x 0, y 0, width 0, height 0

RRNotify event, serial 43, synthetic NO, window 0x3200001,
    subtype XRROutputChangeNotifyEvent
    output DP3-2, crtc None, mode None
    rotation RR_Rotate_0
    connection RR_Disconnected, subpixel_order SubPixelUnknown

RRScreenChangeNotify event, serial 43, synthetic NO, window 0x3200001,
    root 0xf8, timestamp 20147889, config_timestamp 20148198
    size_index 65535, subpixel_order SubPixelUnknown
    rotation RR_Rotate_0
    width 4160, height 1440, mwidth 978, mheight 338

RRNotify event, serial 43, synthetic NO, window 0x3200001,
    subtype XRRCrtcChangeNotifyEvent
    crtc 63, mode None, rotation RR_Rotate_0
    x 0, y 0, width 0, height 0

RRNotify event, serial 43, synthetic NO, window 0x3200001,
    subtype XRROutputChangeNotifyEvent
    output DP3-1, crtc 63, mode None
    rotation RR_Rotate_0
    connection RR_Disconnected, subpixel_order SubPixelUnknown

RRNotify event, serial 43, synthetic NO, window 0x3200001,
    subtype XRROutputChangeNotifyEvent
    output DP3-2, crtc None, mode None
    rotation RR_Rotate_0
    connection RR_Disconnected, subpixel_order SubPixelUnknown

RRScreenChangeNotify event, serial 43, synthetic NO, window 0x3200001,
    root 0xf8, timestamp 20147889, config_timestamp 20148198
    size_index 65535, subpixel_order SubPixelUnknown
    rotation RR_Rotate_0
    width 2560, height 1440, mwidth 600, mheight 338

RRScreenChangeNotify event, serial 51, synthetic NO, window 0x3200001,
    root 0xf8, timestamp 20147889, config_timestamp 20148198
    size_index 65535, subpixel_order SubPixelUnknown
    rotation RR_Rotate_0
    width 1920, height 1080, mwidth 450, mheight 253

RRScreenChangeNotify event, serial 51, synthetic NO, window 0x3200001,
    root 0xf8, timestamp 20147889, config_timestamp 20148198
    size_index 65535, subpixel_order SubPixelUnknown
    rotation RR_Rotate_0
    width 1920, height 1080, mwidth 450, mheight 253

RRNotify event, serial 51, synthetic NO, window 0x3200001,
    subtype XRRCrtcChangeNotifyEvent
    crtc 64, mode 1920x1080, rotation RR_Rotate_0
    x 0, y 0, width 1920, height 1080

RRNotify event, serial 51, synthetic NO, window 0x3200001,
    subtype XRROutputChangeNotifyEvent
    output eDP1, crtc 64, mode 1920x1080 (1920x1080)
    rotation RR_Rotate_0
    connection RR_Connected, subpixel_order SubPixelUnknown

RRScreenChangeNotify event, serial 54, synthetic NO, window 0x3200001,
    root 0xf8, timestamp 20149047, config_timestamp 20148198
    size_index 65535, subpixel_order SubPixelUnknown
    rotation RR_Rotate_0
    width 1920, height 1080, mwidth 406, mheight 228

RRScreenChangeNotify event, serial 54, synthetic NO, window 0x3200001,
    root 0xf8, timestamp 20152536, config_timestamp 20157920
    size_index 0, subpixel_order SubPixelUnknown
    rotation RR_Rotate_0
    width 1920, height 1080, mwidth 406, mheight 228

RRNotify event, serial 54, synthetic NO, window 0x3200001,
    subtype XRRCrtcChangeNotifyEvent
    crtc 63, mode None, rotation RR_Rotate_0
    x 0, y 0, width 0, height 0

RRNotify event, serial 54, synthetic NO, window 0x3200001,
    subtype XRROutputChangeNotifyEvent
    output DP3-1, crtc None, mode None
    rotation RR_Rotate_0
    connection RR_Disconnected, subpixel_order SubPixelUnknown

</details>

**Comment by fd0** [comment]
Works good so far, although I occasionally run into #2657 again (or at least it looks like it) on return to the docking station: The i3bar is only displayed on one of the monitors. Restarting i3 in place fixes that.

**Comment by Airblader** [comment]
Thanks for the feedback! Since it works on the `next` branch I'm going to close this. We'll have to fix #2657 in #2657. :-)

**Comment by fd0** [comment]
I'm sorry, I must've mixed something up. What I experienced was that upon returning to the docking station (different situation than #2657) i3bar is only displayed on one output. I pointed to #2657 without looking up what that issue was about.

Is there an issue for it already? I remember there was, but I'm unable to find it...

**Comment by Airblader** [comment]
@fd0 If you can't find one just open a new one. :-)

**Comment by fd0** [comment]
Ok, will do the next time this happens (then I can also supply a log). Thanks!

**Comment by fd0** [comment]
It happened again, see #2815.
