### ISSUE TITLE
frozen bar when switching from a fullscreen window to a different workspace

### ISSUE THREAD

**Issue by klloe** [i3/i3#2790]
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08) (pid 844)to abort…)
Loaded i3 config: /home/manu/.config/i3/config (Last modified: Wed 24 May 2017 07:12:21 AM CEST, 440970 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

URL to a logfile as per http://i3wm.org/docs/debugging.html: 
http://logs.i3wm.org/logs/5646535253557248.bz2

**What I did:**

1. Set a window to fullscreen mode
2. Switch to a non-empty workspace

**What I saw:**

i3bar won't refresh anymore, which means all items (clock, battery) freeze and won't update their values, The only workaround so far is to restart i3, toggle fullscreen or switch to another workspace (with no fullscreen window) again.

**What I expected instead:**

i3bar to refresh as usual.

**Comment by Airblader** [comment]
I cannot reproduce this. Are you using i3status for i3bar? Or something else?

**Comment by klloe** [comment]
i3pystatus

**Comment by Airblader** [comment]
Can you reproduce this with i3status?

**Comment by klloe** [comment]
yes, same issue with i3status

here is my config: http://ix.io/vtb

**Comment by klloe** [comment]
@Airblader I just tried again, this only happend if you switch to a non-empty workspace.

**Comment by Airblader** [comment]
I still cannot reproduce it. Do you have anything in your setup that seems worth mentioning, like scripts that cause signals to be sent to i3bar or something like that?

**Comment by stapelberg** [comment]
I can reproduce this.

**Comment by stapelberg** [comment]
I think the problem is that i3bar doesn’t receive the `VisibilityNotify` event, but I’m not yet sure why.
