### ISSUE TITLE
I3WM becomes unresponsive when spice is started attempting to connect to a nonexistent spice session.

### ISSUE THREAD

**Issue by BurningSmile** [i3/i3#2801]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08) (pid 1171)o abort…)
Loaded i3 config: /home/david/.config/i3/config (Last modified: Tue 30 May 2017 02:36:48 PM MDT, 277081 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

Logfile

http://logs.i3wm.org/logs/5693703389708288.bz2

**What I did:**
When launching spice on a different workspace then switching to the workspace it is assigned to it crashes i3wm, No hotkeys work, cannot click on anything, cpu on one thread spikes to 100%. The session must be restarted from a different TTY to be resolved. This has been tested with a spice alias with connect commands, rofi, and spice with no connect commands.

This starts spices connect window on workspace 9. If the VM is running then it connects without issue. However if it is unable to connect and displays the connect window asking to be filled out it will crash i3 after switching to that workspace. (Please note that the connect window is not tiled. I have tested enabling floating and it had no effect.)

**What I saw:**

i3WM  becomes unresponsive and must be restarted from a different tty.

**What I expected instead:**
i3WM should not crash and should allow the continue button to be pressed to begin the spice session. The same issue has not been able to be reproduced under gnome or plasma. 

Steps to reproduce

Attempt to start the spice client then switch to the assigned workspace.

My Configuration file for i3 can be found below.

https://github.com/BurningSmile/dotfiles/blob/master/i3/config

**Comment by Airblader** [comment]
I haven't looked at the log yet but provided the log isn't spamming in the end the next step would be to attach gdb to i3 and see where exactly it is freezing up.

**Comment by BurningSmile** [comment]
Hello,

Here is some more information I gathered when it happened agian today.

Opened a spice connection window with the incorrect port by accident. when switching to it it locked up i3wm. 

Switching to another tty to go kill the spice connect window i see i3 using 100% of a thread/cpu. running 
i3 -a --restart /run/user/1000/i3/restart-state.1282

Killing the spice window process and switching back to the i3 tty. There is now a black space where the spice connect window was. I3 is still unresponsive to any kind of input. [mouse on polybar or open windows or keyboard input]

Switching back to the tty with htop running after a while it returns to a normal i3 process. Switching back to the tty with i3 running it still locked up.

As for attaching a gdb log ill get that if you think its needed.

Thanks.

**Comment by psychon** [comment]
> As for attaching a gdb log ill get that if you think its needed.

My 5c: I think it's needed.

**Comment by stapelberg** [comment]
Please supply a gdb log.

Also, the i3 logfile you provided doesn’t seem to contain anything Spice-related at all? I don’t see you starting it up, for example. Note that you can dump the i3 log even when i3 hangs.

Also note that a minimal i3 log, i.e. starting with the default i3 config, would be much more helpful.

Thanks!

**Comment by stapelberg** [comment]
Can’t reproduce this. Assigning spicy to a different workspace results in it starting up just fine for me.

**Comment by BurningSmile** [comment]
The issue seems to have cleared itself up with no rhyme or reason. I forgot to close this issue, sorry.
