### ISSUE TITLE
konsole freezes when I press tab for few seconds and then resumes

### ISSUE THREAD

**Issue by govindx7c6** [i3/i3#2806]
Output of `i3 --moreversion 2>&- || i3 --version`:
[gvaradar@cisco ~]$ i3 --moreversion 2>&- || i3 --version

Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08) (pid 22534) abort…)
Loaded i3 config: /home/gvaradar/.i3/config (Last modified: Thu 08 Jun 2017 11:41:43 AM PDT, 2522 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3-with-/i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5659569942429696.bz2

**What I did:**
Open konsole(mod + return), press tab
nm-applet freezes too when I click on the icon. 

**What I saw:**
konsole freezes for 25 seconds and then resumes. nm-applet also freezes for sometime and then resumes.

**What I expected instead:**
Not freeze.

**Comment by awrush** [comment]
I can confirm the problem. Same i3 version here.

**Comment by Airblader** [comment]
What makes you think this is an i3 problem? Is i3 still responsive? Does it work with a previous i3 version? Have you tested it against other window managers?

Generally i3 being at fault for only a client freezing is somewhat unlikely since i3 is not responsible for keeping the application responsive.

**Comment by govindx7c6** [comment]
On 06/12/2017 05:14 AM, Ingo Bürk wrote:
>
> What makes you think this is an i3 problem?
>
I do not know, we need to start debugging somewhere.
The client freeze does not happen on gnome, kde-plasma.
Its happening only on i3. This is what made me think this is i3 problem.
>
> Is i3 still responsive?
>
Yes, I can open other other windows, move it around. Only the particular 
client window(konsole/ nm-applet)
window freezes.
>
> Does it work with a previous i3 version?
>
I will have to check.
>
> Have you tested it against other window managers?
>
Yes, I do not see any problem on gnome/kde-plasma.
>
> Generally i3 being at fault for only a client freezing is somewhat 
> unlikely since i3 is not responsible for keeping the application 
> responsive.
>
>

**Comment by Airblader** [comment]
Do you have any other instance of Konsole open on another workspace? I remember Konsole having some problems in this area. Does it also happen if it's the *only* Konsole window?

**Comment by govindx7c6** [comment]
On 06/12/2017 06:48 AM, Ingo Bürk wrote:
>
> Do you have any other instance of Konsole open on another workspace? I 
> remember Konsole having some problems in this area. Does it also 
> happen if it's the /only/ Konsole window?
>
Yes and no. The issue occurs irrespective of konsole open in other 
workspace.
It happens on konsole window and nm-applet. I cannot say "only" though.
konsole is my most used app. I do not see the issue on firefox, 
thunderbird, xfce4-terminal.

I am running arch linux. Last update of i3 was on 2016-11-15. So I do 
not think
downgrade on i3 will conclude anything.

However, I downgraded all my packages to 2017-05-25 
(https://wiki.archlinux.org/index.php/Arch_Linux_Archive#How_to_restore_all_packages_to_a_specific_date)
and I do not see the issue.

I am in process of finding out which package upgrade broke this.
This will take some time. I will update one I have enough info.

Thanks

**Comment by govindx7c6** [comment]
update on 2017/06/02 broke this. Following packages were updated on that day
`extra/bluedevil                      1:5.9.5-1       1:5.10.0-1        0.05 MiB
extra/breeze                         5.9.5-1         5.10.0-1        -19.12 MiB
extra/breeze-gtk                     5.9.5-1         5.10.0-1          0.47 MiB
core/diffutils                       3.5-1           3.6-1             0.06 MiB
extra/dkms                           2.3-2           2.4.0-1           0.00 MiB
extra/drkonqi                        5.9.5.1-1       5.10.0-3          0.02 MiB
core/file                            5.30-1          5.31-1            0.04 MiB
community/haskell-conduit-extra      1.1.16-4        1.1.16-5          0.01 MiB
community/haskell-network            2.6.3.1-1       2.6.3.2-1        -0.01 MiB
community/haskell-streaming-commons  0.1.17-3        0.1.17-4          0.01 MiB
community/haskell-tagstream-conduit  0.5.5.3-70      0.5.5.3-71        0.00 MiB
community/haskell-xml-conduit        1.4.0.4-12      1.4.0.4-13        0.02 MiB
extra/kactivitymanagerd              5.9.5-1         5.10.0-1          0.01 MiB
extra/kde-cli-tools                  5.9.5-1         5.10.0-1         -0.02 MiB
extra/kde-gtk-config                 5.9.5-1         5.10.0-1          0.01 MiB
extra/kdecoration                    5.9.5-1         5.10.0-1          0.01 MiB
extra/kdeplasma-addons               5.9.5-1         5.10.0-1         -0.67 MiB
extra/kgamma5                        5.9.5-1         5.10.0-1          0.00 MiB
extra/khotkeys                       5.9.5-1         5.10.0-1          0.10 MiB
extra/kinfocenter                    5.9.5-1         5.10.0-1          0.01 MiB
extra/kmenuedit                      5.9.5-1         5.10.0-1          0.01 MiB
extra/knetattach                     5.9.5-1         5.10.0-1          0.00 MiB
extra/kscreen                        5.9.5-1         5.10.0-1          0.04 MiB
extra/kscreenlocker                  5.9.5-1         5.10.0-1          0.02 MiB
extra/ksshaskpass                    5.9.5-1         5.10.0-1          0.00 MiB
extra/ksysguard                      5.9.5-1         5.10.0-1          0.02 MiB
extra/kuiserver                      5.9.5.1-1       5.10.0-3          0.00 MiB
extra/kwallet-pam                    5.9.5-1         5.10.0-1          0.00 MiB
extra/kwayland-integration           5.9.5-1         5.10.0-1          0.01 MiB
extra/kwin                           5.9.5-1         5.10.0-1          0.81 MiB
extra/kwrited                        5.9.5-1         5.10.0-1          0.00 MiB
extra/libgusb                        0.2.9-3         0.2.10-1          0.06 MiB
extra/libkscreen                     5.9.5-1         5.10.0-1         -0.05 MiB
extra/libksysguard                   5.9.5-1         5.10.0-1         -0.06 MiB
extra/libqalculate                   0.9.11-1        0.9.12-1         -0.03 MiB
core/libtasn1                        4.10-1          4.12-1            0.00 MiB
extra/milou                          5.9.5-1         5.10.0-1          0.00 MiB
core/nano                            2.8.2-1         2.8.4-1           0.00 MiB
core/ncurses                         6.0+20170429-1  6.0+20170527-1    0.00 MiB
extra/oxygen                         5.9.5-1         5.10.0-1          0.10 MiB
extra/plasma-desktop                 5.9.5-1         5.10.0-1          0.21 MiB
extra/plasma-integration             5.9.5-1         5.10.0-1          0.02 MiB
extra/plasma-nm                      5.9.5-1         5.10.0-1          0.19 MiB
extra/plasma-pa                      5.9.5-1         5.10.0-1          0.01 MiB
extra/plasma-sdk                     5.9.5-1         5.10.0-1         -1.23 MiB
extra/plasma-workspace               5.9.5.1-1       5.10.0-3          0.18 MiB
extra/plasma-workspace-wallpapers    5.9.5-1         5.10.0-1          0.00 MiB
extra/polkit-kde-agent               5.9.5-1         5.10.0-1          0.00 MiB
extra/poppler                        0.54.0-1        0.55.0-1          0.02 MiB
extra/poppler-glib                   0.54.0-1        0.55.0-1          0.00 MiB
extra/poppler-qt4                    0.54.0-1        0.55.0-1          0.00 MiB
extra/poppler-qt5                    0.54.0-1        0.55.0-1          0.00 MiB
extra/powerdevil                     5.9.5-1         5.10.0-1          0.03 MiB
extra/python-setuptools              1:36.0.0-1      1:36.0.1-1        0.00 MiB
extra/python2-setuptools             1:36.0.0-1      1:36.0.1-1        0.00 MiB
extra/sddm-kcm                       5.9.5-1         5.10.0-1          0.01 MiB
community/smplayer                   17.5.0-1        17.6.0-1          0.01 MiB
core/sqlite                          3.18.0-1        3.19.2-2         -0.02 MiB
core/sudo                            1.8.20.p1-1     1.8.20.p2-1       0.00 MiB
extra/systemsettings                 5.9.5-1         5.10.0-1          0.01 MiB
extra/user-manager                   5.9.5-1         5.10.0-1          0.01 MiB`

@Airblader Can you tell me relevant packages what could affect this issue? I will test upgrade one by one unless you see something obvious.

**Comment by govindx7c6** [comment]
upgrade of plasma-workspace from 5.9.5.1-1 to 5.10.0-3 causes this issue. @Airblader you can close this bug if you want. Looks like this has something to do with plasma-workspace. But I dont understand why this occurs only on i3. I do not see this issue on gnome or plasma. I thought nm-applet has nothing to do with plasma, but it freezes too.

**Comment by Airblader** [comment]
Are you reporting this against plasma? If so, can you share the link to the report here as well?

5.9.5.1-1 to 5.10.0-3 also doesn't sound like too much of a difference, perhaps looking at the changes in those versions could be helpful.

**Comment by govindx7c6** [comment]
This looks similar to https://bugs.kde.org/show_bug.cgi?id=381115

**Comment by Airblader** [comment]
Yes, looks similar enough to me. Let's close here for now. If something does come up pointing to a problem in i3 we can reopen. Thanks!

**Comment by awrush** [comment]
I've git-bisect'ed it down to this commit here: [https://phabricator.kde.org/D5012](https://phabricator.kde.org/D5012)

I don't think we can ask the KDE guys to revert their commit since it seems to be working perfectly fine for KDE, Gnome and any other environment/window manager in combination with plasma-workspace - except i3, as @govindx7c6 already pointed out.

It looks like some kind of DBus issue. Since I've got no experience with i3's DBus integration, maybe someone can shed some light on this, although, of course, it's still not 100% clear that this is an exclusive i3 problem.

**Comment by Airblader** [comment]
Thanks for the bisect!

> Since I've got no experience with i3's DBus integration

Me either, because i3 doesn't have one.

**Comment by awrush** [comment]
Alright then.

It looks like aforementioned commit forces you to have a service running that implements org.freedesktop.Notifications.

When running any Notifications service (e.g. https://github.com/mk-fg/notification-thing), all the freezes/hangs disappear immediately for as long as the service is active.

I could go on researching this further but I suppose the summary of it is: run a org.freedesktop.Notifications service or remove plasma-workspace.

**Comment by Airblader** [comment]
I would call this a bug in KDE.

**Comment by awrush** [comment]
Well, at least it has nothing to do with i3 but I'm hesitating to call this a KDE bug. It's not unlikely that this is actually intended behavior since KDE/Plasma comes with its own Notifications service AFAIK. It only affects people who want to use certain parts of the framework and not the whole KDE package/environment.

It's not pretty in any case.

Thanks for the help with this!
