### ISSUE TITLE
i3bar in hide mode covers dmenu

### ISSUE THREAD

**Issue by maekclena** [i3/i3#2809]
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08) (pid 2739)o abort…)
Loaded i3 config: /home/erwan/.config/i3/config (Last modified: Sun 11 Jun 2017 06:31:26 PM CEST, 513 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

URL to a logfile as per http://i3wm.org/docs/debugging.html:

[http://logs.i3wm.org/logs/5633951804686336.bz2](http://logs.i3wm.org/logs/5633951804686336.bz2)

**What I did:**

1. Set i3bar to hide mode
2. Press and maintain the modifier key to make i3bar appear
3. Press 'd' to make dmenu appear
4. Wait until i3bar refreshes i3status (interval in i3status configuration file)

You can also set hidden_state to show instead of maintaining the modifier key.

**What I saw:**

I3bar covers dmenu while dmenu still has focus

**What I expected instead:**

dmenu staying over i3bar

N.B.: I have had similar issues with i3lock where the lock screen would disappear and show the desktop while still maintaining focus but I haven't been able to reproduce it consistently.

**Comment by Airblader** [comment]
Dmenu opens an override redirect window and thus i3 is not responsible for this window at all. You should open this as a bug against dmenu and ask them to stack the window back on top when it gets covered (if that's the behavior they intend).
