### ISSUE TITLE
Command `workspace number` does not behave as expected

### ISSUE THREAD

**Issue by jmsdvl** [i3/i3#2823]
Output of `i3 --moreversion 2>&- || i3 --version`:
```
Binary i3 version:  4.13-non-git © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13-non-git (pid 2064)l-c to abort…)
Loaded i3 config: /home/jms/.config/i3/config (Last modified: Wed 28 Jun 2017 02:50:44 PM CDT, 1091 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3-with-/i3
```
URL to a logfile as per http://i3wm.org/docs/debugging.html:
http://logs.i3wm.org/logs/5680423082393600.bz2

**What I did:**
In my configuration, I set up a series of named workspaces, for example:
```
set $ws_spotify 3: spotify
bindsym $mod+3 workspace $ws_spotify
```

In a terminal on workspace 1, I execute `i3-msg "workspace number 3"`. 

**What I saw:**
I am taken to a workspace named 3, distinct from the workspace I defined in my config. 

**What I expected instead:**
I expect that I will be taken to a workspace numbered 3 and named `spotify`. 

_However_, if I already have a window open on workspace 3, I _am_ correctly taken to workspace 3.  So in other words, I don't think the mapping from workspace indices to names works correctly - or, if this is intended behavior, I find it extremely counter-intuitive.

Also, sometimes after executing `i3-msg "workspace number N` from a terminal in one workspace, my screen changes to workspace number N (whatever i3 thinks that is) but commands are still executed in the original workspace - i.e., `<mod-Enter>` will open a new terminal in the first workspace, not the one on my screen.  But I haven't been able to reliably reproduce this behavior, so I'm mentioning it here in passing instead of creating a new ticket.

**Comment by Airblader** [comment]
This is the intended behavior and also described in the userguide. To make what you want to do work you should use

    workspace number "3: spotify"

See userguide 6.7.1:

> […] To combine both commands you can use workspace number 1: mail to specify a default name if there’s currently no workspace starting with a "1".
