### ISSUE TITLE
Mouse binding don't work *at all*.

### ISSUE THREAD

**Issue by dnfm** [i3/i3#2824]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.13-121-g2a918169 (2017-06-23, branch "git-r3/x11-wm/i3/0/__main__") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13-121-g2a918169 (2017-06-23, branch "git-r3/x11-wm/i3/0/__main__") (pid 18988)
Loaded i3 config: /home/jwheeler/.config/i3/config (Last modified: Sun 02 Jul 2017 03:54:41 PM EDT, 601 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5753952654065664.bz2

**What I did:**

I tried right clicking on the title of a window.

From my config file (which is copy/pasted from the i3 configs:

bindsym --release button3 kill

**What I saw:**

Not a thing.

**What I expected instead:**

The window whose title I right clicked would be killed.

I'm running the latest git on my gentoo box since I was experiencing the same issue with the latest stable.

This is on my laptop, which does not have xbindkeys running, nor does it have a numlock button at all (it's a small laptop).

And the output from xev when I right click on its title bar:

ButtonPress event, serial 33, synthetic NO, window 0x1400001,
    root 0xd5, subw 0x0, time 455998124, (354,-1), root:(998,19),
    state 0x10, button 3, same_screen YES

ButtonRelease event, serial 33, synthetic NO, window 0x1400001,
    root 0xd5, subw 0x0, time 455998212, (354,-1), root:(998,19),
    state 0x410, button 3, same_screen YES

**Comment by Airblader** [comment]
> From my config file (which is copy/pasted from the i3 configs:
> 
>     bindsym --release button3 kill

According to the log, no such line exists. What you do have, instead, is

> 02/07/17 04:03:43 PM - config_parser.c:parse_config:267 - CONFIG(line 132): bindsym --release button2 kill

So perhaps you changed it and forgot to reload the config? Or edited the wrong config?

**Comment by dnfm** [comment]
No, that is academic.  I apologise since I guess I messed with my config more before reporting the bug.

I update the config again to bindsym --release button3 kill and it still does squat.  NO mouse bindings work at all anywhere.

**Comment by Airblader** [comment]
Can you please provide a minimal log file and the config that goes with it for where you have the non-functioning binding configured and try to trigger it a few times?

**Comment by dnfm** [comment]
New log is at: http://logs.i3wm.org/logs/5640686850277376.bz2
Heavily shortened config file is:

```
# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see http://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod1

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
#font pango:monospace 8

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 10
font pango:System San Francisco Display 10

# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec /usr/bin/urxvt


#FUCK OFF, CHROME.
bindsym --release button3 kill

# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart

bindsym F1 nop

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
    status_command i3bar
}
```

**Comment by Airblader** [comment]
Can you reproduce this on the current `next` branch?

Locally I do see an issue, but slightly different: the binding doesn't work on the bottom window of a stacked container, but it does work on the top one. So there is at least some kind of issue here.

**Comment by dnfm** [comment]
I was already on the next branch (I installed the =x11-wm/i3-9999 package on my gentoo box).

But to be sure, I git cloned the next branch as it sits now, and recompiled, unmerged the gentoo package, and installed the built source, and verified that the issue remains.

**Comment by akash-akya** [comment]
Tested and its related to numlock. If you disable numlock it will work correctly.
Isn't this already fixed?
Tested on 4.13-121-g2a91816 (2017-06-23, branch "next")

**Comment by akash-akya** [comment]
#2827 PR for this issue. Please review

**Comment by dnfm** [comment]
I tried the patch you submitted, and it fixed my issues.
