### ISSUE TITLE
Feature request: Show only one window when execute '<criteria> scratchpad show'

### ISSUE THREAD

**Issue by nabice** [i3/i3#2825]
When we have some similar windows in scratchpad, I want to show only one when execute '`<criteria> scratchpad show`' instead of all of them, like the behaviour '`scratchpad show`' does.

Or we can group the scratchpad windows, which is better.

**Comment by Airblader** [comment]
This is possible, you just need to use better (more specific) match criteria. If there is no way to distinguish the windows better, depending on the particular application, you want to file a bug against it or script setting some property yourself to distinguish them.
