### ISSUE TITLE
[enhancement] merge command for container

### ISSUE THREAD

**Issue by gammelon** [i3/i3#2835]
What do you think about implementing a merge command for a container?

It would work as follows:
this ascii art represents the tree with all the containers (dots are just for spacing) ;)
before:

`./H\`
`/M\  C`
`C C`

three arbitrary containers C, one arbitrary container to be merged M, one horizontal H

focused is one of Ms direct descendants

now the merge command
*merge*

after:

` / H \`
`C | C`
`.   C `
three containers C and only one horizontal container H left
note that the three Cs are all on the same level
M does not exist anymore, but all of its direct descendants are now direct descendants of its parent

optional: a parameter controlling the recursion depth of this commands (e.g. merge also every childs childs for recursion==2 )

what do you think?

**Comment by Airblader** [comment]
Let's not discuss adding a command just because we can. What's the use-case you are trying to solve here?

**Comment by gammelon** [comment]
My use-case would be that after a certain amount of time using i3 the containers are getting somewhat nested.

like this as a part of the container tree:
`C`
`|`
`C`
`|`
`C`
`|`
`W`

W is a terminal or whatever

This situation is not only inconvenient when trying to add a new window next to the existing one but it also messes up the titlebars displaying containers that do not even have a purpose

The other use case would be when i simpy want to remove a container and add all its children to its parent

I am aware that both of these situation can be coped with by moving the windows out of the container (an empty container gets destroyed i guess) but this is somewhat unintuitive and may require a little bit of thinking or try-and-error
(or maybe i am missing a much simpler solution...?)

I also tried scripting this using the i3 ipc but the commands do not really provide a method to reparent a container (another suggestion ;p)

I suppose this command is not that hard to implement if one knows where to start. I'd have tried it myself but i am by no means familiar with the codebase.
If you do not like this suggestion could you at least point me to where to begin so i can try myself? :)

**Comment by Airblader** [comment]
> I am aware that both of these situation can be coped with by moving the windows out of the container

And this is exactly the approach that should be taken.

> could you at least point me to where to begin so i can try myself? :)

You need to adapt `parser-specs/commands.spec` and then implement it in `src/commands.c` (and `src/commands.h`), that's about it, implementation-wise. Looking at the history of `src/commands.c` you can also find a command that has been introduced recently and look at the entire commit of that for reference.

Feel free to ask further questions!

**Comment by gammelon** [comment]
Thanks, I'll see what I can do ;)
