### ISSUE TITLE
Hangs when switching from two external screens to notebook screen

### ISSUE THREAD

**Issue by marcvs** [i3/i3#2854]
Output of `i3 --moreversion 2>&- || i3 --version`:
Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08) (pid 1519)o abort…)
Loaded i3 config: /home/marcus/.i3/config (Last modified: Fri 07 Jul 2017 09:39:39 AM CEST, 2177397 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: x-window/i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:
http://logs.i3wm.org/logs/5678807906254848.bz2

**What I did:**
I called my script (via macro) to turn off two external screens and switch to notebook screen. Script here: http://marcus.hardt-it.de/now/reset-laptop-screen.sh

**What I saw:**
The output of the left screen appeared on my notebook screen, but I was unable to do anything. i3-msg commands didn't work. They hang until interrupted.

**What I expected instead:**
All desktops should be back on my notebook and i3 should be responsive.

**Comment by stapelberg** [comment]
Can you reproduce this with the latest git version from the `next` branch? I’m asking because we implemented RandR 1.5 support with commit 633a9f7b1475ffd5c72489bc6bd2d224c441c9a9, which might change things.

**Comment by marcvs** [comment]
Reproducability is unfortunately at roughly 20%.  I'm now using the "next" branch, built with debuild -b -uc -us. Will report back.

**Comment by marcvs** [comment]
Behaviour changed. I do now get the message that i3 crashed. There I chose "restart inplace", after which I suspect my xserver crashed.  I'm not sure why my "reset-laptop-screens.sh" script invoked i3-dump-log twice, but well, I uploaded both runs. 
The first one http://logs.i3wm.org/logs/5700609697120256.bz2 occured at 16:47:24
The second one http://logs.i3wm.org/logs/5696101055201280.bz2 at 16:48:06
I will watch the situation and send updates, on the next crash.

**Comment by stapelberg** [comment]
When the crash dialog appears, could you please press “b” to generate a backtrace in /tmp, then provide the file and the corresponding log? The backtrace contains much more details about the crash, which would be helpful when debugging.

**Comment by marcvs** [comment]
Got backtrace: http://hardt-it.de/now/i3-backtrace.1492.0.txt
And debug-log: http://logs.i3wm.org/logs/5630370875703296.bz2
'f' (forget layout) kept me from restarting all my applications - thanks!!

**Comment by stapelberg** [comment]
Thanks for the backtrace and log, that’s indeed helpful in diagnosing.

Here’s my current theory:

1. You work with outputs HDMI-2 and HDMI-3
2. When switching to your notebook screen, you enable LVDS-1
3. LVDS-1 is also set as the primary output, so it will be focused by i3
4. Because the output has no containers yet, the topdock container is focused (instead of the content container), resulting in an incorrect focus.
5. Mapping the next window crashes i3.

Can you please recompile i3 with the following patch applied and confirm that it fixes the issue, or provide an updated backtrace+logfile if it doesn’t?

```diff
diff --git i/src/randr.c w/src/randr.c
index 48bffb46..86f78d6d 100644
--- i/src/randr.c
+++ w/src/randr.c
@@ -368,6 +368,10 @@ void output_init_con(Output *output) {
     FREE(name);
     DLOG("attaching\n");
     con_attach(bottomdock, con, false);
+
+    /* Change focus to the content container */
+    TAILQ_REMOVE(&(con->focus_head), content, focused);
+    TAILQ_INSERT_HEAD(&(con->focus_head), content, focused);
 }
 
 /*
```

**Comment by marcvs** [comment]
Will do. Will be out of office soon. Reporting back will not be timely.

Is it enough to inplace-restart i3, to use the new binary?

**Comment by stapelberg** [comment]
> Will do. Will be out of office soon. Reporting back will not be timely.

Okay. We’ll go ahead with the 4.14 release without this fix, then.

> Is it enough to inplace-restart i3, to use the new binary?

Yes, inplace-restarting will be enough.

**Comment by marcvs** [comment]
So, I switched from HDMI-2 + HDMI-3 to LVDS-1 with a few scenarios without failure:
- focus HDMI-2
- focus HDMI-3
- focus empty HDMI-2 (no containters)
- focus empty HDMI-3 (no containters)

However, since reproducability is low there's no way to be sure that this one is fixed. I'll be back for testing on Sep12-15.

**Comment by marcvs** [comment]
One week testing the patch now. No crashes observed. I'd consider it fixed.
