### ISSUE TITLE
[Enhancement] Criteria for focus_on_window_activation

### ISSUE THREAD

**Issue by soumya92** [i3/i3#2855]
> When a new window appears, it will be focused. The no_focus directive allows preventing this from happening and must be used in combination with [command_criteria].
> Note that this does not apply to all cases, e.g., when feeding data into a running application causing it to request being focused. To configure the behavior in such cases, refer to [focus_on_window_activation].

I was expecting `focus_on_window_activation` to support criteria because `no_focus` also supports criteria :)

The main motivation behind my feature request is IntelliJ, which makes it's popup windows request focus when they open. I have a setup where one monitor holds my main window, and the other monitor (using assign) holds the auxiliary windows (logs, device monitor, version control, etc.)

However, any time I show an auxiliary window, focus moves to it because it requests focus on being shown. I like the "smart" behaviour of focus_on_window_activation for all other apps, and would love to be able to set it to "none" just for IntelliJ.

**Comment by soumya92** [comment]
Apparently this is an IntelliJ bug with no fix 😞

**Comment by soumya92** [comment]
Thinking about this some more (yeah, it's been driving me nuts, why do you ask?), although the bug is in IntelliJ, there's no reason i3 couldn't let me work around it.

When IJ requests focus, the result is controlled by i3, using the value of `focus_on_window_activation`. i3 should know at that point that the request is coming from IJ, so it should be able to handle criteria for `focus_on_window_activation`.

This issue then becomes a question of complexity/effort vs. benefit tradeoff. I have no idea how hard it would be to implement, though, so any thoughts from the maintainers would be much appreciated. (If I had to attach an arbitrary value to how much this benefits me, I'd say it's a 100-125% improvement on `focus_on_window_activation`.)

There's also a case to be made that this could be handled by ipc alone. To that end, the only thing missing is for `focus_on_window_activation none` to fire an event. Maybe another window event 'active', that mimics existing 'urgent' or 'focus'? In that case, I could subscribe to 'active', check criteria myself, and dispatch focus if needed. Would that maybe be simpler or more in the i3 spirit?

**Comment by Airblader** [comment]
Sorry, we're not looking to support this for `focus_on_window_activation`. The config directive is frequently misunderstood and was probably a mistake to add to begin with. As you said, this can be done entirely via the IPC.

> To that end, the only thing missing is for focus_on_window_activation none to fire an event.

The requests are sent as client messages to the root window; you can subscribe to these as well, no need for a message from the IPC.

**Comment by soumya92** [comment]
> The requests are sent as client messages to the root window
Perfect. Thanks! I had assumed that these were events only the WM was allowed to receive, similar to the window mapping and unmapping events.

**Comment by soumya92** [comment]
I tried playing with some event listeners using `xprop -root -spy`, and looked through https://standards.freedesktop.org/wm-spec/wm-spec-latest.html#activation, but I can't find any messages that would be fired when a window requests activation.

I can only find events fired when a window is actually activated (but that wouldn't happen with `focus_on_window_activation none`). I also see this in the docs:
> Depending on the information provided with the message, the Window Manager may decide to refuse the request (either completely ignore it, or e.g. use _NET_WM_STATE_DEMANDS_ATTENTION).

Which makes it sound like if i3 does not focus the window, the request is discarded.

Do you have an example of subscribing to the client events that you mentioned?
I couldn't find any way for an x11 client to be notified when a different window requests activation but the window manager ignores that request. Which is why I suggested adding an ipc event when i3 does so. I'm happy to send you a patch for it, looks like I would just need to add an ipc event here: https://github.com/i3/i3/blob/a92acadfc052c0ac73455e03edaf64b75853dde7/src/handlers.c#L443

**Comment by Airblader** [comment]
`xprop` only works for properties (hence the name). Client messages are events, so `xev` is the tool of choice here (`xev -root`). Unfortunately, `xev` doesn't have an argument for `-event` which filters client messages, but for actually dealing with client messages you'd not use `xev` anyway.

**Comment by soumya92** [comment]
D'oh. Got it. I'll stop looking at properties and more at events :)
Thanks for the pointer!

**Comment by AdamDanischewski** [comment]
Not being able to disable activation for certain window classes is a killer for focus_on_window_activation. What is the workaround if one exists? 

I like "focus_on_window_activation focus" 99% of the time, but for some applications when activated for whatever reason I'd like to ignore focus. For many apps there are workarounds such as cvlc for vlc. Otherwise maybe Xephyr?

**Comment by benedikt-bartscher** [comment]
@AdamDanischewski did you find a solution for this? I want to disable focus for chromium instances spawned by selenium (by window class)

**Comment by prosoitos** [comment]
I also wish that `focus_on_window_activation` were able to accept criteria.

I really like `focus_on_window_activation focus` but it is impossible to use with Zoom as Zoom keeps grabbing the focus all the time for all sorts of disruptive reasons (recording stared, recording stopped, screen sharing started, screen sharing stopped, etc.)

Thank you!!

**Comment by jdholtz** [comment]
Would also love to see this!
