### ISSUE TITLE
Feature request: Start uniquely an application and window title.

### ISSUE THREAD

**Issue by biocyberman** [i3/i3#2870]
tOutput of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08) (pid 2050)o abort…)
Loaded i3 config: /home/user/.i3/config (Last modified: Mon 21 Aug 2017 11:54:45 AM CEST, 4537 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

URL to a logfile as per http://i3wm.org/docs/debugging.html:

Not applicable

**What I did:**

I am using this wrapper script to make sure only one instance of an application is running (i.e. Firefox, Chrome or a Special Terminal instance).

```
#!/bin/bash
STARTPROC=$1
shift
CHECKPROC=${1:-$STARTPROC}
shift
STARTPROC="$STARTPROC $@"
if [[ "$(pidof $CHECKPROC)" == "" ]]; then
        echo -e "Running $STARTPROC"
        exec $STARTPROC &
else
        echo -e "$CHECKPROC is running already"
fi

```

However if I want to start more than one instances of an application (i.e. terminal) to do different things, I can't use this script and have to make another wrapper script. 

**What I saw:**

Not applicable

**What I expected instead:**

Being able to uniquely start an application with a particular window title is needed. That is, if an application mypro, with a title "MyTitle" is already running, then just focus to it. Otherwise, start application and focus.

**Comment by Airblader** [comment]
> Being able to uniquely start an application with a particular window title is needed.

The only one who can reliably do this is the application, so please file a bug / request against the application to support the standard X11 arguments such as `--class`, `--instance`, `--title` etc.

i3 knows nothing about processes and how they connect to windows. And that's a really tough task: an application can create one, many or none windows and it can do so at any point during its lifetime. We simply cannot correlate windows to applications.
