### ISSUE TITLE
crash when toggling floating mode and dragging with mouse at the same time

### ISSUE THREAD

**Issue by Hippo0o** [i3/i3#2886]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.13-non-git © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13-non-git (pid 25470)-c to abort…)
Loaded i3 config: /home/tobias/.i3/config (Last modified: Sa 26 Aug 2017 17:34:49 CEST, 87329 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5688895442255872.bz2

**What I did:**

pressing $mod+Shift+space on any floating window while dragging it with $mod+leftMouseButton

**What I saw:**

black rectangle (i3 crashed)

**What I expected instead:**

it should toggle float

**Comment by Airblader** [comment]
duplicates #1627
