### ISSUE TITLE
[feature] Drag window into floating mode

### ISSUE THREAD

**Issue by SrTobi** [i3/i3#2904]
Wouldn't it be cool to be able to click on the titlebar of a window and then, when dragging it, it goes automatically into the floating mode. That would be a great enhancement for using i3 with the mouse. 

One should of cause be able to enable/disable this feature through the config. One should also be able to bind it to a keybinding (like $mod) to enable the dragging. So you would have to press $mod and then click and then drag.

**Comment by Airblader** [comment]
Why would it be a great enhancement? What's the usecase for this? Floating mode is mostly intended for dialogs and scratchpad. We're a tiling window manager.

**Comment by SrTobi** [comment]
That's true and I love it for that. But whenever I want to use a window in floating mode (and it was docked before), I also almost always want to move it around with the mouse -> so I have to change the mode and then grab it anyway. Why not combine both actions into the very natural motion of grabbing it out of the docking mode?

**Comment by Airblader** [comment]
We already have #2643 which probably conflicts with this. Unless it can be made compatible somehow.

**Comment by Airblader** [comment]
Since there has been no further feedback I'm going to go with my above reasoning that #2643 has a much stronger usecase that also suits i3 better.
