### ISSUE TITLE
`append_layout`: crash

### ISSUE THREAD

**Issue by Hibou57** [i3/i3#2919]
Output of `i3 --moreversion 2>&- || i3 --version`:

> Binary i3 version:  4.14 (2017-09-04) © 2009 Michael Stapelberg and contributors
> Running i3 version: 4.14 (2017-09-04) (pid 2081)o abort…)
> Loaded i3 config: /home/yannick/.config/i3/config (Last modified: sam. 09 sept. 2017 12:59:32 CEST, 26436 seconds ago)

> The i3 binary you just called: /usr/bin/i3
> The i3 binary you are running: i3-w/bin/i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5726146096267264.bz2

**What I did:**

From a workspace containing no more than a terminal, copy the attached `workplace.json` to your home directory, then from the same home directory, do:

    i3-msg append_layout workspace.json

**What I saw:**

One time I got an i3 crash box I’ve seen before and never seen then. Then other times, it seems to hang, but it appears it was terminated.

When I got an i3 crash box, it asked me to to generate a trace pressing a key. I pressed that key, but I don’t know if the trace was generated or where. As GDB was not installed, it’s likely not. Anyway, the repository I use does not provide an i3 with debug symbols (it is stripped) and the debug symbols are only available as a separate file. If I still can do something with this, please, tell me.

**What I expected instead:**

I expected to see a layout with its place holders.

**Note:**

There is another issue with `append_layout`, but that will be for another issue report.

**Attachments:**

This one exposes the crash: [workspace.json.zip](https://github.com/i3/i3/files/1290006/workspace.json.zip)

This one does not (not all layout files make i3 crash): [workspace2.json.zip](https://github.com/i3/i3/files/1290009/workspace2.json.zip)

**Comment by Hibou57** [comment]
At least marks are involved. In the attached ZIP, two files. The first, `workspace1.json` makes i3 crash, the second, `workspace2.json` does not. The only difference between the two is that there are marks in the former and there are not there in the latter.

**Comment by orestisf1993** [comment]
Hello, I can't reproduce this with the `next` branch. `workspace.json` and `workspace1.json` don't crash i3. This is probably the same issue as #2900 because reverting 554775f6 makes the problem appear.

**Comment by Hibou57** [comment]
Hi, thanks. So I will wait for this next version to be in the repository and will wait this new version too to check again another but non‑crashing issue I was to submit.

If it’s fixed in the next version, I believe I have to close this issue.
