### ISSUE TITLE
Freeze of all interaction upon pausing an app with opened context menu

### ISSUE THREAD

**Issue by Hi-Angel** [i3/i3#2927]
Output of `i3 --moreversion 2>&- || i3 --version`:

	Binary i3 version:  4.14 (2017-09-04) © 2009 Michael Stapelberg and contributors
	Running i3 version: 4.14 (2017-09-04) (pid 3120)o abort…)
	Loaded i3 config: /home/constantine/.i3/config (Last modified: Thu 31 Aug 2017 05:07:00 PM MSK, 882078 seconds ago)

	The i3 binary you just called: /usr/bin/i3
	The i3 binary you are running: i3

URL to a logfile: http://logs.i3wm.org/logs/5702949112119296.bz2

**What I did:**

1. Open `gdb kate` *(or libreoffice, that's where I originally triggered the bug)*
2. In gdb prompt type `run`, and wait for kate to appear.
3. Press <kbd>Ctrl</kbd>+<kbd>c</kbd> in gdb, type `br open` <kbd>Enter</kbd>, then `continue` <kbd>Enter</kbd>.
4. Click in kate `File`.

**What I saw:**

Freeze of all interaction: shortcuts stops working, windows can not be focused, clicking windows or applets doesn't do anything. However any animation continue working, e.g. date applet and CPU percentage are keep changing.

The only way to recover from the freeze is to switch to a TTY, and kill gdb from there.

**What I expected instead:**

Switch to a terminal with gdb to continue working on.

**Comment by Airblader** [comment]
I don't think there is anything we can do about this. Context menus typically grab the keyboard and mouse and as long as that happens, we're just stuck.

**Comment by Hi-Angel** [comment]
@Airblader shall I report the bug to XServer instead?

**Comment by Airblader** [comment]
There is no bug here. That's simply how X was designed.
