### ISSUE TITLE
Enabling / disabling floating for containers from other workspace loses their focus

### ISSUE THREAD

**Issue by orestisf1993** [i3/i3#2938]
Output of `i3 --moreversion 2>&- || i3 --version`:
```
Binary i3 version:  4.14-8-g85eb0976 (2017-09-05, branch "makepkg") © 2009 Michael Stapelberg and contributors
(Getting version from running i3, press ctrl-c to abort…)
Running i3 version: 4.14-40-gbcaec964 (2017-09-11, branch "remotes/origin/HEAD") (pid 902)
Loaded i3 config: /tmp/i3.config (Last modified: Tue 12 Sep 2017 11:42:24 AM EEST, 27 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: /home/orestis/Documents/programming/i3/build/i3
```

URL to a logfile as per http://i3wm.org/docs/debugging.html:
http://logs.i3wm.org/logs/5751832013963264.bz2

**What I did:**
1. open 2 windows on workspace 1.
2. run `i3-msg floating enable && i3-msg mark A` for the second one. It is now focused & floating.
3. switch to workspace 2
4. run `i3-msg '[con_mark=A]' floating disable`
5. switch back to workspace 1

**What I saw:**
Window marked as A is not floating & is not focused.

**What I expected instead:**
Window marked as A is not floating & is still focused.

**Comment by Airblader** [comment]
We have another ticket called "inconsistent focus fallback" (or something like that) which is possibly related. I can't look for it at the moment, though.

**Comment by orestisf1993** [comment]
You are talking about issue #1975. I think that it's not exactly the same issue. I am currently working on a fix that only modifies `floating_disable()` and it seems to solve this (2938) issue. Haven't tested it properly yet though.

I'll see if I can make a PR soon.

**Comment by orestisf1993** [comment]
Bug also applies to `floating enable`.
