### ISSUE TITLE
enhancement: make the IPC interface support network byte order

### ISSUE THREAD

**Issue by stapelberg** [i3/i3#2958]
Currently (4.14), i3 specifies byte order to be native byte order.

When writing that, we thought it would be fastest and most convenient for downstream programmers to not have to do any conversions.

We didn’t realize at the time that some programming languages might allow to specify a byte order, but not have the concept of a native byte order. This [discussion of native endianness in Go](https://www.reddit.com/r/golang/comments/3a88ay/does_go_need_native_endianess/) is just one example.

Ideally, the IPC interface would be easy to use from any language, and having to resort to unsafe hacks in modern languages is not a good experience.

Hence, I propose we extend the IPC interface as follows:

If the first message contains the magic string `i3-bge` (for big endian) instead of `i3-ipc`, then all values henceforth are assumed to be in network byte order and i3 will send messages with the `i3-bge` magic string itself.

Then, newer IPC libraries can just use network byte order.

Libraries which want to maintain compatibility with older i3 versions can start by sending an `i3-bge` message (e.g. `GET_WORKSPACES`, which is available in all versions of i3) and falling back to `i3-ipc` messages if the reply to the message is a closed connection instead of a `WORKSPACES` reply.

Thoughts? cc @Airblader @acrisci

**Comment by Merovius** [comment]
Bikeshedding: `nbo` is also the acronym for "native byte order". Why not `i3-be`, or somesuch? Personally, I find "Big Endian" to be less ambiguous than "Network Byte Order" (if nothing else, because "Big Endian" has a counterpart "Little Endian", whereas the opposite of "Network Byte Order" is… "Host Byte Order"? Which isn't necessarily different).

**Comment by stapelberg** [comment]
I’d like to keep the length the same to keep changes to the existing parsing code at a minimum. Let’s use `i3-bge` for Big Endian to avoid the acronym issue you pointed out.

**Comment by acrisci** [comment]
I think I'd like it better if we made an explicit break in the ipc protocol and deprecate the old version instead of giving the impression that either are viable. That way we're future proof in case we need to make another break. It would only apply to the big endian version.

So maybe the magic should be `i3-ipc-v2` or `i3ipc2` or something like that.

**Comment by stapelberg** [comment]
I sent PR #2961 which documents a technique to auto-detect i3’s byte order in memory-safe languages.

IPC libraries will need to use such a technique (or resort to the `unsafe` package or similar) until i3 ≥ 4.15 is used widely enough that users can reasonably be expected to upgrade their i3 before using a third-party program. I expect that point to be at least 5 years in the future due to e.g. Ubuntu’s long support cycles.

So, coming back to this proposal:
* Pro: IPC library authors might delete 50 lines of code in 5 years
* Pro: In case new and weird architectures are introduced and gain traction, i3 might not need any further changes to work on them. I think this is very unlikely, and processors are more likely to just use little endian.
* Con: possible incompatibilities (newer software targeting `i3-bge` won’t work on older i3)
* Con: additional mental complexity in the ipc interface

I’m having second thoughts about this suggestion now.

My gut feeling is to not do it, so that we don’t even risk the chance of incompatible third-party software. I think “my software is implemented slightly more cleanly” is nice, but “my software doesn’t work at all, and I don’t know why” is massively frustrating, and both are possible outcomes.

If there are any strong arguments for the change which I’ve missed, I’m all ears. If I don’t hear anything, I’ll close this ticket soonish.

**Comment by stapelberg** [comment]
Closing as described in [the previous comment](https://github.com/i3/i3/issues/2958#issuecomment-330041441)
