### ISSUE TITLE
[enhancement] `mouse_warping window` option: warp mouse on every focus change

### ISSUE THREAD

**Issue by Qu4Z** [i3/i3#2971]
The `mouse_warping` config option currently supports two values: `none` and `output`.     

Would you consider a pull request to implement the `window` value for this option, which would warp the mouse for every non-pointer-initiated focus change? For example, when you use `focus left` by hitting `Mod+j` the focus would change as normal and the mouse would be centered on the newly focused window. If it can be implemented cleanly without adding unduly to the maintenance load, of course, but the option and `x_set_warp_to` already exist, so I don't think it would be too difficult (famous last words). 

On a largish monitor (say, 27"), if you have a lot of windows open, your keyboard focus can end up quite a distance from where the mouse is, which can be annoying when you then need to use the mouse on the focused window. This would implement mouse-follows-focus, basically, to complement the existing focus-follows-mouse.

**Comment by Airblader** [comment]
It sounds good to me. @stapelberg Thoughts?

**Comment by stapelberg** [comment]
I don’t quite see how this request differes from the recently-rejected https://github.com/i3/i3/pull/2813? The latter says “always” instead of “window”, but (why?) does that reduce edge-cases?

**Comment by Qu4Z** [comment]
Ah, thank you for the link to the other issue. I'd searched for mouse warping issues to see whether it had been previously discussed, but since I'd filtered it down to enhancements-only I didn't catch it. 

By "edge-cases" are you referring to the relatively large number of files/functions that are touched by the patch tohojo provided? Or do you find the user-visible behaviour inherently edge-casey/complex? 

As an alternative, would you accept a patch adding a command to warp the mouse to the currently-focused window? This should be substantially simpler, and could be used to implement the behaviour I'm after in config, something like:

```
bindsym $mod-j focus left; warp mouse
```

That would provide the mechanism, and leave the (admittedly somewhat edge-casey) policy to the user. 

PS: Airblader: I think by "works well with focus-follows-mouse", tohojo meant it not because he's suggesting pointer-warping should be triggered by ffm-initiated focus changes (since his patch goes to pains to avoid just that), but because you can consistently select the window to the right of the focused one by moving the mouse to the right. Currently with focus-follows-mouse enabled but used in combination with the keyboard shortcuts, moving the mouse to the right focuses the window to the right of wherever the mouse was last used.

**Comment by Airblader** [comment]
> warp the mouse to the currently-focused window

This you could achieve entirely without i3 by using tools like `xdotool`.

**Comment by stapelberg** [comment]
> By "edge-cases" are you referring to the relatively large number of files/functions that are touched by the patch tohojo provided? Or do you find the user-visible behaviour inherently edge-casey/complex?

I was referring to edge cases in the X11 protocol regarding focus changes, not necessarily our code base itself.

>> warp the mouse to the currently-focused window
>
> This you could achieve entirely without i3 by using tools like xdotool.

Indeed, I think the best course of action here would be to use xdotool. If it turns out that external tools fundamentally cannot do warping sensibly for whichever reason, but i3 could, then we can revisit adding this feature to i3 itself.

**Comment by oliversturm** [comment]
In case it helps someone, I wrote this small script:

```bash
#!/bin/bash
XDT=/usr/bin/xdotool

WINDOW=`$XDT getwindowfocus`

# this brings in variables WIDTH and HEIGHT
eval `xdotool getwindowgeometry --shell $WINDOW`

TX=`expr $WIDTH / 2`
TY=`expr $HEIGHT / 2`

$XDT mousemove -window $WINDOW $TX $TY
```

The script moves the mouse to the center of the focused window, I execute it as a chained statement for key bindings that move window focus.

**Comment by GrantCuster** [comment]
@oliversturm's script works great for me, except when I am navigating to a screen that does not have an open window on it. If I do that the script (understandably) gets confused, and usually the mouse gets warped to the top-left. Any ideas on how to adjust the script to handle that situation?

Edit, I'm sure this code is inefficient (I don't do much bash or JQ scripting) but it does work for me. Check for height of 100 assumes that anything less than that means no window:

```bash
#!/bin/bash
XDT=/usr/bin/xdotool

WINDOW=`$XDT getwindowfocus`

# this brings in variables WIDTH and HEIGHT
eval `xdotool getwindowgeometry --shell $WINDOW`

if [ $HEIGHT -gt 100 ]
then
  TX=`expr $WIDTH / 2`
  TY=`expr $HEIGHT / 2`

  $XDT mousemove -window $WINDOW $TX $TY
else
  rect=$(i3-msg -t get_workspaces | jq -r '.[] | select(.focused==true).rect')

  x=$(jq -r '.x' <<< $rect)
  y=$(jq -r '.y' <<< $rect)
  w=$(jq -r '.width' <<< $rect)
  h=$(jq -r '.height' <<< $rect)
  TX=`expr $x + $w / 2`
  TY=`expr $y + $h / 2`
  $XDT mousemove -window $WINDOW $TX $TY
fi
```

**Comment by mutageneral** [comment]
Here is a version that is portable POSIX shell (no bash required) and no jq required, only xdotool. And it does work with multi monitor for me.

```sh
#!/bin/sh
set -e

output=$(xdotool getactivewindow getwindowgeometry --shell) 
read -r window width height << EOF
$( echo $(echo $output | awk '{print $1; print $4; print $5;}' | cut -d "=" -f 2) )
EOF

move_y=$((height / 2))
move_x=$((width / 2))

xdotool mousemove --window $window $move_x $move_y
```
Original code taken from [here](https://old.reddit.com/r/i3wm/comments/nr73k6/mouse_following_the_focused_window/jkohm6e/).
