### ISSUE TITLE
layout toggle split not working

### ISSUE THREAD

**Issue by Eyenseo** [i3/i3#2991]
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.14.1 (2017-09-24) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.14.1 (2017-09-24) (pid 30885)bort…)
Loaded i3 config: /home/eyenseo/.config/i3/config (Last modified: Mon 25 Sep 2017 15:07:42 CEST, 7649 seconds ago)
The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3-with-/i3
```

URL to a logfile as per https://i3wm.org/docs/debugging.html:

[https://logs.i3wm.org/logs/5692767623708672.bz2](https://logs.i3wm.org/logs/5692767623708672.bz2)

**What I did:**
Create two windows (alacritty) that are by default V-Split, press the key combination (Super+e) for `layout toggle split`.
This was after a 'fresh' log in with debug enabled -> there _should_ be no side effects.

**What I saw:**
Two terminals that where V-Split.

**What I expected instead:**
Two terminals that where H-Split.

Edit: forgot that I'm testing alacritty and not using termite

**Comment by Eyenseo** [comment]
Just noticed that after `layout tabbed` `layout toggle split` works as expected.

**Comment by orestisf1993** [comment]
Bisect blames 52ce8c803d424f395874fa87992eea0cc9f061d3. I also tested this together with https://github.com/i3/i3/issues/2846 and I believe that they are duplicates.

**Comment by Eyenseo** [comment]
Oh sorry, I searched but somehow didn't see that one  - I close this issue then.
