### ISSUE TITLE
Inconsistent behavior of move with fullscreen windows

### ISSUE THREAD

**Issue by orestisf1993** [i3/i3#2993]
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.14-117-gf4f3d649 (2017-09-25, branch "next") © 2009 Michael Stapelberg and contributors
(Getting version from running i3, press ctrl-c to abort…)
Running i3 version: 4.14-117-gf4f3d649 (2017-09-25, branch "next") (pid 9098)
Loaded i3 config: /tmp/i3.config (Last modified: Tue 26 Sep 2017 03:12:56 AM EEST, 3 seconds ago)

The i3 binary you just called: /home/orestis/Documents/programming/i3/build/i3
The i3 binary you are running: i3
```

URL to a logfile as per https://i3wm.org/docs/debugging.html:

https://logs.i3wm.org/logs/5697070107197440.bz2 (I don't think you'll find anything useful here)

**What I did:**

Open a bunch of windows, fullscreen one of them, try to move it around using `move up|down|left|right`, `fullscreen disable`.

**What I saw:**

- For split h layout the fullscreen window can only move left or right and will change outputs if it is on the edge. It won't move up / down.
- For split v layout the window will move up / down and will change outputs if it is on the edge. It won't move left / right.
- For tabbed / stacked same as above but the windows won't change outputs.

Generally, the containers won't detach from their parents but can move inside them. Special case is split h / v where they can move across outputs.

Another difference in behavior is with unfocused fullscreen windows (fullscreen & change workspace). There, freedom of movement is not restricted in any case.

**What I expected instead:**

Consistent behavior.

This also applies to global fullscreen windows. Inspired by https://github.com/i3/i3/issues/2974#issuecomment-331456278.

**Comment by Airblader** [comment]
Given the lack of visual feedback both on the current workspace's layout and any kind of move within its workspace, I'd say fullscreen containers should never be moved within their workspace, but only (and always) directly between outputs. @stapelberg Thoughts?

**Comment by stapelberg** [comment]
Sounds reasonable.
