### ISSUE TITLE
Icons break per-workspace-layout

### ISSUE THREAD

**Issue by Chais** [i3/i3#2996]
Output of `i3 --moreversion 2>&- || i3 --version`:
```
Binary i3 version:  4.14-non-git © 2009 Michael Stapelberg and contributors
Running i3 version: 4.14-non-git (pid 879)rl-c to abort…)
Loaded i3 config: /home/chais/.config/i3/config (Last modified: Wed 27 Sep 2017 20:41:49 CEST, 1271 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```
URL to a logfile as per https://i3wm.org/docs/debugging.html:
https://logs.i3wm.org/logs/5763418761986048.bz2

**What I did:**
I use `per-workspace-layout.pl` with
```perl
my %layouts = (
    "1:" => 'tabbed',
);
```
**What I saw:**
Workspace 1 does not default to tabbed layout.

**What I expected instead:**
Workspace 1 should default to tabbed layout. It does when not using an icon as name (e.g. '1:www')

**Comment by Chais** [comment]
That was a quick fix :smile: Thanks. :ok_hand:

**Comment by Chais** [comment]
I spoke too soon. i3 still starts with split layout. Could locking workspaces to outputs or assigning applications to workspaces be involved here?

**Comment by Airblader** [comment]
@Chais I could reproduce the issue and this fix worked (and for good reasons). If it still doesn't work, please run the script from a terminal and see whether it complains about something?

**Comment by Chais** [comment]
It doesn't complain when run from the terminal. I verified it's run by i3, but only when I run it again from the terminal it actually has an effect. My attempt to write a little script to output the layout of all workspaces failed.

**Comment by hubitor** [comment]
For me it doesn't work both ways with the icon...There are no error messages when I run it from the terminal. If I remove the icon it works fine both ways.

```
Binary i3 version:  4.15 (2018-03-10) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15 (2018-03-10) (pid 1166)o abort…)
Loaded i3 config: /home/nick/.config/i3/config (Last modified: Sam 12 Mai 2018 10:21:11 CEST, 2493 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

**Comment by imme-emosol** [comment]
In strict mode I got some error

    EV: error in callback (ignoring): Can't use string ("1: xXx") as an ARRAY ref while "strict refs" in use at $DIR$/per-workspace-layout.pl line 39.

https://perlmaven.com/symbolic-reference-in-perl

So I changed using $ws->{name} into using $ws->{num}, to use the workspace's number i.e. : 

     my $name = $ws->{num};
