### ISSUE TITLE
enhancement: kill misbehaving IPC connections instead of deadlocking

### ISSUE THREAD

**Issue by stapelberg** [i3/i3#2999]
Currently, i3 blockingly writes replies and events (only after subscribing, of course) to IPC clients. If an IPC client does not read from the connection for whichever reason, this will result in i3 blocking indefinitely, effectively freezing as far as users are concerned. (Side note: the same is true for reading, i.e. once i3 starts reading anything, it blockingly waits for the entire message to arrive. This turns out to not be a problem in practice.)

This is a recurring problem (see #2280 and #2539 for examples), so I’m filing this issue to brainstorm about what we could do about it, if anything.

My current favorite mitigation technique is to check whether the IPC connection’s file descriptor is writeable before sending a message (using `select(2)` with a 0 timeout). If not, we kill the connection, preventing a deadlock.

Here are a few more thoughts about this idea:

* We should spawn an i3-nagbar instance to inform users that they just ran into a third-party bug. Otherwise, software might start to rely on this behavior (e.g. it might not clean up IPC connections which are no longer used).
  * We should refer users to a help document on https://i3wm.org/docs where we explain how to further diagnose the issue.
* I considered using a timeout instead, but timeouts are very brittle: they make assumptions about how quickly processes run at *every point in time* on *vastly different computers*. E.g., if we decided to use a 10 second timeout, and another program starts swapping to hard disk (hence starving other processes for a while), i3 would incorrectly kill correctly functioning IPC clients. If we opt for a timeout that is too high, the mitigation becomes ineffective and users would still think that i3 hangs.
  * I think that the check-writeability approach will gracefully degrade on systems which are under high load: if the IPC client is slow, i3 will likely be slowed down to a somewhat similar extent.
* Linux-specific: as per http://elixir.free-electrons.com/linux/v4.13.4/source/include/net/sock.h#L2139 and https://stackoverflow.com/a/22007520/712014, UNIX sockets are reported as writeable as long as half of their send buffer is available. Linux’s default value for the default and maximum send buffer size is 212992 bytes, i.e. individual i3 messages must not exceed 106496 bytes for this mitigation technique to be effective. The largest messages we send are TREE replies, which can easily reach 60 kb in size (observed on my somewhat big session right now). Luckily, the most common case for deadlocks are events, which are significantly smaller in size, so we should be good.
  * We could use the (platform-specific) [`SIOCOUTQ` ioctl](https://manpages.debian.org/stretch/manpages/tcp.7.en.html#Ioctls) to get the number of unsent bytes, which — in combination with the send buffer size — would allow us to verify that the message we are about to send is going to fit. https://codesearch.debian.net/search?q=ioctl.*SIOCOUTQ%2C&perpkg=1 shows that a handful of programs use this ioctl.
* Some platforms have significantly lower send buffer size limits (IIRC, BSDs default to 32k), so i3 should try to increase the limit to the maximum value or 256k, whichever is lower.
* If the platform does not correctly report writeability, lacks the `SIOCOUTQ` (or similar) ioctl, or has a too strict limit on the maximum send buffer size, we’d fall back to the current behavior and deadlock.

Disclaimer: I have not actually implemented anything yet, so I’m not sure if this works out in practice.

cc @Airblader 
cc @acrisci 
cc @Merovius (we briefly spoke about this a few weeks ago)
cc @hannes to keep me honest about linux networking

**Comment by Airblader** [comment]
SGTM, but I know next to nothing about these things, so I cannot really weigh in here.

**Comment by stapelberg** [comment]
Another alternative is to implement a per-connection message queue which can be consumed byte-wise into the IPC connection using a libev watcher which is called when the socket is writeable.

That’s more portable, but raises the question of queue sizing. I would suggest applying the following rules of thumb when sizing the queue:
* The queue must hold at least the number of messages which a single i3 event loop iteration can generate, otherwise we’d kill clients prematurely.
* The queue must not be sized so large that misbehaving clients are turned into what looks like a memory leak, as the connection between a misbehaving client and large i3 memory usage is not obvious for users.
* A reasonable queue size might be, say, 5 * minimum queue size.

Also, the libev watcher priority should be set such that immediately after an i3 event loop iteration, the queued messages are written to clients, so that the buffers are empty in the common case.
