### ISSUE TITLE
mate-panel autohide setting has no effect in i3

### ISSUE THREAD

**Issue by nochiel** [i3/i3#3025]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.14.1 (2017-09-24) © 2009 Michael Stapelberg and contributors
(Getting version from running i3, press ctrl-c to abort…)
Running i3 version: 4.14.1 (2017-09-24) (pid 838)
Loaded i3 config: /home/nic/.config/i3/config (Last modified: Fri 20 Oct 2017 02:18:58 AM EAT, 689 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per https://i3wm.org/docs/debugging.html:

https://logs.i3wm.org/logs/5706456892440576.bz2

**What I did:**
- run `i3`
- run `mate-panel`
- right click `mate-panel`; select `properites`, enable `autohide`

**What I saw:**
- mate-panel remains visible and does not autohide.

**What I expected instead:**
mate-panel should automatically hide.

Ref: https://github.com/mate-desktop/mate-panel/issues/673

**Comment by Airblader** [comment]
It'll be interesting to know how mate-panel's autohide works. In other words, what X11 mechanisms do they use to hide the panel? Do they just unmap the window? Do they use some (potentially proprietary) client message?

**Comment by nochiel** [comment]
> [@lukefromdc says](https://github.com/mate-desktop/mate-panel/issues/673#issuecomment-338425280): In autohide the panel uses an animated in/out from the edge of the screen.

I don't [yet] know enough about GTK to describe what X11 api's it uses.

**Comment by Airblader** [comment]
Given that this affects not just i3, I am going to close this issue here for now as we are tracking it on mate-panel. Once we have indication that i3 is doing something incorrectly, we can reopen here. I'll also be subscribed to the issue over at mate-panel.

**Comment by nochiel** [comment]
>  I'll also be subscribed to the issue over at mate-panel.

Thank you.
