### ISSUE TITLE
[Feature request] Empty frames

### ISSUE THREAD

**Issue by Hund** [i3/i3#3029]
Something I really like about Herbstluftwm is the fact that you can create empty frames. I know that `i3-msg open` exists. But with Herbstluftwm you can create an empty frame at a specified direction with:

```
hc keybind $Mod-u       split   bottom  0.5
```
```
hc keybind $Mod-o       split   right   0.5
```

You also have two ways of closing clients and removing frames:

```
hc keybind <keybinding> close_and_remove
```
```
hc keybind <keybinding> close_or_remove
```

The first options closes the client and removes the frame, while the alternative option only closes the client and keeps the frame open. It will only remove the frame if you run the command again. 

These empty frames can also have the regular window decoration or to be completely invincible and only show the border of the active frame.

Since this is all optional behavior, would it be something for you to consider? I know it's probably a very niche feature, but for someone with 3 monitors and tons of clients arranged in very specific ways, this is a very nice feature to have! :)

**Comment by TwoToneBone** [comment]
I like this idea. I would love to have this in i3 aswell.

**Comment by stapelberg** [comment]
How does this request differ from the seemingly duplicate #634 and #2872?

**Comment by Hund** [comment]
They don't, I guess. They didn't come up when I searched. :( Bah! I've been toying around with other window managers, but I like i3 the most.

**Comment by stapelberg** [comment]
Thanks for clarifying and sorry to disappoint — the position on this feature has not changed in the meantime. I’ll therefore close the issue.

https://faq.i3wm.org/question/778/why-is-patch-not-merged-and-made-optional/index.html outlines why we can’t add every feature request.

**Comment by Hund** [comment]
It's okay. I understand anyway, it's your project and you have to do what you feel is right for i3. :)

**Comment by matttproud** [comment]
Posting this comment mostly for search indexability (for other folks who are migrating or curious about i3).  A feature like this would largely enable seamless migration from [ion3](https://web.archive.org/web/20070708162006/http://modeemi.fi/%7Etuomov/ion/) or [notion](https://notionwm.net/) to i3.
