### ISSUE TITLE
Enhancement: $mod+r toggles resize mode

### ISSUE THREAD

**Issue by jchook** [i3/i3#3034]
Why not change the meaning of `$mod+r` from "enable resize mode" to "toggle resize mode"?

I believe this is a more desirable and intuitive UX as you can "exit through the door you entered".

Here is [my attempt at making the change](https://github.com/i3/i3/compare/next...jchook:next).

**Comment by jchook** [comment]
Wanted to quickly add that this pattern is already found throughout i3's defaults:

1. `$mod+f` both enables and disables full-screen
1. `$mod+e` will toggle between splits
1. `$mod+Shift+space` toggles between floating and not
1. `workspace_auto_back_and_forth` is not a default, but highlighted in the docs.

This last one is interesting because the docs touch on the philosophy behind the design decision:

> For instance: Assume you are on workspace "1: www" and switch to "2: IM" using mod+2 because somebody sent you a message. You don’t need to remember where you came from now, you can just press $mod+2 again to switch back to "1: www".

**Comment by disconsis** [comment]
Cool idea, but I don't see why that would need to be specifically implemented.
You can configure it for yourself by putting `bindsym $mod+r mode "default"` inside `mode "resize"`

**Comment by jchook** [comment]
IMO this is a UX improvement, not a preference. After reading about window mangers, it's surprisingly clear that a very significant reason people choose i3 (over Xmonad, etc) is for it's superior default behavior.

**Comment by Airblader** [comment]
> but I don't see why that would need to be specifically implemented.

It doesn't; the proposed change is just a change to the default config.

@jchook The proposal sounds good to me. Assuming @stapelberg doesn't object, I'll be happy to wait for the PR.

**Comment by stapelberg** [comment]
Sounds good to me.
