### ISSUE TITLE
[enhancement] Make "swap" support direction movement

### ISSUE THREAD

**Issue by NikolajSimling** [i3/i3#3056]
The swap command implemented in #2496 requires the user to know the id, con_id og mark. As discussed in #917, it should also be possible to swap containers based on directions, that is:

`swap left | right | up | down`

This would basically be an alternative move command.

This operation should work exactly as the similar focus command, except instead of moving the focus from one container to another, it should swap the two containers. Implementation-wise, it should use the same algorithm as focus, to find the container to swap with, and then swap it using the swap function.

An example of a use-case would be that we have this layout:
```
+---+---+
|   | B |
| A +-+-+
|   |C|D|
+---+-+-+
```
Here A is our main windows, i.e. where we have a browser, a editor or something else. The BCD pane is where we have other secondary windows, orgasined in some way. If we at some time need to focus our attention on window C, we would like to bring that into the main pane, and instead move A into the pane of secondary windows. An operation that is very common in Xmonad.

Currently, using regular moves, that requires me to (a) move C into the workspace container, between A and BD, (b) move C to the left of A, (c) move focus to A, and (d) move A into the h-split that D is contained ind. A swap command would do this in one action.

If I instead would like to swap A and B, and started by moving B into the workspace container, the CD container would collapse into the workspace container too, and I would have receate the layout of the secondary pane.

If anyone could give me a tip on how to achive such a swap-command using the IPC-interface, that would be great.

**Comment by Airblader** [comment]
Can't this be done via

    mark _last; focus left; swap with mark "_last"

? You can also easily extend it to have focus on the other window, whichever you prefer.

I'm not in reach of a laptop so I can't test this right now.

**Comment by orestisf1993** [comment]
Yes. You can also use `i3-msg "focus left; swap with id $(xdotool getwindowfocus)"` if you don't want to affect your marks.

**Comment by Airblader** [comment]
Although you have to take care with that one — you need to actually expand that subshell before issuing the command. :-) Tricky!

You can also use `mark --add` to be safe. The mark won't interfere and is invisible.

**Comment by NikolajSimling** [comment]
Thank you very much - it works like a charm!

I still think it should be a primitive, though.

**Comment by Airblader** [comment]
I actually think I view `swap` as more of a framework used in scripts to do something truly useful. In this case, `swap left` is so trivially implemented with a couple of commands that you can even bind it directly in the i3 config – I'm not sure a separate command is actually necessary. @stapelberg What do you think?

**Comment by stapelberg** [comment]
I agree with @Airblader’s assessment. If use-cases like this can be covered with the combination of a few of our primitives (mark, focus, swap), that’s fine, and we shouldn’t introduce new primitives which duplicate that functionality.

Closing as a solution was found.
