### ISSUE TITLE
font size changed after a distro upgrade

### ISSUE THREAD

**Issue by magnetophon** [i3/i3#3063]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.14.1 (2017-09-24) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.14.1 (2017-09-24) (pid 1442)abort…)
Loaded i3 config: /home/bart/.config/i3/config (Last modified: Thu 23 Nov 2017 11:55:34 PM CET, 610257 seconds ago)

The i3 binary you just called: /nix/store/1y1w4h6dyhpcg4205pajfyahspszl9b5-i3-4.14.1/bin/i3
The i3 binary you are running: /nix/store/1y1w4h6dyhpcg4205pajfyahspszl9b5-i3-4.14.1/bin/i3

URL to a logfile as per https://i3wm.org/docs/debugging.html:

https://logs.i3wm.org/logs/5729940565655552.bz2

**What I did:**

update of my distro: NixOS unstable

**What I saw:**

The font in both i3bar and the i3 title windows got bigger.
Screenshots: https://imgur.com/a/QeUbo
(I was able to make these cause NixOS allows you to boot into earlier versions)

**What I expected instead:**

No change.

I'm not sure if i3 caused this.
Both screenshots are with 4.14.1.
I found this in my distro changelog:
``pango: maintenance 1.40.12 -> 1.40.14``
but I don't think it's related, since https://github.com/GNOME/pango/blob/master/NEWS doesn't mention anything that seems relevant.

**Comment by seebs** [comment]
check xdpyinfo for DPI? I've had font size changes be because something changed the reported DPI and X was trying to help.

**Comment by magnetophon** [comment]
@seebs that's unlikely, since the other programs and the desktop image look exactly the same.

**Comment by Airblader** [comment]
Have you updated i3 within this distro upgrade? We are now reading the DPI from the Xresources, if set, rather than calculating it.

**Comment by magnetophon** [comment]
@Airblader No, I was on 4.14.1 before the upgrade as well.

**Comment by magnetophon** [comment]
In the NixOS irc I learned that the issue is not with i3. Thanks for your time.
