### ISSUE TITLE
"i3 has just crashed"  everytime I start the computer

### ISSUE THREAD

**Issue by WooHooDai** [i3/i3#3088]
**Output of `i3 --moreversion 2>&- || i3 --version`:**
Binary i3 version:  4.14.1 (2017-09-24) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.14.1 (2017-09-24) (pid 832) abort…)

**URL to a logfile
http://paste.ubuntu.com/26183959/

**What I did:**
Just start the computer, and then login with i3

**What I saw:**
a dialog told me

```
i3 has just crashed.Please report abug for this
To debug this problem, you can either attach gdb or choose from the following options
..........
```

**What I expected instead:**
fix the issue

**Comment by Airblader** [comment]
The log file doesn't really contain anything. Can you provide the backtrace please?

**Comment by WooHooDai** [comment]
@Airblader 
sorry, please check this: http://paste.ubuntu.com/26183959/

**Comment by Airblader** [comment]
It looks like you don't have the debug symbols installed. What does `file $(which i3)` say? You can refer to [this page](https://i3wm.org/docs/debugging.html) on how to get the backtrace. I apologize for the trouble, but unfortunately we can only fix something once we know what's wrong. :-)

**Comment by WooHooDai** [comment]
`file $(which i3)` returns the result with "stripped".I tried to install i3-wm-dbg, but the result didn't change.
And i don't know how to turn off stripping. So sorry for I can't provide the backtrace.
However, I removed the line `force_xinerama yes` in my config file, and then problem solved.

Thank you for the guide page, it reminds me to notice config file. @Airblader
