### ISSUE TITLE
feature request:  Add workspace vars to support DRY when customizing

### ISSUE THREAD

**Issue by tpraxl** [i3/i3#3099]
**Add workspace vars to support DRY when customizing**

Relabeling the workspaces currently requires the user to update the labels at least in two places of the i3 config file (switch to workspace + move focused container to workspace) to keep a consistent state.

This gets even worse when the user starts to reference the workspaces elsewhere, e.g. for assigning containers to specific workspaces.

We could support the DRY principle when the user customizes i3 in the config file by providing workspace variables. Relabeling the workspaces would then merely be a matter of changing the respective variable (`$ws1`, `$ws2`, … `$ws10`).

See [my fork commit](https://github.com/tpraxl/i3/commit/0600b11d2b151fa034cd6bdfa2ad4ccdcfe1f184) for a possible PR if you consider this feature request to be wanted.

**Comment by Airblader** [comment]
We already have [variables](https://i3wm.org/docs/userguide.html#variables), so there's nothing to implement here.

**Comment by tpraxl** [comment]
@Airblader 

The feature request leverages the usage of variables. The feature is a simple change in the default config that supports DRY when customizing the config:

The change results in the following initial config setting (example):

```
# Define workspaces along with their labels
#
# Customize your workspace labels here.
# Example:
#
# set $ws1 "Terminals" 
#
# or
#
# set $ws1 "1: Terminals"
#
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# switch to workspace
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace $ws8
bindsym $mod+9 workspace $ws9
bindsym $mod+0 workspace $ws10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5
bindsym $mod+Shift+6 move container to workspace $ws6
bindsym $mod+Shift+7 move container to workspace $ws7
bindsym $mod+Shift+8 move container to workspace $ws8
bindsym $mod+Shift+9 move container to workspace $ws9
bindsym $mod+Shift+0 move container to workspace $ws10
```

It helps users avoiding to start off with labels at several places.

**Comment by Airblader** [comment]
I see; I misread your issue as something to implement, not a change to the default config. I think this change is fine to also make variables more easily discoverable as a feature. Please feel free to just send the PR.

**Comment by tpraxl** [comment]
Done: [PR](https://github.com/i3/i3/pull/3101)
