### ISSUE TITLE
rxvt-unicode resizing issue in floating mode

### ISSUE THREAD

**Issue by git-heisenberg** [i3/i3#3106]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.14.1 (2017-09-24) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.14.1 (2017-09-24) (pid 511) abort…)
Loaded i3 config: /home/davide/.i3/config (Last modified: Wed 27 Dec 2017 11:59:44 AM CET, 25497 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per https://i3wm.org/docs/debugging.html:

https://logs.i3wm.org/logs/5734977488551936.bz2

**What I did:**

1. open urxvt (alb+enter)
2. make it float (alt+shift+space)
3. enter resize mode (alt+r)

**What I saw:**

*Horizontally* you can reduce the window size (left arrow) but NOT increase it (right arrow)

**What I expected instead:**

Obvious. 
Note: other windows works correctly.

**Attempted Fixes**

Laptop throwed outside the window

**Comment by Airblader** [comment]
https://github.com/Airblader/i3/issues/137
https://faq.i3wm.org/question/6989/resize-issue-with-urxvt.1.html
