### ISSUE TITLE
Window focus not changing on click

### ISSUE THREAD

**Issue by bitdivision** [i3/i3#3108]
Output of `i3 --moreversion 2>&- || i3 --version`:
```
Binary i3 version:  4.14.1 (2017-09-24) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.14.1 (2017-09-24) (pid 1597)abort…)
Loaded i3 config: /home/bitdivision/.i3/config (Last modified: Wed 03 Jan 2018 23:03:06 GMT, 642 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```
URL to a logfile as per https://i3wm.org/docs/debugging.html:

https://logs.i3wm.org/logs/5739578472267776.bz2

**What I did:**

1) Booted computer
2) i3 was started through .xinitrc
3) Opened two terminal windows using Ctrl + enter (urxvt-patched)
4) Clicked on the first terminal window after the second one got focus on opening it.

**What I saw:**

i3 did not change window focus to the first terminal window

**What I expected instead:**

i3 to change window focus

**Comments**

I've tried to keep this as simple as possible to help debugging but can certainly perform more actions and upload the log if it helps.

A general description would be:
Window focus is behaving extremely strangely, sometimes working, sometimes not. I'm running archlinux with a dual screen setup. Switching between windows does not work via the mouse (in that keyboard input still goes to the wrong window). If I use keyboard commands, switching windows works fine.

If I select some text in the unfocused terminal, the selection is displayed in the (still) focused one.

The only way I have found to get around this is to restart i3 while the mouse cursor is hovered over the correct window.

I have tried running xev to make sure the mouse click is working properly, it doesn't show anything when I click until I can hover over the xev window and restart i3. Switching windows to it via the keyboard doesn't help. Only restarting i3 seems to do the trick.

Chromium behaves extremely strangely too, when I restart I3 to get focus on it, the page itself will accept mouse input, however the tab bar and address bar do not respond to click events. I would imagine the chromium window system is complex though, so perhaps this isn't very useful.

I do not have `focus_follows_mouse` enabled, but if I do enable it, things do work a little better.

Please let me know if there's anything else I can do to help debug this.

**Comment by bitdivision** [comment]
I also wonder whether #2778 is related, given the workaround for that also working here, and someone else commenting 4 days ago saying they were having the same issue.

**Comment by bitdivision** [comment]
This also happens on 4.14-214-g59e2b7d4 (2018-01-02, branch "next"). Installed via i3-git package on archlinux.

**Comment by bitdivision** [comment]
I've found a more permanent workaround. Exiting i3 using `Ctrl-Shift-E` and running `startx` fixes the issue for the rest of that session.

For completeness I've recorded the same log as I did originally (same version), but this time I:

- Open two urxvt-patched windows
- Click around between the two not seeing any focusing.
- Press Ctrl-Shift-E to exit
- Run `startx`
- Open two urxvt-patched windows
- Record the log in one of those terminal windows.

https://logs.i3wm.org/logs/5722721933590528.bz2

Please do let me know if there's anything else I can do to solve this more permanently, or even where to start looking for a solution. I'm happy to submit a PR if I know roughly where to start looking

**Comment by Airblader** [comment]
When you say you start i3 through the xinitrc, does that actually mean startx as well? So to clarify, for every boot of your machine i3 is broken the first time you start it but killing the entire X server and starting it in the exact same way fixes it? That would really surprise me.

**Comment by bitdivision** [comment]
That is indeed exactly what I'm saying @Airblader. I was going to try your branch 'focus-in-root'. Is that worth doing?

**Comment by Airblader** [comment]
> I was going to try your branch 'focus-in-root'. Is that worth doing?

No, that's something else entirely.

To clarify more, you start X and i3 on boot by also typing `startx` into the VT? So the way you start it initially (when broken) and for the second time (when fixed) is the same keystroke for keystroke?

**Comment by bitdivision** [comment]
@Airblader Yes, the sequence is as follows:

1) Boot
2) Login
3) `startx`
4) Broken focus
5) `Alt-Shift-E`
6) `startx`
7) Focus fixed.

My xinitrc is https://github.com/bitdivision/dotfiles/blob/master/host-ArchBox/xinitrc with some minor changes

**Comment by bitdivision** [comment]
Now that you've shown so much incredulity at this, I'm wondering if this could be something else that is started in xinitrc and takes time to initialise, or just a time between boot and startx issue.

I'll do some testing later to rule both of those out.

**Comment by bitdivision** [comment]
I'm no longer able to reproduce this. I have run a system update which could have helped.

In any case, I'll close this for now and reopen if I ever see it again.

**Comment by bitdivision** [comment]
This has happened to me again. It seemed to start after I opened Steam.

**Comment by orestisf1993** [comment]
See #2722, #3096

**Comment by bitdivision** [comment]
@Airblader said that this was unrelated to the focus-in-root branch which he mentioned in #3096 .

I'm also seeing this happening across reboots, so unless there is some state that is reloaded on startup, I can't see how the same issue would apply?

**Comment by vtavernier** [comment]
I am observing the exact same behavior on Debian 9, on i3 4.13-1 (but the issue occurs also on 4.14.1-1 and 4.15 from Debian's testing and unstable).

Output of `i3 --moreversion` : 
```
Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
(Getting version from running i3, press ctrl-c to abort…)
Running i3 version: 4.13 (2016-11-08) (pid 1654)
Loaded i3 config: /home/vincent/.config/i3/config (Last modified: mar. 13 mars 2018 20:40:12 CET, 204 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

Debug log : https://logs.i3wm.org/logs/5657019268726784.bz2

Reproduced by : 
* Login into tty
* `startx`
* Create two terminal emulators using Mod+Enter
* Switch focus between them using keyboard : works
* Switch focus using mouse left click : not working
* Exit i3
* `startx`
* Mouse focus works correctly

**Comment by vtavernier** [comment]
On my setup, switching to a tty (e.g. CTRL+ALT+F2) and back to i3 resolves the issue without having to restart X.

This issue also happened to me when using bspwm, so it might be related to some X component instead of i3. According to https://bugs.launchpad.net/ubuntu/+source/xorg/+bug/1316873 there might be a lot of reasons for a suddenly failing left mouse button (including having the nvidia proprietary driver, a mouse with extra buttons, etc.)

**Comment by ajmar** [comment]
I also have this issue, reswitching TTYs seems to fix it for the remainder of the session. It's really strange, if I click on my bar at the top (polybar), wherever I click the mouse is stuck to the bar window.

Seems related to this (closed) issue: https://github.com/i3/i3/issues/2778

**Comment by ajmar** [comment]
Edit: I managed to fix it by finding [this](https://www.reddit.com/r/archlinux/comments/5rmo6o/bspwm_i3_mouse_does_not_focus_focus_is_stuck_on/difzyqr/) post. I have a Razer DeathAdder and I used xev to find that the left click button was firing off `button 2` as well. So I set ButtonMapping to "1 0 ...". I also used MatchUSBID instead of MatchProduct. At least in my case it seems to maybe be a hardware bug (my mouse is modified, didn't notice anything before).

@Airblader @bitdivision can you try this fix if you still have access to the mouse you had problems with? Otherwise this issue can probably be closed, it's most likely a hardware issue, or at least not a bug with i3.

**Comment by mjmoore** [comment]
Adding my results here. I have a Cyborg RAT 3 mouse and was experiencing the same issue. Problem was only resolved using `MatchUSBID`; `MatchProduct` had no effect.

```sh
$ lsusb
...
Bus 001 Device 007: ID 06a3:0ccc Saitek PLC Cyborg R.A.T.3 Mouse
...

$ cat /etc/X11/xorg.conf
Section "InputClass"
    Identifier "Mouse Remap"
    MatchUSBID "06a3:0ccc"
    MatchDevicePath "/dev/input/event*"
    Option "ButtonMapping" "1 2 3 4 5 6 7 8 9 0 0 0 0 0 0"
EndSection
```

Thanks for the help @etylermoss!
