### ISSUE TITLE
[enhancement] Set mark on window when opening with exec (redux)

### ISSUE THREAD

**Issue by dansteen** [i3/i3#3109]
Some years back there was a good discussion about this in #1682 .  At the time it was determined that the use-case just wasn't there to make it worthwhile.  What with the proliferation of in-browser web-apps it may be time to reconsider.  As an example,  I typically run five to ten different "applications" in a web browser that I would like to be addressable from my window manager.   These are things like, email, chat programs, ticketing systems, management tools and more - all of which run inside a browser.   

To accomplish this there are a few options:

1. Run seperate browser instances
This works - especially when coupled with something like electron and nativefier where each instance can have its own name and properties.  The trouble is that each of these instances is a huge resource hog.   Running more than six or seven of these at the same time will bring a quad-core system with 16g of RAM to its knees.   This makes it not really feasable at any sort of scale.

2) Attempt to address the individual applications by their `title` properties.  
This also works -  most of the time.  Unfortunately, the usability of this entirely depends on the websites you are using.  Browsers typically modify the window title based on the page you are on.  Some web pages, like google inbox, will maintain a fairly consistent set of window titles, while others, like the AWS console, don't.   This makes addressing based on `title` error-prone at best and broken at worst.   

I know that in the past the opinion has been that the application author needs to fix their application, and that being unable to use class, title, instance or other window properties is a broken behavior.   However, I think that since the landscape has changed in the direction that it has, and since we are using the same "binary" (web browser) to access multiple "applications" (web pages) it may be beneficial to provide some funcationality for this use-case.

-Thanks!

**Comment by Airblader** [comment]
I'm sorry, but I don't follow. Are these multiple apps even all running in separate windows? Or just as browser tabs? Also, how are you starting these apps using `exec`?

**Comment by Airblader** [comment]
On another note, what was mentioned in the referenced issue holds true for i3 as well. Running a binary and a window opening are simply completely different things. A process can open none, one or many windows. It can do so "right away", five hours later and open different windows at different times. Setting a mark "on a process" simply doesn't work conceptually.

**Comment by dansteen** [comment]
@Airblader thanks for the response! 

The basic idea is that each one is running in a separate window ( I agree that if they were running in different tabs in the same window it wouldn't make much sense).   The goal is to be able to call each of those windows at will - without having to resort to the title of the window which may be arbitrary since *all* web browsers (by default) title the window using the webpage title (which is up to the webpage author to set - and they are not following the same guidelines as standard gui developers - rightly or wrongly).   

As far as processes and windows go, the idea would be to mark any windows that opened as a result of a process being run.   You mention 

> A process can open none, one or many windows. It can do so "right away", five hours later and open different windows at different times. Setting a mark "on a process" simply doesn't work conceptually.

I see what you are saying here.  I suppose the idea would be that all windows opened by the command that we ran via exec would get marked.   But I definitely hear the complixity of that.  There are times when a command will just be a message to another process which then opens the window (`i3-msg` would be a prime example of that sort of messaging).

Is there a parent-child relationship between windows that a process runs and the process itself?  Could the PID of the exec'ed command be tracked and any window that is started that has an ancestor of that PID would get marked?  Obviously this wouldn't work in the case of the "messaging" mentioned above, but in other cases woudl that work?

**Comment by Airblader** [comment]
There are some mechanisms such as _NET_WM_PID or perhaps startup notifications, but they all require the support of the client and support os generally pretty bad. And if you need support from the client you might as well use the mechanisms that already exist.

There simply is no reliable way to associate a process and the windows opened by it. The best we do here right now is startup notifications.

The specs to allow this functionality exist and big browsers not wanting to add better control over these things is a pity, but it's a client problem, not a window manager problem.

I still don't understand how you start these web apps, though. I doubt that you actually start individual web apps using exec? So even if this association was possible, how would that help?

**Comment by dansteen** [comment]
I actually do start them from the exec line:

``` bindsym $mod+i exec firefox -P apps --new-window inbox.google.com```

That opens a new window for that specific site.

**Comment by Airblader** [comment]
But if you start the app explicitly using exec like that, why not pass a flag to that program that sets `WM_CLASS` to some value that you can match on? I don't know if Firefox supports that, but if they don't, they should. As I said, without client support we cannot ever match windows with processes anyway.

**Comment by Airblader** [comment]
I'm going to close this for the following reasons:

1. There is no good way to correlate processes and windows without support from the client itself. So the situation is just unchanged here.
2. The specific use-case presented could be solved with a `firefox --class my-app`, assuming firefox supports some kind of flag like that. And if they don't, they should. Since we need client support one way or another, there's no loss or gain here.

We can keep discussing this if there is something worth discussing further, of course.
