### ISSUE TITLE
i3 crashing when running PYWAL, going back to normal after resolution change

### ISSUE THREAD

**Issue by fusion4bass** [i3/i3#3125]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.14.1 (2017-09-24) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.14.1 (2017-09-24) (pid 416) abort…)
Loaded i3 config: /home/obi-wan/.config/i3/config (Last modified: Tue 30 Jan 2018 07:41:45 PM CET, 6322 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per https://i3wm.org/docs/debugging.html:

https://logs.i3wm.org/logs/5760586365272064.bz2

**What I did:**

What happens is I can run wal from console but not from i3 startup nor bindkey.
I'm using pywal 1.2.2 on ARCH Linux guest OS on VirtualBox with Guest Additions

**What I saw:**

 - bind key in i3 to run wal
 - hit key
 - x11/i3 (or both?) crashes and screen goes back to console
 - I hit "ctrl+F" which is shortcut to change display mode from fullscreen to window on virtualbox
 - once guest OS is in window mode, i3 comes back to life with newly loaded pywal colorscheme and wallpaper

It might have something to do with resolution change once display mode is changed.

I've tried to look into i3 dump log to check if that's i3 problem but couldn't find any clue.

**What I expected instead:**

Pywal running changing color scheme without problem just as ran from console.

**Comment by orestisf1993** [comment]
Do you still have this issue? Could you perhaps acquire a backtrace?

> once guest OS is in window mode, i3 comes back to life with newly loaded pywal colorscheme and wallpaper

how do you start i3? if i3 crashes then all your windows should be lost on when logging in again.

**Comment by orestisf1993** [comment]
Inactivity
