### ISSUE TITLE
Electron apps (specifically Discord and Slack) receiving notifications causes windows to not appear

### ISSUE THREAD

**Issue by SeanMcLoughlin** [i3/i3#3130]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.14.1-151-g13185fe2 (2017-10-07, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.14.1-151-g13185fe2 (2017-10-07, branch "gaps-next") (pid 488)
Loaded i3 config: /home/smclough/.config/i3/config (Last modified: Tue 30 Jan 2018 06:43:43 PM EST, 491178 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

**What I did:**

Started [discord](https://discordapp.com/), switched to a new workspace, received a notification in discord,, switched back to the workspace that the discord window was on.

**What I saw:**

The window disappears. If no more notifications are received, the window reappears after about a minute. Reloading i3 causes the window to appear black. Swapping workspaces to it again causes the window to not appear.

**What I expected instead:**

The windows to appear after switching back to the workspace that the window is on.

Log File: https://logs.i3wm.org/logs/5716959832309760.bz2

**Comment by vmarovic** [comment]
I have the similar issue. After receiving a message when switching to workspace slack or skype is on, slack window is ether blank(white) or is showing random page that is open in browser. I am also unable to kill it using i3.
This seems to only occur if the app receives message while window is not in focus.

**Comment by Kruptein** [comment]
I'm also having this issue which means I have to use both discord and slack in browser as the applications are unusable for me.

**Comment by ixjlyons** [comment]
I ended up using a notification daemon (e.g. lxqt-notificationd) to fix this issue after running signal-desktop from a terminal and seeing it shows some error about pushing a notification. I'm not sure if it's an Electron issue or if it has to be fixed for each application, but it doesn't seem to be an i3 bug.

**Comment by raymoo** [comment]
This happens for me on any notification at all, electron application or not. I'm not sure what the problem is, and it only happens on one of my computers.

**Comment by bartekbrak** [comment]
@ixjlyons Can you describe your fix in more detail, please?
WIll disabling notifications from the app (in my case it's [Franz](https://github.com/meetfranz/franz), a slack client)?

**Comment by ixjlyons** [comment]
@bartekbrak either Electron or the applications using it don't seem to be handling the condition in which your system doesn't have a notification daemon running, so it hangs. I would think that if the application has an option to disable notifications, that would be fine. Other options would be to run i3 as a window manager inside a desktop environment that provides a notification daemon, or as I suggested before, run a notification daemon like dunst or lxqt-notificationd yourself from your i3 config.

This isn't an i3-specific problem, so I think this issue can be closed.

**Comment by orestisf1993** [comment]
Thanks for the info :)

**Comment by ThoreKr** [comment]
Unfortunately installing dunst didn't resolve this issue for me. It still affects most electron apps and chrome (though chrome magically recovers after some time). 
Usually with nouveau this problem only appeared in the first few days after a reboot but persisted when loading the nvidia drivers.

This changed insofar as I now don't get past two days of uptime because a notification (no consistent pattern, so far two applications triggered it) froze my entire system.

**Comment by AngeloNicolson** [comment]
I was having this problem with slack and discord. I just installed dunst and it worked for me. 
I have not tested lxqt-notificaitond as a fix, but I would assume this would work as well.

```
sudo apt update
sudo apt install dunst
```

**Comment by 0xTiger** [comment]
In my case I had dunst installed but it was not running, so I needed to add 
`exec --no-startup-id dunst`
to my i3 config file
