### ISSUE TITLE
Resize with mouse warps cursor to bottom right of viewport

### ISSUE THREAD

**Issue by JayGoldberg** [i3/i3#3139]
Output of `i3 --moreversion 2>&- || i3 --version`:

$ i3 --moreversion 2>&- || i3 --version
Binary i3 version:  4.14.1 (2017-09-24) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.14.1 (2017-09-24) (pid 182522)ort…)
Loaded i3 config: /home/rmrf/.i3/config (Last modified: Mon 12 Feb 2018 01:30:33 AM CST, 51796 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per https://i3wm.org/docs/debugging.html:

https://logs.i3wm.org/logs/5656846262075392.bz2

**What I did:**

Resize window with mouse.

**What I saw:**
Cursor snaps to bottom right of viewport immediately. If you continue to drag, the window resize hinting ruler appears to the extreme right of the viewport. You can of course drag it back, closer to where it already was, but the behavior is weird.

Even when clicking the resize title (with left button, or Alt+rightbutton) and not moving the border at all, the mouse is warped to (-1,-1).

No mouse warping occurs when using Super+R (keyboard resize).

All mouse warping is turned off in config.

**What I expected instead:**
Previously, the behavior was to allow resizing of a window edge from its existing position.

**Comment by JayGoldberg** [comment]
Yes, I have! That' it.

On Feb 25, 2018 09:20, "Alex Lu" <notifications@github.com> wrote:

Have you set your input device's coordinate transform matrix other than
identity matrix? If so, I guess it is caused by this xorg-server bug
<https://bugs.freedesktop.org/show_bug.cgi?id=97263>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/i3/i3/issues/3139#issuecomment-368317617>, or mute the
thread

**Comment by stapelberg** [comment]
IIUC, this is an issue somewhere else. Closing.
