### ISSUE TITLE
Enhancement request: readline/history support for i3-input

### ISSUE THREAD

**Issue by eater** [i3/i3#3149]
I use i3-input a lot, both to issue commands directly and as part of scripts. It would be a significant improvement if it supported GNU-Readline style editing of the input line, and recall of previously entered lines.

**Comment by Airblader** [comment]
i3-input is really only meant to be a reference implementation. I think it would probably be better to write a separate tool dedicated for such advanced usecases.

**Comment by stapelberg** [comment]
I agree with @Airblader.

I also thought there already are tools which fulfill the description. Rofi seems popular and can likely be used just like i3-input: https://wiki.archlinux.org/index.php/Rofi
