### ISSUE TITLE
App execution doesn't follow active workspace [Feature Request]

### ISSUE THREAD

**Issue by killown** [i3/i3#3154]
I would like to know if there is a way to implement a "doesn't follow the active workspace"
Example:
started app1 in workspace2, the app takes 10 seconds to start, while that the user switched for workspace1, the normal behavior is that the app will start on workspace1 but my proposal is to make i3-msg exec --no-follow-active-workspace app to start from the workspace that the command was started

**Comment by Airblader** [comment]
This already works thanks for startup notifications. If it doesn't work for a specific application, please open an issue against it asking them to implement the specification.

A process and a window are different things that i3 cannot correlate without help from the application.
