### ISSUE TITLE
[feature request] Add basic cheatsheet with keybindings and some help information

### ISSUE THREAD

**Issue by omtcvxyz** [i3/i3#3209]
There is one feature from Awesome WM I really liked and I miss it in the i3: a cheat sheet. Awesome WM offers a default key binding to open an interactive cheat sheet which looks roughly like [this one](https://github.com/cmichi/awesome-cheatsheet/blob/master/awesome.pdf). It really helped me to learn the hotkeys faster and whenever I forget them I simply opened this help.

I wonder if you'd be willing to add some pretty basic cheat sheet by default to i3 (for example something like [this one](https://gist.github.com/JeffPaine/cbdf57c3721546b14113)). I think it would allow users to learn faster and quickly access the forgotten key bindings, I feel like not having such thing and having to open browser and documentation every time I would like to do something pretty easy really affected my learning curve in a bad way since I managed to learn most Awesome key bindings quicker.

**Comment by Airblader** [comment]
Thanks for the issue. I agree that such a cheat sheet might be a neat thing for some users; however, I think that it's perfectly doable outside of i3 as a separate tool. That way it can be maybe more customized and is independent of core i3, plus we can avoid the complexity for this in i3.

If you do write such a tool, make sure to link it and perhaps also send a PR to mention it in the docs!

**Comment by Airblader** [comment]
As a side note, with other languages it's probably orders of magnitude simpler to implement this than in C and low-level X.

**Comment by omtcvxyz** [comment]
I see, thanks for the input! I'll probably look into that if I have enough time, but I think a separate tool with a decent integration is a viable solution.
