### ISSUE TITLE
Strange thing with cursor position in firefox (something like double rmc).

### ISSUE THREAD

**Issue by Sonahaim** [i3/i3#3216]
First of all, i'm not absolutly sure that this bug related with i3. The only thing i know it appeared at around the same time i updated i3 to 4.15

Output of `i3 --moreversion 2>&- || i3 --version`:
Binary i3 version:  4.15 (2018-03-10) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15 (2018-03-10) (pid 8952)o abort…)
Loaded i3 config: /home/sonahaim/.config/i3/config (Last modified: Sat 31 Mar 2018 10:37:25 PM MSK, 147881 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per https://i3wm.org/docs/debugging.html:
https://logs.i3wm.org/logs/5692158946312192.bz2

**What I did:**
Right clicked in firefox window.

**What I saw:**
Instant click on "Back" button in context menu.

**What I expected instead:**
Context menu.

Here is a pic of context menu in firefox.
![rmc](https://user-images.githubusercontent.com/37549841/38196789-9cd141fc-368d-11e8-8c0b-dd49fbed3952.png)

When i RMC in firefox in any DE or WM but i3 i get my cursor position a little bit out of the context box (above the left top corner). When i do the same thing in i3 my cursors appears right on the "Back" button and click happens immediately. So i get previous page if i don't move cursors while RMC is pressed.
Tested in DWM, Xfce4, Mate.

**Comment by orestisf1993** [comment]
https://www.reddit.com/r/i3wm/comments/88k0yt/right_mouse_btn_instantly_clicks_first_option_in/

I am closing this since it appears to be a firefox bug, please reopen if you think otherwise.

**Comment by orestisf1993** [comment]
Also, I don't have this bug with firefox-beta but I do get it with regular firefox

**Comment by Sonahaim** [comment]
Thanks a lot for the link. Seems like that solution with userChrome works perfectly.
