### ISSUE TITLE
Enhancement: Allow borders to go all the way around a container.

### ISSUE THREAD

**Issue by indeedwatson** [i3/i3#3219]
As it is, tabbed and stacked containers have the window border just disappear, I always found this design unintuitive: https://u.teknik.io/rp3Iq.png

Having the border go all around the container gives it a more finished and clean look: https://u.teknik.io/QjfQQ.png

The second screenshot is using [tabbed](https://tools.suckless.org/tabbed/), but I don't want to use that because the tabs don't interact with the wm like i3's do, so it would be nice to be able to replicate that look.

**Comment by ym1234** [comment]
+1 I would like also to have more customizability in general with how tabs look, without having an to use external tool that doesn't integrate well with i3.

**Comment by Airblader** [comment]
The way you showed in the second picture simply isn't reasonably possible with i3: different windows can have different borders and we always show the border of the currently focused tab; so this would mean constantly resizing the tabbed container when switching tabs. I don't think that's a good idea.

The only option would be drawing the top border between the tabs and the client, which IMHO looks terrible, but more importantly there really isn't a good reason for why this should be changed. 

i3 is not an eye candy window manager. Unless we have a convincing reason for why a change is objectively better, we're not looking to change the look & feel, sorry.

**Comment by indeedwatson** [comment]
I don't follow what you're saying. I used tabs pretty extensively, and I don't know what you mean by "different windows can have different borders". Isn't the border size across all windows the same?

How is a top border different than a bottom or side border?

>i3 is not an eye candy window manager. Unless we have a convincing reason for why a change is objectively better, we're not looking to change the look & feel, sorry.

Well it's about consistency. It is clear that i3 is not made by visual designers, but shouldn't that be all the more reason to reevaluate some design choices that can't be justified with anything other than "that's how it was at first so we're not gonna change it".

**Comment by Airblader** [comment]
> Isn't the border size across all windows the same?

No, it is not. Try opening a bunch of terminals (in a tabbed container, if you want). Then run `i3 border normal 5`, `i3 border normal 10` and `i3 border normal 50` in one each.

> How is a top border different than a bottom or side border?

In tabbed and stacked containers, the client border is taken away from the client window's size. With left, right and bottom borders, this doesn't affect the titlebars. A top border in the way you described, however, would have to affect the titlebars.

> Well it's about consistency.

Consistency with what? Random other tools?

> but shouldn't that be all the more reason to reevaluate some design choices that can't be justified with anything other than "that's how it was at first so we're not gonna change it"?

Sure, as I said: if you have an objective reason for why one design is better than the other, we can weigh the options. As long as we don't have one, the way things are is both the least effort and the best option we have as it doesn't subject users to changes that aren't motivated by anything.

**Comment by Airblader** [comment]
Just as an example, we introduced `tray_padding` because the objective argument of Fitt's Law was made in #1700.

**Comment by indeedwatson** [comment]
>As long as we don't have one, the way things are is both the least effort and the best option we have as it doesn't subject users to changes that aren't motivated by anything (useful / nothing entirely up to personal preference).

Since you're the main dev of i3-gaps, how do you objectively justify gaps? It seems like the epitome of eye candy. Or are you saying this kind of suggestion would be more welcome in i3-gaps than here?

I'm not throwing a jab at i3-gaps, I use it, but that argument seems as inconsistent as the borders.

>Consistency with what? Random other tools?

Consistency with itself.

If I do this:

> Try opening a bunch of terminals (in a tabbed container, if you want). Then run i3 border normal 5, i3 border normal 10 and i3 border normal 50 in one each.

with a single window, then the whole border changes size. If I do it in a tabbed container, then suddenly the top border disappears. This is inconsistency, a border is a border, and it's function is to separate containers visually. The function of tabs is different, it's to display information such as window title.

>With left, right and bottom borders, this doesn't affect the titlebars.

It still affects the overall size of the window, which invalidates what you said earlier "so this would mean constantly resizing the tabbed container when switching tabs". This already happens by allowing inconsistent border sizes (which I have nothing against, I just never used this feature).

I think what I'm saying is pretty objective: a border is a border, and it has a specific function, particularly in a tiling WM. It shouldn't just disappear for some reason. If we were talking about floating WM, where you will mostly see fullscreen or floating windows that inconsistency isn't as important.

I will show a picture of an edge case to make my point: https://u.teknik.io/3O6NI.png

From a design point, that is "visually communicating to the user what's goin on", that's a mess.

**Comment by orestisf1993** [comment]
> with a single window, then the whole border changes size. If I do it in a tabbed container, then suddenly the top border disappears. This is inconsistency, a border is a border, and it's function is to separate containers visually. The function of tabs is different, it's to display information such as window title.

when you are using pixel border, not "normal border"

> I will show a picture of an edge case to make my point: https://u.teknik.io/3O6NI.png

You use the same colours for `client.unfocused` and `client.focused_inactive` right?

**Comment by indeedwatson** [comment]
>when you are using pixel border, not "normal border"
What's the difference?

>You use the same colours for client.unfocused and client.focused_inactive right?

Yeah, cause I only care about highligting the active tab, just like I do on firefox or ranger or any other application with tabs. What does it have to do with borders tho?

**Comment by orestisf1993** [comment]
> Since you're the main dev of i3-gaps, how do you objectively justify gaps? It seems like the epitome of eye candy. Or are you saying this kind of suggestion would be more welcome in i3-gaps than here?

Bad argument since gaps are not merged with i3? One of the reasons being its conflict with title bars: https://github.com/Airblader/i3/issues/64#issuecomment-282592446. You can certainly maintain your own patch if you want.

> Yeah, cause I only care about highligting the active tab, just like I do on firefox or ranger or any other application with tabs. What does it have to do with borders tho?

This is a visual mess because the bottom border of the top tabbed container is indistinguishable.

**Comment by indeedwatson** [comment]
This is why I asked

" Or are you saying this kind of suggestion would be more welcome in i3-gaps than here?"

But I have the hunch that that's not the case.

>This is a visual mess because the bottom border of the top tabbed container is indistinguishable.

Why should it be? It's not active, I don't want borders of non active containers calling attention to my eyes.

**Comment by Airblader** [comment]
> how do you objectively justify gaps?

I could justify them, though it's a slightly subjective objectivity since I can't back it with studies. :-) In any case, as you pointed out yourself, i3-gaps is quite different from i3 here. Even if we see gaps as purely eye-candy, i3-gaps just isn't i3 (which is one of two major reasons why i3-gaps is and will continue to be a fork).

> Or are you saying this kind of suggestion would be more welcome in i3-gaps than here?

Yeah, it'd be more something to be discussed in i3-gaps, but to save you the trouble: I don't think I want to add it there, either (feel free to fork it yourself, though). My main goal with i3-gaps is keeping it up to date with upstream and any new feature makes this more difficult.

> This is inconsistency

I'd disagree on that. Not everything that doesn't behave 1:1 in all situations is automatically an inconsistency.

> a border is a border, and it's function is to separate containers visually. The function of tabs is different, it's to display information such as window title.

And a titlebar just implicitly also does the job of the border. The overwhelming majority of users has a border width less than the height of a titlebar, so a titlebar is thicker than the border basically all the time.

I would strongly assume that changing the borders as you suggest would give us at least a few users complaining about the wasted space since the titlebar already does the job of separation. Which is exactly why I'm saying that I don't see a point in upsetting users over a matter of taste.

> It still affects the overall size of the window, […] This already happens by allowing inconsistent border sizes

No, it does not. It only affects the client window, not the container.

**Comment by indeedwatson** [comment]
>I'd disagree on that. Not everything that doesn't behave 1:1 in all situations is automatically an inconsistency.

If it doesn't, it should have a reason. But I'm not sure how you can disagree that having a border disappear is not inconsistency, objectively.

>And a titlebar just implicitly also does the job of the border. 

It does for a floating WM or in fullscreen. As shown in the screenshot, it doesn't when tiling vertical splits.

> No, it does not. It only affects the client window, not the container.

Why is one worse than the other? As the user, all I see is inconsistent changes in window sizes, regardless if it's container or window.

**Comment by Airblader** [comment]
As for the screenshot: you can use a different color for border and child_border (see userguide). If you have titlebars disabled for normal windows anyway, then it won't bother you there.

![screenshot-2018-04-03_22-39-45](https://user-images.githubusercontent.com/2392216/38274749-f1d9720c-378f-11e8-875d-d1ba6e407978.png)

**Comment by Airblader** [comment]
> Why is one worse than the other? As the user, all I see is inconsistent changes in window sizes, regardless if it's container or window.

The same client will always have the same size: there is no weird resizing going on. However, applying the border of the focused child to the tabs would mean that the titles in the tabs would jump in all directions everytime you change focus.

**Comment by Airblader** [comment]
> As shown in the screenshot, it doesn't when tiling vertical splits.

And as explained by @orestisf1993 (and my screenshot), that's only because of your choice of colors. The option to color these tabs in a way that makes them stand out more is there; you chose to not do that and that's fine, but that's not a shortcoming of i3.

**Comment by indeedwatson** [comment]
>However, applying the border of the focused child to the tabs would mean that the titles in the tabs would jump in all directions everytime you change focus.

You're explaining what happens but not why it's bad or worse than, say, a firefox window being displayed differently because of different side and bottom borders.

>The option to color these tabs in a way that makes them stand out more is there; you chose to not do that and that's fine, but that's not a shortcoming of i3.

It's a shortcoming to have to use tabs as a separator. Because I precisely do *not* want to make inactive tabs stand out because they are inactive. The active window color serves the function of telling my eyes which window is focused. Having every single tab share that color, even if inactive, makes the color stand out less. It looks decent when one of the tabs is in focus, but if none are it doesn't look great.

A good compromise would be to have that same 1px border, but only the top parts, and only when a tab is selected, this would properly serve the function of separating windows, and also highligting the active window, whether it's a tab or not.

I get the feeling that if the issue was reversed, if all around border was in i3 by default, and per-window border size was not, you'd have the same reluctance about implementing per-window border size, it's kind of discouraging.

**Comment by orestisf1993** [comment]
> You're explaining what happens but not why it's bad or worse than, say, a firefox window being displayed differently because of different side and bottom borders.

Different compared to what?

If I understand the problem correctly here: consider the layout `V[ A T[ B C ] ]` where A, B, C  leaf containers with pixel borders 10, 0, 5 respectively. Focusing B will make the "top" border 0, focusing right will increase the border by 5 pixels, reducing A's or T's size.

Of course you could apply the border to the tabbed container only but then it wouldn't solve the inconsistency.

**Comment by Airblader** [comment]
> You're explaining what happens but not why it's bad or worse than, say, a firefox window being displayed differently because of different side and bottom borders.

I did explain it, but I'll try again with some visual help. Let's say we have `T[A B]` where A has a thin and B a thick border. In the following sketches, the first one shows A focused and the second B focused.

The current behavior is this:

```
+---+---+
| A | B |
+---+---+
|       |
|       |
+-------+

+---+---+
| A | B |
+---+---+
##     ##
#########
#########
```

If you quickly cycle focus between these, the titlebars will stay exactly in place as they look exactly the same. Only the child window part changes, which it has to anyway because you're displaying a different window.

Now, with the proposed change, it'd be this:

```
+---+---+
| A | B |
+---+---+
|       |
|       |
+-------+

#########
#########
# A | B #
+---+---+
##     ##
#########
#########
```

If you cycled through these, the labels ("A", "B") would shift to the inside and downwards everytime you focus B and to the left and upwards everytime you focus A. So you just end up getting a lot of nervous jumpiness in the titlebars. And *that* is what I think is really bad.

> The active window color serves the function of telling my eyes which window is focused. Having every single tab share that color, even if inactive […]

It doesn't have to be the same color as the focused window. You can make it a different one.

> It looks decent when one of the tabs is in focus, but if none are it looks quite bad.

"Looks decent" and "looks bad" is exactly the problem here: that's just entirely a matter of taste. And I'm not saying that I don't understand that or even that I don't agree, but it's not a reason to upset hundreds of users over. i3's look & feel is quite conservative and when I first joined i3, I also wanted to change things around a lot. Over time I have learned that we have a strong userbase that appreciates the way things are and the fact that we do not make these changes light-heartedly.

**Comment by indeedwatson** [comment]
Thanks for the visual explanation. I understand that it is *bad*, but to me that's not *worse* than having 2 firefox containers with different borders having their contents displaced because of the border difference. I understand you're coming at it from "i3 dev" perspective, so to you the tabs moving might be worse than an input box in a website moving around. But to me as a user, they're both equally bad, but not as bad as the disappearance of the top border.

>It doesn't have to be the same color as the focused window. You can make it a different one.

It has to be the same for consistency. If I use a color to highlight a window and separate it from non-highlighted windows visually, then it has to be all the same color: form should follow function. That's why this *is* a limitation of i3, because it doesn't allow me to assign the same color to the same function without confusion. If tab-borders act as an active container border, then they should stop acting as such when no container in the tab group is active.

If I choose an arbitrary color, then it stops functioning as separator of highlighted active container, and has its own function of "separting tabs regardless of state", which is not the function I want.

>"Looks decent" and "looks bad" is exactly the problem here: that's just entirely a matter of taste. And I'm not saying that I don't understand that or even that I don't agree, but it's not a reason to upset hundreds of users over.

It's not just taste, it's function and consistency.

> Over time I have learned that we have a strong userbase that appreciates the way things are

There's also a significant userbase that wants more customization. They can get around it with scripting and that's fine. If I could do what I want with scripts I'd be okay with that, but forking i3 just to add a top border is beyond my knowledge unforntunately.

>but it's not a reason to upset hundreds of users over

Well that's why I worded it "allow borders to go around" rather than "force borders to go around".

**Comment by Airblader** [comment]
> I understand that it is bad, but to me that's not worse than having 2 firefox containers with different borders having their contents displaced because of the border difference.

For the record, it doesn't have to be (and usually probably isn't) two windows of the same app, but can be entirely different windows. I'm sorry you don't understand why that's worse, but to me it very, very clearly is. And it just goes on top of other arguments such as taking up more space than it does right now.

> It has to be the same for consistency. If I use a color to highlight a window and separate it from non-highlighted windows visually, then it has to be all the same color: form should follow function.

That's fine. But i3 is not black and white: we have focused, focused inactive and unfocused. You're not making use of this distinction and that's your choice, but you *could* make use of it.

> There's also a significant userbase that wants more customization.

There sure is, but that's not exactly i3's mission statement. There are other window managers that are better suited if you want to be able to control everything in full detail.

> Well that's why I worded it "allow borders to go around" rather than "force borders to go around".

Making something a configuration requires even more thought, because every additional configuration also brings complexity, both mental and maintenance. When discussing changes, we weigh the benefits versus the cost and in this particular case, I already see the cost outweighing the benefit even if it wasn't a configurable change.

**Comment by indeedwatson** [comment]
> But i3 is not black and white: we have focused, focused inactive and unfocused. You're not making use of this distinction and that's your choice, but you could make use of it.

The function of that distinction is to differentiate those categories. A border serves a different function. Therefore, those settings are not apt for the function of a border.

>Making something a configuration requires even more thought, because every additional configuration also brings complexity, both mental and maintenance. When discussing changes, we weigh the benefits versus the cost and in this particular case, I already see the cost outweighing the benefit even if it wasn't a configurable change.

That's a blanket statement that you could throw to deny any possiblity of improvement save bug fixes. 

Having borders that are different sizes across windows certainly adds to the complexity you speak of, and I question the value of that added complexity when I've *never* seen a setup use different border sizes. So this goes back to what I said earlier that if the example was reversed, you'd be using the same exact arguments to speak against an issue that, in the current way, is a part of default i3.

I understand that you don't want to implement this, but I can't concede that there is a consistent or solid argument behind including certain features that add complexity, and rejecting another.

**Comment by orestisf1993** [comment]
Are you kidding me? Every other post in /r/unixporn uses some kind of custom border. You are comparing the customizability of a pixel value that you are required to get right (if your code works for 5 pixels but not for 10 then something is wrong) vs the addition of a new, non-trivial behaviour.

**Comment by Airblader** [comment]
We don't need to argue about existing features. There certainly are things in i3 and its ecosystem that we wouldn't add again if we had a chance to revisit. But we care a lot about backwards compatibility, thus we don't remove them.

In the specific case of border widths I'm frankly not sure whether the specs might even demand this to be implemented (my internet is broken so I only have my phone).

You're right that weighing benefit versus cost isn't something we can quantify and thus make entirely objective. So ultimately that is just a project decision. And the decision here is to not implement this. I'm sorry if that isn't what you want to hear. 

I think we exhausted this discussion, so I'm going to stop dragging this out further.

**Comment by indeedwatson** [comment]
@orestisf1993 I'm not sure you understood me, I mean different windows with different border sizes. I just went quickly through the newest i3 posts in unixporn and they all have consistent window border (that is, same border size across windows, not across different posts).

**Comment by orestisf1993** [comment]
Ok, but still, tons of people use it if you search around: https://github.com/search?q=bindsym+border&type=Code, https://github.com/search?q=for_window+border&type=Code and I opened a few posts in the subreddit too and some had relevant bindings.

**Comment by Airblader** [comment]
A very common usecase is having borders on certain apps like terminal emulators but not on other apps like browsers.

Also both the existence and width of a border is a core X11 protocol feature. See `man XCreateWindow`.
