### ISSUE TITLE
i3wm not working with AMD driver + LightDM on Fedora and Manjaro

### ISSUE THREAD

**Issue by auyer** [i3/i3#3232]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version: 4.15 (2018-03-10) © 2009 Michael Stapelberg and Contributors

Running version:   < 4.2-200

~~I was unable to collect logs~~ (longs in the EDIT)  . I ran the command in another TTY ( since the graphical one crashed instantly )

The message was this: 

> i3-sump-log: ERROR: Cannot connect to X11. 
> 
> FYI: The DISPLAY environment is set to ":0" 

**What I did:**

After testing i3wm without any specific Video Drivers, I installed the AMD Linux Oficial Driver, rebooted, and tried to log-in. 

**What I saw:**

With the i3 selected, it crashed immediately and returns to the login screen. There was no error message whatsoever.

EDIT: 

Log URL: [https://logs.i3wm.org/logs/5693646749827072.bz2](https://logs.i3wm.org/logs/5693646749827072.bz2)

**Comment by orestisf1993** [comment]
How did you start i3?

**Comment by auyer** [comment]
@orestisf1993 I'm not sure how I'm supposed to start it manually. 

I selected i3 on login as it can be seen in this screenshot from [fedoramagazine.org](https://fedoramagazine.org/getting-started-i3-window-manager/) post:
![i3-01](https://user-images.githubusercontent.com/12375421/38461424-f25da928-3aa5-11e8-9fa0-cfb874a19a86.png) ( this screenshot is not mine, but it is identical to my setup)


It used to work in this same PC (without the AMD drivers), and it still works in a VM.   
My hardware config is: i7-4790, AMD Vega 64, 16GB ram.

**Comment by orestisf1993** [comment]
Select & login with the "(with debug log)" option, see if there is anything under `/dev/shm/i3*`.

If you can't get anything, edit ~/.xinitrc (save the original contents if necessary) to use the following line:
`i3 -d all -V &> ~/i3.log` then run `startx`.

**Comment by auyer** [comment]
@orestisf1993 I've just updated the post with the logs obtained after editing .xinitrc . Thanks for the help.

Logs are now available.

**Comment by orestisf1993** [comment]
My guess is that this is not an i3 issue, the log doesn't indicate anything like that.
