### ISSUE TITLE
Feature request: Allow modifier combinations for the bar modifier

### ISSUE THREAD

**Issue by faulesocke** [i3/i3#3234]
The `floating_modifier` allows any combination of keys. In contrast, the `modifier` of the `bar` section only allows a very limited set of modifiers and combinations of these are entirey prohibited. This behaviour is contra-intuitive and seems inconsistent to me. It would be more useful, if I could use key combinations (for example `Mod4+Shift`) as the bar modifier.

Background:  I'm using the bar to display a lot of information. However, not all the info fits my relatively small screen, therefore I would like to have multiple bars, one appearing when pressing Mod4, the second when pressing Mod4+Shift, etc...

**Comment by Airblader** [comment]
I haven't confirmed this, but if this discrepancy does in fact exist I see no reason not to allow it for i3bar as well.
