### ISSUE TITLE
swap fails when 'first' is behind fullscreen window

### ISSUE THREAD

**Issue by orestisf1993** [i3/i3#3259]
Credits to @nejni-marji

```
Binary i3 version:  4.15-116-ga40bcef4 (2018-04-20, branch "next") © 2009 Michael Stapelberg and contributors
```

URL to a logfile as per https://i3wm.org/docs/debugging.html:
https://logs.i3wm.org/logs/5744017589403648.bz2

**What I did:**

1. workspace 1
2. open 2 windows
3. mark a
4. workspace 2
5. open window
6. mark b
7. workspace 1
8. focus unmarked window, fullscreen enable
9. `i3-msg '[con_mark=a]' swap with mark b`

**What I saw:**

The swap command fails (even though it wouldn't fail if it was executed from workspace 2). a moves to workspace 2, b doesn't move in workspace 1

**What I expected instead:**
Swap succeeds

This is a problem of `con_fullscreen_permits_focusing` in https://github.com/i3/i3/blob/a40bcef4385bfc42920761afc596e538d8c56c30/src/con.c#L1100-L1103
I believe that this function is flawed, especially since it relies on the currently focused container, introducing inconsistent behaviour depending on the focused container instead of the focus stack. I think we can ignore it's output when ignore_focus is set.

**Comment by nejni-marji** [comment]
I found a crash that I think is related, which occurs if
a) the 'second' container is behind the fullscreen, rather than the first
b) the 'second' container is in a horizontal or vertical split (_not_ a tabbed or stacked layout)
c) you try to de-fullscreen the container

**Comment by orestisf1993** [comment]
Thanks. I have a fix for both issues, I'll PR it soon.
