### ISSUE TITLE
_NET_WM_STATE_ABOVE ignored after i3 restart

### ISSUE THREAD

**Issue by bebehei** [i3/i3#3265]
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.15 (2018-03-10) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15 (2018-03-10) (pid 12547) abort…)
Loaded i3 config: /home/bebe/.i3/config (Last modified: Mo 16 Apr 2018 18:20:01 CEST, 767595 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3-with-/i3
```

URL to a logfile: https://logs.i3wm.org/logs/5643944717189120.bz2

**What I did:**

```
git clone https://gist.github.com/bebehei/bf5204254b3d64c9d5468f75b6ca73d8 testcase
cd testcase
make
./x
i3-msg restart
```

**What I saw:**

Until restart the spawned window behaves correctly. But right after restart, it'll get layered behind all other windows. 

**What I expected instead:**

The window stays always on top and doesn't care about an i3 restart.

**Comment by Airblader** [comment]
i3 doesn't support `_NET_WM_STATE_ABOVE`, see `xprop -root _NET_SUPPORTED`.
