### ISSUE TITLE
Modal dialog prevents moving the floating window that spawned it, but doesn't prevent raising

### ISSUE THREAD

**Issue by eater** [i3/i3#3266]
Output of `i3 --moreversion 2>&- || i3 --version`:
```
Binary i3 version:  4.15.0.1 (03-13-2018) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15.0.1 (03-13-2018) (pid 706)bort…)
Loaded i3 config: /home/eater/.config/i3/config (Last modified: Wed 25 Apr 2018 03:17:26 PM EDT, 78640 seconds ago)

```

URL to a logfile as per https://i3wm.org/docs/debugging.html:

https://logs.i3wm.org/logs/5737161613639680.bz2

**What I did:**

I launched pamac-manager in a floating window. I attempted to install a package which caused pamac-manager to spawn a modal dialog window (in front of the main pamac-manager window) informing me of a package conflict.  I then clicked the main pamac-manager window and tried to drag it aside in preparation for resolving the conflict in a terminal. 

**What I saw:**

1. The mouse click raised the pamac-manager window so that it was in front of the modal dialog, hiding it.
2. The floating pamac-manager window did not move when I tried to drag it.

**What I expected instead:**

1. I expected the modal dialog window to remain in front of the window that spawned it.
2. I expected the floating window to respond to my attempts to move it.

**Comment by orestisf1993** [comment]
Are you referring to this dialog?
![img](https://user-images.githubusercontent.com/5778622/39323746-22ce2494-4996-11e8-9ba3-fba10787d506.png)

Because I can move both windows with the floating modifier but I can't move pamac's main window using its own client decoration - title bar.

**Comment by orestisf1993** [comment]
> Because I can move both windows with the floating modifier but I can't move pamac's main window using its own client decoration - title bar.

Is the behaviour different with this dialog?

**Comment by eater** [comment]
I have resolved the package conflict so I'm not immediately able to reproduce the Warning dialog and check whether the keyboard moves it.

When I spawn a "Transaction Summary" dialog like yours, I am able to move both windows with the keyboard.

However, when pamac-manager spawns an "Authenticate" dialog, requesting the root password, I *am* able to move both windows with the mouse, I guess because that window belongs to polkit-gnome-authentication-agent-1.

**Comment by orestisf1993** [comment]
You should be able to move managed floating windows using the floating modifier ($mod) + the mouse. Where you doing this or where you using just the mouse? Because if you were using just the mouse then i3 had nothing to do with it. Being able to move the windows using the keyboard hints that you are also able to move them using $mod + mouse.

**Comment by eater** [comment]
Yes, if I configure that in my config then I can drag the window with $mod + mouse. 

So dragging with the titlebar is not handled by i3? It's in the i3 docs.

**Comment by orestisf1993** [comment]
This is not i3's titlebar but pamac's (GTK+) client side decoration. If you enable the i3 titlebar (with `border normal` - you can use a `for_window` rule in your config) you will be able to drag the window.

Sorry for urging you to open an issue but i3 follows the indented behaviour here after all.
