### ISSUE TITLE
Error: status_command process exited unexpectedly (exit 1)  AND Compton Composite Manager

### ISSUE THREAD

**Issue by einnsoltair** [i3/i3#3273]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.15.0.1 (03-13-2018) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15.0.1 (03-13-2018) (pid 719)bort…)
Loaded i3 config: /home/oodevil/.config/i3/config (Last modified: Mon 30 Apr 2018 05:00:35 PM UTC, 606 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per https://i3wm.org/docs/debugging.html:

https://logs.i3wm.org/logs/5730342413533184.bz2

**What I did:**

I've been trying to install compton and get it to work correctly with i3. I've modified my config files (i3, compton, and terminator) and removed the changes because they didn't work. Now this error message won't stop popping up and compton won't render my windows correctly. 

**What I saw:**
[REFERENCE IMAGE]
https://imgur.com/a/e0bKEDs

Yes, the text isn't legible in those windows. The colors I specified for the compton to use are correct for the window on the far left, however when I make new windows, they're all distorted and overall incorrect.

**What I expected instead:**
I'm trying to get a layout similar to this:
https://www.google.com/search?q=i3+compton&rlz=1C1GCEA_enUS787US787&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiTp7OrwuLaAhVqwYMKHWX4B3kQ_AUIDSgE&biw=1920&bih=949#imgrc=-vgtf2G_LLmbgM:

**Comment by orestisf1993** [comment]
AFAIK compton is not supported. You might want to check https://github.com/chjj/compton/issues/477. Anyway, this doesn't seem to be an i3 issue.
If you don't think that this is an i3 bug but you just want help, consider posting in /r/i3wm or the IRC channel.

For i3status please open an issue in https://github.com/i3/i3status/issues if you think that it is a bug. A backtrace or running i3status from the terminal, the command you use to run i3status and your i3status config would help in this case.
