### ISSUE TITLE
resize set does not correctly interpret 0 for floating windows

### ISSUE THREAD

**Issue by stapelberg** [i3/i3#3276]
Output of `i3 --moreversion 2>&- || i3 --version`:

Running i3 version: 4.15-137-g981e901b (2018-05-01, branch "next") (pid 39735)

URL to a logfile as per https://i3wm.org/docs/debugging.html:

Can add one later on in case this turns out to not be reproducible.

**What I did:**

* open urxvt
* set floating
* `i3 resize set 800 px 400 px`
* `i3 resize set 0 px 400 px`

**What I saw:**

The window was first resized to 800x400 (expected), then to a large width exceeding my screen width (unexpected).

**What I expected instead:**

The second resize command should not result in any changes.

**Comment by Airblader** [comment]
> The second resize command should not result in any changes.

To be clear, the command should be rejected with an error because a width of 0 is an invalid value (right?).

**Comment by stapelberg** [comment]
> To be clear, the command should be rejected with an error because a width of 0 is an invalid value (right?).

No, it’s the documented way to signal “do not change”: https://i3wm.org/docs/userguide.html#resizingconfig says:

> Notes about resize set: a value of 0 for <width> or <height> means "do not resize in this direction", and resizing a tiling container by px is not implemented.

**Comment by Airblader** [comment]
Ah, I forgot. :-)
