### ISSUE TITLE
Mod key not working with apple keyboard

### ISSUE THREAD

**Issue by kirk86** [i3/i3#3285]
Output of `i3 --moreversion 2>&- || i3 --version`:
```
Binary i3 version:  4.15 (2018-03-10) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15 (2018-03-10) (pid 1122)o abort…)
Loaded i3 config: /home/kirk/.config/i3/config (Last modified: Thu 10 May 2018 20:05:47 IST, 141 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

URL to a logfile as per https://i3wm.org/docs/debugging.html:
https://logs.i3wm.org/logs/5769200056401920.bz2

**What I did:**
set $mod Mod4
set $alt Mod1

I've tried both combinations separately:
bindsym $alt+Return exec i3-sensible-terminal
bindsym $mod+Return exec i3-sensible-terminal

"I’m pressing Alt+Enter"

**What I saw:**

Nothing happened. 

**What I expected instead:**

I expect the terminal to pop up but nothing happened.

**Notice:**
This only happens with my bluetooth apple keyboard. When I `set mod Mod1` and use the default dell keyboard things work as expected. 

The strange thing is that at the bottom of my i3 config file I have the following:

```
bar {
	position bottom
	status_command i3status
	mode hide
        #bindsym $mod+Shift+s modifier
	modifier Mod1
}
```

Pressing just the Alt key on my apple keyboard I can see the bottom i3 bar with the info. But pressing Alt+Return or Alt+l(left focus) or Alt+h(right focus) etc, nothing of those things works as expected.

Any ideas on what might I've been doing wrong?

This is really frustrating at the moment because I can't work at all, I can't move the windows and interferes with my whole workflow.

**Comment by Airblader** [comment]
What is the xev output? Did you try toggling NumLock?

**Comment by kirk86** [comment]
@Airblader 


> What is the xev output?

Is that xorg-xev? Because I don't have that installed.



> Did you try toggling NumLock?

What do u mean by that? Enabling NumLock?
I don't think I have to since all the num keys work fine.
I have this keyboard 
![keyboard](https://user-images.githubusercontent.com/2902390/39892465-ac9c8870-5498-11e8-8759-ae9ff1967c54.jpg)

**Comment by Airblader** [comment]
Yes, xorg-xev. Please have a look at our userguide on how to configure bindings as it tells you how to use xev.

The reason I'm asking about both is because the activated keysym might not be the one you are binding to. The NumLock is a prime candidate for causing such trouble, and using xev is a good way to see what's actually being triggered.

**Comment by kirk86** [comment]
@Airblader I just provide the log from xev. Do you guys have any tutorials or step by step guide on the wiki where I can see someone that might have had the same issues and configured the keyboard using xev or some other kind of tool? Thank you!

**Comment by kirk86** [comment]
@Airblader What the proper use of bincode in the i3 config?
In the wiki the only example shows only one line with bincode calling a program through exec.

In my  previous config file I had in the beginning something like:
```
set $mod Mod1
```

After your suggestion I used xev and got the keycode 64 for ALT_L.
According to that I modified the config file as follows:
```
bincode 64 atl
set $alt Mod1
```

I also tried directly to do:
```
bincode 64 Mod1
```

but still when executing `$mod+Return` nothing happens.

**Comment by kirk86** [comment]
@Airblader What the proper use of bincode in the i3 config?
In the wiki the only example shows only one line with bincode calling a program through exec.

In my  previous config file I had in the beginning something like:
```
set $mod Mod1
```

After your suggestion I used xev and got the keycode 64 for ALT_L.
According to that I modified the config file as follows:
```
bincode 64 atl
set $alt Mod1
```

I also tried directly to do:
```
bincode 64 Mod1
```

but still when executing `$mod+Return` nothing happens.

**Comment by orestisf1993** [comment]
`bindcode` is an alternative to `bindsym`, you use it like you would use `bindsym`.

Can you also please restrict xev's output? Use `xev -event keyboard` and just press alt + return on the window and close it.

**Comment by kirk86** [comment]
@orestisf1993 Here's the output from xev restricted:
```
Outer window is 0x1e00001, inner window is 0x1e00002

KeymapNotify event, serial 24, synthetic NO, window 0x0,
    keys:  4294967234 0   0   0   16  0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

KeyRelease event, serial 25, synthetic NO, window 0x1e00001,
    root 0x1e0, subw 0x0, time 625118, (-129,4), root:(1155,60),
    state 0x10, keycode 36 (keysym 0xff0d, Return), same_screen YES,
"   XLookupString gives 1 bytes: (0d) "
    XFilterEvent returns: False

KeyPress event, serial 28, synthetic NO, window 0x1e00001,
    root 0x1e0, subw 0x0, time 629005, (-129,4), root:(1155,60),
    state 0x10, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 28, synthetic NO, window 0x1e00001,
    root 0x1e0, subw 0x0, time 629017, (-129,4), root:(1155,60),
    state 0x18, keycode 36 (keysym 0xff0d, Return), same_screen YES,
"   XLookupString gives 1 bytes: (0d) "
"   XmbLookupString gives 1 bytes: (0d) "
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x1e00001,
    root 0x1e0, subw 0x0, time 629155, (-129,4), root:(1155,60),
    state 0x18, keycode 36 (keysym 0xff0d, Return), same_screen YES,
"   XLookupString gives 1 bytes: (0d) "
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x1e00001,
    root 0x1e0, subw 0x0, time 629167, (-129,4), root:(1155,60),
    state 0x18, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```



> bindcode is an alternative to bindsym, you use it like you would use bindsym.

So what's the proper way in my case to set up the mod key have the same functionality as before with the old dell keyboard? I've tried pretty much everything, changing modes from Mod1 to Mod5, Control, etc. nothing has worked so far.

Any hints would be much appreciated.

**Comment by kirk86** [comment]
It seems like if it use `set $mod Mod2` then everything works like before but with exception that now things are a bit messed up. Before I used Alt+Return for new terminal now that translates to just Return. When you write you can't use the numpad directly since it switches between workspaces, you'll have to use either Shift or Ctrl.

The thing that bogs me the most is the fact that the Alt key works buy showing the bottom i3-bar infor but the combination of Alt+Other key is not. This is strange.

**Comment by kirk86** [comment]
Ok this is my last post and honestly I don't know what actually resolved the problem but what I did was to try multiple times the different modes Mod1-Mod7 and reloaded and restarted i3 as well multiple times, finally after many reboots as well now things work as they should have since the beginning (Mod1 -> Alt). I feel that I've lost a complete day from my life accomplishing nothing at all. The linux community should continue to work on those things so that users don't have to spend all that time for nothing. I wish I knew what actually was the problem and provided a solution for whomever had the same issue but the worst thing is that i don't know.

**Comment by tomadimitrie** [comment]
Hi @kirk86, sorry for reviving a 6 year old thread, lol. I have the exact same problem as you and have no idea what to do, and this is the only thread I found with this problem. Did you encounter the problem again since you last posted?
