### ISSUE TITLE
Feature Request: Layout command criteria.

### ISSUE THREAD

**Issue by plexigras** [i3/i3#3287]
so you can do something like

```
new_window pixel 2
for_window [layout="tabbed"] border normal
```

or you could make layout specific bindings which i think would be a nice thing to be able to do.

**Comment by Airblader** [comment]
I don't think this would really do what you think as changing the tabbed layout to a normal one wouldn't reset the border.

This usecase can be (correctly) covered with relatively simple scripts using the IPC i3 offers, so I'd recommend you use that for such customizations :-)
