### ISSUE TITLE
FR: make hor & vert split (indicators) swappable

### ISSUE THREAD

**Issue by laur89** [i3/i3#3289]
Not a bug but a feature request.
I don't agree with i3 definition for `vertical` & `horizontal` split, so I've swapped the keybindings.
But if there's say vertically-split (by my definition) container tab in its parent container, it shows with `H` prefix in the tab title.

Could we have some config option switching the semantics of vertical & horizontal split? Or at least make the indicator character (ie `V` vs `H`) user-definable.

**Comment by Airblader** [comment]
Hi, 

while I understand that you may feel differently about it, this is how we define the terminology in i3. I don't believe that making this configurable in any way adds (enough) benefit to justify the mental complexity of additional configuration. 

If you feel strongly about it I'd suggest running a patch locally as it's going to be a trivial and small patch. Thanks for understanding!

**Comment by laur89** [comment]
For anyone stumbling upon this issue, this is the patch I'm using: https://github.com/laur89/i3-extras/blob/master/i3-v-h-split-label-swap.patch
