### ISSUE TITLE
Outputs are rendered at wrong position auf X screen

### ISSUE THREAD

**Issue by maralorn** [i3/i3#3290]
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.15 (2018-03-10) © 2009 Michael Stapelberg and contributors                                                                              
Running i3 version: 4.15 (2018-03-10) (pid 28251) abort…)                                                                                                     
Loaded i3 config: /home/maralorn/.config/i3/config (Last modified: Thu 01 Jan 1970 01:00:01 AM CET, 1526129159 seconds ago)                                   

The i3 binary you just called: /nix/store/8h067gw7rny6frpsnmr40zinmw7dmwwy-i3-4.15/bin/i3
The i3 binary you are running: /nix/store/8h067gw7rny6frpsnmr40zinmw7dmwwy-i3-4.15/bin/i3 
```

URL to a logfile as per https://i3wm.org/docs/debugging.html:

https://logs.i3wm.org/logs/5637945855836160.bz2

**What I did:**

I am using two outputs `eDP1` (laptop monitor) and `HDMI2` (external monitor).
I ran `xrandr --output HDMI2 --auto --above eDP1`.

**What I saw:**

i3 and xrandr agree on what monitors are enabled and where they are. An exerpt from `i3-msg -t get_outputs`:
```
   {
      "rect" : {
         "x" : 0,
         "y" : 1080,
         "height" : 1080,
         "width" : 1920
      },
      "active" : true,
      "primary" : true,
      "current_workspace" : "0:tasks",
      "name" : "eDP1"
   }, …
   {                
      "name" : "HDMI2",                                                                                                                          
      "rect" : {                                                                                                                                              
         "x" : 0,
         "height" : 1080,                                                                                                                                     
         "y" : 0,                                                                                                                                              
         "width" : 1920                                                                                                                                        
      },                                                                                                                                                       
      "active" : true,                                               
      "current_workspace" : "1",                                                                                                                              
      "primary" : false                                                                                                                                        
   }, 
```
but the workspace "0:tasks" is actually shown (and works) on HDMI2.

The mouse movement works as expect (i.e. the mouse enters HDMI2 from the bottom, when it leaves eDP1 at the top, but to send a mouse event to a window on workspace "0:tasks" if have to click on the corresponding spot on eDP1, where the window is not shown. The mouse movement is restricted to the area of the two monitors as expected.

The workspace "1" is nowhere to be seen, but I can move the focus and windows there and back. It feels like it is rendered on the virtual screen above my external monitor HDMI2. But of course according to xrandr that's outside of the Xscreen.

eDP1 remains to show what ever was visible there before reconfiguring the monitors. It remains frozen that way, with the exception of showing the mouse cursor, when moved there.

**What I expected instead:**
The output/workspaces/i3bar corresponding to one output should be actually shown on that output.
Mouseclicks should happen, where the mouse is shown.

**Remarks**
I have no clue, what is the culprit. This is probably not very reproducable outside of my setting. I have no output specific stuff in my i3config. Running i3 with the defaultconfig gave the same problem.
I have a similar offset problem when putting the monitors in some other formation (left, right), strangely then the mouse works on HDMI2 as expect (apart from i3 thinking that this is actually eDP1).
When mirroring HDMI2 and eDP1, everything works as expected.

This problem is very weird, because all debugging seems to indicate everything works as expected, but what I see is completely different and disfunctional.

I would be glad about any hints on how to debug this further.

**Comment by mzanibelli** [comment]
Did you by any chance update to Xorg 1.20 recently ? I'm experiencing a similar problem but only when one of my screens is rotated. Downgrade Xorg solves the problem. I won't go into details while not sure that it's a related issue.

**Comment by maralorn** [comment]
Nope, I have this problem with xorg 1.19.6.

**Comment by enckse** [comment]
@mzanibelli - by chance do you have an open bug/more knowledge on the issue you are facing (exact same problem as you, downgraded off of 1.20 until I can figure out where/what the problem is)

**Comment by mzanibelli** [comment]
@enckse not yet because I had no time to properly analyze and report the problem. Please do so if you can, I'll try to be helpful !

**Comment by enckse** [comment]
https://bugs.freedesktop.org/show_bug.cgi?id=106593

**Comment by zmertens** [comment]
I have an issue related to using multiple monitors, specifically after I run the command 
`xrandr --output HDMI1 --auto --right-of eDP1`, 
and then switching back to a single monitor and running `xrandr --auto`, and it causes the i3bar icons (audio, network, battery, package manager) to overlap. I'm posting a screenshot and pay close attention to the bottom right of the screen:

![i3bar_icon_overlap](https://user-images.githubusercontent.com/5597089/50730054-837a9880-1101-11e9-90dc-542b7a422627.jpg)

`i3 --moreversion 2>&- || i3 --version` output:
```bash
Binary i3 version:  4.16 (2018-11-04) © 2009 Michael Stapelberg and contributors
(Getting version from running i3, press ctrl-c to abort…)
Running i3 version: 4.16 (2018-11-04) (pid 960)
Loaded i3 config: /home/zach/.i3/config (Last modified: Tue 14 Nov 2017 08:24:07 PM MST, 36012972 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

**Comment by maralorn** [comment]
So I played around with this for a bit. The bug also happened with other window-managers e.g. awesome.
But it went away when I disabled compton and now (without compton) it's working and I'm happy. I guess i3 was not to blame.
