### ISSUE TITLE
This syntax should be on the user guide. It was the only way to make Spotify open on the assigned workspace

### ISSUE THREAD

**Issue by alienbogart** [i3/i3#3293]
Output of `i3 --moreversion 2>&- || i3 --version`:
```
Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08) (pid 3061)o abort…)
Loaded i3 config: /home/mrpink/.config/i3/config (Last modified: Sat 19 May 2018 07:48:27 AM -03, 487 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```
**My Environment**
* OS: MX Linux 17
* i3 version 4.13
* Spotify 1.0.77
* [i3/config](https://gitlab.com/mrbig/dotfiles/blob/master/i3/config)
* [full environment](https://gist.github.com/mrbig033/63fd7f4f51b6a8ae379abae74c52aff2)

**What I did:**

Spotify doesn't follow workspace assignments. I tried the following combinations:

* `assign [class="Spotify"] $ws04`
* `assign [title="Spotify"] $ws04`
* `for_window [class="Spotify"] move $ws04`
* `for_window [title="Spotify"] move $ws04`
* `for_window [class="Spotify"] move window to $ws04`
* `for_window [title="Spotify"] move window to $ws04`

**What I saw:**

Spotify was not loading on the $ws04 workspace. 

**What I expected instead:**

Spotify should load on the $ws04 workspace.

**Solution**

`for_window [class="Spotify"] move to workspace $ws04` made Spotify behave.

**Suggestion**

Even though the syntax is present in the documentation, it is not clear it can be used with `for_window`. Since that's a solution to a common problem (Spotify is a popular app), I think there should be an example on the user guide showing how that syntax can be used with `for_window`, or at least a mention about that possibility inside [this section](https://i3wm.org/docs/userguide.html#_changing_named_workspaces_moving_to_workspaces). [This comment](https://old.reddit.com/r/i3wm/comments/8kimi8/spotify_doesnt_follow_workspace_assignment/dz8asby/) helped me figure it out, otherwise I'd be lost.

**Comment by Airblader** [comment]
Thanks for reporting this. I don't think the userguide is a good spot to document workarounds for all the broken X clients out there. I'd suggest using this energy for actually convincing the developers to fix their software. Thank you :-)

**Comment by orestisf1993** [comment]
What we can do, imo, is make the FAQ a bit more visible (not under /r/i3wm's wiki) and enhance it with all kinds of common questions.

**Comment by Airblader** [comment]
What place do you have in mind that would be more visible?

**Comment by orestisf1993** [comment]
https://i3wm.org/faq/ or https://i3wm.org/docs/faq/

Besides visibility, this will make the faq easier to contribute to.

**Comment by mrbig033** [comment]
Airblader, I also used that syntax to correctly assign a Google Chrome window with Netflix to a workspace. I guessing here, but I think this particular workaround might be frequent enough to deserve more exposition. Google Chrome is probably the most popular software nowadays.

**Comment by Airblader** [comment]
And has anyone reported this issue to either application yet? It's a violation of the specs, so these clients are simply broken. If you find a bug, get it fixed and not worked around in other software.

**Comment by mrbig033** [comment]
@Airblader, I'll also send an issue to Spotify, wherever they are

**Comment by Airblader** [comment]
By the way, how- and wherever we document the workaround, we should also mention the drawbacks of it since it is not equivalent to `assign`.
