### ISSUE TITLE
Can't run slock with bindsym anymore

### ISSUE THREAD

**Issue by NickeZ** [i3/i3#3298]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

`slock` doesn't start using my keybinding `$mod+Shift+s`. It worked before (I'm sorry but I don't know when it broke)

In .xsession-errors I see
```
slock: unable to grab mouse pointer for screen 0
slock: unable to grab keyboard for screen 0
```

## Expected Behavior

* `slock` should start.
* .xsession-errors should be empty.

## Reproduction Instructions

Add a keybinding: `bindsym $mod+Shift+s exec "slock"`.
Try above keybinding.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.14.1 (2017-09-24, branch "4.14.1") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.14.1 (2017-09-24, branch "4.14.1") (pid 4214)
Loaded i3 config: /home/niklas/.config/i3/config (Last modified: fre  1 jun 2018 01:35:50, 402 seconds ago)
The i3 binary you just called: /home/niklas/.local/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
Config is default with above addition.
</pre>

<pre>
- Linux Distribution & Version: Ubuntu 18.04 LTS
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

**Comment by NickeZ** [comment]
Same problem on i3 4.15.

```
Binary i3 version:  4.15 (2018-03-10, branch "tags/4.15") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15 (2018-03-10, branch "tags/4.15") (pid 4214)
Loaded i3 config: /home/niklas/.config/i3/config (Last modified: fre  1 jun 2018 01:35:50, 932 seconds ago)
The i3 binary you just called: /home/niklas/.local/bin/i3
The i3 binary you are running: i3
```

**Comment by NickeZ** [comment]
A workaround is to create a bash script with `sleep 1` in it.

**Comment by orestisf1993** [comment]
Please use the `--release` flag, see https://i3wm.org/docs/userguide.html#keybindings

From a quick skim through their log they seem to have made changes on the pointer grabbing code: https://git.suckless.org/slock/commit/?id=e378f735d857f7da124177e3540912d920be5022

**Comment by orestisf1993** [comment]
And since the linked commit is after 1.3 and before 1.4, I guess your slock version is 1.3?

**Comment by orestisf1993** [comment]
Actually, seems to be a bug that is still present with slock 1.4

In https://git.suckless.org/slock/tree/slock.c#n282 I think they shouldn't break when both `ptgrab` and `kbgrab` are `AlreadyGrabbed`

**Comment by NickeZ** [comment]
Thanks! `--release` works great
