### ISSUE TITLE
Enhancement: i3bar progress bars

### ISSUE THREAD

**Issue by Gravemind** [i3/i3#3299]
I'm experimenting with a per-module "progress bar" indicators in my bar, on top of the module text, something like that:

![i3bar_progress_bars](https://user-images.githubusercontent.com/431519/40842801-868cb63e-659e-11e8-888b-6cacc230c05b.png)

I didn't find any other bar able to do that (and still being reasonably lightweight and modern). So I started to look at the source code of a couple promising bars, but in the end I came back to i3bar because I found it was the only one really "compatible" with this feature (source-code-architecture-wise, in the other bars I could not see how to implem without being too disruptive).

This feature obviously also implies an implementation in the status program too, but I think the json keys I chose are "high level" enough to be easily implemented in any status program.

So, I've been [experimenting with i3bar](https://github.com/i3/i3/compare/next...Gravemind:progress-bar-wip) (and [i3status](https://github.com/i3/i3status/compare/master...Gravemind:progress-wip), screenshot above), so far I got:

New i3 configs:
```
bar {
    # Disabled (the default)
    progress none
    # Enabled as progress bars
    # progress top_bar|bottom_bar [margin_px height_px]
    progress top_bar 1 1
}
``` 
New status json keys:
```js
[... ,{ ...
    // Progress in percent
    "progress":70,
    // Colors: "foreground [background]"
    "progress_colors":"#80BEED #505050",
    // Or colors with bar's default foreground
    "progress_colors":"- #505050",
... }, ...]
```

Notes:
1. `progress` instead of `progress_bar` leaves room for any other progress indicator (e.g. pies) (future, or other bars...).
1. `progress_colors` as a color list (instead of something like `progress_fg/bg`) leaves the possibility to have more than 2 colors (future or other bars...). Could also be json array of string ... ?
1. the `top_bar` `bottom_bar` might be redundant with `margin_px` if you know the height, but I thought it was more human friendly. But I'm undecided, it could also be only `progress bar [position_y_px height_px]` ?

What do you think ?

**Comment by Airblader** [comment]
This seems to fall into the eye candy category. All the information in your examples is now duplicated. Is there any actual benefit we get here other than visuals?

**Comment by Gravemind** [comment]
It's eye candy, but it also improves readability at a glance. Especially with #3300 minimized bar (I made a single PR with this one at first then changed my mind), it's really nice to have urgent workspaces, volume, load, temp, disk etc available at a glance without the full height.

I thought it might be too much eye candy, but then saw the borders and background integration in i3bar... But, I'll understand if closed, then do you think i3-gaps would be more inclined ?

**Comment by Airblader** [comment]
> it also improves readability at a glance

I don't quite see why it would – if you want a percentage view on the data, this can be expressed in text (as is typically done for, e.g., volume). And a numeric percentage value is much more expressive, with a progress bar you only get a rough information and have to guess the exact value.

I think overall this is mostly about eye candy and the functional benefits can be argued and don't quite fit our cost / benefit calculation here, so I'm going to close this feature request.

> do you think i3-gaps would be more inclined ?

Let's please discuss it on the i3-gaps issue tracker.
