### ISSUE TITLE
Enhancement: i3bar new mode minimized

### ISSUE THREAD

**Issue by Gravemind** [i3/i3#3300]
Implement a new bar `mode minimize`, that would behave like `mode hide` but when hiding it would show only a few pixels of the top or bottom pixels.

I'm tired of missing my urgent windows because of `mode hide`, but I still want a my full screen height, so I thought of this compromise so we can always see to top border color or workspaces.

I also got exited because of #3299 progress bars I am experimenting with:

![i3bar_workspaces_minimized](https://user-images.githubusercontent.com/431519/40845917-989ee51e-65a7-11e8-89ac-c8b141f62503.png)
(it doesn't look nice over white, so I added a thick black border to simulated a screen border, but still does not render as good as in reality I think)

The height of the minimized mode would always be reserved, and when shown it would show the full height floating over the other windows.

A trivial implementation of the minimized state should is easy to do by just changing the size of the created window, and it would still render at full height in the buffer.

But I am not sure about the shown state. I don't know enough about xorg to know if a window render can overflow it's docked size. If not, my first guess would require 2 windows, the standard full height floating-over to render the bar, and a placeholder dummy window to always reserve the minimized docking height...

On the config side, I'm thinking of something like this:
```conf
bar {
    mode minimize

    # When minimized, the bar shows `height_px` pixels starting from the top,
    # bottom, or `offset_y_px` pixels
    # minimize top|bottom|offset_y_px height_px
    minimize top 3
}
```

**Comment by Airblader** [comment]
Thanks for the issue. I don't think there is anything meaningful we can currently display in such a state (we don't have progress bars) as the text is already quite minimal. If you want it to be even thinner, you can always choose a smaller font.

With regards to the progress bar: we should first clarify that issue and whether we want to add that and, given that we do, could then later revisit this idea. 

Thanks for understanding.
