### ISSUE TITLE
[Bug] `mod4` gets stuck after entering `mod4+fn+mod4`

### ISSUE THREAD

**Issue by Abominas** [i3/i3#3302]
<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
The mod4 key (Windows key) becomes 'stuck' after entering this key combination.
Every key acts as if `mod4` was already pressed, so pressing `a` selects every window, `1` moves to workspace 1.

## Expected Behavior
`mod4` shouldn't get stuck

## Reproduction Instructions
1. Press and hold `mod4`
2. Press and hold the `fn` key
3. Release `mod4`
4. Press `mod4` again

## Environment
Output of `i3 --moreversion 2>&-`:
Binary i3 version:  4.15-148-g26f50898 (2018-05-20, branch "next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15-148-g26f50898 (2018-05-20, branch "next") (pid 1386)
<pre>
- Linux Distribution & Version: Arch
- Are you using a compositor (e.g., xcompmgr or compton): compton v0.1_beta2.5

- Laptop model: Lenovo Yoga 720-15ikb
- In the bios, I toggled the fn key mode, so that hitting the f[1-0] keys doesn't act as if fn is pressed.
</pre>

**Comment by orestisf1993** [comment]
The Fn key is usually invisible to software so I don't think that this is an i3 bug. Can you run `xev -event keyboard` and share its output? Does this also happen with other window managers, eg openbox?

**Comment by Abominas** [comment]
I ran the command, and like you said, the Fn key doesn't show up.
The output shows that when I enter the key combination, another key, 'Super_R' gets pressed and released, while 'Super_L' does not get released.

<pre>
KeyPress event, serial 28, synthetic NO, window 0x1600001,
    root 0x19d, subw 0x0, time 16564251, (-1100,1632), root:(824,1662),
    state 0x0, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 28, synthetic NO, window 0x1600001,
    root 0x19d, subw 0x0, time 16565221, (-1100,1632), root:(824,1662),
    state 0x40, keycode 134 (keysym 0xffec, Super_R), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x1600001,
    root 0x19d, subw 0x0, time 16565323, (-1100,1632), root:(824,1662),
    state 0x40, keycode 134 (keysym 0xffec, Super_R), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
</pre>

**Comment by orestisf1993** [comment]
I doubt that anything can be done from i3's side since we just read those events and Super_L is still pressed according to them. This sounds like either a bug with your laptop (or feature! maybe it is supposed to be a way to press the Super_R key) or with Xorg.

**Comment by Abominas** [comment]
> This sounds like either a bug with your laptop (or feature! ...

Sounds like it could be, I'll go ahead and close this issue. 
Thanks for your time.
