### ISSUE TITLE
Rendering Bug

### ISSUE THREAD

**Issue by FishCoding** [i3/i3#3304]
## I'm submitting a…

<pre>
[X] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When I do transitions like the full screen, i3 renders weird things, like a lot of squares of a different colors. 
Link with a recorded video of a transition: https://imgur.com/a/b8Secdz

## Expected Behavior

A normal transition. 

## Environment

It also happens with the 4.15 version that can be downloaded form the apt ( i3 not gaps ) 
<pre>
Output of `i3 --moreversion 2>&-`:
Binary i3 version:  4.15.0.1-2-g1c535b18 (2018-03-13, branch "gaps") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15.0.1-2-g1c535b18 (2018-03-13, branch "gaps") (pid 1701)
Loaded i3 config: /home/neo/.config/i3/config (Last modified: mar 05 jun 2018 19:57:17 CEST, 47397 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3-with-/i3
</pre>

<pre>
- Linux Distribution & Version: Ubuntu 18.04
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by FishCoding** [comment]
I am not running compton, but I think that is the graphics driver cause I changed to arch and the problem disappeared.

**Comment by orestisf1993** [comment]
Thanks. Closing this since I don't think that this was an issue with i3.
