### ISSUE TITLE
Strange layout behavior after pressing mod+h, mod+w, mod+h, mod+w, mod+h

### ISSUE THREAD

**Issue by kaiwk** [i3/i3#3305]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Split two terminals, then press this key sequences:

`mod+h, mod+w, mod+h, mod+w, mod+h, ......`

It would generate useless title bar like below:

<img width="1108" alt="screen shot 2018-06-06 at 8 29 24 pm" src="https://user-images.githubusercontent.com/10190397/41038543-210a6e26-69c9-11e8-99d6-a6321cd6d5ab.png">

## Expected Behavior

After pressing `mod+h, mod+w, mod+h, mod+w, mod+h, ...`, it should do nothing.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
<img width="1016" alt="screen shot 2018-06-06 at 8 45 41 pm" src="https://user-images.githubusercontent.com/10190397/41038981-a3da3b0a-69ca-11e8-9346-205c469e4845.png">

</pre>

<pre>
- Linux Distribution & Version: Debian Stretch
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by orestisf1993** [comment]
This is essentially #3001
