### ISSUE TITLE
Match empty window properties (e. g. no title set)

### ISSUE THREAD

**Issue by exic** [i3/i3#3308]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

We cannot check for "title unset" or something similar to match a window.

## Expected Behavior

I can check for title="^$" or title=null to match weird windows.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.15.0.1-161-g19735b5e (2018-05-04, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15.0.1-161-g19735b5e (2018-05-04, branch "gaps-next") (pid 3720)
Loaded i3 config: $HOME/.config/i3/config (Last modified: Mon 11 Jun 2018 10:47:18 AM CEST, 726 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

</pre>

<pre>
- Linux Distribution & Version: Ubuntu 18.04
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

I've asked about this here, describing the use case: https://www.reddit.com/r/i3wm/comments/87qlqr/finding_criteria_for_heidisql_window_with_net_wm/

Looking at the code I found that it's simply not possible atm.

**Comment by Airblader** [comment]
I would argue that a client should preferably set a title. Why not fix the client to provide useful information?

**Comment by exic** [comment]
That's what I'd prefer too. You might encounter software that you can't fix though and would still want to handle the window?

In my case its probably a wine issue since no windows user ever saw this weird untitled window, and I'm unsure where to file an issue to get this fixed. :-/

**Comment by Airblader** [comment]
> You might encounter software that you can't fix though and would still want to handle the window?

We officially only support open-source software, so I'd argue that this case should never reasonably happen (and even in closed-source software you can still contact the developers behind it).

Regarding your current problem with wine: does this affect all windows opened by wine or is it just specific programs launched through wine (i.e., does wine generally not set titles)?

I'm not entirely opposed to the proposed idea here, but I would like to probe the situation a bit more before making a call.

**Comment by exic** [comment]
It only happened using HeidiSQL so far, other windows are fine.

These are the xprop outputs (as in [above mentioned post](https://www.reddit.com/r/i3wm/comments/87qlqr/finding_criteria_for_heidisql_window_with_net_wm/)):
Crappy useless window: https://pastebin.com/nmsthuLm
Main window: https://pastebin.com/hu4JZ6TP

To fix my issue it actually doesn't need to be "match empty window properties", if I could for example match _NET_WM_STATE_SKIP_TASKBAR to put it on scratchpad, that would work fine too.

I agree that I should check wine/heidisql to get a permanent fix for the problem. It's just that very few people use HeidiSQL with Wine and a tiling manager, where this hidden window gets in the way. I've been on AwesomeWM before. There, it was an only one pixel large window. Here's a screenshot, the black box is what I'm talking about:

![weird](https://user-images.githubusercontent.com/242107/41271722-69d129cc-6e12-11e8-9c0f-0e024cd69adb.png)

**Comment by archenemies** [comment]
Well maybe I'll try asking this one over here: "is there a pattern to 'match every window'? Even if it doesn't have a title or a class? Maybe that would be a good thing to have."

**Comment by orestisf1993** [comment]
`[workspace=.*]` should work.

**Comment by archenemies** [comment]
Thank you, that indeed works for me.

**Comment by infabo** [comment]
Any ideas how to hide this creepy black window?

**Comment by exic** [comment]
Hey, thanks for bringing this back up. My workaround atm is to focus it and move it to the scratchpad manually, but that's not really cool. 

@Airblader prefers to fix the client, HeidiSQL maintainer says it's most likely a wine issue but I haven't managed to open a wine bug yet.

Maybe we can find another window property that matches the "creepy black window" so it can be moved away?

**Comment by infabo** [comment]
reporting bugs to wine-hq isn't as easy....

**Comment by infabo** [comment]
Maybe this black-window represents the systray-icon? But there isn't any systray in an i3-environment? many windows applications have a permanent systray icon....

**Comment by sandsmark** [comment]
since it's a very simple patch, and this has been an issue for a while so I'm fairly sure I'm missing something I'll ask here before potentially opening a PR: this should work, shouldn't it?:

```
diff --git src/match.c src/match.c
  index 83e37327..8d71addc 100644
  --- src/match.c
  +++ src/match.c
  @@ -92,11 +92,8 @@ bool match_matches_window(Match *match, i3Window *window) {
   #define CHECK_WINDOW_FIELD(match_field, window_field, type)                                       \
       do {                                                                                          \
           if (match->match_field != NULL) {                                                         \
  -            if (window->window_field == NULL) {                                                   \
  -                return false;                                                                     \
  -            }                                                                                     \
  -                                                                                                  \
  -            const char *window_field_str = GET_FIELD_##type(window->window_field);                \
  +            const char *window_field_str = window_field_str == NULL ?                             \
  +                GET_FIELD_##type(window->window_field) : ""                                       \
               if (strcmp(match->match_field->pattern, "__focused__") == 0 &&                        \
                   focused && focused->window && focused->window->window_field &&                    \
                   strcmp(window_field_str, GET_FIELD_##type(focused->window->window_field)) == 0) { \
```

Fixing the clients is the best approach, but there are a ton of broken clients, and the most broken clients are usually closed source so it's not always an option.

**Comment by Airblader** [comment]
> Fixing the clients is the best approach, but there are a ton of broken clients, and the most broken clients are usually closed source so it's not always an option.

Well, the more broken clients there are, the less matching on information which aren't set actually makes sense; that's not identifying a window, that's trying to rule out non-broken clients.

That said, if the patch works I think that's fine to do.

**Comment by sandsmark** [comment]
> Well, the more broken clients there are, the less matching on information which aren't set actually makes sense; that's not identifying a window, that's trying to rule out non-broken clients.

I think many people have a single "bad" application, so being able to identify that solves an issue for at least some people. But there isn't a solution that will solve it 100% for everyone that I can see at least.

> That said, if the patch works I think that's fine to do.

Tried just running it and it segfaulted, but I'll try to find some time to do it properly. :-)

**Comment by sandsmark** [comment]
Please don't look too closely at the patch above, it was a bit embarassing. :-P
