### ISSUE TITLE
Tray symbols disappear after switching monitor outputs

### ISSUE THREAD

**Issue by manueljacob** [i3/i3#3317]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
I have `tray_output primary` in a `bar` block. When switching from my external monitor to my internal monitor while leaving the primary output unchanged (`xrandr --verbose --output DP1 --off --output eDP1 --auto`), the tray symbols disappear. Even when switching back (`xrandr --verbose --output eDP1 --off --output DP1 --auto --primary`), the symbols don't show up until I press `Mod1+Shift+r` (restart).

## Expected Behavior
When switching back to the external monitor (set as primary by xrandr), the tray symbols should be shown.

Also, not showing any symbols if the primary output is off is a bit confusing but you could argue that's exactly what I configured. (EDIT: I think that the behavior described in this paragraph is fine. I shouldn't have distracted from the actual problem which was described in the previous paragraph.)

## Reproduction Instructions
Described above.

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.15 (2018-03-10) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15 (2018-03-10) (pid 383)to abort…)
Loaded i3 config: /home/manu/.config/i3/config (Last modified: 2018-06-29T21:00:40 CEST, 408 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

For testing, I've used an almost default config (copied from `/etc/i3/config`), with `tray_output primary` inserted into the `bar` block.

<pre>
- Linux Distribution & Version: Arch Linux (rolling release)
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

I sometimes encounter other issues with tray symbols and switching monitors (in particular, the Pidgin symbol disappears sometimes and even restarting i3 doesn't help; only restarting Pidgin helps). However, the issue described here is the only one that I could reproduce reliably.

**Comment by bebehei** [comment]
I'm experiencing the exact same problem for a longer time and have had a few unsuccessful tries debugging the code.

But today, I found the bad codebit. I'll fire a PR.

I guess #2957 is related.

**Comment by manueljacob** [comment]
What part did the PR intend to fix? Showing the tray symbols when switching back to the primary monitor (not requiring restart)? Showing the tray symbols somewhere if the primary monitor is off? Both?

**Comment by Airblader** [comment]
It was this part:

> Showing the tray symbols somewhere if the primary monitor is off?

More specifically, the PR would've shown the tray on the first available output if you specified `tray_output primary` but didn't have an active primary output.

The reasons why the PR has not been merged can be seen in the discussion there. The PR is IMHO unrelated to the issue of the tray not showing up when switching back to the primary output.

On a side note, does it work if you split switching back to the external monitor up like this?

```
xrandr --verbose --output eDP1 --off --output DP1 --auto
xrandr --verbose --output DP1 --primary
```
