### ISSUE TITLE
Urgency hint not appearing

### ISSUE THREAD

**Issue by He-Ro** [i3/i3#3321]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>
**NOTE:** I am not sure, if this is a bug in i3, in QT or just a wrong way of using QT.

## Current Behavior

Using Method 0 of the attached program activates the window, if it is on a visible workspace, but it does not mark it as urgent if the workspace is not visible.
## Expected Behavior

Using Method 0 of the attached program should make the window active and marked as urgent, if it was not activated (because it was on a not visible workspace).
## Reproduction Instructions

0. Download the program from https://ptpb.pw/ya1R/py
1. Execute the attached python program, put it on workspace 1 and close all other windows.
2. Click on the button labeled 'Method 0'
3. Within 10 seconds switch to another workspace (e.g. workspace 2)
4. Wait more than 10 seconds
5. Observe that the workspace 1 is not marked as urgent

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
Binary i3 version:  4.15 (2018-03-10) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15 (2018-03-10) (pid 11458) abort…)
Loaded i3 config: /home/rosendahl/.config/i3/config (Last modified: 2018-04-10T08:23:13 CEST, 7633835 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
Configuration URL: https://ptpb.pw/Vvnh
</pre>

<pre>
Logfile URL: https://ptpb.pw/2Y79
</pre>
I restarted i3 before clicking the button and restarted i3 again after the urgency hint should have been shown. So the relevant log parts should be between the two restarts.

<pre>
- Linux Distribution & Version: Arch Linux (upto date)
- Are you using a compositor (e.g., xcompmgr or compton): No compositor
</pre>

**Comment by Airblader** [comment]
Thanks for filing this issue. I think something that'd be helpful here would be running the program under x11trace and looking at its output. Then we can see what Qt is doing on X level here.

**Comment by He-Ro** [comment]
I used https://www.github.com/yuq/xtrace to generate the following log: https://ptpb.pw/wweA

If you search for 'Method 0' you quickly get to the point where the action should happen. In the code the title is changed to this value right before requesting focus, see https://ptpb.pw/ya1R/py#L-45.

Please let me know if there is anything else I can do to help triage this!

**Comment by Airblader** [comment]
I took a quick first look at the logs. You can see the following two parts:

```
2018-07-07 16:41:44 - ClientMessage for window 0x00e00006
2018-07-07 16:41:44 - handlers.c:handle_client_message:748 - _NET_ACTIVE_WINDOW: Window 0x00e00006 should be activated
2018-07-07 16:41:44 - workspace visible? fs = 0x55bd62e04ca0, ws = 0x55bd62dd4f00
2018-07-07 16:41:44 - workspace visible? fs = 0x55bd62e04ca0, ws = 0x55bd62dd4f00
2018-07-07 16:41:44 - handlers.c:handle_client_message:793 - Marking con = 0x55bd62dd50f0 urgent
2018-07-07 16:41:44 - workspace.c:workspace_update_urgent_flag:799 - Workspace urgency flag changed from 0 to 1
2018-07-07 16:41:44 - Urgency flag changed to 1
2018-07-07 16:41:44 - ipc.c:ipc_send_window_event:1393 - Issue IPC window urgent event (con = 0x55bd62dd50f0, window = 0x00e00006)
```

and right after

```
2018-07-07 16:41:44 - ClientMessage for window 0x00e00006
2018-07-07 16:41:44 - workspace.c:workspace_update_urgent_flag:799 - Workspace urgency flag changed from 1 to 0
2018-07-07 16:41:44 - Urgency flag changed to 0
2018-07-07 16:41:44 - ipc.c:ipc_send_window_event:1393 - Issue IPC window urgent event (con = 0x55bd62dd50f0, window = 0x00e00006)
```

So it seems that there's a second client message unsetting the urgent hint again. Given the code paths we have in the handler and the fact that there is no further log message, it seems that we're getting a `_NET_WM_STATE_DEMANDS_ATTENTION` message. Likely, Qt tries to toggle this itself, causing a doubled toggle which essentially does nothing.

To check up on this hypothesis, you could apply the following patch, compile, restart and re-run the experiment whilst gettings logs again:

```
diff --git a/src/handlers.c b/src/handlers.c
index 38c2caf1..49d5c29e 100644
--- a/src/handlers.c
+++ b/src/handlers.c
@@ -710,13 +710,18 @@ static void handle_client_message(xcb_client_message_event_t *event) {
                 con_toggle_fullscreen(con, CF_OUTPUT);
             }
         } else if (event->data.data32[1] == A__NET_WM_STATE_DEMANDS_ATTENTION) {
+            DLOG("_NET_WM_STATE_DEMANDS_ATTENTION received for 0x%08x\n", event->window);
             /* Check if the urgent flag must be set or not */
-            if (event->data.data32[0] == _NET_WM_STATE_ADD)
+            if (event->data.data32[0] == _NET_WM_STATE_ADD) {
+                DLOG("_NET_WM_STATE_ADD");
                 con_set_urgency(con, true);
-            else if (event->data.data32[0] == _NET_WM_STATE_REMOVE)
+            } else if (event->data.data32[0] == _NET_WM_STATE_REMOVE) {
+                DLOG("_NET_WM_STATE_REMOVE");
                 con_set_urgency(con, false);
-            else if (event->data.data32[0] == _NET_WM_STATE_TOGGLE)
+            } else if (event->data.data32[0] == _NET_WM_STATE_TOGGLE) {
+                DLOG("_NET_WM_STATE_TOGGLE");
                 con_set_urgency(con, !con->urgent);
+            }
         } else if (event->data.data32[1] == A__NET_WM_STATE_STICKY) {
             DLOG("Received a client message to modify _NET_WM_STATE_STICKY.\n");
             if (event->data.data32[0] == _NET_WM_STATE_ADD)

```

Perhaps this would be conclusive.

**Comment by He-Ro** [comment]
The log with the patch applied: https://ptpb.pw/TdQU
I had a look at it, and it seems like QT is using ADD and REMOVE instead of two TOGGLEs. I had a look at some parts of the QT code and I suspected that the state of QT and that of the X server somehow deviated. When adding some sleeps inbetween the function calls in `_method0`, I saw that the urgency hint was appearing for a brief second or two and this led me to believe, that the last call to `QApplication.instance().alert(self)` resets the urgency hint somehow.
Now I added a call to `QCoreApplication.processEvents()` right infront of that line and the urgency hint stays on. I am not sure, if i3 can or should do something about this or if this is a full application bug.

**Comment by Airblader** [comment]
Yeah, I also have the impression that Qt caches the state internally (which is reasonable) and somehow goes out of sync. Can you please raise this to Qt and link the issue here (both ways)? Thanks!

**Comment by He-Ro** [comment]
I opened a bug in the QT bugtracker: https://bugreports.qt.io/browse/QTBUG-69568

**Comment by Airblader** [comment]
Yes, thanks, we'll close here for now but feel free to let us know if something happens on the Qt bug. We can always reopen :)
