### ISSUE TITLE
request: how to make dmenu show on output with focused workspace

### ISSUE THREAD

**Issue by nmschulte** [i3/i3#3326]
## I'm submitting a…

<pre>
[x] Bug
[x] Feature Request
[x] Documentation Request
[x] Other (Please describe in detail)
</pre>

## Current Behavior
Using multiple outputs (monitors; displays), pressing `Alt + d` (`bindsym $mod+d exec dmenu_run -fn "DejaVu Sans Mono-11"`) causes dmenu to show on the output with the current focus.  However, if you split focus from the cursor (`mouse_warping none`), **dmenu will only open on a focused output with an empty workspace if the cursor is on the output**.  If the workspace is not empty, dmenu shows on the output as expected.  Otherwise, dmenu shows on the output with the cursor.

## Expected Behavior
dmenu shows on the output of the currently focused workspace.

## Reproduction Instructions
Two outputs (monitors), `mouse_warping none`, workspace per output.
Focus a workspace using the cursor.
Focus the other workspace using the keyboard shortcuts.
Run `dmenu` (press Alt + d).

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.15-165-g6339427f (2018-06-22, branch "next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15-165-g6339427f (2018-06-22, branch "next") (pid 2127)
Loaded i3 config: /home/nmschulte/.config/i3/config (Last modified: Wed 04 Jul 2018 11:48:34 AM CDT, 596832 seconds ago)

The i3 binary you just called: /home/nmschulte/.local/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
</pre>

<pre>
- Linux Distribution & Version: Debian amd64
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by Airblader** [comment]
dmenu is override_redirect and as such i3 doesn't manage it or decide anything about it such as where it's placed. Or do you have any specific reason to believe there's something we can do?

**Comment by nmschulte** [comment]
> do you have any specific reason to believe there's something we can do?

I wasn't sure where this behavior came from.  I'll poke the suckless folks about it.

It seems it's behavior is to open on the output with the current focused/active window.  In my edge case, I assume there is no actual focused/active window (because the workspace is empty), and dmenu defaults to the output with the cursor.

I started resolving this with a different binding, but I've missed something re: encoding for `~/.config/i3/config` (string escaping).  As well, it seems I've not got the logic mapping `dmenu`'s monitor/output identification scheme to that of `i3`.

```
i3-msg -t get_workspaces | jq '.[] | select(.focused) | .output' | xargs -I{} sh -c 'xrandr | grep " connected" | sed -n "/{}/="' | sed 's/\(.\)/\1 - 1/' | bc | xargs -I{} dmenu_run -m {} -fn 'DejaVu Sans Mono-11'
```
```
bindsym $mod+d exec "i3-msg -t get_workspaces | jq '.[] | select(.focused) | .output' | xargs -I{} sh -c 'xrandr | grep " connected" | sed -n "/{}/="' | sed 's/\(.\)/\1 - 1/' | bc | xargs -I{} dmenu_run -m {} -fn 'DejaVu Sans Mono-11'"
```
