### ISSUE TITLE
overlapping / duplicating icons

### ISSUE THREAD

**Issue by bsdtux** [i3/i3#3335]
## I'm submitting a…

<pre>
[X ] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Fresh install of manjaro with i3 when 1st starting desktop I have 4 icons overlapping in what appears to be a rendering issue. 

Here is an image that shows the exact issue

![2018-07-26-000757_1918x1073_scrot](https://user-images.githubusercontent.com/5418213/43243002-c00bba90-9069-11e8-8434-b83d286407e8.png)

it appears that It can be resolved temporarily by hitting mod+shift+r to initiate a restart

## Expected Behavior
The expected behavior would be where the icons display without overlapping. 

## Reproduction Instructions
Starting an i3 session 

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.15
</pre>

<pre>
My i3 config: https://pastebin.com/8t1M6R19
</pre>

<pre>
Logfile URL: https://pastebin.com/aTw6jwmz
</pre>

<pre>
- Linux Distribution & Version: Manjaro 
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

**Comment by bsdtux** [comment]
So quick update. I removed compton from starting, thinking maybe that was causing the issue but it doesn't seem to have any effect. 

Not sure what else I can do to continue troubleshooting. happy to help in anyway

**Comment by sabarasaba** [comment]
I've tried with both i3bar and polybar and I'm seeing the same behavior with both.

**Comment by jtaala** [comment]
All, realised this is closed but just some info on (somewhat) of a fix entirely on the i3 config side.

It works for me and seems to disable the transparent backgrounds on the systray icons that seems to be causing the issue.  I now have a plain black background on icons in i3bar (making it at least usable now).

In i3 config, in the “bar” section, add the “-t” option to the “i3bar_command”, like so:
```
bar {
    i3bar_command i3bar -t
    ...
````
Seems robust. My i3bar background is not black, so is not as perfect as it was but at least now it’s very usable and doesn’t really bother me.

Found reference to the “-t” option (which supposedly enables transparency on the i3bar… ?) here:
https://github.com/Airblader/i3/issues/85

**Comment by nevdelap** [comment]
I removed i3-gaps from my manjaro i3 installation preferring to have vanilla i3 since I had gaps turned off having used i3 for years with gaps. So now I find that the -t option jtaala mentions, which I'd been using since I installed manjaro i3, is only in the i3-gaps version of i3bar. But it's been there for 3 years. So I wonder if bringing that into i3 wouldn't be a good idea, as the workaround to this bug, which is better than nothing?

**Comment by sabarasaba** [comment]
Its a gtk3-classic bug (see https://github.com/TomaszGasior/gtk3-mushrooms/issues/12#issuecomment-412555346) for me what fixed it was to uninstall gtk3-classic and installing gtk3 instead

**Comment by nevdelap** [comment]
Fantastic! Thanks for the quick reply. That's fixed it.
For others coming here, this is what I've done...

sudo pacman -Rn manjaro-i3-settings
sudo pacman -S i3-wm # it says it conflicts with i3-gaps and offers to replace i3-gaps.
sudo pacman -Rn gtk3-classic
sudo pacman -S gtk3
# Remove the -t from i3bar if you have it.

Thanks again!

**Comment by sabarasaba** [comment]
no worries, glad it worked for you too :D

**Comment by Streetwalrus** [comment]
That workaround is only temporary, the patches in question will be included in future gtk3 releases and break it again.

**Comment by jqdfkld** [comment]
same problem after latest debian unstable upgrade.
i do not use neither i3gaps nor gtk3-classic so have no idea how to fix it.

**Comment by TomaszGasior** [comment]
As I said, there is no problem with gtk3-mushrooms/gtk3-classic. Problem is caused by these commits: https://github.com/GNOME/gtk/commit/2ce63a86ba689aa41eb47409c889c469497478b0 https://github.com/GNOME/gtk/commit/01d1bc3c75fd0eff5665f5b9c690c5e1e6c65f13

**Comment by jqdfkld** [comment]
it seems that i do not use any of those libraries: have no files to patch.

**Comment by Streetwalrus** [comment]
Those commits are the _cause_ of the problem. They are already included in the latest version of GTK (3.24).
That thread on the GNOME issue tracker discusses possible ways to fix the issue.

**Comment by emmanueltouzery** [comment]
@jqdfkld on fedora 29, I just keep using i3, but I built i3-gaps from source just to get their version of i3bar, so I could add the `-t` flag. Seems to work fine although the translucent tray icons definitely stand out. But at least I can use them properly again now.

    i3bar_command /home/emmanuel/programs/i3gaps-4.15.0.1/bin/i3bar -t

**Comment by obadz** [comment]
According to https://gitlab.gnome.org/GNOME/gtk/issues/1280#note_387734 gtk 3.24.3 will fix this issue.

**Comment by TomaszGasior** [comment]
@obadz Yep, I wrote that comment. ;) I am waiting for .3 two weeks.

**Comment by volovikariel** [comment]
Sorry for reviving this thread

Despite using a much more recent version of gtk (3.24.43), I still have the same issue with duplicate icons.
It was suggested in this thread that GTK versions > 3.24.21 would fix the issue, but it didn't for me.

Curious if anyone else is still facing the duplicate icon issue.

**Comment by obadz** [comment]
> Curious if anyone else is still facing the duplicate icon issue.

Not me…

**Comment by keysmashes** [comment]
I was still seeing corruption at least as late as 2023-05-12:

![image](https://github.com/user-attachments/assets/df9f9e2e-e635-4fa4-b6e9-7a22cc4b35e1)

but I don't _think_ it has happened particularly recently.

**Comment by anpavlov** [comment]
> Curious if anyone else is still facing the duplicate icon issue

I  encountered this issue with fresh ubuntu 24.04 i3 (regolith) install.
Had bugged nm-applet icon overlapping when changing status
The only thing helped is your advice to use `i3bar_command i3bar -t`
