### ISSUE TITLE
[feature request] Operations on workspaces that are not in focus

### ISSUE THREAD

**Issue by ersi-dnd** [i3/i3#3341]
First, thank you for a wonderful window manager that has served me as my first choice for a few years now. 

In my opinion, there is one broad area where options seem to lack: Operations on windows that are not in focus. To do stuff with windows, they have to be either in focus or marked, and you cannot really do anything with unmarked windows that are not in focus. I have plenty of ideas in this area, but I only mention the following one.

Let's say I have a bunch of workspaces open. We have as many workspaces visible as we have monitors, the rest of the workspaces are hidden. How do I delete a hidden workspace at the same time closing all the windows there? As far as I can see, there is no way to do it currently.

How about having a syntax like `kill workspace %s` to close all the windows on that workspace and remove the workspace on statusbar? Additionally, there could be `remove workspace %s` to remove the workspace from the statusbar while moving all the open windows and containers on it to scratchpad.

**Comment by Airblader** [comment]
You can do this via 

    [workspace="<regex>"] kill

More generally, command criteria let you target any window regardless of visibility and focus.
