### ISSUE TITLE
Tapping+pressing $mod key to passthrough

### ISSUE THREAD

**Issue by lord-re** [i3/i3#3347]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When tapping then pressing $mod key i3 keep the keybinding for itself.

## Expected Behavior

When tapping then pressing $mod key i3 should pass the keypress to the focused application.

For example, if $mod is bound to Alt : tapping then pressing Alt+AnyOtherKey , i3 should pass this to the focused application.

With this, even if you are used to Alt, you could still send it to some application without remapping anything.

I hope my bad english is legible.

**Comment by orestisf1993** [comment]
Works for me
