### ISSUE TITLE
Is there any way to only show active workspace in i3bar ?

### ISSUE THREAD

**Issue by du0ngpv** [i3/i3#3350]
## I'm submitting a…
<pre>
[ ] Bug
[x ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
i3 bar show both inactive and active workspace

## Expected Behavior
i3 bar show only active workspace

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.15 (2018-03-10)
</pre>

Thank you !

**Comment by Airblader** [comment]
Hi,

no, there's no way to do this in i3bar, and we don't believe it's a good idea as it's the only indication of which workspaces exist, typically.

**Comment by du0ngpv** [comment]
`No way` ? Even by modify the code ?

**Comment by Airblader** [comment]
Of course you can modify the code to hide them if that's a patch you want to run locally.
