### ISSUE TITLE
Video problem with second monitor

### ISSUE THREAD

**Issue by Bobkins** [i3/i3#3357]
## I'm submitting a…

<pre>
[X ] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
I play movie on VLC player on primary monitor, when I move workspace with movie to second monitor VLC stop play and show just 'MEDIA! text
On first monitor OK 
https://ibb.co/ipiiJ9
Moved to second monitor
https://ibb.co/jo3uQp

If I play movie with Media player (app in Mint19), so I can play on second monitor but is it a lot of lagging.

If I play movie on Chromium browser and enter to full screen on second monitor. Chromium crash and I must to kill it. 

It start doing after upgrade Mint 18.3 -> Mint 19.
If i switch to MATE env, everything is OK. 

## Environment
<pre>
i3 version: 
Binary i3 version:  4.15 (2018-03-10) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15 (2018-03-10) (pid 2255)o abort…)
Loaded i3 config: /home/bobkins/.config/i3/config (Last modified: Fri 10 Aug 2018 06:40:03 PM CEST, 178826 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5689608004173824.bz2
</pre>

<pre>
- Linux Distribution & Version:
- Are you using a compositor (e.g., xcompmgr or compton): I'dont know what is it. 
$ inxi -Fx
System:    Host: bobkins-PC Kernel: 4.15.0-20-generic x86_64 bits: 64 gcc: 7.3.0 Desktop: i3 4.15
           Distro: Linux Mint 19 Tara
Machine:   Device: desktop Mobo: Gigabyte model: GA-970A-D3 serial: N/A BIOS: Award v: F7 date: 10/13/2011
CPU:       Quad core AMD Phenom II X4 965 (-MCP-) arch: K10 rev.3 cache: 2048 KB
           flags: (lm nx sse sse2 sse3 sse4a svm) bmips: 28990
           clock speeds: max: 3600 MHz 1: 2200 MHz 2: 2200 MHz 3: 2200 MHz 4: 800 MHz
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Tahiti XT [Radeon HD 7970/8970 OEM / R9 280X] bus-ID: 01:00.0
           Display Server: x11 (X.Org 1.19.6 ) drivers: ati,radeon (unloaded: modesetting,fbdev,vesa)
           Resolution: 1920x1080@60.00hz
           OpenGL: renderer: AMD TAHITI (DRM 2.50.0 / 4.15.0-20-generic, LLVM 6.0.0)
           version: 4.5 Mesa 18.0.5 Direct Render: Yes
Audio:     Card-1 Advanced Micro Devices [AMD/ATI] Tahiti HDMI Audio [Radeon HD 7870 XT / 7950/7970]
           driver: snd_hda_intel bus-ID: 01:00.1
           Card-2 Advanced Micro Devices [AMD/ATI] SBx00 Azalia (Intel HDA)
           driver: snd_hda_intel bus-ID: 00:14.2
           Sound: Advanced Linux Sound Architecture v: k4.15.0-20-generic
Network:   Card: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
           driver: r8169 v: 2.3LK-NAPI port: ce00 bus-ID: 03:00.0
           IF: enp3s0 state: up speed: 100 Mbps duplex: full mac: 50:e5:49:ca:da:e0
Drives:    HDD Total Size: 1250.3GB (76.4% used)
           ID-1: /dev/sda model: Samsung_SSD_860 size: 250.1GB temp: 0C
           ID-2: /dev/sdb model: ST1000DM003 size: 1000.2GB temp: 37C
Partition: ID-1: / size: 90G used: 19G (22%) fs: btrfs dev: /dev/dm-1
           ID-2: /boot size: 244M used: 144M (64%) fs: ext4 dev: /dev/sda1
           ID-3: /home size: 48G used: 34G (71%) fs: btrfs dev: /dev/dm-2
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 41.0C mobo: N/A gpu: 57.0
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 284 Uptime: 1:39 Memory: 2452.5/7974.4MB Init: systemd runlevel: 5 Gcc sys: 7.3.0
           Client: Shell (zsh 5.4.2) inxi: 2.3.56 

</pre>

**Comment by orestisf1993** [comment]
This appears to be an issue elsewhere. Start vlc / chromium from the command line and move it to the second monitor to see if there is any helpful stderr output.

**Comment by Bobkins** [comment]
this is output, what do you think? 
https://pastebin.com/riiCS96Y

**Comment by orestisf1993** [comment]
Generally seems to be an issue with your drivers, maybe fixing the acceleration API errors is a good starting point.

I don't think there is anything i3 can do here though.
