### ISSUE TITLE
Add shortcut hints  to each tile

### ISSUE THREAD

**Issue by Peixinho** [i3/i3#3362]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Expected Behavior

What is the possibility to add shortcuts (small hints like vimium in chromium) to each individual tile that we open (maybe only visible when we press $mod key or something) to let us jump to specific window by pressing those shortcuts.
Thanks for this amazing wm

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
</pre>

<pre>
</pre>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version:
- Are you using a compositor (e.g., xcompmgr or compton):
</pre>

**Comment by Airblader** [comment]
There's an external tool providing such functionality and we believe that this is indeed better handled externally. You can find the project [https://github.com/cornerman/i3-easyfocus](here).
