### ISSUE TITLE
Option to disable border/decoration click resizing for floating windows

### ISSUE THREAD

**Issue by gonX** [i3/i3#3371]
## I'm submitting a…

<pre>
[ ] Bug
[X] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Currently, right clicking the border or decoration will resize the window while the button is held. Left clicking the decoration will move the window while the button is held.

## Expected Behavior
The current behavior is fine if you are not aware of the modifier key.

However, by holding the modifier key, you can achieve the exact same results.
Therefore, it might be interesting for some users to disable the former feature.

My suggested implementation is a global switch to toggle this.

I may be able to write the code for this if there is interest (looks like a couple of lines in `src/click.c`?)

**Comment by orestisf1993** [comment]
```
bindsym --border button1 nop
bindsym --border button3 nop
```
https://i3wm.org/docs/userguide.html#mousebindings

Though this isn't specific to floating windows.

**Comment by orestisf1993** [comment]
I support supporting match criteria for bindsyms though.

**Comment by Airblader** [comment]
As @orestisf1993 pointed out, this is possible already, so I'm going to close this. Match criteria on a per-binding basis is a fundamentally different feature request to discuss.

**Comment by gonX** [comment]
Thanks and sorry, didn't consider the option to `nop` the operations. Is there a way to handle this for LMB+RMB? `bindsym --border button1+button3 nop` still resizes the border for me.

**Comment by Airblader** [comment]
Bind them both to nop individually.

**Comment by orestisf1993** [comment]
He means both clicked at the same time

**Comment by Airblader** [comment]
Why would you press both left and right mouse button at the same time in the first place?

**Comment by orestisf1993** [comment]
Don't know if there is a usecase but to support it we would need to add `XCB_KEY_BUT_MASK_BUTTON_x` in `event_state_from_str`.

**Comment by gonX** [comment]
Alright, sounds like it's more work than it's worth, especially if I'm the only one who has brought it up.

My specific use case is with a game that uses both mouse buttons regularly, and the game does not handle resizing very gracefully. So accidentally grabbing the screen edge can be fatal (in-game).

My final solution is just to remove the border entirely from the window. Thanks for your time, and sorry for the noise.
