### ISSUE TITLE
Feature request: back_and_forth_on_output

### ISSUE THREAD

**Issue by eater** [i3/i3#3373]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

I have two monitors. Say the layout is like this (^ indicates focus): `[6] [^3] ` I hit $mod-F2 to move to workspace 2, which lives on the other output, and now I've got `[^2] [3]`. I want to hit $mod-F2 again and toggle back to workspace 6, but instead that gives me `[2] [^3]`.

## Expected Behavior

When back_and_forth is invoked, hjitting a key to "switch to the current workspace" should switch the current output to the workspace previously displayed on the current output.

## Environment

<pre>
i3 version: 4.15 (2018-03-10)
</pre>

<pre>
- Linux Distribution & Version: Xubuntu 18.04
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by Airblader** [comment]
Hi,

we discussed extending the back_and_forth behavior in various ways in the past, but we decided not to add any more features to this as the implementation is already quite complex. This kind of behavior can easily be implemented with an external solution, so we recommend going down that route. If you need help doing so, you can ask a question on the /r/i3wm subreddit. Thanks for understanding!

**Comment by eater** [comment]
Thanks, @Airblader. I [asked](https://www.reddit.com/r/i3wm/comments/9h6ij2/how_can_i_restrict_back_and_forth_workspace/) about this on Reddit per your suggestion and nobody has replied, but the more I think about it, I can't think of any reason that this shouldn't be the _default_ behavior of back_and_forth. The general point of back_and_forth functionality as I understand it is to toggle between the current state and the previous state. But the way it works now, it's involving a _third_ state, like this:

First state: `[6] [^3]`
Second state: `[^2] [3]`
Third state: `[2] [^3]`

I think the default and expected behavior should be to toggle between the first and second states, not the second and third states.

**Comment by orestisf1993** [comment]
Assuming you have workspace assignments to outputs, this seems to be a bug. Here's a testcase:

```diff
diff --git a/testcases/t/176-workspace-baf.t b/testcases/t/176-workspace-baf.t
index 01906e462..b1e47accf 100644
--- a/testcases/t/176-workspace-baf.t
+++ b/testcases/t/176-workspace-baf.t
@@ -165,4 +165,34 @@ is(focused_ws, '6: baz', 'workspace 6 now focused');
 
 exit_gracefully($pid);
 
+################################################################################
+# TODO
+# See issue: #3373.
+################################################################################
+
+$config = <<EOT;
+# i3 config file (v4)
+font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
+
+fake-outputs 1024x768+0+0,1024x768+1024+0
+
+workspace 1 output fake-0
+workspace 2 output fake-1
+workspace 3 output fake-0
+workspace 4 output fake-1
+EOT
+
+$pid = launch_with_config($config);
+
+cmd 'workspace 2';
+cmd 'workspace 1';
+cmd 'workspace 4';
+cmd 'workspace back_and_forth';
+is(focused_ws, '1', 'workpace 1 now focused');
+
+ok(!workspace_exists('4'), 'workspace 4 closed');
+
+exit_gracefully($pid);
+
+
 done_testing;
```

**Comment by orestisf1993** [comment]
Wait, I changed my mind. `back_and_forth` refers to the previous focused workspace, not the previous "state":

> To switch back to the previously focused workspace, use workspace back_and_forth; likewise, you can move containers to the previously focused workspace using move container to workspace back_and_forth.

**Comment by eater** [comment]
The docs' explanation of `workspace_auto_back_and_forth` (below) says that the purpose of this convenience tool is so you "don't need to remember" which workspace you just came from. But in the case where the previous focused workspace is still visible on the other output, it's not a question of remembering, so just going back and forth between two visible workspaces sort of removes the usefulness of `back_and_forth`. IMHO.

> For instance: Assume you are on workspace "1: www" and switch to "2: IM" using mod+2 because somebody sent you a message. You don’t need to remember where you came from now, you can just press mod+2 again to switch back to "1: www".

**Comment by orestisf1993** [comment]
Still, the behavior is the one described in the docs. Changing the unfocused visible workspace might not be what the user expect.

As @Airblader said, the implementation for this is not trivial but it can be implemented using the IPC interface.

You'll have to subscribe to workspace events and save the previously focused workspace for each output. Then, whenever you want to switch to a workspace, check if the target workspace is the same as the current workspace and if yes, grab the previous workspace for the current output and focus that.

**Comment by medwatt** [comment]
I also found the current behaviour of `workspace back_and_forth` strange. Surprisingly, it was quite an easy feature to implement using `i3ipc-python`. [Here](https://github.com/medwatt/i3-workspace-back-and-forth)'s my implementation in case someone is interested.

**Comment by hnorkowski** [comment]
> I also found the current behaviour of `workspace back_and_forth` strange. Surprisingly, it was quite an easy feature to implement using `i3ipc-python`. [Here](https://github.com/medwatt/i3-workspace-back-and-forth)'s my implementation in case someone is interested.

Your Repo is down. Do you have it somewhere else?

**Comment by medwatt** [comment]
> > I also found the current behaviour of `workspace back_and_forth` strange. Surprisingly, it was quite an easy feature to implement using `i3ipc-python`. [Here](https://github.com/medwatt/i3-workspace-back-and-forth)'s my implementation in case someone is interested.
> 
> Your Repo is down. Do you have it somewhere else?

I didn't think people found it useful, so I deleted it.

**Comment by tipa40** [comment]
> I didn't think people found it useful, so I deleted it.

If someone comes up with a solution for this I am interested and would find it very useful. :) (mostly to be applicable over on swaywm as well ;) )
