### ISSUE TITLE
Please allow enabling/disabling manpages and docs separately with individual --enable-xx arguments

### ISSUE THREAD

**Issue by yurivict** [i3/i3#3378]
## I'm submitting a…

<pre>
[ ] Bug
[X] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Can't leave manpages and remove docs

## Expected Behavior
Need to be able to enable docs independently from manpages.
Please have separate enable/disable arguments for both.

## Reason
In the FreeBSD port we need to be able to enable/disable manpages and docs separately, because they are separate port options.

Version 4.15.0.1 on FreeBSD.

**Comment by Airblader** [comment]
There's a port for vanilla i3 AFAIK, so my main question would be why the i3-gaps port needs this if the i3 port doesn't? Can you answer that or involve the maintainer of the i3 port for this?

**Comment by yurivict** [comment]
They both need this. All ports need to be able to control manpages and docs separately.

**Comment by Airblader** [comment]
OK then. Can we get the maintainer of that port involved then so that they're aware of this?
As for the request itself: sounds good to me, PRs welcome.

**Comment by yurivict** [comment]
I'm not a maintainer of either of them.

**Comment by Airblader** [comment]
So can we get both of them involved, then? I'm guessing a change in i3 is a bit pointless if the ports won't adapt it.

**Comment by yurivict** [comment]
The more people are involved, the lower the chance of something to be successful.
Of course it will be adopted, I will submit a patch and they will likely adopt it.
