### ISSUE TITLE
introduce contexts based workflow and DRY configs

### ISSUE THREAD

**Issue by arael** [i3/i3#3382]
## I'm submitting a…

<pre>
[ ] Bug
[x ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Currently the workspaces are not assigned to any context. The user has to decide how to use the workspaces to create meaningful context in the workflow.

Usually, for most of the people, context is decided by workspace numbers. But I think it can be better.

I have a lot of projects I work on concurrently. It would be amazing if I could separate them in a more meaningful way besides the workspace number.

Right now i3 does not have the concept of context. The closest I could think of is the mode. If you set the resize mode you get a label on the bar showing you that you are in a new mode.
I think this can be extended to make a more powerful and flexible feature called context.

## Expected Behavior
A context can be thought as a separated i3 session within the i3 session or as a collection of workspaces.

For Example:
Context 1: Developing platform A

- workspace 1: terminal
- workspace 2: gvim for modifying the code of the platform A
- workspace 3: browser instance pointing to the platform A
- workspace 4: browser instance for searching online and documentation

Context 2: Supporting platform B

- workspace 1: terminal
- workspace 2: gvim for modifying the code of the platform B
- workspace 3: browser instance to the platform B
- workspace 5: browser for searching online and documentation

Context 3: Communications

- workspace 1: terminal
- workspace 2: mail client
- workspace 3: skype
- workspace 4: browser

Context 4: New project, here you give a name for the project and a project directory is created

- workspace 1: terminal already pointing to the the project directory, git repo initialized for the directory
- workspace 2: gvim already started pointing got the directory
- workspace 3: browser ready for the project
- workspace 4: browser ready for searching online

Once you switch the context all the workspaces belonging to that context are switched too.
I think one way to implement this idea would be by providing one of the next two features, maybe even both:

It should be possible to include configuration chunks in the default configuration with a new include command. This would allow for the modes to include the default configuration without being forced to repeat the default keybindings.

1. It should be possible to the mode, by including a command such as default_bindings to include the default bindings and then overwrite them.
2. Both of these two features would make it easier to implement the context feature and would avoid repeating the config directives.

I think either of these two features would be fine, even better would be having them both.

I know I could use separated X sessions, but I also think the scratchpad could be used as a cross-context workspace. This way the user could also move the windows between contexts. This way music players, and small utilities, would be available no matter on which context the user has switched.

There are probably better ways to implement contexts. I though about achieving this by modifying the existing commands.

Feature 1 would extend the modes by allowing the user to decide if the mode has to carry the default keybindings.

Feature 2 would allow the DRY approach on the config.

**Comment by orestisf1993** [comment]
You can implement this using the IPC interface. I think the one thing we can improve here is #2333 so that you can hide workspaces in other "contexts".

**Comment by orestisf1993** [comment]
> It should be possible to include configuration chunks in the default configuration with a new include command. This would allow for the modes to include the default configuration without being forced to repeat the default keybindings.

You can do this using third-party software like templaters / template engines: http://jinja.pocoo.org/docs/2.10/.

The `include` directive has been discussed in #1197.

**Comment by Airblader** [comment]
This essentially duplicates #1808 / #2874, thus closing. As @orestisf1993 pointed out, a combination with #2333 would allow implementing this externally anyway, which I find preferable.
