### ISSUE TITLE
Popups open in previous workspace

### ISSUE THREAD

**Issue by Nano-Sec** [i3/i3#3383]
I'm submitting a Bug

## Current Behavior
Whenever any app opens up a second window (save file window for chrome for example), It goes to the previously visited workspace

## Expected Behavior
Window pops up in the current workspace

## Reproduction Instructions
Visit workspace x.
Open up chrome and save a file.
Window pops up on workspace x.

## Environment
i3 version 4.15.0.1 (03-13-2018) © 2009 Michael Stapelberg and contributors

- Linux Distribution & Version: Manjaro 17.1.12
- I'm using compton

[i3.txt](https://github.com/i3/i3/files/2349731/i3.txt)

**Comment by orestisf1993** [comment]
I see that you have a `for_window [class="Google-chrome"]` rule in your config. Are you sure that the new window doesn't trigger it?

**Comment by Nano-Sec** [comment]
I don't think so. That statement assigns workspace 1 for chrome windows, so I'm always on 1 with chrome. The dialogues pop up on the previously visited workspaces, say 2 or 4 or 6. It's not one specific number.

**Comment by Airblader** [comment]
Can you please attach a log file as described by i3bot's comment? Thank you!

**Comment by Nano-Sec** [comment]
Here you go: 
https://logs.i3wm.org/logs/5682897923080192.bz2

**Comment by orestisf1993** [comment]
Did you [enable logging](https://i3wm.org/docs/debugging.html#_enabling_logging) in your session?

**Comment by Nano-Sec** [comment]
Sorry about that. The exec commands didn't enable shm logging for some reason so i had to enable on the fly. Does this seem right?

https://logs.i3wm.org/logs/5704940030787584.bz2

**Comment by Nano-Sec** [comment]
Oh right. Makes sense. Disabling that solves it. Thank you so much!

**Comment by He-Ro** [comment]
You should also be able to add `--no-auto-back-and-forth` to the move call. This way you can keep the setting on, but for this specific case it is ignored.

**Comment by oopschen** [comment]
problem solved by follow config:
`
assign [class="(?i)firefox"] 1

for_window [class="(?i)firefox"] move --no-auto-back-and-forth container to workspace 1
`
