### ISSUE TITLE
More useful `mouse_warping`

### ISSUE THREAD

**Issue by I60R** [i3/i3#3387]
## I'm submitting a…
<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Currently `mouse_warping` option accepts only `output` value (besides `none`) which centers cursor on newly focused windows that are placed on different monitor

## Expected Behavior
It would be useful to also accept value that centers cursor on all newly focused windows. 
Such behavior provides the following benefits:

1. It don't requires to remember cursor position
2. It's very handy on floating windows
3. In most of cases it reduces path to target that should be clicked

The value might be:

`mouse_warping focus`

----

Additionally, this might include option to warp cursor only when workspace changes. Accepting all the following values then seems to be more reasonable:

`mouse_warping  none|output|workspace|window`

----

Users that uses mouse rarely might prefer to not place cursor in center of window, but at the top of window / bottom-right corner / etc. 
Allowing that with the following syntax might be a good thing:

`mouse_warping none|output|workspace|window <top|center|bottom> <left|center|right>`

----

And disabling / changing it for some windows:

`for_window [..] mouse_warping none | <top|center|bottom> <left|center|right>`

**Comment by orestisf1993** [comment]
#3387, #2813
