### ISSUE TITLE
Feature Request: Arbitary-width workspaces with 'Camera'-style scrolling

### ISSUE THREAD

**Issue by marzhall** [i3/i3#3413]
## I'm submitting a…

<pre>
[ ] Bug
[ x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
When pressing `Mod+Shift+Enter`, or holding the `Mod` key and clicking and moving the mouse, nothing happens.

## Desired Behavior
When pressing `Mod+Shift+Enter` key, a new column is created to the right of the current columns, and the screen (that being all currently-visible column windows) 'scrolls' to the right - as if the user is viewing the desktop through a camera, and the camera is moving. This means that the current leftmost column is no longer in view.

In addition, when pressing the above key combination, this process can repeated an arbitrary number of times, with a new column being added for each press, and the screen scrolling to the new column each time.

When pressing the `Mod` key and moving the mouse, all windows scroll left or right, depending on which direction the mouse moves.

The above behavior would be able to be turned on or off in the configuration.

## Potential additional behaviors

- Wrapping of the camera view; that is, if the user scrolls right until the end of the existing columns, the left-most window becomes visible again.

- Creating windows to the left instead of the right

- Switching workspaces to instead be 'bookmarks' of locations in the indefinitely-long chain of columns., so that the user can press `ctrl+mod+shift+<number>' to 'bookmark' a location in the chain, then jump to it by pressing `mod+shift+<number>`.

## Reasoning

I think it would be neat.

## Additional notes

I'm planning to implement this in a fork, but would be interested to see if anyone else thinks the behavior would be interesting, or has any ideas or insights.

**Comment by Airblader** [comment]
Thanks for filing this issue. I think this is a pretty big change that we're not looking to add to i3 at this time due to the complexity it willl add and the questions it will raise in the usability of it. I also think this requires pretty large changes to i3.

Since you plan on implementing it in a fork anyway, feel free to update us here once it is done. There's always a chance to backport it if we change our mind then. :-) Thanks for understanding!
