### ISSUE TITLE
no_focus doesn't work properly

### ISSUE THREAD

**Issue by mac1202** [i3/i3#3423]
## I'm submitting a…

<pre>
[X ] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Hi I have added this line in config files to avoid notification stealing focus
no_focus [window_type="notification"]

The issue I got is that it only work when I have two or more windows open on the workspace. If I only have 1 windows open the notification get the focus.

Screenshot with only 1 window open notification got the focus (blue border)
https://ptpb.pw/aJhX.png
with 2 windows no focus (no blue border)
https://ptpb.pw/-lkR.png

## Expected Behavior
Notification doesn't steal the focus.

## Reproduction Instructions
Open only 1 terminal on a workspace and create a notification with notify-send.

## Environment
<pre>
Running i3 version: 4.15.0.1 (03-13-2018) 
</pre>

<pre>
Config :  https://ptpb.pw/OKL0
</pre>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5661887614156800.bz2
</pre>

<pre>
- Linux Distribution & Version: Manjaro linux 17.1.12
- Are you using a compositor (e.g., xcompmgr or compton): yes, compton
</pre>

**Comment by andreatta** [comment]
Sorry for being off-topic, but what statusbar are you using?

**Comment by mac1202** [comment]
It's just a kde panel, with breeze dark theme.
