### ISSUE TITLE
cpu_usage formatting handles cpu10 incorrectly

### ISSUE THREAD

**Issue by Cypher1** [i3/i3#3427]
## I'm submitting a…
[x ] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
cpu_usage { format = "%cpu10" } renders as XX%0
## Expected Behavior
cpu_usage { format = "%cpu10" } renders as XX%

## Reproduction Instructions
Have greater than 9 cores and set `cpu_usage { format = "%cpu10" }` in i3status/config.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: Binary i3 version:  4.15 (2018-03-10) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15 (2018-03-10) (pid 7235)o abort…)
Loaded i3 config: /usr/local/google/home/jopra/.config/i3/config (Last modified: Thu 13 Sep 2018 09:29:40 AM AEST, 1320810 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
cpu_usage { format = "%cpu10" }
</pre>

<pre>
- Linux Distribution & Version:Debian 4.17.17
</pre>

**Comment by Cypher1** [comment]
I don't think this bug needs a log (no crash or particular activity).

**Comment by Airblader** [comment]
Thanks for reporting this issue. However, this is the repository for the window manager itself. Could you please reopen it against the correct repository, i3/i3status? Thanks!

**Comment by Cypher1** [comment]
Sorry, thought they were the same repo. Thanks
