### ISSUE TITLE
FEATURE: Support non-orphaned exec

### ISSUE THREAD

**Issue by serussell** [i3/i3#3437]
## I'm submitting a…

<pre>
[ ] Bug
[X] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Currently, i3 only supports an `exec` that spawns and then orphans the child process.  This prevents the use of [polkit's](https://www.freedesktop.org/wiki/Software/polkit/) `pkexec`, which -- for security reasons -- refuses to run in orphaned child processes; pkexec provides finer-grained control (and more security) over programs running with elevated permissions.

*An* example is backlight control via commands executed by i3 hotkeys; RandR extensions for this are not available in all drivers.  Other commands can be used, but they require priviledge escalation, and so require either setuid, sudo, or pkexec.  Of these, pkexec is the most secure, but is not currently an option under i3.

## Expected Behavior

To support `pkexec`, a version of i3's exec would provide non-orphaning behavior; this could be through a new exec keyword, or as an argument to exec.

## Reproduction Instructions

To follow the rabbit, add a hotkey that exec's a command with pkexec:

```
bindsym XF86MonBrightnessUp exec pkexec brillo -A 10 -q
```

and watch the fun in `.xsession-errors` when you try to execute this command.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.15.0.1 (03-13-2018) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15.0.1 (03-13-2018) (pid 22268)rt…)
Loaded i3 config: /home/ser/.i3/config (Last modified: Thu 04 Oct 2018 09:19:19 PM CDT, 42458 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

## Log information

The relevant xsession log line, generated on every key press that executes `pkexec`, is:
<pre>
Refusing to render service to dead parents.
</pre>

## System information

<pre>
OS: Arch Linux x86_64
Host: XPS 13 9343
Kernel: 4.18.7-arch1-1-ARCH
Resolution: 1920x1080, 1920x1080, 1920x1080
WM: i3
CPU: Intel i5-5200U (4) @ 2.700GHz
GPU: Intel HD Graphics 5500
Compositor: compton
</pre>

**Comment by orestisf1993** [comment]
Don't know which is the best way but you can work around this: `bindsym XF86MonBrightnessUp exec bash -c 'true $(pkexec ls)'`

**Comment by serussell** [comment]
That is downright devious. I love it!

**Comment by orestisf1993** [comment]
:) It can be simplified more since i3 passes `exec`s to `sh -c`: `bindsym XF86MonBrightnessUp exec true $(pkexec ls)`

Given that we can work around the issue, I am going to close this issue since the extra complexity is not worth it.
