### ISSUE TITLE
Key binding in i3wm will not make the rofi window to appear. 

### ISSUE THREAD

**Issue by ghost** [i3/i3#3446]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

# System info

```
$ rofi -v
Version: 1.5.1
```

rofi configuration: https://gist.github.com/phfrohring/237f89df2b2e2a7f25e5a01bf2549729

```
$ i3 --moreversion 2>&-
Binary i3 version:  4.14.1 (2017-09-24) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.14.1 (2017-09-24) (pid 1340)abort…)
Loaded i3 config: /home/phf/.config/i3/config (Last modified: Wed 10 Oct 2018 08:49:08 PM CEST, 2010 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

relevant line of i3 config: `bindsym --release $mod+d exec ~/bin/./trigger_rofi`

content of `~/bin/./trigger_rofi`:

```
#! /usr/bin/env bash
rofi -combi-modi window,drun,run,ssh -theme solarized -font 'hack 10' -show combi -modi combi
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

No compositor is used.

# Steps to reproduce

typing `$mod+d` won't trigger rofi.

# What behaviour you see

Nothing.

# What behaviour you expect to see

The same behaviour as when I execute: `$ ~/bin/./trigger_rofi` i.e. rofi to show up.

**Comment by phfrohring** [comment]
Thx!

```
$ cat i3_logs/i3log-2018-10-11-19-04-08 | tail
10/11/2018 07:04:08 PM - workspace.c:extract_workspace_names_from_bindings:129 - binding with command restart
10/11/2018 07:04:08 PM - workspace.c:extract_workspace_names_from_bindings:129 - binding with command exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"
10/11/2018 07:04:08 PM - workspace.c:extract_workspace_names_from_bindings:129 - binding with command mode "resize"
10/11/2018 07:04:08 PM - workspace.c:extract_workspace_names_from_bindings:129 - binding with command exec --no-startup-id pactl -- set-sink-volume 0 +5% #increase sound volume
10/11/2018 07:04:08 PM - workspace.c:extract_workspace_names_from_bindings:129 - binding with command exec --no-startup-id pactl -- set-sink-volume 0 -5% #decrease sound volume
10/11/2018 07:04:08 PM - workspace.c:extract_workspace_names_from_bindings:129 - binding with command exec --no-startup-id pactl set-sink-mute 0 toggle # mute sound
10/11/2018 07:04:08 PM - workspace.c:extract_workspace_names_from_bindings:129 - binding with command exec --no-startup-id "light -A 2.5"
10/11/2018 07:04:08 PM - workspace.c:extract_workspace_names_from_bindings:129 - binding with command exec --no-startup-id "light -U 2.5"
10/11/2018 07:04:08 PM - workspace.c:extract_workspace_names_from_bindings:129 - binding with command exec --no-startup-id gnome-screenshot -a --file=$HOME/screenshots/screenshot-$(date +"%Y-%m-%d_%H-%M-%S").jpg
10/11/2018 07:04:08 PM - ERROR: Another window manager seems to be running (X error 10)
```
[gist of log](https://gist.github.com/phfrohring/ccf02d54f3977d8dd497a365e2880df2)

**Comment by orestisf1993** [comment]
> 10/11/2018 07:04:08 PM - ERROR: Another window manager seems to be running (X error 10)

How did you try to produce the log? You have to run `i3-dump-log`. See https://i3wm.org/docs/debugging.html

If the `notify-send` command mentioned here https://github.com/DaveDavenport/rofi/issues/865#issuecomment-428698355 works, the script is executed by i3

**Comment by phfrohring** [comment]
`i3-dump-log` gave me this:

```
i3-dump-log: ERROR: i3 is running, but SHM logging is not enabled.

You seem to be using a release version of i3:
  4.14.1 (2017-09-24)

Release versions do not use SHM logging by default,
therefore i3-dump-log does not work.

Please follow this guide instead:
https://i3wm.org/docs/debugging-release-version.html
```

So I followed the link and were told to do this: `exec /usr/bin/i3 -V -d all >~/i3log-$(date +'%F-%k-%M-%S') 2>&1`

So, I tried the failing binding and then executed `$ /usr/bin/i3 -V -d all >~/i3log-$(date +'%F-%k-%M-%S') 2>&1` hoping that it would catch something. 

And here we are.

So, I guess I should install the 4.15 version and use `i3-dump-log` so that you may help. 

Thank you for looking at these things!

**Comment by orestisf1993** [comment]
> Release versions do not use SHM logging by default, therefore i3-dump-log does not work.

\<facepalm\> I didn't know this.

> So, I tried the failing binding and then executed `$ /usr/bin/i3 -V -d all >~/i3log-$(date +'%F-%k-%M-%S') 2>&1` hoping that it would catch something. 

What the link means is to start i3 like this in your ~/.xinitrc or ~/.xsession file, you can't use it in an already running i3 session.

> So, I guess I should install the 4.15 version and use i3-dump-log so that you may help.

i3-dump-log does not work with release versions, so it won't work with 4.15 either
