### ISSUE TITLE
Option to disable scroll wheel actions on window list at top of screen

### ISSUE THREAD

**Issue by bolangi** [i3/i3#3447]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When the mouse cursor is on the horizontal black bar at the top of the screen with the tabs that bring windows to the forground, operating the scroll wheel causes a changes to the windows occupying the foreground. I find that when using the scroll wheel for some other purpose, if the mouse cursor accidentally touches the top of the screen this causes unintended changes to window focus. 
## Desired Behavior

I would like some way to disable this behavior of the scroll wheel. 
## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
</pre>
Binary i3 version: 4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors (Getting version from running i3, press ctrl-c to abort…)
Running i3 version: 4.13 (2016-11-08) (pid 11829) Loaded i3 config: /home/jroth/.i3/config (Last modified: Thu 23 Feb 2017 09:14:18 PM HST, 51281441 seconds ago) The i3 binary you just called: /usr/bin/i3 The i3 binary you are running: /usr/bin/i3

<pre>
- Linux Distribution & Version:
- Are you using a compositor (e.g., xcompmgr or compton):
</pre>
Devuan ascii

**Comment by bolangi** [comment]
On Wed, Oct 10, 2018 at 05:23:50PM -0700, Ingo Bürk wrote:
> Try adding
> 
>     bindsym button4 nop
>     bindsym button5 nop
> 
> to your i3bar configuration (that is, inside the `bar {} ` block in the config). 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/i3/i3/issues/3447#issuecomment-428776120

Thanks.  I'll look more carefully at the docs and post to IRC or mailing list next time.
BTW I've been using i3 for years with the default configuration  :-)

-- 
Joel Roth

**Comment by bolangi** [comment]
I'm reporting the same behavior after a fix was suggested and after upgrading to debian package i3-wm 4.19.1-1. 
 
.i3/config contains:

  bar {
      bindsym button4 nop                                                                                  
      bindsym button5 nop
      status_command i3status
  }

Despite this, the scroll wheel continues to change the window focus when the cursor is on the top bar. 

My system details:

   ~ $ lsb_release -a  
  No LSB modules are available.
  Distributor ID: Devuan
  Description:    Devuan GNU/Linux 4 (chimaera)
  Release:        4
  Codename:       chimaera

lsusb
  Bus 001 Device 011: ID 046d:c52b Logitech, Inc. Unifying Receiver

Thank you

**Comment by Airblader** [comment]
Please update to the latest version and if the issue still exists there, open a new issue. Thanks!
