### ISSUE TITLE
Error with client.unfocused on start

### ISSUE THREAD

**Issue by TheDevKiller** [i3/i3#3449]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
When I start i3, I have an error in my config file

## Expected Behavior
No errors when I start i3

## Reproduction Instructions
Use this in a config
<pre>
# Colors
set_from_resource       $background       background
#set_from_resource       $theme-active     foreground
set_from_resource       $theme-inactive   trueblack
set $theme-active #27ae60

client.background             $background
client.focused          $theme-active   $theme-active   $theme-inactive $theme-active   $theme-active
client.focused_inactive $theme-inactive $theme-inactive $theme-active   $theme-active   $theme-inactive
client.unfocused        $theme-inactive $theme-inactive $theme-active   $theme-inactive $theme-inactive
</pre>

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.15.0.1 (03-13-2018) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15.0.1 (03-13-2018) (pid 862)bort…)
Loaded i3 config: /home/thedevkiller/.config/i3/config (Last modified: mer. 10 oct. 2018 20:51:18 CEST, 55613 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

## Full config
https://pastebin.com/5v4FHxdy

## Linux & compositor
<pre>
- Linux Distribution & Version: Manjaro 17.1.12 Hakoila
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

**Comment by orestisf1993** [comment]
`set_from_resource $<name> <resource_name> <fallback>` (you can keep the whitespace)
`name=$theme-inactive`
`resourcename=trueblack`
`fallback=`(empty)

Is trueblack defined in your ~/.Xresources? If not, the `client.unfocused  like will fail.

**Comment by TheDevKiller** [comment]
I don't have this file so I replaced theses lines (colors) by a simple set. It works, thank you
