### ISSUE TITLE
XF86MonBrightness keys cause window closure

### ISSUE THREAD

**Issue by GodOrGovern** [i3/i3#3458]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When either of the XF86MonBrightness keys are hit for the first time after starting a new i3 session, all windows, programs, and auto-started applications are closed. Only some can be re-opened. For example, Firefox can be opened but Terminator cannot be opened.

## Expected Behavior

The XF86MonBrightness keys should change the brightness of the monitor without producing any other unexpected behavior.

## Reproduction Instructions

The relevant lines of my config file are:

    # Sreen brightness controls
    bindsym XF86MonBrightnessUp exec xbacklight -inc 5
    bindsym XF86MonBrightnessDown exec xbacklight -dec 5

I have flux installed as well but this problem has not occurred up until today, so I doubt it is the problem. To reproduce: copy those lines into your config file, start a new i3 session, open a program (to see the effect), and hit either of the XF86MonBrightness keys.

## Environment

Output of `i3 --moreversion 2>&-`:

    Binary i3 version:  4.15 (2018-03-10) © 2009 Michael Stapelberg and contributors
    Running i3 version: 4.15 (2018-03-10) (pid 31623) abort…)
    Loaded i3 config: /home/david/.config/i3/config (Last modified: Mon 15 Oct 2018 12:36:05 PM EDT, 2954 seconds ago)
    The i3 binary you just called: /usr/bin/i3
    The i3 binary you are running: i3

<pre>
i3 version: 4.15
</pre>

<pre>
https://pastebin.com/yR8ACZdw
</pre>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5661725076488192.bz2
</pre>

<pre>
- Linux Distribution & Version: Manjaro 18.0.0-rc
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by orestisf1993** [comment]
Does this happen when

1. You delete the bindsym from your config, start a new session and press the keys?
2. If you run the xbacklight command from your terminal?

**Comment by GodOrGovern** [comment]
@orestisf1993 It happens if I delete the bindsym from my config but not when I run xbacklight from the terminal.

**Comment by orestisf1993** [comment]
It seems that the issue is with the key then. What are you using to launch i3?

**Comment by GodOrGovern** [comment]
I believe I am just using my .xinitrc. Here's a link to it: https://pastebin.com/MRciG4q4

**Comment by orestisf1993** [comment]
Can you please remove dbus-launch and retry?

**Comment by GodOrGovern** [comment]
@orestisf1993 Sorry, but how do I remove dbus-launch? I don't want to make the situation worse by fumbling with things and Google is being unhelpful.

**Comment by orestisf1993** [comment]
I didn't mean to remove dbus-launch completely from your system, just comment out `exec $(get_session)` and replace it with `exec i3`.

**Comment by GodOrGovern** [comment]
@orestisf1993 Thank you very much, that fixed the problem. For reference, here is my new .xinitrc: https://pastebin.com/RLza5X38

**Comment by orestisf1993** [comment]
Related to #2979, #3439
