### ISSUE TITLE
How to launch terminal as fullscreen

### ISSUE THREAD

**Issue by fxkrait** [i3/i3#3460]
## I'm submitting a…

<pre>
[X?] Bug
[ ] Feature Request
[X] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Describe the current behavior,
Command:
bindsym $mod+Ctrl+u exec --no-startup-id urxvt -e cmatrix & sleep 0.2 & i3-msg fullscreen

Works when no windows in current workspace.

Does not work when another terminal or application is open.
It will full screen an existing opened window.

## Expected Behavior

Except the new terminal to be launched, focused, and put into fullscreen.

## Reproduction Instructions
Run bindsym $mod+Ctrl+u exec --no-startup-id urxvt -e cmatrix & sleep 0.2 & i3-msg fullscreen

with no terminals open in workspace, and with one terminal in workspace.

## Environment

Binary i3 version:  4.15.0.1 (03-13-2018) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15.0.1 (03-13-2018) (pid 4218)ort…)
Loaded i3 config: /home/toreshi/.config/i3/config (Last modified: Tue 16 Oct 2018 11:39:19 AM PDT, 306 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

**Comment by orestisf1993** [comment]
You put the background process in the background. Try `sleep 0.2 && i3-msg fullscreen`.

**Comment by Airblader** [comment]
sleep is, as always, a hack here, however. The proper way is to start the terminal emulator with a specific class or other attribute and have a rule in your config to match on which enables fullscreen. The underlying issue here is that executing a binary and opening a window are separate actions. More information can be found here: https://www.reddit.com/r/i3wm/wiki/faq/assign_emulator

Closing since there's no bug here.

**Comment by fxkrait** [comment]
Do I have the ability to set urxvt fullscreen **only** for the given command I want to execute, or will the wm_class apply to all instances urxvt is run (I.E. it will always execute full screen)?

Would the correct solution be to then use wm_class, but use a different terminal editor for this command?

**Comment by Airblader** [comment]
Ultimately this is handled by the terminal emulator. Most of them allow you to pass a flag to set the WM_CLASS for one specific instance of it. This is explained in the link I provided and is what I consider the correct solution.

**Comment by fxkrait** [comment]
Awesome! Thanks @orestisf1993.
