### ISSUE TITLE
i3bar: Provide modifier states in events

### ISSUE THREAD

**Issue by soumya92** [i3/i3#3461]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

i3bar events include the button and co-ordinates.

## Desired Behavior

i3bar events also include the modifier state (list of active modifiers when event happened). This would allow different behaviour for Ctrl+Left Click vs. Left Click, for example.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
Binary i3 version:  4.15 (2018-03-10) © 2009 Michael Stapelberg and contributors
(Getting version from running i3, press ctrl-c to abort…)
Running i3 version: 4.15 (2018-03-10) (pid 958)
Loaded i3 config: /home/soumya/.config/i3/config (Last modified: Sat 29 Sep 2018 12:34:38 PDT, 1502413 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
- Linux Distribution & Version: ArchLinux
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

**Comment by Airblader** [comment]
Would be fine by me.

**Comment by soumya92** [comment]
Great! I think this might be somewhat straightforward, so I'll try to get you a PR sometime.
