### ISSUE TITLE
i3bar incorrectly renders applets

### ISSUE THREAD

**Issue by crushv** [i3/i3#3463]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

i3bar displays applets wrong:
* Nearby applets merge images (ex: nm-applet is drawn over keepassxc)
* Applets cover the clock on start
* Applets do not have a transparent background
* Applets have general visual glitches/noise
![screenshot from 2018-10-14 22-32-04](https://user-images.githubusercontent.com/42139900/47189040-4e2f8d00-d300-11e8-9319-7d606029a93f.png)
![image](https://user-images.githubusercontent.com/42139900/47189058-60113000-d300-11e8-9892-c85dc9a99b5c.png)
![image](https://user-images.githubusercontent.com/42139900/47189074-6dc6b580-d300-11e8-8daf-58c5397363d5.png)

## Expected Behavior

Normal drawing of applets.

## Reproduction Instructions
Setup Arch Linux with i3, lightdm and default configuration.
Start a few applications that have applets and observe the rendering issues.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.15.0.1 (03-13-2018) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15.0.1 (03-13-2018) (pid 1030)ort…)
Loaded i3 config: /home/nik/.config/i3/config (Last modified: Thu 18 Oct 2018 05:59:19 PM CDT, 158 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
set $mod Mod4

font pango:DejaVu Sans Mono 8

# Set key repeat rate
exec xset r rate 150 35
# light-locker daemon
exec --no-startup-id light-locker --no-lock-on-suspend
# lock binding
bindsym $mod+l exec light-locker-command -l
bindsym XF86PowerOff exec light-locker-command -l

# hide_edge_borders both
new_window normal 0

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec termite

# kill focused window
bindsym $mod+Shift+q kill

# start dmenu (a program launcher)
bindsym $mod+d exec --no-startup-id rofi -show drun
bindsym $mod+Shift+d exec --no-startup-id rofi -show run
bindsym $mod+Shift+s exec --no-startup-id rofi -show ssh

# change focus
bindsym $mod+j focus left
bindsym $mod+k focus down
#bindsym $mod+l focus up
bindsym $mod+semicolon focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+semicolon move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
# bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
# bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

# switch to workspace
bindsym $mod+1 workspace 1
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9
bindsym $mod+0 workspace 10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace 1
bindsym $mod+Shift+2 move container to workspace 2
bindsym $mod+Shift+3 move container to workspace 3
bindsym $mod+Shift+4 move container to workspace 4
bindsym $mod+Shift+5 move container to workspace 5
bindsym $mod+Shift+6 move container to workspace 6
bindsym $mod+Shift+7 move container to workspace 7
bindsym $mod+Shift+8 move container to workspace 8
bindsym $mod+Shift+9 move container to workspace 9
bindsym $mod+Shift+0 move container to workspace 10

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
# bindsym $mod+Shift+e exec i3-msg exit

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym semicolon resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape
        bindsym Return mode "default"
        bindsym Escape mode "default"
}

bindsym $mod+r mode "resize"

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        status_command i3blocks
        position bottom
        colors {
                background #000000
                statusline #ffffff
                separator #666666
        }
        verbose yes
}

</pre>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5633851275608064.bz2
i3bar log: https://github.com/i3/i3/files/2493842/i3bar.bar-0.log
</pre>

<pre>
- Linux Distribution & Version: Arch Linux
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by orestisf1993** [comment]
See https://github.com/i3/i3/issues/3335#issuecomment-419815719
