### ISSUE TITLE
Tiny issue with the documentation

### ISSUE THREAD

**Issue by Hibou57** [i3/i3#3464]
## I'm submitting a…

<pre>
[ ] Bug
[ ] Feature Request
[x] Documentation Request
[ ] Other (Please describe in detail)
</pre>

There is a misleading wording in the documentation. The page https://i3wm.org/docs/userguide.html says:

> You can then use the i3-msg application to perform any command listed in the next section.

It says so from section 4, and the commands are in section 6. The section next to 4 is 5, which is about configuring and there is a big amount of text from this one to the other.

I would suggest to either change “in the next section” into “in a next section” or into “in section 6” or “in the section named 'List of commands' ”.

**Comment by Airblader** [comment]
We can just create an anchor and link directly to it :)
