### ISSUE TITLE
Export $I3SOCK

### ISSUE THREAD

**Issue by xzfc** [i3/i3#3476]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Currently there are two ways to get the socket path:

1. Calling `i3 --get-socketpath`. On my system it takes up to 28ms and it is noticeable for instant actions like switching windows, etc. I suppose the slowdown is caused by large number of dynamic libraries used by `i3` binary.
2. Retrieving `I3_SOCKET_PATH` atom. It is fast enough, but implies code complexity for IPC clients: requires a lot of code and using external dependencies like bindings to libxcb or other X11 protocol implementation.

## Desired Behavior

I propose exporting `I3SOCK` environment variable to apps executed by i3. Retrieving the environment variable is simple and is not time-consuming.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
$ i3 --moreversion
Binary i3 version:  4.15 (2018-03-10) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15 (2018-03-10) (pid 1073)o abort…)
Loaded i3 config: /home/alice/.config/i3/config (Last modified: Tue 23 Oct 2018 23:58:01 +07, 4519 seconds ago)

The i3 binary you just called: /nix/store/pmz1bsqczf9fzj9q4qp2bbpn343sblby-i3-4.15/bin/i3
The i3 binary you are running: /nix/store/pmz1bsqczf9fzj9q4qp2bbpn343sblby-i3-4.15/bin/i3
</pre>

<pre>
- Linux Distribution & Version: NixOS unstable
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by Airblader** [comment]
I don't see a reason against this, so yeah, this would be fine with me.

**Comment by acrisci** [comment]
Another good solution for this might be to encode the `DISPLAY` into the socket path, so I could read it in my script and look for `/run/user/1000/i3/ipc-socket.[PID]-[DISPLAY]`.

**Comment by xzfc** [comment]
@acrisci It's not reliable location, the socket may be in `$XDG_RUNTIME_DIR/i3/`, or in `/tmp/`, or the path can be specified in i3 config or by environment variable.

However I like how your solution (unlike mine) don't introduce interfering with `$I3SOCK` of the current i3 session. E.g. command to send message to another i3 instance is `DISPLAY=:1 i3-msg '...'` instead of `unset I3SOCK; DISPLAY=:1 i3-msg '...'`.

**Comment by Airblader** [comment]
I think we can do both, ultimately, but they're separate ideas.
