### ISSUE TITLE
Investigate whether trailing comma can be allowed in JSON

### ISSUE THREAD

**Issue by Airblader** [i3/i3#3498]
## I'm submitting a…

<pre>
[ ] Bug
[X] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Currently, when loading a layout file, the last key of an object must not have a trailing comma. 

## Expected Behavior

Ideally, this would be allowed, as users frequently run into this issue and it's unnecessarily strict. We should check if the json parser can be configured to be a bit more tolerant here. If so, let's enable that option. I haven't looked at this at all yet. 

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: i3 4.15
</pre>

<pre>
</pre>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version:
- Are you using a compositor (e.g., xcompmgr or compton):
</pre>

**Comment by orestisf1993** [comment]
yajl doesn't seem to support this. Possible solutions:

- Detect the error while parsing, get the error position, delete the comma there and retry (hacky)
- Use a fork of yajl that corrects this, eg https://github.com/eldenchen/yajl. We would have to add it as a submodule.
- Change JSON library (overkill)

**Comment by Airblader** [comment]
I definitely don't like the hacky solution :-) I wouldn't be opposed to switching to a different library of we have such benefits, though there's some things we'd need to make sure of first (such as support for comments and multiple top-level documents). I'm not sure what alternatives there are, though I can't imagine there aren't any. 

The yajl project, unfortunately, seems abandoned despite @lloyd being active on Github still. So perhaps it's reasonable to switch to a maintained project.

**Comment by Airblader** [comment]
Having done some more digging it seems this isn't currently viable. It'd be nice if yajl (optimally) supported trailing commas, but it doesn't, so I guess nothing we can do here for now.
