### ISSUE TITLE
Improved focus handling (problem with notifications stealing focus)

### ISSUE THREAD

**Issue by JanKaifer** [i3/i3#3507]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
When KDE throws a  new notification (small floating window)t automatically gets focus and mouse moves in the middle of notification. And then when notification disappears the mouse changes window and focus stays on th window that is under notification.

## Desired Behavior
I would like some way to prevent i3 from giving focus to notificatins.

## Environment
Output of `i3 --moreversion 2>&-`:
Binary i3 version:  4.15.0.1 (03-13-2018) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15.0.1 (03-13-2018) (pid 779)bort…)
Loaded i3 config: /home/pearman/.config/i3/config (Last modified: Tue 06 Nov 2018 10:44:20 PM CET, 837 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

<pre>
i3 version: 4.15.0.1 (03-13-2018)
</pre>

<pre>
- Linux Distribution & Version: Archlinux - up-to-date
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

**Comment by orestisf1993** [comment]
i3 does not give focus to windows that specify the appropriate hints: https://tronche.com/gui/x/icccm/sec-4.html#s-4.1.7.

If KDE doesn't use the correct hints you would have to use the `no_focus` config directive: https://i3wm.org/docs/userguide.html#no_focus
You might be affected by https://github.com/i3/i3/issues/3423 though, so update to 4.16

**Comment by daviddavo** [comment]
I'm having the exact same problem, but with a multi-screen setup.
If the mouse is on another screen, the notification will appear on the primary screen, but the mouse will be moved to the primary screen as well.

If the mouse is on the primary screen, the notification doesn't steal the focus. I have the following directive in my config

`for_window [class="plasmashell" window_type="notification"] floating enable; border none; no_focus`

My i3 version is
```
i3 --moreversion 2>&-
Binary i3 version:  4.18.1 (2020-04-23) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18.1 (2020-04-23) (pid 1535)abort…)
Loaded i3 config: /home/davo/.config/i3/config (Last modified: lun 04 may 2020 11:20:37, 235 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: /usr/bin/i3
```

xprop gives me the following poperties:
```
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
I3_FLOATING_WINDOW(CARDINAL) = 1
_NET_WM_USER_TIME(CARDINAL) = 745433470
_KDE_NET_WM_SHADOW(CARDINAL) = 37749008, 37749009, 37749010, 37749011, 37749012, 37749013, 37749014, 3774015, 10, 10, 10, 10
_KDE_NET_WM_BLUR_BEHIND_REGION(CARDINAL) = 0, 0, 370, 83
_NET_WM_DESKTOP(CARDINAL) = 4294967295
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_SKIP_PAGER, _NET_WM_STATE_FOCUSED
_KDE_NET_WM_DESKTOP_FILE(UTF8_STRING) = "org.kde.plasmashell"
XdndAware(ATOM) = BITMAP
WM_NAME(STRING) = 
_NET_WM_NAME(UTF8_STRING) = "Plasma"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x1, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NOTIFICATION, _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _NET_WM_WNDOW_TYPE_NORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x240000d
WM_HINTS(WM_HINTS):
                Client accepts input or input focus: False
                window id # of group leader: 0x240000d
WM_CLIENT_MACHINE(STRING) = "manjaro"
_NET_WM_PID(CARDINAL) = 1546
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 37750520
WM_CLASS(STRING) = "plasmashell", "plasmashell"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                user specified location: 1510, 1695
                user specified size: 370 by 83
                window gravity: Static
```

**Comment by orestisfl** [comment]
@daviddavo  This is https://github.com/i3/i3/issues/3979
