### ISSUE TITLE
Add ppt support to move position (similar to resize)

### ISSUE THREAD

**Issue by shazow** [i3/i3#3519]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Right now, the move syntax only supports px:

```
move <left|right|down|up> [<px> px]
move position <pos_x> [px] <pos_y> [px]
```

## Desired Behavior

`resize` learned to use `ppt` to support percentage values here: https://github.com/i3/i3/pull/3023

It would be useful (and also more consistent) to support ppt (percentage-based) measures for `move`.

Example use case: I'm trying to top-middle align a window to take up 80% of the screen width.

`resize set 80 ppt 40 ppt` works great, but would be nice if `move absolute position 10 ppt 0 ppt` also worked (move 10% from the left).

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.16 (2018-11-04) 
</pre>

<pre>
- Linux Distribution & Version: Arch Linux
- Are you using a compositor (e.g., xcompmgr or compton): No.
</pre>

**Comment by Airblader** [comment]
Off the top of my head I don't see a good reason not to support this.

**Comment by acheronfail** [comment]
Hey @Airblader, I'd also like this feature, and I'm happy to try and make a PR for it too. :slightly_smiling_face: 

I've looked through the code, and it looks like we'd need to add `ppt` support in these two places:

* https://github.com/i3/i3/blob/f33a49372ff4ea0d8d51ba2a3b3296db52c901fb/src/commands.c#L1498
* https://github.com/i3/i3/blob/f33a49372ff4ea0d8d51ba2a3b3296db52c901fb/src/commands.c#L1729

After having a look, I'm still not entirely sure about a couple things, for example: where are these functions called? I can't see any references to them elsewhere in the codebase...

If you could throw a couple pointers to me I'd be happy to give this a crack.

**Comment by Airblader** [comment]
> After having a look, I'm still not entirely sure about a couple things, for example: where are these functions called?

The calls to them are generated from the parser configuration, so you need to also extend `parser-specs/commands.spec`. A good template would be to find any PR that introduced a new command to see the kind of changes made there.

If you have further questions I'll tap in @orestisfl from here as I'm a bit on a break. :-)

**Comment by acheronfail** [comment]
No worries, that was all the information I needed, I've opened a PR at #4189 and we can continue the discussion there if required.

Enjoy your break!
