### ISSUE TITLE
sort i3bar workspaces alphabetically

### ISSUE THREAD

**Issue by bartman** [i3/i3#3548]
## I'm submitting a…
<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
I use workspaces dynamically, based on project I'm working on. Say, I'm working for project "foo", I will have workspaces: foo-1, foo-2, foo-3, etc devoted for this project.  I tend to have about 30 workspaces open at any time.

Creating a new workspace always puts it the new one at the end of the list in i3bar.  I want the "foo" workspaces to be near one another, and sequential.

## Desired Behavior
I want the workspaces to be ordered alphabetically in i3bar.

Setting a workspace number explicitly, does not work well in my use case.  I used to set the numbers to force sorting using helper script, but it's rather slow.

A small hack to i3bar (see below) works much better.

## Environment
I'm running i3 on debian/testing (4.16), but this problem exists in master and next branches also.
Please include your exact i3 version.
</pre>

## Proposed Fix
I have hacked on i3bar to implement this feature [in my fork](https://github.com/bartman/i3/tree/bart/i3bar-hacks)...
https://github.com/bartman/i3/commit/cc1d8fdf99be8cf50c05c35502e0b3bd5429a4c6

After adding the following to `~/.i3/config`, I get the behaviour I want.

<pre>
bar {
    sort_workspace_by_name yes
}
</pre>

Note that the default behavior is "no" and i3bar behaves as before.

**Comment by Airblader** [comment]
You can prefix the workspace names with a number and a colon (`1:foo`), then they are sorted by that number. If you don't want to display that number, add strip_workspace_numbers (see userguide).

That's the mechanism intended to achieve a specific order, so you can also use that to do it alphabetically by numbering accordingly.

**Comment by Airblader** [comment]
Maybe just to address it more specifically: I don't think we want to add sorting options because that's very opionated and people are going to want all kinds of sorting. We currently have a generic mechanism that is flexible to achieve any sorting you want and I don't see a good reason not to use that approach.

If your helper script was/is too slow, I think it should be improved to not be slow. Since the IPC commands are the same thing i3 uses in many places I don't think it's just generically too slow.

**Comment by bartman** [comment]
The slowness comes from having to renumber existing workspaces when one is inserted in the middle.  Not so much the mechanism of informing i3 to assign the prefix -- which was never an issue, because a name must be assigned anyway.

I don't like the solution, but I understand your position.  I can deal with the restrictions, although it's not ideal for my purpose.

**Comment by Airblader** [comment]
A little trick coming to mind would be not using consecutive numbers but adding some "padding", so numbering them 0, 100, 200, ... and inserting a new one in the middle between two neighbors. This will of course eventually require updating more than one, but make it a more rare event.

That said, I think even renaming multiple workspaces shouldn't be a big problem. I would think the slowness comes from the fact that you opened a new IPC connection with every command (if I had to guess).
