### ISSUE TITLE
MINOR: Syntax error? (i3status, load)

### ISSUE THREAD

**Issue by Kreyren** [i3/i3#3552]
## I'm submitting a…

<pre>
[X] Bug
[ ] Feature Request
[X] Documentation Request
[ ] Other (Please describe in detail)
</pre>

In https://i3wm.org/i3status/manpage.html under Configuration there is mensioned:

```
load {
    format = "[ load: %1min, %5min, %15min ]"
}
```

Which results in `Error: status_command process exited unexpectedly (exit1)`

Seems to work with:

```
load {
        format = "%1min, %5min, %15min"
}
```

*Removed the rest since it seem irelevant*

**Comment by Airblader** [comment]
Thanks for filing this issue; however, the i3/i3 repository is for the window manager and i3bar, so the correct repository for this would be i3/i3status. Would you mind filing this issue again over there? Thank you!
