### ISSUE TITLE
add duration option to i3-nagbar

### ISSUE THREAD

**Issue by msudgh** [i3/i3#3561]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

The navigation after showing is fixed and will never be hidden.
## Desired Behavior

It'd be better to have a `duration` option to close the navigation after the configured amount.

**Comment by orestisf1993** [comment]
You can kill the spawned process with a simple shell script: `i3-nagbar & sleep 1 && kill %1` or `i3-nagbar & sleep 1 && kill $(jobs -p)`
