### ISSUE TITLE
Missing IPC window::focus event when switching focus from an empty workspace

### ISSUE THREAD

**Issue by KJoke70** [i3/i3#3562]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Sometimes when switching focus from an empty workspace to a container, no `window::focus` event is sent.

## Expected Behavior

i3 sends a `window::focus` event whenever a window is focused.

## Reproduction Instructions

I have noticed 2 ways to reproduce this. To see the events being sent, I start this script beforehand:

```
#!/usr/bin/env python3

import i3ipc

def on_workspace_focus(a, b):
    print("workspace::focus: name->%s" % (b.current.name))

def on_window_focus(a, b):
    print("window::focus: name->%s, floating->%s, scratchpad->%s" %
                                                    (b.container.name,
                                                     b.container.floating,
                                                     b.container.scratchpad_state))

i3 = i3ipc.Connection()
try:
    i3.on("window::focus", on_window_focus)
    i3.on("workspace::focus", on_workspace_focus)
    i3.main()
finally:
    i3.main_quit()
```

#### 1. Requires at least two displays:
Open a terminal on display 1 and execute the above script. Focus to the empty workspace on display 2. Then focus back to display 1. No `window::focus` is being sent, despite the terminal being in focus now. If both workspaces contain windows, `window::focus` is sent on focus change.

#### 2. Open a terminal, and run the above script. Then open a second terminal and run this script:
```
#!/bin/bash
  i3-msg workspace 111 &&
  i3-msg "exec urxvt -name test -title test" &&
  sleep 1 &&
  i3-msg "[instance='test'] floating enable; move scratchpad" &&
  sleep 1 &&
  i3-msg [instance="test"] scratchpad show &&
  sleep 1 &&
  i3-msg [instance="test"] scratchpad show &&
  sleep 1 &&
  i3-msg [instance="test"] kill &&
```
No `window::focus` was being sent, when the scratchpad window becomes visible.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.16 (2018-11-04) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16 (2018-11-04) (pid 709)to abort…)
Loaded i3 config: /home/martin/.config/i3/config (Last modified: Fri 14 Dec 2018 11:19:06 AM CET, 6171 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
Config: default config with Alt as $mod.
</pre>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5648879299067904.bz2
</pre>

<pre>
- Linux Distribution & Version: Arch, 4.19.8-arch1-1-ARCH
- Are you using a compositor (e.g., xcompmgr or compton): None
</pre>

**Comment by orestisf1993** [comment]
Can you explain the second case? You should receive a single focus event when the scratchpad is shown. Doesn't this happen?

**Comment by KJoke70** [comment]
In the second case

* Go to empty workspace 111 -> `workspace::focus`
* I open urxvt -> `window::focus`
* Make it float and move it to scratchpad -> `workspace::focus`
* Show the scratchpad terminal with `scratchpad show` -> *nothing*
* Hide the scratchpad terminal with `scratchpad show` -> `workspace::focus`

When moving the terminal from the internal workspace to the current one and focusing it there should be `window::focus`.
