### ISSUE TITLE
i3 brings CPU usage to 100% for i3 and xorg when adding two screens.

### ISSUE THREAD

**Issue by drPytho** [i3/i3#3571]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

I start my computer (Laptop dell xps 15) on my single screen, with no issues. 
```xinit
setxkbmap se
exec i3 --shmlog-size=26214400
exec /home/drpytho/.config/i3/init
```

Then I add my two external screens that I have at work with the following script.
```
#!/bin/sh
xrandr --output VIRTUAL1 --off --output DP3 --mode 1920x1080 --pos 3640x0 --rotate left --output DP1 --mode 1920x1080 --pos 0x0 --rotate right --output eDP1 --primary --mode 2560x1440 --pos 1080x480 --rotate normal --output DP2 --off
```

My CPU usage then instantly spikes to 100%cpu for both i3 and xorg.
> PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
> 12877 drpytho   20   0   85304  38872  37324 R 100.0   0.1   3:45.74 i3
> 12867 drpytho   20   0  832740 159208 147408 R  95.0   0.5   3:35.93 Xorg

## Expected Behavior

I don't want the CPU to go ti 100%

## Reproduction Instructions

Doing what is above. Also when I run 
`xrandr --output VIRTUAL1 --off --output DP3 --off --output DP1 --off --output eDP1 --primary --mode 2560x1440 --pos 0x0 --rotate normal --output DP2 --off`
Which just scales my current screen the same thing happens.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
Binary i3 version:  4.16 (2018-11-04) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16 (2018-11-04) (pid 12877) abort…)
Loaded i3 config: /home/drpytho/.config/i3/config (Last modified: Wed 26 Dec 2018 01:44:14 PM CET, 869 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

This is pretty much the standard config. 
https://pastebin.com/h0wrHxc1

<pre>
Logfile URL:
https://logs.i3wm.org/logs/5750762164453376.bz2
</pre>

<pre>
- Linux Distribution & Version:
Linux  4.19.12-arch1-1-ARCH #1 SMP PREEMPT Fri Dec 21 13:56:54 UTC 2018 x86_64 GNU/Linux

- Are you using a compositor (e.g., xcompmgr or compton):
Don't think so. 
</pre>

**Comment by drPytho** [comment]
Is there something else I should add to make a more compleate Issue report?

**Comment by orestisf1993** [comment]
From your log file, a window is sending thousands of configure requests. Is there anything else you start with i3, eg in your xinitrc?

**Comment by drPytho** [comment]
.xinitrc
<pre>
setxkbmap se
exec i3 --shmlog-size=26214400
</pre>
Nothing else really getts run.

**Comment by orestisf1993** [comment]
Can you please upload a log file from a very short session? The one in the original post doesn't include the start of the session. Just append `exec "sleep 0.5s && i3-msg exit"` to your config.

**Comment by drPytho** [comment]
```
setxkbmap se 
exec i3 --shmlog-size=26214400
exec "sleep 0.5s && i3-msg exit"
```

https://logs.i3wm.org/logs/5735221261500416.bz2

**Comment by drPytho** [comment]
```
setxkbmap se 
exec i3 --shmlog-size=26214400
exec "sleep 0.5s && i3-msg exit"
```

https://logs.i3wm.org/logs/5735221261500416.bz2

**Comment by drPytho** [comment]
This should be a bit better. I got from the beginning to all the notify Config.
https://logs.i3wm.org/logs/5096140429066240.bz2

**Comment by orestisf1993** [comment]
Thanks, can you try with a terminal other than Alacritty?

**Comment by drPytho** [comment]
Hmm, seems like the CPU does not hit the roof when I don't change the screens from Alacritty...
https://logs.i3wm.org/logs/5753530203766784.bz2

**Comment by 0ax1** [comment]
Same issue here when using Alacritty.

**Comment by orestisf1993** [comment]
https://github.com/jwilm/alacritty/issues/1790

**Comment by orestisf1993** [comment]
Alacritty issue marked as solved so I am closing this one as well
