### ISSUE TITLE
Provide default keybinding for "move workspace to output right"

### ISSUE THREAD

**Issue by vog** [i3/i3#3583]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

A freshly installed i3 provides many useful keybindings, but none for

* move workspace to output right

Not having this in a multi monitor setup is very limiting. This problem is so common that it even has an old entry in the FAQ: https://faq.i3wm.org/question/591/move-workspace-to-other-monitor.1.html

## Desired Behavior

Instead of forcing every new user to edit their i3/config just for "move workspace to output right", there should be a binding in the default configuration.

To minimize confusion, I propose to not use any of the bindings mentioned in https://i3wm.org/docs/userguide.html, which means it should be one of the following:

* $mod+i
* $mod+q
* $mod+z

I'd prefer $mod+z, but that's that's a minor point. The important point is to have this very useful and widely used functionality in the default config.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.16 (2018-11-04) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16 (2018-11-04) (pid xxxxx)o abort…)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
- Linux Distribution & Version: Debian GNU/Linux buster/sid
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by Airblader** [comment]
So why should the be one for `move output right`, but not any of the other directions?

> Not having this in a multi monitor setup is very limiting.

Which is why you can change your config :-)

> This problem is so common that it even has an old entry in the FAQ: https://faq.i3wm.org/question/591/move-workspace-to-other-monitor.1.html

I'd rather view this as »there's one entry from many years ago«. This issue has not frequently appeared on other support channels in the recent past in my experience.

---

In general we're very cautious about adding anything to the default config. I'd rather have people familarize themselves with their options and adjusting it to their needs. The default config mostly serves so that it's possible to work on a new install out of the box, not to provide defaults for every kind of situation, so I'm inclined to close this issue.

**Comment by vog** [comment]
Please note that this proposal is just about sensible defaults.

We should provide a default keybinding for "move workspace to output right" for the same reason we have a default keybinding for moving a window to another workspace.

Of course a user should learn the config settings if they want to shape i3 to their needs. However, they shouldn't be forced to do so for basic functionality. And on a multi-monitor setup, moving a workspace from one display to the next is a pretty basic action. Without it, things become cumbersome quickly.

Regarding the direction, it is easier to agree on a keybinding for a single action "move workspace to output right" than for a whole set of actions ""move workspace to output X". I don't really care it it's left or right, I just picked one.

**Comment by Airblader** [comment]
> We should provide a default keybinding for "move workspace to output right" for the same reason we have a default keybinding for moving a window to another workspace.

Moving a window to another workspace is aj extremely common action, but moving entire workspaces across outputs is much less common and important. I don't think this argument applies here. 

The danger with adding bindings to the default config is that for new users, this "uses up" this combination for other things, and users can be reluctant to remove default bindings in the beginning. 

Ultimately the two questions we should ask are 

1. Is the action very common among a wide fraction of users? 
2. Is there a binding for it that is natural and intuitive? 

I would aggie that even 1. isn't fulfilled, but even when for the sake of the argument we say that it is, none of the proposed bindings feel intuitive and natural.

I appreciate you opening this issue, but I think ultimately the need for this just isn't there.
