### ISSUE TITLE
$mod+Shift+q stopped working

### ISSUE THREAD

**Issue by serussell** [i3/i3#3596]
## I'm submitting a…
<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

$mod+Shift+Q has stopped working.  **Only** $mod+Shift+Q has stopped working.  It was working until yesterday, and I'm not aware of anything that's changed (no i3 upgrade, no new applications running that might be grabbing the key), but of course I can't rule that entirely out.  

If I remap kill to, say, $mod+Shift+X, then it works.  If I map $mod+Shift+Q to something like "exec /usr/bin/termite", then it also does not work.  $mod+Shift+R does work, as do all other $mod+Shift combos I've tried, so I'm pretty sure this is unrelated to #2418 or #2417.

I have a dump from `xdotool key "XF86LogGrabInfo"`, but to be honest I'm not sure how to interpret the output to find what's listening for $mod+Shift+Q.  I've remapped caps lock to Super_L and set mod4 to that.

Interestingly, xev shows no output on the `q` press of $mod+Shift+q.  I get the mod, and the shift, but denada for q.  I've never seen that before.  It *does* register `c` in $mod+Shift+c, but i3 doesn't reload the config so I don't know what's going on there; probably unrelated.

Oh, and, yes, the `q` key works fine everywhere else.

## Expected Behavior

I'd expect i3 to be able to capture and respond to `$mod+Shift+q`.

## Reproduction Instructions

See above -- I haven't changed anything; I run i3, and `$mod+Shift+q` doesn't work.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.16 (2018-11-04) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16 (2018-11-04) (pid 879)to abort…)
Loaded i3 config: /home/ser/.i3/config (Last modified: Sat 19 Jan 2019 09:52:01 AM CST, 933 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

* [xdotool output](https://pastebin.com/xyqJnVmW)
* [config](https://pastebin.com/zK0pQByW)

<pre>
                   -`                    ser@sting
                  .o+`                   ---------
                 `ooo/                   OS: Arch Linux x86_64
                `+oooo:                  Host: XPS 13 9343
               `+oooooo:                 Kernel: 4.20.0-arch1-1-ARCH
               -+oooooo+:                Uptime: 48 mins
             `/:-:++oooo+:               Packages: 2310 (pacman)
            `/++++/+++++++:              Shell: zsh 5.6.2
           `/++++++++++++++:             Resolution: 1920x1080
          `/+++ooooooooooooo/`           WM: i3
         ./ooosssso++osssssso+`          Theme: GnomishDark [GTK2/3]
        .oossssso-````/ossssss+`         Icons: AwOken [GTK2], Potenza-Dark [GTK3]
       -osssssso.      :ssssssso.        Terminal: tmux
      :osssssss/        osssso+++.       CPU: Intel i5-5200U (4) @ 2.700GHz
     /ossssssss/        +ssssooo/-       GPU: Intel HD Graphics 5500
   `/ossssso+/:-        -:/+osssso+-     Memory: 1769MiB / 7880MiB
  `+sso+:-`                 `.-/+oso:
 `++:.                           `-/+/
 .`                                 `/
</pre>

I do use a composer, but I've killed it during submission of this bug because frequent restarts of i3 was causing it to freak a bit out.

**Comment by serussell** [comment]
I didn't, bot; the instructions said the logs were optional, and I wasn't sure whether -- since xev wasn't even registering the `q`, it would be useful.

**Comment by orestisf1993** [comment]
Still having this issue? If yes, can you upload the i3 log file?

**Comment by serussell** [comment]
I'm going to close this; I don't think it's an i3 issue.  It has something to do with the combination of me using dvorak and remapping caps lock to mod.  Something in there is screwing up the Q; or it's some applet I'm running.  Anyway, it's not i3's fault.

**Any** hints on how I might go about debugging this would be appreciated.  Is there anything that's easier than shutting down all applets & undoing my keymap, and then re-enabling everything one-by-one until I find the culprit?  Are there any tools to help make this sort of investigation easier?

You know what's _really_ weird?  xev doesn't even register mod+shift+q.  Something is hijacking it before it gets to xev.
