### ISSUE TITLE
if dmenu or j4-dmenu-desktop doesnt fit the string or the command just keep the string that fit and ignore wrong keys

### ISSUE THREAD

**Issue by enricoT** [i3/i3#3615]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
</pre>

<pre>
- Linux Distribution & Version:
- Are you using a compositor (e.g., xcompmgr or compton):
</pre>

**Comment by enricoT** [comment]
j4-dmenu-desktop
for example tel show telegram
if i type  telè just keep tel for telegram and discard the symbol not found

**Comment by orestisf1993** [comment]
i3 doesn't ship dmenu or j4-dmenu
