### ISSUE TITLE
Hide titlebars in tabbed and stacking modes.

### ISSUE THREAD

**Issue by david-tamar** [i3/i3#3617]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Tabbed and stacked modes are always showing window titlebars despite the configuration for floating or windowed modes. 

I'm using a docked panel (xfce-panel) which already shows me the information I need about the window I'm currently focusing on, therefore the window titlebars are merely **duplicate information** that takes up space and my monitor is merely 12.5" inch, I don't want any titlebars.

This is related: The titlebar uses the window border color as its background color. Since I'm using a plain white, bright theme, I use a solid black color for the borders to contrast the theme, but then the window titlebars appear in black as well, which makes them look completely out of sync with the rest of the bright theme and thus I wish to hide them completely for that reason too. 

## Desired Behavior

Tabbed and stacked modes don't show window titlebars while allowing the user to cycle between the windows in horizontal (tab mode) or vertical (stacking mode) fashions respectively.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.16.1
</pre>

<pre>
- Linux Distribution & Version: Debian 10 (Buster)
- Are you using a compositor (e.g., xcompmgr or compton): No.
</pre>

**Comment by orestisf1993** [comment]
#2664, #2734, #2735

**Comment by david-tamar** [comment]
I've already read these threads and they keep ignoring the fact that on a 12.5" Thinkpad I always maximize all windows and I don't need to distinguish between layouts because I don't really tile anything, I just maximize and cycle through the windows, I don't need a titlebars nor tabs. Stacking mode is completely unusable because if you have 5 windows with 12pt font under 176 DPI then you get about a quarter of your screen filled with useless titlebars.

**Comment by Airblader** [comment]
If you have seen those issues, it would be good if you mentioned your research and pointed out *specifically* why you believe the current reasoning for rejection does not consider the entire picture. If you just raise the same feature request, it will be of course be rejected for the same reasons.

It would also be good to either link issues together (for context) or just comment on the existing issues so we can avoid the clutter of spreading one discussion over many different issues.

> I always maximize all windows and I don't need to distinguish between layouts because I don't really tile anything

i3 has no "maximize" so I assume you mean fullscreen. In this case I wonder why you don't just put each window on its own workspace instead of using a stacked container?

**Comment by david-tamar** [comment]
>  i3 has no "maximize" so I assume you mean fullscreen. 

Nope, I use "fullscreen" only rarely with programs like VLC, or while watching videos on YouTube with Firefox (i.e. F11-like window behavior that hides everything else, including the desktop panel). That's not what I meant by saying "maximized".

Speaking of i3wm, I'd describe modes like "tabbed" and "stacked" to be equivalent to "maximized" in mainstream WMs, because each new opened window is being immediately stretched all across the dedicated space for rendering windows (but not over desktop panels), switching between floating and tabbed modes is almost the same as maximizing and restoring windows in normal non-tiling window managers, and that's what I meant by "maximizing" windows.

>  In this case I wonder why you don't just put each window on its own workspace instead of using a stacked container?

Because I use workspaces to group different tasks that I carry on with simultaneously, and I have only 10 workspaces available while I sometimes cycle more than just 10 windows.

**Comment by Airblader** [comment]
I see. Did you consider using a tabbed container rather than a stacked one? You do still get a titlebar, but only one for all windows, not one each. With a lot of windows you won't be able to read the titles, but since you actually don't want to see them anyway that shouldn't matter.

**Comment by david-tamar** [comment]
>  I see. Did you consider using a tabbed container rather than a stacked one? You do still get a titlebar, but only one for all windows, not one each. With a lot of windows you won't be able to read the titles, but since you actually don't want to see them anyway that shouldn't matter.

**I always use the tabbed container.** 

I still try to put my efforts to find a middle ground with either you, or with one of Topmenu's or Appmenu's maintainers so one of you will eventually allow me to hide the duplicate information about the application names that shown all over my 12.5" screen.

**Comment by Airblader** [comment]
I see. My problem here is that we want to ensure visual clarity from i3, and from our perspecctive the titlebar for tabbed and stacked containers is essential to give visual clues about the tree structure (this is far more information than just a title), and of course it's part of our look&feel.

While I understand your needs, I don't think we want to deviate from it still. You could of course consider patching i3 locally (probably all you need to do is change where `deco_height` is assigned in `src/render.c`), another option is to define a font size of zero for i3 (and possibly `title_format ""` for all windows), which would reduce the titlebar to currently 4px.

**Comment by JSamir** [comment]
Honestly, it makes zero sense to reject this. If you are that much concerned why not just leave the default as it is and create a new option for users who want this feature?

You not implementing this is not the end of the world. But honestly I am shocked that for an app that I associate so much with customizing and creating my own experience, the maintainers refuse to implement a feature that 1) people want and 2) lets users further customize their i3.

**Comment by Airblader** [comment]
i3 has never aimed to make a window manager as configurable as possible, I think you might be confusing that with others like awesome.

As for the why not make it optional, we always try to weigh benefit versus cost. You can read an answer on this topic here: https://faq.i3wm.org/question/778/why-is-patch-not-merged-and-made-optional/index.html

**Comment by JSamir** [comment]
I understand that, I develop software myself. If implementing this option has the negative consequences as described in the link, then it makes sense that you need to draw a line somewhere.

I am not familiar with this project at code level, but I was assuming that implementing this would not cause (all/many) of the problems as described.

Fair enough :)

Still many thanks for this wonderful piece of software!
