### ISSUE TITLE
i3 forks and distro packaging

### ISSUE THREAD

**Issue by kgilmer** [i3/i3#3633]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
i3-gaps is a popular variant of the i3 window manager.  There are some programs such as i3blocks which provide some additional functionality to i3.  In distro packaging metadata, these packages refer to i3 as a dependency.  Because i3-gaps (and presumably other forks) are not named, there seems to be no "official" way of allowing a dependency on a fork at the distro package level.  If I install i3-gaps from sources, and then try to install i3blocks via a package, it will fail or attempt to install the non-gaps variant of i3.  This is because my compiled i3-gaps has files that conflict with the packaged version.  Additionally, if I want to create a program for i3wm, I must also hardcode the dependency on the root variant, disallowing forks such as i3-gaps from being install-able (via a distro packaging system).  As-is, each i3-dependent program must create separate packages for every fork/variant of i3 they wish to support.

## Desired Behavior
Programs for i3wm should be able to express the dependency on i3 in such a way that the end-user can install a variant such as i3-gaps and have it "just work".

I am not an expert on distro packaging systems.  The way I could see this working (I have not tried it) is that a "virtual" i3wm package is created in which the root i3wm and variants can supply their own concrete packages as desired.  I believe vim in Ubuntu is configured in this way.

I can see the obvious reply to this issue as being "not our problem, talk to your package maintainer" and I don't disagree with that.  On the other hand, I hold the opinion that distro packaging systems are generally good for users and software systems that integrate well with these packaging systems will have more users.

 I'm also creating this issue to see if there is another way of solving this problem that doesn't occur to me.

Thanks for your attention.

## Environment
N/A

**Comment by Airblader** [comment]
Hi,

This is indeed purely a packaging concern and will depend on the distro / package manager. For example on Arch (pacman) a package can "provide" something and dependencies can depend on that rather than a package, so on Arch this usecase works just fine. 

I'm afraid you'll need to discuss this with people from your distro / package manager if there is no such mechanism. Thanks!
