### ISSUE TITLE
Focus can briefly change when a workspace is renamed

### ISSUE THREAD

**Issue by anowlcalledjosh** [i3/i3#3635]
(originally reported at Airblader/i3#283)

## I'm submitting a…
<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Sometimes, renaming a workspace causes focus to move briefly to a different window, then back again. This often results in my keypresses going to the wrong window :(

## Expected Behavior

Window focus shouldn't change unless I click on another window (or move the mouse to it in the case of focus-follows-mouse).

## Reproduction Instructions

- Have two monitors connected (in my setup, one above the other)
- Open at least one window on each monitor (not necessary, but makes it easier to observe the bug – look at the titlebar of the unfocused window)
- Focus a window on the lower monitor
- Run a command like `i3-msg 'rename workspace "6: aaa" to "6: aaa"'` (where workspace 6 is on the upper monitor) several times
- Notice that the focus sometimes flickers to the window on the upper monitor for a moment when the title changes (i.e. the titlebar on the focused window flickers from blue to black and back again, and vice versa on the unfocused window)

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.16.1 (2019-01-27, branch "tags/4.16.1") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16.1 (2019-01-27, branch "tags/4.16.1") (pid 1909)
Loaded i3 config: /home/josh/.config/i3/config (Last modified: Tue 26 Feb 2019 13:34:18 GMT, 384339 seconds ago)

The i3 binary you just called: /usr/local/bin/i3
The i3 binary you are running: i3
</pre>

Config: https://github.com/anowlcalledjosh/dotfiles/blob/e30be7c2133fc56bed8d6f8a166c1dd8b38b93ee/.config/i3/config

<pre>
Logfile URL: https://logs.i3wm.org/logs/5653512587313152.bz2
</pre>

<pre>
- Linux Distribution & Version: Ubuntu 18.04
- Are you using a compositor (e.g., xcompmgr or compton): no (problem happens both with and without compton running)
</pre>

**Comment by orestisf1993** [comment]
I reproduced with:
- workspace 1 assigned to left output, 1 window
- workspace 2 assigned to right output, 1 window
- focus 1
- `rename workspace 2 to 2`
