### ISSUE TITLE
autofullscreen for standalone windows

### ISSUE THREAD

**Issue by grigorievich** [i3/i3#3649]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Suppose you have a fullscreen window N1 and this window launches window N2 - which goes fullscreen. But when you close N2, N1 won't be fullscreen anymore. Exiting a fullscreen video in a browser is an example.

## Desired Behavior

When closing a fullscreen window, if there is only one window left, fullscreen it. Configurable per workspace and/or window id basis.

## Environment

Output of `i3 --moreversion 2>&-`:

<pre>
Binary i3 version:  4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16.1 (2019-01-27) (pid 1046)abort…) 
</pre>

<pre>
- Linux Distribution & Version: Arch Linux
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by orestisf1993** [comment]
Can be easily done with the IPC library, using [window events](https://i3wm.org/docs/ipc.html#_window_event).

I don't think that the proposed behavior is better as a default compared to the current behavior and making such niche cases configurable is not worth it because of the added complexity.
