### ISSUE TITLE
Improve distinction between config directives and commands

### ISSUE THREAD

**Issue by Airblader** [i3/i3#3653]
## I'm submitting a…

<pre>
[ ] Bug
[] Feature Request
[x] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

In our support channels I see a frequent confusion of config directives and commands, specifically when it comes to `for_window` and match criteria. We should make clear what the difference between config / commands are, and that a user can only run commands at runtime but not change config. 

i3 4.16

**Comment by jeffhuxen** [comment]
I would be willing to do this.  Would this be as simple as a text file, or would I edit the documentation file?

**Comment by Airblader** [comment]
We should update the userguide for this (`docs/userguide`). It itself is already separated into config and commands, but I think the distinction isn't clear enough to users. Relevant sections are

1. https://i3wm.org/docs/userguide.html#for_window
2. https://i3wm.org/docs/userguide.html#list_of_commands

Particularly in the latter one an explicit hint that config directives listed under https://i3wm.org/docs/userguide.html#configuring cannot be changed at runtime unless they happen to have a command equivalent would be extremely useful I think.

**Comment by jeffhuxen** [comment]
Okay, I will get to it the. Thanks.

**Comment by xPMo** [comment]
I agree, the `for_window` section starts out with

> With the `for_window` command ...

which is definitely misleading.
