### ISSUE TITLE
[feature request] Allow decreasing niceness of selected window's process and all children

### ISSUE THREAD

**Issue by danhoffman699** [i3/i3#3675]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

To increase the niceness of a process and all commands, I hop into htop and change it there

## Desired Behavior

It would be neat if there was some keyboard shortcut that could decrease/increase the niceness of a window and all child processes forked from the main process., or some keyboard shortcuts that the process and all child nice values to some value (probably 20 or 0). There are times when I have a lot of processes running that don't need a high priority, and having a keyboard shortcut to relegate them to the background would be useful. 
## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version:  4.16.1 (2019-01-27)
</pre>

**Comment by Airblader** [comment]
Thanks for filing this issue.

This sounds like something you can easily do in a script that you can bind to a key using `bindsym`. That way it'd also be independent of the window manager. 

Implementing it as a builtin command i3 sounds incorrect to me — we are a window manager, not a process manager. Therefore I'll close this issue. Thanks for understanding!

**Comment by danhoffman699** [comment]
Sounds good to me, I'll whip up a script. Can bindsym pass the currently highlighted PID as a parameter? I can't seem to find this in the documentation. Thanks.

**Comment by Airblader** [comment]
A PID cannot be focused, only a window which belongs to some process. There is no real standard on correlating a window to its process other than _NET_WM_PID (which the client has to implement) or some trickery of using procfs & co (in particular, i3 has no idea about processes).

You can get the focused window through window manager agnostic ways (implemented eg by xdotool) or from the i3 IPC.
