### ISSUE TITLE
i3status: insufficient capabilities to check for VPN status

### ISSUE THREAD

**Issue by snake-scaly** [i3/i3#3677]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

The only way to check for VPN status currently seems to be the Path-exists module. Documentation suggests to check for existence of /proc/sys/net/ipv4/conf/tun0. In my case it's /proc/sys/net/ipv4/conf/vpn0 with OpenConnect. Unfortunately this directory stays there after a laptop suspend even though the connection breaks.

## Desired Behavior

I know of two ways to check if the VPN connection is actually up:

1. Check if /sys/class/net/vpn0/operstate exists and contains "up". After resuming from suspend it still exists but contains "down".
2. Check if `nmcli con show --active | grep -i vpn` is non-empty.

It would be nice if one of these ways was supported, e.g. a substring search within file contents.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.14.1 (2017-09-24) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.14.1 (2017-09-24) (pid 18952)bort…)
Loaded i3 config: /home/gromov/.config/i3/config (Last modified: 2019-04-05T04:26:34 MSK, 2828 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
- Linux Distribution & Version:
~$ cat /etc/linuxmint/info 
RELEASE=19
CODENAME=tara
EDITION="Cinnamon"
DESCRIPTION="Linux Mint 19 Tara"
DESKTOP=Gnome
TOOLKIT=GTK
NEW_FEATURES_URL=http://www.linuxmint.com/rel_tara_cinnamon_whatsnew.php
RELEASE_NOTES_URL=http://www.linuxmint.com/rel_tara_cinnamon.php
USER_GUIDE_URL=help:linuxmint
GRUB_TITLE=Linux Mint 19 Cinnamon
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by Airblader** [comment]
Thanks for filing this issue, however this is the repository for the window manager. Can you please reopen this against [i3/i3status](https://github.com/i3/i3status)? Thanks!

**Comment by snake-scaly** [comment]
Sure, no problem: https://github.com/i3/i3status/issues/342
