### ISSUE TITLE
My command not being executed (Android Emulator)

### ISSUE THREAD

**Issue by Dentrax** [i3/i3#3686]
## I'm submitting a…
[ ] Bug
[ ] Feature Request
[ ] Documentation Request
[x] Other (Please describe in detail)

## Current Behavior

Custom shell script not executing from `i3`.

## Expected Behavior

Must be executed from the file from `i3`.

## Reproduction Instructions

```
# Programs
set $EXECUTE i3-EXECUTE
mode "$EXECUTE" {
    # Programs
    bindsym a exec /usr/local/bin/amx_start android-emulator,       mode "default"
    bindsym c exec /usr/local/bin/amx_start chromium,               mode "default"
    bindsym f exec /usr/local/bin/amx_start firefox,                mode "default"
    bindsym m exec /usr/local/bin/amx_start mailspring,             mode "default"

    # back to normal: Enter or Escape
    bindsym Return mode "default"
    bindsym Escape mode "default"
}
bindsym $win+e mode "$EXECUTE"
```

The commands `c`, `f `and `m` are working perfectly except `a`

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16.1 (2019-01-27) (pid 983) abort…)
Loaded i3 config: /home/dentrax/.config/i3/config (Last modified: Wed 17 Apr 2019 12:17:48 PM +03, 32952 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

My i3 config is: [here](https://github.com/Dentrax/dotfiles/blob/master/.config/i3/config)

My custom script is: [here](https://github.com/Dentrax/AMX_Manager/blob/master/amx_start)

**P.S:** Android Emulator is working fine when i execute from Terminal. 

<pre>
</pre>

**P.S:** I called my Android Emulator at `04/17/2019 09:32:03 PM` Please see the log file, for details.

<pre>
Logfile URL: https://logs.i3wm.org/logs/5639288494489600.bz2
</pre>

<pre>
- Linux Distribution & Version:` Arch 5.0.7`
- Are you using a compositor (e.g., xcompmgr or compton): `NO`
</pre>

**Comment by orestisf1993** [comment]
i3 is executing the command normally:
```
04/17/2019 09:32:03 PM - commands_parser.c:parse_command:265 - COMMAND: *exec /usr/local/bin/amx_start android-emulator,       mode "default"*
04/17/2019 09:32:03 PM - commands.c:cmd_criteria_init:151 - Initializing criteria, current_match = 0x56501d49a660
04/17/2019 09:32:03 PM - commands.c:cmd_exec:1211 - should execute /usr/local/bin/amx_start android-emulator, no_startup_id = 0
```

My guess is that `$ANDROID_HOME` is not set when executing the command through i3

**Comment by Dentrax** [comment]
@orestisf1993 

But it works in the terminal? And my `echo $ANDROID_HOME` prints `/home/dentrax/android`

Doesn't _i3_ read my **env**s?

**Comment by Airblader** [comment]
i3 starts a shell from the environment it was run in. Generally speaking your bashrc / zshrc will not have been sourced at this point. So unless you defined it in your profile that's why it won't be available.

Closing since i3 has executed the command and this is some environment issue.

**Comment by Dentrax** [comment]
@Airblader 

Consequently, how can i fix this problem?

**Comment by Airblader** [comment]
Make sure the environment variable is set in i3's environment or don't use the environment variable. A user recently commented on a thread about this on reddit: https://www.reddit.com/r/i3wm/comments/b8uri4/bash_path/ek0lwn3/
