### ISSUE TITLE
i3bar not show when start i3 session start on Hyper-V Enhanced Session Mode

### ISSUE THREAD

**Issue by sonbui00** [i3/i3#3690]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

I'm running i3 session on Arch Linux - Hyper-V Enhanced Session Mode (Basic session work normally)
 (https://wiki.archlinux.org/index.php/Hyper-V#Enhanced_Session_Mode)
i3bar do not show when start or restart i3 session with bar config: status_command i3status. 
But It's work when I run i3bar manually from command line.
## Expected Behavior

i3bar show with bar config: status_command i3status
## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors
Running version: < 4.2-200
</pre>

<pre>
bar {
    status_command i3status
}
</pre>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5722312225587200.bz2

Linux show error:
Apr 23 01:50:40 arch systemd-coredump[675]: Process 672 (i3bar) of user 1000 dumped core.

                                            Stack trace of thread 672:
                                            #0  0x00007f561b2b282f raise (libc.so.6)
                                            #1  0x00007f561b29d672 abort (libc.so.6)
                                            #2  0x00007f561b58b105 n/a (libev.so.4)
                                            #3  0x00007f561b58f79f ev_run (libev.so.4)
                                            #4  0x00005614e0aa02c1 n/a (i3bar)
                                            #5  0x00007f561b29ece3 __libc_start_main (libc.so.6)
                                            #6  0x00005614e0aa03ce n/a (i3bar)
</pre>

<pre>
- Linux Distribution & Version: Linux arch 5.0.8-arch1-1-ARCH #1 SMP PREEMPT Wed Apr 17 14:56:15 UTC 2019 x86_64 GNU/Linux 
</pre>

**Comment by devnoot** [comment]
I am running into this same issue. It seems like the issue is only related to running enhanced session mode as i3bar starts normally if I dont use xrdp to login.

```
noot@dev:~/.config/i3$ uname -a
Linux dev 5.0.0-16-generic #17-Ubuntu SMP Wed May 15 10:52:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

```
noot@dev:~$ i3 --moreversion
Binary i3 version:  4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16.1 (2019-01-27) (pid 2861)abort…)
Loaded i3 config: /home/noot/.config/i3/config (Last modified: Thu 13 Jun 2019 11:54:44 AM EDT, 728 seconds ago)
```

```
bar {
        status_command i3status
}
```

```
noot@dev:~/.config/i3$ which i3bar
/bin/i3bar
noot@dev:~/.config/i3$ which i3status
/bin/i3status
```

Executing it manually starts it though
```
noot@dev:~/.config/i3$ i3-msg -t get_bar_config
["bar-0"]
noot@dev:~/.config/i3$ i3bar --bar_id="bar-0"
[libi3] ../../i3-wm-4.16.1/libi3/font.c Using Pango font Hack, size 12
i3status: trying to auto-detect output_format setting
i3status: auto-detection: parent process is "sh", looking at its parent
i3status: auto-detected "i3bar"
```

**Comment by gtrak** [comment]
I was able to work-around it like this, still not sure why it's needed.

```
exec_always --no-startup-id i3bar -b `i3-msg -t get_bar_config | jq -r ". | first"` &
```
