### ISSUE TITLE
i3-nagbar option (default?) to appear on _current_ monitor

### ISSUE THREAD

**Issue by megatux** [i3/i3#3692]
## I'm submitting a…
<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Use the first monitor or the one defined as _primary_ with XRANDR

## Desired Behavior
Dynamically get the current monitor and display it there.
The most similar issue I've found is #1405, but it is not the same.

Unrelated extra: I would like a _"replace"_ flag to replace previous "bars", so if I call it several times it will not creates lot of "bars"

## Environment

<pre>
i3 version:   4.14.1
</pre>

<pre>
- Linux Distribution & Version:  ElementaryOS Juno
- compositor? I don't think so
</pre>

**Comment by Airblader** [comment]
i3-nagbar should already open on the primary output as shown by the issue you linked. If this is not the case for you, please file this as a bug report with corresponding information.

**Comment by orestisf1993** [comment]
He mentions that as the current behavior, not the desired

**Comment by Airblader** [comment]
Ah, yeah, I misread. So the request is for it to be put on the *focused* monitor. Yeah, I think the focused screen is more reasonable behavior than the primary screen, though I could see some users preferring it the other way around. Still, though, I'd be OK with changing this behavior.
