### ISSUE TITLE
Return a i3-input exit status indicating whether a command was executed

### ISSUE THREAD

**Issue by rittelle** [i3/i3#3705]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Currently i3-input returns 0 whenever no error occured in the program itself.

## Desired Behavior

i3-input could return 0 when the specified command was executed successfully and other values (e.g. 1 and 2) when the user canceled the process (by using the escape key) or the specified command failed respectively.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16.1 (2019-01-27) (pid 1660)abort…)
Loaded i3 config: /home/rittelle/.config/i3/config (Last modified: Sat 18 May 2019 08:06:23 AM CEST, 268412 seconds ago)

The i3 binary you just called: /nix/store/mf89f7cf3nnvzrv4ybyym476v8w02z68-i3-gaps-4.16.1/bin/i3
The i3 binary you are running: /nix/store/mf89f7cf3nnvzrv4ybyym476v8w02z68-i3-gaps-4.16.1/bin/i3
</pre>
Yes, I‘m using gaps, but skimming over the i3-input code on the next branch, the current behavior seems to be the same.

**Comment by Airblader** [comment]
SGTM, PRs welcome

**Comment by rittelle** [comment]
It doesn‘t sound too complicated, if I find the time later today, I‘ll see what I can do.

**Comment by zarszz** [comment]
interest thing

**Comment by rittelle** [comment]
It could take some time until I get to work on this, but it is not forgotten :)
