### ISSUE TITLE
Minimal width for workspace buttons

### ISSUE THREAD

**Issue by cdlscpmv** [i3/i3#3711]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
The width of workspace buttons depends solely on the text they display, so for workspaces with different names we get workspace buttons with different width.

## Desired Behavior
It would be nice to have an ability to specify some minimal width for workspace buttons,
so that they all can have the same width. I propose adding an option to i3bar, something
like `workspace_button_min_width <pixel or string>` to make it similar to the `min_width` option of i3status.

**Comment by Airblader** [comment]
> so for workspaces with different names we get workspace buttons with different width.

Why is that an issue?

**Comment by cdlscpmv** [comment]
> Why is that an issue?

1. I use a single unicode character for some workspaces. And if I don't add any padding to them, the  workspace buttons look too small. So I have to manually add some padding spaces to those workspace names to make the buttons look bigger.

2. Uniformly spaced workspace buttons aid navigation between workspaces, because now it is easier to distinguish between workspace names.

I have the patch ready, and I've been using the feature for a week without problems. I probably need to write some tests though. If you don't mind I'll open a pull request soon.

**Comment by Airblader** [comment]
> So I have to manually add some padding spaces to those workspace names to make the buttons look bigger.

Exactly, so why doesn't that suffice? Your second point seems to be solved by that as well as it isn't about having all buttons be of equal length, but just to be wider(?)

It feels like this might add a new config option for a case affecting few users and which can be solved well enough by padding the names.

For contrast, the minimum width of status blocks has a practical purpose, which is to avoid blocks visually jumping as they get shorter / longer on every update cycle. This isn't an issue with workspace buttons.

**Comment by cdlscpmv** [comment]
> For contrast, the minimum width of status blocks has a practical purpose, which is to avoid blocks visually jumping as they get shorter / longer on every update cycle. This isn't an issue with workspace buttons.

The same applies for workspace buttons as well. Workspace names can be changed which may cause the same visual jumps. For example, I often increase/decrease the number assosiated with a workspace (this number is also embedded in the workspace name). If my font is not monospace, chances are there will be some visual shortening/broadening of the workspace button which may propagate to other buttons as well.

**Comment by Airblader** [comment]
But that's on explicit user action and doesn't randomly happen every five seconds :-)

> this number is also embedded in the workspace name

Just in case you didn't know, you can hide the numbers from i3bar if you don't need/want to see them there.

**Comment by cdlscpmv** [comment]
> But that's on explicit user action and doesn't randomly happen every five seconds :-)

Nevertheless, it would be nicer not to see those glitches.

> Just in case you didn't know, you can hide the numbers from i3bar if you don't need/want to see them there.

I know that, but I still choose to show workspace numbers on some workspaces in order to navigate them easier.

Well, I've prepared one more reason for inclusion of the feature :-). That method of padding workspace names with spaces have one drawback: it's not always possible to center a unicode glyph on a workspace button. At one time I managed to achive this with various hacks like changing the font size used for the spaces in the padding with pango. But when I moved to a monitor with different resolution, all my efforts turned out to be in vain.

**Comment by Airblader** [comment]
> Nevertheless, it would be nicer not to see those glitches.

I really don't see this as a glitch, but as a totally expected effect of renaming a workspace. You also get jumps when workspaces open and close since i3 destroys empty workspaces which aren't active. 

I'm leaning towards not implementing this because I feel like this is mostly about eye candy kind of stuff. I'm not seeing a functional advantage for this.

**Comment by cdlscpmv** [comment]
> I really don't see this as a glitch, but as a totally expected effect of renaming a workspace.

Thanks to the IPC mechanism, there is more use to workspace names than manually renaming them. For example, I can switch the unicode symbol associated with a workspace depending on the application that it contains or the state of this applcation (for example, a music player can play music or be paused). To explore these possibilites further, it is essential that the width
of workspace buttons stays the same, because otherwise those nasty jumps ruin the whole experience.

> I feel like this is mostly about eye candy kind of stuff. I'm not seeing a functional advantage for this.
 
Just take a look at any kind of button in various user interfaces (on the web or in graphical toolkits). Most of them have their text centered on the button. Right now there is simply no reliable way to achieve that in i3. And the misalignment may be quite noticeable given the small size of a workspace button.

**Comment by Airblader** [comment]
Properly centering is a different issue, of course it should be centered correctly. If i3 is doing this wrong we can certainly fix that. Since we use pango for rendering text it could also be something somewhere in there, though.

Sorry, just a quick reply since I'm at a conference.

**Comment by Airblader** [comment]
Having given this some more thought I think I'm OK with adding this feature after all. I would not support a string for the min_width, though, but only a pixel value as I think the case from the i3bar protocol for a string doesn't apply here.

**Comment by cdlscpmv** [comment]
Thank you! I will create a pull request in a few days, and we can discuss the details there.
