### ISSUE TITLE
i3bar memory leak

### ISSUE THREAD

**Issue by vabenil** [i3/i3#3712]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

i3bar grows in ram usage over time. Approximately 0.1MB/s
## Expected Behavior

i3bar should be using less than a 100MB of RAM at all times
## Reproduction Instructions

My bar:
```
bar {
    position top
    strip_workspace_numbers yes
 
    font pango:Hermit, FontAwesome, Regular 12px
    colors {
        statusline #ffffff
        separator #212121
    }

    status_command ~/.config/i3/scripts/statustest.sh
}
```

~/config/i3/scripts/statustest.sh:
```
#!/bin/sh

echo '{ "version": 1 }'

echo '['

echo '[]'

while :;
do
    echo ',['
        echo "
    {
        \"name\":\"Time\",
        \"full_text\": \"$(date +%r )\",
        \"separator\": false,
        \"separator_block_width\": 0
    }"
           
    echo ']'
    sleep 1
done
```
## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version:
Binary i3 version:  4.16-130-ga5743469 (2019-04-11, branch "next") © 2009 Michael Stapelberg and contributors
(Getting version from running i3, press ctrl-c to abort…)
Running i3 version: 4.16-130-ga5743469 (2019-04-11, branch "next") (pid 3792)
Loaded i3 config: /home/vabenil/.config/i3/config (Last modified: Tue 04 Jun 2019 10:16:42 AM EEST, 1144 seconds ago)

The i3 binary you just called: /usr/local/bin/i3
The i3 binary you are running: i3

</pre>

my i3 configuration can be found here as well as all my scripts: https://github.com/vabenil/dotfiles/tree/master/.config/i3
<pre>
</pre>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5654863790735360.bz2
</pre>

<pre>
- Linux Distribution & Version: Ubuntu 19.04
- Are you using a compositor (e.g., xcompmgr or compton): I'm using compton
</pre>

**Comment by orestisf1993** [comment]
When running a development version of i3 as your daily driver, please use `--disable-sanitizers` during the configure step.
