### ISSUE TITLE
Support `class!="foo"` in command criteria

### ISSUE THREAD

**Issue by DanielHeath** [i3/i3#3717]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

You can target commands to windows matching a class, but not to windows *not* matching a class.

## Desired Behavior

I'd like to apply `no_focus` to all windows other than selected apps.

## Environment
```
  $ i3 --moreversion 2>&-
Binary i3 version:  4.15 (2018-03-10) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15 (2018-03-10) (pid 104593)abort…)
Loaded i3 config: /home/daniel/.config/i3/config (Last modified: Tue 11 Jun 2019 11:10:10 AM AEST, 219 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

  $ uname -a
Linux titan 4.18.0-20-generic #21-Ubuntu SMP Mon May 6 18:45:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```
No compositor.

I'd be interested in helping out, though I'm not super familiar with the language / coding standards.

**Comment by Airblader** [comment]
The match string is a regular expression, so you can already do this by using a negative lookahead:

```
class="^(?!foo).*$"
```
