### ISSUE TITLE
Firefox, Paraview, VS Code drop-down menu not working

### ISSUE THREAD

**Issue by amit112amit** [i3/i3#3718]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

1. Start i3 with default config and launch Firefox / VS Code / Paraview using `dmenu`.
2. Press `Alt + F` to open the File menu from the menu bar.
3. In Firefox, the menu appears but trying to select an option using up, down arrow keys does not work. In VS Code, I can see the menu rapidly flickering and disappearing. In Paraview, the menu does not show up.
4. Press `$mod + Enter` to open a terminal to the side of Firefox / VS Code / Paraview.
5. Either close the newly opened terminal with `$mod + Shift + q` or just switch to the window (Firefox / VS Code / Paraview) on the left with `$mod + ;`. Now try `Alt + F` again and everything works as expected!

## Expected Behavior

The drop-down menus must show up and the arrow keys must allow to select options from the menu.

## Reproduction Instructions

Same as in the section `Current Behaviour`.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16.1 (2019-01-27) (pid 3490)abort…)
Loaded i3 config: /home/agd/.config/i3/config (Last modified: Tue 11 Jun 2019 01:59:23 PM EDT, 1731 seconds ago)
The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3-with-/i3
</pre>
<pre>
i3 version: 4.16.1
</pre>
## Additional info:
I have HiDPI screen (Dell XPS 9550) but I run it in 1920x1080 resolution by running
`xrandr --output eDP-1 --mode 1920x1080` in my `~/.xprofile` using LightDM. I get the same issue when I was not using any display manager but starting i3 from `~/.xinitrc`.

<pre>
I removed my config and started `i3` so that it prompted me to use default config.
</pre>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5721521683169280.bz2
</pre>

<pre>
- Linux Distribution & Version:  Arch Linux 4.19.49-1-lts (all updates installed)
- Are you using a compositor (e.g., xcompmgr or compton): I have it installed but because I reproduce this issue with the default config, `compton` is never started.
</pre>

**Comment by Airblader** [comment]
These menus are override redirect windows, meaning that i3 is not involved with them whatsoever.

I could imagine this has something to do with focus behavior, but outside of that I wouldn't expect it to be an i3 issue.

**Comment by amit112amit** [comment]
Thank you for the quick reply. I don't see this behavior when I use KDE or Gnome Desktop environments. This only happens when I use i3 (although I haven't tried any other window manager except i3). Also, why does it start working when I open and close a terminal to the side? It makes it appear that the menu windows are not getting some rendering hint or something initially but later on they are able to know where to draw themselves.
