### ISSUE TITLE
Add a option to always split biggest window on the workspace

### ISSUE THREAD

**Issue by LhKipp** [i3/i3#3719]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Desired Behavior

Whenever I create a new window, I want the biggest window on the current workspace to be split (either horizontally or vertically - depending on the size) and the new window to be inserted at that place, without manual key presses like "move to the biggest window, set correct splitting and then create the new window"

Something like an option in my config file:
workspace_layout split_max.
Currently there are these options available:
workspace_layout default|stacking|tabbed

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: i3 version 4.16.1
</pre>

<pre>
- Linux Distribution & Version:Ubuntu 18.04
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by Airblader** [comment]
Thanks for opening this issue. I don't think we'll be adding this to i3, though.

1. Opening windows in the focused position is established, we have an indicator for it and there's nothing surprising about it. On the other hand, which window is "biggest" is often visually hard to say, it's not even unambiguous (what if two have the same size?) and will likely often cause confusion.
2. I think this is a very specific behavior that the vast majority of users would not use / benefit from. As such it doesn't quite pass the cost vs benefit calculation for making such a fundamental change. 
3. The workspace layout you reference is not really the same thing. It's about windows which open directly underneath the workspace node of the tree, not anywhere within the workspace. Also for those the behavior is much clearer defined. 

What you describe should be possible in a script: when a window opens, mark it and move it away or make it floating. Now determine where you want to insert it, mark that window as well and then use `[con_mark=...] move window to mark`.

Please do feel free to share such a script here if you end up writing it. For the time being I'm going to reject this feature request for the reasons above. Thanks for understanding!

**Comment by LhKipp** [comment]
Thanks for the fast answer Ingo Bürk.
Sure, I'll share the script.

PS: I3 is great and you are doing a great job.
