### ISSUE TITLE
Support transparency in i3bar

### ISSUE THREAD

**Issue by Airblader** [i3/i3#3723]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Desired Behavior

The `i3bar -t` flag from i3-gaps should be migrated into i3 so that it can also be used there.

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.16.1
</pre>

**Comment by stapelberg** [comment]
Is this a flag only or also a config file option? If a flag only, shouldn’t there be a corresponding config file option?

**Comment by Airblader** [comment]
It is purely a command-line argument, for the simple reason that at the time we need it the config has not yet been read. Changing this is possible, but a bigger change. It would probably also be much trickier to deal with changing configs on the IPC as we'd have to reinitialize the window etc.

**Comment by stapelberg** [comment]
Okay, that seems fair.
