### ISSUE TITLE
allow binding not only single keys, but also key groups

### ISSUE THREAD

**Issue by mighty9245** [i3/i3#3730]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>
---
i was trying to make my resize mode more comfortable and flexible and decided to try something like that:
```
# s - shrink, g - grow, z - 1px, x - 10px, c - 30px and arrow keys for direction
bindsym g+x+up resize grow up 10px
bindsym g+c+up resize grow up 30px
...
bindsym s+x+down resize shrink down 10px
bindsym s+c+down resize shrink down 30px
```
## Current Behavior

i3 only supports bindings satisfying `[<Group>+][<Modifiers>+]<keysym>` pattern, so it basically allows binding of only one key (and a number of modifiers)

## Desired Behavior

i would like to see ability to bind several keys at least in mode (`g+x+up` for example) if it is possible

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16.1 (2019-01-27) (pid 748) abort…)
Loaded i3 config: /home/mighty/.config/i3/config (Last modified: Sat 29 Jun 2019 05:32:06 PM MSK, 1160 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

</pre>

<pre>
- Linux Distribution & Version: arch linux with 5.1.14-arch1-1-ARCH kernel
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

**Comment by Airblader** [comment]
Hi,

thanks for the issue. We're not looking to support this ourselves because this actually comes with quite a few challenges of handling the input, for example distinguishing $mod+a from $mod+a+b.

We would recommend to use some standalone software (like xbindkeys) to configure such bindings instead. Thanks for understanding.

**Comment by mighty9245** [comment]
@Airblader, thanks for the response, then i'll try to achieve this with standalone software for binding keys someday.
