### ISSUE TITLE
switch binding mode automatically upon changing focus

### ISSUE THREAD

**Issue by xdavidliu** [i3/i3#3733]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

There is no obvious way to have different windows automatically use different keybindings when focused on them. For example, the closest thing would be something like `for_window [class="Google-chrome"] mode "my-chrome-binding-mode"`. However, this only activates `my-chrome-binding-mode` when the chrome window is _started_, not when you refocus on it.

The motivation is that I want to alter the shortcut keys in chrome itself. For example, in Chrome, Ctrl+w closes a tab. The following makes it so I don't have to hold Ctrl, just pressing w will do it:

    mode "my-chrome-binding-mode" {
        bindsym --release w exec --no-startup-id xdotool keydown ctrl key w keyup ctrl
    }

The mode itself and the bindsym command work fine, but I have to manually press a key to enter `my-chrome-binding-mode`. I also tried 

    bindsym --release w [class="Google-chrome"] exec ...

but that is equivalent to not having the class criteria at all. 

## Desired Behavior

Have some kind of syntax like 

    mode [class="Google-chrome"] "my-chrome-binding-mode" {
        ....
    }

Such that every time a window with that criteria is refocused, the mode is automatically activated. This will allow different window classes to have separate keybindings automatically, without having to manually press a button to toggle between them. 

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.16.1
</pre>

<pre>
- Linux Distribution & Version: 5.2.0-arch2-1-ARCH
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by Airblader** [comment]
Hi,

thanks for raising this feature request! I can see the benefit for your usecase, but it seems that this could comfortably and without downsides be implemented as an external tool that just watches the focus and activates the proper mode (for example using the IPC). Given that I would recommend you choose this approach, you can always look to /r/i3wm if you need some help with writing such a script. 

Within i3 this feels a bit like a workaround to reduce effort on implementing a feature we would probably implement differently, but dont actually intend on supporting anyway. Therefore I'll close this issue. Thanks for understanding!
