### ISSUE TITLE
i3 wm didn't use system network proxy for chrome

### ISSUE THREAD

**Issue by Zxrcoming** [i3/i3#3735]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
when press my chrome keyboard shortcut --same as "google chrome" in terminal, and I see don't have a proxy .

but  when I open firefox , firefox has a proxy. 

The most strang thing is when I switch to gnome desktop and use google chrome and it works ,then immediately switch back to i3 , google chrome works as expected, how strang it was!

## Desired Behavior
google chrome should have a system default proxy just like firefox has.

## Environment

i3 version 4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors

Output of `i3 --moreversion 2>&-`:

Binary i3 version:  4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16.1 (2019-01-27) (pid 7114)abort…)
Loaded i3 config: /home/zxr/.config/i3/config (Last modified: Thu 11 Jul 2019 07:26:28 PM CST, 74730 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

<pre>
i3 version: 4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors

</pre>

<pre>
- Linux Distribution & Version:
- Are you using a compositor (e.g., xcompmgr or compton):
</pre>

**Comment by Airblader** [comment]
i3 is not involved in whether a proxy is used or not. If you `exec` a command, we pass that command through unchanged, but of course it runs in the environment that was given to i3 when you launched it, so perhaps this is something you would have to investigate.

Closing as this is not an i3 issue.

**Comment by jidibinlin** [comment]
@Zxrcoming Hi I have the same problem. Have you solved this problem?
