### ISSUE TITLE
graphic artefacts when moving windows around

### ISSUE THREAD

**Issue by nsklaus** [i3/i3#3744]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

in workspace 1
i open 3 terminals,
- terminal 1 : i run powertop
- terminal 2 : i run ranger 
- terminal 3 : i do various stuffs, vim, apt-get ...

in workspace 2
- i run firefox
now i go back to workspace 1, and shuffle the window position a bit..
i never leave the default tiling mode, no floating, no stacking, no tabbing,
i just switch the variosu window's position and size with `alt+shift+arrows`
until i'm statisfied with their shape and position.
and i observe a lot of graphical glitches and artefacts can be seen in the background of my terms. please see attached screenshot.
also, the longer i keep the same windows open, the worse it deteriorate. more and more artefacts pile up, and the transparency effect looks darker as time passes, as if the opacity had been increased (but in fact its the artefacts piling up upon themselves, darkening my terms). 
you can see on the provided screenshot the term on the upper side of screen look much darker, while in fact they should look like the one below running ranger.

## Expected Behavior
moving the windows around, changing their position and size, i didn't expect to get graphical glitches. i expected windows to keep their appearances.

## Environment
ubuntu 19.04, kernel: 5.0.0-13-generic x86_64 
intel gfx, xorg options sna, dri3

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: Binary i3 version:  4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors
</pre>
my i3 config :
<pre>
# This file has been auto-generated by i2-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod1

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:monospace 10

# focus
focus_follows_mouse no

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec i3-sensible-terminal

#vol
bindsym XF86AudioRaiseVolume exec --no-startup-id "pactl set-sink-volume 0 +5%"
bindsym XF86AudioLowerVolume exec --no-startup-id "pactl set-sink-volume 0 -5%"
bindsym XF86AudioMute exec --no-startup-id "pactl set-sink-mute 0 toggle"

#bright
bindsym XF86MonBrightnessUp exec xbacklight -inc 5
bindsym XF86MonBrightnessDown exec xbacklight -dec 5

# kill focused window
bindsym $mod+Shift+A kill

# start dmenu (a program launcher)
bindsym $mod+d exec dmenu_run -nf cyan -nb black

# -fn 'terminus Mono-15' 
# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.
# bindsym $mod+d exec --no-startup-id i3-dmenu-desktop

# change focus
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+m focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+M move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+z layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+q focus parent

# focus the child container
#bindsym $mod+d focus child

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# switch to workspace
bindsym $mod+ampersand workspace $ws1
bindsym $mod+eacute workspace $ws2
bindsym $mod+quotedbl workspace $ws3
bindsym $mod+apostrophe workspace $ws4
bindsym $mod+parenleft workspace $ws5
bindsym $mod+section workspace $ws6
bindsym $mod+egrave workspace $ws7
bindsym $mod+exclam workspace $ws8
bindsym $mod+ccedilla workspace $ws9
bindsym $mod+agrave workspace $ws10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+eacute move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5
bindsym $mod+Shift+section move container to workspace $ws6
bindsym $mod+Shift+egrave move container to workspace $ws7
bindsym $mod+Shift+8 move container to workspace $ws8
bindsym $mod+Shift+ccedilla move container to workspace $ws9
bindsym $mod+Shift+agrave move container to workspace $ws10

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym m resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        status_command i3status
}
</pre>

here's my .xinitrc:
<pre>
# background
feh --bg-scale ~/Pictures/backgrounds/1477967366315.jpg 

# transparency
xcompmgr -c -f -n &

# wm
exec i3
</pre>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5683991990501376.bz2
</pre>

<pre>
- Linux Distribution & Version: ubuntu 19.04
- Are you using a compositor ?  yes: xcompmgr 
</pre>

additional screenshot displaying the problem:
![Untitled](https://user-images.githubusercontent.com/6810861/61581539-e4a70e00-ab1f-11e9-801e-f096dc883896.png)

and this is how it is supposed to look like: (you can still see the background here)
![Untitled2](https://user-images.githubusercontent.com/6810861/61581591-b8d85800-ab20-11e9-8c68-319710e5794d.png)

**Comment by nsklaus** [comment]
well .. something was wrong ..somewhere ..at some point.
i don't know what it was but it doesn't happen anymore.
i thought it maybe related to ranger w3m option for previewing images, but apparently i can't reproduce it anymore. maybe it was a problem with me compiling st term, i have no idea right now.
if i find out why, l'll update this issue.

**Comment by Airblader** [comment]
I'll close this for now since the issue resolved itself. Anyway, this is a compositing issue which we technically do not support anyway, and most likely the answer is to be found in your compositor settings or video driver (and if it is in i3, we are not likely doing anything about it).
