### ISSUE TITLE
Feature request: hide mode for borders

### ISSUE THREAD

**Issue by mzuther** [i3/i3#3763]
## I'm submitting a…
<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
There is no way to *temporarily* change the border style.

## Desired Behavior
On playing around with the `hide` display mode of `i3bar`, an idea struck: it would be great to have this mode for the border style. *All* borders (including stacked and tabbed windows) would be hidden and displayed temporarily for the time a modifier was pressed. The idea is to display the borders as an overlay (just like `i3bar` in `hide` mode) so that no window needs to be re-drawn.

The improvement: enable users to use all of their screen and only display the borders when they are needed -- i.e. when the modifier key is pressed for moving the windows around. The prospective configuration settings:

    border hide 1          # display optional permanent 1-pixel border between windows
    border modifier Mod4   # modifier for showing up all borders

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
i3 version:  4.16.1
</pre>

<pre>
- Linux Distribution & Version:  Linux Mint 19.2 Cinnamon
- Are you using a compositor (e.g., xcompmgr or compton):  compton 0.1~beta2+20150922
</pre>

**Comment by mzuther** [comment]
Here are two mockups, first with hidden borders:

![i3wm_mockup_1](https://user-images.githubusercontent.com/316423/62832016-a2598400-bc28-11e9-827b-ac82d0f3494e.png)

and then with overlayed borders:

![i3wm_mockup_2](https://user-images.githubusercontent.com/316423/62832018-a5547480-bc28-11e9-982a-38dd8c226c15.png)

**Comment by Airblader** [comment]
Thanks for opening this issue!

> There is no way to temporarily change the border style.

Yes, there is. The IPC exposes commands to change the border of any window.

> including stacked and tabbed windows

Hiding the titlebars (not borders) for those is something we don't want to do, there are various discussions in other issues regarding this. 

Your feature can be implemented with a simple script that on keydown adds borders to all windows and on keyup removes them again. I think that's reasonably easy to be solved that way, so I don't think we need to add anything for this to i3 itself. Thanks!
