### ISSUE TITLE
recent change in title truncation ellipsis wastes horizontal space

### ISSUE THREAD

**Issue by archenemies** [i3/i3#3772]
## I'm submitting a…

<pre>
[x] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When tab titles are truncated, an ellipsis was previously (v 4.13) rendered as a single character. Now it looks like it is rendered as three characters. The result is that when I have a "normal" number of tabs open, I get very little information from the titles and most of the horizontal space is taken up by dots.

![Image of title bar](https://i.imgur.com/xTMMGJk.png)

(I'm not sure if the font got larger too, or maybe it only looks like it because of #3755)

## Expected Behavior

I wanted it to be like it was before.

## Environment

I also have

    $ echo $GDK_DPI_SCALE
    1.5

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
Binary i3 version:  4.17 (2019-08-03) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17 (2019-08-03) (pid 670)to abort…)
Loaded i3 config: /home/frederik/.i3/config (Last modified: Sat 04 May 2019 03:16:49 AM PDT, 8932641 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: /home/fr/i3
</pre>

<pre>
# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see http://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod1

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:monospace 8

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
#bindsym $mod+Return exec i3-sensible-terminal
bindsym $mod+Return exec remote-xterm localhost
bindsym $mod+Tab exec remote-xterm localhost

# kill focused window
bindsym $mod+c kill

#bindsym $mod+l exec packages/focus-last.py --switch
bindsym $mod+l [con_mark=_last] focus
exec --no-startup-id focus-last-helper-3

# change focus
bindsym $mod+b focus left
bindsym $mod+n focus down
bindsym $mod+p focus up
bindsym $mod+f focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# On kensington slimptype keyboard, alt+shift+f doesn't work
# so we use ctrl instead of shift

# move focused window
bindsym $mod+Ctrl+b move left
bindsym $mod+Ctrl+n move down
bindsym $mod+Ctrl+p move up
bindsym $mod+Ctrl+f move right
# Old Kensington keyboard can't do Alt+Ctrl+f
bindsym $mod+Ctrl+g move right

# alternatively, you can use the cursor keys:
bindsym $mod+Ctrl+Left move left
bindsym $mod+Ctrl+Down move down
bindsym $mod+Ctrl+Up move up
bindsym $mod+Ctrl+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+Ctrl+w fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+t layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Ctrl+space floating toggle

# # Make the currently focused window a scratchpad
# bindsym $mod+minus move scratchpad

# # Show the first scratchpad window
# bindsym $mod+Ctrl+minus scratchpad show

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
bindsym $mod+m focus child

# switch to workspace
bindsym $mod+1 workspace 1
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9
bindsym $mod+0 workspace 10

# move focused container to workspace
bindsym $mod+Ctrl+1 move container to workspace 1
bindsym $mod+Ctrl+2 move container to workspace 2
bindsym $mod+Ctrl+3 move container to workspace 3
bindsym $mod+Ctrl+4 move container to workspace 4
bindsym $mod+Ctrl+5 move container to workspace 5
bindsym $mod+Ctrl+6 move container to workspace 6
bindsym $mod+Ctrl+7 move container to workspace 7
bindsym $mod+Ctrl+8 move container to workspace 8
bindsym $mod+Ctrl+9 move container to workspace 9
bindsym $mod+Ctrl+0 move container to workspace 10

# reload the configuration file
bindsym $mod+Ctrl+j reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Ctrl+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Ctrl+period exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym h resize shrink width 10 px or 10 ppt
        bindsym t resize grow height 10 px or 10 ppt
        bindsym n resize shrink height 10 px or 10 ppt
        bindsym s resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape
        bindsym Return mode "default"
        bindsym Escape mode "default"
}

#bindsym $mod+r mode "resize"

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
# bar {
#         status_command i3status
# }

hide_edge_borders both
workspace_layout tabbed

# for_window [class=".*"] floating disable
# for_window [title=".*"] floating disable
for_window [workspace=".*"] floating disable

# doesn't work?
#for_window [class="gimp"] floating enable
#assign [class="R_x11"] workspace 2

#focus_on_window_activation smart
#assign [class="Firefox"] workspace 2
#for_window [class="Firefox"] focus
for_window [class="R_x11"] fullscreen enable
for_window [class="R_x11"] fullscreen disable

#workspace 2 output VGA1
workspace 2 output DP-2
workspace 4 output DP-2
workspace 6 output DP-2
workspace 8 output DP-2

workspace 1 output DP-1
workspace 3 output DP-1
workspace 5 output DP-1
workspace 7 output DP-1

force_focus_wrapping yes
#workspace_auto_back_and_forth yes

# "kill" and "yank"
bindsym $mod+w mark _copy
bindsym $mod+y mark _paste, [con_mark=_copy] move to mark _paste, [con_mark=_copy] focus
# bindsym $mod+w mark copy
# bindsym $mod+y mark paste, [con_mark=copy] move to mark paste, [con_mark=copy] focus

bindsym $mod+Ctrl+Return exec my-x-browser
bindsym $mod+Ctrl+Tab exec my-x-browser
</pre>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version: Arch, Linux 4.19.61-1-lts #1 SMP Fri Jul 26 10:27:00 CEST 2019 x86_64 GNU/Linux
- Are you using a compositor (e.g., xcompmgr or compton): not that I know of
</pre>

**Comment by Airblader** [comment]
The ellipsis is handled by pango, not by i3 (see https://github.com/i3/i3/blob/next/libi3/font.c#L100), so please file a bug there and ideally link it here. Thanks!

**Comment by archenemies** [comment]
Pango is a library that i3 uses? I don't have time to become an expert on the i3 code, so I'm not going to be an efficient intermediary with another project. I had hoped it would be useful to you for me to report this regression here. I'm sorry that you had to close the bug.

**Comment by Airblader** [comment]
Yes, pango is a dependency of i3. You can find the issue tracker here: https://gitlab.gnome.org/GNOME/pango/issues

One thing that would be good to try first just to verify: could you put an actual ellipsis into a window title (using title_format or whatever) and compare it with the ellipsis of a truncation? Just to make sure it's not just an issue of the font itself.

**Comment by archenemies** [comment]
I fixed the problem by downgrading Pango, thank you for telling me about the relationship of i3 to this library.

Maybe somebody else will be able to reproduce it and comment here.

I think the issue should stay open, because in a community-driven software project it should be possible for one person to report a problem and for another person to investigate or solve it. As you point out, there are various possible causes for what I experienced, and of course there are various solutions which could happen on the i3 end, for example using a different library, or statically linking with a version that works.

**Comment by Airblader** [comment]
I think the fact that downgrading pango works conclusively proves that the issue is to be searched in pango for now, one way or another. If someone can report the issue there we can link to it here, but there's no value in maintaining issues for bugs in other software for us. :-)
