### ISSUE TITLE
Optionally add focused window title to the bar

### ISSUE THREAD

**Issue by pedrocr** [i3/i3#3774]
## I'm submitting a…
<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Bar only shows workspaces, mode and status line.

## Desired Behavior
Optionally also show the title of the currently focused window

## Environment
I'm actually using sway and have implemented this feature here:

https://github.com/swaywm/sway/pull/4463

I was asked to also suggest it for i3 to try and keep the two projects compatible. I find this useful when not using window title bars to still have the window title visible.

**Comment by Airblader** [comment]
The i3bar protocol let's you show whatever you want as a statusline block, there's no reason to add this to i3bar in any other way.

**Comment by pedrocr** [comment]
I considered doing this through the statusline. It seemed simpler however to not have an external program polling the WM to then feed the information back.

**Comment by Airblader** [comment]
This doesn't require any polling, you can get the title of the focused window even through window manager agnostic mechanisms by subscribing to events.

**Comment by pedrocr** [comment]
I can get the title through the events and then the statusline is polled. But I guess I could write a new statusline script to avoid the polling. Either way the feedback is clear. Thanks.

**Comment by Airblader** [comment]
i3bar doesn't poll the statusline, it reacts to new lines on stdout. How the statusline program does that is its job — tools like i3blocks support signal based updates. With i3status you have polling anyway, and it also supports sending a signal for immediate update.

**Comment by Airblader** [comment]
For the record: I realize you were asked to post here, but compatibility with i3 is sway's concern, i3 has no ambition to stay in sync with sway. I also don't think sway will reject these features based on how i3 thinks of them, since they are optional and won't affect compatibility. I guess it's more to make sure that if we were to add it, they could synchronize on how it could be implemented configuration wise. So this shouldn't really be in your way. Just my guess, though.

**Comment by pedrocr** [comment]
The other feature is arguable but this one if it's indeed possible through the i3bar protocol there's no reason to implement it. I don't see a way to do left alignment properly in the protocol though. I can set something like `min-width = 1000` and then `align = "left"`. But this is extremely fragile:

- It depends on the resolution of the output
- As the items on the left (workspaces and mode), drawn by the WM itself, grow and shrink the value becomes wrong
- As the items on the right in the status bar change size it also moves around

Is there actually a way to set a block as far to the left as will currently fit with the i3bar protocol?

**Comment by Airblader** [comment]
No, there's no way to do that. We definitely discussed this in the past, too, but I'm not sure if the issue is still open or closed. It does exist, though.

**Comment by pedrocr** [comment]
Maybe this?

https://github.com/i3/i3/issues/1148

The current situation does seem a bit strange. Workspaces and modes are implemented by the WM itself and then i3bar is supposed to be used for everything else. If new features are not to be added to the bar it would seem to make more sense to go the opposite direction and have everything be done with the i3bar protocol, maybe shipping a base script that works the same as before.

**Comment by Airblader** [comment]
> Maybe this?

Yes! 

I think it's fair to argue that the current situation is to an extent defined by i3's long history, but that doesn't mean it's all bad, especially once you learn and accept that we do not intend i3 (nor i3bar) to be 100% customizable in every possible aspect. Some customization is fine and useful, but we also want to keep mental complexity of the configuration down. And having workspaces baked into i3bar makes sense as that is its primary function. 

The nice thing about the architecture is that you can also run any other dock client, such as polybar, if you're looking to maximize the customization you can get.

What you suggest requires at least a new protocol version, is at best a big and complex change and at worst a breaking change. Such things require corresponding important reasons that I don't think are given here given the modularity.

**Comment by pedrocr** [comment]
Sounds fine. I was using Waybar before and got annoyed by a bug so decided to go back to a default bar and i3status. These two enhancements are the the things I miss from Waybar. There's always the alternative to just write a new bar that works like I described I guess.

**Comment by Airblader** [comment]
If writing your own bar is a serious consideration, I would also throw another solution in the ring: patching the bar of your choice locally. This requires far less work than starting from scratch.

**Comment by pedrocr** [comment]
Patching locally is what I've already done to swaybar really. It's already doing exactly what I want. But since my sway setup is now running a local blend of 5 different PRs on top of master I'd like to be able to merge upstream as much as possible.

**Comment by ddevault** [comment]
>For the record: I realize you were asked to post here, but compatibility with i3 is sway's concern, i3 has no ambition to stay in sync with sway. I also don't think sway will reject these features based on how i3 thinks of them, since they are optional and won't affect compatibility. I guess it's more to make sure that if we were to add it, they could synchronize on how it could be implemented configuration wise. So this shouldn't really be in your way. Just my guess, though.

This isn't exactly our stance. Let me clarify.

Sway is basically done with respect to i3 compatibility - it's nearly 100%. Any future changes we do with respect to features within the domain of i3 will be very conservative. I don't want sway to become the kitchen sink, at some point I will consider it done and put it into maintenance mode. Good software needn't chase shiny things to stay relevant.

That being said, there's still room for continued innovation and development in the parts of sway which are not within i3's domain, but rather within Xorg's domain. To this end we've been working on stuff like improvements to screen capture, virtual input devices, VR support, etc. Window management, however, is basically sealed and for the most part just tracks features in i3 releases.
