### ISSUE TITLE
Description for the `fullscreen_mode` field received from IPC request 'GET_TREE'.

### ISSUE THREAD

**Issue by Iskustvo** [i3/i3#3780]
## I'm submitting a…
<pre>
[ ] Bug
[ ] Feature Request
[x] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Description
When requesting `GET_TREE` over the IPC, `i3`'s response contains fields named `fullscreen_mode`.
I've got an [reasonable PR](https://github.com/Iskustvo/i3-ipcpp/pull/2) for using these fields in my IPC library, but since it is not documented in the official documentation(at least not for `GET_TREE`), I have some concerns about it:

1. Is `fullscreen_mode` field safe to use?
2. Which nodes have this flag set to `1`? (I've seen it set on some of `i3`'s internal nodes)
3. Will this field always have value or can it be `null`/unset?
4. Can it have any value other than `0` and `1`?

## Version
Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17.1 (2019-08-30) (pid 647) abort…)
</pre>

**Comment by Airblader** [comment]
> Is fullscreen_mode field safe to use?

Yes.

> Which nodes have this flag set to 1? 

"1" means that the window is fullscreened on its output, "2" means it is globally fullscreened.

> Will this field always have value or can it be null/unset?

It will always be set.

> Can it have any value other than 0 and 1?

Yes, `2`, see above. :-)

---

If someone wants to send a PR to document this [here](https://i3wm.org/docs/ipc.html#_tree_reply), we would appreciate it. :-)
