### ISSUE TITLE
Cannot download sur5r-keyring_2019.02.01_all.deb 

### ISSUE THREAD

**Issue by duckunix** [i3/i3#3781]
## I'm submitting a…
<pre>
[x] Bug
[ ] Feature Request
[x] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Trying to follow the steps listed on https://i3wm.org/docs/repositories.html for a Ubuntu 19.04 host, and it errors out on downloading the keyring.  Details below.

## Expected Behavior
Would like to be able to install the i3wm.org managed packages, but cannot.

## Reproduction Instructions
First go, as written:
<pre>

23:18:44 ⌁0% [don@eve:~/tmp/i3] $ /usr/lib/apt/apt-helper download-file http://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2019.02.01_all.deb keyring.deb SHA256:176af52de1a976f103f9809920d80d02411ac5e763f695327de9fa6aff23f416
Err:1 http://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2019.02.01_all.deb
  403  Forbidden [IP: 95.216.115.90 80]
E: Failed to fetch http://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2019.02.01_all.deb  403  Forbidden [IP: 95.216.115.90 80]                                                                                               
E: Download Failed
23:19:00 ⌁0% [don@eve:~/tmp/i3] 100 $ wget http://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2019.02.01_all.deb                                                                                                              
--2019-08-31 23:19:13--  http://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2019.02.01_all.deb
Resolving debian.sur5r.net (debian.sur5r.net)... 95.216.115.90, 46.237.250.143, 2001:470:9e42:0:221:5eff:fe56:cdba, ...                                                                                                                       
Connecting to debian.sur5r.net (debian.sur5r.net)|95.216.115.90|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-08-31 23:19:13 ERROR 403: Forbidden.
</pre>

Doing some digging, I see that I should be using **https** vs. **http**.  Trying again:
<pre>
23:20:14 ⌁0% [don@eve:~/tmp/i3] 3s 100 $ /usr/lib/apt/apt-helper download-file https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2019.02.01_all.deb keyring.deb SHA256:176af52de1a976f103f9809920d80d02411ac5e763f695327de9fa6aff23f416
Err:1 https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2019.02.01_all.deb
  Certificate verification failed: The certificate is NOT trusted. The name in the certificate does not match the expected.  Could not handshake: Error in the certificate verification. [IP: 95.216.115.90 443]
E: Failed to fetch https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2019.02.01_all.deb  Certificate verification failed: The certificate is NOT trusted. The name in the certificate does not match the expected.  Could not handshake: Error in the certificate verification. [IP: 95.216.115.90 443]
E: Download Failed
23:25:17 ⌁0% [don@eve:~/tmp/i3] 2s 100 $ wget https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2019.02.01_all.deb
--2019-08-31 23:25:40--  https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2019.02.01_all.deb
Resolving debian.sur5r.net (debian.sur5r.net)... 95.216.115.90, 46.237.250.143, 2001:470:9e42:0:221:5eff:fe56:cdba, ...
Connecting to debian.sur5r.net (debian.sur5r.net)|95.216.115.90|:443... connected.
ERROR: no certificate subject alternative name matches
        requested host name ‘debian.sur5r.net’.
To connect to debian.sur5r.net insecurely, use `--no-check-certificate'.
</pre>

This time, the SSL cert is broken for this site.

## Environment
Next part is just to keep the robot overlords happy

Output of `i3 --moreversion 2>&-`:
<pre>
i3 --moreversion
Binary i3 version:  4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16.1 (2019-01-27) (pid 18277)bort…)
Loaded i3 config: /home/don/.config/i3/config (Last modified: Sat 24 Aug 2019 09:07:50 AM CDT, 656623 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
- Linux Distribution & Version: Ubuntu 19.04.
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by Airblader** [comment]
@sur5r

**Comment by sur5r** [comment]
Thanks for the hint, fixed. Redundancy will return later today.
