### ISSUE TITLE
Hope a power-manager built in!

### ISSUE THREAD

**Issue by jidibinlin** [i3/i3#3790]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

For now, I find i3wm doesn\`t hava automatic suspend function like gnome/kde and i3wm also can\`t cowork with xfce4-power-manager or mate-power-manager very well who just can solve the backlight. I think this can influent our useing experience
## Desired Behavior

So I suggest i3 can built in a power-manager that can handle lock-screen,automatic suspend, dim screen and so on.
## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: i3 version 4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
</pre>

<pre>
- Linux Distribution & Version: Archlinux
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

**Comment by Airblader** [comment]
i3 is a window manager, we do not intend to become a full-blown DE, sorry.
