### ISSUE TITLE
Add a command for setting all the windows to the same size

### ISSUE THREAD

**Issue by avalonv** [i3/i3#3792]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Desired Behavior
Similarly to `CTRL-W_=` on vim, a command that automatically resizes all (non floating) windows in the current i3 container to roughly the same size

**Comment by Airblader** [comment]
Duplicate of #1623, also see there for a script achieving this.

**Comment by avalonv** [comment]
I was thinking of a native implementation within i3 since it seems like a common enough operation.

Thanks for linking the script though.
