### ISSUE TITLE
Enable mode upon switching to workspace

### ISSUE THREAD

**Issue by treeshateorcs** [i3/i3#3800]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Currently, when the rule  `for_window [workspace="5"] mode "mode"` is applied then if a window appears on workspace 5, mode "mode" activates for all workspaces 

## Desired Behavior

I want the mode to activate only when I'm switching to workspace 5, and when I'm on other workspaces it should never be active

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17.1 (2019-08-30) (pid 191732)ort…)
Loaded i3 config: /home/tho/.config/i3/config (Last modified: Tue 24 Sep 2019 06:41:58 AM MSK, 1011 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
- Linux Distribution & Version: Arch Linux
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

I'll try to explain my use case: I run VMs and i3 hotkeys often overlap with  the guest OS' hotkeys, so I have these lines in my config

```
assign [class="Qemu-system-x86_64"] 5
bindsym Control+slash mode "_"
mode "_" {
    bindsym Control+slash mode "default"
}
```
and they are essentially to toggle i3 hotkeys on workspace 5 when I'm running a VM in full screen

**Comment by Airblader** [comment]
This can be achieved by writing a script using the IPC. Listen for workspace events and activate the binding mode based on that.

https://i3wm.org/docs/ipc.html
