### ISSUE TITLE
certain applications freeze after doing actions or nothing

### ISSUE THREAD

**Issue by Hdertgaming** [i3/i3#3801]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When browsing normally and particularly when scrolling in Firefox or while entering information into KeePassXC the output to the screen freezes. The freeze can be fixed by waiting (sometimes) and can always be fixed by pressing the i3bar toggle key (when i3bar mode is hide). The output then jumps to whatever action has taken place. When this happens with i3bar (when i3bar mode is default) the output freezes and can be unfrozen by waiting (this is always the case). The freezing occurs without doing anything after 5 - 25 seconds or when reversing scrolling direction in Firefox. The freezing used to occur in a previous version of i3wm but far less frequently (every 10-15 minutes).

## Expected Behavior

Firefox and KeePassXC shouldn't freeze constantly
## Reproduction Instructions

Turn on computer
start i3
open Firefox
open any webpage (that's long enough to scroll in)
wait or
scroll in one direction then scroll in the other
if i3bar is show:
wait
if i3bar is hide:
toggle i3bar
start scrolling
the webpage should skip and start to respond
## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: Binary i3 version:  4.17.1 (2019-08-30) Â© 2009 Michael Stapelberg and contributors
Running i3 version: 4.17.1 (2019-08-30) (pid 18364)bortâ¦)
Loaded i3 config: /home/hdertgaming/.config/i3/config (Last modified: Thu Sep 26 14:34:33 2019, 24156 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
</pre>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5667224203296768.bz2
</pre>

<pre>
- Linux Distribution & Version: 5.3.1-arch1-1-ARCH
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

I would like to note that this issue doesn't happen with:
<pre>
xfce & xfwm
Windows
URxvt
Mindustry
a near identical arch & i3 setup but with different hardware
</pre>
and that the issues does happen with:
<pre>
firefox
firefox (default profile)
firefox (after following troubleshooting)
KeePassXC
xfce & i3
i3
i3-gaps
</pre>
Current config:

<pre>
# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:monospace 8

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesnât scale on retina/hidpi displays.

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec urxvt

# kill focused window
bindsym $mod+Shift+q kill

# start dmenu (a program launcher)
# bindsym $mod+d exec dmenu_run
# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.
bindsym $mod+d exec --no-startup-id i3-dmenu-desktop

# maximum floating window size
floating_maximum_size 1356 x 758

# change focus
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+semicolon focus right

# alternatively, you can use the cursor keys:
#bindsym $mod+Left focus left
#bindsym $mod+Down focus down
#bindsym $mod+Up focus up
#bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+semicolon move right

# alternatively, you can use the cursor keys:
#bindsym $mod+Shift+Left move left
#bindsym $mod+Shift+Down move down
#bindsym $mod+Shift+Up move up
#bindsym $mod+Shift+Right move right

# floating modifier
floating_modifier Mod4

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# default border style
default_border pixel 1
default_floating_border pixel 1
hide_edge_borders both

# i3-gaps
#gaps inner 10
#gaps outer -4
#smart_gaps on

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
bindsym $mod+z focus child

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# switch to workspace
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace $ws8
bindsym $mod+9 workspace $ws9
bindsym $mod+0 workspace $ws10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5
bindsym $mod+Shift+6 move container to workspace $ws6
bindsym $mod+Shift+7 move container to workspace $ws7
bindsym $mod+Shift+8 move container to workspace $ws8
bindsym $mod+Shift+9 move container to workspace $ws9
bindsym $mod+Shift+0 move container to workspace $ws10

# reload the configuration file
bindsym $mod+Shift+x reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the windowâs width.
        # Pressing right will grow the windowâs width.
        # Pressing up will shrink the windowâs height.
        # Pressing down will grow the windowâs height.
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym semicolon resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        #bindsym Left resize shrink width 10 px or 10 ppt
        #bindsym Down resize grow height 10 px or 10 ppt
        #bindsym Up resize shrink height 10 px or 10 ppt
        #bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

focus_follows_mouse no

bindsym $mod+r mode "resize"

bindsym $mod+g exec "ithreelock"

for_window [class="Tor Browser"] floating enable

for_window [class="veracrypt"] floating enable

for_window [class="Devtools"] floating enable

for_window [class="Steam"] floating enable

for_window [class="SpeedCrunch"] floating enable

exec --no-startup-id "nm-applet"

#exec "volume 80"

exec "keepassxc"

exec "setxkbmap -option && setxkbmap -option \"caps:swapescape\" -option \"compose:ralt\""

exec "feh --bg-fill ~/documents/pictures/LineageOsWallpaper.jpg"

#exec --no-startup-id "~/.fehbg"

bindsym XF86MonBrightnessDown exec "backlight 1"

bindsym XF86MonBrightnessUp exec "backlight 2"

bindsym XF86AudioLowerVolume exec "volume - 5"

bindsym XF86AudioRaiseVolume exec "volume + 5"

bindsym XF86AudioMute exec "volume m"

bindsym XF86AudioPrev exec "cmus-remote -C player-prev"

bindsym XF86AudioPlay exec "cmus-remote -C player-pause"

bindsym XF86AudioStop exec "cmus-remote -C player-stop"

bindsym XF86AudioNext exec "cmus-remote -C player-next"

bindsym XF86ScreenSaver exec "ithreelock"

bindsym XF86Calculator exec "speedcrunch"

#bindcode 237 exec "backlight 1"

#bindcode 238 exec "backlight 2"

bindsym $mod+m scratchpad show

bindsym $mod+Shift+m move scratchpad

bindsym $mod+b exec "firefox"

bindsym $mod+Shift+b exec "pcmanfm"

#bindsym $mod+t exec "i3-nagbar -t warning -m 'Are you, kind Sir inclined to open this.' -B 'Yes, open it!' 'tor-browser'"

bindsym $mod+t exec "tor-browser"

bindsym $mod+c exec "idlex"

#bindsym $mod+Shift+c exec "code"

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        status_command i3blocks
	mode hide
	#hidden_state hide
	modifier Mod4
	font xft:Inconsolata-regular 9
}
</pre>

Slightly modified default config that causes the issue:

<pre>
# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:monospace 8

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

# The combination of xss-lock, nm-applet and pactl is a popular choice, so
# they are included here as an example. Modify as you see fit.

# xss-lock grabs a logind suspend inhibit lock and will use i3lock to lock the
# screen before suspend. Use loginctl lock-session to lock your screen.
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork

# NetworkManager is the most popular way to manage wireless networks on Linux,
# and nm-applet is a desktop environment-independent system tray GUI for it.
exec --no-startup-id nm-applet

# Use pactl to adjust volume in PulseAudio.
set $refresh_i3status killall -SIGUSR1 i3status
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10% && $refresh_i3status
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10% && $refresh_i3status
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle && $refresh_i3status
bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle && $refresh_i3status

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec i3-sensible-terminal

# kill focused window
bindsym $mod+Shift+q kill

# start dmenu (a program launcher)
bindsym $mod+d exec dmenu_run
# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.
# bindsym $mod+d exec --no-startup-id i3-dmenu-desktop

# change focus
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+semicolon focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+semicolon move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split
##
#default_border pixel 1
#default_floating_border pixel 1
#hide_edge_borders both
##
# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# switch to workspace
bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4
bindsym $mod+5 workspace number $ws5
bindsym $mod+6 workspace number $ws6
bindsym $mod+7 workspace number $ws7
bindsym $mod+8 workspace number $ws8
bindsym $mod+9 workspace number $ws9
bindsym $mod+0 workspace number $ws10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3
bindsym $mod+Shift+4 move container to workspace number $ws4
bindsym $mod+Shift+5 move container to workspace number $ws5
bindsym $mod+Shift+6 move container to workspace number $ws6
bindsym $mod+Shift+7 move container to workspace number $ws7
bindsym $mod+Shift+8 move container to workspace number $ws8
bindsym $mod+Shift+9 move container to workspace number $ws9
bindsym $mod+Shift+0 move container to workspace number $ws10

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the windowâs width.
        # Pressing right will grow the windowâs width.
        # Pressing up will shrink the windowâs height.
        # Pressing down will grow the windowâs height.
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym semicolon resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        status_command i3status
	mode hide
	modifier Mod4
}
</pre>

**Comment by bitdefect** [comment]
I'm having the same issue. I did a kernel downgrade and the problem disappeared. I think it came with a driver change in the most recent kernel.

**Comment by Hdertgaming** [comment]
> I'm having the same issue. I did a kernel downgrade and the problem disappeared. I think it came with a driver change in the most recent kernel.

I fixed the problem by downgrading to 5.2.14-arch2-1 from 5.3.1-arch1-1
Is there any other action I need to take elsewhere?

**Comment by bitdefect** [comment]
I played a bit with the settings. Setting "TearFree" seems to solve the issue even for the most recent kernel: https://wiki.archlinux.org/index.php/Intel_graphics#Tearing

**Comment by bitdefect** [comment]
Forget my last past. After some testing this evening it didn't fix the issue.

**Comment by bitdefect** [comment]
Alright, after some more playing it seems that removing xf86-video-intel is a workaround. Read here for the implications on doing that: https://wiki.archlinux.org/index.php/Intel_graphics#Installation

**Comment by Hdertgaming** [comment]
after downgrading to 5.2.14-arch2-1 and playing around a bit the problem still occurred but less frequently. I uninstalled xf86-video-intel and that seem to fix it on both 5.2.14 and 5.3.1
