### ISSUE TITLE
add --if-empty to exec

### ISSUE THREAD

**Issue by 4nd3r** [i3/i3#3804]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

right now I use following:
```
bindsym $mod+w workspace w; exec --no-startup-id i3-run firefox
```
script `i3-run` checks if current focused workspace is empty and executes command, if so.

I have many similar bindings for single app dedicated workspaces.

for reference, my `i3-run` script:

```
#!/bin/sh -e

__workspace_windows() {
    i3-msg -t get_tree | jq -r ".nodes[].nodes[].nodes[]
        | select(.type==\"workspace\" and .name==\"$1\")
        | .nodes[].nodes[]"
}

__active_workspace_name() {
    i3-msg -t get_workspaces \
        | jq -r '.[] | select(.visible==true).name'
}

__active_workspace_window_count() {
    __workspace_windows "$( __active_workspace_name )" \
        | jq -r '.name' \
        | wc -l
}

[ "$( __active_workspace_window_count )" -eq 0 ] && "$@" &
```
(yeah, sure, you can optimize it)

## Desired Behavior

of course I can continue using my wrapper script without problems, but I was wondering maybe this feature can be useful to many users if supported in core? I leave this decision to developers of this fine piece of software.

**Comment by Airblader** [comment]
Thanks for the request. I think that these kind of requirements aver very specific and hard to capture in a general way, so it's better solved by a script rather than adding unrelated flags to `exec`. Therefore I don't think we'll be adding this to i3. Thanks for understanding!
