### ISSUE TITLE
Leave Fullscreen Temporary on popup

### ISSUE THREAD

**Issue by fcladera** [i3/i3#3805]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When there is a popup, current options quit fullscreen (or ignore the popup). 

## Desired Behavior

It would be good to go back to the fullscreen mode after the popup has been solved. I'll submit a PR  if there is enough momentum.
## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 

Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17.1 (2019-08-30) (pid 2597)abort…)
Loaded i3 config: /home/fclad/.i3/config (Last modified: Wed 04 Sep 2019 03:05:46 PM EDT, 1973955 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
- Linux Distribution & Version: Arch Linux
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

**Comment by Airblader** [comment]
For my understanding, do you already have the patch ready or would you simply be willing to start working on this if approved?

**Comment by fcladera** [comment]
I have started doing something, but it is far from complete.I just wanted to know if the feature is useful or it is a waste of time to prepare a PR on this. Thanks!

**Comment by orestisfl** [comment]
First of all, when `popup_during_fullscreen smart` is set popups do not leave fullscreen.

So, this issue is only about `popup_during_fullscreen leave_fullscreen`. Should the proposed new behavior optional or the default?

**Comment by Airblader** [comment]
The reason I'm not sure about adding this is that it can lead to pretty confusing behavior. If fullscreen is left and the user does a bunch of things before actually closing that window, it is awkward that suddenly some window regains fullscreen status "out of nowhere". On the other hand I also see the usefulness of this behavior, in fact personally I have a script which does basically exactly this for when I open some throw-away floating terminal.

**Comment by fcladera** [comment]
Maybe setting a timer would help? My first use case was password popups, which get resolved pretty quickly but afterwards one has to explicitly make the window that triggered the popup fullscreen again.

**Comment by pnfox** [comment]
Would be much more elegant if popup showed on top of fullscreened window. Most likely harder to do though. Perhaps it would be simpler to just exit fullscreen when popup window is created but then don´t force user back into fullscreen? That would get rid of unexpected jumps. Popups will always appear on the same workspace as application that created it right?

**Comment by orhun** [comment]
It would be really nice to have this!

**Comment by vanboom** [comment]
> Perhaps it would be simpler to just exit fullscreen when popup window is created but then don´t force user back into fullscreen? That would get rid of unexpected jumps. Popups will always appear on the same workspace as application that created it right?

Imho leaving fullscreen would be most intuitive.  Opening a new window should pop out of fullscreen mode.  Currently the new window opens but does not appear because the current full screen window remains full screen. 

Try this: 
1. Open a browser, then activate full screen
2. Open a terminal window.  The terminal opens but the browser remains full screen. 

UPDATE: my apologies on previous comment - I am referring to new application windows not popups of the full screen application in this comment, and suggesting that new application windows should cause existing windows to leave full screen mode to allow the new window to appear tiled instead of "behind" the existing full screen window.

**Comment by orestisfl** [comment]
Closing in favor of https://github.com/i3/i3/issues/6062, it's not exactly the same issue but the "temporary" part of this ticket would make this feature unnecessarily complicated.
