### ISSUE TITLE
[Feature request] Hide titlebar if only one window in a workspace

### ISSUE THREAD

**Issue by jluttine** [i3/i3#3811]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Currently, it is possible to hide edge borders if the window is the only one in a workspace:

```
hide_edge_borders smart
```

## Desired Behavior

Would be nice to have a similar feature for titlebars. I want to see titlebars in split containers (and in stacked and tabbed containers obviously), but when the window is the only one in the workspace, I'd like to hide the titlebar automatically.

**Comment by Airblader** [comment]
We allow hiding the borders because their primary function is to separate windows, which with a single window isn't necessary. I don't really see a similar argument for the titlebar which has window information as the primary function.

Given that I don't think adding more configuration surface for this is worth it, even with the edge border hiding people already want a different types of behavior and the same would likely apply here, so I think this is better handled in a script using the IPC such that you can hide/show the titlebars exactly when you want to see them. Thanks for understanding!

**Comment by jluttine** [comment]
Ok, thanks for the response. And yes, I understand. I'm not arguing now, but just writing some motivation for reference, in case it is of interest to someone: For me at least, the main purpose of the titlebar is to highlight the focused window in a clearly visible way. The content of the titlebar of the focused window can be put to the bar so one can see it there anyway. So in that case no information is lost if there's only one window in the workspace.

Also, just for reference, this kind of setting can be used to toggle the titlebar/borders of the focused window: 

```
bindsym $mod+BackSpace border toggle
```

**Comment by steveb-123** [comment]
I would just like to agree with jhuttine: for me the main function of the title is for focus. I barely/rarely/never read the title text. 

I understand for people who routinely run multiple terminal emulators (running vim?) in separate windows this might not be the case though. Clearly the titlebar text is has function in that setting.

For me it was unexpected that this requested feature would not be an available option in i3.

**Comment by orestisfl** [comment]
You can implement this yourself using the IPC interface. You can probably find a ready-made script

**Comment by steveb-123** [comment]
I wasn't aware of this interface, but I don't have the time to work on this. My aim was just to add that to me this was something that seemed like a natural standard option to be present. Indeed I was just googling for some time to try to find the option.

We all bring our own usage/use-case biases. I just wanted to second jluttine. Whether to add main line features or not is not up to me, but thats quite okay with me :)

Thanks for your work on i3! I love it.

**Comment by eeriemyxi** [comment]
I threw together a quick script if you want it:

```python
# /// script
# requires-python = ">=3.4"
# dependencies = [
#     "i3ipc",
# ]
# ///

# @name i3-smart-titlebar.py
# @description Disable i3WM titlebar when the current workspace at any moment has only one
# window. Enable it again if there are more.
# @author myxi@envs.net
# @license MIT

from i3ipc import Connection, Event

i3 = Connection()
i3.ws_focus = None

def on_workspace_focus(self, e):
    self.ws_focus = e.current

def on_window_focus(self, e):
    if not i3.ws_focus:
        return
    amnt = len(self.ws_focus.leaves())
    if amnt == 1:
        i3.command("border none")
    else:
        i3.command("border normal")

i3.on(Event.WORKSPACE_FOCUS, on_workspace_focus)
i3.on(Event.WINDOW_FOCUS, on_window_focus)

i3.main()
```
Run it with `uv run -s i3-smart-titlebar.py`. You can get `uv` [here](https://github.com/astral-sh/uv). Otherwise `python3 -m pip install --user i3ipc && python3 i3-smart-titlebar.py`.
