### ISSUE TITLE
i3-msg error in tmux: could not connect to i3 on socket

### ISSUE THREAD

**Issue by bilaal-s** [i3/i3#3845]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When running any i3-msg command in tmux the following error occurs: i3-msg: Could not connect to i3 on socket /run/user/1000/i3/ipc-socket.2087: Connection refused

## Expected Behavior

This error should not occur in tmux.

## Reproduction Instructions

Running any i3-msg command in tmux (I know this isn't helpful, sorry).

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
</pre>

https://github.com/bilaal-s/dotfiles/blob/master/i3/config

Logfile URL: https://logs.i3wm.org/logs/5680478338154496.bz2

<pre>
- Linux Distribution & Version: Ubuntu 18.04.2 LTS
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

**Comment by orestisfl** [comment]
Can you try to reproduce in a separate session without any custom tmux config, just have `exec i3` in your xinitrc and just do the following:  start i3, start tmux, run any i3-msg command, exit, upload the logfile

**Comment by bilaal-s** [comment]
@orestisfl thanks for looking into this! it seems to work outside of tmux. here is a logfile: https://logs.i3wm.org/logs/5714303789301760.bz2

**Comment by orestisfl** [comment]
Your uploaded files do not seem to contain a complete log, if you are running multiple X sessions concurrently you'll have to modify the display number in `DISPLAY=:0`.

**Comment by stapelberg** [comment]
Most likely your tmux session uses an old `I3SOCK` environment variable, i.e. you restarted i3 but kept the same tmux session running.

One possible fix for this might be to just unset `I3SOCK` before launching tmux and rely on i3-msg’s socket path auto-detection via the X11 root window.

I’ll close this issue as I don’t think there’s a bug here.
