### ISSUE TITLE
Rewriting key bindings

### ISSUE THREAD

**Issue by DamienCassou** [i3/i3#3847]
## I'm submitting a…
<pre>
[x] Feature Request
</pre>

I would like to use Emacs bindings in every app I use. For that, I can have something like this in my i3 configuration file:

```conf
# Bind Control+b so it moves the cursor one character to the left:
bindsym --release Control+b exec --no-startup-id xdotool key --clearmodifiers Left
```

This "works" but has problems that prevent me from actually using it:
- using `xdotool` means executing a command for each key press which is noticeably slow (especially when I have to press it a lot of times quickly)
- I can't let <kbd>Control+b</kbd> pressed for some time to go back many characters
- the binding is active for every window, even for Emacs which makes no sense and may even be problematic (if <kbd>Left</kbd> has a different meaning than <kbd>Control+b</kbd> there)
- you can't have more complex keybindings such as <kbd>Control+x h</kbd>

I'm dreaming about something like that in my configuration file:

```conf
# Bind Control+b so it moves the cursor one character to the left:
rebindsym [class!="Emacs"] Control+b to Left
# Bind Control+x h so it selects all text:
rebindsym [class!="Emacs"] Control+x h to Control+a
```

Note the `rebindsym` new keyword and the  `!=` new operator (to exclude Emacs).

**Comment by Airblader** [comment]
I think I would rather send this kind of complexity to dedicated software for this purpose.

**Comment by DamienCassou** [comment]
Ingo Bürk <notifications@github.com> writes:
> I think I would rather send this kind of complexity to dedicated
> software for this purpose.

is there a way to write an application separate from the WM that would
capture the keybindings for all applications but Emacs?

-- 
Damien Cassou

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by Airblader** [comment]
Window managers are not special in this regard, any X client can capture key bindings the same. The difference is just who does it "first".

**Comment by stapelberg** [comment]
I agree that this should be implemented in a separate program. Closing this issue.
