### ISSUE TITLE
rename i3's config file to `i3.conf`

### ISSUE THREAD

**Issue by lxbarbosa** [i3/i3#3851]
<pre>
[x] Feature Request
</pre>

## Current Behavior
Hi, Most software that use XDG CONFIG convention are naming their config files as `xxx.conf` as `tmux.conf, sakura.conf, mpv.conf`

What do y'all think about changing i3 config file from `config` to `i3.conf` too? 

`XDG_CONFIG_HOME/i3/i3.conf'

Thanks! 

## Environment
<pre>
i3 version:  4.17.1 (2019-08-30)
</pre>

<pre>
- Linux Distribution & Version:  Debian SID 10
- Compositor: No
</pre>

**Comment by Airblader** [comment]
Looking at my local `~/.config` folder I cannot confirm that hypothesis. In fact there are two patterns applications use:

1. `~/.config/app.conf`
2. `~/.config/app/config`

Since we do put our config into an i3 subfolder I don't see much reason to repeat the name again.

**Comment by orestisfl** [comment]
I think the proposed path would be ~/.config/i3.conf

It's not a bad idea, since we only have one file. Maybe as the second
option to avoid changing default location s once again.

**Comment by Airblader** [comment]
I'm not seeing any benefit to doing this. All it does is add complexity and if we ever do need another file we have a problem.

**Comment by lxbarbosa** [comment]
@Airblader 

Ive seen some software that have `good reason` to not followed that convention as their config file are actually using their own programming language:
 
`config.fish`, `init.vim`

@orestisfl 

It could still mantain its folder:

`/i3/i3.conf`

**Comment by Airblader** [comment]
No, there's plenty of software with a config filename of literally `config`, in my local machine that is even the majority of tools. Either way, we have what we have and changing it should come with a good reason that I am still missing. What's the benefit of renaming the file?

**Comment by lxbarbosa** [comment]
@Airblader 
real benefit? none

conventions are not rules, but they easy users life, a lot! 

Thanks, anyway! :D

**Comment by Airblader** [comment]
> conventions are not rules, but they easy users life, a lot!

And if there is a convention we can think about adopting it, but as I said the hypothesis "most apps do this" at least is not correct on my local machine, but if there is some actually written down convention somewhere or evidence that it is indeed the majority we can think about it.

**Comment by lxbarbosa** [comment]
fixed: 'most' -> 'some' 
+1
