### ISSUE TITLE
i3-nagbar optional expire-time

### ISSUE THREAD

**Issue by x123** [i3/i3#3873]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
i3-nagbar sticks around permanently or until manually closed.

## Desired Behavior
be able to specify an optional time in milliseconds for the nag to stay on screen before disappearing/expiring (for reference `notify-send` has a behavior like this with `-t`)
```
  -t, --expire-time=TIME            Specifies the timeout in milliseconds at which to expire the notification.
```
 This would be particularly useful when using `i3-nagbar` as the `notifier` in `xautolock` prior to utilizing `i3lock`. It works great as is, but upon returning to the machine and unlocking the nagbar stays around, having a customizable expiry time would be perfect.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.17.1 (2019-08-30)
</pre>

<pre>
- Linux Distribution & Version: NixOS 19.09
- Are you using a compositor (e.g., xcompmgr or compton): No.
</pre>

**Comment by Airblader** [comment]
Thanks for opening this issue. We don't really want to extend i3-nagbar much. It is not intended as a tool for users to use very actively, but just a small utility to *nag* users that we can make use of. :-)

For use-cases such as this one there's plenty other – better – tools, like zenity etc. A workaround would also be to just start a timeout in the background to kill the process (if you really want to).

See https://github.com/i3/i3/issues/2765#issuecomment-326362037 for more context. Thanks for understanding!
