### ISSUE TITLE
Separate full-screen mode of application and maximising a window

### ISSUE THREAD

**Issue by TitouanT** [i3/i3#3884]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

To explain the feature request I will take the example of chrome but It applies to other application as well.
This feature request is close but not quiet the same as #2107.

## Current Behaviour

When pressing Alt+f (`fullscreen toggle`), the window takes the whole screen and the application is notified to go on it's own full screen mode. For chrome it means that the tabs navigation bar disappears, And the current web page takes the whole window space.

## Desired Behaviour

The desired behaviour is to separate changing the size of the window (`fullscreen toggle`) and notifying the application to go on its own fullscreen mode (`fullwindow toggle`).
Thus allowing the user to:
+ maximise the window and keep the same view of the application (`fullscreen toggle`)
+ tell the application to go on it's fullscreen mode in the current window's boundaries (you can still view your other splits if any) (`fullwindow toggle`)
+ or do both (like the current behaviour) by maximising the window and telling the application to go on fullscreen mode. (`fullwindow toggle && fullscreen toggle`)

I have drawn this to summarise the feature request:
![full_screen_window](https://user-images.githubusercontent.com/16353124/71323238-46094980-24d1-11ea-8393-4c8973b32738.jpg)

Of course the naming of the different options can differ to be compatible with older behaviour and/or to be more meaningful.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
(Getting version from running i3, press ctrl-c to abort…)
Running i3 version: 4.17.1 (2019-08-30) (pid 1030)
Loaded i3 config: /home/t2/.config/i3/config (Last modified: lun. 09 déc. 2019 16:14:21 CET, 1117308 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
- Linux Distribution & Version: Antergos
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by Airblader** [comment]
As I stated in the linked issue already this is a firm "no". If Chrome wants to be like this in fullscreen and you don't like it, please file it with Chrome. Thanks for understanding!

**Comment by TitouanT** [comment]
As I said, other apps do that too.

**Comment by Airblader** [comment]
That doesn't change my opinion. These apps *explicitly* implemented different behavior for fullscreen and from a window manager perspective it is up to the client to make this decision of how they feel best represented while fullscreened. That's why the fullscreen protocol works the way it works: we only tell them that they are fullscreen, not what they have to do with that. If users of such applications don't like those decisions they should address it with the respective developers. The window manager is not the place to workaround unpopular decisions of the design of client applications' windows.

**Comment by TitouanT** [comment]
Actually, I like how it is when it is fullscreen, but it would be a nice thing to have the app `fullscreened` in a smaller window. This is the main reason I switched to i3 in the first place. I thought it was one of the features of i3 until it stopped working and I realised that it was just a bug in chrome that made it behave like I wanted to. I guess now I want to take it out of the hands of chrome to decide how the window behaves but you are telling me that it should stay a chrome decision.

> what if next release Chrome decides that they hide the UI not based on the _NET_WM_STATE_FULLSCREEN atom but on whether the window dimensions match the output dimensions?

If one day they decide to detect fullscreen mode by comparing the window's size to the screen size then that would be something to report as a bug to them.

> That's why the fullscreen protocol works the way it works: we only tell them that they are fullscreen, not what they have to do with that.

All I want there is to control when i3 tell them that they are fullscreen.

Of course I am not saying that this feature should be the default behaviour for all users, but if people are looking for it, shouldn't they have a way to find it ?

**Comment by Airblader** [comment]
> but it would be a nice thing to have the app fullscreened in a smaller window.

That is a different feature request from the one presented here and essentially an addition of #2107 since that's maximization, not fullscreen.

>  If one day they decide to detect fullscreen mode by comparing the window's size to the screen size then that would be something to report as a bug to them.

And yet no one seems to want to report this current issue to Chrome. *shrugs* :-) 

> All I want there is to control when i3 tell them that they are fullscreen.

As I said, IMHO this is too technical to expose it directly to users. There's also no intent for this in the specs. If we fullscreen, we fullscreen. Don't mask unpleasentries in client applications by breaking specifications.

> if people are looking for it, shouldn't they have a way to find it ?

Every new feature comes with cost in terms of code, maintenance, testing and mental complexity for the users. We therefore don't just merge features just because they can be made optional.

**Comment by TitouanT** [comment]
> That is a different feature request from the one presented here and essentially an addition of #2107 since that's maximization, not fullscreen.

It's the top right state in the picture.

**Comment by Airblader** [comment]
That part is actually violating the specs since we'd tell an app to be fullscreen that isn't. I assumed what you meant was maximize inside some parent container.

**Comment by TitouanT** [comment]
All right, I guess we don't want that.

**Comment by Airblader** [comment]
For completeness sake, here is an excerpt from the spec:

> _NET_WM_STATE_FULLSCREEN indicates that the window should fill the entire screen and have no window decorations. Additionally the Window Manager is responsible for restoring the original geometry after a switch from fullscreen back to normal window. For example, a presentation program would use this hint.

I will actually have to correct myself with regards to breaking the spec: it only uses "SHOULD" (RFC 2119) and is therefore not forbidden. 

This part may be something to think about separately. But I'd open a separate issue for fullscreening containers inside some parent container other than the output container itself (feel free to do so — note that I'm not saying it's an automatic yes, but it's definitely not an automatic no, either). 

Fullscreen without actually using the fullscreen protocol is still a different topic that I oppose.

**Comment by Airblader** [comment]
One more note: maximizing to arbitrary (parent) containers rather than to the output is the maximize equivalent we could also consider once maximization has actually been implemented.

**Comment by dpuhr** [comment]
I was hoping that i3 just supports this functionality. It's a pity I was wrong. I wanted to use i3 as a presentation environment for multiple browser instances in their windows, and I assumed they would be able to switch to fullscreen mode within the window. Too bad...
