### ISSUE TITLE
Add a way to get current binding mode through IPC, without waiting for MODE event.

### ISSUE THREAD

**Issue by Iskustvo** [i3/i3#3892]
## I'm submitting a…
<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
At the moment, there is no way to get current binding mode from i3.
This is an issue for initialization of a status bar.
Yes, it can be workaround by subscribing to MODE event and waiting for mode change(or forcing MODE event by sending the request to change binding mode) but this is not a proper solution.

## Desired Behavior
There are two clean ways to resolve the issue.
1)  Add support for new IPC request, for example GET_CURRENT_BINDING_MODE.
2)  Expend GET_BINDING_MODES to also provides info about current binding mode, either as a string or an index for the already provided list of all available binding modes.

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.17.1 (2019-08-30)
</pre>

**Comment by orestisfl** [comment]
https://github.com/i3/i3/issues/2711

**Comment by Iskustvo** [comment]
@orestisfl, sorry but I don't see any useful information on that issue.
As I've noted in the description, I am aware of the MODE event, but that is not the solution.
I do not see any way to start a status bar and properly display current mode.

Consider below attempts to understand the struggle :D
1) If I have to wait for the user to change mode first time in order to start displaying it, that is just bad.
2) If I force change to "default" mode in order to trigger that event, I can't go back and I will change users environment for no reason.
3) If user sets the name of **his** default mode in my config file, there is still a reasonable assumption that he might start a bar later when the mode is not in **his** default state.

Since this issue is obviously coming back and people are either masking or altogether ignoring it, I have to ask. Why are you(not you personally, but core developers in general) against adding new(or modifying existing) request to resolve this issue?

**Comment by Airblader** [comment]
We're not against it, but until now the alternatives have worked for anyone who brought it up. I believe @orestisfl only referenced the issue as related, nothing else. 

I'm absolutely not opposed to adding this. A breaking change to the existing one could probably only be achieved by making sure the current mode is the first one in the array, otherwise it'd have to be a new request.

**Comment by Iskustvo** [comment]
@orestisfl, I guess I was too optimistic when I saw the referenced issue and expected the solution there. Sorry if I came out as bitter :)

@Airblader, great idea for a solution that doesn't break the API!

**Comment by Airblader** [comment]
Yeah, it's "clever", but the more I think about it the more I prefer a separate request as it's more clear.

**Comment by stapelberg** [comment]
For the record: the stream recording where this was implemented can be found at https://youtu.be/rv4nVz4gG6w
