### ISSUE TITLE
bindsym arrows only work in reverse order

### ISSUE THREAD

**Issue by Silur** [i3/i3#3907]
I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
`bindsym $mod+Left|Up|Right|Down focus left..`
and
`bindcode xy+z ...` equivalents (codes got with `xev`)
only trigger their corresponding commands if keys pressed in reverse order,
- Left+$mod -> command ok :heavy_check_mark: 
- $mod+Left -> not firing :x: 

## Expected Behavior
command should work in the specified order

## Reproduction Instructions
use default config generated by wizard or explicitly set focus/move commands by codes
try to use any command that involves arrow keys

## Environment
Linux 5.5.0-0.1 MANJARO-ARM
Pinebook Pro

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.17.1 (2019-08-30)
</pre>

config: https://pastebin.com/xCKeewXy

<pre>
Logfile URL: https://logs.i3wm.org/logs/5643435285413888.bz2
</pre>

<pre>
- Linux Distribution & Version: Manjaro 
- Are you using a compositor (e.g., xcompmgr or compton): only x11 
</pre>

**Comment by Airblader** [comment]
> command should work in the specified order

Small note: it shouldn't; what matters is the fact that the modifier is pressed first.

**Comment by Silur** [comment]
Also note that individually, `Left` sym or code `113` can fire any command, they are only "muted" if used together with mod

**Comment by Silur** [comment]
this seems to be a pinebook pro issue as it's present in other window managers too
