### ISSUE TITLE
Give popup_during_fullscreen a sister: window_during_fullscreen 

### ISSUE THREAD

**Issue by magnetophon** [i3/i3#3912]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When a program is running fullscreen and a new window is added to the current workspace, the program will stay fullscreen, so you don't see the new window. 

## Desired Behavior

A configurable way to show the new window would be nice:
Maybe add an option similar to popup_during_fullscreen, called window_during_fullscreen?  

## Environment

<pre>
i3 version: 

Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17.1 (2019-08-30) (pid 1527)abort…)
Loaded i3 config: /home/bart/.config/i3/config (Last modified: ma 20 jan 2020 12:07:00 CET, 953 seconds ago)

The i3 binary you just called: /nix/store/844h8saa007wwsbvzp9f8arva2khzxfq-i3-4.17.1/bin/i3
The i3 binary you are running: /nix/store/844h8saa007wwsbvzp9f8arva2khzxfq-i3-4.17.1/bin/i3
</pre>

<pre>
- Linux Distribution & Version: NixOS 20.03 (Markhor) x86_64
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by Airblader** [comment]
I think this can be implemented as a script using the IPC. I don't want to close this issue yet but I'd currently tend towards recommending to just do that.

**Comment by magnetophon** [comment]
Thanks.  I looked trough the docs, and honestly it's a bit much for me to take in for creating this one function.
Good to know it's (probably) possible though!

**Comment by magnetophon** [comment]
Turns out it wasn't that hard to get what I wanted, plus a bit I didn't know I wanted:
This config:
```
hide_edge_borders smart
default_border pixel 1
default_floating_border normal 1

# enter fullscreen mode for the focused container
bindsym $Shift+F11 fullscreen
# fake-fulscreen everything
bindsym F11 exec --no-startup-id "~/.local/bin/FakeFullscreen.sh"
```
With this script:
```
#!/usr/bin/env bash

if [ "$(i3-msg -t get_bar_config bar-0 | grep dock)" ]; then
    i3 [class="^.*"]  border pixel && i3 bar mode invisible
else
    i3 [class="^.*"] border normal && i3 bar mode dock
fi
```

That works really nice: F11 turns off the statusbar and the title, so if it's the only window in the workspace it effectively goes fullscreen.
Also, this works globally.

I think I like that even more then what I thought I wanted, namely per workspace and with the current window going big even if it's not the only one on the desktop.  

The only issue I've seen with this so far is that new windows can't have the new border style without reloading the config.
Would that be a feature worth considering?

**Comment by Airblader** [comment]
> Turns out it wasn't that hard to get what I wanted

Great! :-) Given that this is easily achievable like this I think we can close this issue for now.

> The only issue I've seen with this so far is that new windows can't have the new border style without editing and reloading the config. Would that be a feature worth considering?

Sorry, I don't entirely follow(?)

I'll be closing but please feel free to keep commenting :-)

**Comment by magnetophon** [comment]
> Sorry, I don't entirely follow(?)

Well, I toggle the border of all existing windows between normal and pixel, but when I create  a new window it will just have whatever is set in the config as the default.
It'd be great if one could dynamically set ``default_border`` and ``default_floating_border``.

Would you consider adding that  feature?

**Comment by johantiden** [comment]
I ended up here from google. Just wanted to say that IntelliJ is a pain to use in fullscreen. I always have to move it so a separate workspace and do fake fullscreen hacks, similar to the one above. 

Some applications use popups _A LOT_, which makes them impossible to run in fullscreen.
