### ISSUE TITLE
Prepend "exec " to default i3bar_command

### ISSUE THREAD

**Issue by phy1729** [i3/i3#3925]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

The default `i3bar_command` leaves a useless shell process hanging around.

## Desired Behavior

The shell should `exec i3bar` so the end state does not have a useless shell without having to change the default.

It's a one line change which I've done at https://github.com/phy1729/i3/commit/a2cba79f9cdad5ea0db903d5610873706362e68d ; however, CONTRIBUTING.md instructs to open a feature request first.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
</pre>

<pre>
- Linux Distribution & Version: OpenBSD-snapshot
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by stapelberg** [comment]
Yeah, please send a PR for this.
