### ISSUE TITLE
Support for _KDE_NET_WM_WINDOW_TYPE_ON_SCREEN_DISPLAY

### ISSUE THREAD

**Issue by whitequark** [i3/i3#3937]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
EWMH notification windows can be matched with a rule like:

    [window_type="notification"]

However, KDE on-screen display windows currently cannot be matched with any rule, since i3 uses a hardcoded list of comparisons:

https://github.com/i3/i3/blob/225ebb0d588e57d7cdb4d8bd269f7f0b791c9368/src/match.c#L308-L331

This is inconvenient because the OSD windows steal focus even though none of them are interactive.

## Desired Behavior
KDE extended window types may be matched in some way. Either by extending the hardcoded list of window types, or by interning the provided string as an atom if it doesn't match the hardcoded list.

If the OSD windows can be matched, they can be used with `no_focus`, like I use `no_focus [window_type="notification"]` right now.

In the past this was addressed by extending the hardcoded list (#1969). I'll implement whichever approach the i3 maintainers think is appropriate here. There are currently [four KDE extended window types](https://code.woboq.org/qt5/kf5/kwindowsystem/src/platforms/xcb/netwm.cpp.html#1300) in total, at least one of which also seems useful to match in i3.

**Comment by Airblader** [comment]
i3 generally doesn't support DE specific extensions of the EWMH specs. The specs also state this:

> The Client SHOULD specify window types in order of preference (the first being most preferable) but MUST include at least one of the basic window type atoms from the list below. This is to allow for extension of the list of types whilst providing default behavior for Window Managers that do not recognize the extensions. — https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm45384480095168

I'm inclined to reject this as KDE should also set _NET_WM_WINDOW_TYPE_NOTIFICATION which would be sufficient for the match, and is in violation of they don't.

> In the past this was addressed by extending the hardcoded list (#1969).

Note that this was a spec'd basic type, not an extension.

> or by interning the provided string as an atom if it doesn't match the hardcoded list.

That would leak atom names into the config which we probably don't want to do.

**Comment by whitequark** [comment]
> I'm inclined to reject this as KDE should also set _NET_WM_WINDOW_TYPE_NOTIFICATION which would be sufficient for the match, and is in violation if they don't.

It looks like they don't set this window type because of what was probably a copy-paste error five years ago: https://github.com/KDE/kwindowsystem/blob/c284eacfda197d120955a59ec8f8db1172aecb4f/src/platforms/xcb/netwm.cpp#L3227-L3237

**Comment by Airblader** [comment]
Indeed looks that way. Can you raise this with KDE?

**Comment by whitequark** [comment]
Done: https://phabricator.kde.org/D27356

**Comment by UtkarshVerma** [comment]
@whitequark I'm new to phabricator, so I couldn't understand what was going on. Could you please tell me what's the status right now?
I also want to steal focus for the OSD windows.

**Comment by whitequark** [comment]
> Could you please tell me what's the status right now?

Looks like no one remembered to commit the patch. I pinged it.

**Comment by UtkarshVerma** [comment]
Since the commit is going to take time to reach the release, any way I can locally apply the patch to get my job done?

**Comment by orestisfl** [comment]
Thank you @whitequark. I'll close this.
