### ISSUE TITLE
Windows that were tiled found floating after screen unlock 

### ISSUE THREAD

**Issue by laynor** [i3/i3#3938]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
I am using i3 together with plasma, on a laptop with a secondary monitor setup with randr/autorandr. 
After the screen is locked for some time, one, some or all the main screen windows, which were tiled (tabbed layout), are found floating. The secondary screen windows usually keep their position/tiling. 

## Expected Behavior
Would like all the windows to be were I left them after unlocking.

## Reproduction Instructions

This always happens for me after the screen is left locked for some time (probably around 10 minutes).

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17.1 (2019-08-30) (pid 683) abort…)
Loaded i3 config: /home/ale/.config/i3/config (Last modified: Thu 13 Feb 2020 03:25:36 PM JST, 64791 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: /usr/bin/i3
</pre>

<pre>
# -*- mode: conf -*-
# i3 config file (v4)
#
# Please see http://i3wm.org/docs/userguide.html for a complete reference!
#

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:Segoe UI bold italic 9

workspace_layout tabbed # tabbed | tiling | stacking
exec sh ~/.fehbg
set $ws1 1: 
set $ws2 2:   (2)
set $ws3 3: >_ (3)
set $ws4 4: >_ (4)
set $ws5 5: >_ (5)
set $ws6 6: >_ (6)
set $ws7 7: >_ (7)
set $ws8 8: >_ (8)
set $ws9 9: >_ (9)
set $ws10 10: >_ (10)
exec i3-msg rename workspace 1 to $ws1
exec i3-msg rename workspace 2 to $ws2
exec i3-msg rename workspace 3 to $ws3
exec i3-msg rename workspace 4 to $ws4
exec i3-msg rename workspace 5 to $ws5
exec i3-msg rename workspace 6 to $ws6
exec i3-msg rename workspace 7 to $ws7
exec i3-msg rename workspace 8 to $ws8
exec i3-msg rename workspace 9 to $ws9
exec i3-msg rename workspace 10 to $ws10
client.focused #586e75 #586e75 #fdf6e3 #268bd2
client.focused_inactive #073642 #073642 #93a1a1 #002b36
client.unfocused #002b36 #002b36 #586e75 #002b36
client.urgent #dc322f #dc322f #fdf6e3 #dc322f

# -*- conf -*-
# use these keys for focus, movement, and resize directions when reaching for
# the arrows is not convenient
set $up k
set $down j
set $left h
set $right l
set $mod Mod4
set $i3dir ~/.i3

# use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# kill focused window
bindsym $mod+c kill

# rofi bindings
bindsym $mod+r exec rofi -show run
bindsym $mod+d exec rofi -show drun
bindsym $mod+w exec rofi -show window

# change focus
# bindsym $mod+$left focus left
set $move exec ~/.config/i3/scripts/sync-cursor.sh

bindsym $mod+$left  $move focus left
bindsym $mod+$down  $move focus down
bindsym $mod+$up    $move focus up
bindsym $mod+$right $move focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+$left move left
bindsym $mod+Shift+$down move down
bindsym $mod+Shift+$up move up
bindsym $mod+Shift+$right move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# bindkey $mod+Print exec spectacle

# split in horizontal orientation
bindsym $mod+Shift+s split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+Return fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+i layout stacking
bindsym $mod+u layout tabbed
bindsym $mod+o layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+minus floating toggle

# Switch to window
bindsym $mod+e [class="Emacs"] focus
bindsym $mod+t [class="konsole"] focus
bindsym $mod+f [class="Firefox"][instance="Navigator"] focus

# change focus between tiling / floating windows
bindsym $mod+minus focus mode_toggle

# focus the parent container
bindsym $mod+q focus parent

# focus the child container
bindsym $mod+a focus child

# move the currently focused window to the scratchpad
bindsym $mod+Shift+space move scratchpad

# Show the next scratchpad window or hide the focused scratchpad window.
# If there are multiple scratchpad windows, this command cycles through them.
bindsym $mod+space scratchpad show

# switch to workspace
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace $ws8
bindsym $mod+9 workspace $ws9
bindsym $mod+0 workspace $ws10
bindsym $mod+period workspace next
bindsym $mod+comma workspace prev

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5
bindsym $mod+Shift+6 move container to workspace $ws6
bindsym $mod+Shift+7 move container to workspace $ws7
bindsym $mod+Shift+8 move container to workspace $ws8
bindsym $mod+Shift+9 move container to workspace $ws9
bindsym $mod+Shift+0 move container to workspace $ws10

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym $left       resize shrink width 10 px or 10 ppt
        bindsym $down       resize grow height 10 px or 10 ppt
        bindsym $up         resize shrink height 10 px or 10 ppt
        bindsym $right      resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left        resize shrink width 10 px or 10 ppt
        bindsym Down        resize grow height 10 px or 10 ppt
        bindsym Up          resize shrink height 10 px or 10 ppt
        bindsym Right       resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape
        bindsym Return mode "default"
        bindsym Escape mode "default"
}

bindsym $mod+Shift+r mode "resize"

# display the window class with a notification
bindsym $mod+F1 exec ~/.i3/scripts/display-window-class.sh

#########################
# reload/restart/lock etc

set $rebuildConf exec python3 ~/.i3/i3wrapper.py
# reload the configuration file
bindsym $mod+Shift+c $rebuildConf reload

# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+p $rebuildConf restart

# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "qdbus org.kde.ksmserver /KSMServer logout -1 -1 -1"
bindsym $mod+Shift+m exec "xmodmap ~/.Xmodmap" # "DISPLAY=:1 xmodmap /home/ale/.Xmodmap"
# lock screen
bindsym $mod+semicolon exec "i3lock"

bindsym button4 nop
bindsym button5 nop

# -*- mode: conf -*-
# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
# bar {
#   # status_command i3status -c ~/.i3/i3status.conf | ~/.i3/net-speed.sh
#   status_command python3 ~/.i3/i3pystatusconf.py
#   tray_output primary
#   strip_workspace_numbers yes
#   colors {
#     separator #586e75
#     background #002b36
#     statusline #aea79f
#     focused_workspace #586e75 #586e75 #ffffff
#     active_workspace #073642 #073642 #ffffff
#     inactive_workspace #002b36 #002b36 #aea79f
#     urgent_workspace #77216f #77216f #ffffff
#   }
# }

for_window [class="Keepassx2" instance="keepassx2"] move scratchpad 
# for_window [title="Skype Preview"] floating disable
# for_window [title="Skype Preview"] move scratchpad
# for_window [class="Skype"] floating disable

for_window [title="Desktop — Plasma"] kill; floating enable; border none

## Avoid tiling popups, dropdown windows from plasma
# for the first time, manually resize them, i3 will remember the setting for floating windows
# for_window [class="plasmashell"] floating enable;
# for_window [class="Plasma"] floating enable; border none
# for_window [title="plasma-desktop"] floating enable; border none
# for_window [title="win7"] floating enable; border none
# for_window [class="krunner"] floating enable; border none
# for_window [class="Kmix"] floating enable; border none
# for_window [class="Klipper"] floating enable; border none
# for_window [class="Plasmoidviewer"] floating enable; border none

# no_focus [window_type=notification]
# no_focus [class="plasmashell" window_type="on_screen_display"]

exec xrdb ~/.Xresources
exec compton

#######################################################################
# automatically start i3-config-wizard to offer the user to create a
# keysym-based config which used their favorite modifier (alt or windows)
#
# i3-config-wizard will not launch if there already is a config file
# in ~/.i3/config.
#
# Please remove the following exec line:
#######################################################################
# exec i3-config-wizard

</pre>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5718278848643072.bz2
</pre>

<pre>
- Linux Distribution & Version: Arch linux, updated weekly
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by Airblader** [comment]
The log file spans some 12 hours or so. Can you create a log file with a fresh session for this issue and also note down the timestamps of when you lock and unlock? Also it would be helpful if you had as few windows open as possible and could tell us which one ended up floating. Thank you!

**Comment by duvholt** [comment]
`for_window [title="Desktop — Plasma"] kill; floating enable; border none`
This line should be 
`for_window [title="Desktop — Plasma"] kill, floating enable, border none`

From the [userguide](https://i3wm.org/docs/userguide.html#list_of_commands):
>When using multiple commands, separate them by using a , (a comma) instead of a semicolon. Criteria apply only until the next semicolon, so if you use a semicolon to separate commands, only the first one will be executed for the matched window(s).

In your config`floating enable; border none` is applied to the active window instead.

**Comment by Airblader** [comment]
Thanks for the catch. I'll close this on the suspicion of a config error but if the issue persists we can reopen, just let us know.
