### ISSUE TITLE
Mechanism for manipulating layout tree directly

### ISSUE THREAD

**Issue by uosis** [i3/i3#3962]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

`i3-msg -t get_tree` returns tons of very useful information, but it's all read-only.

## Desired Behavior

It would be nice if there was a way to manipulate the layout tree directly, without going through the commands designed for key bindings.

For example, moving/reparenting containers, renaming windows and containers, etc.

It would be even nicer if the layout tree could be mapped into a filesystem using FUSE, such that normal file manipulation tools could be used.

E.g. `mv /run/i3/layout/Display1/Workspace1/Container1/Container2/Window1 /run/i3/layout/Display2/Workspace2`.

**Comment by Airblader** [comment]
What about validation of the tree, or dealing with all the things that need to be done when renames or moves happen? This would mean significant complexity in the window manager to figure out how the layout has been changed and what actions to take.

**Comment by uosis** [comment]
I am not necessarily proposing an operation like `put_tree` that would take a new layout, diff it, and somehow figure out the changes needed. I agree that would mean considerable complexity, and it would probably not even be that useful.

I am proposing a set of more targeted operations, e.g. `move_container`, `rename_container`, etc. that would allow one to parse the layout tree, get container ids, and then directly manipulate them. E.g. `rename_container --id 123 --new_name foo` or `move_container --id 123 --child-of 456`. It would essentially be an extension of existing key binding commands, but rather than operating on active container, you could specify what to operate on.

And if going the FUSE route, it would be useful just to start with a read-only representation of the layout as files, and then support for specific modifications could be gradually added.

**Comment by Airblader** [comment]
From your examples I don't see anything that cannot be done by parsing the JSON tree and using the commands we have, or why the existing commands are not good enough for that. It certainly doesn't seem to justify adding an entirely different layer on top of what we have. What exactly makes this solution conceptually so much better that it would be justified?

**Comment by uosis** [comment]
This would primarily allow targeting commands to containers other than the currently focused container.

As is, after parsing the json tree, the only option is to focus the container of interest, apply desired changes to that container, and then restore focus.

Being able to directly target containers would significantly simplify scripting/automation.

**Comment by Airblader** [comment]
> As is, after parsing the json tree, the only option is to focus the container of interest, apply desired changes to that container, and then restore focus.

https://i3wm.org/docs/userguide.html#command_criteria ?

**Comment by uosis** [comment]
Indeed, I did not see that feature before. It effectively accomplishes the same thing I was proposing.

Thanks for pointing it out. I will close this issue since it's redundant.
