### ISSUE TITLE
Allow `for_window` to match against `WM_CLIENT_MACHINE`

### ISSUE THREAD

**Issue by tbraeutigam** [i3/i3#3981]
## I'm submitting a...
<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
`for_window` cannot match against `WM_CLIENT_MACHINE`

## Desired Behavior
Matching with `for_window` against `WM_CLIENT_MACHINE`.

## Use Case
When using lxc containers (or possibly other remote means) to start gui programs this match would allow to apply common rules to all windows launched from this remote instance.
This would be useful when running multiple instances of ie. firefox from different containers.

**Comment by Airblader** [comment]
SGTM

**Comment by iio7** [comment]
Could you please elaborate on this issue. I don't quite understand what it is you want achieved.

**Comment by tbraeutigam** [comment]
I'm using lxd containers for gui applications for a couple of reasons:
- logically separate programs. (Different profiles, different versions, different application sets)
- run different Network/VPN configs (company, private, adblocked, not adblocked)
- keeping the 'main' system clean and uncluttered
- easily reproducible, re-installable "system builds"

`WM_CLIENT_MACHINE` allows the easy identification of the origin of the application window, without having to resort to scripting to figure it out.

Using `[class="Firefox"]` would affect all instances of firefox.
Having `[WM_CLIENT_MACHINE="workcontainer" class="Firefox"]` would allow targeting a specific one.

And being able to apply some visual separation for all windows coming from a specific remote location is a big boon, too.

**Comment by orestisfl** [comment]
There is already a PR here https://github.com/i3/i3/pull/4007 that is almost ready. Since @xzfc is not very active in i3 lately, I will attempt to merge it myself.
