### ISSUE TITLE
feature request, accessing to unfocused windows in tiling layout

### ISSUE THREAD

**Issue by bigAmir** [i3/i3#3998]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
user can not remove the window borders for non-focused windows

## Desired Behavior
I'm requesting for a feature ( it could be a command in cfg file ) to access the unfocused windows and make changes
to their border.
What I wanna do is to disable window borders for "unfocused" windows in tiling layout. I tried to do it
by setting #00000000 for client.unfocused but it doesn't work well with tabbed layout.

## Environment
i3 version 4.18 (2020-02-18) © 2009 Michael Stapelberg and contributors

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.18 (2020-02-18) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18 (2020-02-18) (pid 733)to abort…)
Loaded i3 config: /home/amir/.config/i3/config (Last modified: Thu 09 Apr 2020 01:38:12 PM +0430, 844 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
- Linux Distribution & Version: ArchLinux
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

**Comment by orestisfl** [comment]
You can't disable tabbed titlebars: https://github.com/i3/i3/issues/2664, https://github.com/i3/i3/issues/2734.

For what you are asking for, you have to use an IPC script. For example: https://www.reddit.com/r/unixporn/comments/4mblsq/there_is_a_way_in_i3_to_active_the_border_only_in/d3u996z/

**Comment by Airblader** [comment]
In general you can send almost all commands against unfocused windows by using match criteria, though this may require writing a script. Therefore will be closing this issue. If there are further questions feel free to ask!

**Comment by bigAmir** [comment]
> You can't disable tabbed titlebars: #2664, #2734.
> 
> For what you are asking for, you have to use an IPC script. For example: https://www.reddit.com/r/unixporn/comments/4mblsq/there_is_a_way_in_i3_to_active_the_border_only_in/d3u996z/

ty, it does what I want. but I have another question
when I run the script it works, how should I use it ?
i did 
exec --no-startup-id ./borders.py
but it doesnt work, I have to manually run it. 
so, could u help me with that ?

**Comment by Airblader** [comment]
You need to pass a proper path to it, like /home/…/borders.py.

**Comment by bigAmir** [comment]
solved, ty.

**Comment by dabchinsky** [comment]
> You can't disable tabbed titlebars: [#2664](https://github.com/i3/i3/issues/2664), [#2734](https://github.com/i3/i3/issues/2734).
> 
> For what you are asking for, you have to use an IPC script. For example: https://www.reddit.com/r/unixporn/comments/4mblsq/there_is_a_way_in_i3_to_active_the_border_only_in/d3u996z/

this comment is deleted, please provide another solution
