### ISSUE TITLE
Set workspaces by number to specific output

### ISSUE THREAD

**Issue by angeelgod** [i3/i3#4021]
<pre>
[x] Bug (as seen on issue #3685, this should be default behaviour)
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Assigning a workspace to an specific output (i.e `workspace 6 output HDMI-1-1 eDP-1-1`) and renaming it at the same time it gets created (i.e using an external script to rename workspaces according to its content) ends up on i3 creating a new workspace with the same number but the new name (i.e `6:named`), moving original `6` workspace to HDMI-1-1 and keeping the new workspace on current screen (behavior previously documented on issue #3685 )
## Desired Behavior
Explicitly assign workspace by number to output on config files as to avoid conflicts between named and non-named workspaces, i.e:
- assign **all workspaces** with given number to specific output:
`workspace number 6 output HDMI-1-1`
- alternatively, assign specific named workspace to specific output:
`workspace 6:Browser output eDP-1-1`
This should end up on having all workspaces with number 6 on output HDMI-1-1 except for workspace 6:Browser (although having multiple workspaces with the same numbers shouldn't be a thing altogether)
## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.18 (2020-02-18) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18 (2020-02-18) (pid 632)to abort…)
</pre>

<pre>
- Linux Distribution & Version: Arch Linux, kernel 5.6.3-arch1-1
- Are you using a compositor (e.g., xcompmgr or compton): Yes, picom
</pre>

**Comment by orestisfl** [comment]
>     * alternatively, assign specific named workspace to specific output:
>       `workspace 6:Browser output eDP-1-1`
>       This should end up on having all workspaces with number 6 on output HDMI-1-1 except for workspace 6:Browser (although having multiple workspaces with the same numbers shouldn't be a thing altogether)

Doesn't this already work? https://i3wm.org/docs/userguide.html#workspace_screen

**Comment by orestisfl** [comment]
Also, please attach said script

**Comment by nedimlisica** [comment]
> > ```
> > * alternatively, assign specific named workspace to specific output:
> >   `workspace 6:Browser output eDP-1-1`
> >   This should end up on having all workspaces with number 6 on output HDMI-1-1 except for workspace 6:Browser (although having multiple workspaces with the same numbers shouldn't be a thing altogether)
> > ```
> 
> Doesn't this already work? https://i3wm.org/docs/userguide.html#workspace_screen

Using number keyword is not possible for choosing the screen. eg. this does not work:
```
workspace number 6 output HDMI-1-1
```
The desired behaviour here would be to support syntax above and allow choosing the output screen for workspaces whose names begin in a number regardless of the rest of the name.
Currently if a workspace is configured to screen using
```
workspace 1 output HDMI-1-1
```
and renamed to for example "1 web", reloading the wm will result in a new workspace named "1" getting created, which is not desired.

**Comment by orestisfl** [comment]
The part I am quoting is to assign a specific workspace name to an output and a number to a different output. See my link. Assigning by number is supported, just remove the 'number' token.

**Comment by nedimlisica** [comment]
That works, but problem is renaming workspace. Let's say workspace named "1" is assigned to HDMI1. Renaming it to eg. "1 web" makes i3 treat it as different workspace from that original "1" and if wm is reloaded, "1" is created again on HDMI1 and now two different workspaces exist, "1" and "1 web". Keyword "number" makes workspace switching key binds look at only the leading number in workspace name, so $mod + 1 will switch to "1 web" with no problems. We want the similar behaviour for output configuration, since currently renaming and assigning to the output don't play together.
```
workspace number 1 output HDMI1 LVDS1
```
So this should make workspace "1" open on HDMI, and make sure it gets moved back to it from LVDS1 in case that output was re-connected in the meantime, even thought it may have been renamed to somthing following the format of "1 new_name".
