### ISSUE TITLE
Some windows on the new open aren't centered, but every time opened in a new position.

### ISSUE THREAD

**Issue by funnydman** [i3/i3#4026]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When open for instance "Select Path" dialog it is opened normally but every next time it is opened in a new position.

## Expected Behavior

The floating windows should be centered, it works just fine on DE.

## Reproduction Instructions

How to reproduce https://www.youtube.com/watch?v=4p_ulX0fK0s&feature=youtu.be

## Environment

i3, the problem also appears on fresh Manjaro with i3 installation.
Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.18 (2020-02-18)
</pre>

<pre>
https://github.com/funnydman/my-dot-files/blob/master/.config/i3/config
</pre>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5642436940398592.bz2
</pre>

<pre>
- Linux Distribution & Version: Linux 5.4.32-1-lts
- Are you using a compositor (e.g., xcompmgr or compton): compton (picom)
</pre>

**Comment by funnydman** [comment]
Some guy on reddit provided a solution: https://www.reddit.com/r/i3wm/comments/g446yh/jumping_floating_windows_in_idea_with_i3/

**Comment by orestisfl** [comment]
The window seems to ask to be there. Can you perhaps ask the intelliji developers why it acts this way?
