### ISSUE TITLE
Switching between containers

### ISSUE THREAD

**Issue by yyy33** [i3/i3#4037]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When I switch to another container in full screen mode, the screen doesn't change, only the focus 
changes
One more question, if there is the ability to switch to the last container, I searched the user guide and found only the ability to switch to the last workspace

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: Binary i3 version:  4.18 (2020-02-18) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18 (2020-02-18) (pid 640)to abort…)
Loaded i3 config: /home/yyy/.config/i3/config (Last modified: Thu 23 Apr 2020 10:05:40 PM CST, 1081 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

</pre>

<pre>
- Linux Distribution & Version:
- Are you using a compositor (e.g., xcompmgr or compton):Linux x550vc-yyy 5.6.4-arch1-1 #1 SMP PREEMPT Mon, 13 Apr 2020 12:21:19 +0000 x86_64 GNU/Linux

</pre>

**Comment by orestisfl** [comment]
What's the feature request here?

Can you please describe in detail what you are trying to do?

**Comment by yyy33** [comment]
> What's the feature request here?
> 
> Can you please describe in detail what you are trying to do?

I found your answer record, it has been done using ipc. Thank you

**Comment by yyy33** [comment]
This is the solution for your reference

````
bindsym $mod+Left exec "FOCUSED=$(xprop -root _NET_ACTIVE_WINDOW | awk -F' ' '{print $NF}'); if xprop -id ${FOCUSED} _NET_WM_STATE | grep -q _NET_WM_STATE_FULLSCREEN; then i3-msg \\"[id=${FOCUSED}] fullscreen disable\\"; i3-msg \\"focus left\\"; i3-msg \\"fullscreen enable\\"; else i3-msg \\"focus left\\"; fi"
bindsym $mod+Down exec "FOCUSED=$(xprop -root _NET_ACTIVE_WINDOW | awk -F' ' '{print $NF}'); if xprop -id ${FOCUSED} _NET_WM_STATE | grep -q _NET_WM_STATE_FULLSCREEN; then i3-msg \\"[id=${FOCUSED}] fullscreen disable\\"; i3-msg \\"focus down\\"; i3-msg \\"fullscreen enable\\"; else i3-msg \\"focus down\\"; fi"
bindsym $mod+UP exec "FOCUSED=$(xprop -root _NET_ACTIVE_WINDOW | awk -F' ' '{print $NF}'); if xprop -id ${FOCUSED} _NET_WM_STATE | grep -q _NET_WM_STATE_FULLSCREEN; then i3-msg \\"[id=${FOCUSED}] fullscreen disable\\"; i3-msg \\"focus up\\"; i3-msg \\"fullscreen enable\\"; else i3-msg \\"focus up\\"; fi"
bindsym $mod+Right exec "FOCUSED=$(xprop -root _NET_ACTIVE_WINDOW | awk -F' ' '{print $NF}'); if xprop -id ${FOCUSED} _NET_WM_STATE | grep -q _NET_WM_STATE_FULLSCREEN; then i3-msg \\"[id=${FOCUSED}] fullscreen disable\\"; i3-msg \\"focus right\\"; i3-msg \\"fullscreen enable\\"; else i3-msg \\"focus right\\"; fi"

````

**Comment by orestisfl** [comment]
Great, thank you for letting us know!
