### ISSUE TITLE
i3 crashes after switching monitors and starting kodi

### ISSUE THREAD

**Issue by matejdro** [i3/i3#4039]
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

i3 crashes (dialog appears that asks me to press q to save backtrace, r to restart etc.)

## Expected Behavior

i3 shouldn't crash

## Reproduction Instructions

(This is probably unique to my monitor setup so I'm not sure if it is reproducible. Hopefully, stacktrace helps. Still, here are the steps).

I have a TV and 2 monitors plugged into my PC. By default TV is disabled and monitors are enabled.

1. Enable TV and disable two monitors (via `xrandr`)
2. Start kodi (https://kodi.tv/)
2. Disable TV and enable two monitors (via `xrandr`)
4. Stop kodi (`pkill kodi`)

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.18-238-g4d55bba7 (2020-04-22, branch "next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18-238-g4d55bba7 (2020-04-22, branch "next") (pid 7893)
Loaded i3 config: /home/matej/.config/i3/config (Last modified: pon 20 apr 2020 07:24:18, 522470 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: /usr/bin/i3

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: /usr/bin/i3
</pre>

<pre>
Default config (generated right before reproducing).
</pre>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5766310139002880.bz2
</pre>

<pre>
- Linux Distribution & Version: Manjaro
- Are you using a compositor (e.g., xcompmgr or compton): Happens both with picom started and without it.
</pre>

Stack trace: 
[i3-backtrace.6476.0.txt](https://github.com/i3/i3/files/4534736/i3-backtrace.6476.0.txt)

**Comment by orestisfl** [comment]
Is this something recent? Can you also reproduce with 4.18?

**Comment by orestisfl** [comment]
From your backtrace: `#8  0x0000564bef3189da in handle_configure_request (event=0x564bf1090530) at ../../i3/src/handlers.c:357` however, I don't see the message from line 356:
https://github.com/i3/i3/blob/4d55bba7/src/handlers.c#L356-L358
in your log. Are you sure that your log captured everything?

**Comment by matejdro** [comment]
This did not happen with 4.18, so I assume it is recent.

Not sure why the log was cut off, did it like this:

1. Reproduced the bug (got crash dialog)
2. Pressed Q (to save backstack)
3. Pressed R to restart i3
4. Opened terminal and dumped logs via `i3-dump-log`

**Comment by orestisfl** [comment]
> This did not happen with 4.18, so I assume it is recent.

If you are willing to bisect it would be very helpful. I understand if you don't want to invest the time though.

> Not sure why the log was cut off, did it like this:

Ok, can you do this instead:

- Reproduce the bug
- Run the command from the [docs](https://i3wm.org/docs/debugging.html#_obtaining_the_debug_logfile): `DISPLAY=:0 i3-dump-log | bzip2 -c | curl --data-binary @- https://logs.i3wm.org`. You can log in a different tty to do it or you can set a timer so that the command executes after the bug. However, do not restart i3 as it erases the logs.

**Comment by matejdro** [comment]
First bad commit is https://github.com/i3/i3/commit/ae757c6848b49d7a0423973a39791ba6eca29308 .

Full logs: https://logs.i3wm.org/logs/5634849780006912.bz2 (linked commit version, default config, instructions from above comment)

Also note that after crash happens and I restart i3 with windows preserved (R key), crash will not reproduce anymore until I fully restart i3. However, if I restart i3 with F key (full restart), crash can be reproduced immediately.

**Comment by orestisfl** [comment]
This helps a ton, thank you very much

**Comment by orestisfl** [comment]
This helps a ton, thank you very much

## Patch

Can you please check after this patch:

```diff
diff --git a/include/floating.h b/include/floating.h
index 8e60f78c..612874fc 100644
--- a/include/floating.h
+++ b/include/floating.h
@@ -25,7 +25,7 @@ typedef enum { BORDER_LEFT = (1 << 0),
  * floating_windows list of the workspace.
  *
  */
-void floating_enable(Con *con, bool automatic);
+bool floating_enable(Con *con, bool automatic);
 
 /**
  * Disables floating mode for the given container by re-attaching the container
diff --git a/src/floating.c b/src/floating.c
index 4fed43e4..7302f644 100644
--- a/src/floating.c
+++ b/src/floating.c
@@ -221,22 +221,22 @@ void floating_check_size(Con *floating_con, bool prefer_height) {
     }
 }
 
-void floating_enable(Con *con, bool automatic) {
+bool floating_enable(Con *con, bool automatic) {
     bool set_focus = (con == focused);
 
     if (con_is_docked(con)) {
         LOG("Container is a dock window, not enabling floating mode.\n");
-        return;
+        return false;
     }
 
     if (con_is_floating(con)) {
         LOG("Container is already in floating mode, not doing anything.\n");
-        return;
+        return false;
     }
 
     if (con->type == CT_WORKSPACE) {
         LOG("Container is a workspace, not enabling floating mode.\n");
-        return;
+        return false;
     }
 
     Con *focus_head_placeholder = NULL;
@@ -419,6 +419,7 @@ void floating_enable(Con *con, bool automatic) {
 
     floating_set_hint_atom(nc, true);
     ipc_send_window_event("floating", con);
+    return true;
 }
 
 void floating_disable(Con *con) {
diff --git a/src/handlers.c b/src/handlers.c
index ed3f6c3e..42dfb485 100644
--- a/src/handlers.c
+++ b/src/handlers.c
@@ -841,12 +841,13 @@ static void handle_client_message(xcb_client_message_event_t *event) {
              * let's float it and make it sticky. */
             DLOG("The window was requested to be visible on all workspaces, making it sticky and floating.\n");
 
-            floating_enable(con, false);
+            if(floating_enable(con, false)){
             con->floating = FLOATING_AUTO_ON;
 
             con->sticky = true;
             ewmh_update_sticky(con->window->id, true);
             output_push_sticky_windows(focused);
+            }
         } else {
             Con *ws = ewmh_get_workspace_by_index(index);
             if (ws == NULL) {
```

If that is not enough (I think it should be) also apply this one on top:
```diff
diff --git a/src/manage.c b/src/manage.c
index eecba95c..bc5c2bc4 100644
--- a/src/manage.c
+++ b/src/manage.c
@@ -537,8 +537,9 @@ void manage_window(xcb_window_t window, xcb_get_window_attributes_cookie_t cooki
          * was not specified */
         bool automatic_border = (motif_border_style == BS_NORMAL);
 
-        floating_enable(nc, automatic_border);
+        if(floating_enable(nc, automatic_border)){
         nc->floating = FLOATING_AUTO_ON;
+        }
     }
 
     /* explicitly set the border width to the default */
```

## Explanation from the logs

Plasma window that eventually causes the crash:
```
27. 04. 2020 07:24:39 - This window is of type dock
…
27. 04. 2020 07:24:39 - ipc.c:ipc_send_window_event:1610 - Issue IPC window new event (con = 0x556c8961bed0, window = 0x0240004a)
```

Sticky request here, after ae757c6 `FLOATING_AUTO_ON` is set regardless of the con_is_dock check that happens inside floating_enable:
```
27. 04. 2020 07:24:53 - handlers.c:handle_client_message:842 - The window was requested to be visible on all workspaces, making it sticky and floating.
27. 04. 2020 07:24:53 - Container is a dock window, not enabling floating mode.
```

Here is the configure request. This handles the window as floating instead of dock:
```
27. 04. 2020 07:25:02 - handlers.c:handle_configure_request:280 - window 0x0240004a wants to be at 2560x1296 with 1920x24
```

**Comment by matejdro** [comment]
I can confirm that applying the first patch works!
