### ISSUE TITLE
_NET_DESKTOP_VIEWPORT not consistent with get_workspaces after changing monitor configuration

### ISSUE THREAD

**Issue by patrick96** [i3/i3#4053]
## I'm submitting a…
<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
When rearranging monitors, the [`_NET_DESKTOP_VIEWPORT`](https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm44813837967616) EWMH property of the root window does not show the coordinates of the workspaces in the new configuration, it keeps the old value while `i3-msg -t get_workspaces` displays the correct coordinates. After switching workspaces the value is updated.

## Expected Behavior
At all times, the `_NET_DESKTOP_VIEWPORT` property on the root window should be consistent with the `rect.x` and `rect.y` coordinates of `i3-msg -t get_workspaces`.

## Reproduction Instructions

I first ran `xprop -root _NET_DESKTOP_VIEWPORT` and `i3-msg -t get_workspaces | jq` as my baseline measurements. The produced the following output:

```
_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 0, 1920, 0
```

and

```json
[
  {
    "id": 94250941275632,
    "num": 2,
    "name": "2: II",
    "visible": true,
    "focused": false,
    "rect": {
      "x": 0,
      "y": 0,
      "width": 1920,
      "height": 1061
    },
    "output": "HDMI-0",
    "urgent": false
  },
  {
    "id": 94250941272320,
    "num": 1,
    "name": "1: I",
    "visible": true,
    "focused": true,
    "rect": {
      "x": 1920,
      "y": 0,
      "width": 1920,
      "height": 1061
    },
    "output": "DP-3",
    "urgent": false
  }
]
```

Here the output is consistent. The DP-3 monitor is to the right of the HDMI-0 monitor.

I then ran `xrandr --output DP-3 --primary --below HDMI-0` to put DP-3 below HDMI-0.

And finally I ran the two commands I mentioned above again:

```
_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 0, 1920, 0
```

```json
[
  {
    "id": 94250941275632,
    "num": 2,
    "name": "2: II",
    "visible": true,
    "focused": false,
    "rect": {
      "x": 0,
      "y": 0,
      "width": 1920,
      "height": 1061
    },
    "output": "HDMI-0",
    "urgent": false
  },
  {
    "id": 94250941272320,
    "num": 1,
    "name": "1: I",
    "visible": true,
    "focused": true,
    "rect": {
      "x": 0,
      "y": 1080,
      "width": 1920,
      "height": 1061
    },
    "output": "DP-3",
    "urgent": false
  }
]
```

Now `xprop` tells me that the "second" workspace (workspace `I`, though it is listed as the second in the root window properties) is at `1920,0` while i3 correctly tells me it is at position `0,1080` below the other workspace.

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.18-259-gd7d4f0a9 (2020-05-01, branch "next") © 2009 Michael Stapelberg and contributors

Running version: < 4.2-200
</pre>

<details><summary>Config file</summary><pre>

</pre>

```
set $mod Mod4

set $ws1 "1: I"
set $ws2 "2: II"
set $ws3 "3: III"
set $ws4 "4: IV"
set $ws5 "5: V"
set $ws6 "6: VI"
set $ws7 "7: VII"
set $ws8 "8: VIII"
set $ws9 "9: IX"
set $ws10 "10: X"

font pango:monospace 8

# change focus
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right
bindsym $mod+h focus left

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right
bindsym $mod+Shift+h move left

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

bindsym $mod+Control+h focus output left
bindsym $mod+Control+l focus output right

# switch to workspace
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace $ws8
bindsym $mod+9 workspace $ws9
bindsym $mod+0 workspace $ws10

bindsym $mod+period workspace next_on_output
bindsym $mod+comma workspace prev_on_output
bar {
    strip_workspace_numbers yes
    status_command i3status
}
```

For completeness also my xinitrc file:

```
#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    # Source user xmodmap
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xset -b b off &
xset +fp /usr/share/fonts/local &
xset fp rehash &

~/.fehbg &
xbindkeys &
exec i3 --shmlog-size=26214400
```
</details>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5672210089902080.bz2
</pre>

<pre>
- Linux Distribution & Version: ArchLinux with kernel `5.6.7-arch1-1`
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by orestisfl** [comment]
Something is wrong with your version. How did you build i3?

Can you also reproduce with the latest commit from `next`?

**Comment by orestisfl** [comment]
Nevermind my previous comment

**Comment by orestisfl** [comment]
I don't have any extra monitors right now to reproduce (and I don't know how to fake it) but this could be an easy catch-al solution:

```diff
diff --git a/src/randr.c b/src/randr.c
index 56b0707fc..bdb1ce12e 100644
--- a/src/randr.c
+++ b/src/randr.c
@@ -1023,6 +1023,7 @@ void randr_query_outputs(void) {
     }
 
     /* render_layout flushes */
+    ewmh_update_desktop_properties();
     tree_render();
 
     FREE(primary);
```

Can you verify if it works?

**Comment by patrick96** [comment]
@orestisfl Yes, with the patch the window property is directly updated.

**Comment by patrick96** [comment]
Great, thanks for the fix :)
