### ISSUE TITLE
Scratchpad: show all contained windows

### ISSUE THREAD

**Issue by legendofa** [i3/i3#4056]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
`scratchpad show` currently cycles through the windows contained in the scratchpad.

## Desired Behavior
Additional option that allows `scratchpad show` to show all floating scratchpad windows at once.

This is useful for tools and should function as an overlay.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.18.1
</pre>

<pre>
- Linux Distribution & Version: Arch Linux 5.6.8
- Are you using a compositor (e.g., xcompmgr or compton): picom
</pre>

**Comment by orestisfl** [comment]
Try ` i3-msg '[class=.] scratchpad show'`

**Comment by legendofa** [comment]
This works, thank you.

Is it possible to prevent i3 from hiding new windows if an application in the scratchpad opens them?

**Comment by orestisfl** [comment]
If the window is hidden, no. If the window is visible it shouldn't hide it.

**Comment by orestisfl** [comment]
That said, I can't even reproduce the first case. "Transient for" window do not get hidden for me.

**Comment by legendofa** [comment]
This is a gif of the behaviour i've descibed, the about window should display above the main window.

I toggled the scratchpad with:
```
bindsym $mod+p [class=.] scratchpad show
```

![Peek 2020-05-02 15-57](https://user-images.githubusercontent.com/34162874/80866297-5ac6cc80-8c7d-11ea-8b98-dfc588ce9374.gif)
 
Also tried it with thunderbird with the same result.

**Comment by orestisfl** [comment]
Do you have any rules that trigger in your config file? If not, can you upload it somewhere please?

**Comment by legendofa** [comment]
I dont think so, my config is just the basic stuff.

[config.zip](https://github.com/i3/i3/files/4569911/config.zip)

**Comment by orestisfl** [comment]
Here is the problem: `for_window [class="(?i)pwsafe"] move scratchpad`

When you open the "About" window it gets matched and sent to the scratchpad. To deal with this, your `for_window` rule must be more specific e.g. also matching instance or name.

**Comment by legendofa** [comment]
When changing `for_window [class="(?i)pwsafe"]` to `for_window [class="pwsafe"]` the about window does not get sent to the scratchpad anymore, the problem now is that it also does not hide with the main window on the scratchpad toggle.

Is there a way to do this?

**Comment by orestisfl** [comment]
It does not hide because it isn't considered a scratchpad window. Maybe you can match that window so that you move it to the scratchpad and then show it immediately.

**Comment by legendofa** [comment]
I think this is not possible currently, maybe i could write a script as a workaround.

Someone else mentioned this on the i3wm Reddit. https://www.reddit.com/r/i3wm/comments/gzusn1/scratchpad_show_behavior/

**Comment by orestisfl** [comment]
What I am saying is possible and depends on the properties of the window. You can have criteria that match the main window but not the other dialogs.

**Comment by legendofa** [comment]
Can you give an example on how this would look like in a config?

This is my workaround so far.
https://github.com/legendofa/i3-scratchpad-overlay

**Comment by orestisfl** [comment]
I'll need the `xprop` output of both windows. I should have mentioned that earlier.

**Comment by legendofa** [comment]
[xprop_about.txt](https://github.com/i3/i3/files/4759592/xprop_about.txt)
[xprop_pwsafe.txt](https://github.com/i3/i3/files/4759593/xprop_pwsafe.txt)

**Comment by orestisfl** [comment]
I think you clicked on i3's decoration in pwsafe

**Comment by legendofa** [comment]
Yes, was wondering why the output was so short.
[xprop_pwsafe.txt](https://github.com/i3/i3/files/4759674/xprop_pwsafe.txt)

**Comment by orestisfl** [comment]
Ok, so here instance & class are equal, so you have to classify based on `WM_NAME`.

You can use `[class="Pwsafe" title="psafe\d$"]` for example because I see that the main window's title finishes with "psafe3" or `[class="Pwsafe" title="^PasswordSafe"]` because it starts with "PasswordSafe".

Alternatively, you can use negative lookaheads to unmatch the "about" window but I doubt that you only care about the "About" window specifically: https://faq.i3wm.org/question/7662/reverse-perl-matches-in-criteria-in-i3-config.1.html

**Comment by legendofa** [comment]
Thanks for your help, this is a lot more useful now. Still would like to see a mode where you can toggle all windows at once. I know that this is not what Scratchpad is meant to do, but i think people will put it in use as an overlay for multiple floating applications. Sort of like the Steam overlay.

**Comment by orestisfl** [comment]
But you can toggle all windows at once. What are you missing?

**Comment by legendofa** [comment]
`for_window [class="Pwsafe" title="^PasswordSafe"] move scratchpad` does not hide the window again on `[class=.] scratchpad show`.

**Comment by orestisfl** [comment]
Works correctly on my end. If you are still having trouble, please open a new bug issue with all needed information, including logs and reproduction instructions.
