### ISSUE TITLE
Only first command in for_window critera gets executed.

### ISSUE THREAD

**Issue by blueforesticarus** [i3/i3#4058]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
In this config line, the floating enabled command works, but the Notebook windows are not resized or moved.

> for_window [class="Notebook"]  floating enabled, resize set 1560 841, move 0 0 

## Expected Behavior

Notebook windows should open floating, resized and moved to the corner.

## Reproduction Instructions

Set the config line, restart i3, then open a window with that class by doing "kitty ---class Notebook" or something similar with your terminal.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version:  4.18.1 (2020-04-23)
</pre>

<pre>
Config: https://pastebin.com/SEAzzgwY
</pre>

<pre>
I have no idea if there is anything useful in here, but I turned on logging, ran "kitty --class Notebook" and then closed it with alt-q, then dumped then log.
Logfile URL: https://logs.i3wm.org/logs/5658801906647040.bz2
</pre>

<pre>
- Linux Distribution & Version: Arch Linux, up to date
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

**Comment by orestisfl** [comment]
`floating enabled` -> `floating enable`

**Comment by blueforesticarus** [comment]
That fixes it mostly. Now I have the issue that it is centering based on the original size rather than the new size (making it offcenter once resize takes effect).

However, I'm more concerned with what floating enabled was doing, since the documentation makes no mention of such an option, but it was making the windows float, and prevented the other options from working as described above. I tested with and without that for_window line, and with and without the "floating enabled part." The option is definately causing the window to be floating.

**Comment by orestisfl** [comment]
> However, I'm more concerned with what floating enabled was doing

Unfortunately, that's a quirk of the parser. It matches until the expected substring and then stops.

For `floating enableBLABLA` `floating enable` trigers the command and `BLABLA` is handled as a separate input.

**Comment by orestisfl** [comment]
> That fixes it mostly. Now I have the issue that it is centering based on the original size rather than the new size (making it offcenter once resize takes effect).

Can you specify this more? You are never trying to center your window according to your commands.

**Comment by blueforesticarus** [comment]
My bad, that was from a seperate config line.
I am no longer able to reproduce that second issue.
