### ISSUE TITLE
"exec-always" not working

### ISSUE THREAD

**Issue by viini42** [i3/i3#4062]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Reload i3 with super+shift+R and "exec-always" not working.

## Expected Behavior

Execute the "exec-always" instructions

## Reproduction Instructions

Set up an "exec-always" instructions like: `exec-always feh --bg-scale ~/Picture/some_image.png`.
Call the reload command (super+shift+R) and the 'feh' command not is called.

## Environment

Output of `i3 --moreversion 2>&-`:
```
Binary i3 version:  4.18.1 (2020-04-23) © 2009 Michael Stapelberg and contributors
(Getting version from running i3, press ctrl-c to abort…)
Running i3 version: 4.18.1 (2020-04-23) (pid 677)
Loaded i3 config: /home/vinicius-devel/.config//i3/config (Last modified: Sun 03 May 2020 02:41:44 AM -03, 3038 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3-with-/i3
```
<pre>
i3 version 4.18.1 (2020-04-23) © 2009 Michael Stapelberg and contributors
</pre>

<pre>
# i3 config file (v4)

# set modifier
set $super Mod4
set $alt Mod1

# set font
font pango: JetBrains Mono 10

# Use Mouse+$super to drag floating windows to their wanted position
floating_modifier $super

# Gaps
gaps inner 25
smart_gaps on
#gaps outer 15

#autostart
exec --no-startup-id picom --experimental-backends -b

# start a terminal
bindsym $super+Return exec i3-sensible-terminal

# start dmenu (a program launcher)
bindsym $super+Shift+d exec i3-dmenu-desktop --dmenu="dmenu -i -fn 'JetBrains Mono:size=8'"
bindsym $super+d exec rofi -show drun

# common apps keybinds
bindsym Print exec flameshot gui
bindsym $super+l exec i3lock -i ~/.dotfiles/lock-wallpaper

#change volume
# using pamixer
bindsym XF86AudioRaiseVolume exec pamixer -i 5
bindsym XF86AudioLowerVolume exec pamixer -d 5
bindsym XF86AudioMute exec pamixer -t

# music control
bindsym XF86AudioNext exec mpc next
bindsym XF86AudioPrev exec mpc prev
bindsym XF86AudioPlay exec mpc toggle
bindsym XF86AudioStop exec mpc stop

# kill focused window
bindsym $super+Shift+q kill
bindsym $alt+F4 kill

# change focus
bindsym $super+Left focus left
bindsym $super+Down focus down
bindsym $super+Up focus up
bindsym $super+Right focus right

# move focused window
bindsym $super+Shift+Left move left
bindsym $super+Shift+Down move down
bindsym $super+Shift+Up move up
bindsym $super+Shift+Right move right

# split in horizontal orientation
bindsym $super+h split h

# split in vertical orientation
bindsym $super+v split v

# enter fullscreen mode for the focused container
bindsym $super+f fullscreen toggle

# change container layout split
bindsym $super+s layout toggle split

# toggle tiling / floating
bindsym $super+space floating toggle

# change focus between tiling / floating windows
bindsym $super+Shift+space focus mode_toggle

# names for workspaces
# icons from <nerdfonts.com/cheat-sheet>
set $ws1 "| 1 ARCH  |"
set $ws2 "| 2 WEB  |"
set $ws3 "| 3 DEV  |"
set $ws4 "| 4 TERM  |"
set $ws5 "| 5 MEDIA  |"
set $ws6 "| 6 MISC  |"

# programs
exec-always feh --bg-scale ~/Picture/arch-light.png 

# switch to workspace
bindsym $super+Control+Right workspace next
bindsym $super+Control+Left workspace prev
bindsym $super+1 workspace $ws1
bindsym $super+2 workspace $ws2
bindsym $super+3 workspace $ws3
bindsym $super+4 workspace $ws4
bindsym $super+5 workspace $ws5
bindsym $super+6 workspace $ws6

# move focused container to workspace
bindsym $super+Shift+1 move container to workspace $ws1
bindsym $super+Shift+2 move container to workspace $ws2
bindsym $super+Shift+3 move container to workspace $ws3
bindsym $super+Shift+4 move container to workspace $ws4
bindsym $super+Shift+5 move container to workspace $ws5
bindsym $super+Shift+6 move container to workspace $ws6

# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $super+Shift+r restart

# exit i3
bindsym $super+Shift+e exec "i3-nagbar -t warning -m 'Really, exit?' -b 'Yes' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        bindsym Left resize shrink width 2 px or 2 ppt
        bindsym Down resize grow height 2 px or 2 ppt
        bindsym Up resize shrink height 2 px or 2 ppt
        bindsym Right resize grow width 2 px or 2 ppt
	    bindsym Shift+Left resize shrink width 6 px or 6 ppt
        bindsym Shift+Down resize grow height 6 px or 6 ppt
        bindsym Shift+Up resize shrink height 6 px or 6 ppt
        bindsym Shift+Right resize grow width 6 px or 6 ppt
        bindsym Return mode "default"
        bindsym Escape mode "default"
}
bindsym $super+r mode "resize"

# panel
bar {
        colors {
            background #2f343f
            statusline #2f343f
            separator #4b5262

            # colour of border, background, and text
            focused_workspace       #2f343f #bf616a #d8dee8
            active_workspace        #2f343f #2f343f #d8dee8
            inactive_workspace      #2f343f #2f343f #d8dee8
            urgent_workspacei       #2f343f #ebcb8b #2f343f
        }
        status_command i3status
        
}

# window rules, you can find the window class using xprop
for_window [class=".*"] border pixel 0
for_window [class=Lxappearance] floating enable
for_window [class=Sxiv] floating enable

# colour of border, background, text, indicator, and child_border
client.focused              #bf616a #2f343f #d8dee8 #bf616a #d8dee8
client.focused_inactive     #2f343f #2f343f #d8dee8 #2f343f #2f343f
client.unfocused            #2f343f #2f343f #d8dee8 #2f343f #2f343f
client.urgent               #2f343f #2f343f #d8dee8 #2f343f #2f343f
client.placeholder          #2f343f #2f343f #d8dee8 #2f343f #2f343f
client.background           #2f343f
</pre>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5714248793587712.bz2
</pre>

<pre>
- Linux Distribution & Version: `Arch Linux (5.6.8-arch1-1)`
- Are you using a compositor: `picom-ibhagwan-git 1379_Next.98.g68c8f1b_2020.04.26-1`
</pre>

**Comment by orestisfl** [comment]
According to your log, the command has been executed. Have you verified that it works in the command line?

**Comment by viini42** [comment]
> According to your log, the command has been executed. Have you verified that it works in the command line?

Yes, I saw the command in the log too, very strange.
But if I call the `feh` command from the command line, it works fine.

**Comment by orestisfl** [comment]
Can you redirect the output to some file please? Eg `exec-always feh --bg-scale ~/Picture/arch-light.png &> /tmp/out`

**Comment by viini42** [comment]
> Can you redirect the output to some file please? Eg `exec-always feh --bg-scale ~/Picture/arch-light.png &> /tmp/out`

I did insert this in config, save, restart (super shift R) and the `/tmp/out` wasn't created.
```console
❯ cat /tmp/out
cat: /tmp/out: No such file or directory
```

**Comment by viini42** [comment]
Another thing about this problem: my pictures folder is called `Pictures`, not `Picture`, if I call the wrong name in command line, the `feh` shows me an error. But in i3 restart, nothing appears being called.

Now I copy `Pictures` to `Picture` to continue with tests, but nothing is being done, nor the error message.

**Comment by orestisfl** [comment]
Ah finally found it `exec-always` should have been `exec_always`

**Comment by viini42** [comment]
Oh, I'm very embarrassed. Thank you, sorry for your time.

**Comment by orestisfl** [comment]
No worries. i3 could be more clear here and throw an error instead.

**Comment by orestisfl** [comment]
For the record, the technical reason why i3 doesn't throw an error here is that it matches `exec` and uses `-always feh …` as the actual command.

**Comment by jakob1379** [comment]
Just to necrobump things I do experience the exact described issue.
```
exec_always --no-startup-id "~/.i3/Scripts/feh-random-wallpaper"
```

Redirecting to output creates nothing and the command is run once at boot but not when restarting i3 with my restart i3 key.

**Comment by Airblader** [comment]
Please create a new issue and make sure to provide all required information. Thanks!
