### ISSUE TITLE
error another window manager seems to be running (x error 10)

### ISSUE THREAD

**Issue by mybigman** [i3/i3#4072]
## I'm submitting a…
<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
running
```i3 -c .confg/i3/config```

results in
```error another window manager seems to be running (x error 10)```

## Expected Behavior
validate the config

## Reproduction Instructions
startx
open terminal
run ```i3 -c .confg/i3/config```

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version:  Binary i3 version:  4.18.1 (2020-04-22)
</pre>

<details><summary>Config file</summary><pre>
same result in a fresh install / stock config
</pre>
</details>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5731026076696576.bz2
</pre>

<pre>
- Linux Distribution & Version: Fedora 32
- Are you using a compositor (e.g., xcompmgr or compton):  everything disabled
</pre>

**Comment by orestisfl** [comment]
What is in your ~/.xinitrc? You should execute i3 from that file.

**Comment by mybigman** [comment]
@orestisfl - I certainly execute it from .xinitrc with...

```
exec i3
```

**Comment by Airblader** [comment]
Then i3 is already running and attempting to run it again is bound to fail so this is behaving as expected. Validating the config is -C, not -c.

**Comment by mybigman** [comment]
@Airblader embarrassing... I guess that's what happens when you're playing at 2am :/

sorry for the dramas.

**Comment by ChuYanLon** [comment]
## ss
ssmdk
