### ISSUE TITLE
bindsym --press

### ISSUE THREAD

**Issue by mvrozanti** [i3/i3#4078]
##  I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior / Desired Behavior
`bindsym --release` exists but `bindsym --press` doesn't. `--press` could be added to immediately execute the desired command when key combination is just pressed _and not_ pressed and released.

**Comment by orestisfl** [comment]
This is the default behavior

**Comment by mvrozanti** [comment]
...but is it wanted behavior? Sorry I think I didn't catch that on your detailed response.

**Comment by orestisfl** [comment]
If `--release` is not used then the default behavior is like `--press`.
