### ISSUE TITLE
Support for nonprimary outputs

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [i3/i3#4083]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

I have several screens. But depending on what I do, I don't always set up the same one as primary.  I'm using a bar on each screen though. I set up the first one with `output primary` but I'd like to specify a bar for all secondary screens. Sot it would be great to have an option `outpout nonprimary` or `output secondary`.

## Desired Behavior

To be able to specify a bar for all nonprimary screens.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: Binary i3 version:  4.18 (2020-02-17) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18 (2020-02-17) (pid 9341)o abort…)
Loaded i3 config: /home/$USER/.config/i3/config (Last modified: jeu. 14 mai 2020 09:12:03 CEST, 1071 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

</pre>

<pre>
- Linux Distribution & Version: Ubuntu 18.04
- Are you using a compositor (e.g., xcompmgr or compton):
</pre>

**Comment by wlhlm** [comment]
This has been discussed as part of #2311, though I never came around to opening up a standalone issue. Here is an alternate explanation of the feature request with a different use case: https://github.com/i3/i3/issues/2311#issuecomment-213966121

**Comment by thiswillbeyourgithub** [comment]
Maybe another idea would be to allow ordering of outputs.

Say I have several `bar` section in my config file (one for each monitor). My laptop screen is my primary when it's my only screen but when I plug it into my bigger monitor, the latter becomes the primary. I have a bar for my primary monitor and one for my secondary.

Right now I am manually changing my line in the config file to tell the bar where to go.

Hence a solution would be to allow orders like so : 
```
bar { output HDMI2 edp1 # primary
bar { output HDMI2 edp1 # secondary
```
If the hdmi is connected : the first mentionned bar (here the primary) goes there, otherwise it goes to edp1. for the second line : given that HDMI2 has already been atributed a bar, it skips it and goes to edp1

if the hdmi is not connected : the first line skips HDMI2 and goes to edp1, the second line skips HDMI2 and skips edp1 because it has already a bar.


Does that help somehow?

Thanks!
