### ISSUE TITLE
i3bar: Status blocks on the left side

### ISSUE THREAD

**Issue by mox-mox** [i3/i3#4101]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
 i3bar shows the workspace buttons on the left, status output aligned to the right side of the screen.

## Desired Behavior
 There should be a way to tell i3bar to put some of the status output on the left or middle. E.g.:
```
{
	"version": 1,
	[
		[
			"align_left":
			[
				{
					"full_text": "E: 10.0.0.1 (1000 Mbit/s)",
					"color": "#00ff00"
				}
			],
			"align_right":
			[
				{
					"full_text": "2012-01-05 20:00:01"
				}
			]
		],
		...
	]
}

```

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version:  Binary i3 version:  4.18 (2020-02-17) © 2009 Michael Stapelberg and contributors
</pre>

<pre>
- Linux Distribution & Version: Archlinux (current)
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by mox-mox** [comment]
... and just now my search fu kicked in and I noticed there was aleady a somewhat similar request: #1148

**Comment by Airblader** [comment]
Thanks for opening this issue. #1148 is about as far as we'd want to go I think, the behavior described here is something I'd consider a bit too complex for i3bar. Closing in favor of #1148. Thanks for understanding!
