### ISSUE TITLE
Add dry run mode to i3-input

### ISSUE THREAD

**Issue by Arc676** [i3/i3#4103]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

The `i3-input` tool is extremely convenient for simple scripts that implement features that i3 doesn't provide on its own or shortcuts for common actions that require some string input (e.g. `"move container to workspace %s"`). However, the input is always interpreted as an i3 command; there is no way to simply use it as an all-purpose input dialog and there's no way to prevent the command from being sent to i3 after it is entered while also obtaining the input itself.

## Desired Behavior

It would be convenient for users (and possibly useful for developers) if there were a dry-run option that simply caused `i3-input` to skip over `ipc_send_message` and not send the command to i3. This would allow testing without actually running the command itself. In addition, it would mean that scripts could use `i3-input` to obtain text from the user. This is currently possible without any changes, but if that text is a valid i3 command, it will be executed, which is somewhat insecure.

If this feature is accepted, I'd be glad to implement it myself.

## Environment

i3 Version: 4.18.1 (2020-04-22)

**Comment by Airblader** [comment]
Thanks for the suggestion! i3-input isn't intended to be a general purpose input tool, it's largely a reference implementation for the IPC. I'm not much inclined to support such a use case as I think much better tool exists to capture input.

With regards to testing, you can just prepend "nop" which is an i3 command that won't do anything other than log the provided message.

**Comment by Arc676** [comment]
Thanks for the reply! I wasn't aware of the `nop` command; that definitely makes such a command line option superfluous.
