### ISSUE TITLE
Sometimes saved layouts don't capture certain programs

### ISSUE THREAD

**Issue by randomshinichi** [i3/i3#4105]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Sometimes, upon startup, `st -n everything` does not actually start `st`, and when I run that maually from another terminal, it doesn't go into my saved layout. I think it works once per reboot.

## Expected Behavior

It should work all the time, and if `st` doesn't start, it should tell me why.
## Reproduction Instructions

Reboot the computer. Log in with i3 once. It should work, keepassxc will start, st will start.
Log out, keepassxc will start and go into the layout, st will not start, and if you run `st -n everything`, it still won't go into the layout.

This has never happened to me with Thunderbird or KeepassXC. It might have happened once or twice with Quod Libet, but I am not so sure.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.18.1 (2020-04-22) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18.1 (2020-04-22) (pid 1765563)rt…)
Loaded i3 config: /home/shinichi/.config/i3/config (Last modified: So 24 Mai 2020 03:52:16 CEST, 524 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3-with-/i3

</pre>

<details><summary>Config file</summary><pre>
https://pastebin.com/raw/maUVptiJ
</pre>
<summary>Layout file</summary><pre>
{
  "border": "normal",
  "floating": "auto_off",
  "layout": "splith",
  "percent": 1,
  "type": "con",
  "nodes": [
    {
      "border": "normal",
      "floating": "auto_off",
      "layout": "splitv",
      "percent": 1,
      "type": "con",
      "nodes": [
        {
          "border": "normal",
          "floating": "auto_off",
          "layout": "tabbed",
          "percent": 1,
          "type": "con",
          "nodes": [
            {
              "border": "normal",
              "current_border_width": 2,
              "floating": "auto_off",
              "geometry": {
                "height": 1041,
                "width": 1916,
                "x": 0,
                "y": 0
              },
              "name": "Inbox - randomshinichi4869@gmail.com - Mozilla Thunderbird",
              "percent": 0.333333333333333,
              "swallows": [
                {
                  "class": "^Thunderbird$",
                  "instance": "^Mail$"
                }
              ],
              "type": "con"
            },
            {
              "border": "normal",
              "current_border_width": 2,
              "floating": "user_off",
              "geometry": {
                "height": 750,
                "width": 898,
                "x": 1663,
                "y": 168
              },
              "name": "pw.kdbx [Locked] - KeePassXC",
              "percent": 0.333333333333333,
              "swallows": [
                {
                  "class": "KeePassXC",
                  "instance": "keepassxc"
                }
              ],
              "type": "con"
            },
            {
              "border": "normal",
              "current_border_width": 2,
              "floating": "user_off",
              "geometry": {
                "height": 388,
                "width": 644,
                "x": 0,
                "y": 0
              },
              "name": "everything",
              "percent": 0.333333333333333,
              "swallows": [
                {
                  "class": "st-256color",
                  "instance": "everything"
                }
              ],
              "type": "con"
            }
          ]
        }
      ]
    }
  ]
}</pre>
</details>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5761026154823680.bz2
</pre>

<pre>
- Linux Distribution & Version: Arch Linux (I've had this bug for a long time already)
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by orestisfl** [comment]
In the logfile you linked st is called normally:

```
24.05.2020 03:52:39 - auto-starting st -n everything
24.05.2020 03:52:39 - executing: st -n everything
```

Can you redirect the output of the command somewhere and see if you get errors?

`exec --no-startup-id st -n everything &> /tmp/st.log`

**Comment by codebling** [comment]
I've noticed this to be true several Python apps with UIs, like [Brightness Controller](https://github.com/lordamit/Brightness) and [`cpupower-gui`](https://github.com/vagnum08/cpupower-gui). The layout seems to swallow them, but then the windows get unswallowed. I don't know that an i3 solution is possible to this. As a workaround, I've been making a delayed call to change the window name using `xprop` and swallowing the altered name. That seems to work.
