### ISSUE TITLE
i3bar: progressively shorten blocks when bar is too wide

### ISSUE THREAD

**Issue by ammgws** [i3/i3#4113]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
When the predicted bar width is too wide, i3bar will switch every block over to its `short_text` mode.

## Desired Behavior
When the predicted bar width is too wide, i3bar will progressively switch blocks over to `short_text` mode until the width requirement is satisfied. The idea is to use short_text only for the minimum of needed blocks.

Glancing over the code it seems doable, so I would be willing to give it a shot if this FR is accepted.

**Comment by GladOSkar** [comment]
I think this would be a very nice addition. Maybe it should be optional to avoid unexpected behavior for users of very narrow (vertical) screens who might want all blocks to be in short mode.

**Comment by orestisfl** [comment]
This seems like a strict upgrade that doesn't require any configuration so I don't see why not.

**Comment by Zocker1999NET** [comment]
This maybe could also be combined with a preference factor (of keeping full size) which can be given by the JSON api. Meaning that blocks with a lower preference value are tried to shorten before blocks with a higher preference value. To make the implementation easy, I would define that for each preference level used, it will be tried to gain enough place by only use `short_text` on blocks with this level or lower. If blocks with a higher preference need to use `short_text` as well, assume all blocks of the current selected level to use `short_text`, increase the level to the next one used and retry the same until all blocks must use `short_text`.

Would this also be feasible for i3bar? I can implement the preference part, I think, but could not easily build an efficient algorithm trying to shorten the minimum needed blocks (either with or without a preference value).

**Comment by Airblader** [comment]
I would like to avoid expanding the protocol.
