### ISSUE TITLE
Multiple flloating windows in fullscreen on same workspace cause issues

### ISSUE THREAD

**Issue by Celmor** [i3/i3#4124]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

With two fullscreened (media player) windows on same workspace the window doesn't respond correctly to input (mouse clicks, keyboard) while un-fullscreened via i3 hotkey doesn't work either, (double mouse-click allowed the player window to be un-fullscrened, although this behavior is specific to this player application).

## Expected Behavior

Application windows react to input correctly and let themselves un-fullscreen via i3. The the currently visible (foreground) window which is in fullscreen can be closed to make the 2nd fullscreen window "behind" it visible, still in fullscreen.

## Reproduction Instructions

Starting with 2 player windows open in a tiled format.
1. Set first window to float ($win+shift+space)
2. Move first window to secondary workspace/screen ($win+shift+2)
3. Fullscreen first window ($win+2; $win+f)
4. Set second window to float ($win+1; $win+shift+space)
5. Fullscreen second window ($win+f)
6. Move second window to secondary workspace/screen ($win+shift+2)
-> Result both windows were set to float and fullscreened on the same monitor overlapping each other, 

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.18.1 (2020-04-22)
</pre>
Dual-monitor setup, both 1440p using Nvidia driver (440.82-17).

<details><summary>Config file</summary>
-> default config file
</details>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5675353569755136.bz2
</pre>

<pre>
- Linux Distribution & Version: MANJARO (kernel: 5.6.15-1)
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by orestisfl** [comment]
Thanks, also affects moving the parent of a fullscreen container
