### ISSUE TITLE
Transfer workspaces to other screens on monitor disconnection

### ISSUE THREAD

**Issue by LiSongMWO** [i3/i3#4139]
## I'm submitting a…
<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
I have a laptop and an external DP monitor via a Thunderbolt dock. When I disconnect the laptop from the dock, all workspaces that were previously on the now disconnected monitor, remain on that now hidden/phantom monitor. I have to blindly cycle through all workspaces not on the laptop monitor and move all windows manually to get access to them.

## Desired Behavior
When I disconnect a monitor (xrandr event), all workspaces on that monitor are migrated to a previously bordering screen with ties broken in favour of the screen with bigger display size. Migrated workspaces would be marked with some form of status indicator, and when the monitor is reconnected the workspace automatically migrates back. This would facilitate more portability for laptops and docks.

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.18-1 (latest debian testing)
</pre>

<pre>
- Linux Distribution & Version: In-house Debian derivative.
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by orestisfl** [comment]
You can set up autorandr to do that. i3 just waits for your randr config to be updated, it does not act because it is not its place to do so.

Also see: https://unix.stackexchange.com/questions/4489/a-tool-for-automatically-applying-randr-configuration-when-external-display-is-p/171916
