### ISSUE TITLE
focus_follows_mouse behaviour even when it's turned off, after using flameshot

### ISSUE THREAD

**Issue by keysmashes** [i3/i3#4141]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When I run `flameshot gui` and close it (either by taking the screenshot or pressing escape), window focus should respect the `focus_follows_mouse no` in my config file.

## Expected Behavior

After I close the flameshot GUI, focus begins to follow the mouse until I focus another window by mouse _click_ or keyboard shortcut. i3's window decorations don't reflect where the focus actually is (i.e. if I have a floating window that's focused before I run flameshot, then move my mouse away from the floating window, it won't receive keystrokes any longer but i3 will still draw the focused-colour titlebar for it).

## Reproduction Instructions

- have focus_follows_mouse turned off
- install flameshot, and run the `flameshot` daemon
- open some windows
- run `flameshot gui`
- press escape
- notice that focus is suddenly following your mouse
- click or use keyboard shortcuts to focus a different window
- notice that focus no longer follows the mouse

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.18-330-gee2fa0c7d (2020-06-28, branch "no-bar-padding") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18-330-gee2fa0c7d (2020-06-28, branch "no-bar-padding") (pid 1920)
Loaded i3 config: /home/ash/.config/i3/config (Last modified: Sun 28 Jun 2020 01:49:25 BST, 681 seconds ago)

The i3 binary you just called: /usr/local/bin/i3
The i3 binary you are running: i3
</pre>
(this is a small patch on top of `next` (currently 025743eaf9c993e57c7fdd20127078b835bcd2c0), touching only `i3bar/src/xcb.c`)

<details><summary>Config file</summary><pre>
# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
# font pango:Roboto Sans 11
# font pango:Inter Regular 11
font pango:Jost* Book 11
title_align center

# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

# Increase the border width slightly to make resizing windows easier.
default_border normal 0
default_floating_border normal 0

# Default to tabbed layout.
workspace_layout tabbed

# # colours (gruvbox)
# set $bg #282828
# set $greyl #928374
# set $redd #cc241d
# set $redl #fb4934
# set $greend #98971a
# set $greenl #b8bb26
# set $yellowd #d79931
# set $yellowl #fabd2f
# set $blued #458588
# set $bluel #83a598
# set $purpled #b16286
# set $purplel #d3869b
# set $aquad #689d6a
# set $aqual #8ec07c
# set $greyd #a89984
# set $fg #ebdbb2
# set $bg0_h #1d2021
# set $bg0 $bg
# set $bg1 #3c3836
# set $bg2 #504945
# set $bg3 #665c54
# set $bg4 #7c6f64
# set $oranged #d65d0e
# set $orangel #fe8019
# set $bg0_s #32302f
# set $fg4 #a89984
# set $fg3 #bdae93
# set $fg2 #d5c4a1
# set $fg1 $fg
# set $fg0 #fbf1c7

# colours (gruvbox light)
set $bg #fbf1c7
set $greyd #928374
set $redl #cc241d
set $redd #9d0006
set $greenl #98971a
set $greend #79740e
set $yellowl #d79931
set $yellowd #b57614
set $bluel #458588
set $blued #076678
set $purplel #b16286
set $purpled #8f3f71
set $aqual #689d6a
set $aqud a#427b58
set $greyl #7c6f64
set $fg #3c3836
set $bg0_h #f9f5d7
set $bg0 #fbf1c7
set $bg1 #ebdbb2
set $bg2 #d5c4a1
set $bg3 #bdae93
set $bg4 #a89984
set $orangel #d65d0e
set $oranged #af3a03
set $bg0_s #f2e5bc
set $fg4 #7c6f64
set $fg3 #665c54
set $fg2 #504945
set $fg1 #3c3836
set $fg0 #282828

set $qpurple #662d91
set $qgreen #8dc63f
set $qorange #f7941d
set $qpink #ec008c

# class                 border   bg       text  indicator child_border
client.focused          $qgreen  $qgreen  $fg0  $qgreen   $qgreen
client.focused_inactive $bg1     $bg1     $fg0  $bg3      $bg2
client.unfocused        $bg2     $bg2     $fg0  $bg4      $bg3
client.urgent           $qorange $qorange $fg0  $qorange  $qorange
# client.focused          #aaaaaa  #e5e5e5  #000000  #aaaaaa    #aaaaaa
# client.focused_inactive #aaaaaa  #f0f0f0  #000000  #aaaaaa    #aaaaaa
# client.unfocused        #000000  #f0f0f0  #000000  #aaaaaa    #000000
# client.urgent           #e5e500  #e5e500  #000000  #aaaaaa    #e5e500

# Hide borders when there's only one window on a workspace
# hide_edge_borders smart
hide_edge_borders both

focus_follows_mouse no
focus_wrapping no
mouse_warping none

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec exec i3-sensible-terminal
# bindsym $mod+Return exec exec kitty
# bindsym $mod+Shift+Return exec dup-gnome-terminal

# kill focused window
bindsym $mod+Shift+q kill
bindsym button2 kill

# keyboard volume controls
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +5% && display-volume
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -5% && display-volume
bindsym Shift+XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +1% && display-volume
bindsym Shift+XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -1% && display-volume
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle && display-volume

# keyboard media controls
bindsym XF86AudioPrev exec --no-startup-id playerctl previous
bindsym XF86AudioPlay exec --no-startup-id playerctl play-pause
bindsym XF86AudioNext exec --no-startup-id playerctl next

# keyboard brightness controls
bindsym XF86MonBrightnessUp exec --no-startup-id lightctl inc 9; exec --no-startup-id sleep 0.05 && display-value $(lightctl get) brightness
bindsym XF86MonBrightnessDown exec --no-startup-id lightctl dec 9; exec --no-startup-id sleep 0.05 && display-value $(lightctl get) brightness
bindsym Shift+XF86MonBrightnessUp exec --no-startup-id lightctl inc 1; exec --no-startup-id sleep 0.05 && display-value $(lightctl get) brightness
bindsym Shift+XF86MonBrightnessDown exec --no-startup-id lightctl dec 1; exec --no-startup-id sleep 0.05 && display-value $(lightctl get) brightness

# start dmenu (a program launcher)
# bindsym $mod+d exec dmenu_run
bindsym $mod+d exec rofi -show run -display-window '' -display-run '' -display-ssh '' -display-drun ''
# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.
# bindsym $mod+Shift+d exec --no-startup-id i3-dmenu-desktop
bindsym $mod+Shift+d exec rofi -show drun -display-window '' -display-run '' -display-ssh '' -display-drun ''
# oh no
bindsym $mod+Menu exec bash -c 'set -o pipefail && out=$(2>&1 eval $(grep -v "^#" ~/src/bin/commands.list | rofi -dmenu -i -p "" | cut -f2-)) || notify-send "Task failed" "$out"'
bindsym $mod+Shift+Menu exec grep -v "^#" ~/src/bin/emoji.list | rofi -dmenu -i -p "copy emoji: " | cut -f1 | xclip2 -sel clip -rmlastnl

bindsym --release Print exec --no-startup-id screenshot ~/Pictures/Screenshots/"Screenshot from $(date '+%Y-%m-%d %H-%M-%S').png"
bindsym --release Ctrl+Print exec --no-startup-id screenshot | xclip -selection clipboard -t image/png
bindsym --release Shift+Print exec --no-startup-id screenshot -s ~/Pictures/Screenshots/"Screenshot from $(date '+%Y-%m-%d %H-%M-%S').png"
bindsym --release Ctrl+Shift+Print exec --no-startup-id screenshot -s | xclip -selection clipboard -t image/png
bindsym $mod+Print exec flameshot gui
exec exec flameshot

# See https://github.com/i3/i3/issues/2558
set $KP_0 Mod2+KP_0
set $KP_1 Mod2+KP_1
set $KP_2 Mod2+KP_2
set $KP_3 Mod2+KP_3
set $KP_4 Mod2+KP_4
set $KP_5 Mod2+KP_5
set $KP_6 Mod2+KP_6
set $KP_7 Mod2+KP_7
set $KP_8 Mod2+KP_8
set $KP_9 Mod2+KP_9

set $KP_0_Shift Shift+Mod2+KP_Insert
set $KP_1_Shift Shift+Mod2+KP_End
set $KP_2_Shift Shift+Mod2+KP_Down
set $KP_3_Shift Shift+Mod2+KP_Next
set $KP_4_Shift Shift+Mod2+KP_Left
set $KP_5_Shift Shift+Mod2+KP_Begin
set $KP_6_Shift Shift+Mod2+KP_Right
set $KP_7_Shift Shift+Mod2+KP_Home
set $KP_8_Shift Shift+Mod2+KP_Up
set $KP_9_Shift Shift+Mod2+KP_Prior

# Store clipboard
bindsym $mod+$KP_1_Shift exec --no-startup-id xclip2 -out -selection clipboard | xclip2 -selection buffer-cut -buffer 1
bindsym $mod+$KP_2_Shift exec --no-startup-id xclip2 -out -selection clipboard | xclip2 -selection buffer-cut -buffer 2
bindsym $mod+$KP_3_Shift exec --no-startup-id xclip2 -out -selection clipboard | xclip2 -selection buffer-cut -buffer 3
bindsym $mod+$KP_4_Shift exec --no-startup-id xclip2 -out -selection clipboard | xclip2 -selection buffer-cut -buffer 4
bindsym $mod+$KP_5_Shift exec --no-startup-id xclip2 -out -selection clipboard | xclip2 -selection buffer-cut -buffer 5
bindsym $mod+$KP_6_Shift exec --no-startup-id xclip2 -out -selection clipboard | xclip2 -selection buffer-cut -buffer 6
bindsym $mod+$KP_7_Shift exec --no-startup-id xclip2 -out -selection clipboard | xclip2 -selection buffer-cut -buffer 7

# Recall stored
bindsym $mod+$KP_1 exec --no-startup-id xclip2 -out -selection buffer-cut -buffer 1 | xclip2 -selection clipboard
bindsym $mod+$KP_2 exec --no-startup-id xclip2 -out -selection buffer-cut -buffer 2 | xclip2 -selection clipboard
bindsym $mod+$KP_3 exec --no-startup-id xclip2 -out -selection buffer-cut -buffer 3 | xclip2 -selection clipboard
bindsym $mod+$KP_4 exec --no-startup-id xclip2 -out -selection buffer-cut -buffer 4 | xclip2 -selection clipboard
bindsym $mod+$KP_5 exec --no-startup-id xclip2 -out -selection buffer-cut -buffer 5 | xclip2 -selection clipboard
bindsym $mod+$KP_6 exec --no-startup-id xclip2 -out -selection buffer-cut -buffer 6 | xclip2 -selection clipboard
bindsym $mod+$KP_7 exec --no-startup-id xclip2 -out -selection buffer-cut -buffer 7 | xclip2 -selection clipboard

# change focus
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right
bindsym $mod+Control+h focus output left
bindsym $mod+Control+j focus output down
bindsym $mod+Control+k focus output up
bindsym $mod+Control+l focus output right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right
bindsym $mod+Control+Left focus output left
bindsym $mod+Control+Down focus output down
bindsym $mod+Control+Up focus output up
bindsym $mod+Control+Right focus output right

# move focused window
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right
bindsym $mod+Shift+Control+h move container to output left; focus output left
bindsym $mod+Shift+Control+j move container to output down; focus output down
bindsym $mod+Shift+Control+k move container to output up; focus output up
bindsym $mod+Shift+Control+l move container to output right; focus output right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right
bindsym $mod+Shift+Control+Left move container to output left; focus output left
bindsym $mod+Shift+Control+Down move container to output down; focus output down
bindsym $mod+Shift+Control+Up move container to output up; focus output up
bindsym $mod+Shift+Control+Right move container to output right; focus output right

# split in horizontal orientation
bindsym $mod+bar split h

# split in vertical orientation
bindsym $mod+minus split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# Move the focused (floating) window to the centre of the screen.
bindsym $mod+Shift+grave move position center

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
bindsym $mod+z focus child

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws0 0
set $ws1 1
set $ws2 2
set $ws3 3
set $ws4 4
set $ws5 5
set $ws6 6
set $ws7 7
set $ws8 8
set $ws9 9

# default workspaces to particular monitors
workspace $ws0 output eDP-1 eDP-1-1 eDP1
workspace $ws1 output eDP-1 eDP-1-1 eDP1
workspace $ws2 output eDP-1 eDP-1-1 eDP1
workspace $ws3 output eDP-1 eDP-1-1 eDP1
workspace $ws4 output eDP-1 eDP-1-1 eDP1
workspace $ws5 output HDMI-2 HDMI-1-2 HDMI2
workspace $ws6 output HDMI-2 HDMI-1-2 HDMI2
workspace $ws7 output HDMI-2 HDMI-1-2 HDMI2
workspace $ws8 output HDMI-2 HDMI-1-2 HDMI2
workspace $ws9 output HDMI-2 HDMI-1-2 HDMI2
workspace 10 output HDMI-1 HDMI-1-1 HDMI1
workspace 11 output HDMI-1 HDMI-1-1 HDMI1
workspace 12 output HDMI-1 HDMI-1-1 HDMI1
workspace 13 output HDMI-1 HDMI-1-1 HDMI1
workspace 14 output HDMI-1 HDMI-1-1 HDMI1

# switch to workspace
bindsym $mod+0 workspace number $ws0
bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4
bindsym $mod+5 workspace number $ws5
bindsym $mod+6 workspace number $ws6
bindsym $mod+7 workspace number $ws7
bindsym $mod+8 workspace number $ws8
bindsym $mod+9 workspace number $ws9
bindsym $mod+bracketleft workspace prev
bindsym $mod+bracketright workspace next

# # bulk-switch to workspace
# bindsym $mod+F1 exec bulk-switch-workspace 0
# bindsym $mod+F2 exec bulk-switch-workspace 1
# bindsym $mod+F3 exec bulk-switch-workspace 2
# bindsym $mod+F4 exec bulk-switch-workspace 3
# bindsym $mod+F5 exec bulk-switch-workspace 4
# bindsym $mod+F6 exec bulk-switch-workspace 5
# bindsym $mod+F7 exec bulk-switch-workspace 6
# bindsym $mod+F8 exec bulk-switch-workspace 7
# bindsym $mod+F9 exec bulk-switch-workspace 8
# bindsym $mod+F10 exec bulk-switch-workspace 9
# bindsym $mod+F11 exec bulk-switch-workspace 10
# bindsym $mod+F12 exec bulk-switch-workspace 11

# nop out these
bindsym $mod+F1 exec true
bindsym $mod+F2 exec true
bindsym $mod+F3 exec true
bindsym $mod+F4 exec true
bindsym $mod+F5 exec true
bindsym $mod+F6 exec true
bindsym $mod+F7 exec true
bindsym $mod+F8 exec true
bindsym $mod+F9 exec true
bindsym $mod+F10 exec true
bindsym $mod+F11 exec true
bindsym $mod+F12 exec true

# move focused container
bindsym $mod+Shift+0 move container to workspace number $ws0; workspace number $ws0
bindsym $mod+Shift+1 move container to workspace number $ws1; workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2; workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3; workspace number $ws3
bindsym $mod+Shift+4 move container to workspace number $ws4; workspace number $ws4
bindsym $mod+Shift+5 move container to workspace number $ws5; workspace number $ws5
bindsym $mod+Shift+6 move container to workspace number $ws6; workspace number $ws6
bindsym $mod+Shift+7 move container to workspace number $ws7; workspace number $ws7
bindsym $mod+Shift+8 move container to workspace number $ws8; workspace number $ws8
bindsym $mod+Shift+9 move container to workspace number $ws9; workspace number $ws9

# bindings for "scratchpad" workspace
# bindsym $mod+m move scratchpad
bindsym $mod+o scratchpad show

# switch between workspaces
# bindsym Mod1+Tab workspace back_and_forth
# bindsym Mod1+Shift+Tab move container to workspace back_and_forth; workspace back_and_forth
# switch between workspaces on the current output
bindsym $mod+Tab exec backandforth
bindsym $mod+Shift+Tab exec i3-msg "move container to workspace $(backandforth -n)" && backandforth
exec_always --no-startup-id exec backandforthd
# switch between outputs
bindsym Mod1+Tab exec outputbackandforth
bindsym Mod1+Shift+Tab exec i3-msg "move container to output $(outputbackandforth -n)" && outputbackandforth
exec_always --no-startup-id exec outputbackandforthd

# bindsym Ctrl+Mod1+a exec keepass2 --auto-type

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"
# lock screen
bindsym $mod+Shift+f exec --no-startup-id lock
# lock screen and force it to turn off now
bindsym $mod+Shift+p exec --no-startup-id xset dpms force off && lock
# lock screen and suspend (need the delay in case the lockscreen is being regenerated)
bindsym $mod+Shift+BackSpace exec --no-startup-id "bash -c '{ sleep 10; test -e /tmp/screen-is-locked && sudo pm-suspend; } & lock'"

# bindsym $mod+r exec i3-input -P "Reminder (time message): " -F "exec --no-startup-id remind %s"
bindsym $mod+r exec --no-startup-id remind $(zenity --entry --text "Reminder (time message):" --title "New reminder" --width 400)

# # resize window (you can also use the mouse for that)
# mode "resize" {
#         # These bindings trigger as soon as you enter the resize mode

#         # Pressing left will shrink the window’s width.
#         # Pressing right will grow the window’s width.
#         # Pressing up will shrink the window’s height.
#         # Pressing down will grow the window’s height.
#         bindsym h resize shrink width 10 px or 5 ppt
#         bindsym j resize grow height 10 px or 5 ppt
#         bindsym k resize shrink height 10 px or 5 ppt
#         bindsym l resize grow width 10 px or 5 ppt

#         # same bindings, but for the arrow keys
#         bindsym Left resize shrink width 10 px or 5 ppt
#         bindsym Down resize grow height 10 px or 5 ppt
#         bindsym Up resize shrink height 10 px or 5 ppt
#         bindsym Right resize grow width 10 px or 5 ppt

#         # back to normal: Enter or Escape or $mod+r
#         bindsym Return mode "default"
#         bindsym Escape mode "default"
#         bindsym $mod+r mode "default"
# }
# bindsym $mod+r mode "resize"

set $mode_monitor monitor (hjklcp)
mode "$mode_monitor" {
        bindsym h move workspace to output left
        bindsym j move workspace to output down
        bindsym k move workspace to output up
        bindsym l move workspace to output right
        bindsym c move workspace to output current
        bindsym p move workspace to output primary

        bindsym Shift+h move container to output left
        bindsym Shift+j move container to output down
        bindsym Shift+k move container to output up
        bindsym Shift+l move container to output right
        bindsym Shift+c move container to output current
        bindsym Shift+p move container to output primary

        bindsym u exec --no-startup-id xrandr --output HDMI-2 --auto --above eDP-1
        bindsym d exec --no-startup-id xrandr --output HDMI-2 --off

        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+x mode "default"
}
bindsym $mod+x mode "$mode_monitor"

set $mode_shutdown "(l)ogout, (s)hutdown, (r)eboot"
mode $mode_shutdown {
        bindsym l exit
        bindsym r exec --no-startup-id systemctl reboot
        bindsym s exec --no-startup-id shutdown now
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+Escape mode "default"
}
bindsym $mod+Escape mode $mode_shutdown
# bindsym Control+Mod1+Delete exec --no-startup-id

set $mode_bluetooth "bluetooth: (e)nable, (d)isable"
# TODO: somehow add `rfkill -o SOFT -n list bluetooth` to this maybe idk
mode $mode_bluetooth {
        bindsym e exec rfkill unblock bluetooth; mode "default"
        bindsym d exec rfkill block bluetooth; mode "default"
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+Escape mode "default"
}
bindsym $mod+b mode $mode_bluetooth

set $transparent #00000000
set $translucent #28282855
# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        i3bar_command exec i3bar -t
        status_command exec i3status-rs ~/.config/i3status-rs/config.toml
        # Place application indicators on the display most likely to be in front of me.
        tray_output HDMI-1-2
        tray_output HDMI-2
        tray_output primary
        # Use a slightly larger font
        # font pango:Fira Code, Font Awesome 5 Pro, Font Awesome 5 Brands Regular 14
        font pango:Jost*, Source Sans Variable, Font Awesome 5 Pro, Font Awesome 5 Brands Regular 13
        # separator_symbol " "
        # tray_padding 2px
        colors {
                # class            border        bg            text
                focused_workspace  $qgreen       $qgreen       $fg
                active_workspace   $bg1          $bg1          $fg
                inactive_workspace #000000  #000000  $bg0
                urgent_workspace   $qorange      $qorange      $fg
                background $transparent
        }
}

assign [class="^Slack$"] → number $ws3
assign [class="^KeePass2$" title="^(?!Auto-Type Entry Selection$)"] → number $ws4
assign [class="^KeePassXC$" title="^(?!Auto-Type - KeePassXC$)"] → number $ws4

for_window [class="Eog"] floating enable
for_window [class="Ibus-ui-gtk3"] floating enable
for_window [class="Insync"] floating enable
for_window [class="Wine"] floating enable
for_window [class="jetbrains-toolbox"] floating enable
for_window [class="Mathpix Snipping Tool"] floating enable
for_window [class="Peek-run"] floating enable
for_window [class="Debconf-communicate"] floating enable
for_window [class="flameshot"] floating enable
# fuck off forever, steam updater
for_window [class="Steam" title="Steam - Self Updater"] floating enable, move scratchpad
# for_window [class="Steam" title="- event started"] floating enable, move scratchpad
for_window [title="Steam - System Information"] floating enable
for_window [title="Steam - News"] floating enable
for_window [class="steam" title="Steam Keyboard"] floating enable
for_window [class="Steam" title="Friends List"] floating enable
for_window [window_role="pop-up"] floating enable
# for_window [window_role="pref"] floating enable
for_window [title="Arc emulator"] floating enable

no_focus [title="Steam - Self Updater"]

# i3-gaps
# for_window [class="^.*"] border pixel 0
# gaps inner 4

# https://tribaal.io/using-i3.html
# Get the GTK theme, font, etc. set up
exec --no-startup-id exec unity-settings-daemon

# Make Polkit authentication dialogs work
exec --no-startup-id exec /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1

# Maybe make the login keyring be unlocked automatically??
# https://www.reddit.com/r/i3wm/comments/863l1j/gnomekeyring_in_i3/dw44qyc/
exec --no-startup-id exec gnome-keyring-daemon --start

# Compositor
# exec --no-startup-id sh -c 'if [ "$(nvctl gpu query)" = "intel" ]; then compton --config /dev/null --backend glx; fi'

# Tray icons
# NetworkManager
exec exec nm-applet
exec exec blueman-applet
# Audio tools
# exec exec volumeicon
# exec exec indicator-sound-switcher
# Insync
exec exec insync start
# JetBrains Toolbox
# exec ~/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox --minimize
# Password manager
# exec exec keepass2
# Configure Nvidia stuff???
exec --no-startup-id nvidia-settings --load-config-only
# Nvidia GPU control
exec exec ~/src/nv-applet/venv/bin/python -m nv_applet
# exec exec ~/src/totp-applet/venv/bin/python -m totp_applet
# Thermal monitoring, mostly
# exec psensor
# Screen colour shifting depending on the time of day
exec exec redshift-gtk
# Start snaps that should autostart (currently broken)
# exec --no-startup-id snap userd --autostart

exec --no-startup-id tail -f /var/log/Xorg.0.log | notify-grep nvLock

# Correctly position monitors etc.
exec --no-startup-id exec autorandr

# Show wallpaper
exec exec feh --bg-fill ~/Pictures/Wallpapers/default

# Wallpaper++
# exec --no-startup-id conky

# Shiny workspace names/icons
# exec_always --no-startup-id i3-workspace-names-daemon --pro

# Mount Keybase filesystem
# exec env KEYBASE_AUTOSTART=1 run_keybase

# Notifications about updates
exec exec update-notifier

# Lock the screen when idle.
# exec --no-startup-id xautolock -locker lock -time 10 -detectsleep
# Lock the screen on suspend.
# exec --no-startup-id xss-lock dm-tool lock

# Increase speed of keyboard repeat
exec --no-startup-id xset r rate 230 30
# Make sure the volume is sane to start with
exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ 40%
# Enable compose key
# https://unix.stackexchange.com/questions/108207/how-to-map-caps-lock-as-the-compose-key-using-xmodmap-portably-and-idempotently
# https://askubuntu.com/questions/23491/how-to-change-capslock-key-to-produce-a
# exec --no-startup-id xmodmap ~/.Xmodmap
# Delete old files from the trash.
exec --no-startup-id trash-empty 15

# vim: set sw=8 et:
</pre>
</details>

Logfile URL: https://logs.i3wm.org/logs/5642890529210368.bz2

- Linux Distribution & Version: Ubuntu 18.04
- Are you using a compositor (e.g., xcompmgr or compton): yes, picom (though the problem occurs without it running)

Maybe this is related to lupoDharkael/flameshot#58? Or xmonad/xmonad#218 seems similar.

**Comment by orestisfl** [comment]
Closing because this seems to be an issue with flameshot: https://github.com/flameshot-org/flameshot/issues/784

**Comment by keysmashes** [comment]
and yet:

![image](https://github.com/i3/i3/assets/9433472/034fb0fb-dcf6-4ef3-bf73-6039526bff17)

I don't understand how a Flameshot bug could cause i3 to suddenly apply behaviour contrary to a line of my config.

**Comment by orestisfl** [comment]
The way I read the issue, multiple window managers are having the exact same issue. If there is any constructive suggestion on how i3 could handle this situation better, we could certainly consider it.

**Comment by orestisfl** [comment]
> I don't understand how a Flameshot bug could cause i3 to suddenly apply behaviour contrary to a line of my config.

I don't think `focus_follow_mouse` has anything to do with it. In fact, it's quite easy to remove all `focus_follow_mouse` code from i3 and see that the behavior is still the same, here's a patch if you want to play around:

```diff
diff --git a/include/configuration.h b/include/configuration.h
index 19d2f714..c46cd681 100644
--- a/include/configuration.h
+++ b/include/configuration.h
@@ -119,12 +119,6 @@ struct Config {
     /** Default orientation for new containers */
     int default_orientation;
 
-    /** By default, focus follows mouse. If the user explicitly wants to
-     * turn this off (and instead rely only on the keyboard for changing
-     * focus), we allow them to do this with this relatively special option.
-     * It is not planned to add any different focus models. */
-    bool disable_focus_follows_mouse;
-
     /** By default, when switching focus to a window on a different output
      * (e.g. focusing a window on workspace 3 on output VGA-1, coming from
      * workspace 2 on LVDS-1), the mouse cursor is warped to the center of
diff --git a/src/config_directives.c b/src/config_directives.c
index 36154ce3..eb1f5318 100644
--- a/src/config_directives.c
+++ b/src/config_directives.c
@@ -429,7 +429,6 @@ CFGFUN(hide_edge_borders, const char *borders) {
 }
 
 CFGFUN(focus_follows_mouse, const char *value) {
-    config.disable_focus_follows_mouse = !boolstr(value);
 }
 
 CFGFUN(mouse_warping, const char *value) {
diff --git a/src/handlers.c b/src/handlers.c
index c583dade..cebf8e2c 100644
--- a/src/handlers.c
+++ b/src/handlers.c
@@ -89,35 +89,7 @@ bool event_is_ignored(const int sequence, const int response_type) {
  *
  */
 static void check_crossing_screen_boundary(uint32_t x, uint32_t y) {
-    Output *output;
-
-    /* If the user disable focus follows mouse, we have nothing to do here */
-    if (config.disable_focus_follows_mouse) {
-        return;
-    }
-
-    if ((output = get_output_containing(x, y)) == NULL) {
-        ELOG("ERROR: No such screen\n");
-        return;
-    }
-
-    if (output->con == NULL) {
-        ELOG("ERROR: The screen is not recognized by i3 (no container associated)\n");
-        return;
-    }
-
-    /* Focus the output on which the user moved their cursor */
-    Con *old_focused = focused;
-    Con *next = con_descend_focused(output_get_content(output->con));
-    /* Since we are switching outputs, this *must* be a different workspace, so
-     * call workspace_show() */
-    workspace_show(con_get_workspace(next));
-    con_focus(next);
-
-    /* If the focus changed, we re-render to get updated decorations */
-    if (old_focused != focused) {
-        tree_render();
-    }
+    return;
 }
 
 /*
@@ -171,27 +143,6 @@ static void handle_enter_notify(xcb_enter_notify_event_t *event) {
             }
         }
     }
-
-    if (config.disable_focus_follows_mouse) {
-        return;
-    }
-
-    /* if this container is already focused, there is nothing to do. */
-    if (con == focused) {
-        return;
-    }
-
-    /* Get the currently focused workspace to check if the focus change also
-     * involves changing workspaces. If so, we need to call workspace_show() to
-     * correctly update state and send the IPC event. */
-    Con *ws = con_get_workspace(con);
-    if (ws != con_get_workspace(focused)) {
-        workspace_show(ws);
-    }
-
-    focused_id = XCB_NONE;
-    con_focus(con_descend_focused(con));
-    tree_render();
 }
 
 /*
@@ -215,44 +166,6 @@ static void handle_motion_notify(xcb_motion_notify_event_t *event) {
         check_crossing_screen_boundary(event->root_x, event->root_y);
         return;
     }
-
-    if (config.disable_focus_follows_mouse) {
-        return;
-    }
-
-    if (con->layout != L_DEFAULT && con->layout != L_SPLITV && con->layout != L_SPLITH) {
-        return;
-    }
-
-    /* see over which rect the user is */
-    if (con->window != NULL) {
-        if (rect_contains(con->deco_rect, event->event_x, event->event_y)) {
-            /* We found the rect, let’s see if this window is focused */
-            if (TAILQ_FIRST(&(con->parent->focus_head)) == con) {
-                return;
-            }
-
-            con_focus(con);
-            x_push_changes(croot);
-            return;
-        }
-    } else {
-        Con *current;
-        TAILQ_FOREACH_REVERSE (current, &(con->nodes_head), nodes_head, nodes) {
-            if (!rect_contains(current->deco_rect, event->event_x, event->event_y)) {
-                continue;
-            }
-
-            /* We found the rect, let’s see if this window is focused */
-            if (TAILQ_FIRST(&(con->focus_head)) == current) {
-                return;
-            }
-
-            con_focus(current);
-            x_push_changes(croot);
-            return;
-        }
-    }
 }
 
 /*
```
