### ISSUE TITLE
i3bar unhide when network availability changes, or other problems

### ISSUE THREAD

**Issue by al-caveman** [i3/i3#4142]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

when the bar is configured to be "hide", it re-appears only if:

* some tile gets alerted, then the i3bar unhides to show the workspace with alert in it (good).
* when i press MOD (good).

but it does _not_ re-appear when:

* network availability by i3status changes (bad).
* available ram falls below limit (bad).
* load exceeds limit (bad).

feature request:

* allow for possibility to re-appear i3bar with those 3 extra points.

**Comment by orestisfl** [comment]
i3bar has no knowledge of ram, load or i3status state. For this reason, this feature request is out of scope.

You can externally show the bar according to your criteria.

**Comment by al-caveman** [comment]
can't it get an alert from i3status, and represent the alert by means of unhiding?

i didn't say that i3bar should have knowledge of ram/load/network.  but since i3bar is reading stdin from i3status, imo it's a lil change to make in i3bar and i3status to let i3status tell i3bar _"hey, unhide!  somethin weird just happened!"_

**Comment by Airblader** [comment]
I think we have been pretty clear that you are no longer welcome in the i3 community.
