### ISSUE TITLE
feature request: show mark in title

### ISSUE THREAD

**Issue by elig0n** [i3/i3#4176]
I'm looking to show a mark (if exists) in the client title. 
I was surprised there isn't something like %mark for title_format

**Comment by Airblader** [comment]
There's show_marks, which is also enabled by default. Supporting a %marks placeholder comes with the issue of formatting the marks which likely users would have different preferences for. I'd be curious why the current way of having them shown isn't sufficient though if you could elaborate :-)

**Comment by Airblader** [comment]
Also note that window marks are an array, not a single mark per window. Otherwise the formatting would be no issue and supporting %mark would be easy.

**Comment by elig0n** [comment]
hmm I must have missed that somehow ... :-) 
I have no further remarks regarding marks as the current format seems sufficient enough for me but since title can be positioned along left/right/center it might be nice if marks could too (when there are no conflicts of course)...
