### ISSUE TITLE
Icons in json protocol for i3bar.

### ISSUE THREAD

**Issue by eleksir** [i3/i3#4177]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Right now i3bar does not implemet any icons at all, except tray ones.
## Desired Behavior

The idea is to supply any valid path to supported image format of icon and use it for (resizing and) embedding into displayed text. Can be useful for labels and indicators (sound volume, signal strength/quality, charge in battery, etc).

I'm not sure that it should be constantly transferred to bar, but maybe on state change | update.

I'm not sure that it worth to implement icons as base64 encoded images embedded into i3bar json proto. I think that this is a bad idea.

This idea have something in common with https://github.com/i3/i3/issues/3578 Looks like i suggesting persistent state mechanics that should be avoided because of complexity, because of potential growth of memory footprint and other resource hog (check perms of files, read images, etc).

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
Binary i3 version:  4.18.2 (2020-07-26) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18.2 (2020-07-26) (pid 41482)bort…)
Loaded i3 config: /home/sfedosov/.config/i3/config (Last modified: Вт 09 июн 2020 16:47:53, 5953454 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
- Linux Distribution & Version: any
- Are you using a compositor (e.g., xcompmgr or compton): not applicable
</pre>

**Comment by Airblader** [comment]
The common way to do this is using an icon font and I don't see much of a reason that we need anything else. For the presented use cases that seems sufficient to me.

**Comment by eleksir** [comment]
So, you suggest to embed telegram, slack, firefox... etc all required icons to specially crafted font?
But can you give me a (link) tool that makes this task easy to complete? by the way - i'd like to retain full palette of icons to easy recognize them on i3bar, is it possible?

**Comment by Airblader** [comment]
There are popular icon fonts out there already, for example Font Awesome. I personally use that as well.
