### ISSUE TITLE
Allow for_window rules to be removed

### ISSUE THREAD

**Issue by danieldg** [i3/i3#4182]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
for_window and similar rules stick around until a reload

## Desired Behavior
Rules can be removed after they are no longer needed (for example, having a launcher add and remove pid-based rules for a process before launching and after it exits - right now, you just have to hope PID reuse never happens).

**Comment by rpigott** [comment]
> for example, having a launcher add and remove pid-based rules

i3 does not support pid criteria. The user guide contains a [list of supported criteria attributes](https://i3wm.org/docs/userguide.html#command_criteria).

**Comment by ammgws** [comment]
I'm guessing this is so that it will be implemented in sway by getting it in i3 first

**Comment by stapelberg** [comment]
> Rules can be removed after they are no longer needed

But i3 can’t know when a rule is no longer needed.

It seems clearer to me to instruct i3 to reload its config (which you modify programmatically beforehand) to pick up changes to these rules.
