### ISSUE TITLE
Stop raising windows whenever i3 wants

### ISSUE THREAD

**Issue by gsstark** [i3/i3#4183]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
I noticed when I click on a floating window it jumps to the top of the stack obscuring other windows. I know this is popular behaviour in Windows and Mac but it seems out of place in a Unix environment, especially in a tiling window manager meant for power users.

## Desired Behavior

I want to explicitly control the stacking orthogonally to the focus. That is, I want a key binding to raise or lower the current window and unless I press those bindings I don't want i3 randomly raising or lowering windows based on any heuristics.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
bash-4.2$ i3 --moreversion
Binary i3 version:  4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12 (2016-03-06, branch "4.12") (pid 16333)
Loaded i3 config: /home/stark/.config/i3/config (Last modified: Fri 14 Aug 2020 11:52:56 AM EDT, 1120325 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

</pre>

<pre>
- Linux Distribution & Version:
- Are you using a compositor (e.g., xcompmgr or compton):
</pre>
CentOS Linux release 7.8.2003 (Core)

**Comment by Airblader** [comment]
Thanks for the request, but floating windows are not intended to be heavily used in i3 (we're a tiling window manager). If you find yourself using so many floating windows obscuring each other that you'd have to manage the stack, I'd argue i3 is not being used the intended way. As such I'd like to keep this kind of complexity out of i3. Thanks for understanding!
