### ISSUE TITLE
Add a dummy command

### ISSUE THREAD

**Issue by gorsheninmv** [i3/i3#4187]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

I came here from the sway project to propose the feature because it don`t accept any features unless they get implemented by i3.
It would be nice to have a dummy command to get ability handling custom bind events via IPC.

I would like to show you the [example](https://gist.github.com/gorsheninmv/7288193786a2f1344367ed5171983e47).
I implemented the script to swap two containers and used mark workaround to achieve that.
If the dummy command feature were implemented I could listen to the bind dummy command event with "swap" argument and handle it by avoiding using the mark workaround.

**Comment by orestisfl** [comment]
Does either [nop](https://i3wm.org/docs/userguide.html#_nop) or [tick](https://i3wm.org/docs/ipc.html#_sending_messages_to_i3) do what you want?

**Comment by gorsheninmv** [comment]
> Does either [nop](https://i3wm.org/docs/userguide.html#_nop) or [tick](https://i3wm.org/docs/ipc.html#_sending_messages_to_i3) do what you want?

Yes, you`re right. Nop works fine. I was mislead by the nop command description that its optional argument is ingored.
Thanks!

**Comment by orestisfl** [comment]
Happy to help!
