### ISSUE TITLE
Always show titlebar in tabbed/stacked layout

### ISSUE THREAD

**Issue by miseran** [i3/i3#4190]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Currently, when titlebars are disabled, a tabbed or stacked container will show a titlebar only when it has multiple children.

## Desired Behavior

For the sake of consistency, and to avoid the window size changing whenever the second tab is added or removed, I would like to have an option to always show the titlebar in tabbed and stacked containers, even when it is otherwise disabled.

If there is interest, I can try writing a pull request.

**Comment by stapelberg** [comment]
> For the sake of consistency, and to avoid the window size changing whenever the second tab is added or removed, I would like to have an option to always show the titlebar in tabbed and stacked containers, even when it is otherwise disabled.

When you disable title bars, i3 only shows title bars when necessary to disambiguite what’s on the screen.

I don’t think we should change this behavior—existing users are used to it, and I like the simple-to-understand model of when to expect title bars. Let’s not make it more complicated.
