### ISSUE TITLE
Focus specific numbered window in each workspace

### ISSUE THREAD

**Issue by malta895** [i3/i3#4191]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Only workspaces are reachable with `$mod+n` key binding.

## Desired Behavior
I'd like to be able set a key bind to focus each specific window, exactly like workspaces currently work (e.g. go to workspace 2 with `$mod+2`, focus to window 2 with `$mod+ctrl+2`).

For this purpose, all the windows in each workspace should be incrementally numbered from 1 to 10, to be uniquely identifiable, and each identifier should be visible on each window to identify it, for example right-aligned on the title bar, or it could be visible at the center of each window while keeping pressed `$mod` .

The user should able to activate/deactivate this feature from the config file

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
Binary i3 version:  4.18.2 (2020-07-26) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18.2 (2020-07-26) (pid 41968)bort…)
Loaded i3 config: /home/malta/.config/i3/config (Last modified: mer 2 set 2020, 22:30:40, 2885 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
- Linux Distribution & Version: Arch Linux 2020-09-01
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by davvil** [comment]
Have a look at [this script](https://github.com/davvil/dotfiles/blob/master/.config/i3/autotag.py) for tagging the windows. You then only need to bind keys for jumping to the corresponding marks ([example](https://github.com/davvil/dotfiles/blob/c4e8c7afe02ecf44663156e7a79ad3f4e6cb7741/.config/i3/config#L98)).

**Comment by stapelberg** [comment]
> Have a look at [this script](https://github.com/davvil/dotfiles/blob/master/.config/i3/autotag.py) for tagging the windows. You then only need to bind keys for jumping to the corresponding marks ([example](https://github.com/davvil/dotfiles/blob/c4e8c7afe02ecf44663156e7a79ad3f4e6cb7741/.config/i3/config#L98)).

+1 for doing this externally to i3
