### ISSUE TITLE
Always hide titlebar of windows

### ISSUE THREAD

**Issue by haug1** [i3/i3#4198]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## New feature

Configuration option that always hides the window's titlebar.

## My motivation
I have not found a configuration option that allows me to do this. After searching the web I found only hacky ways to accomplish this such as setting the font size to 0. I remember having some unintentional effects from this configuration though;I think my i3bar disappeared as well.

## Implementation
Implementation is ready, I compiled it myself for personal use. 
I read in the contribute readme that you want an issue to check before submitting a PR. Do you want to review my implementation?

**Comment by haug1** [comment]
Found 'default_border', I'd like to hide it when in tabbed mode as well, but I'm not motivated enough to add another 'mode' to that.

**Comment by haug1** [comment]
I'm reopening because I implemented a [solution](https://github.com/haug1/i3/tree/hide-titlebar-config-and-command).

1. Adds boolean configuration option "always_hide_titlebar"
2. Adds command "titlebar" with options true|false|toggle

Different from 'border'/'default_border' in the sense that it is not a state on a single window, but rather a global value for all windows. And it _always_ hides titlebar even on tabbed/stacked layouts

**Comment by rpigott** [comment]
I'm not disagreeing with you, but this exact feature has been rejected many many times now. It's one of the most frequent feature requests. See #3617 and the links in the comments to find prior discussion.

**Comment by haug1** [comment]
Thanks for the reply. After reading your post and the linked issue(s) that have been requested, I only feel it adds relevancy to this feature request. I hope you will take my commit, otherwise I'll have to compile myself or switch over to xmonad. As many before me, as you pointed out. Obviously this is something that many users want implemented and adds no complexity or overhead.

**Comment by rpigott** [comment]
You misunderstand, I'm not against this feature. I'm also not a maintainer though, so I'm not who you need to convince.

**Comment by haug1** [comment]
Thanks. No, I understood that, this conversation will still be here for them to read. And it is a valid argument. So thanks for helping making it visible

**Comment by orestisfl** [comment]
Closing as this has been rejected in the past
