### ISSUE TITLE
Show indicator when hide_edge_borders is set

### ISSUE THREAD

**Issue by geshido** [i3/i3#4219]
Hi!
 I don't know if it is bug or should be feature request, but anyway...

## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When `hide_edge_borders` is set (to `smart` in my case) and there is only one window in workspace, there is no indicator showing where the next window will appear

## Expected Behavior
An indicator is drawn at the edge of where next window will appear.

**Comment by stapelberg** [comment]
Next-window indicators are drawn over the window border, and if you don’t have any border, there is no place where we can draw.

I’m not sure how this feature request would even work on a technical level, but independently, I don’t think adding a new knob is worth it for changing this behavior.
