### ISSUE TITLE
i3bar: render empty blocks with min_width

### ISSUE THREAD

**Issue by burik666** [i3/i3#4227]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
> If full_text is an empty string, the block will be skipped.

## Desired Behavior
> If full_text is an empty string and min_width is not set, the block will be skipped.

These changes will allow to do something like this:
![i3](https://user-images.githubusercontent.com/1700398/96832095-df352380-1446-11eb-95eb-16087f50110a.gif)
<details>
<summary>status.sh</summary>

```shell
#!/bin/sh
HEIGHT=18
cat <<EOF
{"version":1}
[
[],
EOF

while true; do
    value=$((RANDOM % 100))

    red=255
    green=255
    if [ $value -lt 50 ]; then
        red=$((255 * value / 50))
    else
        green=$((255 - 255 * (value - 50) / 50))
    fi

    color=$(printf %02x%2x00 $red $green)

    cat <<EOF
[
    {
        "full_text": "..."
    },
    {
        "full_text": "${value}%",
        "min_width": "100%",
        "align": "right",
        "separator": false,
        "separator_block_width": 5
    },
    {
        "full_text": "",
        "min_width": 5,
        "border": "#${color}",
        "border_top": 0,
        "border_left": 0,
        "border_right": 0,
        "border_bottom": $((HEIGHT * value / 100))
    },
    {
        "full_text": "..."
    }
],
EOF

sleep 1s
done

```
</details>
See PR: #4226 

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.18.2 (2020-07-26) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18.2 (2020-07-26) (pid 23694)bort…)
Loaded i3 config: /home/burik/.config/i3/config (Last modified: Thu 22 Oct 2020 08:29:20 AM MSK, 2152 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
- Linux Distribution & Version:Gentoo ~amd64
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by Airblader** [comment]
What if instead of empty string or a single space you use `"<span></span>"` or `"<span size=1> </span>"`? Does that work? Note that this requires pango markup to be enabled, so you also need to send `"markup": "pango"`

**Comment by burik666** [comment]
@Airblader, 
Great, that worked!

Thanks.

**Comment by Airblader** [comment]
Then I'll go ahead and close this since the use case is already bending the features in unintended ways, so I think that's a reasonable workaround to use. Thanks!
