### ISSUE TITLE
Set floating window position in terms of screen percentage

### ISSUE THREAD

**Issue by daboross** [i3/i3#4232]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When changing positions of floating windows programatically, the only way to specify an absolute position is to use

```
move position 1080 px 200 px
```

This refers to logical pixels, and the exact values needed to, say, place directly right of center, depend on the screen size & scale factor. The same is true for resizing -

```
resize set width 1920 px
resize set height 400 px
```

`resize` has an optional `ppt` mode, but that still refers to my understanding to the window's current size, _not_ to percentage points of the whole screen.

## Desired Behavior

I would like to be able to have a new window spawn always in a specific position on the screen, taking of a specific percentage of the screen's total height/width, regardless of the monitor size and my current scaling factor. This issue exists even for single monitor displays, but it's compounded by multiple monitors, and by changing the scale factor. In my particular situation, I use 2x scaling half the time, and 1x the other half, so I'd like my configuration to be independent of that.

Specifically, I suggest the following:

```
move position 75 screen_pp 75 screen_pp
resize set width 25 screen_pp
resize set height 25 screen_pp
```
unconditionally set a window's position to 75% of the way to the bottom-right corner of the screen, and so it takes up exactly 25% of the screen width and height.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: i3 version 4.18.2 (2020-07-26) © 2009 Michael Stapelberg and contributors
</pre>

<pre>
- Linux Distribution & Version: Fedora 33
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by orestisfl** [comment]
Does `i3-msg resize set 25 ppt 25 ppt, move position 75 ppt 75 ppt` work for you?

**Comment by daboross** [comment]
My apologies, I completely forgot about this. Thanks for closing, it is no longer an issue / I'm no longer trying to do this.
