### ISSUE TITLE
How to achieve effect like the monocle mode in bspwm

### ISSUE THREAD

**Issue by QiangF** [i3/i3#4247]
## I'm submitting a…

<pre>
[x] Feature Request
</pre>

I mostly work in maximized single window. When I open a new application, I want it occupy the whole display most of the times. Is there a way to open a new container under the root container of the same workspace when a new application is started, and make it the default behavior?

## Environment
<pre>
i3 version:  4.18
</pre>

**Comment by Airblader** [comment]
You could perhaps use a tabbed workspace layout. 

I'm going to close this as not actionable since it's more of a question. Please also have a look at the i3 subreddit for questions since that's where most of the community is. Thanks!
