### ISSUE TITLE
i3-nagbar keyboard control

### ISSUE THREAD

**Issue by yagarea** [i3/i3#4248]
<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
When i3-nagbar pops with some action buttons and close button user has to click button with cursor. This is very uncomfortable

## Desired Behavior
I would love to be able to iterate buttons using arrow keys and vim's `hjkl` navigation and select button with Enter. After pressing Escape i3-nagbar should close.

## Environment
Binary i3 version:  4.18.3 (2020-10-20) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18.3 (2020-10-20) (pid 691) abort…)
Loaded i3 config: /home/john/.config/i3/config (Last modified: Ne 8. listopadu 2020, 23:15:36, 42774 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

<pre>
- Linux Distribution & Version: Arch linux - 5.9.4-arch1-1
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by Airblader** [comment]
> This is very uncomfortable

This is more or less intentional, i3-nagbar is supposed to *nag* you because there's a mistake in your config.

While I'm not per se against being able to navigate i3-nagbar, I am not convinced we should add that level of complexity to it, because it brings up the issue of configuring these commands, visually highlighting the focused one etc. This seems way too much effort for a tool that exists almost exclusively for showing configuration errors.

**Comment by yagarea** [comment]
Thank you for your comment, I use i3-nagbar regularly for other controls. For example:
```
i3-nagbar -t warning -m 'Display menu:' \
	-B 'Vertical mode' 'bash ~/.config/screenlayout/vertical.sh && echo "1" > ~/.config/screenlayout/.session' \
	-B 'Connect to Dock' 'bash ~/.config/screenlayout/dock-in.sh && echo "0" > ~/.config/screenlayout/.session' \
	-B 'Disconnect all' 'bash ~/.config/screenlayout/dock-out.sh && echo "1" > ~/.config/screenlayout/.session'
```

I tried to emulate i3-nagbar with dmenu like this:
```
#!/bin/bash
while [ "$select" != "NO" -a "$select" != "YES" ]; do
    select=$(echo -e 'NO\nYES' | dmenu -nb '#151515' -nf '#999999' -sb '#f00060' -sf '#000000' -fn '-*-*-medium-r-normal-*-*-*-*-*-*-100-*-*' -i -p "You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.")
    [ -z "$select" ] && exit 0
done
[ "$select" = "NO" ] && exit 0
i3-msg exit
```
But it is ugly and hell to script custom stuff. 

Is this even intended usesage of i3-nagbar? Should I use some alternative?

**Comment by Airblader** [comment]
We don't intend i3-nagbar to be something you use for regular things, no. You could use a binding mode (if you want to use purely i3) or some external tool like zenity.

**Comment by orestisfl** [comment]
I personally use rofi for this: https://github.com/orestisfl/dotfiles/blob/b2a0c96034f9a837389322e33ee176706f895b13/executables/bin/i3-rofi-actions

Closing for the reasons @Airblader provided
