### ISSUE TITLE
Automatic vertical/horizontal splits

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [i3/i3#4253]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When a window pops up - you are forced to define where it gets placed beforehand or risk it being unreadable

## Desired Behavior

Split vertical/horizontal split being automatically switched based on window size. I have a script that does exactly what I want, it's just that I'd prefer it being part of i3.
```bash
REGEX="([0-9]+)x([0-9]+)"

update_split(){
    OUTPUT="$(xdotool getwindowfocus getwindowgeometry)"

    if [[ $OUTPUT =~ $REGEX ]]
    then
        WIDTH="${BASH_REMATCH[1]}"
        HEIGHT="${BASH_REMATCH[2]}"
        if [ $WIDTH -gt $HEIGHT ]; 
        then 
            i3-msg "split h"
        else
            i3-msg "split v"
        fi
    fi
}

while read -r line 
do
    LAYOUT="$(i3-msg -t get_tree | jq -r 'recurse(.nodes[]; .nodes != null) | select(.nodes[].focused).layout')"
    if [ "$LAYOUT" = "splitv" ] || [ "$LAYOUT" = "splith" ]; then
        update_split
    fi
done < <(xprop -spy -root _NET_ACTIVE_WINDOW)
```

**Comment by Airblader** [comment]
Loosely related to #674, more strongly related to #2106 and the reasoning in each of them applies here, too. 

> Opening a window and splitting a container are distinct operations, and I don’t want to throw them together. […] Users can always use the IPC interface to achieve the suggested feature. I’m closing this request in favor of #1814 and possibly scripts using the IPC interface.

As you demonstrated, it can be achieved using the IPC anyway.

---

> When a window pops up - you are forced to define where it gets placed beforehand or risk it being unreadable

This does not accurately reflect the current situation. You can decide this afterwards, the layout is not set in stone.

**Comment by gytis-ivaskevicius** [comment]
> As you demonstrated, it can be achieved using the IPC anyway.

Yeah, but I am literally running a separate daemon script for this little thing and that's not particularly nice. I strongly believe that there would be quite a few users that would love to see this as an option in i3 config

> This does not accurately reflect the current situation. You can decide this afterwards, the layout is not set in stone.

yes, you are right. But I think my point still stands

**Comment by orestisfl** [comment]
> Yeah, but I am literally running a separate daemon script for this little thing and that's not particularly nice. I strongly believe that there would be quite a few users that would love to see this as an option in i3 config

We have nothing against running running daemon scripts in the background, that's why we provide an IPC interface: to not have to implement any potential usercase.

**Comment by magnetophon** [comment]
Thanks a lot for this script, @gytis-ivaskevicius!

I would still like to ask the i3 devs to consider adding a layout that does this natively.
The reasons being:
- I think this is the most sensible way to split a window, and once it is available in i3 proper, a lot of people will make it their default layout.
- With this script, you cannot easily toggle between different layouts, like you can with the built in ones. ie: ``layout toggle splitv stacking``
- When a workspace is in tabbed or stacked layout, you need to put it in either hsplit or vsplit layout to start having the effects of this script. The first split will be horizontal or vertical, depending on the layout you chose, not depending on the dimensions of the window.
- presumably, a script using a ``while`` loop, will not be as battery-friendly as a native implementation.


Thanks for considering!

**Comment by bobbbay** [comment]
+1, I'd really like this feature - in general, I think I'd even be willing to provide that small amount of battery if needed. Also in general that script looks pretty smooth...
