### ISSUE TITLE
Center cursor on focused window

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [i3/i3#4254]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Desired Behavior
It would be cool to have an option that would achieve this behavior:
```bash
set $movemouse "sh -c 'eval `xdotool getactivewindow getwindowgeometry --shell`; xdotool mousemove $((X+WIDTH/2)) $((Y+HEIGHT/2))'"

bindsym $mod+$left focus left; exec $movemouse
bindsym $mod+$down focus down; exec $movemouse
bindsym $mod+$up focus up; exec $movemouse
bindsym $mod+$right focus right; exec $movemouse
```
TL;DR: it works as a focused window indicator (centers mouse on the focused window)

**Comment by Airblader** [comment]
i3 doesn't have any explicit command surface for cursor movement at the moment, and given that this is trivially achieved with tools like xdotool I would prefer to keep it that way.

**Comment by orestisfl** [comment]
I agree
