### ISSUE TITLE
enhancement - Adjust i3-sensible-terminal to Prioritize Accessible Terminals for Blind Users

### ISSUE THREAD

**Issue by jdfthetech** [i3/i3#4256]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Currently i3 prioritizes non-accessible terminals that do not function properly with orca and speech-dispatcher for blind users.

## Desired Behavior

This can be resolved by adjusting the prioritization of terminals in the i3-sensible-terminal file.
I have tested this with our blindarch distro and have confirmed it does work in our testing branch.

The attached file is updated to reflect the changes that would make this work better for blind users.
We simply change the order of some terminals that have orca support to be first in line.
Mate terminal is currently considered to be the most accessible.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
4.18.3

</pre>

<pre>
- Linux Distribution & Version:
Arch Linux - latest version (building custom ISO)
- Are you using a compositor (e.g., xcompmgr or compton):
no
</pre>

[i3-sensible-terminal.zip](https://github.com/i3/i3/files/5541911/i3-sensible-terminal.zip)

**Comment by Airblader** [comment]
Thanks for opening this issue.

In general I'd definitely be on board with doing this change given how simple it is. The problem, however, is that it's "breaking" in that it will very likely cause a problem for users who have multiple terminal emulators installed as it will change which one it opens.

**Comment by orestisfl** [comment]
To avoid having to download a file, here is the proposed word diff:

```diff
for terminal in "$TERMINAL" {+mate-terminal gnome-terminal terminator xfce4-terminal+} x-terminal-emulator urxvt rxvt termit[-terminator-] Eterm aterm uxterm xterm[-gnome-terminal-] roxterm[-xfce4-terminal-] termite lxterminal[-mate-terminal-] terminology st qterminal lilyterm tilix terminix konsole kitty guake tilda alacritty hyper; do
    if command -v "$terminal" > /dev/null 2>&1; then
        exec "$terminal" "$@"
    fi
```

**Comment by jdfthetech** [comment]
Would it be possible to enable this for future versions and prevent any updates from overwriting the file? I would assume this could be done with a if then and a sed statement.  

In addition, a note to current users would prevent them from having issues if they decided to reinstall so that might be an option.

We currently just overwrite the file with arch-chroot and that does the trick for us, so it's not stopping our installer, but this sort of thing would go a long way to preventing blind users from getting stuck at launch.  I am going to discuss with the arch team to update the wiki with this fix as well so that may be a good solution.

**Comment by Airblader** [comment]
> In addition, a note to current users would prevent them from having issues

We generally try to stay compatible by default rather than requiring users to read something and update their configuration, and my guess is that most people update packages without reading release notes for all of them.

I think the real question here is whether this is just worth biting the bullet and making the change. We're always looking to have good enough of a reason to make such changes, not just "but x looks better than y", and accessibility is obviously a very good reason. So I'd be open to reordering the list a bit based on accessibility. CC @stapelberg

**Comment by stapelberg** [comment]
I don’t mind shuffling these around, especially as we already explicitly do not guarantee any order.

One order invariant should not be violated, though: distribution-specific terminal emulator selection mechanisms like `x-terminal-emulator` must stay at the beginning of the list.

AFAIK, Arch doesn’t have such a mechanism, so this doesn’t matter for the use-case at hand.

**Comment by jdfthetech** [comment]
I just updated the i3-sensible-terminal and everything works using your suggested changes @stapelberg .
Full list we have in the file currently:

`x-terminal-emulator mate-terminal gnome-terminal terminator xfce4-terminal urxvt rxvt termit Eterm aterm uxterm xterm roxterm termite lxterminal terminology st qterminal lilyterm tilix terminix konsole kitty guake tilda alacritty hyper`

**Comment by stapelberg** [comment]
I sent pull request https://github.com/i3/i3/pull/4259 to address this issue. Thanks for your suggestion!
