### ISSUE TITLE
Swap windows between workspaces

### ISSUE THREAD

**Issue by KGusev** [i3/i3#4262]
## I'm submitting a proposal to add new feature that will allow to swap windows between workspaces 

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Desired Behavior
I am used to place concrete types of program on separate workspaces.
For example I always place IDE on 2nd, 3rd and 4th workspaces (2nd workspace is major IDE, other are helper).
But sometimes priority of that projects are changed and i compelled to change them places.
I propose to add feature that will allow to swap all windows between current and selected workspaces with saving geometry of windows (if possible).

**Comment by Airblader** [comment]
Why not just rename the workspaces to exchange names?

**Comment by KGusev** [comment]
Thanks.

I have solved the issue using `i3-msg -t "rename workspace"` command called three times. Script is something like this:
```bash
i3-msg -t "rename workspace $this_ws_name to $tmp_ws_name"
i3-msg -t "rename workspace $that_ws_name to $this_ws_name"
i3-msg -t "rename workspace $tmp_ws_name to $that_ws_name"
```
What about to add `i3-msg swap workspace` command that must be do something like script above?

**Comment by Airblader** [comment]
I think renaming is easy enough to not warrant a separate command for it. Closing since this is solved.
