### ISSUE TITLE
Workspace output interpreted as workspace name

### ISSUE THREAD

**Issue by quinnchr** [i3/i3#4276]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
I've been attempting to update my config to assign certain workspaces to a particular display. When I hit the key binding I set up or execute the same via i3-msg a new named workspace is created with the name being everything after `workspace` as the name.

In my config I have: `bindsym F12 workspace 8 output DP-0`
And i3-msg produces the same result `i3-msg "workspace 8 output DP-0"`

Both create a new workspace with name `8 output DP-0` on the active display

## Expected Behavior
Workspace number `8` should be displayed on `DP-0`

## Reproduction Instructions

<pre>
i3-msg "workspace 8 output DP-0"
</pre>

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.19 (2020-11-15) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.19 (2020-11-15) (pid 1878)
</pre>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5675045976276992.bz2
</pre>

<pre>
- Linux Distribution & Version:
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
- Are you using a compositor (e.g., xcompmgr or compton): gnome-shell
</pre>

**Comment by Airblader** [comment]
Output assignments are config directives, not runtime commands. If you want to move a workspace to another output, please use the move command.

**Comment by quinnchr** [comment]
Thank you! I'm an idiot and should read the docs more closely :facepalm:
