### ISSUE TITLE
Hide the i3bar separator

### ISSUE THREAD

**Issue by AlphaTechnolog** [i3/i3#4282]
## I'm submitting a…
<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Get the hidde bar separator function, something like this in `$HOME/.config/i3/config`:

```
bar {
    [...]
    show_separator off
    [...]
}
```

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.16.1
</pre>

<pre>
- Linux Distribution & Version: Debian 9
- Are you using a compositor: Compton
</pre>

**Comment by Airblader** [comment]
You can already do that with

```
separator_symbol ""
```

https://i3wm.org/docs/userguide.html#_custom_separator_symbol

**Comment by AlphaTechnolog** [comment]
I get a unknown error at use it config.

**Comment by AlphaTechnolog** [comment]
At use: `separator_symbol ""` i get an unknown error

**Comment by orestisfl** [comment]
Try `separator_symbol " "`

**Comment by AlphaTechnolog** [comment]
I need to hide it to show powerline fonts in i3 bar, now I'm using the `separator_symbol" "` but it's not the idea. The separator interrupts the continuity of the items.
![The space interrupted by the separator in the bar of i3](https://user-images.githubusercontent.com/54639968/102136415-bbcb9b00-3e2f-11eb-8165-7966c466c508.png)

**Comment by Airblader** [comment]
I've seen people do that by making the separator symbol one of the Powerline "arrow" heads.

Otherwise I would suggest looking into something like polybar. I don't think we're going to want to add another flag just to support this.

**Comment by AlphaTechnolog** [comment]
thanks for your support ... I'll be researching about polybar.
