### ISSUE TITLE
Kali[Gnome/Wayland](latest) cannot switch to i3!!

### ISSUE THREAD

**Issue by its0x08** [i3/i3#4323]
## I'm submitting a…

<pre>
[ ] Bug
[ ] Feature Request
[x] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
I've tried alot of online tutorials but none of them works..
Can't switch from gnome to anything.. I've tried xfce, lxfce, openbox
Can someone here help?!
It only starts gdm3+Gnome/Wayland, others just dont run at all it get stuck at gdm

## Expected Behavior
Boot to i3

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.18.3-276-g04442cd5 (2020-11-03, branch "gaps-next") © 2009 Michael Stapelberg and contributors

Running version: < 4.2-200

</pre>

<details><summary>Config file</summary><pre>
The one generated by the wizard
</pre>
</details>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version: Kali-rolling
- Are you using a compositor (e.g., xcompmgr or compton):
</pre>

**Comment by Airblader** [comment]
i3 is a X11 window manager and doesn't run under Wayland. For other issues please refer to the i3wm subreddit or your distro support channels, since this doesn't relate to i3 as a software.

**Comment by its0x08** [comment]
Since **Xorg**  doesn't support by default my **Dedicated GPU/3D controller**  and **Wayland**  does.. 
When I switched to **Xorg**  it just _crashed_  which made me think it was **i3**  fault or something..
Then just by commenting the **D-GPU**  from **Xorg**  config in _/etc/_  it worked fine ..
I wrote this for anyone who has same problem. Hope it helps!
