### ISSUE TITLE
XF86AudioPlay event causes dbus error and windows crashing

### ISSUE THREAD

**Issue by jprhyne** [i3/i3#4386]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When I press the Play/Pause button on my keyboard, the XF86AudioPlay event according to xev, all open applications that can produce sound crash. When starting up again, ROXTerm (my terminal emulator) reports an error of "Error connecting to dbus: Failed to connect to socket /tmp/dbus-zD4qpK2abk: Connection refused," and then applications like ncspot do not produce sound (I have tested with terminator and the same behavior exists but without the error being reported). However, browsers like LibreWolf and IceCat produce sound as expected. 
![latest-screenshot](https://user-images.githubusercontent.com/55465012/111110916-4fa72300-8555-11eb-82d4-982d1f2cf481.png)

## Expected Behavior

No crashes and no dbus error
## Reproduction Instructions

Start i3 session, fire XF86AudioPlay event
## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Running i3 version: 4.19.2 (2021-02-27) (pid 1935)
Loaded i3 config: /home/lidesia/.config/i3/config
</pre>

<details><summary>Config file</summary><pre>
# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod1
set $sup Mod4

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:monospace 8

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

# The combination of xss-lock, nm-applet and pactl is a popular choice, so
# they are included here as an example. Modify as you see fit.

# xss-lock grabs a logind suspend inhibit lock and will use i3lock to lock the
# screen before suspend. Use loginctl lock-session to lock your screen.
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork

# NetworkManager is the most popular way to manage wireless networks on Linux,
# and nm-applet is a desktop environment-independent system tray GUI for it.
exec --no-startup-id nm-applet

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec i3-sensible-terminal

# kill focused window
bindsym $mod+Shift+q kill

# start dmenu (a program launcher)
bindsym $mod+d exec --no-startup-id dmenu_run
# A more modern dmenu replacement is rofi:
# bindcode $mod+40 exec "rofi -modi drun,run -show drun"
# There also is i3-dmenu-desktop which only displays applications shipping a
# .desktop file. It is a wrapper around dmenu, so you need that installed.
# bindcode $mod+40 exec --no-startup-id i3-dmenu-desktop

# change focus
# bindsym $mod+j focus left
# bindsym $mod+k focus down
# bindsym $mod+l focus up
# bindsym $mod+semicolon focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
# bindsym $mod+Shift+j move left
# bindsym $mod+Shift+k move down
# bindsym $mod+Shift+l move up
# bindsym $mod+Shift+semicolon move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# switch to workspace
bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4
bindsym $mod+5 workspace number $ws5
bindsym $mod+6 workspace number $ws6
bindsym $mod+7 workspace number $ws7
bindsym $mod+8 workspace number $ws8
bindsym $mod+9 workspace number $ws9
bindsym $mod+0 workspace number $ws10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3
bindsym $mod+Shift+4 move container to workspace number $ws4
bindsym $mod+Shift+5 move container to workspace number $ws5
bindsym $mod+Shift+6 move container to workspace number $ws6
bindsym $mod+Shift+7 move container to workspace number $ws7
bindsym $mod+Shift+8 move container to workspace number $ws8
bindsym $mod+Shift+9 move container to workspace number $ws9
bindsym $mod+Shift+0 move container to workspace number $ws10

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym semicolon resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"
# User definied below
bindsym --release $mod+x exec --no-startup-id import /tmp/latest-screenshot.png
bindsym $mod+Shift+minus move scratchpad
bindsym $mod+minus scratchpad show
bindsym $mod+l exec i3lock -c 000000
#user defined above
#
# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        status_command i3blocks
}
</pre>

</details>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5721752705433600.bz2
</pre>

<pre>
- Linux Distribution & Version: Arch Linux with Kernel: Linux 5.11.5-arch1-1
- Are you using a compositor (e.g., xcompmgr or compton): Not sure, so probably not
- I uninstalled and reinstalled pulseaudio, but I don't think that's the issue as XF86AudioRaiseVolume does not cause these issues, it just does nothing as I haven't configured those symbols yet, but wanted to pass along the information just in case I mucked it up.
</pre>

**Comment by Airblader** [comment]
I'm not sure why i3 would be involved here, the key is not bound, so i3 doesn't care, and i3 is doing nothing with dbus and isn't responsible for how clients react to dbus messages. Is there anything that makes you suspect i3?

**Comment by jprhyne** [comment]
I switched to i3 from KDE and the error started, so i3 was the most recent change.

I'll look into what X is doing and see if I can figure that out (worst comes to worse maybe disable the keys). 

I posted the issue here since I wasn't really sure how i3 interacted under the hood. If the bug report is not applicable, you can close the issue.

Edit: I also thought i3 because most windows would close and that is something i3 does handle

**Comment by orestisfl** [comment]
Sounds like https://github.com/i3/i3/issues/2979.

If you have `dbus-launch` in your .xinitrc you need to remove it and start i3 with `exec i3` instead.

**Comment by jprhyne** [comment]
Just as I thought, user error on my end.

Thank you @orestisfl that fixed the issue!

the .xinitrc had a general purpose "case" for iterating through common DE and WMs and I didn't notice it launched that with dbus-launch.
