### ISSUE TITLE
Moving workspaces to different monitors

### ISSUE THREAD

**Issue by ZioZhul** [i3/i3#4449]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
I am trying to create and configure two workspaces in different monitors.
So currently when I run the following
```
i3-msg "workspace 4; exec urxvt; move workspace to DP-1" 
i3-msg "workspace 5; exec urxvt; move workspace to eDP-1"
```
I have both workspace 4 and 5 in eDP-1

## Expected Behavior
I expect that workspace 4 will be in DP-1 monitor and workspace 5 in eDP-1 monitor.

## Reproduction Instructions
Just by running the following in a shell script:
```
i3-msg "workspace 4; exec urxvt; move workspace to DP-1"
i3-msg "workspace 5; exec urxvt; move workspace to eDP-1"
```

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version 4.19.2 (2021-02-27)
</pre>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5751580582215680.bz2
</pre>

<pre>
- Linux Distribution & Version: ArchLinux
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by Airblader** [comment]
Is there any reason not to use [`workspace … output …`](https://i3wm.org/docs/userguide.html#workspace_screen)? I'm afraid you're snippet doesn't do what you think it does for various reasons.

**Comment by ZioZhul** [comment]
> Is there any reason not to use workspace … output …? 

Because I want to change workspace assignments without having to re-edit the configuration.
I use my laptop mainly with a second monitor but sometimes I unplug it to move away from desk. So I thought about a script (with a shortcut) to rearrange my workspaces deepening on having the second monitor available or not.

> I'm afraid you're snippet doesn't do what you think it does for various reasons.

Interesting, I thought the following `workspace 5; exec urxvt; move workspace to DP-1` to be quite straightforward: select workspace 5, open a terminal then move the workspace to the specified output

EDIT1: which what happens actually, but if I have multiple commands like the above, the last `move workspace` is going to move all workspaces created in the script.
EDIT2: This issue does not happen if workspaces are already created and I just need to move them:
```
i3-msg "workspace 4; move workspace to DP-1"
i3-msg "workspace 5; move workspace to eDP-1"
```

**Comment by Airblader** [comment]
Can you try running everything in a single `i3-msg` rather than two calls?

**Comment by ZioZhul** [comment]
I have thought about that too (maybe some concurrency issue) and unfortunately it does not fix it.
```
i3-msg "workspace 4; exec urxvt; move workspace to DP-1; workspace 5; exec urxvt; move workspace to eDP-1" 
```

**Comment by ZioZhul** [comment]
The workaround I am using is to split the creation and the relocation of workspaces in two scripts.
The first creates the workspaces (this can be even put in the config file) and the second moves them to the appropriate monitors depending on my working environment.
So this is not really urgent, but still I thought that it may be useful to report it

**Comment by Airblader** [comment]
> So this is not really urgent, but still I thought that it may be useful to report it

Yes, definitely thanks for reporting!

We will have to check out the logs on this to be sure on what's happening. When I say it doesn't do what you think it's mostly about timing things, eg the move of the workspace will happen after the urxvt process is launched, not necessarily after its window has opened.

**Comment by orestisfl** [comment]
According to the logs the order of events is: Switch to workspace 4 -> launch urxvt1 -> Switch to workspace 5 -> launch urxvt2 -> Kill empty workspace 4 -> urxvt2 opens on workspace 5 (through startup sequence) -> urxvt1 opens on workspace 4 (through startup sequence) -> workspace 4 is created again (on the same output as workspace 5).

Thus, it is a timing issue and i3 can't realistically do anything.

Hacky solution is to sleep after launching each urxvt instance, more correct solution is to wait for each urxvt instance to spawn. Example:

```shell
#!/bin/bash

function wait_for_urxvt() {
    # Wait until a window with URxvt's class is focused / created
    i3-msg -t subscribe '[ "window" ]' \
        | jq --unbuffered -r .container.window_properties.class \
        | stdbuf -oL grep -m 1 -i urxvt \
        | head -1 \
        | while read line;
        do
            # loop seems to be necessary because of https://github.com/stedolan/jq/issues/1691
            break
        done
}

i3-msg 'workspace 4, exec urxvt'
wait_for_urxvt
i3-msg 'move workspace to DP-1'

i3-msg 'workspace 5, exec urxvt'
wait_for_urxvt
i3-msg 'move workspace to eDP-1'
```
