### ISSUE TITLE
I3 doesn't show a part of toolbar if it is started on several different monitors

### ISSUE THREAD

**Issue by unera** [i3/i3#4458]
I have two monitors.

My xrandr is:

```
xrandr \
   --output eDP-1 --mode 2160x1350 --pos 360x1635 --primary \
   --output DP-4 --mode 3840x2160 --pos 0x0 --scale 0.75x0.75

$ xrandr
eDP-1 connected primary 2160x1350+360+1635 (normal left inverted right x axis y axis) 280mm x 175mm
   2160x1350     59.74*+  30.00  
...
DP-4 connected 2880x1620+0+0 (normal left inverted right x axis y axis) 597mm x 336mm
   3840x2160     29.98* 
```

So i3 showed the full bar at DP4 and part of the bar doesn't show at eDP-1.

bar on DP-4:
![DP-4 screenshot right-bottom](https://user-images.githubusercontent.com/538980/126630600-1bb0a382-dc67-491c-abd2-4054ae4c10e2.png)

bar on eDP-1:
![eDP-screenshot right-bottom](https://user-images.githubusercontent.com/538980/126630730-26a8d2d6-2eb0-4b2c-8cc9-2510fa95e0cc.png)

You can see that all system-tray icons aren't showed on primary monitor.

## Environment
```

$ i3 --moreversion
Binary i3 version:  4.19.1-non-git © 2009 Michael Stapelberg and contributors
Running i3 version: 4.19.1-non-git (pid 80581)
Loaded i3 config: /home/unera/.i3/config (Last modified: Чт 22 апр 2021 14:24:40, 7862058 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

$ LANG=C apt policy i3 
i3:
  Installed: 4.19.1-1
  Candidate: 4.19.1-1
  Version table:
 *** 4.19.1-1 990
        990 http://deb.debian.org/debian bullseye/main amd64 Packages
        500 http://deb.debian.org/debian sid/main amd64 Packages
        100 /var/lib/dpkg/status
     4.16.1-1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages

```

<details><summary>Config file</summary><pre>
# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see http://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod1
set_from_resource $font i3wm.font

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
font $font
# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec rxvt
bindsym $mod+Control+t exec rxvt
bindsym $mod+Control+m exec x-www-browser
bindsym $mod+Control+p exec --no-startup-id bash ~/.scripts/screenshot window
bindsym $mod+Control+Shift+p exec --no-startup-id bash ~/.scripts/screenshot full

bindsym $mod+period exec ~/.scripts/mpc next
bindsym $mod+comma exec ~/.scripts/mpc prev
bindsym $mod+Shift+comma exec ~/.scripts/mpc stop
bindsym $mod+Shift+period exec ~/.scripts/mpc play

# kill focused window
bindsym $mod+Shift+c kill

# start dmenu (a program launcher)
bindsym $mod+d exec shellex
# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.
# bindsym $mod+d exec --no-startup-id i3-dmenu-desktop

# change focus
bindsym $mod+t border toggle
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+semicolon focus right

bindsym $mod+Shift+s exec xscreensaver-command -lock
bindsym $mod+Control+s exec xscreensaver-command -lock
bindsym $mod+Control+w exec sudo wpa_cli reassociate

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+m fullscreen

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

# switch to workspace
bindsym $mod+F1 workspace 1

bindsym $mod+F2 workspace 2
bindsym $mod+F3 workspace 3
bindsym $mod+F4 workspace 4
bindsym $mod+F5 workspace 5
bindsym $mod+F6 workspace 6
bindsym $mod+F7 workspace 7
bindsym $mod+F8 workspace 8
bindsym $mod+F9 workspace 9
bindsym $mod+F10 workspace 10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace 1
bindsym $mod+Shift+2 move container to workspace 2
bindsym $mod+Shift+3 move container to workspace 3
bindsym $mod+Shift+4 move container to workspace 4
bindsym $mod+Shift+5 move container to workspace 5
bindsym $mod+Shift+6 move container to workspace 6
bindsym $mod+Shift+7 move container to workspace 7
bindsym $mod+Shift+8 move container to workspace 8
bindsym $mod+Shift+9 move container to workspace 9
bindsym $mod+Shift+0 move container to workspace 10

# reload the configuration file
# bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width 10 px or 5 ppt
        bindsym k resize grow height 10 px or 5 ppt
        bindsym l resize shrink height 10 px or 5 ppt
        bindsym semicolon resize grow width 10 px or 5 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 5 ppt
        bindsym Down resize grow height 10 px or 5 ppt
        bindsym Up resize shrink height 10 px or 5 ppt
        bindsym Right resize grow width 10 px or 5 ppt

        # back to normal: Enter or Escape
        bindsym Return mode "default"
        bindsym Escape mode "default"
}

bindsym $mod+r mode "resize"

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
#        status_command i3status --config ~/.i3/status
#	status_command perl ~/.scripts/i3status.pl
	status_command i3blocks -c ~/.i3/blocks
}

focus_follows_mouse no
popup_during_fullscreen smart

workspace_layout default

bindsym $mod+Control+Left resize grow width 10 px or 3 ppt
bindsym $mod+Control+Right resize shrink width  10 px or 3 ppt
bindsym $mod+Control+Up resize grow height 10 px or 3 ppt
bindsym $mod+Control+Down resize shrink height  10 px or 3 ppt

# exec --no-startup-id iceweasel
# exec rxvt

workspace 1 output DP-4                   eDP-1 
workspace 2 output                        eDP-1
workspace 3 output DP-4                   eDP-1
workspace 4 output                        eDP-1
workspace 5 output DP-4                   eDP-1
                                             
workspace 6 output                        eDP-1
workspace 7 output                        eDP-1
workspace 8 output DP-1-1                 eDP-1
workspace 9 output                        eDP-1
workspace 0 output DP-1-1                 eDP-1

bindsym $mod+minus scratchpad show
bindsym $mod+Shift+minus move scratchpad

exec --no-startup-id i3-msg '[class=Iceweasel] move workspace 1'
exec --no-startup-id i3-msg '[class=URxvt] move workspace 1'
exec --no-startup-id i3-msg 'workspace 1'
exec --no-startup-id i3-msg '[class=URxvt] focus'
exec --no-startup-id i3-msg '[class=URxvt] move right'
exec --no-startup-id i3-msg '[class=URxvt] resize shrink width 10 px or 3 ppt'

assign [class="Skype"] 6
assign [class="Telegram"] 6
assign [class="Viber"] 6
assign [class="ViberPC"] 6
assign [class="Navigator"] 1
for_window [class="[Gg]oldendict"] floating enable

exec --no-startup-id feh --bg-scale ~/.fluxbox/wp.jpg
exec --no-startup-id compton --config .i3/compton.conf

bindcode 232 exec --no-startup-id ~/.scripts/brightness down
bindcode 233 exec --no-startup-id ~/.scripts/brightness up
bindsym control+F6 exec --no-startup-id ~/.scripts/brightness up
bindsym control+F5 exec --no-startup-id ~/.scripts/brightness down

bindcode 237 exec --no-startup-id ~/.scripts/brightness-key down
bindcode 238 exec --no-startup-id ~/.scripts/brightness-key up
bindsym $mod+0 exec "bash ~/.scripts/volume up"
bindsym $mod+9 exec "bash ~/.scripts/volume down"
bindsym XF86AudioLowerVolume exec "bash ~/.scripts/volume down"
bindsym XF86AudioRaiseVolume exec "bash ~/.scripts/volume up"
bindsym XF86AudioMute exec "bash ~/.scripts/volume mute"

# class                 border  backgr. text    indicator child_border
client.focused          #222222 #000000 #eeeeee #000000   #222222
client.focused_inactive #222222 #444444 #aaaaaa #000000   #222222

client.unfocused        #222222 #333333 #aaaaaa #222222   #222222

client.urgent           #222222 #AA0000 #cccccc #222222   #222222
client.placeholder      #222222 #0c0c0c #aaaaaa #222222   #222222

client.background       #000000
</pre>
</details>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5708842134405120.bz2
</pre>

**Comment by Airblader** [comment]
Thanks for opening the issue and taking the time to fill out all the details. The system tray can (unfortunately) only be shown on one single output. That's a limitation of how the tray specification works. You can control which output the tray will be placed on through configuration, though.

There's a replacement specification which supports this, but is significantly more complex, and we have discarded the idea of adopting it for a few reasons, see #2088.
