### ISSUE TITLE
window border icons only respecting icon theme for GTK+ applications

### ISSUE THREAD

**Issue by LordMZTE** [i3/i3#4461]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

In the case of applications that use other GUI frameworks besides GTK+, such as Qt, the icon displayed in the window border uses the default icon of the application, instead of the one of the current GTK icon theme.
Icon are enabled in the config with `for_window [class=".*"] title_window_icon on`.
The icon theme is set in `~/.gtkrc-2.0` and `~/.config/gtk-3.0/settings.ini`.
The icons of the applications are defined in their respective `.desktop` files.
## Expected Behavior

All applications should display the icons set in their `.desktop` file (respecting the icon theme), regardless of the GUI toolkit they use.

## Reproduction Instructions

- Select an icon theme in the `~/.gtkrc-2.0` and `~/.config/gtk-3.0/settings.ini` files. (I use [candy-icons](https://github.com/EliverLara/candy-icons))
- Enable title icons for all windows using the `for_window [class=".*"] title_window_icon on` config option in `~/.config/i3/config`.
- Open an application that uses GTK, such as firefox. The icon theme should be respected.
- Open an application that does not use GTK, such as discord. The default icon should be displayed in the window bar instead of the icon defined by the icon theme.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 

Binary i3 version:  4.19.1-134-g991824ab © 2009 Michael Stapelberg and contributors
Running i3 version: 4.19.1-134-g991824ab (pid 1912)
Loaded i3 config:
  /home/lordmzte/.config/i3/config (main) (last modified: Thu 15 Jul 2021 05:15:39 PM CEST, 852145 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<details><summary>Config file</summary><pre>
https://github.com/LordMZTE/dotfiles/blob/master/.config/i3/config
</pre>
</details>

<pre>
Logfile URL:
https://logs.i3wm.org/logs/5696284086239232.bz2
</pre>

<pre>
- Linux Distribution & Version: Arch Linux 5.13.4
- Are you using a compositor (e.g., xcompmgr or compton): yes, picom
</pre>

**Comment by psychon** [comment]
> the icon displayed in the window border uses the default icon of the application, instead of the one of the current GTK icon theme.

Could you run `xprop _NET_WM_ICON` in a terminal and click on one of the affected program's windows? This should show you the current icon of the window.

This property is set by the application itself. The WM only uses this and displays it. At no point does i3 interact with any kind of icon theme.

I am not quite sure what you are doing and what you expect to happen, but, well, if there is a bug, it would be in the individual applications or Qt or something like that.

**Comment by LordMZTE** [comment]
Running that command, it also displays the icon that isn't from the icon theme. I thought this was an issue with i3, since other window managers such as KWin display the icon of the icon theme for the same application.

**Comment by Airblader** [comment]
I agree with psychon's view here: what we render is the icon defined by `_NET_WM_ICON`, which is set by the client. If this shows the "wrong" icon, it has to be investigated by the application (or the framework they use). I wouldn't be surprised if KWin et al do more than just look at this atom for what they render, but that's not what i3 does.
