### ISSUE TITLE
i3bar - Recent update caused i3bar to show "Error: status_command process exited unexpectedly (exit 1)"

### ISSUE THREAD

**Issue by voxelv** [i3/i3#4462]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

i3bar shows "Error: status_command process exited unexpectedly (exit 1)"

## Expected Behavior

i3bar to show normal i3status

## Environment

Output of `i3 --moreversion 2>&-`: 
<pre>
i3 version: 
Binary i3 version:  4.19.2 (2021-02-27) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.19.2 (2021-02-27) (pid 634)
Loaded i3 config: /home/tim/.config/i3/config (Last modified: Sun Jul 25 11:51:51 2021, 1702 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<details><summary>Config file</summary><pre>
# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
#font pango:monospace 8

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8
font pango:Hack 8

# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
#bindsym $mod+Return exec i3-sensible-terminal
bindsym $mod+Return exec kitty

# kill focused window
bindsym $mod+Shift+q kill

# start dmenu (a program launcher)
#bindsym $mod+d exec dmenu_run
# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.
bindsym $mod+d exec --no-startup-id i3-dmenu-desktop

# change focus
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+b split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# switch to workspace
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace $ws8
bindsym $mod+9 workspace $ws9
bindsym $mod+0 workspace $ws10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5
bindsym $mod+Shift+6 move container to workspace $ws6
bindsym $mod+Shift+7 move container to workspace $ws7
bindsym $mod+Shift+8 move container to workspace $ws8
bindsym $mod+Shift+9 move container to workspace $ws9
bindsym $mod+Shift+0 move container to workspace $ws10

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym h resize shrink width 10 px or 10 ppt
        bindsym j resize grow height 10 px or 10 ppt
        bindsym k resize shrink height 10 px or 10 ppt
        bindsym l resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"

bindsym $mod+Shift+o exec dm-tool lock

bindsym Print exec maim -s ~/jatacore/pic/ss/$(date +%Y%m%d_%H%M%S).png

default_border pixel 1
hide_edge_borders smart

floating_modifier Mod4

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
	tray_output primary
        status_command i3status
}

# Workspace on screens
#workspace $ws1 output DVI-D-0
#workspace $ws2 output HDMI-0
#workspace $ws3 output DVI-I-1
workspace $ws1 output HDMI-0
workspace $ws2 output DVI-I-1

# set bg color
exec --no-startup-id xsetroot -solid black

</pre>
</details>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5133334132817920.bz2
</pre>

<pre>
- Linux Distribution & Version: 
$ uname-a
Linux sanctus 5.13.4-arch2-1 #1 SMP PREEMPT Thu, 22 Jul 2021 20:46:28 +0000 x86_64 GNU/Linux
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by psychon** [comment]
Since I have no good ideas, here is a bad one: What happens when you run `i3status` in a terminal?

**Comment by voxelv** [comment]
<pre>
➜  ~ i3status                   
i3status: trying to auto-detect output_format setting
i3status: auto-detected "term"
no IPv6 | W: ( 72% at DerelicTech) 123.123.123.123 | E: down | 136.6 GiB | LOAD:1.47 | RAM:5.2%(1.6 GiB) | 2021-07-25 12:46:00
^Ci3status: exiting due to signal.
</pre>
_Note: I replaced my internal IP with 123.123.123.123_

**Comment by voxelv** [comment]
Interestingly, I get a different result when ssh'd in:

<pre>
➜  ~ i3status
Could not set locale. Please make sure all your LC_* / LANG settings are correct.% 
➜  ~
</pre>

**Comment by psychon** [comment]
That could very well be it. If you want to make super-sure, create a shell with exactly the following environ and try to execute `i3status`:
```
$ xargs --null --max-args=1 echo < /proc/$(pidof i3)/environ
```
(This should print all of i3's environment variables)

**Comment by voxelv** [comment]
I tried that and there was no `LC_*` environment variables, but `LANG=en_US.UTF-8` did show up.

I found this [reddit post](https://www.reddit.com/r/archlinux/comments/gk5s22/how_to_fix_locale_errors/) which did not inspire confidence, but I tried it anyway.

What eventually worked was to uncomment my desired locale in `/etc/locale.gen` and run `locale-gen` with sudo.

I vaguely remember doing that back when I first installed Arch. Weird that I had to do it again...
