### ISSUE TITLE
Parallels 2XClient does not respond to i3 functions

### ISSUE THREAD

**Issue by eskalVAR** [i3/i3#4500]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[x] Other (Please describe in detail)
</pre>

## Current Behavior

2XClient is a program I use to access a windows work PC remotely. Upon connecting the session is fullscreen and no i3 functions work. Cannot exit fullscreen, change workspace, move to scratchpad etc.  My custom binds work, e.g to take a screenshot but cause an immediate crash of the program. Using the keybind to minimize : https://kb.parallels.com/en/124361, understandably doesn't work as i3 does not implement it. I have written a script that forces the program out of fullscreen:

`sleep 15 `
`i3-msg [class="2X_Software-Application"] fullscreen disable`
`i3-msg [class="******REDACTED****"] fullscreen disable`

Then once the program is moved to scratchpad it's pretty stable. At one point toggling in out and fullscreen worked for some unknown reason. If the program is not put in a scratchpad and workspaces are changed, it crashes.

Please note that none of this broken behavior occurs with KDE. The minimize bind works, everything works.
## Expected Behavior

Program should obey i3 functions and not crash.
## Reproduction Instructions

Open 2XClient and connect to remote desktop.
## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
Binary i3 version:  4.19.1 (2021-02-01) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.19.1 (2021-02-01) (pid 54825)
Loaded i3 config: /home/viking/.config/i3/config (Last modified: Wed 08 Sep 2021 16:13:15 BST, 11729 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<details><summary>Config file</summary><pre>
</pre>
</details>

<pre>
Logfile URL:
Working fullscreen toggle
https://logs.i3wm.org/logs/5740833366081536.bz2
Application crash when changing workspace
https://logs.i3wm.org/logs/5758041588760576.bz2
</pre>

<pre>
- Linux Distribution & Version: Arch Linux Linux 5.13.13-arch1-1
- Are you using a compositor (e.g., xcompmgr or compton): Yes picom
</pre>

**Comment by orestisfl** [comment]
It seems that the bindings not working is expected behavior? The program probably grabs some of the keys that are assigned to your i3 keybindings (e.g. to use the "windows" key inside windows).

Regarding a proprietary application crashing, I don't see how we can help with that. Attempt to contact them.

**Comment by eskalVAR** [comment]
The application is not grabbing the keys, I can use screenkey with it and
the keys are displayed correctly. Looking through the logs i3 tries to do
something with the window but it doesn't respond to re-sizing parameters.
Thanks

**Comment by orestisfl** [comment]
Regarding the screenshot key, I don't really see anything in either log. We are talking about these two bindings right?

```
bindsym --release Mod4+w exec "screenshot"
bindsym --release Print exec "screenshot_whole"
```

Regarding the fullscreen command, I can see a lot of them in the logs. Can you please upload some that contain only the events we are interested in? Specifically, open a new session with the default config, run the program, wait for it to be fullscreen, run the fullscreen toggle / disable command twice (wait a second or two between each call) and then immediately exit the session & upload the logs.

**Comment by eskalVAR** [comment]
https://logs.i3wm.org/logs/5664206586118144.bz2

Here I run default config. Opened the client, connected, tried alt + f twice, then win+alt+m (minimize bind hardcoded into client)

Thanks.

**Comment by orestisfl** [comment]
So, nowhere in the new logs there is a fullscreen command triggered. Probably meaning that your keybindings are not triggered at all.

**Comment by eskalVAR** [comment]
I changed an option in the client can use it's in-built bind to exit fullscreen without crashing etc. I3 handles it correctly as well.
