### ISSUE TITLE
i3status read file documentatioi incomplete

### ISSUE THREAD

**Issue by ghost** [i3/i3#4812]
## I'm submitting a…

<pre>
[ ] Bug
[ ] Feature Request
[ x ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

i3status documentation not containing a full example of read_file (config block present but order directive not present)

## Expected Behavior

As with other modules, both module configuration and order directive are expected (in this case, 'order += 'read_file uptime').

## Environment

Binary i3 version:  4.19.1-non-git © 2009 Michael Stapelberg and contributors
Running i3 version: 4.19.1-non-git (pid 1984)
Loaded i3 config: /home/pat/.config/i3/config (Last modified: do 20 jan 2022 16:44:27, 402766 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

<pre>
- Linux Distribution & Version: Ubuntu 21.10
- Are you using a compositor (e.g., xcompmgr or compton): Yes
</pre>

**Comment by orestisfl** [comment]
Please use the i3status repository
