### ISSUE TITLE
firefox not opening in configured workspace when opened with atleast 4 workspaces ( jumps to 4th opened workspace )

### ISSUE THREAD

**Issue by RayZ0rr** [i3/i3#4846]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When logging into i3 with a specific startup script, firefox opens in a different workspace than configured in i3 config
## Expected Behavior

Firefox to open in the proper workspace.
## Reproduction Instructions

1. Make the following executable:
<details>
<summary>spawntest1.sh</summary>

```bash
#!/usr/bin/env bash

i3-msg "workspace number 1; exec alacritty"

sleep 1
i3-msg "workspace number 2; exec alacritty"

sleep 1
i3-msg "workspace number 3; exec alacritty"

sleep 1
i3-msg "workspace number 4; exec alacritty"

sleep 1
i3-msg "workspace number 1"
```
</details>
<details>
<summary>spawntest2.sh</summary>

```bash
#!/usr/bin/env bash

i3-msg "workspace number 1; exec alacritty"

sleep 1
i3-msg "workspace number 2; exec alacritty"

sleep 1
i3-msg "workspace number 3; exec alacritty"

# sleep 1
# i3-msg "workspace number 4; exec alacritty"

sleep 1
i3-msg "workspace number 1"
```
</details>
2. Put the following in i3 config file:

```bash
assign [class="firefox"] number 9
exec --no-startup-id /path/to/spawntest1.sh
# exec --no-startup-id /path/to/spawntest2.sh # This works.
```
3. Restart system.
4. Log into i3 (i3-gaps here)
5. Open firefox

If `spawntest1.sh` is used, firefox opens in workspace number 4 instead of configured workspace number 9. If `spawntest2.sh` is used then, firefox opens in workspace 9 as expected.
## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.20.1 (2021-11-03) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.20.1 (2021-11-03) (pid 3806)
Loaded i3 config:
  /home/razorr/.config/i3/config (main) (last modified: Mon 07 Feb 2022 03:34:43 PM IST, 993 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3-with-/i3
</pre>

<details><summary>Config file</summary>

<pre>
# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!
#
# This config file uses keycodes (bindsym) and was written for the QWERTY
# layout.
#
# To get a config file with the same key positions, but for your current
# layout, use the i3-config-wizard
#

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:Fira Nerd Font Mono 2

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

# Start XDG autostart .desktop files using dex. See also
# https://wiki.archlinux.org/index.php/XDG_Autostart
exec --no-startup-id dex --autostart --environment i3

# The combination of xss-lock, nm-applet and pactl is a popular choice, so
# they are included here as an example. Modify as you see fit.

# xss-lock grabs a logind suspend inhibit lock and will use i3lock to lock the
# screen before suspend. Use loginctl lock-session to lock your screen.
# exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork

# NetworkManager is the most popular way to manage wireless networks on Linux,
# and nm-applet is a desktop environment-independent system tray GUI for it.
# exec --no-startup-id nm-applet

# Use pactl to adjust volume in PulseAudio.
set $refresh_i3status killall -SIGUSR1 i3status
# bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10% && $refresh_i3status
# bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10% && $refresh_i3status
# bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle && $refresh_i3status
# bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle && $refresh_i3status

# Super(windows) modifier key and alt key
set $mod Mod4
set $altKey Mod1

# i3 scripts folder shortcut for easy use in following commands
set $i3_scripts ~/.config/i3/scripts

# use these keys for focus, movement, and resize directions when reaching for
# the arrows is not convenient
set $up l
set $down k
set $left j
set $right h

# use Mouse+$mod to drag floating windows to their wanted position
floating_modifier Mod4

# start a terminal
bindsym Mod4+Return exec alacritty

# kill focused window
bindsym Mod4+Shift+x kill

# start dmenu (a program launcher)
# bindsym $mod+d exec --no-startup-id dmenu_run
# A more modern dmenu replacement is rofi:
# bindsym $mod+d exec "rofi -modi drun,run -show drun"
# There also is i3-dmenu-desktop which only displays applications shipping a
# .desktop file. It is a wrapper around dmenu, so you need that installed.
# bindsym $mod+d exec --no-startup-id i3-dmenu-desktop

# change focus
bindsym $mod+$left focus left
bindsym $mod+$down focus down
bindsym $mod+$up focus up
bindsym $mod+$right focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+$left move left
bindsym $mod+Shift+$down move down
bindsym $mod+Shift+$up move up
bindsym $mod+Shift+$right move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# Cycle workspaces
bindsym $mod+a workspace prev
bindsym $mod+s workspace next
# bindsym $mod+Shift+a workspace prev_on_output
# bindsym $mod+Shift+s workspace next_on_output
bindsym $mod+Shift+a exec --no-startup-id ~/.config/i3/scripts/workspace_change.sh prev
bindsym $mod+Shift+s exec --no-startup-id ~/.config/i3/scripts/workspace_change.sh next

# Cycle containers
bindsym $mod+w focus prev
bindsym $mod+e focus next
bindsym $mod+Shift+w focus parent, focus prev
bindsym $mod+Shift+e focus parent, focus next
# bindsym $mod+Shift+w focus prev sibling
# bindsym $mod+Shift+e focus next sibling

# switch between the current and the previously focused one
bindsym $mod+Tab workspace back_and_forth
bindsym $mod+Shift+Tab move container to workspace back_and_forth

# border changing
bindsym $mod+b border toggle

# Hiding borders adjacent to the screen edges
hide_edge_borders smart

# split in horizontal orientation
bindsym $mod+o split horizontal
bindsym $mod+Shift+o focus parent, split horizontal
bindsym $mod+$altKey+o split h, exec alacritty -e ${HOME}/.config/i3/scripts/empty_container.sh
# bindsym $mod+$altKey+o split horizontal, exec i3 open, split h, layout tabbed

# split in vertical orientation
bindsym $mod+u split vertical
bindsym $mod+Shift+u focus parent, split vertical
bindsym $mod+$altKey+u split vertical, exec alacritty -e ${HOME}/.config/i3/scripts/empty_container.sh
# bindsym $mod+$altKey+u split vertical, exec i3 open, split v, layout tabbed

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle
bindsym $mod+Ctrl+f fullscreen toggle global

# Default layout for new containers
workspace_layout default

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+d split h, layout tabbed
bindsym $mod+Shift+d layout tabbed
bindsym $mod+t split h, layout stacking
bindsym $mod+Shift+t layout stacking
bindsym $mod+g layout toggle split

# toggle tiling / floating
bindsym $mod+space floating toggle
bindsym $mod+Ctrl+space [workspace=__focused__] floating toggle

# change focus between tiling / floating windows
bindsym $mod+c focus mode_toggle

# Force focus wrapping
focus_wrapping yes
# focus next visible window
# bindsym $mod+n exec --no-startup-id ~/.config/i3/scripts/focus-next-visible.py
# focus previous visible window
# bindsym $mod+Shift+n exec --no-startup-id ~/.config/i3/scripts/focus-next-visible.py reverse

# focus the parent container
bindsym $mod+z focus parent

# focus the child container
bindsym $mod+x focus child

# Jump to urgent window
bindsym $mod+v [urgent=latest] focus

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# switch to workspace
bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4
bindsym $mod+5 workspace number $ws5
bindsym $mod+6 workspace number $ws6
bindsym $mod+7 workspace number $ws7
bindsym $mod+8 workspace number $ws8
bindsym $mod+9 workspace number $ws9
bindsym $mod+0 workspace number $ws10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3
bindsym $mod+Shift+4 move container to workspace number $ws4
bindsym $mod+Shift+5 move container to workspace number $ws5
bindsym $mod+Shift+6 move container to workspace number $ws6
bindsym $mod+Shift+7 move container to workspace number $ws7
bindsym $mod+Shift+8 move container to workspace number $ws8
bindsym $mod+Shift+9 move container to workspace number $ws9
bindsym $mod+Shift+0 move container to workspace number $ws10

# reload the configuration file
bindsym $mod+Shift+r reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+$altKey+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+q exit
# bindsym $mod+Shift+q exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym $left       resize shrink width 10 px or 10 ppt
        bindsym $down       resize grow height 10 px or 10 ppt
        bindsym $up         resize shrink height 10 px or 10 ppt
        bindsym $right      resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left        resize shrink width 10 px or 10 ppt
        bindsym Down        resize grow height 10 px or 10 ppt
        bindsym Up          resize shrink height 10 px or 10 ppt
        bindsym Right       resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"

mode "swap" {
	# switch to workspace
	bindsym $mod+1 workspace $ws1
	bindsym $mod+2 workspace $ws2
	bindsym $mod+3 workspace $ws3
	bindsym $mod+4 workspace $ws4
	bindsym $mod+5 workspace $ws5
	bindsym $mod+6 workspace $ws6
	bindsym $mod+7 workspace $ws7
	bindsym $mod+8 workspace $ws8
	bindsym $mod+9 workspace $ws9
	bindsym $mod+0 workspace $ws10

	# change focus
	bindsym $mod+Left focus left
	bindsym $mod+Down focus down
	bindsym $mod+Up focus up
	bindsym $mod+Right focus right

	# change focus (without mod)
	bindsym Left focus left
	bindsym Down focus down
	bindsym Up focus up
	bindsym Right focus right

	bindsym Return swap container with mark "swapee"; unmark "swapee"; mode "default";
	bindsym Escape unmark "swapee"; mode "default";
}

bindsym $mod+slash mark --add "swapee"; mode "swap"

# Modes
#######################################
# set shut down, restart and locking features
# ⇒ type `$mod+Shift+Delete` then either `e`, `r` or `s`
mode "$mode_system" {
    bindsym e  exec --no-startup-id i3-msg exit
    bindsym r  exec --no-startup-id systemctl reboot
    bindsym s  exec --no-startup-id systemctl poweroff

    # exit system mode with "Enter" or "Escape"
    bindsym Return mode "default"
    bindsym Escape mode "default"
}
set $mode_system (e)xit, (r)eboot, (s)hutdown
bindsym $mod+Shift+Delete   mode "$mode_system"

# read 1 character and mark the current window with this character
bindsym $mod+semicolon exec i3-input -F 'mark %s' -l 1 -P 'Mark: '

# read 1 character and go to the window with the character
bindsym $mod+apostrophe exec i3-input -F '[con_mark="%s"] focus' -l 1 -P 'Goto: '

# Resizing windows in i3 using keyboard only
# https://unix.stackexchange.com/q/255344/150597

#i3 scratchpads
# move the currently focused window to the scratchpad
bindsym $mod+m move scratchpad

# Show the next scratchpad window or hide the focused scratchpad window.
# If there are multiple scratchpad windows, this command cycles through them.
bindsym $mod+n scratchpad show

for_window [instance="i3-scratchpad1"] floating enable
for_window [instance="i3-scratchpad1"] resize set 1000 600
for_window [instance="i3-scratchpad1"] move scratchpad
for_window [instance="i3-scratchpad1"] border pixel 5
exec st -n i3-scratchpad1
bindsym $mod+Ctrl+1 [instance="i3-scratchpad1"] scratchpad show

# Resizing by 1
bindsym $mod+Ctrl+Right resize shrink left 5 px or 5 ppt
bindsym $mod+Ctrl+Up resize shrink up 5 px or 5 ppt
bindsym $mod+Ctrl+Down resize shrink down 5 px or 5 ppt
bindsym $mod+Ctrl+Left resize shrink left 5 px or 5 ppt

# Resizing by 10
bindsym $mod+$altKey+Right resize grow left 5 px or 5 ppt
bindsym $mod+$altKey+Up resize grow up 5 px or 5 ppt
bindsym $mod+$altKey+Down resize grow down 5 px or 5 ppt
bindsym $mod+$altKey+Left resize grow left 5 px or 5 ppt

# Send apps to workspaces
# for_window [class="firefox"] move window to workspace number 9
assign [class="firefox"] number 9
assign [class="Tor Browser"] number 5
assign [class="obs"] number 7
for_window [title="nmtui"] floating enable, move position center
for_window [class="steam" class="Steam"] floating enable
for_window [title="tdrop"] floating enable
for_window [title="Event Tester"] floating enable
assign [class="steam" class="Steam"] number 8
# assign [class="Firefox"] number 8
#assign [class="jetbrains-phpstorm"] 2

# floating pop up automatically
for_window [window_role="pop-up"] floating enable
for_window [window_role="task_dialog"] floating enable
for_window [window_role="Preferences"] floating enable
for_window [window_role="bubble"] floating enable
for_window [window_type="dialog"] floating enable
for_window [window_type="menu"]	floating enable

# enable window icons for all windows
for_window [all] title_window_icon off

# class                 border  backgr. text    indicator child_border
client.focused          #4c7899 #285577 #ffffff #2e9ef4   #285577
client.focused_inactive #333333 #5f676a #ffffff #484e50   #5f676a
client.unfocused        #333333 #222222 #888888 #292d2e   #5f676a
client.urgent           #2f343a #900000 #ffffff #900000   #900000
client.placeholder      #000000 #0c0c0c #ffffff #000000   #0c0c0c

client.background       #ffffff

default_border pixel 5
default_floating_border pixel 5
# default_border normal 5
# default_floating_border normal 5

# Title bar text alignment
title_align center

# Gaps (Outer gaps are added to the inner gaps)
gaps inner 10
gaps outer 0

# Only enable gaps on a workspace when there is at least one container
smart_gaps on

# Activate smart borders (always)
smart_borders on

exec --no-startup-id $i3_scripts/startup.sh
exec --no-startup-id $i3_scripts/spawntest.sh
# exec --no-startup-id i3-msg "workspace number 1; exec alacritty"

# exec --no-startup-id i3-msg "workspace number 2; exec alacritty"

# exec --no-startup-id i3-msg "workspace number 3; exec alacritty"

# exec --no-startup-id i3-msg "workspace number 4; exec alacritty"

# exec --no-startup-id i3-msg 'workspace number 1'

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
# bar {
#         status_command i3status
# }

#######################################################################
# automatically start i3-config-wizard to offer the user to create a
# keysym-based config which used their favorite modifier (alt or windows)
#
# i3-config-wizard will not launch if there already is a config file
# in ~/.config/i3/config (or $XDG_CONFIG_HOME/i3/config if set) or
# ~/.i3/config.
#
# Please remove the following exec line:
#######################################################################
# exec i3-config-wizard

# vim: commentstring=#\ %s:
</pre>
</details>

<pre>
Logfile URL:
For spawntest1.sh :- https://logs.i3wm.org/logs/6241016298340352.bz2
For spawntest2.sh :- https://logs.i3wm.org/logs/6322967172612096.bz2

</pre>

<pre>
- Linux Distribution & Version: Arch Linux
- Are you using a compositor (e.g., xcompmgr or compton): Yes, picom (yshui, not forks) 8.2-1
- Relevant discussion : https://github.com/i3/i3/discussions/4531
</pre>

**Comment by RayZ0rr** [comment]
Did some testing with `st` instead of `alacritty`. Same issue. One more observation. This happens when 4 workspaces (or more?) are opened. If 3 workspaces are opened, say `1,3,5` in the above script (`spawntest2.sh`) then this doesn't happen. But if `1,3,5,7` are opened, then firefox opens in workspace number 7 (the last one where terminal was opened)

**Comment by Airblader** [comment]
In that spawntest1 scenario, since your spawntest script runs with lots of `sleep`s, at what point do you open Firefox – clearly after the entire script has run, or somewhere in the middle?

Firefox opens just fine on workspace 9:

```
02/08/2022 02:05:40 AM - Creating new workspace "9"
02/08/2022 02:05:40 AM - ../i3-4.20.1/src/con.c:con_new_skeleton:52 - opening window
02/08/2022 02:05:40 AM - ../i3-4.20.1/src/x.c:x_con_init:184 - Adding window 0x004000f9 to lists
02/08/2022 02:05:40 AM - ../i3-4.20.1/src/x.c:x_con_init:188 - adding new state for window id 0x004000f9
02/08/2022 02:05:40 AM - ../i3-4.20.1/src/con.c:_con_attach:109 - it's a workspace. num = 9
02/08/2022 02:05:40 AM - ../i3-4.20.1/src/workspace.c:_workspace_apply_default_orientation:66 - Auto orientation. Workspace size set to (1366,768), setting layout to 6.
02/08/2022 02:05:40 AM - ../i3-4.20.1/src/manage.c:manage_window:306 - focused on ws 9: 0x5652cd11ae70 / 9
```

However, someone sends a client message later on, requesting the window to move to another workspace (EWMH index = 3 means the fourth desktop, which is workspace number 4):

```
02/08/2022 02:05:40 AM - ClientMessage for window 0x0560002c
02/08/2022 02:05:40 AM - ../i3-4.20.1/src/handlers.c:handle_client_message:831 - Request to move window 90177580 to EWMH desktop index 3
02/08/2022 02:05:40 AM - ../i3-4.20.1/src/con.c:_con_move_to_con:1233 - target originally = 0x5652cd115280 / (null) / type 2
02/08/2022 02:05:40 AM - ../i3-4.20.1/src/con.c:_con_move_to_con:1277 - Re-attaching container to 0x5652cd113830 / 4
```

The behavior of i3 as the window manager is correct here – the window is requested to be moved, and i3 honors that request. Client messages can be sent by any X client, but it should be safe to assume that it is Firefox itself that sends this message here.

Was there a Firefox update recently with which this broke? It looks a bit as if Firefox is trying to be clever in figuring out where it should be.

**Comment by RayZ0rr** [comment]
I made sure to open firefox after the script was run. I also saw that, for spawntest1, firefox opens in workspace 9 as configured in i3/config and then jumps to last opened workspace. Also, this only happens when number of workspaces opened is greater than three. For eg, the following works fine: 
```bash
#!/usr/bin/env bash

i3-msg "workspace number 1; exec alacritty"

sleep 1
i3-msg "workspace number 3; exec alacritty"
i3-msg "workspace number 3; exec alacritty"

sleep 1
i3-msg "workspace number 6; exec alacritty"
i3-msg "workspace number 6; exec st -e htop"

sleep 1
i3-msg "workspace number 1"
```
This works no matter how many windows are opened.
But add one more workspace and then firefox 'jumping behavior' starts: 
```bash
#!/usr/bin/env bash

i3-msg "workspace number 1; exec alacritty"

sleep 1
i3-msg "workspace number 3; exec alacritty"
i3-msg "workspace number 3; exec alacritty"

sleep 1
i3-msg "workspace number 6; exec alacritty"
i3-msg "workspace number 6; exec st -e htop"

sleep 1
i3-msg "workspace number 2; exec alacritty"

sleep 1
i3-msg "workspace number 1"
```
Here, firefox jumps to workspace number 6.

**Comment by Airblader** [comment]
Given that we receive a client message (presumably from Firefox), I see no issue with i3 here. Can you file a bug report with Firefox and cross-link them?

**Comment by RayZ0rr** [comment]
Okay, but as this happens only when there are more than 3 workspaces opened in i3 through the startup script, I thought it might have something to do with i3.

**Comment by Airblader** [comment]
Looking at the window manager first was certainly reasonable, but the logs clearly say someone told us to move the window. :-)

**Comment by RayZ0rr** [comment]
Okay, will close this for now. I will do some more debugging and report back.

**Comment by RayZ0rr** [comment]
Okay, did some more testing. This can be produced without the startup script. The only condition required to reproduce is more than 3 workspaces opened. Other ways to reproduce: 
1. Type in terminal
```sh
i3-msg "workspace number 1, exec alacritty"
i3-msg "workspace number 2, exec alacritty"
i3-msg "workspace number 3, exec alacritty"
# If you open firefox here, it opens in proper workspace.
i3-msg "workspace number 4, exec alacritty"
# If you open firefox here, it opens in workspace number 4.
```
2. Have this in i3 config. ( The applications and workspace numbers can be anything else )
```sh
assign [class="Thunar"] number 4
assign [class="mpv"] number 7
assign [class="Steam"] number 8
assign [class="firefox"] number 9
```
Open all these apps before firefox,
```
mpv --player-operation-mode=pseudo-gui &
thunar &
steam &
# If you open firefox here, then no problem
alacritty & # This opens one more workspace
# Open firefox here and jumps to last workspace opened
```

**Comment by RayZ0rr** [comment]
So, the issue in general is: 
**Irrespective of number, firefox opens in 4th workspace( in ascending order ) when there are more than 3 workspaces opened**
@Airblader Can you share the default i3 config file, so that I can test if there's something wrong in my config?

**Comment by Airblader** [comment]
You can run `i3-config-wizard` to create a new config.

**Comment by ghost** [comment]
Bump
