### ISSUE TITLE
New i3 session opening when first is killed

### ISSUE THREAD

**Issue by michaelBelsanti** [i3/i3#4909]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

If i3 is started by a display manager, killing it in an attempt to log out results in a new i3 session starting instantly. The new session will retain windows and apps that will open, but will rerun any exec commands in my config. Killing the second session will send me back to my display manager.

This does not happen if i3 is started by startx. I've looked for any X11 configuration files or startup scripts that could be running two i3 sessions, but did not find any. 

## Expected Behavior

i3 should close entirely, and I should be sent back to my display manager.

## Reproduction Instructions

Start i3 using a display manager, then try to close it as you would to log out.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: Binary i3 version:  4.20.1 (2021-11-03) © 2009 Michael Stapelberg and contributors
</pre>

<details><summary>Config file</summary><pre>
#=============================== Applications ================================#
#---------------------------- Default applications ---------------------------#
set $taskbar        $HOME/.config/polybar/i3.sh
set $wallpaper      nitrogen --restore
set $compositor     picom  --unredir-if-possible --experimental-backends
set $notifications  dunst
set $scratchpad     tilda
set $session        lxsession
set $keybinds	    sxhkd
#-----------------------------------------------------------------------------#

#----------------------------- Startup applications --------------------------#
exec_always --no-startup-id xrdb -load ~/.config/X11/xresources 
exec_always --no-startup-id $taskbar
exec_always --no-startup-id $keybinds
exec        --no-startup-id $wallpaper 
exec        --no-startup-id $notifications
exec        --no-startup-id $scratchpad
exec        --no-startup-id $compositor
exec        --no-startup-id $session
exec	    --no-startup-id xrandr --output DP-4 -r 240

exec        --no-startup-id obs --startreplaybuffer
exec        --no-startup-id betterlockscreen -u ~/wallpapers/lockscreen.png --off 5
#-----------------------------------------------------------------------------#
#=============================================================================#

#================================= Appearance ================================#
#------------------------------- Colors & font -------------------------------#
set $border     #F28FAD
set $bg         #1E1D2F
set $fg         #D9E0EE
set $indicator  #96CDFB

#                       border    background  text  indicator
client.focused          $border   $border     $fg   $indicator  
client.unfocused        $bg       $bg         $fg   $indicator   
client.focused_inactive $border   $bg         $fg   $indicator   
client.urgent           $border   $bg         $fg   $indicator   

font pango:JetBrains Mono 10
#-----------------------------------------------------------------------------#

#----------------------------- Window appearance -----------------------------#
# Removes titlebars
for_window [class="^.*"] border pixel 2
 hide_edge_borders both
gaps inner 6
smart_gaps on
#-----------------------------------------------------------------------------#
#=============================================================================#

#================================= Controls ==================================#
set $mod Mod4
floating_modifier $mod
# Note:
# Application keybinds are set using sxhkd which is launched by i3 on startup.
#-----------------------------------------------------------------------------#

#---------------------------- Workspace navigation ---------------------------#
# switch to workspace
bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4
bindsym $mod+5 workspace number $ws5
bindsym $mod+6 workspace number $ws6
bindsym $mod+7 workspace number $ws7
bindsym $mod+8 workspace number $ws8
bindsym $mod+9 workspace number $ws9
bindsym $mod+0 workspace number $ws10
bindsym $mod+ctrl+1 workspace number $ws11
bindsym $mod+ctrl+2 workspace number $ws12
bindsym $mod+ctrl+3 workspace number $ws13
bindsym $mod+ctrl+4 workspace number $ws14
bindsym $mod+ctrl+5 workspace number $ws15
bindsym $mod+ctrl+6 workspace number $ws16
bindsym $mod+ctrl+7 workspace number $ws17
bindsym $mod+ctrl+8 workspace number $ws18
bindsym $mod+ctrl+9 workspace number $ws19
bindsym $mod+ctrl+0 workspace number $ws20

# move focused container to workspace
# bindsym $mod+s layout stacking
bindsym $mod+Shift+1 move container to workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3
bindsym $mod+Shift+4 move container to workspace number $ws4
bindsym $mod+Shift+5 move container to workspace number $ws5
bindsym $mod+Shift+6 move container to workspace number $ws6
bindsym $mod+Shift+7 move container to workspace number $ws7
bindsym $mod+Shift+8 move container to workspace number $ws8
bindsym $mod+Shift+9 move container to workspace number $ws9
bindsym $mod+Shift+0 move container to workspace number $ws10
bindsym $mod+ctrl+Shift+1 move container to workspace number $ws11
bindsym $mod+ctrl+Shift+2 move container to workspace number $ws12
bindsym $mod+ctrl+Shift+3 move container to workspace number $ws13
bindsym $mod+ctrl+Shift+4 move container to workspace number $ws14
bindsym $mod+ctrl+Shift+5 move container to workspace number $ws15
bindsym $mod+ctrl+Shift+6 move container to workspace number $ws16
bindsym $mod+ctrl+Shift+7 move container to workspace number $ws17
bindsym $mod+ctrl+Shift+8 move container to workspace number $ws18
bindsym $mod+ctrl+Shift+9 move container to workspace number $ws19
bindsym $mod+ctrl+Shift+0 move container to workspace number $ws20

# move focused container and stay focues
bindsym $mod+mod1+1 move container to workspace number $ws1; workspace $ws1
bindsym $mod+mod1+2 move container to workspace number $ws2; workspace $ws2
bindsym $mod+mod1+3 move container to workspace number $ws3; workspace $ws3
bindsym $mod+mod1+4 move container to workspace number $ws4; workspace $ws4
bindsym $mod+mod1+5 move container to workspace number $ws5; workspace $ws5
bindsym $mod+mod1+6 move container to workspace number $ws6; workspace $ws6
bindsym $mod+mod1+7 move container to workspace number $ws7; workspace $ws7
bindsym $mod+mod1+8 move container to workspace number $ws8; workspace $ws8
bindsym $mod+mod1+9 move container to workspace number $ws9; workspace $ws9
bindsym $mod+mod1+0 move container to workspace number $ws10; workspace $ws10
bindsym $mod+ctrl+mod1+1 move container to workspace number $ws11; workspace $ws11
bindsym $mod+ctrl+mod1+2 move container to workspace number $ws12; workspace $ws12
bindsym $mod+ctrl+mod1+3 move container to workspace number $ws13; workspace $ws13
bindsym $mod+ctrl+mod1+4 move container to workspace number $ws14; workspace $ws14
bindsym $mod+ctrl+mod1+5 move container to workspace number $ws15; workspace $ws15
bindsym $mod+ctrl+mod1+6 move container to workspace number $ws16; workspace $ws16
bindsym $mod+ctrl+mod1+7 move container to workspace number $ws17; workspace $ws17
bindsym $mod+ctrl+mod1+8 move container to workspace number $ws18; workspace $ws18
bindsym $mod+ctrl+mod1+9 move container to workspace number $ws19; workspace $ws19
bindsym $mod+ctrl+mod1+0 move container to workspace number $ws20; workspace $ws20
#-----------------------------------------------------------------------------#

#--------------------------- Container manipulation --------------------------#
# kill
bindsym $mod+q kill
# change focused window
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right
# alternatively, you can use the cursor keys (why would you tho)
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right
# move focused window
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right
# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right
# horizontal and vertical splits
bindsym $mod+x split h
bindsym $mod+z split v
# toggle fullscreen
bindsym $mod+f fullscreen toggle
# toggle floating
bindsym $mod+Shift+space floating toggle
# change focus between tiling / floating windows
bindsym $mod+semicolon focus mode_toggle
# focus the parent container
bindsym $mod+Shift+a focus parent
# focus the child container
bindsym $mod+a focus child
#-----------------------------------------------------------------------------#

#------------------------------ Miscellaneous --------------------------------#
# refresh i3
bindsym $mod+Shift+r restart; exec pkill -USR1 "sxhkd"

mode "resize" {
        # Vim keys
        bindsym h resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym j resize shrink height 10 px or 10 ppt
        bindsym l resize grow width 10 px or 10 ppt

        # Arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # Leave resize mode
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}
bindsym $mod+r mode "resize"
#-----------------------------------------------------------------------------#
#=============================================================================#

#================================ Workspaces =================================#
#-----------------------------------------------------------------------------#
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"
set $ws11 "11"
set $ws12 "12"
set $ws13 "13"
set $ws14 "14"
set $ws15 "15"
set $ws16 "16"
set $ws17 "17"
set $ws18 "18"
set $ws19 "19"
set $ws20 "20"

# monitor 1 workspaces
workspace $ws1  output  DP-4
workspace $ws2  output  DP-4
workspace $ws3  output  DP-4
workspace $ws4  output  DP-4
workspace $ws5  output  DP-4
workspace $ws11 output  DP-4
workspace $ws12 output  DP-4
workspace $ws13 output  DP-4
workspace $ws14 output  DP-4
workspace $ws15 output  DP-4

# monitor 2 workspaces
workspace $ws6  output  HDMI-0
workspace $ws7  output  HDMI-0
workspace $ws8  output  HDMI-0
workspace $ws9  output  HDMI-0
workspace $ws10 output  HDMI-0
workspace $ws16 output  HDMI-0
workspace $ws17 output  HDMI-0
workspace $ws18 output  HDMI-0
workspace $ws19 output  HDMI-0
workspace $ws20 output  HDMI-0

# floating applications
for_window [instance="origin.exe"] floating enable
for_window [instance="EADesktop.exe"] floating enable
for_window [instance="pavucontrol"] floating enable
for_window [instance="$scratchpad"] floating enable
for_window [instance="TeamViewer"] floating enable
for_window [instance="qalculate-gtk"] floating enable
for_window [instance="yuzu"] floating enable
for_window [instance="steam"] floating enable
for_window [instance="steamwebhelper"] floating enable
for_window [instance="nvidia-settings"] floating enable
for_window [instance="lxappearance"] floating enable
for_window [instance="vibrantLinux"] floating enable
#-----------------------------------------------------------------------------#
#=============================================================================#
</pre>
</details>

The issue still occured using a default config file.

<pre>
Logfile URL: https://logs.i3wm.org/logs/6225736830550016.bz2
</pre>

<pre>
- Linux Distribution & Version: Arch Linux with 5.16.13-arch1-1 kernel
- Are you using a compositor (e.g., xcompmgr or compton): Picom, but it also happens without it.
</pre>

**Comment by psychon** [comment]
> i3 should close entirely, and I should be sent back to my display manager.

That's exactly what happens for me.

So... uhm...

How's your first and second `i3` started? Do both have the same parent process?

For example, right now for me, `i3` is started by `lightdm`. (Oh and: What display manager are you using?)
```
$ pstree  | grep i3 -3
        |-cron
        |-dbus-daemon
        |-gvim---{gvim}
        |-i3bar---sh---i3status
        |-lightdm-+-Xorg---16*[{Xorg}]
        |         |-lightdm-+-i3
        |         |         |    |-update-notifier
        |         |         |    |-xautolock
        |         |         |    `-xss-lock---2*[{xss-lock}]
```

**Comment by michaelBelsanti** [comment]
I'm realizing that this might be a me issue. I'm using Ly as my display manager and it's set to just use my xinit. My xinit doesn't have i3 in it but it's starting anyways. Now I just have to figure out what the hell is starting i3 in every x session...

**Comment by michaelBelsanti** [comment]
In both i3 sessions I get this, meaning it's starting with Ly. I don't see why two are starting...
```
$ pstree | grep i3 -3
        |-lxsession---2*[{lxsession}]
        |-ly---ly-+-Xorg---{Xorg}
        |         `-i3
        |-nm-applet---3*[{nm-applet}]
```

**Comment by michaelBelsanti** [comment]
Choosing to use xinit as my session in Ly starts i3, and choosing i3 starts two i3 sessions. Since it's only me and xinit works fine as a workaround I'll just close it. Thanks for showing me that pstree command, I had no idea it existed.

**Comment by psychon** [comment]
I looked a bit through Ly's source code. Apparently, it simply starts `x_cmd_setup` to start an X11 session. And that defaults to this shell script: https://github.com/fairyglade/ly/blob/master/res/xsetup.sh

Anyway, it sources your `~/.xsession` here: https://github.com/fairyglade/ly/blob/609b3f9ddcb8e953884002745eca5fde8480802f/res/xsetup.sh#L94-L96

And after that is done, it executed whatever it got as arguments. I guess this is how its `i3` session works: https://github.com/fairyglade/ly/blob/609b3f9ddcb8e953884002745eca5fde8480802f/res/xsetup.sh#L101

So, random guess, your `~/.xsession` file starts `i3` even though it shouldn't. Either remove that or replace it with `exec i3` so that `xsetup.sh` cannot continue afterwards (but this will completely break/override the session selection feature).

Edit: However, no idea how that fits your `pstree` output. I would have expected `xsetup.sh` to show up as a parent process...

**Comment by michaelBelsanti** [comment]
I'm a little ashamed to say I found the problem. I had been messing with X related files a lot recently and at some point I made a .xprofile that included i3. I didn't even know there was such thing as .xprofile, I only remembered .xsession. Thanks for all the help!
