### ISSUE TITLE
`i3-msg '[title="some_title"] scratchpad show' not behaving correctly

### ISSUE THREAD

**Issue by YasserKa** [i3/i3#4951]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

I have a window (example Emacs)

If I use `i3-msg '[title="Emacs"] scratchpad show'`

I get the following message:
```
ERROR: (null)
[{"success":false}]
```
I move it to the scratchpad using `i3-msg '[title="Emacs"] move scratchpad'`. It gets moved as expected, then `i3-msg '[title="Emacs"] scratchpad show'` starts working correctly by showing/hiding the window.

I toggle the floating of the window. `scratchpad show` stops working again.
## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: Binary i3 version:  4.20.1 (2021-11-03) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.20.1 (2021-11-03) (pid 1429)
Loaded i3 config:
  /home/yasser/.config/i3/config (main) (last modified: Mon 18 Apr 2022 01:02:47 AM CEST, 699 seconds ago)
  /home/yasser/dotfiles/i3/.config/i3/focus_on_window_activation_config (included) (last modified: Sun 17 Apr 2022 05:46:35 PM CEST, 26871 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<details><summary>Config file</summary><pre>

set $mod Mod4
bindsym $mod+Shift+minus move scratchpad
bindsym $mod+Shift+space floating toggle
bindsym $mod+Shift+w reload
bindsym $mod+Return exec $TERMINAL

# # Change focus
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right
bindsym $mod+h focus left
bindsym $mod+f fullscreen toggle
</pre>
</details>

<pre>
Logfile URL: https://logs.i3wm.org/logs/6292813603930112.bz2
</pre>

<pre>
- Linux Distribution & Version:
Linux yasser-pc 5.17.3-arch1-1 #1 SMP PREEMPT Thu, 14 Apr 2022 01:18:36 +0000 x86_64 GNU/Linux
- Are you using a compositor (e.g., xcompmgr or compton):
https://aur.archlinux.org/packages/picom-git
</pre>

EDIT: Added minimalist  config

P.S. I might have a misunderstanding of how `scratchpad show` works.

**Comment by Airblader** [comment]
I don't really understand your issue, and you didn't provide all required information like expected behavior or instructions to reproduce. It _sounds_ like everything works correctly, because you're trying to `scratchpad show` a window that has never been moved into the scratchpad.

Please update the issue with all required information and we can consider reopening.

**Comment by YasserKa** [comment]
You are right. I thought that scratchpad toggles it by default without it being in the scratchpad in the first place. I misread the documentation. 

I apologize for the inconvenience.
