### ISSUE TITLE
SIGABRT and calloc failure in parse_file()

### ISSUE THREAD

**Issue by zhrvn** [i3/i3#5002]
## I'm submitting a…
<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Using a config with nested variables (see config) causes i3 to crash either with a heap allocation failure (in calloc) or SIGABRT (heap smashing).

## Expected Behavior
Using a config with nested variables (see config) doesn't cause i3 to crash.

## Reproduction Instructions
Start i3 with the following configs.

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.20-96-gce2665ca © 2009 Michael Stapelberg and contributors
</pre>

<details>
<summary>Config file causing allocation failure</summary>
<pre>
# i3 config file (v4)
set $xxxxxxxxxx 1
set $$xxxxxxxxxx 2
set $$$xxxxxxxxxx 3
set $$$$xxxxxxxxxx 4
set $$$$$xxxxxxxxxx 5
set $$$$$$xxxxxxxxxx 6
set $$$$$$$xxxxxxxxxx 7
set $$$$$$$$xxxxxxxxxx 8
set $$$$$$$$$xxxxxxxxxx 9
set $$$$$$$$$$xxxxxxxxxx 10
set $$$$$$$$$$$xxxxxxxxxx 11
set $$$$$$$$$$$$xxxxxxxxxx 12
set $$$$$$$$$$$$$xxxxxxxxxx 13
set $$$$$$$$$$$$$$xxxxxxxxxx 14
</pre>
</details>

<details>
<summary>Config file causing SIGABRT</summary>
<pre>
# i3 config file (v4)
set $xxxxxxxxxx 1
set $$xxxxxxxxxx 2
set $$$xxxxxxxxxx 3
</pre>
</details>

<pre>
Logfile URL: https://github.com/i3/i3/files/8869940/sigabrt-log.txt (SIGABRT) https://logs.i3wm.org/logs/6302401581547520.bz2 (calloc failure)
Strace URL: https://github.com/i3/i3/files/8869954/sigabrt-strace.txt (SIGABRT) https://github.com/i3/i3/files/8869961/calloc-strace.txt (calloc failure)
Backtrace URL: https://github.com/i3/i3/files/8869971/sigabrt-backtrace.txt (SIGABRT)
</pre>

<pre>
- Linux Distribution & Version: Arch Linux
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by Airblader** [comment]
Thanks for the report. Indeed we should not crash, but just to point it out, we do not support nested variables names.
