### ISSUE TITLE
Some keybindings won't work at all

### ISSUE THREAD

**Issue by secnigma** [i3/i3#5053]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Some keybindings won't work at all. My Mod key is Win key (default).

- When pressing $mod+5 to switch to workspace number 5, it won't switch to workspace number 5.
- When pressing $mod+Shift+5 to move a window to workspace number 5, it won't switch.
- When pressing $mod+6 to switch to workspace number 6, it won't switch to workspace number 5.
- When pressing $mod+Shift+6 to move a window to workspace number 6, it won't switch.
- When pressing $mod+Shift+q to exit the focused window,  it won't exit the application window.
- When pressing $mod+Shift+e to exit the i3 session,  it won't exit i3 session.
- When pressing $mod+Shift+r to reload i3,  it won't reload i3.

## Expected Behavior

- When pressing $mod+5 to switch to workspace number 5, it should switch to workspace number 5.
- When pressing $mod+Shift+5 to move a window to workspace number 5, it should switch.
- When pressing $mod+6 to switch to workspace number 6, it should switch to workspace number 5.
- When pressing $mod+Shift+6 to move a window to workspace number 6, it should switch.
- When pressing $mod+Shift+q to exit the focused window,  it should exit the application window.
- When pressing $mod+Shift+e to exit the i3 session,  it should exit i3 session.
- When pressing $mod+Shift+r to reload i3,  it should reload i3.

## Reproduction Instructions

- Press $mod+5 to switch to workspace number 5
- Press $mod+Shift+5 to move a window to workspace number 5
- Press $mod+6 to switch to workspace number 6
- Press $mod+Shift+6 to move a window to workspace number 6
- Press $mod+Shift+q to exit the focused window
- Press $mod+Shift+e to exit the i3 session
- Press $mod+Shift+r to reload i3

## Environment

OS: Fedora Linux 36 (Thirty Six) x86_64
Host: 81MT Lenovo V145-15AST
Kernel: 5.18.10-200.fc36.x86_64
Packages: 1599 (rpm), 6 (flatpak)
Shell: zsh 5.8.1
Resolution: 1366x768
WM: i3
Terminal: alacritty
CPU: AMD A6-9225 RADEON R4 2C+3G (2) @ 2.600GHz
GPU: AMD ATI Radeon R2/R3/R4/R5 Graphics
Memory: 2254MiB / 3697MiB

#### Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.20.1 (2021-11-03) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.20.1 (2021-11-03) (pid 16714)
Loaded i3 config:
  /home/neo/.config/i3/config (main) (last modified: Thu 14 Jul 2022 01:10:00 PM IST, 111253 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

## Config file
<details><summary>Config file</summary><pre>
https://pastebin.com/lgrUmbrU
</pre>
</details>

## Log file

<pre>
Logfile URL: https://logs.i3wm.org/logs/631262957285104.bz2
</pre>

<pre>
- Linux Distribution & Version: Fedora 36
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

## Things I've tried:
- The keys are working fine in other places. So, hopefully not a hardware issue.
- Used `xev` and checked the Keybindings that are not working and they are not showing up in xev.
However, when the key bindings are pressed individually, they are working fine.
Eg. `Win+5` is not getting registered in `xev`, but when pressing `Win` or `5` individually, they are getting registered.

- Reinstalled`i3`
- Reset the configuration to default

**Comment by Airblader** [comment]
> Used xev and checked the Keybindings that are not working and they are not showing up in xev.

If this happens also when you didn't bind the keys in i3 yet it means that something else is grabbing those keys already. If xev can't see it, neither can i3.

**Comment by secnigma** [comment]
Oh. Ok.
Thank you for your reply.
Is there anyway I could identify which application is grabbing the key bindings?

**Comment by Airblader** [comment]
You can try if `xdotool key XF86LogGrabInfo` gives you something useful. Other than that I know of no way.

**Comment by secnigma** [comment]
> You can try if `xdotool key XF86LogGrabInfo` gives you something useful. Other than that I know of no way.

Shows empty output.
Anyway thanks for your help.

**Comment by secnigma** [comment]
Ok this is weird.
I've found that I can switch to the workspace but in a weird way.

I was trying to switch to workspace `5` by pressing `Win+5`, but obviously that didn't work.
I was in Workspace `1` and my terminal was open.
- So, I've tried the reverse I've pressed and hold down `5` in the terminal to the point that my terminal was being flooded with `5`s.
- Then I pressed and hold down `Win` key.
- After that, I've released `5` and pressed `5` again and it worked!

I've checked this with other shortcuts that wasn't working and this trick worked with them too.

Weirdly enough, this is happening only when I'm in an active terminal or text editor window.

**Comment by Airblader** [comment]
Do you have any modifications to xmodmap, key repeat or anything of that sort? Does it work if you use a different modifier key like Alt?

**Comment by secnigma** [comment]
I've changed my Mod key from `Win` key to `Ctrl` and it worked!
Now all of the key bindings are working as expected.
I've got no idea how this worked but thanks a lot man!

**Comment by Airblader** [comment]
It sounds a whole lot like your terminal is grabbing the Win key somehow, you might want to check its settings. 

I'll close this since nothing points towards an i3 bug here, just so you know.
