### ISSUE TITLE
Window sometimes opened on a different workspace (than the currently active one)

### ISSUE THREAD

**Issue by jonnykl** [i3/i3#5065]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Sometimes opened windows are opened on the wrong workspace. This happens relativly often. Most time (or always?) this happens after I unlock the the screen (i.e. after waking up from sleep) (but not always after I unlock the screen). I open up a terminal window (terminator v2.1.1) on workspace 1. This terminal is always opened on the correct workspace. Then I switch to another workspace (say 2) and open up another terminal. This time the terminal will be opened on the previous workspace (1). If I switch back to workspace 1, close the "wrong" terminal, switch to workspace 2 and open a new terminal again, the same bug occurs. I have to switch to workspace 1 and move the "wrong" terminal to another workspace. After that, everything is normal again. Terminals opened at an arbitrary workspace will show up at the correct workspace. I don't know if this is a problem that only occurs when opening a terminal, because thats the application I open most often and every time when I start using the computer. I tried to reproduce the bug using Google Chrome which was not possible.

## Expected Behavior

The (terminal) window opens at the current active workspace.

## Reproduction Instructions

It looks like the bug can be reproduced by ending the i3 session and starting a new one. But it also occurs sometimes after unlocking the screen. I didn't find a way to reproduce the bug after unlocking the screen (occurs only sometimes and I don't know under which conditions).

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
Binary i3 version:  4.20.1 (2021-11-03) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.20.1 (2021-11-03) (pid 423777)
Loaded i3 config:
  /home/jonny/.config/i3/config (main) (last modified: Thu 04 Aug 2022 01:39:16 PM CEST, 623 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

i3 config: https://pastebin.com/fZVALTZA (stock, replace Mod1 by Mod4, comment out xdg auto start and wizard)
logfile: https://logs.i3wm.org/logs/6304662894411776.bz2

<pre>
- Linux Distribution & Version: Ubuntu 22.04.1 LTS (but also occurred using Ubuntu 20.04 LTS before)
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by Airblader** [comment]
I haven't looked at the log file (and won't have time to do so), but from both experience and your description this is likely an application "issue" because the application requests that the window be opened on that workspace.

**Comment by stapelberg** [comment]
From your log file, it seems like your terminal emulator opens a window with an X11 leader window that has the startup id of the original terminal window, instead of the startup id of your current terminal emulator process:

```
08/04/2022 01:38:40 PM - ../src/commands_parser.c:parse_command:241 - COMMAND: *workspace number "2"*
[…]
08/04/2022 01:38:38 PM - ../src/commands_parser.c:parse_command:241 - COMMAND: *exec i3-sensible-terminal*
[…]
08/04/2022 01:38:40 PM - ../src/startup.c:startup_sequence_get:281 - No _NET_STARTUP_ID set on window 0x01000070
08/04/2022 01:38:40 PM - ../src/startup.c:startup_sequence_get:297 - Checking leader window 0x01000001
08/04/2022 01:38:40 PM - ../src/manage.c:manage_window:227 - startup workspace = 1
08/04/2022 01:38:40 PM - ../src/manage.c:manage_window:277 - Initial geometry: (0, 0, 722, 453)
08/04/2022 01:38:40 PM - Checking window 0x01000070 (class X-terminal-emulator)
08/04/2022 01:38:40 PM - dock status does not match
08/04/2022 01:38:40 PM - Checking window 0x01000070 (class X-terminal-emulator)
08/04/2022 01:38:40 PM - dock status does not match
08/04/2022 01:38:40 PM - ../src/manage.c:manage_window:332 - Using workspace on which this application was started (1)
08/04/2022 01:38:40 PM - ../src/manage.c:manage_window:334 - focused on ws 1: 0x55abc8470530 / (null)
```

Which terminal emulator do you use? Perhaps it opens new windows from the same process, and ignores the startup id in that code path.

To mitigate the issue, you can use `exec --no-startup-id`, see https://i3wm.org/docs/userguide.html#exec

**Comment by jonnykl** [comment]
I'm using the gnome terminator.

Just tried to reproduce the bug (as described) but currently everything works as expected (without `--no-startup-id`). Same OS, i3 and terminator version. If the bug occurrs again, I'll try the `--no-startup-id` option.
