### ISSUE TITLE
With "mouse_warping output" dragging tiled windows with mouse to other monitors is weird

### ISSUE THREAD

**Issue by JamiKettunen** [i3/i3#5089]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

With multiple monitors and `mouse_warping output` configured ([default behavior](https://i3wm.org/docs/userguide.html#_mouse_warping)) dragging a tiled window with mouse to another monitor's inner most drop region (an empty workspace or another running program's middle) after releasing `Mouse 1` button warps the mouse cursor to the middle of an application on the previous monitor the window was on.

### Here's some screenshots to illustrate the issue on a fully stock config:
Dragging tiled window with mouse from Monitor 1 (left) to inner most drop region of an application on Monitor 2 (right):
![2022-08-19-131116_3840x1080_scrot.png](https://user-images.githubusercontent.com/47358222/185603859-74a01f2b-4206-4d3e-bddd-4a2299686bc5.png)
After releasing `Mouse 1` cursor incorrectly jumps back to Monitor 1 (left) while the application on Monitor 2 (right) remains focused:
![2022-08-19-131146_3840x1080_scrot](https://user-images.githubusercontent.com/47358222/185603941-81e8a2dd-bb69-45dd-b759-3b4f6dc04094.png)

Dragging tiled window with mouse from Monitor 1 (left) to inner most drop region of empty workspace on Monitor 2 (right):
![2022-08-19-131210_3840x1080_scrot](https://user-images.githubusercontent.com/47358222/185604533-2a3eac0e-5a5b-403e-9ec6-d9acae3c8bb2.png)
After releasing `Mouse 1` cursor incorrectly jumps back to Monitor 1 (left) while the application on Monitor 2 (right) remains focused:
![2022-08-19-131225_3840x1080_scrot](https://user-images.githubusercontent.com/47358222/185604542-24218a82-fd23-49a1-a229-88292334a60a.png)

My current workaround to avoid the constant incorrect mouse warping on latest [i3 next branch commit](https://github.com/i3/i3/commit/ebcd1d43ea9fd08a1dbb1212fb61e42f05a22684) is setting `mouse_warping none` in my config.

## Expected Behavior

The cursor should not warp at all since the focused window doesn't change, in fact the tiled window that is dragged to one of another monitor's inner most drop regions still remains active but only the cursor incorrectly warps back to the previous monitor.

## Reproduction Instructions

With at least 2 monitors, open a single tiled program (e.g. some terminal) on one monitor and drag it with `Mouse 1` to another monitor's empty workspace. Same occurs if the other monitor already has a running program and you drag a  the 

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.20-102-gebcd1d43 © 2009 Michael Stapelberg and contributors
(Getting version from running i3, press ctrl-c to abort…)
Running i3 version: 4.20-102-gebcd1d43 (pid 24946)
Loaded i3 config:
  /etc/i3/config (main) (last modified: Fri 19 Aug 2022 01:10:06 PM EEST, 197 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3-with-/i3
</pre>

<details><summary>Config file</summary><pre>
https://termbin.com/tqjd
</pre>
</details>

<pre>
Logfile URL: https://logs.i3wm.org/logs/4786582477340672.bz2
</pre>

<pre>
- Linux Distribution & Version: Arch Linux (rolling)
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by JamiKettunen** [comment]
@orestisfl Since you contributed the feature (thanks btw I really like it overall!) :) unsure if you have multiple monitors to see the issue for yourself however

**Comment by stapelberg** [comment]
@orestisfl Did you have a look at this issue, too? Do you think it’s fixable within the next week or two? I’d like to get the v4.21 release unblocked soon. Thanks :)

**Comment by stapelberg** [comment]
Is this one on your radar for v4.21, too, @orestisfl, or should we move it to after the release?

**Comment by orestisfl** [comment]
I might have a fix for this but I couldn't confirm yet because I can't simulate mouse warping with xephyr, I'll try it out soon on physical monitors and let you know
