### ISSUE TITLE
Problem with TelegramDesktop WebApp in i3wm

### ISSUE THREAD

**Issue by JustCryingCat** [i3/i3#5090]
## I'm submitting a…
<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
I get this result. Just a white window and a message in the console "Could not determine the accessibility bus address" (Compton has nothing to do with)
![image](https://user-images.githubusercontent.com/90184510/185618285-148e5bc8-ca7c-4f1a-9a17-fed7a9fa1260.png)

## Expected Behavior
![image](https://user-images.githubusercontent.com/90184510/185618392-d49316fb-ebfd-4b97-a47f-6c8b801e64b4.png)

## Reproduction Instructions
1. I downloaded telegram-desktop from snap
2. Running /tsetup.4.1.0/Telegram/Telegram
3. Open Web App durger king bot

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
Binary i3 version:  4.20.1 (2021-11-03) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.20.1 (2021-11-03) (pid 24327)
Loaded i3 config:
  /home/egorka/.config/i3/config (main)
</pre>

<details><summary>Config file</summary><pre>
[https://pastebin.com/MhSDh7Dv](https://pastebin.com/MhSDh7Dv)
</pre>
</details>

## Logs
<pre>
i3 Logfile URL: [https://logs.i3wm.org/logs/6279115220975616.bz2](https://logs.i3wm.org/logs/6279115220975616.bz2)
</pre>

Telegram Logs In ~/.local/share/TelegramDesktop/DebugLog/log_*_*.txt:
<pre>
[21:46:55.257 00-0004272] BotWebView Error: Could not parse """".
[21:46:55.257 00-0004273] BotWebView Error: Could not parse """".
[21:46:55.290 00-0004274] BotWebView Error: Could not parse """".
</pre>

In terminal:
<pre>
Could not determine the accessibility bus address
</pre>

In journalctl:
<pre>
авг 19 18:03:14 egorka-P5K WebKitWebProces[32702]: Locale not supported by C library.
                                                              Using the fallback 'C' locale.
авг 19 18:03:14 egorka-P5K WebKitNetworkPr[32699]: GDBus.Error:org.freedesktop.portal.Error.NotAllowed: This call is not available inside the sandbox
авг 19 18:03:14 egorka-P5K audit[32702]: SECCOMP auid=1000 uid=1000 gid=1000 ses=9 subj=? pid=32702 comm="WebKitWebProces" exe="/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/WebKit>
авг 19 18:03:14 egorka-P5K kernel: audit: type=1326 audit(1660914194.306:167): auid=1000 uid=1000 gid=1000 ses=9 subj=? pid=32702 comm="WebKitWebProces" exe="/usr/lib/x86_64-l>
авг 19 18:03:14 egorka-P5K audit[32702]: SECCOMP auid=1000 uid=1000 gid=1000 ses=9 subj=? pid=32702 comm="eadedCompositor" exe="/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/WebKit>
авг 19 18:03:14 egorka-P5K audit[32702]: SECCOMP auid=1000 uid=1000 gid=1000 ses=9 subj=? pid=32702 comm="eadedCompositor" exe="/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/WebKit>
авг 19 18:03:14 egorka-P5K audit[32702]: SECCOMP auid=1000 uid=1000 gid=1000 ses=9 subj=? pid=32702 comm="eadedCompositor" exe="/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/WebKit>
авг 19 18:03:14 egorka-P5K audit[32702]: SECCOMP auid=1000 uid=1000 gid=1000 ses=9 subj=? pid=32702 comm="eadedCompositor" exe="/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/WebKit>
авг 19 18:03:14 egorka-P5K audit[32702]: SECCOMP auid=1000 uid=1000 gid=1000 ses=9 subj=? pid=32702 comm="eadedCompositor" exe="/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/WebKit>
авг 19 18:03:14 egorka-P5K kernel: audit: type=1326 audit(1660914194.490:168): auid=1000 uid=1000 gid=1000 ses=9 subj=? pid=32702 comm="eadedCompositor" exe="/usr/lib/x86_64-l>
авг 19 18:03:14 egorka-P5K kernel: audit: type=1326 audit(1660914194.490:169): auid=1000 uid=1000 gid=1000 ses=9 subj=? pid=32702 comm="eadedCompositor" exe="/usr/lib/x86_64-l>
авг 19 18:03:14 egorka-P5K kernel: audit: type=1326 audit(1660914194.490:170): auid=1000 uid=1000 gid=1000 ses=9 subj=? pid=32702 comm="eadedCompositor" exe="/usr/lib/x86_64-l>
авг 19 18:03:14 egorka-P5K kernel: audit: type=1326 audit(1660914194.490:171): auid=1000 uid=1000 gid=1000 ses=9 subj=? pid=32702 comm="eadedCompositor" exe="/usr/lib/x86_64-l>
авг 19 18:03:14 egorka-P5K xdg-desktop-por[31148]: Realtime error: Could not map pid: Mapping pids is not supported.
авг 19 18:03:14 egorka-P5K audit[32702]: AVC apparmor="DENIED" operation="open" profile="snap.telegram-desktop.telegram-desktop" name="/sys/devices/virtual/dmi/id/chassis_type>
авг 19 18:03:14 egorka-P5K WebKitWebProces[32702]: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied
авг 19 18:03:14 egorka-P5K audit[32702]: AVC apparmor="DENIED" operation="open" profile="snap.telegram-desktop.telegram-desktop" name="/sys/firmware/acpi/pm_profile" pid=32702>
авг 19 18:03:14 egorka-P5K WebKitWebProces[32702]: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied
авг 19 18:03:18 egorka-P5K audit[32685]: AVC apparmor="DENIED" operation="open" profile="snap.telegram-desktop.telegram-desktop" name="/proc/zoneinfo" pid=32685 comm="Pressure>
авг 19 18:03:18 egorka-P5K audit[32685]: AVC apparmor="DENIED" operation="open" profile="snap.telegram-desktop.telegram-desktop" name="/sys/fs/cgroup/user.slice/user-1000.slic>
авг 19 18:03:18 egorka-P5K audit[32685]: AVC apparmor="DENIED" operation="open" profile="snap.telegram-desktop.telegram-desktop" name="/sys/fs/cgroup/user.slice/user-1000.slic>
авг 19 18:03:18 egorka-P5K audit[32685]: AVC apparmor="DENIED" operation="open" profile="snap.telegram-desktop.telegram-desktop" name="/sys/fs/cgroup/user.slice/user-1000.slic>
</pre>

## OS and compositor
<pre>
Ubuntu 22.04 LTS
Compositor - compton
</pre>

I turned to telegram desktop for help, but they sent me here
[https://github.com/telegramdesktop/tdesktop/issues/24953](https://github.com/telegramdesktop/tdesktop/issues/24953)

Telegram Web Apps work great with KDE Plasma, but I don't want to switch to this one

I would like to draw your attention to the error:
<pre>
WebKitNetworkPr[32699]: GDBus.Error:org.freedesktop.portal.Error.NotAllowed: This call is not available inside the sandbox. 
</pre>
It wasn't in KDE Plasma

**Comment by Airblader** [comment]
I see no reason whatsoever to assume that this has something to do with i3. Why would i3 be involved in any DBUS stuff? 

I'll convert this to a discussion because there's nothing to investigate on the window manager side of things.
