### ISSUE TITLE
Some applications stopped defaulting to "pixel" borders and keep titlebars with the "normal" mode since v4.21

### ISSUE THREAD

**Issue by QuentinFAIDIDE** [i3/i3#5163]
## I'm submitting a…
<pre>
[x] Bug
[ ] Feature Request
[x] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
When opening `code`(vscode open source fork) or `open-lens`, a titlebar appears at the top, which is not the case with other windows. The config file should default to the `pixel 0` border mode but isn't for these apps:
```
[...]
# set the default border mode to pixel
default_border pixel 0
default_floating_border pixel 0

bindsym $mod+Shift+b border normal
bindsym $mod+Shift+Ctrl+b border pixel 0
[...]
``` 
Using the above `bindsym $mod+Shift+Ctrl+b border pixel 0` removes the titlebar, but any new window for these applications will have it again.

## Expected Behavior
Given the config file, all `vscode` or Electron apps windows should be opened in `pixel` border mode and not `normal`. 

## Reproduction Instructions
Opening apps in with my config file and version, and try to open `code` or `open-lens` apps.

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.21 (2022-09-21) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.21 (2022-09-21) (pid 27808)
Loaded i3 config:
  /home/quentin/.config/i3/config (main) (last modified: dim. 25 sept. 2022 20:46:37, 105 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

-->
<details><summary>Config file</summary><pre>
https://pastebin.com/sNxzg478
</pre>
</details>

<pre>
- Linux Distribution & Version: Archlinux
- Are you using a compositor (e.g., xcompmgr or compton): picom (ex-compton)
</pre>

**Comment by Airblader** [comment]
#5149
