### ISSUE TITLE
i3-input problems with neo/neo_qwertz keyboard layout

### ISSUE THREAD

**Issue by jaypikay** [i3/i3#5214]
## I'm submitting a…
<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Having neoqwertz keyboard layout enabled, `i3-input` does not recognize the colon ":" or any other special characters the correct way.

## Expected Behavior
Using special characters to rename a workspace to `5:foobar`.

## Reproduction Instructions
Set keyboard layout to (`setxkbmap -layout de -model pc105 -variant neo_qwertz`)
```
model:      pc105
layout:     de
variant:    neo_qwertz
```
Run `i3-input` and press `Mod3+ö`.

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.21 (2022-09-21) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.21 (2022-09-21) (pid 1073)
Loaded i3 config:
  /home/user/.config/i3/config (main) (last modified: 2022-10-07T08:43:07 CEST, 891327 seconds ago)
  /home/user/.config/i3/assignments.conf (included) (last modified: 2022-10-14T09:37:07 CEST, 283287 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
Logfile URL: https://logs.i3wm.org/logs/6233660776775680.bz2
i3-input stdout Logfile URL: https://pastebin.com/pbGDsypg
</pre>

<pre>
- Linux Distribution & Version: Arch Linux 6.0.1-arch2-1
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by stapelberg** [comment]
The issue is that i3-input does not yet use libxkbcommon for proper keyboard handling. This is tracked in https://github.com/i3/i3/issues/1868, but I don’t use i3-input myself, so we’ll need a community contribution to get this fixed.
