### ISSUE TITLE
Potentially make the gaps configuration no longer order-sensitive

### ISSUE THREAD

**Issue by stapelberg** [i3/i3#5253]

**Comment by stapelberg** [comment]
@Airblader Can you describe (ideally with an example) in which way gaps config directive override each other? I’m not entirely sure I understand what this is about yet :) 

(This issue was created for your comment in https://github.com/stapelberg/i3/commit/3d1a8c4aae39eb13ccbe3db40a5d121056b72d9b#r88348691)

**Comment by Airblader** [comment]
I think that refers to [these lines](https://github.com/i3/i3/blob/next/src/config_directives.c#L307-L308):

```
    if (!strcmp(scope, "inner")) {
        if (workspace == NULL)
            config.gaps.inner = pixels;
        else {
            gaps.inner = pixels - config.gaps.inner;
            create_gaps_assignment(workspace, scope, gaps);
        }
    }
```

If you create a workspace gaps assignment, it depends on the global inner gaps you have previously configured, i.e.

```
gaps inner 10
workspace 1 gaps inner 10
```

and

```
workspace 1 gaps inner 10
gaps inner 10
```

are not equivalent.

**Comment by stapelberg** [comment]
Thanks! Sent https://github.com/i3/i3/pull/5259 to fix this
