### ISSUE TITLE
`output nonprimary` no longer works inside of `bar` config

### ISSUE THREAD

**Issue by djl** [i3/i3#5346]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
When a bar is configured with `output nonprimary`, it is not loaded.

## Expected Behavior
When a bar is configured with `output nonprimary`, it is shown on the non-primary outputs. This was working in 4.21.

## Reproduction Instructions
Use the default config and add a bar with `output nonprimary`. e.g.
```
bar {
    output nonprimary
    status_command i3status
}
```

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.22 (2023-01-02) ? 2009 Michael Stapelberg and contributors
Running i3 version: 4.22 (2023-01-02) (pid 438028)
Loaded i3 config:
  /home/djl/.config/i3/config (main) (last modified: Mon Jan  2 19:26:05 2023, 72 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

</pre>

<details><summary>Config file</summary><pre>The default config file.</pre>
</details>

<pre>
Logfile URL: https://logs.i3wm.org/logs/6214249000992768.bz2
</pre>

<pre>
- Linux Distribution & Version: Arch Linux
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

**Comment by valecs** [comment]
I'm seeing the same issue, on updating from 4.21 to 4.22

**Comment by teddybear** [comment]
Same for me, either without any compositor or with `picom`

**Comment by simontunnat** [comment]
I would really appreciate a bugfix release for this, as Arch Linux has already upgraded to version 4.22.

**Comment by simontunnat** [comment]
Arch Linux already has a patched version in the community-testing repos, so I do not care about the official release anymore. :D
