### ISSUE TITLE
workspace_auto_back_and_forth causes subwindows to appear on an unexpected workspace

### ISSUE THREAD

**Issue by pvutov** [i3/i3#5354]
## I'm submitting a…
[x] Bug

## Current Behavior
I have workspaces 8 (any content) and 9 (thunderbird). I go to workspace 8, then to workspace 9. I click the "write" button on thunderbird, which open a new window for writing an email. The window is opened on workspace 8 (or whichever workspace was active before switching to thunderbird).  

## Expected Behavior
The window should open on workspace 9, which is the active workspace.

## Reproduction Instructions
I am able to break the reproduction by removing ```workspace_auto_back_and_forth yes``` from my config. 
I also have ```for_window ... move container to workspace``` commands that are supposed to move windows to the correct locations (thunderbird to 9 etc) so I wonder if there might be an interaction between those two options that is causing this?

The issue does not only affect thunderbird subwindows, but also, for example, keepass. For example by going File->Database Settings.., which opens a new window on the previous workspace instead of the active one, same as thunderbird. It does not happen for all types of subwindows, for example if in keepass I go new->file, I get a floating warning window, which when confirmed spawns a file browser, and both of those new windows are on the correct workspace.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.22 (2023-01-02) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.22 (2023-01-02) (pid 3951)
Loaded i3 config:
  /home/fade/.config/i3/config (main) (last modified: Fri 06 Jan 2023 02:50:28 PM EET, 226 seconds ago)
  /home/fade/repos/home-master/.config/i3/workspaces.i3 (included) (last modified: Wed 14 Dec 2022 06:12:53 PM EET, 1975281 seconds ago)
  /home/fade/repos/home-master/.config/i3/hotkeys-apps.i3 (included) (last modified: Tue 03 Jan 2023 12:25:06 PM EET, 268148 seconds ago)
  /home/fade/repos/home-master/.config/i3/autostart.i3 (included) (last modified: Tue 03 Jan 2023 05:12:28 PM EET, 250906 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: /usr/bin/i3
</pre>

<details><summary>Config file</summary>
I was able to reproduce the thunderbird case by taking a default config file and appending:

<pre>
workspace_auto_back_and_forth yes
for_window [class="thunderbird"] move container to workspace 9
</pre>
</details>

Logfile URL: https://logs.i3wm.org/logs/6224008093630464.bz2
An example of the 8->9->write email->spawns on 8 can be seen at 01/06/2023 02:29:36. Seems to match the "for_window" command but then the thunderbird subwindow still spawns on the unfocused workspace 8.

- Linux Distribution & Version: Arch, 5.15.86-1-lts, last updated today
- Are you using a compositor (e.g., xcompmgr or compton): no

**Comment by Airblader** [comment]
> I also have for_window ... move container to workspace commands that are supposed to move windows to the correct locations (thunderbird to 9 etc) so I wonder if there might be an interaction between those two options that is causing this?

Yes, this is most likely the case. Try using `move --no-auto-back-and-forth` to avoid the auto-back-and-forth behavior for these commands.

**Comment by pvutov** [comment]
Thank you. Replacing 
```for_window ... move container to workspace n```
with 
```for_window ... move --no-auto-back-and-forth container to workspace n```
seems to allow me to keep the general auto-back-and-forth behavior while avoiding the subwindow issue.
