### ISSUE TITLE
Acquire the WM_Sx selection (enables --replace)

### ISSUE THREAD

**Issue by stapelberg** [i3/i3#536]
A window manager should acquire ownership of the WM_Sx selection. Handling this properly allows us to replace existing window managers and be replaced by other window managers.

See also:
http://tronche.com/gui/x/icccm/sec-4.html#s-4.3

**Comment by Airblader** [comment]
Just an FYI to anyone taking a shot at this, it is well worth looking into Openbox's source to see how this can be done.

**Comment by psychon** [comment]
Another hint could be the following commits. (Note that I know that awesome is not confirming to the spec, I don't see the point in jumping through all the necessary hoops just to get a current timestamp that can be used for acquiring the selection, so I just used `XCB_CURRENT_TIME`):
https://github.com/awesomeWM/awesome/commit/5a17b3978c7aafa720197f670c961aa8cd794dd6 https://github.com/awesomeWM/awesome/commit/19111121ce51e555ba92d1f10e4735d9c217f7ad
https://github.com/awesomeWM/awesome/commit/e824f8f30d3f797374f6597baf4fb70f48f51b25
