### ISSUE TITLE
Laggy application startup since few months

### ISSUE THREAD

**Issue by floriangit** [i3/i3#5407]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
 After a fresh login the very first application takes 10 seconds to load. Subsequent applications behave expected. It does not matter whether a slim application (terminal) or a big (firefox) is launched. It seems this is a regression since it is a new issue for me (roughly 2 months in the past I did not have the issue).

## Expected Behavior
 No lag.

## Reproduction Instructions
 Login, empty screen, launch e.g. Terminal via keyboard shortcut, need to wait 10 seconds.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: Binary i3 version:  4.22 (2023-01-02) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.22 (2023-01-02) (pid 1962)
Loaded i3 config:
  /home/mf/.config/i3/config (main) (last modified: Mon 12 Sep 2022 11:57:58 AM CEST, 12361516 seconds ago)
</pre>

<details><summary>Config file</summary><pre>
https://pastebin.com/w072bjhM
</pre>
</details>

<pre>
Logfile URL: https://logs.i3wm.org/logs/6237383158661120.bz2
</pre>

<pre>
- Linux Distribution & Version: Ubuntu 20.04
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by stapelberg** [comment]
I doubt this is i3-related. You can downgrade i3 to 4.21 or 4.20 to verify.

**Comment by floriangit** [comment]
I downgraded to 4.17.1 since that was the only option in my distro
(ubuntu). It did not solve the problem...Any ideas though? What happens
when I press meta-ENTER to launch a terminal?
1) the terminal executable is started
2) bash inside the terminal starts
So I guess I have to check my .bashrc and others?

Thanks!

**Comment by stapelberg** [comment]
It might be easiest to start with a fresh new user account on your computer and then add parts of your configuration until you notice the slowdown.

I’ll close this issue here as it’s not an i3 bug.
