### ISSUE TITLE
Restoring a layout is not working

### ISSUE THREAD

**Issue by TheShiningBoots** [i3/i3#5424]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

The layout fails to load with the following layout
```ERROR: Could not slurp "/home/theshiningboots/.config/i3/workspace_1.json".
[{"success":true},{"success":false,"error":"Could not slurp \"/home/theshiningboots/.config/i3/workspace_1.json\"."}]
```

## Expected Behavior

Layout loads correctly displaying 3 instances of alacritty in the following layout
``One main terminal occupying half the screen two others occupying half of the screen, each of which takes up half the vertical space``

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.22
</pre>

<details>Workspace.json<summary>
Config files
</summary><pre>
[
{
    "border": "normal",
    "current_border_width": 2,
    "floating": "auto_off",
    "geometry": {
       "height": 600,
       "width": 800,
       "x": 0,
       "y": 0
    },
    "marks": [],
    "name": "theshiningboots@archlinux:~",
    "percent": 0.5,
    "swallows": [
       {
         "class": "^Alacritty$",
         "instance": "^Alacritty$",
         "machine": "^archlinux$",
         "title": "^theshiningboots\\@archlinux\\:\\~$"
       }
    ],
    "type": "con"
},
{
    "border": "normal",
    "floating": "auto_off",
    "layout": "splitv",
    "marks": [],
    "percent": 0.5,
    "type": "con",
    "nodes": [
        {
            "border": "normal",
            "current_border_width": 2,
            "floating": "auto_off",
            "geometry": {
               "height": 600,
               "width": 800,
               "x": 0,
               "y": 0
            },
            "marks": [],
            "name": "theshiningboots@archlinux:~",
            "percent": 0.5,
            "swallows": [
               {
                 "class": "^Alacritty$",
                 "instance": "^Alacritty$",
                 "machine": "^archlinux$",
                 "title": "^theshiningboots\\@archlinux\\:\\~$"
               }
            ],
            "type": "con"
        },
        {
            "border": "normal",
            "current_border_width": 2,
            "floating": "auto_off",
            "geometry": {
               "height": 600,
               "width": 800,
               "x": 0,
               "y": 0
            },
            "marks": [],
            "name": "theshiningboots@archlinux:~",
            "percent": 0.5,
            "swallows": [
               {
                 "class": "^Alacritty$",
                 "instance": "^Alacritty$",
                 "machine": "^archlinux$",
                 "title": "^theshiningboots\\@archlinux\\:\\~$"
               }
            ],
            "type": "con"
        }
    ]
}
]
</pre>
Config file
https://pastebin.com/CxeBiypY

Restore.sh (the sh file I am running for the layout):
<pre>
#!/bin/sh 

exec i3-msg "workspace 1; append_layout ~/.config/i3/workspace_1.json"
(alacritty &)
(alacritty &)
(alacritty &)

</pre>
</details>

<pre>
Logfile URL: ``https://logs.i3wm.org/logs/6196627945553920.bz2`` (This will probably not do much)
</pre>

<pre>
- Linux Distribution & Version: ArchLinux theres probably no version for it but systemctl --version returns ``systemd 253 (253-1-arch)``
- Are you using a compositor (e.g., xcompmgr or compton): Yes, Picom
</pre>

**Comment by Airblader** [comment]
The error indicates that something went wrong [here](https://github.com/i3/i3/blob/a5da4d54f315e830e2a901b8e75ae7e478401c6e/src/util.c#L427) when reading the file. The log file will tell us a better reason, but I'm only on mobile right now so I can't check.

The obvious question would be: is the JSON file at the correct location and readable?

**Comment by TheShiningBoots** [comment]
Yes as of the location I am pretty sure its correct and its most likely readable (I have tried with sudo too), also a thing I would have to say is that it used to work with the placeholder watch icon a few hrs ago.

I use sudo bash ./restore.sh

**Comment by Airblader** [comment]
There's no need to mess around with sudo and it just means there's a chance you changed the file permissions, making it unreadable for i3. So one thing to do would be actually checking the permission flags of the file to rule that out.

**Comment by TheShiningBoots** [comment]
Ok will try

**Comment by TheShiningBoots** [comment]
Here running ls -l gives:
```total 20
-rw-r--r-- 1 theshiningboots theshiningboots 11078 Feb 19 17:16 config
-rwxr-xr-x 1 theshiningboots theshiningboots   126 Feb 19 14:23 restore.sh
-rw-r--r-- 1 theshiningboots theshiningboots  1986 Feb 19 14:19 workspace-1.json
```

**Comment by TheShiningBoots** [comment]
Also if I try running it from another workspace it does change it to workspace 1

**Comment by TheShiningBoots** [comment]
Well, restarting my system seems to have fixed it. Though it now shows watch icon placeholder

**Comment by Airblader** [comment]
Your match criteria are probably just unnecessarily restrictive, especially the title. If all three windows are empty and identical alacritty instances, just remove all match criteria other than the class. Edit: you can also keep machine if you use this across different devices and want behavior to be machine-specific, of course.

**Comment by TheShiningBoots** [comment]
Also is it possible for them to have a command already running? Thank you for guiding me, its my first time with linux

**Comment by Airblader** [comment]
> Also is it possible for them to have a command already running?

That depends on your terminal, not i3; check its documentation whether it allows running it with an initial command, but most do. Usually it's something like `-e`.

If that means your three Terminals will be different, and you care about which one is in which of the three spots, you'll need to make matching more specific again. Best way to do that would be using the instance and seeing if the terminal allows specifying a custom class/instance via another flag.

I'll close this since the original issue is resolved.

**Comment by TheShiningBoots** [comment]
Thank you very much for your help, much appreciated.
