### ISSUE TITLE
Some windows randomly become floating

### ISSUE THREAD

**Issue by AdamWysokinski** [i3/i3#5623]
## I'm submitting a…
<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Some windows randomly become floating.

## Expected Behavior

Windows should not change their state without user intervention.

## Reproduction Instructions

Unfortunately so far I was not able to find a way to reproduce the issue. I believe that it may refer to windows with tabs and happens when switching tabs as it almost exclusively happens to windows of Firefox, Sublime Text, Sublime Merge, in which I have tabs opened. This however also happens when switching to a particular window or reloading i3 config.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.22 (2023-01-02) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.22 (2023-01-02) (pid 2022)
Loaded i3 config:
  /home/eb/.config/i3/config (main) (last modified: Sat 12 Aug 2023 09:44:56 PM CEST, 61 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: x-sessio/i3
</pre>

<details><summary>Config file</summary><pre>
# i3 config file (v4)

set $mod Mod4

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font xft:Hack 12

# Use Mouse+$mod to drag floating windows to their wanted position
# floating_modifier $mod
floating_minimum_size 200x100

# start a terminal
bindsym $mod+Return exec kitty

# file lookup
bindsym $mod+l exec kitty -T Spotlight ~/Applications/spotlight.sh

# rofi
bindsym $mod+r exec rofi -show run

# rofi
bindsym $mod+s exec xsensors

# htop
bindsym $mod+h exec kitty -T htop htop

# kill focused window
bindsym $mod+Shift+q kill
set $close "Close the window? (Y/n)"
mode $close {
    bindsym y kill, mode default
    bindsym Return kill, mode default
    bindsym n mode default
    bindsym Escape mode default
}
bindsym $mod+q mode $close

# start dmenu (a program launcher)
bindsym $mod+d exec dmenu_run -fn 'Hack-14'

# change focus
bindsym $mod+Left focus left
bindsym $mod+Right focus right

# move focused window
bindsym $mod+shift+Left move left
bindsym $mod+shift+Right move right

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
workspace_layout tabbed
bindsym $mod+w layout tabbed

# toggle tiling / floating
bindsym $mod+space floating toggle

# reload the configuration file
bindsym $mod+shift+c reload

# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+shift+r restart

# exit i3 (logs you out of your X session)
bindsym $mod+shift+e exec "i3-nagbar -t warning -m 'Do you really want to exit i3?' -B 'Yes, exit i3' 'i3-msg exit'"

# kill window with MMB
bindsym --release button2 kill

# no border
hide_edge_borders smart

# start i3bar
bar {
        position top
        status_command i3status
        wheel_up_cmd nop
        wheel_down_cmd nop
}

# disable tiling drag (works in 4.21.1)
tiling_drag off

# make certain windows floating
for_window [title="Progress"] floating enable
for_window [title="Blender Preferences"] floating enable
for_window [title="xsensors"] floating enable
for_window [title="Choose one"] floating enable
for_window [title="EEGLAB"] floating enable
for_window [title="eegplot()"] floating enable
for_window [title="pop_"] floating enable
for_window [title="spectopo()"] floating enable
for_window [title="Error"] floating enable
for_window [title="Edit metadata"] floating disable
for_window [title="Convert"] floating disable
for_window [title="IP Range - Angry IP Scanner"] floating enable
for_window [title="Volume Control"] floating enable
for_window [title="Extension Manager"] floating enable
for_window [title="Simulation Progress"] floating enable
for_window [title="Position"] floating enable
for_window [title="GKS QtTerm"] floating enable
for_window [title="Enter value"] floating enable
for_window [title="Qalculate!"] floating enable
for_window [title="NeuroAnalyzer"] floating enable
for_window [class="Rox"] floating enable

for_window [floating] move position center

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"

# switch to workspace
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6

# move focused container to workspace
bindsym $mod+shift+1 move container to workspace $ws1
bindsym $mod+shift+2 move container to workspace $ws2
bindsym $mod+shift+3 move container to workspace $ws3
bindsym $mod+shift+4 move container to workspace $ws4
bindsym $mod+shift+5 move container to workspace $ws5
bindsym $mod+shift+6 move container to workspace $ws6

# assign windows to workspaces
assign [class="firefox"] $ws1
assign [class="calibre"] $ws2
assign [class="Signal"] $ws2
assign [class="transmission"] $ws3

# disable mouse wheel
bindsym button4 nop
bindsym button5 nop
bindsym button6 nop
bindsym button7 nop

# wallpaper
exec --no-startup-id feh --no-fehbg --bg-center ~/Documents/Pictures/lpd.gif

# screen shot
bindsym $mod+Print exec "scrot -o /tmp/scrot.png; gimp /tmp/scrot.png"

# run programs at startup
exec firefox
exec kitty
exec subl
exec smerge
exec jabref
exec transmission-gtk
exec calibre

# monitor
bindsym $mod+F7 exec xrandr --output eDP --off --output HDMI-A-0 --auto
bindsym $mod+shift+F7 exec xrandr --output eDP --auto --output HDMI-A-0 --off

# # lock screen
bindsym $mod+shift+l exec i3lock -c 000000

# calculator
bindsym $mod+c exec ~/.local/bin/qalculate

# audio controls
bindsym $mod+m exec kitty -T pulsemixer pulsemixer
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10% && $refresh_i3status
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10% && $refresh_i3status
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle && $refresh_i3status
bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @FAULT_SOURCE@ toggle && $refresh_i3status

# wifi
bindsym $mod+F8 exec nmcli radio wifi off
bindsym $mod+shift+F8 exec nmcli radio wifi on

# screen brightness
bindsym XF86MonBrightnessDown exec xrandr --output eDP --brightness 0.5
bindsym XF86MonBrightnessUp exec xrandr --output eDP --brightness 1.0
</pre>
</details>

Providing a logfile can help us trace the root cause of an issue much quicker. You can learn how to generate the logfile here:
https://i3wm.org/docs/debugging.html

Providing the logfile is optional.
<pre>
Logfile URL: https://logs.i3wm.org/logs/6320691846578176.bz2
</pre>

Please also answer the questions below to help us process your issue faster. If you have any other information to share, please add it here as well.

<pre>
- Linux Distribution & Version: Linux Debian Testing
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by orestisfl** [comment]
In the specific log file you provided, which window becomes unexpectedly floating?

Additionally, I notice that you have some rules that will apply to many windows, sometimes unexpectedly. 

For example,
```
for_window [title="Progress"] floating enable
```
will match a firefox window in which you are reading, for example, a dictionary page for the word "progress" or any webpage that has the word "Progress" in its title.

**Comment by AdamWysokinski** [comment]
In the log example it was Sublime Merge.

Regarding the rules, the issue happens randomly - sometimes when switching to another application window and sometimes when switching tabs within an application widow. However, I'll disable these rules and try again.
Also, I think this started since the last update. Or at least it happens more often than on the previous versions.

**Comment by orestisfl** [comment]
The Sublime Merge window is set to floating because it matches this rule:
```
for_window [title="NeuroAnalyzer"] floating enable
```

From the log:
```
08/12/2023 09:50:27 PM - Regular expression "NeuroAnalyzer" matches
"~/Documents/Code/NeuroAnalyzer.jl - Sublime Merge"
08/12/2023 09:50:27 PM - window title matches
(~/Documents/Code/NeuroAnalyzer.jl - Sublime Merge)
```

You'll need to add class criteria to these rules to not only match on
titles.

The reason it appears random is that each rule is only executed once per
window. Since you have rules that potentially match many windows in
different situations, they might trigger earlier and not re-trigger later.

**Comment by AdamWysokinski** [comment]
Man, you're right! How silly of me I forgot that title rules act as regexp. Thanks!

**Comment by AdamWysokinski** [comment]
Solved and closed.
