### ISSUE TITLE
i3 mostly not working (keys inputs, layouts, windows splits, etc)

### ISSUE THREAD

**Issue by WillianFuks** [i3/i3#5732]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When issuing commands, for instance, splitting the current window vertically - or horizontally - i3 doesn't work. Changing windows to new workspaces also is not working. Windows are opening not in full expansion and everything is slow with graphics in lower quality (when compared to gnome desktop for instance).

Here's a sample of me trying to split the window (`Alt + v` or `Alt + h`) but nothing works. The image "flickers" but nothing happens.

https://github.com/i3/i3/assets/4665485/6bafa3a9-af48-4cdc-a429-f234dcd8501d

## Expected Behavior

For what I could observe so far:
- Windows should split vertically / horizontally on key inputs.
- The environment is slow. It "freezes" at times. It should be fast and smooth.
- The quality of the images are lower, not sure what's wrong as well but it should be normal.
- Windows are opening in small size instead of full width/height available.

## Reproduction Instructions

I'm not sure if it's a bug or something is missing in my environment but as I tried everything and nothing worked I decided to ask for some help.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
Binary i3 version:  4.22 (2023-01-02) © 2009 Michael Stapelberg and contributors

Running version: < 4.2-200

</pre>

<details><summary>Config file</summary><pre>
Default initial config file. Nothing was changed.
</pre>
</details>

<pre>
Logfile URL: https://logs.i3wm.org/logs/6258625139965952.bz2
</pre>

For this log file I tried hitting Alt+v to see if anything would be revealed.

Linux Distribution & Version:

    Linux will 5.15.0-87-generic #97~20.04.1-Ubuntu SMP Thu Oct 5 08:25:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Are you using a compositor (e.g., xcompmgr or compton): No (I just installed i3 so I suppose those were not installed).

**Comment by orestisfl** [comment]
> Windows should split vertically / horizontally on key inputs.

Alt+v/h does not split the current window in any way, it creates a vertical/horizontal layout and the next window that opens will be placed accordingly.

> The environment is slow. It "freezes" at times. It should be fast and smooth.

This is not really quantifiable or actionable. A freeze is different than something being slow and would be a bug. Something being slow would need profiling data to debug.

> The quality of the images are lower, not sure what's wrong as well but it should be normal.

i3 does not control the resolution of your monitor or the content of the windows, is your resolution and graphics stack set up correctly?

What's the output of `xrandr --query`?

**Comment by WillianFuks** [comment]
Hi @orestisfl , thanks for the reply.

As for the output of `xrandr --query`:

```
Screen 0: minimum 320 x 200, current 3286 x 1080, maximum 16384 x 16384
eDP-1 connected primary 1366x768+0+0 (normal left inverted right x axis y axis) 309mm x 173mm
   1366x768      60.00*+
   1360x768      59.80    59.96  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   800x512       60.17  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   720x450       59.89  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   680x384       59.80    59.96  
   640x400       59.88    59.98  
   576x432       60.06  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
DP-1 connected 1920x1080+1366+0 (normal left inverted right x axis y axis) 509mm x 286mm
   1920x1080     60.00*+
   1600x1200     60.00  
   1680x1050     59.95  
   1280x1024     75.02    60.02  
   1440x900      74.98    59.89  
   1280x960      60.00  
   1280x800      59.81  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   640x480       75.00    72.81    66.67    59.94  
   720x400       70.08  
HDMI-1 disconnected (normal left inverted right x axis y axis)

```
Is there any setup that is still required? I searched on the docs but couldn't find yet what still has to be done.

As for the creation of new windows (Alt + v/h), even when I create new terminal windows (Alt + Enter) they seem to be just floating types. I couldn't make the stacking of windows or the tag view work so far (it's not behaving the same as in the official video tutorials for instance).

As for the slowness I mostly compared with gnome-desktop and then when I tried i3 I observed that browsing through a file or a web site was slower and had the "flickers / freezes" going on but didn't measure those indeed.

**Comment by WillianFuks** [comment]
I'm closing this as this doesn't seem to be a bug. Couldn't figure out what's happening so far but it all seems do indicate it's something related to my environment.
