### ISSUE TITLE
Weird focus behavior and mouse buttons stop working

### ISSUE THREAD

**Issue by jwueller** [i3/i3#6066]
### Welcome

- [X] Yes, I'm using the latest major release or the current development version. These are the only supported versions.
- [X] Yes, I've searched similar issues and discussions on GitHub and didn't find any.

### Current Behavior

I'm not entirely sure what causes this, but i3 seems to at least be a lowest common denominator so far. And it seems to temporarily go back to normal when I restart i3. Here are some very strange symptoms I am observing, not necessarily all of them at once though:

Some time after launching i3, focus starts to behave strangely, meaning I can click a title bar of another window with the mouse, it turns blue, but the focus doesn't actually switch. Typing anything still goes to the original window.

When dealing with a stacked/tabbed layout, I've observed an even stranger behavior that sometimes occurs: If I use the keyboard to switch from window A to window B in the same stack, and then click within the newly visible window B, it swaps back to the original window A.

Usually a little later, hover effects and all kinds of mouse input stop working for everything. I can still switch window focus using my keyboard shortcuts though.

But sometimes the mouse stays partially working within an application. For example, I'm typing this in Firefox right now, and I can still select text and click different inputs. But when moving focus out of Firefox, I can no longer type in here. But I can click and select text still. GitHub even applies the active styles to the input, but the window doesn't _actually_ have focus somehow. i3 shows the border as gray, and keyboard events instead go to the other window I moved focus to, or nowhere at all.

I did notice that both `libinput debug-events` and `i3-dump-log -f` both still log on mouse events, so clearly something must be going wrong when handling the events somewhere. Again, I'm not sure if this is i3, but I haven't been able to narrow it down to a specific application. It could also be X itself I assume.

I also noticed that `xprop` fails in this state, even if it's a partial one:
```plain
xprop: error: Can't grab the mouse.
```

I've also tried different mice, cables, USB ports, you name it. Doesn't make any difference.

Might this be similar to #2778?

### Expected Behavior

Focus behaves consistently.

### Reproduction Instructions

I've been trying to nail this down for three days now and haven't been able to. I clearly need help from people that know the ins and outs. I'll attach a log from this happening.

### i3 version

```text
Binary i3 version:  4.23 © 2009 Michael Stapelberg and contributors
Running i3 version: 4.23 (pid 1818)
Loaded i3 config:
  /home/johannes/.config/i3/config (main) (last modified: 2024-05-20T16:50:08 CEST, 1607 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

### Config file

I get this behavior with a completely auto-generated default config, as well as my custom one. So I assume it's not required to reproduce. It's very tedious to copy things right now, so I hope this is sufficient.

### Linux distribution & Version

Fully upgraded Arch as of 2024-05-20:
```plain
Linux kabutops 6.9.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 17 May 2024 16:56:38 +0000 x86_64 GNU/Linux
```

I've also tried rolling back the kernel, i3, and several other packages.

### Are you using a compositor?

I am sure I don't run any compositor (I usually use `picom` but this reproduces without it too).

### Logfile

https://logs.i3wm.org/logs/6201405291364352.bz2

**Comment by orestisfl** [comment]
Any chance you are running unclutter?

**Comment by jwueller** [comment]
Not that I'm aware. `pidof unclutter` gives no results. And I don't have the package installed either.

**Comment by jwueller** [comment]
I just got this _immediately_ after boot, logging in and only running `startx`. Here is what's in my `.xinitrc` currently:

```sh
#!/bin/sh

export XDG_CURRENT_DESKTOP=i3
export GTK_THEME=Adwaita-dark

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xset dpms 0 0 0
xset s off

xrandr \
    --output DisplayPort-2 --primary --mode 1600x1200 --pos 2560x1080 --rotate left \
    --output DisplayPort-4           --mode 1920x1080 --pos  320x0    --rotate normal \
    --output DisplayPort-6           --mode 2560x1600 --pos    0x1080 --rotate normal

lxpolkit &
#xbindkeys
xsetroot -solid "#000000"
#picom -b
nextcloud --background &
exec i3 --shmlog-size=26214400
```

First window that popped up (except the placeholder windows in my initial layout) was `lxpolkit`, which already didn't receive any mouse events while visibly having focus. After that was confirmed with Return, I opened Kitty by shortcut, and then Firefox to write this.

Currently typing in Firefox, but mouse events all go into the Kitty window (like scrolling) while keyboard stuff works completely as the i3 focus indicates.

I'm all out of ideas at this point. Here is a [new log](https://logs.i3wm.org/logs/6331613747085312.bz2) from just now.

**Comment by MachFour** [comment]
I'm having similar issues, following along. Can reproduce the `xprop: error: Can't grab the mouse` as well.

Interestingly, I am also on Arch and use Kitty and Firefox and picom. My work laptop has a Debian-based linux distro (also with kitty, firefox and picom) and is affected as well. 

It may be unrelated, but I've also noticed that in Firefox, I can't click on popup menus from add-ons (e.g. Dark Reader). The click just goes straight through to the page below.

**Comment by MachFour** [comment]
@jwueller It sounds crazy but have you tried using a different mouse?

I'm using a Logitech wireless mouse, and noticed that unplugging and re-plugging the USB receiver helped get the focus unstuck. After a bit of googling I found [this question on AskUbuntu](https://askubuntu.com/questions/1149436/mouse-cursor-becomes-trapped-focused-on-the-wrong-window) which sounds very similar to our situation, but not specific to i3.

Sure enough, using `xev` (and manually moving focus to the xev window), I could see that my mouse's middle click was triggering multiple times per click, and perhaps got stuck in a 'clicked' state. When this happens, i3 won't change window focus.

You can see the effect for yourself - open two terminal windows, click and hold the left mouse button in one of them and then drag the cursor to another window. The focus does not move to the second window for as long as the left mouse button is held down, even if you click the right mouse button in the second window.

`xprop`'s call of `XGrabPointer` also fails with `AlreadyGrabbed` if you try to run it while holding down a mouse button.

Switching to a cheap wired mouse has mitigated the issue for me for now. Hope this helps!

**Comment by jwueller** [comment]
@MachFour Great observation! That would certainly explain it.

I did in fact try a different mouse as stated in the initial post, but both of them were _also_ made by Logitech. :thinking: I guess it's possible that they are all broken in the exact same way, but what are the odds?

Either way, this doesn't sound like an i3 problem anymore at this point. So I guess I will close the issue until I can confirm that it's not a hardware issue. I have ordered a third mouse and will report back with the results!

**Comment by MachFour** [comment]
@jwueller ah, I missed that sentence where you said you had tried multiple mice.

I just discovered an even better tool for mouse testing `xev`, called `evtest`. Once you find which `/dev/input/eventX` file corresponds to your mouse, running `sudo evtest /dev/input/eventX` will print out a continuous stream of events from your mouse which will highlight any stuck buttons :) 

I guess this isn't strictly an i3 problem, but it does make me wonder how Windows/Mac OS/Gnome etc deal with this issue, since mice fail from time to time and I wonder whether their window managers are more 'forgiving' of stuck mouse buttons.

**Comment by jwueller** [comment]
@MachFour I logged the event stream with `libinput`, but I guess it's hard to notice a stuck state just from an event stream. I haven't been able to reproduce the problem with the new mouse, so it might actually have been a dual hardware failure. Now that's amazing timing.

**Comment by jwueller** [comment]
Also, I'm not sure if this might have contributed to the problem, but I did blacklist the `eeepc-wmi` module due to errors I was seeing in `dmesg`. I'm not sure why this module got loaded to begin with, since I'm not running an Eee PC.
